### PR TITLE
Revert "Update Ndef.schelp"

### PR DESCRIPTION
**Pull request by nuss**
Reverts supercollider/supercollider#2273

The amendments to the Ndef helpfile use a number of methods that are not available with the standard classlib. I guess they come from the JITLibExtensions quark. Possibly the changes could go into the quarks' helpfile?

### CODE REVIEW

**Comment by crucialfelix** [comment]
Sorry about that. Not familiar with the API there.

Maybe in this case since it is the NDef help file we could just put a comment there that says it requires the JITLibExtensions quark. Then they could see the code and the advantage it gives and it would give them a reason to install that.

But I'm fine with just reverting this here and @tiagmoraismorgado can submit that block to the quark.  Maybe that's simpler.

thanks

**Comment by nuss** [comment]
Never mind. I'm loosely following the discussions here but missed that pull request before it was merged. I've left some comments in the source commit source if that's useful for someone: https://github.com/supercollider/supercollider/commit/b30639489fb2f01c0f427dd8f3c668af7c8db3b1

**Comment by crucialfelix** [comment]
so addSpec and addPar are in class lib now ?  I'm confused

**Comment by nuss** [comment]
No, they are **not** part of the standard class lib. Didn't I say that?

**Comment by crucialfelix** [comment]
You said "never mind" -- vielleicht du hast "kein thema" gemeint.  

I thought you meant that you realized that #2273 is not a problem anymore.

but it is. let's revert

**Comment by nuss** [comment]
Sorry, that was a misunderstanding. I meant something like "Nicht so schlimm, man kann's ja rückgängig machen" (after you had apologized in the first place)

**Comment by crucialfelix** [comment]
Alles klar, wir sind rückgegangen.

**Pull request merged**
