### PR TITLE
Scide/theme mgmt fix

### PR DESCRIPTION
**Pull request by vdonnefort**
Hi,

Following our discussion with @miczac (https://github.com/supercollider/supercollider/pull/1150), here's some theme related fixes.

### CODE REVIEW

**Comment by vdonnefort** [comment]
Hi,

I just added a patch which fixes the warning "theme.hpp:0: Note: No relevant classes found. No output generated."

**Comment by miczac** [comment]
Hi, would be lovely to have this commits pulled! ;) thanks!

**Comment by bagong** [comment]
Not sure if this is the right place to comment, but I see the frame/focus rectangle that was removed in #1302 returned. On a retina display and Qt5 the frame now seems removed to the left two or three pixels. On the right side it keeps a bit of distance from the margin, on the left side it is invisible. Top and bottom are okay.

**Comment by vdonnefort** [comment]
@telephon @jleben @muellmusik This PR is needed for 3.7. Can you label it?

**Comment by bagong** [comment]
Or just merge and let testers find problems? In reality pull requests hardly get tested. This one (well, the one this builds upon) had more testing and discussion than most others. I have been using this a bit, seems to work fine. The one confusing thing I found is that you have to create a new theme, before you can change certain settings, but I guess that's by design? (try e.g. to change background color of "matching brackets" in the default settings - currently a hot issue :) )

**Comment by scztt** [comment]
:+1: to merge

**Comment by bagong** [comment]
Sorry, I found two more issues, one very small, the other one significant, but not necessarily directly related to your PR:
1. disabling the foreground button for 'current line' seems okay, although a bit normative. But then the color box (and the display example) should actually display the foreground color chosen for default text. That is currently not the case, both box and sample always display black.
2. the color picker (pipette) doesn't work. If you click it, nothing happens. After you close the preferences dialogue though, the cursor displays as magnifying glass in the editor (this is OS X 10.10.2/Qt5.4.1). Obviously the color picker was waiting for the dialogue to close :)

**Comment by vdonnefort** [comment]
@bagong: 

The behavior you're encountering is perfectly normal: the "current line" is not used and so is disabled: https://github.com/vdonnefort/supercollider/commit/83e84909dacafe5e713d540fd1fcdf6c969615f6

**Comment by bagong** [comment]
Yes, that's not my point.

Any comments on the color picker?

**Comment by vdonnefort** [comment]
@bagong @scztt @miczac Do you agree if instead of disabled foreground options I hide them?

**Comment by bagong** [comment]
Well, I don't want to be too picky, so let somebody else make a judgement. I'll just say that in that case the text sample to the left will still display black as foreground color, regardless of the actual default Text color, so the user will still be confused. But there certainly are more pressing issues. So from my side up to your own judgement.
Would you please say if the color-picker thing is connected to your contribution? If not, I will file a general issue.

**Comment by vdonnefort** [comment]
@bagong, when I make this contribution I've been asked for disabling these unused options. But the fact that the foreground is not used is not related to this PR.

**Comment by bagong** [comment]
Let me try to be clearer: There are two issues.
1. GUI-feedback for the user to *see* if she likes her choices. She can chose fore- and background for default text, see the colors in the boxes, and see the resulting text-background-combination with a sample in the large selection box. This doesn't work in the case of "Current line" where as foreground color always black is displayed, regardless of the color chosen for default "Text". This could make the user think, the "Current Line" can only display black as foreground color. Try to imagine somebody who has no idea of the implementation.
2. The color-picker *pipette* issue: if you click on the color-box for fore- or background, the the system color picker will open. At the left bottom it displays a color box that shows the color you have chosen. To it's right there is a icon resembling a pipette. If you click it, you should be able to pick up a color from the graphical environment. The cursor will change into a magnifying glass to enhance the precision of your color-"pick". This is quite useful, but it doesn't work in the context of the preferences dialog, the functionality is dead. Instead you get the cursor shaped as magnifying glass when you close the preferences dialog. This is a proper and reproducible bug - but it might not be related directly to your pull-request. I am asking for a comment on exactly that question.

I am sorry, I won't be able to comment further on this, have to run...

**Comment by bagong** [comment]
So I took the time to check in blank master: both issues are there as well. I'll file two issues and think this should be merged.

**Comment by telephon** [comment]
@bagong So we should merge and then treat these issues separately?

**Comment by bagong** [comment]
Yes, I've already filed issues.

**Comment by crucialfelix** [comment]
let's merge now, confirm ?

**Comment by vdonnefort** [comment]
Yes

**Comment by crucialfelix** [comment]
Damn we need some structure around here. Over a year to merge a PR ? I just merged a shit tonne of pull requests.

**Comment by vdonnefort** [comment]
And I'm thankful for that, these are bugfix and should have been merged on time for 3.7.

**Comment by crucialfelix** [comment]
There was such an incredible backlog it was hard for me to go through so
many issues and PRs.
3.7 was more about shipping what was already done and merged.
3.8 comes June 1

On Thu, Mar 17, 2016 at 5:34 PM Vincent Donnefort <notifications@github.com>
wrote:

> And I'm thankful for that, these are bugfix and should have been merged on
> time for 3.7.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/pull/1297#issuecomment-197963009>
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Pull request merged**
