### PR TITLE
cmake: turn off -ffast-math for gcc

### LINKED ISSUE #4116: Compiling in release with gcc 8.2 causes FP math issues
Environment
-----------

* Your SuperCollider version: 3.9.3 (installed from the comunity repositories of arch)
* Your operating system and version: Arch Linux 

Steps to reproduce (for bugs)
-----------------------------

```supercollider
(0/0).isNaN
// Please paste SuperCollider code here.
// It really helps if you try to simplify your example as much as possible.
```

Expected Behavior
-----------------
returns true

Current Behavior
----------------
returns false

isNaN is implemented by testing < and > of 0  ... and these tests are already not behaving as expected.

### PR DESCRIPTION
**Pull request by brianlheim**
Purpose and Motivation
----------------------

This causes fp math to behave incorrectly
Instead, enable optimizations for the worst offenders (no signaling nan, no math errno)

Fixes #4116

Types of changes
----------------

- Bug fix (non-breaking change which fixes an issue)
- Breaking change (possibly, needs evaluation)

Checklist
---------

- [x] All tests are passing
- [x] If necessary, new tests were created to address changes in PR, and tests are passing
- [x] Updated documentation, if necessary
- [x] This PR is ready for review

Remaining Work
--------------

Tests should be run after building with this change to ensure nothing
else in the main language test suite has broken as a result of this
change.

### CODE REVIEW

**Comment by brianlheim** [comment]
Since only Linux builds are supported for GCC, I've tagged this os: Linux.

**Comment by brianlheim** [comment]
May also be worth checking if there is a performance impact from this.

**Comment by patrickdupuis** [comment]
This Gist lists UnitTest pass/fail on SC 3.10-beta2 [259275abc]. I get identical results on this branch.

One thing I worry about it how this change will affect embedded devices. I can try and test on Rpi.

**Comment by brianlheim** [comment]
I think this has been tested as thoroughly as we can ask for in development, no issues found, let's ship it :)

**Comment by patrickdupuis** [comment]
@snappizz you good with this?

**Pull request merged**
