### PR TITLE
[WIP] expose parse tree to sclang

### PR DESCRIPTION
**Pull request by lnihlen**
## Purpose and Motivation

Reformatted version of #4402.

## Types of changes

- Documentation
- New feature

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

### CODE REVIEW

**Comment by telephon** [comment]
Excellent. Just curious: will you be able to backtrack the text (line number etc.) that is the source code for a given object?

**Comment by lnihlen** [comment]
> Excellent. Just curious: will you be able to backtrack the text (line number etc.) that is the source code for a given object?

Yup. There's some preliminary documentation in the PR, but the tl;dr is that you'll get back a parse tree. Not all nodes in the parse tree are necessarily *printing* nodes, meaning nodes that have a direct relationship with some substring in the input source string. I haven't propagated line/col numbers yet and have been focused only on character offset, but those data are readily available to the compiler and should be relatively easy to pipe through to the language.

**Comment by brianlheim** [comment]
@lnihlen planning to review this in the next day or two. just making sure, are you planning to continue work on this?

**Comment by lnihlen** [comment]
Not in the foreseeable future. I lost momentum, and in terms of sclang style validation it seems like it wasn't as needed as I had thought.

**Comment by brianlheim** [comment]
> Not in the foreseeable future. I lost momentum, and in terms of sclang style validation it seems like it wasn't as needed as I had thought.

that's too bad! i'm going to save this branch on my local repo, it could be useful for some interpreter-oriented work @scztt and i wanted to do. thanks for getting it started!

**Comment by telephon** [comment]
Yes, this would have been (would be still) very useful for linking objects to their code.

**Pull request closed without merging**
