### PR TITLE
Merge CommonTests into testsuite/classlibrary

### PR DESCRIPTION
**Pull request by snappizz**
Sorry this is so large. I used `git subtree add` to preserve the commit history.

This does not update Travis yet, nor does it include CommonTestsGUI.

Please note that this PR is **not** merging CommonTests into the core class library. It is merging CommonTests into a separate directory in the core repository that must be installed voluntarily. The only effect is that code and tests are now in the same repository to align with standard practice.

### CODE REVIEW

**Comment by snappizz** [comment]
hi

**Comment by vivid-synth** [comment]
lgtm

**Comment by scztt** [comment]
This shouldn't be merged unless the UnitTest quark is merged into the core library as well, else none of this code will compile. And - the UnitTest class has a bunch of serious issues that need to be fixed before it's at a quality level that's good enough for being part of e.g. a 3.9 release.

Any reason not to do a submodule instead of pulling the entire repo history? Wouldn't that achieve roughly the same thing?

**Comment by josiah-wolf-oberholtzer** [comment]
@scztt Is there an issue tracker for the UnitTest quark?

**Comment by snappizz** [comment]
@josiah-wolf-oberholtzer https://github.com/supercollider-quarks/UnitTesting/issues

@scztt

> This shouldn't be merged unless the UnitTest quark is merged into the core library as well, else none of this code will compile. And - the UnitTest class has a bunch of serious issues that need to be fixed before it's at a quality level that's good enough for being part of e.g. a 3.9 release.

I picked a directory that is not part of the core class library, because this is not part of the release nor is it intended to be run by users. The only change here is putting the test code and the class code in the same repository so that a single PR can simultaneously make a change and add a test for it. Submodules wouldn't solve that problem.

Developers who want to run the tests need to install the UnitTest quark and install the testsuite/classlibrary/ directory manually, but users are unaffected.

**Comment by josiah-wolf-oberholtzer** [comment]
Keeping tests in the same repository as the code their testing is a good idea, otherwise there's a structural impediment against matching code changes with test updates.

If there are serious issues with the UnitTest quark, but nothing in the issue tracker for that quark, where can I find information on what exactly is broken?

**Comment by vivid-synth** [comment]
@scztt ^^

**Comment by snappizz** [comment]
:tada:

**Pull request merged**
