### PR TITLE
class library: remove fade in for function play

### PR DESCRIPTION
**Pull request by telephon**
`fadeTime` was never intended to be a fade in, only fade out for release
– it was just wrong. This PR fixes it.

### CODE REVIEW

**Comment by snappizz** [comment]
Can you fix the docs, too?

**Comment by jamshark70** [comment]
I have doubts about this, but, eh, whatever.

**Comment by jamshark70** [comment]
Note that Daniel Mayer has also objected to this on the users mailing list.

We're not quite at consensus to merge this.

**Comment by snappizz** [comment]
For posterity, list discussion is here: http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/play-fade-td7625901.html

**Comment by telephon** [comment]
Yes, agreed. Just a suggestion. Just note that there was no fade originally (early versions of sc3), and I implemented it (IMO) incorrectly.

**Comment by snappizz** [comment]
I was ambivalent about this before, but I agree with James and Daniel Mayer now. It's an API change and not a necessary one. Some novice SC code even uses Function:play in serious contexts, and even if it's a bad practice, we don't want to mess with one of the most visible features in all of SuperCollider. I vote to close.

**Comment by telephon** [comment]
I'd really like to see one or two real examples of code that would click. Then I'm happy to close :)

**Comment by vivid-synth** [comment]
Even ```play { PlayBuf.ar }``` is likely to have clicks at the beginning if the buffer starts non-zero, no?

**Comment by telephon** [comment]
@vivid-synth yes, but buffers for playback usually don't start non-zero, do they?

**Comment by vivid-synth** [comment]
I'm thinking about e.g. recording a buffer with ```SoundIn``` then playing it back -- you might get a click at the beginning and end, depending on the value of ```SoundIn``` when recording started

**Comment by telephon** [comment]
I see. Yes this may happen in existing code. 

If we keep the current behavior, what should we do about the endless occasions where someone tries `{ Impulse.ar(1) }.play` and misses the first trigger (or even `{ Impulse.ar(0) }.play` and misses the only trigger?

**Comment by vivid-synth** [comment]
@telephon can you give an example of when this would be used? Typically impulse is used to control something else, right?

I don't have a strong opinion on keep/remove. I agree it probably should be based on the change's effect on code in the wild (e.g. how many helpfile examples or user code would start with a click, vs how many problems there are with e.g. playing Impulse).

**Comment by brianlheim** [comment]
From the helpfiles:
`{LFNoise0.ar(1000, 0.25) }.play`
`{ LFNoise1.ar(1000, 0.25) }.play`
```supercollider
play({
    VarSaw.ar(
        LFPulse.kr(3, 0, 0.3, 200, 200),
        0,
        LFTri.kr(1.0).range(0,1), //width
        0.1)
}
```
(VarSaw.schelp)

All of these click or have the potential to if you make fade time 0.

Everyone's learned that .play is the safe convenience function you use while prototyping. Since most people are voting to close, I'm closing this.

**Pull request closed without merging**
