### PR TITLE
[enhancement] - supercollider/supercollider/helpsource/search.html - improving indentation of the overall html document

### PR DESCRIPTION
**Pull request by tmm2018**
[enhancement] - supercollider/supercollider/helpsource/search.html - improving indentation of the overall html document

### CODE REVIEW

**Comment by tmm2018** [comment]
hey brian. thank you so much for approving my PR. you didn't approve other similar PRs to this one. is there something I can do to improve the quality of my contributions?

thank you so much, a lot of light to you
peace

**Comment by jamshark70** [comment]
> is there something I can do to improve the quality of my contributions?

In the last batch, Brian already explained: "The indentation is incorrect on this and the other PRs I just closed. Please use tabs in schelp and sc, 4 spaces everywhere else."

This is the biggest problem here: people give you advice but you don't act on it. If you want to improve the quality, read the feedback carefully and then put it into practice.

**Comment by tmm2018** [comment]
hi @jamshark70 you are absolutely right. i just didn't understand the problem was concerning tabs. reason why i didn't fix it immediately. my honest and deep apologies. i will fix this right now and not do it again

**Comment by tmm2018** [comment]
hi @jamshark70 now i have gotten confused. is there something else i should fix, in this specific post? if so, please let me know. anyway sorry for cross(/re)-posting

**Comment by jamshark70** [comment]
Your question (italics by me):

> you didn't approve *other similar* PRs to this one. is there something I can do to improve the quality of my contributions?

So I answered the question why *other* PRs weren't approved and made a general suggestion.

Your question was not about this PR, so my answer was not about this PR.

If this PR was approved, then it's fine.

**Comment by tmm2018** [comment]
i already took that in mind and making an effort in that regard

**Pull request merged**
