### PR TITLE
3.11 Rewrite Server's wait method using Condition.

### LINKED ISSUE #4942: Server's `wait` method doesn't wait inside a Routine.
## Environment

* SuperCollider version: 3.11.0
* Operating system: Arch Linux 5.6.2
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
Server.default.boot;

(
SynthDef(\sendMsg, { |time = 3|
	var line;

	line = Line.kr(0, 1, time, doneAction: Done.none);

	SendTrig.kr(Done.kr(line));
	// SendReply.kr(Done.kr(line), '/name');

	0.0
}).add;
)

(
var server = Server.default;
var time = 2;

Routine({
	var synth;

	synth = Synth.basicNew(\sendMsg, server);

	server.sendMsg(*synth.newMsg(args: [\time, time]));

	"Synth started.".postln;

	server.wait('/tr');
	// server.wait('/name');

	"Stopped after % secs?\n".postf(time);

	server.sendMsg(*synth.freeMsg);
	
}).play;
)
```

## Expected vs. actual behavior
Currently, the `Routine` instance doesn't wait for server's message. 
`Server`'s `wait` method is defined as (lines 763 - 768):
```supercollider
wait { |responseName|
		var routine = thisThread;
		OSCFunc({
			routine.resume(true)
		}, responseName, addr).oneShot;
}
``` 
I think that a line with
```
nil.yield
```
_after_ the OSCFunc, is all that is required.

### PR DESCRIPTION
**Pull request by tsmtzs**
## Purpose and Motivation
`Server`'s `wait` method is defined as
```supercollider
wait { |responseName|
		var routine = thisThread;
		OSCFunc({
			routine.resume(true)
		}, responseName, addr).oneShot;
	}
```
Currently, `wait` doesn't pause the running thread. This PR proposes
a fix using a `Condition` to pause and resume the thread. It is based on discussion for #4942.

It follows a similar pattern found in `Server`'s `sendMsgSync` and `bootSync` methods. Specifically, we have
```supercollider
wait { |responseName|
	var condition = Condition.new;
	OSCFunc({
		condition.test = true;
		condition.signal
	}, responseName, addr).oneShot;

	condition.wait
}
```

Fixes #4942.
## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by jamshark70** [comment]
I won't object to the use of `test` and `signal` -- my comments in the attached issue are just an opinion, not that strongly held.

But it does look like there was a bit of branch confusion here, accidentally pulling a hundred or so unrelated commits. I'm not sure if you can fix it by rebasing and force pushing, or if it's necessary to start again.

**Comment by geoffroymontel** [comment]
Hello @tsmtzs, thanks for the PR !

It seems your commit was made on your local 3.11 branch, which is not recommended as now the PR shows way too many files changed and commits, making it too difficult to review.

Could you put your changes on a new topic branch forked from develop branch ?

Please see the chapter "Updating your fork" in [this page of the WIKI](https://github.com/supercollider/supercollider/wiki/Creating-pull-requests) 

Best

**Comment by tsmtzs** [comment]
Oops!
Apologies for all this mess. I'll create a new topic branch and make a new PR.

**Comment by geoffroymontel** [comment]
Thank you !!!

**Pull request closed without merging**
