### PR TITLE
Fix problem with boost interprocess module on Win

### PR DESCRIPTION
**Pull request by llloret**
See issue #2409.

Applied patch as suggested by Valentin Shtronda. See
https://svn.boost.org/trac/boost/ticket/12137.

### CODE REVIEW

**Comment by bagong** [comment]
Argh, unfortunately it creates a new error. `Exception in World_New: boost::interprocess::intermodule_singleton initialization failed` is gone, but now we get:

````
Booting with:
  In: MME : Microphone (Parallels Audio Con
  Out: MME : Speakers (Parallels Audio Contr
  Sample rate: 44100.000
  Latency (in/out): 0.013 / 0.091 sec
SC_AudioDriver: sample rate = 44100.000000, driver's block size = 64
SuperCollider 3 server ready.
Receiving notification messages from server localhost
Cannot connect to shared memory: The system cannot find the file specified.
ERROR: Primitive '_ServerShmInterface_connectSharedMem' failed.
Failed.
RECEIVER:
Instance of ServerShmInterface {    (0000020201BAD5B8, gc=04, fmt=00, flg=00, set=02)
  instance variables [2]
    ptr : nil
    finalizer : nil
}

PROTECTED CALL STACK:
	Meta_MethodError:new	000002027808B200
		arg this = PrimitiveFailedError
		arg what = Failed.
		arg receiver = a ServerShmInterface
	Meta_PrimitiveFailedError:new	00000202780917C0
		arg this = PrimitiveFailedError
		arg receiver = a ServerShmInterface
	Object:primitiveFailed	0000020237A7D340
		arg this = a ServerShmInterface
	a FunctionDef	0000020278CEE400
		sourceCode = "<an open Function>"
	Routine:prStart	0000020278706D80
		arg this = a Routine
		arg inval = 96.2407462

CALL STACK:
	MethodError:reportError   000002027945DAE8
		arg this = <instance of PrimitiveFailedError>
	< closed FunctionDef >   00000202010AF488
		arg error = <instance of PrimitiveFailedError>
	Integer:forBy   000002027926ACB8
		arg this = 0
		arg endval = 0
		arg stepval = 2
		arg function = <instance of Function>
		var i = 0
		var j = 0
	SequenceableCollection:pairsDo   00000202012E8C48
		arg this = [*2]
		arg function = <instance of Function>
	Scheduler:seconds_   00000202013E44F8
		arg this = <instance of Scheduler>
		arg newSeconds = 97.0567341
	Meta_AppClock:tick   000002027922F658
		arg this = <instance of Meta_AppClock>
		var saveClock = <instance of Meta_SystemClock>
	Process:tick   000002020155C6D8
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_ServerShmInterface_connectSharedMem' failed.
Failed.
RECEIVER: a ServerShmInterface
`````

**Comment by llloret** [comment]
Weird! I'll try to find out what's going on.

**Comment by llloret** [comment]
It works for me. Can you try rebooting and trying again? I am wondering if
there is a leftover from the previous run or something.

I can't think of any way that the patch would break it like that (but the
patch is not mine, and I haven't played with it a lot, so it might be)

**Comment by bagong** [comment]
If I reboot, the missing event will be recreated and the change will not be effective, right? The error I posted only only occurs after deleting the system log. Did you try that? The patch just covers the case where no event with ID 6005 is available in system log, if I understand correctly.

**Comment by llloret** [comment]
Yes, I did that. Can you reboot, and then delete the logs, and then execute scsynth?

**Comment by bagong** [comment]
Yep, will do.

**Comment by bagong** [comment]
Hmm, I still get that error.
I checked the `ProgramData\boost_interprocess` folder, and I get two subfolders now with different numbers, of which only one contains the file. That file used to have a speaking name, something like SuperCollider_57110 if I remember correctly. It's named `7CB97FCE2A34D201A6CFDC362B34D20150080000FFFFFFFF` now... Could I have done something wrong with the merge, or should I do a clean build... I'll continue trying these options...

**Comment by bagong** [comment]
Ah, wait, I only get that problem when starting the server from the IDE. When starting from the command line, it seems to boot fine. I also only get a single folder containing the file, and it's called SuperColliderServer_57110

**Comment by telephon** [comment]
maybe check in Server.sc what this line produces:

`pid = unixCmd(program ++ options.asOptionsString(addr.port))`

and try to do the same in the terminal?

**Comment by llloret** [comment]
It is working for me when launching from the IDE...

**Comment by telephon** [comment]
(organisational): do you by any chance have a new windows binary that can be tried out? If this branch needs testing, this may be the quickest and safest way, because many may not have the toolchain in place.

**Comment by bagong** [comment]
I am getting mixed results now, sometimes it boots, sometimes it produces the error. Building on another machine now. I'll will upload binaries later, might be interesting for Sonic Pi people too, who are still flooded with boot error reports on Windows. Thanks for your input @telephon , also the pid stuff in server.sc, I'll try that later today.

**Comment by bagong** [comment]
I've tried this on a second system now, a slightly aged Lenovo with latest Win10 64-bit, using the 64-bit sc build. Same result: I get the error, not always, but more often than not. My build is from latest 3.8 with Luis' PR on top.

The server start string is `scsynth.exe -u 57110 -a 116 -i 2 -o 2 -b 1026 -H "ASIO : ASIO4ALL" -R 0 -C 0 -l 1`

Changing to MME makes no difference.

No error using it on the command line...

I'll upload two builds in a while and then have a look if I see anything in the debugger. But with my limited knowledge that's unlikely to be of much use.

Note that it works fine without deleting the System.log

**Comment by bagong** [comment]
I've uploaded 64- and 32-bit Visual Studio builds into the 3.8-beta1 release page. The filenames have appended TEST-server-boot.

Note that I once had to boot the server three times to trigger the error, but once it occurred it happened repeatedly. Then again it worked as it should. So you might need a bit of patience when trying.

**Comment by bagong** [comment]
Thanks for reporting @xi-bot , we'll try to find out tomorrow, if it's my build or what the reason for the remaining unreliability is.

**Comment by llloret** [comment]
So, I think it would be a good idea to pull this into the 3.8 release. It seems to solve all the cases when launched from the command-line, and some of them when launching from the GUI.

That way it will get some exposure, and I can have more data to fix in all cases (I am suspecting a race condition, or something like that).

But the important thing is that it does not break anything that was not broken before.

What do you think?

**Comment by bagong** [comment]
This seems not to cleanly solve all problems for server boot from the IDE, but it solves a (rare) boot problem for server only use cases and enhances the situation for the use case with IDE. This is only relevant for Windows. So - also thinking of our Sonic Pi friends - I think this should go in for 3.8.

**Comment by bagong** [comment]
Just for posterity ;) : Sonic Pi does still get errors related to this.

**Comment by llloret** [comment]
Hi, I have been having a look at this, and I don't understand why it is happening. I cannot reproduce it. Can someone reading this reproduce it, so that we can try to run some tests to try to find the possible cause?

As far as I can see Valentin's boost patch that I applied should take care of the original problem (well, in fact it seems to work in 99% of cases... :)). Just need to find what's happening to the remaining 1%.

**Comment by bagong** [comment]
I can still trigger a shm-interface related server boot error, by rebooting many times, at some point it'll happen. But on my stem it's currently not easy to trigger it... what seems most urgently needed is a way to reproduce it reliably... no joy yet.

**Pull request merged**
