### PR TITLE
[class library] new _FileDeleteAll primitive

### LINKED ISSUE #3651: An additional Argument for File.delete
Hi,

I have noticed that File.delete("pathName") only deletes an empty folder.
```supercollider
File.mkdir(PathName(thisProcess.nowExecutingPath).parentPath+/+"test")

File.delete(PathName(thisProcess.nowExecutingPath).parentPath+/+"test")
// it posts "-> true" in the post window and deletes the folder "test".
```
Would it be not useful if we have an additional argument to delete a folder which is not empty?
```supercollider
File.delete(pathName, delete_a_not_empty_folder: 0)
// the second argument: delete_a_not_empty_folder
// 0: default. File.delete deletes only an empty folder.
// 1: File.delete deletes not only an empty folder but also an not empty folder.
```
e.g.:
```supercollider
File.mkdir(PathName(thisProcess.nowExecutingPath).parentPath+/+"test1/test2")
// File.mkdir can make even a folder in a not existing folder!

File.delete(PathName(thisProcess.nowExecutingPath).parentPath+/+"test1")
// will not delete the folder "test1".

File.delete(PathName(thisProcess.nowExecutingPath).parentPath+/+"test1", 1)
// will delete the folder "test1" as well as the folder "test2".
```

### PR DESCRIPTION
**Pull request by mkb218**
Purpose and Motivation
----------------------

Recursive delete of a pathname. Fixes #3651.

Types of changes
----------------

- New feature (non-breaking change which adds functionality)

Checklist
---------

- [x] All tests are passing

- [x] If necessary, new tests were created to address changes in PR (and tests are passing)

- [x] Updated documentation, if necessary

- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
Thanks @mkb218 ! This code is clear and stylistically perfect.

My concern with this approach is that any error message coming from `remove_all` is hidden. To make this method orthogonal with the other `File` operations, I'd recommend:

- use the non-`error_code` version of `remove_all`, so that encountered errors will be caught and reported by the runtime
- set the return value using the `bool` return value of `remove_all`.

I think this addition is fine without a test; we currently don't test filesystem operations and I think unless we run into anything significantly annoying, it's more trouble than it's worth. So I've marked this as OK on the test requirement.

Please also add documentation in `HelpSource/Classes/File.schelp`.

If you have any questions, let me know!

**Comment by mkb218** [comment]
I think I've implemented your recommendations, but now this method's return value is inconsistent with `File.delete`

**Comment by brianlheim** [comment]
@mkb218 That's fine, thanks for the changes! Could you also update the documentation with information about the error throwing conditions?

**Comment by brianlheim** [comment]
Overall looks good, but I think you accidentally committed some changes to hidapi as well, can you please revert that and then I'll approve this?

**Comment by mkb218** [comment]
Oops! Hang on while I try to get git to forget about that.

**Comment by mkb218** [comment]
OK, I think this is ready!

**Comment by mkb218** [comment]
No problem! I'll just squash it into a single commit?

**Comment by snappizz** [comment]
yes, i think that would be appropriate here.

**Comment by mkb218** [comment]
@snappizz should be all set now

**Comment by prko** [comment]
thank you!

**Pull request merged**
