### PR TITLE
SuperColliderAU update

### PR DESCRIPTION
**Pull request by g-roma**
SuperColliderAU has not been maintained for a long time, and does not work with recent SC versions. This PR updates the code in platform/mac/SuperColliderAU so that it compiles and runs from the current develop branch, into current AudioUnits hosts. Apple's CoreAudio Utility Classes are also updated to the latest version. 
A cmake script is provided for compiling within the SuperColliderAU directory. The only change outside this directory involves ensuring that the asio thread and io service  in SC_ComPort.cpp are only created and destroyed once (startAsioThread and stopAsioThread), so that multiple threads can create independent scsynth server instances in the same process.

### CODE REVIEW

**Comment by brianlheim** [comment]
Hey @g-roma - thanks for the work! Could we have some of this code as a submodule? I am hesitant to make a 50k LOC addition to this repo.

**Comment by brianlheim** [comment]
Actually, I'm not sure why this needs to be included here at all. Couldn't we just list the Core Audio SDK as a build dependency?

**Comment by brianlheim** [comment]
Actually, are these files downloadable from some public location? Then we could just list them as a dependency.

**Comment by g-roma** [comment]
Hi, I think some files in the CoreAudioUtilityClasses,  were included at some point in the CoreAudio SDK and then taken out. They are currently available here
https://developer.apple.com/library/content/samplecode/CoreAudioUtilityClasses/Introduction/Intro.html.
However, historically these releases were not as consistent as it may seem, and we decided to include all files that were needed. In the current repo they are under AUSDK. In principle they are provided not as a consistent framework but as a bunch of "example code" that happens to make your life much easier for developing AudioUnits.  
It could be removed which means that compiling SCAU would require downloading this from Apple (and hoping they don't disappear, change location etc). It could also be reduced to the strictly necessary files (which is what is now AUSDK).

**Comment by brianlheim** [comment]
OK! I'll bring it up at the developer meeting tomorrow (which you are welcome to attend). My feeling is that it would be better to provide this as a submodule. That way it can be maintained/updated separately and devs can avoid downloading it unless they need to build this specific project.

**Comment by g-roma** [comment]
OK I've moved CoreAudioUtilityClasses to a submodule (please ignore the review request, I clicked a suggestion by mistake). This should not change much, it mirrors a release from 2014. Unfortunately I can't attend developer meetings these days, I should be able next week.

**Comment by g-roma** [comment]
OK, since the submodule will not likely change in the near future, I hope it does not create too much trouble, it could be removed and re-added later if needed. Surely nothing else than SuperColliderAU depends on it. It is only convenient to have it so that building does not require everyone to re-download the code.

**Comment by brianlheim** [comment]
@g-roma Thanks for reworking it! Do you know if there's anyway we can set up tests for this code so that it doesn't fall out of service again?

**Comment by g-roma** [comment]
Hi, I think building it and running auval onthe AudioUnit bundle should be quite easy to do in Travis and would help a lot keeping it solid, I can take a look one it has a stable home...

**Comment by brianlheim** [comment]
Closing this in favor of #3540 & #3529

**Pull request closed without merging**
