### PR TITLE
Fix gc issues

### PR DESCRIPTION
**Pull request by muellmusik**
Following the discussion in #1476, here is a PR with proposed fixes for a number of possible GC issues. Some of these seem fairly straightforward, but I am not 100% sure that every call to GCWrite is required.

Please review these *carefully*.

### CODE REVIEW

**Comment by muellmusik** [comment]
Hmm, just noticed the annoying whitespace inconsistency. Thank you Xcode...

Review as is, and I'll fix any approved commits before merging.

**Comment by muellmusik** [comment]
@timblechmann Thanks for your comments, I'm away for a couple of days now but will deal with this soon.

One query: I assume it is best practice to run the GC on an allocation where possible to do safely (collect = true)? A strict exception should be utility functions which include allocations since we cannot guarantee that the enclosing function will handle things correctly, and it makes allocation opaque? These should be false, correct?

**Comment by timblechmann** [comment]
yes: in general it is best to collect on allocation ... or not to skip the collection too often. if it is, the collection might pause the interpreter a bit longer once it is run, but this should not be a real issue ...

when we cannot guarantee that all objects are reachable, disabling the allocation seems to be the safest way to ensure gc correctness

**Comment by muellmusik** [comment]
Okay thanks. I will update the help file on Writing Primitives to make this and other things clearer.

**Comment by muellmusik** [comment]
This has been replaced by PR #1618.

**Pull request closed without merging**
