### PR TITLE
Topic/coremidi crash fix

### PR DESCRIPTION
**Pull request by scztt**

### CODE REVIEW

**Comment by crucialfelix** [comment]
What's the best way to test this ? create a midi responder and recompile the library, repeat vigorously ?

**Comment by crucialfelix** [comment]
arg. this is so old that it won't build with my current up to date qt5 sc set up.

**Comment by telephon** [comment]
> Regardless, I don't see any reason why we can't just carry it over between Library rebuilds.
A library rebuild is supposed to behave exactly like a restart of sclang, so maybe better not.

**Comment by scztt** [comment]
@telephon - You're right - but, this is seemingly a problem with the CoreMIDI API's, so there's no other option to avoid the crash. AFAICT once we've called MIDIClientDispose, we can't call MIDIClientCreate again. In lieu of a specific problem happening because of the client re-use, it seems better to opt for avoiding the crash....

**Comment by scztt** [comment]
@crucialfelix - I saw this all the time in a workflow that looked like: (a) compile lang (b) create and init client (c) use midi, (d) recompile (e) repeat..... In an afternoon of working, I would see this crash ten or twelve times - not on every recompile, but it was not uncommon either.

**Comment by scztt** [comment]
@crucialfelix - I just updated this branch but didn't see any merge conflicts or anything - what's the build problem you're seeing?

**Comment by crucialfelix** [comment]
I've experienced the bug myself in the past. Very happy to see a potential
fix.

If I check out the branch I couldn't just build it because I have to switch
my qt, clean build, set cmake the same way we used to do it. The new build
system is much nicer

Or we just merge it and test in master.

**Comment by scztt** [comment]
I'm okay with merging and testing in master - I would consider this a safe fix. @telephon - can you merge if you're okay, or else let us know if there are any problems related to reusing the MIDI client?

**Comment by telephon** [comment]
I don't use MIDI, so I can't test. But I think this fix for now is better than nothing.

**Comment by redFrik** [comment]
@scztt many thanks for fixing this longstanding issue.

i can confirm that it is now fixed.  in my previous build (21c661b) and earlier it was easy to crash sc with...
```
MIDIClient.init
//recompile
MIDIClient.init
//crash -> 'Interpreter has crashed or stopped forcefully. [Exit code: 0]'
```
and you'd get this even without any midi gear connected.
with latest build it doesn't crash.  thanks again.

**Comment by crucialfelix** [comment]
All Hail @scztt Exterminator of The Bug !

**Pull request merged**
