### PR TITLE
Fix nodeproxy fadetime init 3

### PR DESCRIPTION
**Pull request by telephon**
Cleaned up commit history from the messed up #4065.

Sorry, all in one commit now, but I couldn't get it done otherwise.

### CODE REVIEW

**Comment by brianlheim** [comment]
@telephon this should not be so troublesome for us. I would like to help you figure out what is going wrong but unless you provide details about the commands you're executing and their results I can't give any advice.

**Comment by brianlheim** [comment]
And it looks like this branch has merge conflicts, so you will probably have to redo it anyway...

**Comment by telephon** [comment]
This requires #4090, which is why the checks fail. Should I wait until these have been cherry picked? I'm sorry, I don't know how the procedure is now. I've very urgent things to do, so I just squeezed this in between because it seemed really important. But the process with git already took me more time than the fix itself.

**Comment by brianlheim** [comment]
Superceded by #4114

**Pull request closed without merging**
