### PR TITLE
class library: BusPlug play can take bus object

### LINKED ISSUE #2138: Error when playing a Ndef in a multichannel bus object
SC 3.7.2.
If you use ~bus.index or no multichannel, there is no error, but with the two, I get:

```
(
~bus = Bus.audio(s,2);
Ndef(\test, { arg freq=200, pan=0, amp=0.1;
    var sig;
    sig = SinOsc.ar(freq);
    sig = Pan2.ar(sig, pan, amp);
//}).play(~bus); // OK
//}).play(~bus.index, 2); // OK
}).play(~bus, 2); // error
);




ERROR: binary operator '+' failed.
RECEIVER:
Instance of Bus {    (0xc936e90, gc=5C, fmt=00, flg=00, set=03)
  instance variables [5]
    rate : Symbol 'audio'
    index : Integer 38
    numChannels : Integer 2
    server : instance of Server (0xb93ea10, size=50, set=6)
    mapSymbol : nil
}
ARGS:
Instance of Array {    (0x9544450, gc=58, fmt=01, flg=00, set=03)
  indexed slots [2]
      0 : Integer 0
      1 : Integer 1
}
   nil
CALL STACK:
        DoesNotUnderstandError:reportError   0x9663410
                arg this = <instance of BinaryOpFailureError>
        Nil:handleError   0xc69e2b0
                arg this = nil
                arg error = <instance of BinaryOpFailureError>
        Thread:handleError   0xcfc3a90
                arg this = <instance of Thread>
                arg error = <instance of BinaryOpFailureError>
        Object:throw   0xcfc0610
                arg this = <instance of BinaryOpFailureError>
        Object:performBinaryOpOnSomething   0xab09d5f0
                arg this = <instance of Bus>
                arg aSelector = '+'
                arg thing = [*2]
                arg adverb = nil
        BusPlug:playToBundle   0xccf7330
                arg this = <instance of Ndef>
                arg bundle = <instance of MixedBundle>
                arg out = <instance of Bus>
                arg numChannels = 2
                arg group = nil
                arg multi = false
                arg vol = nil
                arg fadeTime = nil
                arg addAction = nil
        BusPlug:play   0xbd844d0
                arg this = <instance of Ndef>
                arg out = <instance of Bus>
                arg numChannels = 2
                arg group = nil
                arg multi = false
                arg vol = nil
                arg fadeTime = nil
                arg addAction = nil
                var bundle = <instance of MixedBundle>
        Interpreter:interpretPrintCmdLine   0xc2c5710
                arg this = <instance of Interpreter>
                var res = nil
                var func = <instance of Function>
                var code = "
(
~bus = Bus.audio(s,2);
Nd..."
                var doc = nil
                var ideClass = nil
        Process:interpretPrintCmdLine   0xcefa800
                arg this = <instance of Main>
^^ The preceding error dump is for ERROR: binary operator '+' failed.
RECEIVER: Bus(audio, 38, 2, localhost)
```

### PR DESCRIPTION
**Pull request by telephon**
This fixes #2138.

### CODE REVIEW

**Comment by telephon** [comment]
there was a reason why this was labeled "work in progress - don't merge yet". 

I'll explain: say, you have an 8 channel proxy and you pass a 3 channel bus object you might expect this to play the 8 channels on the 3, or not? But it will play 8 channels and not 3.

**Comment by brianlheim** [comment]
I was wondering about that, but there didn't seem to be any obvious reason not to merge—it wasn't explained in the initial PR submission, and this fixed the case from the linked issue. The only info given was that "this fixes #2138", which it did, so I merged it. We only changed one line here, so not a big deal either way.

**Comment by brianlheim** [comment]
@telephon let me know what I should do to fix this; I'm sorry it got merged early. I'll take whack at it this weekend if you weren't planning to touch it.

**Comment by telephon** [comment]
No problem. I'll have a look this weekend, I'm not sure if there is an elegant solution though.

**Pull request merged**
