### PR TITLE
Add an 'endPos' argument to PlayBuf

### PR DESCRIPTION
**Pull request by vivid-synth**
**I'm new to this kind of SC work so this could definitely use a thorough code review!**

Adds an 'endPos' argument to PlayBuf (discussed on the mailing list a while back). Loops back to beginning (not 'startPos') when reaches the end if ```loop = true```, otherwise does ```doneAction```

### CODE REVIEW

**Comment by Sciss** [comment]
My main question would be: is scsynth these days bug-free when the UGen is instantiated by a client that does not know about the new input. In other words, does the UGen get a safe default sixth input if the SynthDef says it has five inputs? If not, then I think such a safety check should be implemented first.

**Comment by Sciss** [comment]
My other concern is that this UGen is already quite complex. What does this add that cannot be done using `BufRd` instead? Isn't `BufRd` a good choice for when you must notice the arrival at a particular buffer frame?

**Comment by vivid-synth** [comment]
@Sciss in my informal tests (just using ```playBuf``` from Vivid, which doesn't yet know about the new 6th argument), it works properly.

**Comment by vivid-synth** [comment]
Regarding ```BufRd``` : among other reasons, it's a giant pain when you're working with files longer than a minute or so - indexing with floats gets fuzzy and the audio starts to sound terrible. PlayBuf internally uses a double for phase.

**Comment by Sciss** [comment]
But do you _know_ that it gets a default value? Where from and which one? There is a discrepancy between the help doc that specifies `-1` as default and special value, and the plugin code that seems to rely on `> 0`, perhaps falling back gracefully if the slot is initialised to zero. Do we have a guarantee that it become zero? (Some other devs might want to chime in here, if they know how this behaviour is defined)

**Comment by Sciss** [comment]
I don't buy that argument. Then `BufRd` should be improved by giving double precision as well. This is an implementation detail, that alone doesn't justify API change IMHO.

**Comment by vivid-synth** [comment]
@Sciss I'd love to find a nice way to use double-precision for ```BufRd``` but SC uses only single-precision floats between UGens (so, e.g., the output from ```Phasor``` that's the input to ```BufRd```). Everything I've thought of as a solution is fairly gross.

**Comment by vivid-synth** [comment]
I would also love to hear from another dev about the certainty of the 6th value being defaulted properly!

**Comment by jamshark70** [comment]
@Sciss:

> Then BufRd should be improved by giving double precision as well

It's a nice thought, but PlayBuf's double-precision frame index is internal, so it's easy. BufRd gets it from outside, so if it's to be double, then there are really two choices:

- Change scsynth to use double precision everywhere, with a currently unknown performance cost.

- Or, make specific UGen inputs double and leave the rest single, and certain UGens may then output double, and UGens cast as needed. That would have an unknown performance cost *and* be fraught with complication. (Math ops would have to adapt to single or double output depending on the inputs, for instance.)

Either way, all cases would suffer a performance hit to support one specific case (playing back from large buffers). That is not a decision to take lightly.

**Comment by vivid-synth** [comment]
Another thing worth discussing: if ```startPos``` is non-zero and ```endPos``` is set, does it really make sense to loop back to frame 0? I can't imagine a time where that's the desired behavior.

**Comment by jamshark70** [comment]
Or... on second thought, wouldn't it be better to make a new, proper looping buffer player that does a crossfade at the loop point? From an audio engineering perspective, it's almost always wrong to jump back without a transition (and if you really wanted that anyway, a crossfade looper could let you set the crossfade duration to 0).

I mean, instead of hacking PlayBuf. Part of the problem here is the assumption that PlayBuf is "the" buffer player and should be expected to do everything... maybe PlayBuf should just be the simple one-shot player.

**Comment by alln4tural** [comment]
+1 for a new LoopBuf 

.. and a discussion in the docs highlighting the differences and use cases for the various buffer Ugens. As a longtime, though admittedly over-casual, user of these, I never fully grokked when it's better to use which.

**Comment by Sciss** [comment]
I agree with James that the cleanest solution is to introduce a new UGen, tuned towards a specific use case, e.g. including the possibility to cross-fade.

**Comment by vivid-synth** [comment]
Is the argument backwards compatibility? Since PlayBuf already has a ```loop``` argument, why not add crossfade there? If we add a ```LoopBuf``` separately and leave ```PlayBuf``` "broken" in this regard, there's just another case for users to use the wrong UGen for the job because they haven't heard of the non-"broken" one.

Also: I presume we're only crossfading AR output? KR output is often control values.

Also: an ```endPos``` argument is still an uncontroversial addition, correct?

**Comment by Sciss** [comment]
I'm a big fan of atomicity; unit generators should be units, not macroscopically large. `PlayBuf` and `RecordBuf` for me are already borderline with respect to the number of switches and conditional behaviour. One should encourage combining smaller UGens. I understand the position argument can't get fixed without fixing the 32-bit limitation inside scsynth. Still, I'm not particularly sympathetic of adding even more stuff to existing UGens.

**Comment by vivid-synth** [comment]
@Sciss In general, I agree with you. Still, we already *have* a ```loop``` argument for ```PlayBuf``` and a ```startPos``` argument. Unless we're planning to deprecate ```loop``` and ```startPos``` (which I don't think we should), I think we should "finish the job" instead of leaving ```PlayBuf``` sort of broken/unfinished.

**Comment by brianlheim** [comment]
I agree with @vivid-synth here about `endPos`. There's no good reason for there to be a `startPos` and no `endPos`. I'm less convinced about the crossfading part; I tend to think of that as an atomically separate functionality than reading from a buffer, even though it would of course be really convenient to pack it all in one object.

**Comment by joshpar** [comment]
PlayBuf has worked this way for (almost) decades. A new UGen that doesn't break existing code would make much more sense.

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by vivid-synth** [comment]
@joshpar when you say we should keep existing behavior are you referring to not adding crossfade on loopback or to making the loopback to zero instead of to startPos? (Or both?)

For the latter, my question would be, has anyone actually used loop and startPos together? (In other words, actually wanted start-in-the-middle-then-jump-to-beginning behavior)

**Comment by vivid-synth** [comment]
My concern is, the proposed ```LoopBuf``` UGen seems just as packed with features as we're criticizing ```PlayBuf``` for being. Is the proposal just to leave ```PlayBuf``` as-is and copy-paste all that C++ to ```LoopBuf```, with minor changes?

**Comment by Sciss** [comment]
My proposal is to not proceed with anything until it's clear that the change doesn't break existing code: That loading a synth-def with 5 args behaves correctly (and not by chance, but by definition of the UGen allocation process). And yes, there may be code that starts in the middle of the buffer and then uses loop to jump back to the beginning of the buffer. It is not reasonable to change this behaviour IMHO.

**Comment by Sciss** [comment]
A work-around for the latter issue might be to ensure startPos can be modulated, and so previous behaviour can at least be emulated by changing the startPos from x to zero when the UGen begins.

**Comment by snappizz** [comment]
I'm with @Sciss. If you add new arguments, you can get [disastrous consequences](https://github.com/supercollider/supercollider/issues/2363) if the client and server versions are out of sync. Sure, an outdated client is an outdated client, but this is one of the most popular UGens ever. I recognize this isn't a really strong argument, but it's probably best to leave PlayBuf alone.

Introducing a new UGen that overcomes the limitations of PlayBuf and BufRd is a great idea.

**Comment by vivid-synth** [comment]
Surely arguments have been added to UGens before -- how was it handled then?

**Comment by joshpar** [comment]
It has been very rare, and not with UGens that have been around since 1.0. We added an arg to the Grain UGens a cycle after they came out, and the next release had all sorts of 'OMG your code will break horribly with these UGens! Change it all!!!' 
This is new functionality, and calls for a new UGen, especially since it would break so much historical code. I'd rather copy and paste and add new functionality to a new UGen, giving users a new option, without breaking any code. 

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by snappizz** [comment]
I've opened a new issue at #2600 to work on designing the new UGen. Should we close this?

**Comment by vivid-synth** [comment]
It looks like our hands are tied because it's not safe to add a new UGen argument, but I'd like to make the points:

  - Copy-pasting code isn't free: it adds burden of maintainership
  - Maintaining backwards compatibility isn't free: it litters the code and docs with the carcasses of unused and "seemed like a good idea at the time" stuff, which is a burden on the users and devs

In this case, let's build a new UGen. But I think -- as a broader philosophy -- we need to be willing to deprecate and change things (with a long deprecation cycle) even if they've been widely used in the past

**Comment by Sciss** [comment]
The work that needs to be done first is, in my eyes, to make the server more error-prone and handle the case gracefully where a UGen is instantiated with less arguments than it has in the current version, e.g. by setting extra args to zero, or by refusing to instantiate the synth...

**Comment by jamshark70** [comment]
> handle the case gracefully where a UGen is instantiated with less arguments than it has...

This is a matter of SynthDef topology, so it should be checked upon receiving/loading a SynthDef, not upon `/s_new`. I think...? Because the check would be looking for UGens that do not supply something for every input.

If a def supplies a channel from a Control unit to a certain UGen's input and the default value in the Control does not make sense, that's a totally different issue.

**Comment by telephon** [comment]
Adding arguments at the end has been common practice in sc since a long time. We shouldn't bind our hands even more than they are already. But maybe we can make use of the problem in a positive way. If there is a json list of the specs of every ugen arg (both as args of the ugen class method and the mapping to the synthdef inputs), we might have gained a lot of predictability and flexibility.

**Comment by Sciss** [comment]
@telephon Adding arguments to UGens has produced horrible bugs, because the _server_ currently doesn't handle "obsolete" SynthDefs. Before _that problem_ is fixed, I strongly vote against introducing this scenario.

**Comment by telephon** [comment]
@Sciss ah good to know, I've never seen one. Maybe that could be done in a new version of SynthDef.

But also I wouldn't want to keep old SynthDef files around anyway without their corresponding source code. Actually SynthDef files should have their source code in the header.

**Comment by Sciss** [comment]
"Old" SynthDefs are produced as a "feature" when client version doesn't match server version. Unless we can easily install different server versions in parallel, this is a real issue. `LocalIn` was one of those cases. I think `DC` was another one. `Pitch` was another one. Replacing `LinLin` by a pseudo-UGen was another one.

**Comment by telephon** [comment]
>"Old" SynthDefs are produced as a "feature" when client version doesn't match server version. 

Sorry, can you explain?

**Comment by Sciss** [comment]
@telephon Say you have the latest release version of ScalaCollider (1.22.3) installed, which assumes you are using an scsynth from 3.6.x to 3.8.x. Now there are API changes between 3.6.x and 3.8.x, and perhaps the user even builds 3.9.x from source. There is thus a discrepancy in the API between client and server at some point. Currently, the server does not gracefully handle this discrepancy. It is not feasible to tie one version of ScalaCollider (or Overtone or Sonic Pi or ...) to exactly one version of scsynth.

**Comment by vivid-synth** [comment]
@Sciss https://github.com/supercollider/supercollider/issues/2544 might help with making sure server versions are correct

**Comment by Sciss** [comment]
@vivid-synth yes, but... I cannot and do not want to force any user of any of my libs to use exactly the same SuperCollider version as I happen to be using at the moment. And I cannot maintain forks of my own system, the amount of work is just out of proportion. I think people should appreciate better compatibility in a widely used system such as SuperCollider. It doesn't mean we cannot evolve and fix bugs, it means we have added responsibility for overseeing the consequences of our modifications.

**Comment by snappizz** [comment]
Even if client developers are diligent, API changes still suck.

**Comment by vivid-synth** [comment]
True! But usually API changes are for a reason, and being unable to make any changes also sucks.

**Comment by Sciss** [comment]
Then to remove the suck, work on the server safety first. I'm starting to feel stupid to repeat myself over and over again.

**Comment by vivid-synth** [comment]
@Sciss I'm not disagreeing with you.

**Comment by Sciss** [comment]
I give a counter example: the `[ /done, /notify ]` message was altered to include an additional argument. That's an API change. I had my system broken because I was waiting for a message with two args. Ok, not cool, but I can fix it easily in a way that my updated client works both with the old and new server. One has to do a cost evaluation for each of those changes, some can be mitigated, others - unfortunately - require more fundamental work. If that work is too difficult - I can't do it, and probably most others neither - then we have to find a good compromise. Introducing a new UGen is a good compromise.

**Pull request closed without merging**
