### PR TITLE
Topic/fix dependency versions and case problems

### PR DESCRIPTION
**Pull request by scztt**
This pr:
- fixes a bunch of bugs related to differing cases in quark names (i.e. "Arduino" versus "arduino")
- enables parsing of dependencies of the form "quarkname@version", as well as just enabling version-based dependencies in general (which were not working).

### CODE REVIEW

**Comment by scztt** [comment]
@crucialfelix - Yes. There are at least three or four cases in the default quarks set. Try installing "Arduino" first and then "SWMiniBee" - you'll get two arduino quarks installed, and an error when you recompile. And, it's really easy to get this in practice too - all it takes is accidentally specifying a dependency as e.g. "UgenPatterns" instead of "UGenPatterns" to introduce the problem.

**Comment by scztt** [comment]
Removed case-sensitivity stuff - that requires more conversation.

**Comment by crucialfelix** [comment]
okay thanks, now I understand what the problem is.

I think the dependencies should be case sensitive and should fail to be
found and fail accordingly.  The quark file should be fixed.

**Comment by crucialfelix** [comment]
As discussed, these issues were fixed in my other PR. So we can close this one now. keep the branch around for a bit though.

**Pull request closed without merging**
