### PR TITLE
help browser: ignore comments in evaled code

### PR DESCRIPTION
**Pull request by htor**
fixes: #4536 + some code cleaning. 
forgot to ignore tokens in comments! see this line for relevant change: https://github.com/supercollider/supercollider/pull/4541/files#diff-7da91e28b100e42c97a82a4b6730051eR84

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
Thanks @htor! For future reference please create separate commits (or PRs) for code formatting, this makes it much much easier to review and also keeps commit history clean.

**Comment by htor** [comment]
> Thanks @htor! For future reference please create separate commits (or PRs) for code formatting, this makes it much much easier to review and also keeps commit history clean.

will do! i suggest we use https://standardjs.com/ for formatting JS. it's widely used and simple to enforce. maybe adding that to the wiki on code formatting would be helpful and i could re-format all .js files on a separate pr.

**Comment by brianlheim** [comment]
actually, can you please undo the formatting altogether and just submit the minimum change to fix this issue? I cannot tell what has changed vs what is reformatted and i didn't realize you had reformatted the entire file.

as dicussed on Slack, i am not opposed to enforcing style but it needs to be done in CI as well.

**Comment by htor** [comment]
@brianlheim no, i haven't actually reformatted the code, but refactored it while fixing the bug. i've corrected a minor indentation error introduced in the commit which made it look like i formatted a big chunk, so it should be perfectly readable now

**Comment by joshpar** [comment]
@htor - while @brianlheim stated it isn’t a priority for him to implement, it is part of what we would need to have happen for accepting this. Brian isn’t the lone voice of SC, and there are others who can help review or point you in the direction for how to implement the CI features that are required. I saw the convo on slack, or we can continue it here as well.

**Comment by htor** [comment]
i'll just leave this pr as is. if it's not

**Comment by brianlheim** [comment]
@htor -- (and for the record) what I said in Slack was: 

> if you really want to do this, you will need to:
> 1. format all .js files in the project in a single commit
> 2. add a step to CI that installs npm, installs standard, lints .js files, prints the diff, and fails if there is a diff. this step should happen immediately after clang-format runs

[...]

> you will have to figure that out on your own. sorry, i have no interest in this since it seems like there will be a very minimal benefit

I did not say that I am opposed to it, and you are simply wrong to take it that way. If you decide to contribute to SC again in the future -- and I would be happy to see it -- then I suggest you find a more mature way to respond to criticism.

**Comment by htor** [comment]
> If you decide to contribute to SC again in the future -- and I would be happy to see it -- then I suggest you find a more mature way to respond to criticism.

i've been happy contributing to this project in the past and i'm not new to hacking on open source projects. this is my professional job these days. when people tell me to change some bits and pieces in a pr, or ask me to provide more context in an issue – that's fine - it's usually for the better. 

but, when conributing to supercollider my questions are often met with short dismissive comments, negativity and ignorance by you – one the few maintainers – @brianlheim. maybe it's based on your ideal way of behaving "professionally" as maintainer (the BDFL/linus syndrome anyone?) or just based on the insecurity from the lack of your knowledge about web programming. either way, i'm amazed how much energy you spend on various channels working _against_ the people in the community and the contribs from them. i've seen it many times, you make people do a lot of uncessary re-work just to please your idiotic OCD and to assert your control. 

it's not a problem that i re-factor my code while fixing a bug. that's normal. you invented a problem there out of thin air, like you have done many times in the past. rather than taking time to actually read the pr you complain and nitpick about splitting changes into multiple commits to keep the commit history clean? well, just squash my pr then! problem solved. i even went a step further to contribute (to the project and to my future self) by informally suggesting on slack that we tell people to format their code in certain way. i regret that. you went through all the trouble of writing down all the steps needed to do that using CI (not what i was suggesting) before concluding that the whole thing was unimportant to you. why bother answering my request at all when you clearly won't collaborate?

if you think you are being mature, well then you are wrong. just because you've gained write permissions to this repository doesn't mean you're always right and it certainly doesn't mean you should treat people like shit.

i was planning to contribute more to supercollider, take ownership over the help browser front-end, hack on the new website, etc., but i've changed my mind now.

**Comment by jamshark70** [comment]
I read down through Brian's last reply in the morning, and this thread has been troubling me all day. (I apologize in advance -- I'm sure I will be told this is the wrong place for this discussion. But this is where the discussion, at the moment, *is*, so...)

Some years ago, SC's development community was organized in such a way -- and here, I will deliberately state it in the most cynical way possible -- that it was very good for contributors' egos, but not so good for the software and as a result not so good for the user community. Developing was "fun." *Using* SC -- making music with it -- was not. In 2016, I was seriously considering dropping SC altogether. After 14 years. I didn't, because 14 years, but seriously -- I was finding new catastrophic bugs basically every 3-4 weeks. That's bad.

It's almost single-handedly Brian's efforts that have brought more consistency and stability to the product. Last week, I took SC into a bar and played for an hour, and I had complete confidence in the software. SC is fun again. One might call it OCD, but the quality improvement is concrete.

It's incredibly difficult to tell a group of volunteers that their work is not good enough. But, objectively, for most of the 2010s, our work *was not good enough*. (I can point to specific commits that were obviously never tested, even locally, before going in -- "that 'should' be OK" was the rule.) Brian has been far more skillful at this than I could ever have been. That doesn't mean there have never been any bumps on the road (this is a pretty big pothole), but the bad has to be measured on balance with the good.

(WRT to this specific conversation -- "a couple of diff lines" are not a big deal. But, consider that 5 minutes' extra difficulty in reviewing a PR *times 50 open PRs* comes to 4 hours' burden on reviewers.)

With that said, as SC development was becoming more "officialized," I was one of those who had a hard time with the adjustment, and I acted this out in some ways that were not good for me or the community. I regret that I didn't understand it well enough to express it in a helpful way -- but, lately I understand that underneath the acting out was a concern about what would happen if SC development processes became too bureaucratic.

A week or two ago, Victor commented that a delay on merging one of his patches was "Kafkaesque." Today, a skilled contributor has become alienated from the project.

I have a feeling that the pendulum may possibly have swung too far in the other direction. Is there a way to keep standards high, without overwhelming contributors with dozens of ways to get their wrists slapped?

Tempers are high at the moment. I intend this as a form of mediation. I hope it will be taken as such.

**Comment by brianlheim** [comment]
i am not going to read or reply to this thread any longer. i am not interested in justifying or appeasing clearly toxic behavior.

**Comment by htor** [comment]
@jamshark70 

thanks for the info and medation

> (WRT to this specific conversation -- "a couple of diff lines" are not a big deal. But, consider that 5 minutes' extra difficulty in reviewing a PR times 50 open PRs comes to 4 hours' burden on reviewers.)

yes, resources are limited, tasks many, core maintainers are stressed and nobody likes stress. but this situation doesn't justify being passive-agressive against the people from the community. our time and your time is worth the same. we all do this without getting payed and out of good-will.  it's not anybody's fault brian has taken the responsibility he has in this project or that his time is limited

> ...  lately I understand that underneath the acting out was a concern about what would happen if SC development processes became too bureaucratic.

bureaucratic is fine to certain degree. i'm all for routines that will improve the software quality. what i'm concerned about is doing things in a bureaucratic way *and* be inpolite about it too!

@brianlheim 

> i am not going to read or reply to this thread any longer. i am not interested in justifying or appeasing clearly toxic behavior.

you may call my behaviour toxic and dismiss all criticism. but that just proves my point. i'm being honest, and i'm surely not the only one feeling this about the general situation.

**Comment by jamshark70** [comment]
@htor I had forgotten, when I wrote my reply, that we do have a Code of Conduct. Some of your words do fall outside the bounds of respectful and considerate speech (apart from certain "colorful" language, imputing certain actions to states of mind described in derogatory terms, or to psychological disorders is not within the intended spirit).

https://github.com/supercollider/supercollider/blob/develop/CODE_OF_CONDUCT.md

By responding to the post while failing to note the CoC, my words have been taken as legitimizing personal attacks, which was not my intent. (FWIW to respond to the content of attacks without criticizing the attacking approach does actually imply that attacks are permitted, so I take that criticism and I'm trying to handle that now.)

Unfortunately, while I believe there's a legitimate concern being expressed here, it will be harder to address now as a result of the extra heat.

**Comment by htor** [comment]
i'm sorry! this got messy – i got too angry and used bad language. i'm going to be more patient in the future and try to discuss things more appropriate places. we talked it over on slack, apologized, and i feel we understand each other much better now. if i hurt someone else's feelings in the group, sorry for that, didn't mean to. i really think this community is unique and as you say @joshpar it's not only one voice but many. let's move on, fix bugs, add features and make sounds!

**Pull request closed without merging**
