### PR TITLE
help: document SequenceableCollection:unixCmd

### PR DESCRIPTION
**Pull request by snappizz**

### CODE REVIEW

**Comment by snappizz** [comment]
any comments?

**Comment by jamshark70** [comment]
Two reasons why it is too early to "recommend" Array:unixCmd:

1. #1738: Array:unixCmd is not implemented in Windows.

2. #2317: SequenceableCollection:unixCmd does not use PATH.

**Comment by snappizz** [comment]
Thanks, will incorporate once I have the time.

**Comment by miguel-negrao** [comment]
> Two reasons why it is too early to "recommend" Array:unixCmd:
> 
>     #1738: Array:unixCmd is not implemented in Windows.
>     #2317: SequenceableCollection:unixCmd does not use PATH.
> 
> Until these are fixed, [].unixCmd is an alternative for special cases but it's not ready for prime time. E.g.,

Hi @jamshark70 , regarding 2), the point of  SequenceableCollection:unixCmd is not to use a shell to start the process, but instead start it directly. It is my understanding that the PATH is used by a shell to look for the executable, therefore it seems to me that it is correct that SequenceableCollection:unixCmd will not look at the PATH. I would say that when one wants the PATH to be used for looking for executables then one needs to use a shell, no ?

**Pull request closed without merging**
