### PR TITLE
Add freeSelfResumeNext done action

### PR DESCRIPTION
**Pull request by telephon**
This PR adds a new `doneAction`, namely `Done.freeSelfResumeNext` (number 15). It is analogous to `freeSelfPauseNext` (number 10).

This PR is motivated by the lack of sample based scheduling in sclang. The done action allows us to build a  queue of paused synths that resume each other in a series, while new paused synths can be added. 

Here is an example that streams sclang generated values to scsynth:

```supercollider
(
var n = 2048;
SynthDef(\seq, { |out = 0|
	var array, signal;
	array = \array.ir(0 ! n);
	signal = Duty.ar(SampleDur.ir, 0, Dseq(array, 1), doneAction:Done.freeSelfResumeNext);
	ReplaceOut.ar(out, signal)
}).add
)


(
var block = 2048;
var dt = 1/s.sampleRate;
var dur = dt * block;
var synths;


var nextN = value {
	var c = 0;
	var freq = 64.midicps;
	var r = 2pi * freq * dt;
	{ |n|
		{
			var z = sin(c * r) * 0.1;
			c = c + 1;
			z
		} ! n
	}
};

var addSynth = { |array|
		synths = synths.add(
			Synth.newPaused(\seq, [array: array], addAction:\addToTail);
		)
};

var nextSynth = {
	synths.removeAt(0)//.run(1);
};

var initSynths = { |n|
	n.do {
		addSynth.(nextN.(block))
	}
};


fork {
	initSynths.(3);
	0.1.wait;
	synths.first.run(true);
	inf.do {
		addSynth.(nextN.(block));
		nextSynth.();
		dur.wait;
	}
};
)


```

Feel free to discuss. 

I'd prefer to have a synced server clock (or soundcard clock) in sclang -- I just don't know if the work to get it done will keep it on the hold forever.

### CODE REVIEW

**Comment by telephon** [comment]
I've already looked at the supernova implementation and it would be easy to add. I would do this if there is general consensus that we want to have this.

I also wondered whether for symmetry reasons, we also want `freeSelfResumePrevious`, but I couldn't really think of a case where you could do something useful with it beyond this one.

**Comment by brianlheim** [comment]
If the supernova version is not difficult please add it. Perhaps we should look into making that code shared between implementations.

**Comment by snappizz** [comment]
i confess i don't understand what's going on here. can you describe exactly what this proposed done action is doing and why it is desired?

**Comment by telephon** [comment]
@snappizz 

`freeSelfPauseNext` (action  10) frees the synth and pauses the following node.
By contrast,
`freeSelfResumeNext` (action  10) frees the synth and resumes the following node.

So you can add paused nodes that resume each other. This allows inter-synth node scheduling if you will.

**Comment by Sciss** [comment]
(What would be great, though, in the long term, is to have the possible to trigger any kind of OSC message from a synth, because - as in part of your motivation - to allow server kind-of scheduling, you'd net /n_set etc. as well. That could a new UGen that responds to /u_cmd things)

**Comment by brianlheim** [comment]
@Sciss feel free to open a ticket for that!

**Comment by Sciss** [comment]
@brianlheim that would be a very vagues "an idea" kind of ticket, i don't know, do we use those, or should it go to sc-dev first?

**Comment by telephon** [comment]
@Sciss yes, just write a ticket! 

 I often thought that we need that and I think it might even not be that complicated. I briefly considered doing it for the current purpose, but I found it more tempting to add this and get it done with one done action, at least for now.

**Comment by telephon** [comment]
@Sciss but are you ok with this current PR? I don't want to spend time on the supernova implementation if in the end it turns out that we decide we don't want it.

**Comment by Sciss** [comment]
No, I'm not against the pull request, although I strongly agree with @snappizz that it should address both scserver and supernova, not to open a can here for diverging API.

**Comment by telephon** [comment]
@snappizz if you are happy, can you confirm?

**Comment by telephon** [comment]
@snappizz you wrote:
>supernova?

I've added a supernova implementation, if you get round to it could you have a look? Thanks!

**Comment by telephon** [comment]
It changes the server API because it adds a new done action.

**Comment by telephon** [comment]
@snappizz so it's nothing serious in so far as it doesn't interfere with known functionality.

**Comment by snappizz** [comment]
i'm sorry, but i'm sticking to critical 3.10 tasks for the time being and i'm gonna have to postpone looking at this one

**Comment by telephon** [comment]
@snappizz I don't see why this shouldn't go into 3.10 - it is ready to go.

**Comment by adcxyz** [comment]
> @snappizz I don't see why this shouldn't go into 3.10 - it is ready to go.

I agree - it is a useful addition, it poses no risk, 
and nothing else to be gained by holding it back until 3.11
2c adc

**Comment by brianlheim** [comment]
I think removing the 3.10 milestone is just saying that this is not a vital PR for 3.10, i.e. we could release 3.10 without having merged this, since we are at a point where we're trying to squeeze the last bits through - @snappizz has been managing the milestones though so perhaps it is better for him to explain.

**Comment by telephon** [comment]
thank you for the explanation, brian, I understand. 

It would be good if we can move ahead in such cases, after all it has been around for quite a while, and is simple enough.

**Comment by brianlheim** [comment]
I agree, but it's hard to prioritize PRs with so many of them open right now - it was better when it was down around 20. Some of them have to go stale while we work that number down.

**Comment by adcxyz** [comment]
Seems there are no objections, so we can merge.

**Pull request merged**
