### PR TITLE
class library: cosmetics - standardize code

### PR DESCRIPTION
**Pull request by telephon**

### CODE REVIEW

**Comment by brianlheim** [comment]
lgtm, there are merge conflicts now though.

I would prefer to do this as a single pass with a linting tool. That way we can save ourselves a lot of time, keep a clean commit history, and use that same tool for future style enforcement. Until then, manually updating style should be lowest priority.

**Comment by telephon** [comment]
>I would prefer to do this as a single pass with a linting tool. 

ok. So we accept mixed syntax within a file, I suppose.

**Comment by telephon** [comment]
The dishwasher may take years to be delivered, so in the meantime I think I'll have to do the dishes by hand.

**Comment by brianlheim** [comment]
Fair enough :)

**Pull request merged**
