### PR TITLE
Update Pitch.schelp

### PR DESCRIPTION
**Pull request by tiagmoraismorgado**

### CODE REVIEW

**Comment by snappizz** [comment]
Looks good. A few suggestions:

- remove the `////` separators
- remove `s = Server.local.waitForBoot`
- change `.send(s)` to `.add`

Other than that I think this is an appropriate example.

**Comment by snappizz** [comment]
still some tiny whitespace issues -- remove spaces before semicolons, and unindent the entire SynthDef.

**Comment by crucialfelix** [comment]
whitespace fixed and commits moved into https://github.com/supercollider/supercollider/pull/2334 and merged

**Comment by vivid-synth** [comment]
This example already exists elsewhere (https://github.com/supercollider/supercollider/blob/master/examples/pieces/RM-octaver.scd) -- do we want the duplicates?

**Pull request closed without merging**
