### PR TITLE
help: improved Latch help file

### PR DESCRIPTION
**Pull request by cappelnord**
It was not clear, if Latch would initially output a signal or not.

### CODE REVIEW

**Comment by telephon** [comment]
In the future, we perhaps should add a default value argument.

**Comment by snappizz** [comment]
Why? It may not be convenient, but you can use an `Impulse.ar(0)` to latch an initial value.

**Comment by telephon** [comment]
In addition to the `Impulse.ar(0)` you'd also have to have the right signal at that moment. Say, you are latching a `SoundIn`, this wouldn't be really easy.

**Comment by snappizz** [comment]
I see. `Latch.ar(Impulse.ar(0) + trig, Select.ar(Impulse.ar(0), [sig, DC.ar(initial)]))` should do it, but you lose some CPU.

You gotta be careful adding arguments though, it's an API change. If an alternate client doesn't get updated, the new argument is read from garbage memory. This happened with LocalIn.

**Comment by jamshark70** [comment]
`Select.ar(Impulse.ar(0), [sig, DC.ar(initial)])` "should" do it, although `Select.ar(Impulse.ar(0), ...)` is at the core of my nasty Lag init issue from a couple of months ago, so you have to be careful what you plug the Select into (if we're not going to fix the other issue).

**Pull request merged**
