### PR TITLE
QtCollider: QcTreeWidget: fix instance methods

### LINKED ISSUE #6508: can't add items to TreeView
## Environment

* SuperCollider version: 3.14.0 dev
* Operating system: Windows 11
* Other details (Qt version, audio driver, etc.): Qt 6.8

## Steps to reproduce

These commands both fail. I realized this by trying to open Quarks.gui in 3.14

```supercollider

(
t = TreeView().front;
t.addItem(["hi"]);
)

(
t = TreeView().front;
t.insertItem(0, ["hi"]);
)

```

Here's the error:

```
ERROR: Primitive '_QObject_InvokeMethod' failed.
Failed.
RECEIVER:
Instance of TreeView {    (0000026FC8558EF8, gc=64, fmt=00, flg=00, set=06)
  instance variables [36]
    qObject : RawPointer 0000026F83004870
    finalizer : instance of Finalizer (0000026FC86202C8, size=2, set=1)
    virtualSlots : nil
    wasRemoved : false
    font : nil
    resize : Integer 1
    alpha : Float 1.000000   00000000 3FF00000
    decorator : nil
    layout : nil
    userCanClose : true
    deleteOnClose : true
    action : nil
    mouseDownAction : nil
    mouseUpAction : nil
    mouseEnterAction : nil
    mouseLeaveAction : nil
    mouseMoveAction : nil
    mouseOverAction : nil
    mouseWheelAction : nil
    keyDownAction : nil
    keyUpAction : nil
    keyModifiersChangedAction : nil
    keyTyped : nil
    focusGainedAction : nil
    focusLostAction : nil
    dragLabel : nil
    beginDragAction : nil
    canReceiveDragHandler : nil
    receiveDragHandler : nil
    toFrontAction : nil
    endFrontAction : nil
    onClose : nil
    onResize : nil
    onMove : nil
    itemPressedAction : nil
    onItemChanged : nil
}
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = <instance of TreeView>
	TreeView:addItem
		arg this = <instance of TreeView>
		arg strings = [*1]
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "(
t = TreeView().front;
t.ad..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_QObject_InvokeMethod' failed.
Failed.
RECEIVER: a TreeView
```

### PR DESCRIPTION
**Pull request by sadguitarius**
## Purpose and Motivation

Fixes #6508. My current solution is to hard-code the types that are passed to Qt macros. The ItemPtr typedef broke things because Qt was relying on string comparisons to determine type equivalence. Maybe someone has a better idea for how to handle this though.

## Types of changes

- Bug fix

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by xunil-cloud** [comment]
I found this [discussion](https://forum.qt.io/topic/144669/qmetatype-alias-in-qt6) on Qt forum, I believe this is why, previously, the code stop working in Qt6. For some reason, `QMetaType::name()` is no longer returning the typedef name `ItemPtr`.

**Comment by dyfer** [comment]
@xunil-cloud do you think the proposed solution is the best way forward?
@JordanHendersonMusic do you happen to have an insights into this issue?

**Comment by JordanHendersonMusic** [comment]
https://doc.qt.io/archives/qt-6.4/qmetatype.html#qRegisterMetaType

This seems to be how you'd register the alias... but I think removing it is fine. I don't have time to test this on my machine (or with qt5) but it looks like a trivial change and could just be merged.

**Comment by sadguitarius** [comment]
Thanks everyone, sorry it's still not the most attractive solution! ¯\_(ツ)_/¯

**Comment by dyfer** [comment]
Thanks for your responses!
I went ahead to test this. It does work as expected in Qt6.
However, this breaks the behavior on Qt5.15 (macOS legacy build).

<details>

```supercollider
(
t = TreeView().front;
t.addItem(["hi"]);
)

```
```
ERROR: Qt: Could not get argument type name.
ERROR: Primitive '_QObject_InvokeMethod' failed.
Failed.
RECEIVER:
Instance of TreeView {    (0x7fcf32726f08, gc=BC, fmt=00, flg=00, set=06)
  instance variables [36]
    qObject : RawPointer 0x6000027eef40
    finalizer : instance of Finalizer (0x7fcf30a73f18, size=2, set=1)
    virtualSlots : nil
    wasRemoved : false
    font : nil
    resize : Integer 1
    alpha : Float 1.000000   00000000 3FF00000
    decorator : nil
    layout : nil
    userCanClose : true
    deleteOnClose : true
    action : nil
    mouseDownAction : nil
    mouseUpAction : nil
    mouseEnterAction : nil
    mouseLeaveAction : nil
    mouseMoveAction : nil
    mouseOverAction : nil
    mouseWheelAction : nil
    keyDownAction : nil
    keyUpAction : nil
    keyModifiersChangedAction : nil
    keyTyped : nil
    focusGainedAction : nil
    focusLostAction : nil
    dragLabel : nil
    beginDragAction : nil
    canReceiveDragHandler : nil
    receiveDragHandler : nil
    toFrontAction : nil
    endFrontAction : nil
    onClose : nil
    onResize : nil
    onMove : nil
    itemPressedAction : nil
    onItemChanged : nil
}
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = <instance of TreeView>
	TreeView:addItem
		arg this = <instance of TreeView>
		arg strings = [*1]
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "(
t = TreeView().front;
t.ad..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_QObject_InvokeMethod' failed.
Failed.
RECEIVER: a TreeView
```
</details>

I know that we try not to accumulate technical dept... but I guess we could guard this change with a [Qt6 ifdef](https://github.com/supercollider/supercollider/blob/develop/QtCollider/widgets/QcWebView.cpp#L35)?

**Comment by sadguitarius** [comment]
Weird! Are you able to see where it breaks with Qt5.15? Maybe there's another spot where the type could be hard-coded so it works with both. I tried to leave the typedef in as much as I could to maintain code readability, but I'd assume if the ItemPtr typedef wasn't there at all, everything would work fine.

**Comment by dyfer** [comment]
> Weird! Are you able to see where it breaks with Qt5.15? 

I pasted the SC output in my comment above. I haven't tested beyond that...

**Comment by sadguitarius** [comment]
Ok I added the ifdef. I guess it's not _too_ ugly. Still working for me on Qt6. I haven't attempted a local Qt5 build since there's too much Windows hackery I have to do in order to make that happen. I'd originally solved the issue with Qt6 by stepping through the C++ code with a debugger, so if anyone feels like doing that with Qt5, maybe we can find a better compromise. Otherwise, I'm fine with this if everyone else is.

**Comment by JordanHendersonMusic** [comment]
Is Qt6.2 the lowest version of qt6 we (will ever) support?

**Comment by dyfer** [comment]
Yes, Qt 6.2 is the lowest Qt6 we'd support (aside from the temporary support for Qt 5.15).

**Comment by sadguitarius** [comment]
Are we good to go with this now?

**Comment by dyfer** [comment]
@sadguitarius with the ifdef I'm not convinced. I wonder whether there's a better way address this, that works across Qt 5.15 and Qt6...?

**Comment by xunil-cloud** [comment]
```diff
diff --git a/QtCollider/widgets/QcTreeWidget.h b/QtCollider/widgets/QcTreeWidget.h
index d01613393a..97e62e6ad6 100644
--- a/QtCollider/widgets/QcTreeWidget.h
+++ b/QtCollider/widgets/QcTreeWidget.h
@@ -115,4 +115,4 @@ private:
     bool _emitAction;
 };

-Q_DECLARE_METATYPE(QcTreeWidget::ItemPtr);
+Q_DECLARE_METATYPE(QtCollider::SafePtr<QcTreeWidget::Item>);
```

Add this change on top of 869804839807f28856eebd04fb4cc64b270e0333, I can make TreeWidget works with both Qt5 and Qt6 on my machine. (without ifdef stuff)

**Comment by dyfer** [comment]
@xunil-cloud thanks so much for this!
@sadguitarius would you mind trying @xunil-cloud 's solution?

**Comment by sadguitarius** [comment]
Oh awesome, thank you @xunil-cloud! That's working over here. I've updated my branch with this change, so it should be good to merge unless anyone's still having issues.

**Comment by dyfer** [comment]
@sadguitarius could you remove your previous changes from this branch? It's fine if it's in new/more commits, we'll squash them on merge.

**Comment by sadguitarius** [comment]
Oops forgot to remove the ifdef. I assume you only meant that. I'm still getting the error if the only change against the develop branch is @xunil-cloud 's change

**Comment by dyfer** [comment]
@xunil-cloud when I tried the macOS legacy build (Qt 5.15) from https://github.com/supercollider/supercollider/pull/6521/commits/fd85a67f73de79a755ea7894f1d1887eed77c372 I still got an error when running
```supercollider
(
t = TreeView().front;
t.addItem(["hi"]);
)
```
<details>

```
ERROR: Qt: Could not get argument type name.
ERROR: Primitive '_QObject_InvokeMethod' failed.
Failed.
RECEIVER:
Instance of TreeView {    (0x7f8e110e9f18, gc=A0, fmt=00, flg=00, set=06)
  instance variables [36]
    qObject : RawPointer 0x6000019922e0
    finalizer : instance of Finalizer (0x7f8e6285c6f8, size=2, set=1)
    virtualSlots : nil
    wasRemoved : false
    font : nil
    resize : Integer 1
    alpha : Float 1.000000   00000000 3FF00000
    decorator : nil
    layout : nil
    userCanClose : true
    deleteOnClose : true
    action : nil
    mouseDownAction : nil
    mouseUpAction : nil
    mouseEnterAction : nil
    mouseLeaveAction : nil
    mouseMoveAction : nil
    mouseOverAction : nil
    mouseWheelAction : nil
    keyDownAction : nil
    keyUpAction : nil
    keyModifiersChangedAction : nil
    keyTyped : nil
    focusGainedAction : nil
    focusLostAction : nil
    dragLabel : nil
    beginDragAction : nil
    canReceiveDragHandler : nil
    receiveDragHandler : nil
    toFrontAction : nil
    endFrontAction : nil
    onClose : nil
    onResize : nil
    onMove : nil
    itemPressedAction : nil
    onItemChanged : nil
}
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed
		arg this = <instance of TreeView>
	TreeView:addItem
		arg this = <instance of TreeView>
		arg strings = [*1]
	Interpreter:interpretPrintCmdLine
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "(
t = TreeView().front;
t.ad..."
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_QObject_InvokeMethod' failed.
Failed.
RECEIVER: a TreeView



```
</details>

Any ideas?

**Comment by xunil-cloud** [comment]
That weird. Maybe this error happens even without these change?

**Comment by dyfer** [comment]
@xunil-cloud good point! I guess we haven't checked that... Indeed, the problem does seem to occur in the macOS legacy build on `develop` currently.

I think it would be best to see which of the Qt6-related updates broke this for Qt 5.15... I can try doing that, but not until next week.

**Comment by xunil-cloud** [comment]
Probably this commit f70364c704ea18f00e5aa10aa390aa1ef1b8fdb6? 

`const char* typeName = QMetaType(typeId).name();`

Qt doc doesn't say too much about the pointer return by the `name()` function. I think `typeName` might be a dangling pointer because `QMetatype(typeId)` will be destroyed after this line.

While I don't have this error on my Linux machine, but this commit break `Quarks.gui` on Qt 15.15 on my system.

**Comment by dyfer** [comment]
@xunil-cloud thanks for that.
I tried removing that commit (putting Qt6 ifdef around it) and indeed the error goes away with Qt 5.15.
I tried it on top of original changes in this PR 869804839807f28856eebd04fb4cc64b270e0333; in that case should we revert ffcad8e03aef771192c29f300b021a8d74f35e02 ?

**Review by dyfer — APPROVED** [review]

**Comment by dyfer** [comment]
Thanks everyone for working on this!

**Pull request merged**
