### PR TITLE
scdoc: redesign top bar

### PR DESCRIPTION
**Pull request by snappizz**
uuuugggh whens github going to fix their damn image upload feature.

anyways, so this might be a little controversial, since it "undocks" the top bar in the help files. the main advantage is reducing visual clutter (and looking a touch more modern). as discussed at #2943, there's a problem where this top bar competes with the decorations on the help window. the disadvantage is that now you have to scroll back up to find what page you're on, and to access Browse/Search/Table of contents. it is of course still possible to navigate back to the home page in one click.

before you pull out the pitchforks, i'd like to point out that no other documentation system i've seen has this `position: fixed` menu. ~~also, i don't think i've been in a situation where i need to know what page i'm on.~~ duhhhh i forgot about internal links. search is also easy accessible with Ctrl+D.

this also removes the big black horizontal line in the header, which ruins the visual separation between the header/subtitle and the source/inheritance/see also text. plus the right-alignment is ugly. i have an idea for how to overcome this, but i'll take care of that in a separate PR.

### CODE REVIEW

**Comment by telephon** [comment]
good, I suppose the clarity it's worth the loss of the toc, one can pop it out if necessary.

now some things left to do, I think:

### the scrolling of the popped out toc is a bit funny. 
Maybe that is a problem of webview though?

### the navigation bar is squeezed to the left

screen shot 2017-06-19 at 09 32 24

### the `.subheader` information is a bit of a mess now

The most important information (well arguably) - the summary - is almost lost in all the links. Also a factor may be that the title is so much larger than the summary, and that there is nothing to separate it off now.

screen shot 2017-06-19 at 09 38 08

Somehow I'd now even prefer it the simple way:

screen shot 2017-06-19 at 09 48 25

Or, because screen space on the right is free, something like a box to the right.


If you could hide that long section, it would be a massive improvement:

screen shot 2017-06-19 at 09 51 31


… because in actual use, the the examples are the best resource often.

**Comment by snappizz** [comment]
the navigation bar shouldn't be squeezed there... try `SCDoc.renderAll`?

i'll fix the subheader in another PR. i have some ideas on how to make it cleaner.

**Comment by telephon** [comment]
great!

**Comment by telephon** [comment]
the navigation bar is still squeezed as in the picture above, after a recompile sc and render all.

There is also a suspiciously looking checkbox in the top left corner:

screen shot 2017-06-19 at 22 47 09

**Comment by snappizz** [comment]
that's a bug, i'll take a look later

**Comment by snappizz** [comment]
i am seeing the lack of left margin on the top bar as a result of an scdoc caching error. you may have to bump SCDoc.version to 60, then `SCDoc.renderAll`, then bump it back to 59, then `SCDoc.renderAll`.

i have no clue what the checkbox could be.

**Comment by snappizz** [comment]
here is how it should look now:

untitled

**Comment by snappizz** [comment]
beep beep

**Pull request merged**
