### PR TITLE
scsynth: print version and exit with option -V

### PR DESCRIPTION
**Pull request by blacksound**
Proposed solution for #1310

### CODE REVIEW

**Comment by danstowell** [comment]
looks useful

**Comment by gusano** [comment]
@blacksound Why capital `V` and not just `-v` like any other app?

**Comment by blacksound** [comment]
Related to adding version print for scsynth I took -V since -v is already used for verbosity. See #1310
Should use the same option for sclang and scsynth.


Python uses -V for version btw.

**Comment by blacksound** [comment]
@danstowell fixed the exit code now.

**Comment by crucialfelix** [comment]
+1 looks good, ready to merge

**Comment by gusano** [comment]
I vote for switching:
- `v` for version
- `V` for verbose (which is probably muss less used)

**Comment by gusano** [comment]
Here's a patch:
https://github.com/gusano/supercollider/commit/ef88b2647ad00c14189e9a3d5274eae6aa0b1bf1.patch

**Comment by crucialfelix** [comment]
I think we should be non-breaking and just use -V 

In any case, lets decide and merge

**Pull request merged**
