### PR TITLE
help: main help page: change wording

### PR DESCRIPTION
**Pull request by tiagmoraismorgado**
trying to pay attention to small details. please tell me if these amendments are not relevant

### CODE REVIEW

**Comment by snappizz** [comment]
A better message for this commit would have been "help: main help page: change wording."

Sorry, but most of the edits here change good English into bad English.

The only change here I support is "These might be useful starting points on getting help with SuperCollider" => "These are useful starting points for getting help on SuperCollider," which strengthens an unnecessarily wimpy sentence.

**Comment by crucialfelix** [comment]
We have that new description. I forget where we are with that - it should go here and on the website.

**Comment by vivid-synth** [comment]
It should definitely be "getting help with SuperCollider," not "getting help on SuperCollider," but I'm ok with the rest of the change to that sentence ("might be"->"are", "on getting"->"for getting")

**Comment by tiagmoraismorgado** [comment]
can you guys help me editing that. i am at work right now, a bit busy at the moment, probably only will be able to take on this maybe around saturday or sunday

**Comment by crucialfelix** [comment]
You should be able to see a check box on the right side of this pr: allow maintainers to collaborate.

Check that and then we can easily edit it.  (not that I've tried it yet)

thanks @tiagmoraismorgado !

**Comment by tiagmoraismorgado** [comment]
greetings everyone

i allowed edits in this document a couple of weeks ago. the pull request is still opened. any help regarding fixing its issues and eventually committing it is welcome

kind regards

**Comment by vivid-synth** [comment]
@telephon did you intend to merge this? Imo there's still some work to be done (e.g. "getting help on Supercollider" should be "getting help with Supercollider"), and there are some erroneous extra "-" and " " characters.

**Comment by telephon** [comment]
This was a mistake – sorry. What's the best undo? revert or fix?

**Comment by snappizz** [comment]
#2402

**Pull request merged**
