### PR TITLE
Update boost libraries (1.74.0)

### PR DESCRIPTION
**Pull request by brianlheim**
## Purpose and Motivation

- updates our vendored version of boost from 1.66 to 1.74, released this month
- updates our vendored version of boost_sync (not part of the main boost distribution) to the latest development version, from 11 days ago (https://github.com/boostorg/sync/commit/47d9228feffb1e0a7f6ad9b93665d1d83cc2e8b5).
- updates extract_boost.sh with additional source directories to scan
- applies sc-org boost patches (i don't feel these are necessary anymore but kept them in this PR)
- removes the executable bit from boost_sync files
- remove compatibility code for boost pre-1.70
- silence some deprecation warnings from the newer boost version
- fix a small C++17 compilation error

it looks like a lot, but the majority of the commits are small and can be reviewed individually.

this builds locally under gcc 10 on arch linux. probably we should merge #4906 first to check this under more compilers and configs.

## Types of changes

- library updates
- bug fixes

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [x] Updated documentation
- [ ] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
i was confused about why the additions are 3x the deletions; it looks like many new large files were added in asio, fusion, math, and parameter

**Comment by brianlheim** [comment]
this is passing now, but i'd like to merge #4906 first.

**Comment by brianlheim** [comment]
closed/reopened to retrigger travis build

**Comment by dyfer** [comment]
OMG Travis took `Total time 3 hrs 53 min 13 sec`
I hope ccache makes a substantial difference here :)

**Comment by brianlheim** [comment]
> OMG Travis took Total time 3 hrs 53 min 13 sec

note this is the time spent in all builds total, not the time from the first build starting to the last build completing! it is still a long time though, and most of it is the mac builds. the times do drop a lot once travis caching kicks in: https://travis-ci.org/github/supercollider/supercollider/builds/724707768, still something to keep an eye on. open source users get at least 2 parallel mac builds, fyi. i can't find travis's info about this but can confirm it's at least 2 empirically.

**Comment by dyfer** [comment]
I'try to get to this eventually...
Just a comment for anyone else reviewing this: my intuition is that supernova performance should be carefully checked after this update. I think on Windows we use `shared_mutex` from boost/thread. We might also use other functionality on different platforms (mutexes?), but I haven't looked closely.

**Comment by brianlheim** [comment]
> my intuition is that supernova performance should be carefully checked after this update. I think on Windows we use shared_mutex from boost/thread

have you checked the release notes/implementation to see what changed?

**Comment by dyfer** [comment]
> have you checked the release notes/implementation to see what changed?

Not at this time.

**Comment by brianlheim** [comment]
i skimmed the release notes but didn't see anything of note. keep in mind that this library is one of the more seasoned ones in boost and is regression tested pretty heavily

**Comment by brianlheim** [comment]
i'm rerunning CI for this after #5178

**Comment by brianlheim** [comment]
@timblechmann just wondering because you know supernova best and are usually informed about boost changes. do you foresee any issues with updating this?

**Comment by timblechmann** [comment]
@brianlheim i don't really see much risk here. though on a side note: when i started adding boost sources to supercollider it was a time before package managers for native code have been around. in 2020, it might be worth rethinking the architecture to possibly pull in boost via package managers like conan. they are certainly no silver bullets, but it may simplify the setup for stuff like boost ... maybe even beasts like qt.

when it comes to `shared_mutex`, i guess it should be safe to migrate to the c++17 version if the version from boost is still in use. while boost.thread is well tested, there also have been known bugs in the past ...

**Comment by brianlheim** [comment]
> in 2020, it might be worth rethinking the architecture to possibly pull in boost via package managers like conan. they are certainly no silver bullets, but it may simplify the setup for stuff like boost ... maybe even beasts like qt.

i've looked into conan and vcpkg and they still don't provide all the packages we need for SC across platforms, so i'm hesitant to switch up our build process for it and ask everyone to learn a new tool. but, i am keeping an eye on it. thanks for the advice!

**Comment by timblechmann** [comment]
`vcpkg` has a few design faults imho. `conan` can be integrated within cmake (`conan.cmake`). and while it's not a one-size-fits-all solution, for stuff like boost, yamlcpp or also portaudio it's probably the way with the least amount of trouble (`bcp` always used to be kind of hacky)

**Comment by brianlheim** [comment]
portaudio is one of the packages missing from conan, hoping that changes soon now that they are on github and improving their cmake support.

**Comment by timblechmann** [comment]
portaudio is in bincrafters: https://github.com/bincrafters/conan-portaudio

**Comment by brianlheim** [comment]
@timblechmann oh great! i didn't know about bincrafters and it looks pretty reliable. i'll create a new ticket for exploring conan. meanwhile, we should merge this ASAP so that we're not behind for the 3.12 release. i'll review code changes/do some testing.

**Comment by brianlheim** [comment]
my understanding of the important features we use from Boost.Thread via nova-tt are all in rw_mutex and nonrecursive_rw_mutex:
- shared_mutex (windows only)
- unique_lock and shared_lock (non-windows)

some other Boost.Thread stuff is being used in nova-tt's `semaphore_boost_fallback.hpp` header but we definitely don't use that because it references a nonexistent boost header, so it would fail to compile if we included it.

also, the only place we use either rw_mutex or nonrecursive_rw_mutex in supernova is in `struct symbol_table` in `server/supernova/utilities/named_hash_entry.hpp`.

am i missing something? next i am going to do a small performance regression test on macOS and then on Windows.

**Comment by timblechmann** [comment]
@brianlheim it probably makes sense to get rid of the `rw_mutex`es sooner or later, considering that `shared_mutex` is in c++17

**Comment by brianlheim** [comment]
@dyfer i tested supernova on Windows and macOS before and after this update by running routines that created different amounts of short-lived nodes in a pargroup, i didn't notice any performance degradation.

**Comment by dyfer** [comment]
@brianlheim thanks for testing
Between your tests, Tim's comments, my test, and reading more about boost I think this change is indeed fine. Thanks!

**Review by dyfer — APPROVED** [review]
This is good, to the best of my knowledge.

**Pull request merged**
