### PR TITLE
Update boost.filesystem headers to 1.63.0.

### LINKED ISSUE #2441: Windows: help pages don't open with non-ASCII character in username/helpdir-path
If a username contains a non-ASCII character help pages do not display. The help pain still displays  "Sending help request", and the indexing is processed:

```
*** Welcome to SuperCollider 3.8.0-beta1. *** For help press Ctrl-D.
SCDoc: Indexing help-files...
SCDoc: Indexed 1381 documents in 6.03 seconds
```

But the pane remains empty.

SDoc does contain spaces in usernames (as opposed to Quarks), but not non ASCII characters.

### PR DESCRIPTION
**Pull request by brianlheim**
This paves the way for future simplifications in SC code around
directory manipulation by making available functions such as
is_symlink() and is_directory() that have only been added in
newer versions of boost.filesystem.

Some particular reasons why I would like to update this:
- Staying current with external libraries is always good.
- boost::filesystem::path is IMO the most powerful and reliable tool to fix #2441.
- Adopting `path` as the main representation of path names in the code base will increase readability and clarity and allow us to get rid of some blocks of non-portable code, for instance [this](https://github.com/supercollider/supercollider/blob/master/common/SC_DirUtils.cpp#L121-L145).

### CODE REVIEW

**Comment by bagong** [comment]
Not the whole lot at once? I tried it with VS 2015 the other day, it seemed to work...

**Comment by brianlheim** [comment]
@bagong You're welcome to submit a PR for that.

**Comment by brianlheim** [comment]
To elaborate: this update has a clear use case, and I didn't want to spend time quibbling about updates to things that don't have a pressing need to be updated. If there is a desire to actually spend time deciding on that, then I'd be all for it, but discussions about boost have fizzled so far.

This builds fine for me on macOS.

**Comment by bagong** [comment]
The problems I remember from the past resulted from breaking a platform without providing a fix/workaround. Windows is usually the problem case. For 2015 I can already say that it's okay. If you provide the full set I will test on the other Windows build systems. Why mix different versions? And we can see if we still need the old patches...

**Comment by brianlheim** [comment]
Alright, great! I thought we were already working with mixed versions--maybe some of the headers haven't updated on the boost end for a couple iterations.

I'm occupied right now, but will open a new PR for this in an hour or two. If you test with the Windows toolchains, I can test on macOS with llvm.

I recall that Tim mentioned a utility in the external_libraries folder that would auto-extract the appropriate headers, so I'll try to use that.

**Comment by bagong** [comment]
Okay. If you get that to work, would be good to update it. I didn't manage...

**Comment by bagong** [comment]
I restarted the OSX build, it broke off somewhere building the server, but without error... maybe it was cancelled... Linux and headless went through.

**Comment by vivid-synth** [comment]
The script that Tim was referring to is in external_libraries/extract_boost.sh . That said, one reason why updating all of boost is more work is that we have to figure out where we've patched our version to be different from boost, and re-patching them (I've listed a couple of them in https://github.com/supercollider/supercollider/issues/2301) .

**Comment by brianlheim** [comment]
@vivid-synth - found it and ran it! excellent. 

#2772.

**Pull request closed without merging**
