### PR TITLE
Plugins: Choose Index.ar calc function based on phase arg

### PR DESCRIPTION
**Pull request by jamshark70**
- `Index_next_k()` accesses index `ZIN0(1)` once per control cycle -- i.e., assumes a kr index.
- `Index_next_a()` accesses index `ZIN0(1)` `inNumSamples` times per control cycle -- ar index.

Both calculation functions do `GET_TABLE` only once per control cycle -- so the bufnum input does not support ar under any circumstances.

But, the Ctor chooses next_k for a control-rate *bufnum*, regardless of the rate of the input that matters (index). So this PR changes `INRATE(0)` to `INRATE(1)`.

Five other UGens follow the same pattern: IndexL, FoldIndex, WrapIndex, IndexInBetween and DetectIndex.

Test: without the fix, the following displays an obvious sample-and-hold. With the fix, Index.ar is correctly equivalent to BufRd.ar without interpolation.

```
(
s.waitForBoot {
	b = Buffer.alloc(s, 512, 1, completionMessage: { |buf|
		buf.sine3Msg([4], [1], [0.25pi], asWavetable: false)
	});
	s.sync;
	{
		var phase = Phasor.ar(0, 1, 0, 1000);
		[Index.ar(b, phase), BufRd.ar(1, b, phase, interpolation: 1)]
	}.plot(duration: b.duration); 
};
)
```

I'll suggest 3.9.1 for this as it's a small bugfix.

### CODE REVIEW

**Comment by patrickdupuis** [comment]
I am working on a UnitTest for this. It isn't fun :( Please give me a couple days to add the test before merging this.

**Comment by patrickdupuis** [comment]
I have a draft UnitTest over here: https://gist.github.com/patrickdupuis/077577a8c2800f24c2c3849a0592176d

Currently, the second test fails because `SynthDef not found`. I don't know why this is happening. I would appreciate some expert help :)

**Comment by patrickdupuis** [comment]
I found the issue was being cause by `server.remove` in `tearDown {}`.

**Comment by patrickdupuis** [comment]
I have a UnitTest ready for this. Will push to this PR branch later tonight.

**Comment by patrickdupuis** [comment]
Oops... forgot to change the name before pushing ;)

**Comment by jamshark70** [comment]
Patrick's unit test is in now -- should be ready to merge.

**Comment by joshpar** [comment]
looks good from here.

**Comment by jamshark70** [comment]
Squashed the unit test down to one commit. Should be ready to merge.

**Pull request merged**
