### PR TITLE
classlib: refactor quarks save/load

### PR DESCRIPTION
**Pull request by scztt**
Quarks.load was set up to parse paths both in local=url@refspec form and quark@refspec form, but the latter was never happening because of an extra ? in the regexp. This is fixed, and the parsing broken out into a separate function.

In addition, this change refactors Quarks.save slightly - in cases where we are installing (a) known quarks from the directory, (b) to the default quarks install location, (c) and they are not locally modified, we simply save using quarkname@refspec. The path is platform specific (even possibly machine specific), and is redundant if they're in a default location. For the 99% case (quarks installed from the directory) this makes for a much cleaner list, that is much more likely to be valid across platforms / machines / configurations, and through future changes to SuperCollider.

### CODE REVIEW

**Comment by scztt** [comment]
Please test using (this gist)[https://gist.github.com/scztt/da81d2531f77fefa5c0d] - or, if I've got some of the test cases wrong, please modify.

Also, please mention if there's a good reason to keep the local path in case of plain-old-unmodified-quark installations - I couldn't think of any, and having local paths there increases the changes for failure across machines / platforms, and makes the list more easily human-editable.

**Comment by scztt** [comment]
Will fix args style.

**Comment by scztt** [comment]
Regarding name / refspec validation - I wanted to change the validation of names and refspecs little as possible in this commit, but if you think that change should go in here, I'll add to the pr.

**Comment by crucialfelix** [comment]
I think you are right that if its a default quark in default location then it should just save the name.

add the quarkname and refspec check. it was just an oversight to not check them. also I didn't know realize that \\ is needed in regexps.

I will test this out hopefully tomorrow.  thanks scott !

**Comment by scztt** [comment]
Additionally - I tested this by installing every quark (that currently compiles). and then saving the list, clearing, and reinstalling to ensure I could round-trip correctly. I didn't see any problems.

**Comment by crucialfelix** [comment]
The regex fixes that you found were included in the other bug fix that we merged. so this is now obsolete. closing

**Pull request closed without merging**
