### PR TITLE
help: chaotic generators warnings removed

### PR DESCRIPTION
**Pull request by smrg-lm**
This patch is for removing unnecessary comments and homogenize the math notation with the bhob ugens (taken as example).

### CODE REVIEW

**Comment by smrg-lm** [comment]
I'm sorry for leaving this. The patch was what it was for a simple reason. I believe what I said and didn't had much to do. But I didn't explained it well, the math notation simplifies concepts avoiding the cognitive overhead of the programming language syntax. No hard feelings, not now :-P

**Comment by telephon** [comment]
Maybe a misunderstanding: I like the patch, just didn't want to lose the information that was there, so I suggested to add the examples of the implementation in sclang to each of the helpfiles. I could have done it myself, but thought you know better!

**Comment by smrg-lm** [comment]
:-D It was a joke. I will add the examples above after the formulas as soon as I get my computer to do so.

**Comment by telephon** [comment]
did you get around to add the examples? :)

**Comment by smrg-lm** [comment]
thanks for the buzz :-)

**Comment by telephon** [comment]
thanks!

**Pull request merged**
