### PR TITLE
Ableton Link: final review changes

### PR DESCRIPTION
**Pull request by brianlheim**
Final review changes for 

- switch to different appveyor image
- rename files
- reorder definition of elements within LinkClock (static functions/members first, then actual members)
- rename InitTime (`mInitTime` is inaccurate as this is not a class member)
- various formatting and comment changes that will make fewer lines susceptible to reformatting

### CODE REVIEW

**Comment by brianlheim** [comment]
thanks @jamshark70 ! grrr, still build error. i don't know what's up with this. i'm currently investigating it. worst case we define the function ourselves

**Comment by brianlheim** [comment]
confirmed -- lack of htonll is there if _WIN32_WINNT is defined to Vista (0x600). pushed a kinda necessary kinda unsatisfying fix.

**Comment by brianlheim** [comment]
do not merge yet -- if this works I want to undo the commit changing the AppVeyor image

**Comment by brianlheim** [comment]
ok, turned out to be some issue with the order in which headers are included. i don't have time to investigate this further so I've left a FIXME note. this seems related: https://stackoverflow.com/questions/21399650/cannot-include-both-files-winsock2-windows-h#21401503

**Comment by brianlheim** [comment]
i am done making changes to this branch now; it can be reviewed(/merged) if CI passes. thanks for everyone's patience!

**Comment by brianlheim** [comment]
@jamshark70 Would you mind giving this quick retest now that I've wrapped up work on it?

**Comment by jamshark70** [comment]
`TestTempoClock` and `TestLinkClock` both pass. Tempo, phase and start/stop sync with QLinkHut all work correctly.

Good to go :grin:

**Pull request merged**
