### PR TITLE
class library: deprecate String:inform

### PR DESCRIPTION
**Pull request by snappizz**

### CODE REVIEW

**Comment by telephon** [comment]
Fine! Before we merge more changes to the Server, could we decide on what to do with https://github.com/supercollider/supercollider/pull/2422 ? I've spent endless time maintaining it and fixing the merge conflicts now …

**Comment by snappizz** [comment]
Understood, I'm going to tag as WIP so it doesn't get merged until then.

**Comment by telephon** [comment]
thanks!

**Comment by adcxyz** [comment]
A search in downloaded-quarks finds 71 .sc files with ".inform". 
Maybe deprecating inform will create more noise / annoyance for users 
than the benefit of having one less method alias?
2c adc

**Comment by snappizz** [comment]
i don't know, but you're right that this is found in a lot of quarks. Maybe we can just make it a documentation issue -- replace it with postln in the core library and discourage it in the help files, but not deprecate

**Comment by snappizz** [comment]
#2542

**Pull request closed without merging**
