### PR TITLE
Prepare for 3.11.2-rc1

### PR DESCRIPTION
**Pull request by brianlheim**
## Purpose and Motivation

This updates the changelog, readme, and main version number in the repo to prepare for the 3.11.2-rc1 release.

## Types of changes

- New feature

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Review by dyfer — APPROVED** [review]
Thanks!
I have only one comment: for legacy macOS build, while it's aimed at older systems, I think still it works on all macOS versions (signing issues notwithstanding).

So... I don't know if there's a way to phrase it better, but maybe `(...) that should support macOS 10.10 and above.`. This is only a suggestion, really up to you.

**Comment by brianlheim** [comment]
thanks for the suggestion -- i changed it to "10.10 and above"

**Comment by dyfer** [comment]
> thanks for the suggestion -- i changed it to "10.10 and above"

Thanks! Would you mind changing it also in the `changelog` file?

**Comment by brianlheim** [comment]
@dyfer updated!

**Review by dyfer — APPROVED** [review]
Thanks!

**Pull request merged**
