### PR TITLE
class library: Psym1 outputs n parallel events and avoids accumulation

### LINKED ISSUE #2315: Psym1 doesn't expand arrayed keys correctly
```
(
Pdef(\x, Pbind(\note, 9, \sustain, 1.5));
Pdef(\y, Pbind(\note, 0, \sustain, 0.5));
Pdef(\z, Pbind(\note, 11, \sustain, 0.5));
Psym1(
    Pseq([[\x, \y], \z, \z], inf)
).trace.play;
)
```

This is because `Ppar` internally created by `Psym1`) serializes the parallel events, and `Psym1` uses only one event each.

Could be solved in a new event stream implementation that has been discussed, or some more specific fix.

### PR DESCRIPTION
**Pull request by telephon**
Because Psym1 uses Ppar to produce parallel events, and Ppar uses
(delta: 0) to serialize them, we need to return n events. This fixes #2315.

Also, instead of accumulating streams, Psym1 uses input keys to store them.

Thanks to James Harkins, Daniel Mayer and Gil Fuser.

### CODE REVIEW

**Comment by jamshark70** [comment]
What if the parallel streams have different timing? You can't guarantee all child streams will have an event for every moment in time... but returning *n* events assumes so.

I believe parallel patterns are fundamentally incompatible with the P***1 filter patterns. I'm not sure there is a 100% reliable solution.

**Comment by jamshark70** [comment]
More concretely... does the following make sense? I'm not sure that it does.

```
p = Psym1(
	Pseq([[\x, \y], \x, \y], inf),
	(
		x: Pbind(\freq, 440, \dur, 1),
		y: Pbind(\freq, 880, \dur, 0.5)
	)
).asStream;

p.nextN(10, ()).do(_.postln); ""

( 'delta': 0, 'freq': 440, 'dur': 1 )
( 'freq': 880, 'dur': 0.5 )
( 'freq': 440, 'dur': 1 )   // <-- this is now at time index 0.5
( 'freq': 880, 'dur': 0.5 )
( 'delta': 0, 'freq': 440, 'dur': 1 )
( 'freq': 880, 'dur': 0.5 )
( 'freq': 440, 'dur': 1 )
( 'freq': 880, 'dur': 0.5 )
( 'delta': 0, 'freq': 440, 'dur': 1 )
( 'freq': 880, 'dur': 0.5 )
```

Part of the problem here is that it is not at all clear what parallelism means WRT to Psym1, Pswitch1 etc. Without working that out, code fixes are likely to cause more problems down the road.

**Comment by telephon** [comment]
Good point. I don't think we should suppose that there is a Ppar playing behind the scenes. We could supply an argument that explicitly says which of the streams to use for duration? Or simply state that it is always the last. 

It might be better not to support parallel keys for `Psym1` at all. 

The question is whether there are useful scenarios where this kind of use leads to readable code.

```

(
Pbindf(
	Psym1(
		Pseq([[\x, \y], \z, \z], inf),
		(
			x:Pbind(\note, 9, \sustain, 1.5),
			y:Pbind(\note, Pfunc { rrand(4, 5) }, \sustain, 1),
			z:Pbind(\note, Pfunc { rrand(0, 10) }, \sustain, 0.5),
		)
	),
	\dur, Pseq([1, 0.5, 0.25], inf)
).play;
)
```

Seems to make perfect sense. Any opinions?

**Comment by jamshark70** [comment]
> I don't think we should suppose that there is a Ppar playing behind the scenes. We could supply an argument that explicitly says which of the streams to use for duration? Or simply state that it is always the last.

I'm not necessarily opposed to this. I think it should be a deliberate decision that is documented carefully, instead of "we saw some weird behavior somewhere, so let's do something to it without considering reasonably foreseeable cases."

It might be sufficient to document that users *should* put a parallelized Psym1 in a Pchain or Pbindf to override `\delta` explicitly -- and if they don't, it's at their own risk. We don't have to baby the users, but we should give fair warning where we know that the behavior may be counterintuitive (and there isn't really a solid way to make it intuitive). Documentation can make it clear that parallel symbol patterns in the context of Psym1 are just plain weird and you had better be really careful.

I think, in the Pbindf example, you would have to set `\delta` rather than `\dur`, no? Because `Ppar` sets `\delta` and that will override any `\dur` in the event.

The tricky thing with `Ppar` is that it represents, conceptually, multiple streams of "moments-in-time" that are merged, but the moments have to be converted into discrete events obeying a single stream of inter-onset intervals. In the translation, we lose the possibility of `Psym1`, `Pswitch1` etc. operating on the moments-in-time -- such patterns can only destroy the integrity of the parallelism. We don't have a data structure representing a moment that comprises multiple, simultaneous events. That's a weakness.

**Comment by jamshark70** [comment]
Also, I think the `IdentityDictionary` needs to be a `Dictionary` now -- the symbol pattern may construct arrays dynamically, in which case they may be equal to, but not identical to, parallel keys that were already created, e.g. `Pxrand(#[a, b, c, d, e, f, g], inf).clump(Pwrand([1, 2], [0.9, 0.1], inf))`.

If you test only with a ListPattern containing subarrays, you'd never find this bug.

**Comment by jamshark70** [comment]
Just for fun, I wanted to see what it might look like to have a "compound" event type, which Ppar could use to combine multiple events occurring at the same time.

I'm not proposing this as an actual solution, specifically. This would not work transparently with any filtering pattern (Pcollect, or Pbindf/Pchain/etc. with Pkey) that expects the events coming from Ppar to have a specific structure -- the caller would have to check the event type and take action differently. It might be possible to have a CompoundEvent class that would pass event methods through to the child events, but I haven't thought it through carefully and there's probably a glaring problem with that.

(Or, alternately, a Ppar-like pattern could always return `\compound` type events, even if the array of child events only holds one.)

But at least a design like this would work with Psym1 and keep simultaneous parallel events together.

```
diff --git a/SCClassLibrary/Common/Streams/Ppar.sc b/SCClassLibrary/Common/Streams/Ppar.sc
index 60a224d..642384e 100644
--- a/SCClassLibrary/Common/Streams/Ppar.sc
+++ b/SCClassLibrary/Common/Streams/Ppar.sc
@@ -10,7 +10,7 @@ Ppar : ListPattern {
 		var priorityQ = PriorityQueue.new;
 
 		repeats.value(inval).do({ arg j;
-			var outval, stream, nexttime, now = 0.0;
+			var outval, stream, nexttime, now = 0.0, composite;
 
 			this.initStreams(priorityQ);
 
@@ -38,10 +38,22 @@ Ppar : ListPattern {
 					// requeue stream
 					priorityQ.put(now + outval.delta, stream);
 					nexttime = priorityQ.topPriority;
-					outval.put(\delta, nexttime - now);
-
-					inval = outval.yield;
-					// inval ?? { this.purgeQueue(priorityQ); ^nil.yield };
+					if(nexttime == now) {
+						if(composite.isNil) {
+							composite = (type: \compound, events: [outval]);
+						} {
+							composite[\events] = composite[\events].add(outval);
+						};
+					} {
+						if(composite.notNil) {
+							composite[\events] = composite[\events].add(outval);
+							outval = composite;
+							composite = nil;
+						};
+						outval.put(\delta, nexttime - now);
+						inval = outval.yield;
+						// inval ?? { this.purgeQueue(priorityQ); ^nil.yield };
+					};
 					now = nexttime;
 				};
 			};
```

```
p = Ppar([
	Pbind(\degree, 0, \dur, 0.5),
	Pbind(\degree, 7, \dur, 0.25)
]).asStream;

p.next(());

-> ( 'delta': 0.25, 'events': [ ( 'degree': 0, 'dur': 0.5 ), ( 'degree': 7, 'dur': 0.25 ) ], 'type': compound )
-> ( 'delta': 0.25, 'degree': 7, 'dur': 0.25 )
-> ( 'delta': 0.25, 'events': [ ( 'degree': 0, 'dur': 0.5 ), ( 'degree': 7, 'dur': 0.25 ) ], 'type': compound )
-> ( 'delta': 0.25, 'degree': 7, 'dur': 0.25 )
-> ( 'delta': 0.25, 'events': [ ( 'degree': 0, 'dur': 0.5 ), ( 'degree': 7, 'dur': 0.25 ) ], 'type': compound )
-> ( 'delta': 0.25, 'degree': 7, 'dur': 0.25 )
-> ( 'delta': 0.25, 'events': [ ( 'degree': 0, 'dur': 0.5 ), ( 'degree': 7, 'dur': 0.25 ) ], 'type': compound )
-> ( 'delta': 0.25, 'degree': 7, 'dur': 0.25 )

// Do this before playing it (untested but seems straightforward):
Event.addEventType(\compound, { |server|
	~events.do { |event|
		event.play(server);
	};
});
```

**Comment by telephon** [comment]
@jamshark70 wrote:
>Also, I think the `IdentityDictionary` needs to be a `Dictionary` now

With the above solution, the arrayed keys are not stored anymore separately, but each key has its own, single stream.

**Comment by telephon** [comment]
>Just for fun, I wanted to see what it might look like to have a "compound" event type, …

This is really something we should take a closer look at for the future. Also @rkuivila proposed something like this. Your solution is really elegant.

It probably should support the possibility to override and iterate over keys in the compound event, e.g.:

`stream.collect { |x| x[\freq] = x[\freq] * rrand(1.0, 2.0); x }`

For this, we should have a `CompoundEvent` as you suggest it, I think.

**Comment by brianlheim** [comment]
Ping. @telephon, what work needs to be done to merge this? It has conflicts with master now. Unfortunately, I don't use the Patterns library enough to have opinions about anything here.

**Comment by telephon** [comment]
I'll resolve first, then we see. thanks!

**Comment by telephon** [comment]
can be merged.

**Comment by telephon** [comment]
(need to think about it once more)

**Comment by telephon** [comment]
Now ready to merge.

**Comment by telephon** [comment]
@jamshark70 @rkuivila ok in your eyes ?

**Comment by jamshark70** [comment]
I still have reservations about this, and to be honest, I don't have a lot of time to understand all the ramifications.

*If* we are convinced this is an important new feature, then I won't stand in the way. But I have a sneaky feeling this is one of those cases where a user extrapolated from Psym to Psym1 without considering whether that extrapolation really make sense -- and now we are trying to accommodate an extrapolation of questionable sensibility. Just a feeling. I won't press very hard on that.

Concretely, `\delta, 0` troubles me. It's "like" parallelism without actually being parallel. I think it may be evidence of trying to stick Psym's square peg into Psym1's round hole.

**Comment by telephon** [comment]
I think what we are really missing is a parallel event. This could be an event type or a class. I'll make an issue for it and put this PR on the backlog until we have a properly defined parallel event.

**Pull request closed without merging**
