### PR TITLE
sclang: refactor server menu

### PR DESCRIPTION
**Pull request by scztt**
This fixes issues where server menu flashes when updating because we were detroying the entire thing to rebuild it - now we just incrementally update.

### CODE REVIEW

**Comment by patrickdupuis** [comment]
@telephon can you explain why you approved this PR given my comment above?

**Comment by patrickdupuis** [comment]
Does this PR depend on the fixes from #3871?

**Comment by telephon** [comment]
I approved of it because it fixes issues that scott discovered in his own code. I don't want to hold up patches to peoples own contributions. I didn't have this failure for some reason.

**Comment by patrickdupuis** [comment]
@telephon try testing this out against 3.10 and see if you get the same breakage.

**Comment by telephon** [comment]
now I get it, too.

I did a bit of digging (it is not so convenient that the error doesn't say what call actually failed), I found that it is here:

```supercollider
insertAction {
		|before, action|
		if (before.isKindOf(Number)) {
			before = this.actions[before]
		};

		^this.invokeMethod('insertAction', before, action.asMenuAction); // <--- this is probably wrong, because invokeMethod takes a boolean as third argument.
	}
```

**Comment by telephon** [comment]
```supercollider
invokeMethod { arg method, arguments, synchronous = true;
		_QObject_InvokeMethod
		^this.primitiveFailed
	}
```

**Comment by telephon** [comment]
Ah here I found the fix, which is in develop: #3871

**Comment by telephon** [comment]
>Maybe we can re-awaken the CI?

sorry, I don't understand the abbreviation.

**Comment by brianlheim** [comment]
continuous integration

**Comment by patrickdupuis** [comment]
@telephon have your requests been met?

**Comment by patrickdupuis** [comment]
@scztt told me over Slack that this PR is passing the CI, but that it doesn't show here. @telephon can you approve?

**Pull request merged**
