### PR TITLE
whitespace fixes when posting and converting to compile string

### PR DESCRIPTION
**Pull request by telephon**
Following the agreement on #2931, this PR adjusts the `printOn` and `storeOn` methods of collections.

For example, it will post like the following:

```supercollider
[1, 2, 3]
List[1, 2, 3]
(a: 8, b:9)
// but still as usual:
([1, 2, 3]: 8, b:9)
('a b c': 8, b:9)
```

For this, it completes the interface `isIdentifier`, which now extends to any object.

### CODE REVIEW

**Comment by brianlheim** [comment]
I don't agree with this - as pointed out by @snappizz in that thread, this is a breaking change that could have unintended consequences similar to changing the printing behavior of floats. In that case, the change was justifued in that the new printing behavior indicated type more clearly. On the other hand this is a purely stylistic change. It also makes multidimensional array printing less readable. I think we should learn from our mistakes and not change this behavior.

**Comment by jamshark70** [comment]
Totally agree with @brianlheim - the consensus in the other thread was exactly the opposite of this PR.

We don't know who is parsing compile strings. Unjustified risk to change printing.

**Comment by snappizz** [comment]
adding decimal points to float printing in #3585 broke the ambisonic toolkit. similarly, i don't think this is worth the risk.

**Comment by telephon** [comment]
It would be more polite to wait for me to reply, and to close my own PR at least. 

A general remark: We are heading towards a situation where contributing is not only a waste of time, but also a source of dismay. While the former is unavoidable sometimes, the latter isn't.

**Comment by snappizz** [comment]
my apologies julian -- i didn't mean for my closing this issue to come off that way. i will try to be more considerate about that in the future.

it's just that right now, i'm trying to stay focused on getting in gear for 3.10, and i'm somewhat overwhelmed by the volume of PRs trickling in that aren't related to the small set of [critical tasks](https://github.com/supercollider/supercollider/projects/8) for the upcoming release. as a result i've mostly been ignoring PRs that aren't important to 3.10, and in vein with that, i'm also more eager to close them if the opposition seems strong.

since we're all volunteers and generally doing this for fun, i completely understand the approach of darting between whatever tasks seem most interesting. i do that myself, all the time. but now is a better time to keep our sights on 3.10 critical tasks.

**Comment by telephon** [comment]
thank you for your kind explanation, nathan, I understand. And thank you for taking over the task of organizing the release process, I know it can be a strain. 

I note that in a forum like this it is a little hard to make general announcements that are "pinned", so that everyone can see them.

Actually the current PR wasn't meant to be part of any 3.10 mindset, and if you all feel it is risky, we could postpone it to the next major version change. But I also believe it is dangerous to fetter ourselves in development in fear of breaking code.

**Pull request closed without merging**
