### PR TITLE
Osc.sc: fix audio rate TChoose

### PR DESCRIPTION
**Pull request by miczac**
thanks go to Daniel Mayer
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/choosing-random-value-in-synth-tp7624784p7624799.html

### CODE REVIEW

**Comment by danstowell** [comment]
What in the world? Github says "Files changed 2,164", "233 commits". Not sure this has been done right.

**Comment by bagong** [comment]
This is master. The edit and PR for 3.7 must be made on a branch that was created off 3.7...

**Comment by miczac** [comment]
On 18.Apr 2016, at 18:08 , danstowell <notifications@github.com> wrote:

> What in the world? Github says "Files changed 2,164", "233 commits". Not sure this has been done right.

W.. ? yes, that�s certainly not the idea! The prefilled fields for the PR also looked garbled on gituhb,
had to copy�n paste. something�s odd - my tree didn�t change since #1974. odd.

**Comment by danstowell** [comment]
Ah I see. @bagong is correct

**Comment by miczac** [comment]
Thanks Rainer ... I'll check my history ... I'm sorry for that.

**Pull request closed without merging**
