### PR TITLE
a question: why do all those commits end up in this pull request?

### PR DESCRIPTION
**Pull request by telephon**
I've done the following: 

- committed my changes to my current developer version (not master)
- checked out my master locally
- then cherry-picked the commits on top of it
- and then made a branch
- pushed it and made this pull request.

But now all those old commits are in the pull request. What is wrong with this workflow?

### CODE REVIEW

**Comment by bagong** [comment]
I might be wrong, but the way I think git the core problem is: "Your" master - the one in telephon, and the scgithub master are not the same. The PR will show all the differences, also in history.

I guess you started your telephon supercollider repo by "forking" supercollider with that github fork button, right? And then cloned that forked one and worked there, and brought in scgithub stuff by "merging" another branch from which you pull in scgithubs master, right? I think this "fork" button on github has created a lot of misconceptions and messy repo-relations.

The simple way is to clone the scgithub repo and then push that to your own repo as a separate *remote*. You never "fork". And you keep your own work in separate branches that you only push to your own repo if you need it public (to share with somebody or to create a pull request). scgithub master and "your own" master should never diverge, simply speaking, they should never be different branches.

The other, thing I seem to spot, is that you create a branch *after* you committed your additions, while you'd want to do that *first*. It's not really a problem for the pull request, which will still just show the difference between the two branches, but it means you mess up "your" master, which should really just be the same as sc's master.

**Comment by jamshark70** [comment]
I don't really agree that "non-forking" as @bagong suggests is any clearer or less error-prone than forking. As far as I can see, the only way to navigate the maze of possible git errors is to make mistakes (maybe a lot of them), and from each one, learn something not to do. A couple of years ago, I was complaining (quite literally, as I recall) that git was a mess, workflow was impossible, etc. But now I understand the workflow.

So, assuming you've "forked" the github way: you should have a remote called "origin" pointing to your fork, and another remote called "upstream" pointing to the main SC repository. In [your clone]/.git/config:

```
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
	url = https://github.com/jamshark70/supercollider-rename.git
[remote "upstream"]
	url = https://github.com/supercollider/supercollider.git
	fetch = +refs/heads/*:refs/remotes/upstream/*
```

1. The first step for any pull request is always, always, always, every time, *sync your local repository with upstream.* Github help explains how to do that: `git checkout master`, `git fetch upstream`, `git merge upstream/master`.
   - Also, don't ever commit or cherry-pick anything directly into your local master branch. That raises the risk of merge conflicts.

2. Always, always, always, every time, create your topic branch *immediately* after syncing. Never, never, never, never, never make any changes to master before doing `git checkout -b topic/blahblah`.

3. THEN commit/cherry-pick into the topic branch.

4. Push the topic branch to **origin**: `git push origin topic/blahblah`.

5. Now the webpage for the main supercollider repository should show that you recently pushed a branch, and add a button to create a PR from it.

If you created the topic branch before syncing, it might be possible to fix it retroactively:

```
git checkout master
git fetch upstream
git merge upstream/master
git checkout topic/blahblah (which was based on the out-of-date master)
git rebase master
```

*If* there are no conflicts, the last command will leave your topic branch with the new changes at the end of the history. (If there are conflicts, you might have to make a new topic branch from the up to date master and cherry pick.)

**Comment by bagong** [comment]
Shall we try to go to the bottom @jamshark70? It is quite possible that I still carry on a conceptual error in "my" workflow, and just present that as the right and simple way, because it "clicked" for me, and I think it is clear and correct now. 
Maybe an example from the bottom up helps. So I just "forked" supercollider/language-supercollider with github's button. And then I cloned "my fork" to my computer, I created a local repo from "my language-supercollider".

     git clone https://github.com/bagong/language-supercollider.git

Hopefully there were no submodules, otherwise I am up for consternation at some point.

Now at that stage the file .git/config in my new local repo shows:

    [core]
	   repositoryformatversion = 0
	   filemode = true
	   bare = false
	   logallrefupdates = true
	   ignorecase = true
	   precomposeunicode = true
    [remote "origin"]
	    url = https://github.com/bagong/language-supercollider
	    fetch = +refs/heads/*:refs/remotes/origin/*
    [branch "master"]
	    remote = origin
	    merge = refs/heads/master

So my first question is, where does "upstream" come from? (until now I find this word "upstream" extremely confusing)

**Comment by jamshark70** [comment]
> So my first question is, where does "upstream" come from?

Github's help pages.

https://help.github.com/articles/working-with-forks/

https://help.github.com/articles/configuring-a-remote-for-a-fork

https://help.github.com/articles/syncing-a-fork

My experience was: 1. Working with forks made no sense to me. 2. I read github's help. 3. It started to make sense.

**Comment by bagong** [comment]
Generally I find github's and git's documentation brilliant. But with that "fork" concept I would make an exception ;) Most people shouldn't "fork". A fork, as I understand it, is the first step to making yourself independent of the original repo. But exactly that is *not* what most people intend. They want to work from the original repo, and stay in sync with it, so their default remote should remain the original repo. When you're on master and "pull", the way I see it, you should get the original master. No weird "merging remote tracking branch" required.

And then, I agree, "never never never" commit anything to that master. Do anything you do on a branch you create *first*.

If you follow that logic, the first hurdle is, how do you publish your own changes in order to share them...

**Comment by bagong** [comment]
Haha, I had to take a break because I didn't remember how to create "your own" repo where you'd push changes you want to share to.
It seems you do need the github web interface. And at that point you could of course press fork from within the github supercollider repo, that wouldn't create a problem. But the step kind of muds the water, I find. Just go to your own repo, and add an empty repo called the same as the "original" repo. Initialize it empty.

And then locally just do:

    git remote add yourFavoriteRemoteName URLofYourJustCreatedNewRepo

And you push whatever you want public *there*. The simplest version is to rely on "where you are" locally, and push that to the remote:

    git push yourFavoriteRemoteName

And it'll go there. I would say "always always always" think *where* you want to push. Don't think of your local repo as kind of a mirror of "your own" github repo. It actually is the base from which you access the various remotes you work with. And the *default* remote to *pull master* should be the original supercollider repo.

**Comment by jamshark70** [comment]
While I see your point, for the moment, I prefer to get work done rather than split hairs over whether github is doing things in a sensible way.

Perhaps taking it up with their team, rather than with me, world be more productive.

**Comment by bagong** [comment]
I am not taking it up with you, just trying to help Giulio... I have seen this situation that people have two masters of basically *the same* repo (only on different remotes) many times, and always in relation with problems...

**Comment by telephon** [comment]
@bagong @jamshark70 Thank you very much, James and Rainer, for explaining this. I'll first try to get the pull request done correctly and then come back here. (Btw. github automatically closed the issue – this doesn't mean the question is closed).

I am trying to get things done with a fork, even if it's a little bit more difficult. There are a few important advantages, and I guess it is the recommended way to work in general.

**Comment by jamshark70** [comment]
I apologize for misinterpreting Rainer's messages as argumentation. I was also just trying to help by sharing the workflow that is working for me... Then I got a message saying basically, "What's up with that?"

I believe that the problem github is trying to solve with forks is that you can push to SC's main repository only if someone explicitly gave you write access, whereas, you can push to your own fork at will.

It would also not surprise me if github had some storage optimizations for forks. If 200 people clone a repository and push back, that's 200 copies on github's servers, but with some cleverness, they could base the forks off of one copy and save massive amounts of hard disk space. Or, forego the optimization and have to charge fees for the extra storage.

I tend to think the problems that git users get into have more to do with the "flexibility" = ease of screwing up in git in general, rather than specifically with this github feature. As I started off by saying, I doubt anybody becomes reasonably competent in git without completely fu...tzing up at least 3 repositories to the point that they have to be destroyed and recloned.

**Comment by bagong** [comment]
Yea, sorry too, James, I can see now how my response to your (very clear) post could be understood against my intentions. I was just trying to uncover even more hidden implications of a (actually great) post.
Best
.r.

**Comment by telephon** [comment]
So now thanks to your hints, I finally succeeded, and have a clean pull request (#1912).

The diagnosis first: I indeed had a "dirty" master branch, that is as @bagong said, my own instead of the one from the main repo (`upstream`, or as it is called in GitHubDesktop, `supercollider/master`).

Here are my steps, using a combination of GitHubDesktop and terminal. It assumes that you have commits in some other branch that you want to use to make a pull request.

1. make sure there is nothing in master that isn't anywhere else, that you would lose
2. in terminal, delete the master branch (GitHubDesktop doesn't allow it)
    - check out some other branch `git checkout <branchname>`
    - delete the master branch `git branch -D master` 
3. in GitHubDesktop, get a new master
    - checkout `supercollider/master`. GitHubDesktop suggests to copy it, do this.
    - make a new branch from it
4. in terminal: copy the commits to the new branch
    - use `git cherry-pick <commit-id>` to add the commits to the branch
5. in GitHubDesktop: push it, right-click on the repoand open the repo in the browser.
6. in the Browser: make the pull request with the green button

In the future it will be simple again: I'll need, as I was used to, only the steps `4-6`.

What should be noted somewhere indeed is that in our usual scenario:

**Don't commit anything to master** (if you have, delete it and get a new copy, steps `1-3`).

I do find it useful to keep a branch (`current`) which is a show-down of all that should be working at the same time. From here, I can take commits for specific pull requests.

All in all, it would actually be really useful if such things were a bit easier. This would allow more people to get involved more easily, and for smaller changes. Imagine you just want to fix a typo in a helpfile! Maybe such a custom simplification could be done in sclang?

github is just very general and more low-level than one may think sometimes.

**Pull request closed without merging**
