### PR TITLE
some code suggestions for blip examples

### PR DESCRIPTION
**Pull request by tiagmoraismorgado**

### CODE REVIEW

**Comment by telephon** [comment]
In most cases it is better to use interpreter variables rather than the current environment, as you may want to try the examples in all kind of situations, e.g. from within a proxyspace.

But this is just a suggestion, may be debatable.

**Comment by tiagmoraismorgado** [comment]
i will give the two options

**Comment by tiagmoraismorgado** [comment]
or perhaps we should leave this as a suggestion, which may come to discussion at a later stage, by members of the overall supercollider community. thank you so much for your help and kindness to help me to improve my skills, despite the fact that i have a far much lower level of supercollider development expertise, then most of you guys actually do. thank you so much

**Comment by crucialfelix** [comment]
This complicates the examples. They need to be as simple as possible. thanks for the PR though !

**Pull request closed without merging**
