### PR TITLE
GHA: install necessary compilers

### PR DESCRIPTION
**Pull request by brianlheim**
## Purpose and Motivation

gcc and clang < 9.x are no longer installed on ubuntu images, so we install them manually now:
https://github.com/actions/virtual-environments/issues/2950

it also appears the python install action doesn't work quite right, so i also added a commit to fix that

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks! Just curious, what was wrong/missing with python installation?

**Comment by brianlheim** [comment]
> what was wrong/missing with python installation?

setuptools wasn't installed

**Review by dyfer — APPROVED** [review]
Thanks!

**Comment by brianlheim** [comment]
thanks for the merge @dyfer . seems like GHA building a PR always uses the workflow from the PR branch, so everyone needs to rebase their PR branches now; is that right?

**Comment by dyfer** [comment]
I'm not sure... As a test I've closed/reopened an old PR of mine (#4709), last updated before we moved to GHA, and it triggered what seems to be the current gha workflow. I _think_ that if the build is triggered by pull request (not a push to another branch), then it should use the current workflow in develop.

**Comment by brianlheim** [comment]
ok, great! I must have been seeing something else then.

-------- Original Message --------

**Pull request merged**
