### PR TITLE
sclang: increase maximum number of midi ports

### LINKED ISSUE #2492: ERROR: Primitive '_DisconnectMIDIIn' failed. Index out of range.
I seem to be having trouble getting MIDI to work in my Supercollider install. I initially thought it was a problem with Modality Toolkit which I had installed, but it persists even with removed. I've tried both building my own from master as well as the 3.8.0 binary download. OS X Yosemite is my OS.

If I run:

```
MIDIClient.init
MIDIIn.connectAll
```

I get the following stack trace:

```
MIDI Sources:
	MIDIEndPoint("16A", "LTC Sync", -1350521786)
	MIDIEndPoint("FaderPort", "FaderPort", -1744234616)
	MIDIEndPoint("mio10", "DIN 1", -846562422)
	MIDIEndPoint("mio10", "DIN 2", -1543287909)
	MIDIEndPoint("mio10", "DIN 3", 1382450164)
	MIDIEndPoint("mio10", "DIN 4", 1739041593)
	MIDIEndPoint("mio10", "DIN 5", 184938043)
	MIDIEndPoint("mio10", "DIN 6", -2044030891)
	MIDIEndPoint("mio10", "DIN 7", -937346613)
	MIDIEndPoint("mio10", "DIN 8", 374286964)
	MIDIEndPoint("mio10", "DIN 9", -1036816190)
	MIDIEndPoint("mio10", "DIN 10", 1150784474)
	MIDIEndPoint("mio10", "HST 1", 1499504737)
	MIDIEndPoint("mio10", "HST 2", -604032301)
	MIDIEndPoint("mio10", "HST 3", -1885865213)
	MIDIEndPoint("mio10", "HST 4-10", 730710501)
	MIDIEndPoint("mio10", "ETH 1-4", -506382473)
	MIDIEndPoint("mio10", "USB 2", 1183143406)
MIDI Destinations:
	MIDIEndPoint("FaderPort", "FaderPort", -1653003416)
	MIDIEndPoint("mio10", "DIN 1", -1116144245)
	MIDIEndPoint("mio10", "DIN 2", 185365741)
	MIDIEndPoint("mio10", "DIN 3", 2072244728)
	MIDIEndPoint("mio10", "DIN 4", 1557475687)
	MIDIEndPoint("mio10", "DIN 5", 1855480831)
	MIDIEndPoint("mio10", "DIN 6", -1651344616)
	MIDIEndPoint("mio10", "DIN 7", -172092456)
	MIDIEndPoint("mio10", "DIN 8", 323647511)
	MIDIEndPoint("mio10", "DIN 9", -1825066537)
	MIDIEndPoint("mio10", "DIN 10", 1413141011)
	MIDIEndPoint("mio10", "HST 1", 356405092)
	MIDIEndPoint("mio10", "HST 2", 1005760319)
	MIDIEndPoint("mio10", "HST 3", -242845081)
	MIDIEndPoint("mio10", "HST 4-10", -829524007)
	MIDIEndPoint("mio10", "ETH 1-4", 537248947)
	MIDIEndPoint("mio10", "USB 2", -267914625)
-> MIDIClient
ERROR: Primitive '_DisconnectMIDIIn' failed.
Index out of range.
RECEIVER:
class MIDIIn (0x11e596800) {
  instance variables [19]
    name : Symbol 'MIDIIn'
    nextclass : instance of Meta_MIDIMKtlDevice (0x11f080c80, size=19, set=5)
    superclass : Symbol 'Object'
    subclasses : nil
    methods : nil
    instVarNames : instance of SymbolArray (0x11e596980, size=1, set=2)
    classVarNames : instance of SymbolArray (0x11e596b00, size=21, set=4)
    iprototype : instance of Array (0x11e596a40, size=1, set=2)
    cprototype : instance of Array (0x11e596c80, size=21, set=5)
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 350
    classFlags : Integer 0
    maxSubclassIndex : Integer 350
    filenameSymbol : Symbol '/Users/kamil/Downloads/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary/Common/Control/MIDIOut.sc'
    charPos : Integer 2982
    classVarIndex : Integer 235
}
CALL STACK:
	MethodError:reportError   0x124824838
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError   0x124824c58
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError   0x124824a48
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw   0x124823d38
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed   0x124824998
		arg this = <instance of Meta_MIDIIn>
	Meta_MIDIIn:disconnect   0x1206889d8
		arg this = <instance of Meta_MIDIIn>
		arg inport = 16
		arg device = <instance of MIDIEndPoint>
		var uid = -506382473
		var source = nil
	ArrayedCollection:do   0x1248248e8
		arg this = [*18]
		arg function = <instance of Function>
		var i = 16
	Meta_MIDIIn:disconnectAll   0x124824208
		arg this = <instance of Meta_MIDIIn>
	Meta_MIDIIn:connectAll   0x124824368
		arg this = <instance of Meta_MIDIIn>
		arg verbose = true
	Interpreter:interpretPrintCmdLine   0x12068b018
		arg this = <instance of Interpreter>
		var res = nil
		var func = <instance of Function>
		var code = "MIDIIn.connectAll"
		var doc = nil
		var ideClass = <instance of Meta_ScIDE>
	Process:interpretPrintCmdLine   0x1248242b8
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_DisconnectMIDIIn' failed.
Index out of range.
RECEIVER: MIDIIn
```

### PR DESCRIPTION
**Pull request by telephon**
The limit of 16 was hit too easily.

This fixes #2492, perhaps.

### CODE REVIEW

**Comment by kisielk** [comment]
how about in `SC_AlsaMIDI.cpp` ?

**Comment by telephon** [comment]
good point, I'll open a new PR.

**Comment by kisielk** [comment]
You can always just add another commit to the branch and the PR will update..

**Comment by telephon** [comment]
yes, but I also had typos in this one, which I hadn't noticed because I didn't know that it doesn't compile all the files in `lang/LangPrimSource`.

**Comment by telephon** [comment]
The new one is #2494.

**Pull request closed without merging**
