### PR TITLE
docs: add support for evaluating code regions

### LINKED ISSUE #3777: help-browser: cmd-enter on code evaluates all
The expected behavior of `cmd-enter` is evaluate region, if there is no explicit region  (by parentheses) then evaluate the line (as `shift-enter` would do).

In the help browser, after the webview reform,  `cmd-enter` assumes the whole block between `code::` sections to be a region. This makes many helpfile examples unusuable, as the assume that you step line by line through them.

I'm assigning you @scztt because you have just finished all these excellent improvements, and maybe you know where the glitch comes from.

It is kind of urgent, as it affects a larger portion of the helpfiles.

### PR DESCRIPTION
**Pull request by htor**
this pull fixes #3777. please test with different code examples!

it provides:

* single line code eval
* region code eval
* double-click parens selects whole region
* syntax highlighting after typing/editing (new)

it uses the [codemirror](https://codemirror.net/) library for editing, which is more robust than the prettify+dom traversal way of doing things and makes it easy to extend/maintain the editor with new features in the future.

### CODE REVIEW

**Comment by telephon** [comment]
excellent, thank you. This is a lot better already!

I've tested with the `ProxySpace` helpfile, first code block, and `Klang`.

- it would be good if the cursor would do a step down by default after running a line (or use the setting in the preferences) -- in many examples, a line by line evaluation is assumed.
- the line `p[\out] = Pbind(\dur, 0.03, \freq, Pbrown(0, 1, 0.1, inf).linexp(0, 1, 200, 350));` does a wrong autoselection on cmd-enter: instead of the full line, it selects the part between the parentheses
- shift-enter should evaluate the whole line, even if within a selection

**Comment by htor** [comment]
thanks for testing @telephon 

> the line p[\out] = Pbind(\dur, 0.03, \freq, Pbrown(0, 1, 0.1, inf).linexp(0, 1, 200, 350)); does a wrong autoselection on cmd-enter: instead of the full line, it selects the part between the parentheses
shift-enter should evaluate the whole line, even if within a selection

this should work now

> shift-enter should evaluate the whole line, even if within a selection

this is another issue (#3877) which i'm hoping to fix too, but it needs some c++ code to handle an event. cmd-shift works if you open the docs in a browser and press it.

about the automatic cursor-down suggestion - i think it would be best to mimic the main editor as much as possible and not have special rules and different behaviour than what people are used to.

**Comment by telephon** [comment]
works well! 

could you take a look at that one, too?:

>it would be good if the cursor would do a step down by default after running a single line without selection (or use the setting in the preferences) -- in many examples, a line by line evaluation is assumed.

**Comment by htor** [comment]
> This would be on cmd-enter, when the region is just one line.

and shift-enter too it seems? it's possible to implement it i guess. it's gonna take a little effort to parse the settings file and such. i'm going to have to experiment with it.

**Comment by telephon** [comment]
>and shift-enter too it seems? it's possible to implement it i guess. it's gonna take a little effort to parse the settings file and such. i'm going to have to experiment with it.

let's keep this for another thread/PR.

**Comment by htor** [comment]
allright, then i consider this pull complete.

**Comment by brianlheim** [comment]
@htor - could you please resolve the merge conflicts on this PR? then it should be ready for merging.

**Comment by htor** [comment]
@brianlheim ok, resolved.
there's are some stylistic changes in the help browser since last time (typography looks funky), so i'd like to propose an adjustment to that. imo, before any release that should be addressed. guess that should be another pull?

**Comment by htor** [comment]
@brianlheim the ide editor temporarily selects the regions/lines after eval too, no? 
the only exception is when the cursor i near a start/end parenthesis.

**Comment by scztt** [comment]
The IDE has to access the code being evaluated by querying the selection from the help browser. It's possible that we could somehow save the selection prior to evaluate, and then put that selection back afterwards? I'd consider that a separable issue - this PR is super valuable in itself, I'd say open a separate issue on the eval selection behavior.

**Comment by htor** [comment]
this is an easy fix, i'll push a commit to fix, just going to sleep first.

**Comment by htor** [comment]
okay, i understand the problem now, this is an easy fix. i'll push fix very soon

**Comment by htor** [comment]
this last commit fixes the issue of de-selecting the selection on eval. the behaviour is like the ide now, with background flashing selections.

**Comment by snappizz** [comment]
thanks for the work on this!

in the IDE, ctrl+enter evaluates selection/line/region, while shift+enter evaluates line.

with this PR (i had to merge 3.10 into it to get the shortcuts working on linux), it appears that ctrl+enter evaluates a line, and shift+enter flashes the current line but does not appear to evaluate any code.

**Comment by brianlheim** [comment]
@snappizz The shift-enter point is covered above.

I don't see any inconsistency between the IDE and help browser in eval behavior. What is a specific code snippet that illustrates the difference?

**Comment by snappizz** [comment]
ah alright. anyways, for ctrl+enter:

```
(
3
)
```

if i put my cursor right after the final `)`: ctrl+enter in the IDE evaluates 3. ctrl+enter in the help browser gives me a syntax error as if it's evaluating just the `)`.

**Comment by htor** [comment]
@snappizz i can't reproduce that. testing [045f9d074] on my mac 

```
(
3
)
```

evals to `3`

**Comment by snappizz** [comment]
yeah, i'm up to date and i did build. ¯\\_(ツ)_/¯

i'll merge and we can figure out what's wrong later. probably a Qt-level issue.

**Pull request merged**
