### PR TITLE
Make Jack Startup environment variables usable.

### PR DESCRIPTION
**Pull request by madskjeldgaard**
## Purpose and Motivation
Fixes https://github.com/supercollider/supercollider/issues/5260

This PR makes it possible to set the Jack environment variables on Linux to let SC automatically connect it's inputs and outputs to other jack nodes on startup. These were hardcoded to be "system" by default and were never checked by the system but they are with this PR.

The usage of these has been documented as well in the LinuxPlatform help file. 

## Types of changes

- Documentation
- Bug fix

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks! This works as advertised.

Regarding the help: we now have the [Audio device selection](https://doc.sccode.org/Reference/AudioDeviceSelection.html) guide, where environment variables for JACK are mentioned. I'd prefer this information to stay in one place. 

My suggestion would be to make changes there if needed (maybe adding the info on setting env vars in shell profile?), and possibly link to it from the LinuxPlatform help file, if you think that's useful. What do you think?

**Comment by madskjeldgaard** [comment]
> Thanks! This works as advertised.
> 
> Regarding the help: we now have the [Audio device selection](https://doc.sccode.org/Reference/AudioDeviceSelection.html) guide, where environment variables for JACK are mentioned. I'd prefer this information to stay in one place.
> 
> My suggestion would be to make changes there if needed (maybe adding the info on setting env vars in shell profile?), and possibly linking to it from the LinuxPlatform help file. What do you think?

Ah yes, I see. I hadn't seen that guide before. I will remove it and change it to a link.

**Comment by madskjeldgaard** [comment]
I moved the info to the audio device guide now and added a link to it in the linuxplatform class :)

**Comment by madskjeldgaard** [comment]
And did a tiny bit of cleanup in the linux section of audio device guide. I found it quite hard to read the way it was with lists and yellow notes breaking up the reading pattern so I simplified it a bit. Hope it's okay.

**Comment by madskjeldgaard** [comment]
and now it should be done imo :)

**Comment by dyfer** [comment]
Great, thanks for the changes.
One small question: is setting environment variables for Jack really more commonly done in bash profile, as opposed to from within SC? Since it is set to "system" by default, it would likely be changed only for when we need it for a particular scenario/project, which might be more appropriately done from the SC script, as opposed to a "user default". My suggestion is that setting them in bash profile should be an alternative to setting them from SC, not the other way around. What's your thinking on this?

**Comment by brianlheim** [comment]
> My suggestion is that setting them in bash profile should be an alternative to setting them from SC, not the other way around. What's your thinking on this?

i agree with this. setting them in a shell profile will only affect things launched from the shell, and not via other app launchers like dmenu. doing this within SC is more reliable

**Comment by madskjeldgaard** [comment]
> Great, thanks for the changes.
> One small question: is setting environment variables for Jack really more commonly done in bash profile, as opposed to from within SC? Since it is set to "system" by default, it would likely be changed only for when we need it for a particular scenario/project, which might be more appropriately done from the SC script, as opposed to a "user default". My suggestion is that setting them in bash profile should be an alternative to setting them from SC, not the other way around. What's your thinking on this?

I agree! This is definately a special scenario (probably also why this bug hadn't been found before) :)

**Comment by dyfer** [comment]
> I agree! This is definately a special scenario (probably also why this bug hadn't been found before) :)

Great, thanks! Would you mind changing the docs accordingly, as I suggested before?

**Comment by madskjeldgaard** [comment]
> > Great, thanks for the changes.
> > One small question: is setting environment variables for Jack really more commonly done in bash profile, as opposed to from within SC? Since it is set to "system" by default, it would likely be changed only for when we need it for a particular scenario/project, which might be more appropriately done from the SC script, as opposed to a "user default". My suggestion is that setting them in bash profile should be an alternative to setting them from SC, not the other way around. What's your thinking on this?
> 
> I agree! This is definately a special scenario (probably also why this bug hadn't been found before) :) 

Sure!

**Comment by madskjeldgaard** [comment]
Should be fixed now, @dyfer

**Review by dyfer — APPROVED** [review]
Thanks!

**Pull request merged**
