### PR TITLE
class library: refactor maybe class

### PR DESCRIPTION
**Pull request by telephon**
Instead of creating dedicated FunctionProxy objects, just create
appropriate Maybe objects with functions. This reduces the number of
classes necessary and allows us to extend the Maybe class consistently
for extending LazyEnvir.

Caveat: for now, the post methods have found no replacement.

### CODE REVIEW

**Comment by simdax** [comment]
I'm just checking for dup. I just have the dup you've changed in this fork.

a=LazyEnvir().make{
	~x= ~a ! ~a;
	~z= ~a ! [~a,~a];
}
a.use{
	~a=2; 
	~x.value.postln; // ok
	~z.value.postln; // nop
}

**Comment by telephon** [comment]
Yes, this is one of those things that simply can't work easily. The "arraying" operation that leads to `[~a, ~a]` is not delegated through the environment and thus cannot lead to a placeholder.

**Comment by telephon** [comment]
In other words, this one works:

```
~a = 2;

~x = ~a ! ~a ! ~a;
~x.value
```

**Comment by simdax** [comment]
Do you know why this don't work ?

```
	dup { arg argument;
		^
		 if(argument.isCollection){
		 	argument.reduce(this,this.dup(_))
		 }
		this.composeNAryOp(\dup,[argument])
	}

```

**Comment by telephon** [comment]
@simdax 

I suppose you'd want `reduce` take a binary operator, or a binary function, like `this.dup(_, _))`. (untested)

**Comment by simdax** [comment]
oh gosh I'm tired... that was of course 'inject.'.. (*´ー｀*)

I've pull requested. That's maybe not the kind of solution you want ?

**Comment by simdax** [comment]
In fact, the result was not good. That's a hard problem


a=LazyEnvir().make{
	~a=2; ~b;
	~c = ~a ! ~b ! ~b;
	~d = ~a ! [~b,~b];
};
a[\b]=4;
a[\c].value.postln;
a[\d].value.postln;

**Comment by simdax** [comment]
```
Have you any idea about something like that ?

LazyEnvir().make{
	~notes=8; 
	~a={5.rand} ! ~notes;
}

```

**Comment by telephon** [comment]
Good you mention this.

Yes, the operator `dup` (or `!`) doesn't do a double dispatch, like e.g. `+` and all the math ops. So it can't detect that in your expression you have a "free variable", that is a proxy like `~notes`.

The current solution is to just make a function when necessary:

```
LazyEnvir().make{
    ~notes=8; 
    ~a= { {5.rand} ! ~notes.value };
}
```

A potential "proper" solution would have to analyze the syntax probably: because we can't implement automatic multiple dispatch for the whole system.

**Comment by simdax** [comment]
So we could maybe hack Interpreter preprocessor for it acts differently when we parse a ".use" function e.g.

**Comment by simdax** [comment]
But in fact, your example is not as easy. Compare :+1: 

a=LazyEnvir().make{
    ~notes=8; 
    ~a= { {5.rand} ! ~notes.value }.inEnvir(a);
};
a.at(\a).value

a=LazyEnvir().make{
    ~notes=8; 
    ~a= { {5.rand} ! ~notes.value };
};
a.at(\a).value

**Comment by telephon** [comment]
Sure – also good to keep in mind – but this would also be true for your example.

We could make this automatic in LazyEnvir, perhaps.

**Comment by telephon** [comment]
this can be postponed.

**Comment by snappizz** [comment]
ok! added to [backlog](https://github.com/supercollider/supercollider/projects/7)

**Pull request closed without merging**
