### PR TITLE
Subprocess

### PR DESCRIPTION
**Pull request by telephon**
Is this still interesting? Is this considered complete?

### CODE REVIEW

**Comment by timblechmann** [comment]
google for "fork multithreaded program" and read (and understand) the fork man pages. i'd strongly vote against this as it is a fragile hack

**Comment by telephon** [comment]
Ok, thanks for the info -- then we can close this one.

**Comment by crucialfelix** [comment]
true about multi-threaded programs, but most use cases of spawning a subprocess are not. @timblechmann do you think this is a fragile implementation even for single process subprocesses ?

the current situation in sc is quite weak. 

sclang has to poll scsynth to determine if its crashed and then has to make guesses about if its really dead or not. it doesn't even really know when its started until OSC connects.

when I was doing the Quarks I realized that there isn't a way to get stdout, stderr AND the result code from the current shell command methods. so you can call commands and get the stdout, but you don't know if there was an error.

cmd.unixCmdGetStdOut can not tell me if the result was non-zero

unixCmd has a callback but that gets the result code and pid, but the output is sent to stdout and you cannot capture it.

Pipe does not expose the pid, so again you can't find out what the result code was.

this could be fixed easily just in sc code, but I decided to just finish Quarks without affecting anything else in the class library.

I definitely understand the motivation for what @lijon has done here.
I've just glanced at it a bit and don't have a proper critique right now.

**Comment by timblechmann** [comment]
this PR is not about a subprocess (as in spawning an child process). the problem is more about the fork system call. also forking is not bad per se, but one has to be careful.
* forking a multi-threaded process will only create a single-threaded child. there is also a lot of undefined behaviour e.g. if pthread data structures contain process IDs.
* resources like file descriptors will be copied as well, which might cause some funny behaviour of the child process affecting the parent.

@crucialfelix, i'd be very much in favour of having a class to spawn and manage subprocesses, e.g. based on boost.process (http://www.highscore.de/boost/process/), but that is completely orthogonal to this PR

**Comment by crucialfelix** [comment]
ok, thanks ! now I get it

**Pull request closed without merging**
