### PR TITLE
[Help] Fix broken Help browser navigation

### PR DESCRIPTION
**Pull request by patrickdupuis**
Purpose and Motivation
----------------------

This PR fixes broken navigation inside the IDE's help browser, as well as in the language HelpBrowser. On my system at least, navigating help files when using `HelpBrowser` was entirely broken. Clicking on a link never worked. The situation was more or less the same for the IDE's help browser. Links worked 1 out of 4 times approximately.

This PR add a small deferral time to `ScIDE.prSend` and `HelpBrowser.goTo` in order to correct the issue. Simply deferring is not enough. There needs to be a small delta time.

Types of changes
----------------

- Bug fix (non-breaking change which fixes an issue)

Checklist
---------

- [ ] All tests are passing
- [ ] If necessary, new tests were created to address changes in PR, and tests are passing
- [ ] Updated documentation, if necessary
- [X] This PR is ready for review

Remaining Work
--------------

### CODE REVIEW

**Comment by prko** [comment]
Thanks for this!
I hope that this fixes #3901 as well.
Might it be possible?

**Comment by patrickdupuis** [comment]
I'll add a comment saying this is a hack.

The change to `HelpBrowser` is the one we have been discussing on Slack with all the Qt debugging. Adding the deferral here is the best solution I found. The change to `ScIDE` is the equivalent fix for the IDE's help browser.

**Comment by brianlheim** [comment]
@patrickdupuis in the future it'd be good to use either FIXME or TODO so it can be found more easily later

**Comment by patrickdupuis** [comment]
Thanks for the suggestion @brianlheim!

**Comment by patrickdupuis** [comment]
This has a negative side-effet when using `HelpBrowser` on a fast system. Some pages will show the broken link page for breif moment before correctly loading. I need to rethink this.

**Comment by prko** [comment]
Is it possible to remember the current location when a new document is accessed?
1.  by clicking or by pressing CMD+d, SinOsc help document is opened in the Help browser, and at that time the previous location is remembered.
2. by clicking or by pressing CMD+d, FSinOsc help document is opened in the Help browser, and at that time the last position in the previous location (in this case, SinOsc help document) is remembered.

**Pull request closed without merging**
