### PR TITLE
Fixes Scope Window Error 

### PR DESCRIPTION
**Pull request by patrickdupuis**
Fixes Issue #1878 as proposed by @jamshark70.

### CODE REVIEW

**Comment by telephon** [comment]
should this go into 3.7 ?

**Comment by bagong** [comment]
Maybe we could make a little list of commits that would be a pity to miss out and cherry pick them in one go.

**Comment by crucialfelix** [comment]
I would like to avoid the cherry picking thing. Its only for emergencies, not as a normal part of the release process. I'm going to try to write up a formal release process document.

Also when issues and PR are closed then they show up in the automated CHANGELOG.md

**Comment by bagong** [comment]
okle

**Comment by patrickdupuis** [comment]
Can I delete this Pull Request now that I re-created it for 3.7?

**Comment by telephon** [comment]
yes, it'll be merged back into master from 3.7 once 3.7.1 is out.

**Comment by crucialfelix** [comment]
yes, like j said

thanks for moving it to 3.7

I'll get more PRs processed this week

On Tue, Mar 22, 2016 at 8:57 PM Julian Rohrhuber <notifications@github.com>
wrote:

> yes, it'll be merged back into master from 3.7 once 3.7.1 is out.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/pull/1902#issuecomment-199991248>
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Pull request closed without merging**
