### PR TITLE
optimize degrad/raddeg

### PR DESCRIPTION
**Pull request by patrickdupuis**
## Purpose and Motivation

This PR simplifies methods `degrad` and `raddeg`.

## Types of changes

- slight improvement

## To-do list

- [X] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [X] This PR is ready for review

### CODE REVIEW

**Comment by patrickdupuis** [comment]
I'll test again. I was sure that these changes produces exactly the same output except for maybe a small rounding correction.

**Comment by patrickdupuis** [comment]
I'm sorry if I'm just not getting it. Aren't these equivalent?

```supercollider
a = 303.49; b = 1.89pi;

// degrad
a * (pi/180)
a * pi / 180
a * 0.017453292519943


// raddeg
b * (180/pi)
b * 180 / pi
b * 57.295779513082
```

**Comment by brianlheim** [comment]
> except for maybe a small rounding correction.

yes, that's what i'm saying. it is not the same output, so it should go into a future release rather than become part of this release cycle which already has a beta release out

**Comment by patrickdupuis** [comment]
Ok. Do you want me to point this towards `develop`?

**Comment by brianlheim** [comment]
on my machine:

```
a = 303.49; b = 1.89pi;

// degrad
x = a * (pi/180)
y = a * pi / 180
z = a * 0.017453292519943
x == y; // true
y == z; // false


// raddeg
x = b * (180/pi)
y = b * 180 / pi
z = b * 57.295779513082
x == y; // true
y == z; // false
```

you can also randomly generate floats and quickly find values for which all three differ. in fact that appears to be the case for about 30% of floats on my machine, sampling uniformly at random across bit patterns.

`-0.16640754110721` is one such value on my machine for which the results of `x * (pi/180)`, `x * pi / 180`, and `x * 0.017453292519943` all produce different results.

**Comment by jamshark70** [comment]
I think the change is acceptable for UGens because the server does single-precision math: the proposed constants are written with more than enough precision. And the server is doing the math operations repeatedly -- changing two binops '*' and '/' into one binop would be a valuable efficiency gain. (I did test: aKrUnit.degrad and aKrUnit * 0.017453292519943 report as fully equal.)

But I agree with Brian that the language-side change sacrifices precision and can't be considered to be correct.

You *could* do it by storing the value pi/180 in a variable somewhere, and using the variable instead of a decimal constant. I just tried to do that in `SimpleNumber` but it complains that it's an intrinsic class, and doesn't allow new variables to be defined.

So the other way would be to move the math into C++. The primitives could use static variables for pi/180 and 180/pi. That would give you maximum efficiency with no loss of precision.

**Comment by patrickdupuis** [comment]
I don't know how primitives work, but I agree that would be ideal.

**Comment by brianlheim** [comment]
this is one of those things for me that always ends up having fractal levels of complication...

i thought about this a bit more, and i think really the only issue is the order of operations for the simple number version. i don't know why i didn't think of this sooner but all you need to do is add more precision to get the right double value, since doubles are accurate up to about 15 decimal places: 

```
0.017453292519943 == (pi/180) // false
0.017453292519943295474 == (pi/180) // true

57.295779513082 == (180/pi) // false
57.295779513082322865 == (180/pi) // true
```

(i got these via `(180/pi).asStringPrec(20)`). i think depending on the runtime's implementation of the c stdlib function `atof` and your processor these values could be slightly different, but that's yet another reason why FP math is cursed, no cause for alarm. :)

'correct' is not really a term that applies since fp math is inexact by nature. however, i think we would probably have more accurate results using a single fp multiplication like Patrick is using here. at least experimentally, when i compare the output from both methods to the 'true value' as calculated by WolframAlpha, the single multiply result is always closer, which conforms to intuition.

so this is my summary of what's up here:
- UGen change is fine as is
- SimpleNumber change produces different results no matter what
- SimpleNumber change would make results more accurate if Patrick adds 5 or so more decimal places of precision to the literals

and what i'd prefer to see happen:
- Patrick adds 5 or so more decimal places of precision to the literals in SimpleNumber
- change goes into develop
- we note this in the log as 'degrad and raddeg became more accurate'

**Comment by patrickdupuis** [comment]
That sounds good to me! I'll look into `asStringPrec` and will add more precision to the literals. I've already changed this PR so that it will go into `develop`.

**Comment by jamshark70** [comment]
Agreed with all.

**Comment by redFrik** [comment]
i disagree with this change.
what's the gain in numbers?
but more important: pi / 180 is much more educational and show what is going on.
at least add comments after those magic number. `// pi / 180`

**Comment by brianlheim** [comment]
> what's the gain in numbers?

slightly faster code

> but more important: pi / 180 is much more educational and show what is going on.
> at least add comments after those magic number. // pi / 180

the comments are already added...

**Comment by patrickdupuis** [comment]
I improved styling and comments. I gave both UGen and SimpleNumber the same amount of precision. I get that it might not really be necessary for UGen, but I thought 
"why not?". I can change that if you prefer.

**Comment by dyfer** [comment]
Correct me if I'm wrong, but wouldn't calculating `(pi/180)` in `*initClass` (and using that variable in `degrad`/`raddeg`) be a way to maintain exactly the same behavior while optimizing the calculation?

**Comment by telephon** [comment]
The most idiomatic optimization would be to add a primitive. It is a bit of work, but not really difficult, you just copy a similar one and go through all the cases.

**Comment by jamshark70** [comment]
> Correct me if I'm wrong, but wouldn't calculating (pi/180) in *initClass (and using that variable in degrad/raddeg) be a way to maintain exactly the same behavior while optimizing the calculation?

You can't add variables to intrinsic classes without changing the backend. (I already tried this, and noted that fact here, a few days ago.)

> The most idiomatic optimization would be to add a primitive. It is a bit of work, but not really difficult, you just copy a similar one and go through all the cases.

It's true that it's not difficult (my C skills are not great but I have been able to figure it out in the past, for e.g. Event:isRest), but I'll agree with Brian that there is not much benefit for a single floating point multiplication. (`isRest` was worth it because it encapsulated multiple conditions and iteration.)

I think, let's not beat this one to death. Reserve the scrutiny for issues that are actually complex.

**Comment by brianlheim** [comment]
> I think, let's not beat this one to death. Reserve the scrutiny for issues that are actually complex.

+1

> Correct me if I'm wrong, but wouldn't calculating (pi/180) in *initClass (and using that variable in degrad/raddeg) be a way to maintain exactly the same behavior while optimizing the calculation?

that would require an extra load instruction loading from relatively distant memory, there's really no point to doing that when you can use an inline literal.

**Pull request merged**
