### PR TITLE
Update nova external libraries

### PR DESCRIPTION
**Pull request by TristanCacqueray**
Purpose and Motivation
----------------------

This change fixes the obsolete FSF address in nova-simd and nova-tt headers.

Types of changes
----------------

- Bug fix (non-breaking change which fixes an issue)

Checklist
---------

- [ ] All tests are passing
- [ ] If necessary, new tests were created to address changes in PR, and tests are passing
- [ ] Updated documentation, if necessary
- [ ] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
thanks @TristanCacqueray! have these changes been submitted upstream?

**Comment by TristanCacqueray** [comment]
@brianlheim yes, this is updating submodule for https://github.com/timblechmann/nova-simd/commit/513fa0c05bb6972b4e0f60e85773a2cf29f65e38 and https://github.com/timblechmann/nova-tt/commit/9fe4c3c5cd0dbbec327b9c6cd5f56eabf4ed59c4

**Comment by snappizz** [comment]
thanks tristan!

sorry if this is tangential but does anyone know why we have a copy of nova-simd/nova-tt rather than proper git submodules?

**Comment by brianlheim** [comment]
@TristanCacqueray cool, thanks!

**Pull request merged**
