### PR TITLE
Build - update README to add FLAC support for OS X

### PR DESCRIPTION
**Pull request by samaaron**
* remove old libsndfile - preferring libsndfile from
  homebrew or manual install
* update build instructions to use external libsndfile
* on a rebuild FLAC support now works!

Discussion here: #1783

### CODE REVIEW

**Comment by bagong** [comment]
The travis build breaks because the cmake arguments for soundfile are not in the command that triggers the travis build.

A more general remark: it was an aim during the last years to get rid of the necessity to add arguments to cmake. If the FindSndfile cmake-module was modified to point to the homebrew install (and the reference to the bundled binary deleted) no cmake argument would be necessary (I am pretty sure, except there is a hard-coded pointer to the external-libraries somewhere).

In the past it was tricky to reliably point to "the latest" version of a library in homebrew, but now, since the latest always seems to be mirrored into /usr/local/bin|lib|include, it could be quite easy?

Best
.r.

**Comment by bagong** [comment]
Hey Sam,

I made something for 3.7. Let's see if the others think it is too late. Should have been done 2 years ago ;)
#1870 

Regards
.r.

**Comment by samaaron** [comment]
Great! :-)

**Comment by crucialfelix** [comment]
I think we should take the one from @bagong that goes into 3.7 and fixes the cmake

thanks to both of you guys !

**Comment by samaaron** [comment]
Great! :-)

**Comment by bagong** [comment]
To do a really tidy job one should remove the references to the old "universal" logic and the version control things that are irrelevant now. That could be done together with removing the bundled library. I am also not sure if switching from static to dynamic libraries has any implications...
Also in some other context I noticed that Qt soundfileview has libsndfile as dependency. While there is an option to build without libsndfile, the build will break because of that dependency. Not sure what happens if you build without IDE.

**Pull request closed without merging**
