### PR TITLE
Add option for LIB_SUFFIX

### PR DESCRIPTION
**Pull request by tdug**
## Purpose and Motivation

This makes the option of `LIB_SUFFIX` visible with `cmake -L`

## Types of changes

- Documentation

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

### CODE REVIEW

**Comment by tdug** [comment]
Related: https://github.com/supercollider/sc3-plugins/pull/328

**Comment by dyfer** [comment]
Thanks @tdug 
Sorry I'm not aware - could you explain in what circumstances we need this option?

**Comment by tdug** [comment]
> Thanks @tdug Sorry I'm not aware - could you explain in what circumstances we need this option?

@dyfer - This option already exists, and is documented [here](https://github.com/supercollider/supercollider/blob/develop/README_LINUX.md#library-suffix) This pull request documents that option when running `cmake -L`.

**Comment by dyfer** [comment]
Thanks for the explanation!

**Review by dyfer — APPROVED** [review]

**Pull request merged**
