### PR TITLE
Scide/line number

### PR DESCRIPTION
**Pull request by vdonnefort**
Hi,

Here's some patches to improve the line indicator on scide.

### CODE REVIEW

**Comment by telephon** [comment]
Two comments:
- Could actually use a little less space on the left
- when no colors are set, the numbers are invisible. This is the default!

Could you please try and fix?

**Comment by timblechmann** [comment]
@telephon, please ask for a fix before merging.

@vdonnefort, one more point (i'm also having the issue of transparent line numbers): the focus rectangle was introduced to have a visual feedback, which of the splits is active. removing this  might be controversial. @muellmusik or @jleben, could one of you review this?

**Comment by telephon** [comment]
@timblechmann yes, sorry, looked unproblematic at first.

**Comment by muellmusik** [comment]
Sure, @timblechmann. Sorry I didn't catch this earlier.

The problem is not simply visual feedback of which split is active, although that is important, of course. The issue is the IDE's unusual tab scheme, as the tabs do not look like actual tabs of something in the expected fashion, and are basically just a set of buttons not clearly associated with the thing they are affecting. 

Because of this it is unclear which split the active tab is referring to, or which split will change when you click a tab. The visual feedback helps, but I think this is still a problem even with it, so yes, I am opposed to removing it.

To be fair, I suppose adding the feedback violated the design principle of the IDE, 'do it right or don't do it', since it just tries to improve the situation rather than addressing the root problem. But then the root problem (the unassociated tab bar design) violates that principle too. PR #1155 is an attempt to address this. Further work has been done on that branch, but as it was held up by some queries it's now diverged a lot from master (an unfortunately common occurrence in SC development, particularly with any large changes) so it may take a while before that will be updated. It might be worth revisiting the visual feedback once that's done.

But IAC, I think this merge should be reverted, at least in it's current form.

**Comment by telephon** [comment]
>But IAC, I think this merge should be reverted, at least in it's current form.

How would you do it? I just did:
````git reset --hard d3d379a0bd08859d1617c5ec8cc2be657ab2304e````

so locally I have it correctly. Now how to push it back to master?

**Comment by vdonnefort** [comment]
Hi,

I understand that removing the focus rectangle can be controversial, but:

1. This PR is not only about removing the focus rect. It also fixes fg and font for Line Number which were before just ignored!

2. I'm using vim so not very conscient of what are using others IDE but I looked at QtCreator and didn't seen any focus rectangle, even when editor is split. Is the cursor not enough to indicate the current panel?

In the end, if you think the focus rect is necessary let's bring it back.

I was aware that these modifications could be too intrusive, that's why I sent an e-mail on the sc-dev ML describing what I wanted to do :)

**Comment by muellmusik** [comment]
Hey @vdonnefort, you're quite right that you raised it properly, and I apologise again for not catching this before.

If you want to submit a version without the focus rect changes, I have no particular objection. Just cursor is not enough, as it's small, and may not even be visible. In any case, I don't buy the argument that improving cosmetics (subjective anyway) should trump usability.

@telephon I believe if you push that it will erase the history. That could cause problems if anybody pulls later. A revert commit would be safer, although leaving the mess. If just reverting ebdb0b8 doesn't break this branch, that could be one approach.

**Comment by vdonnefort** [comment]
@muellmusik, @timblechmann, @telephon 

I just pushed into this following PR https://github.com/supercollider/supercollider/pull/1297 a patch which fixes the foreground transparency.

**Comment by muellmusik** [comment]
> I just pushed into this following PR #1297 a patch which fixes the foreground transparency.

Sorry, but @vdonnefort does that restore the focus rect?

**Comment by muellmusik** [comment]
Okay, I see that PR #1297 actually is branched before this branch was merged, so not directly related to this?

To be honest, I'm actually unclear as to what the line numbers stuff is supposed to do exactly. When I built this I got the effect below; not good!

untitled

Seems to have created something called 'my old theme'.  It looks okay when I switch from that to 'default', but I'm pretty sure my old theme was default. This could be a bit jarring for users.

IAC, the extra width seems wasteful:

untitled

and I think especially users on small screens might prefer to have the space for code.

As far as the focus ring goes, note that if you choose to hide the line numbers, you get almost no feedback as to which split is active:

untitled

@vdonnefort could you please fix that. Otherwise I think we should revert this.

**Comment by vdonnefort** [comment]
> Okay, I see that PR #1297 actually is branched before this branch was merged, so not directly related to this?

Yes, so as the foreground transparency problem, that's why I pushed into this branch.

> To be honest, I'm actually unclear as to what the line numbers stuff is supposed to do exactly. When I built this I got the effect below; 

Can you tell me more about this problem, the configuration? Can you check your theme? It could be linked to the transparency fix, now the transparency is really applied.

> I think especially users on small screens might prefer to have the space for code.

The idea was to match the Qt Creator line numbering. If you dislike it, we can revert. 

> As far as the focus ring goes, note that if you choose to hide the line numbers, you get almost no feedback as to which split is active:

We already discussed that, but I thought you'd revert it.

So, I will create a branch with reverted line numbering width and the focus rect.

**Comment by jamshark70** [comment]
After a recent git pull, I also found that line numbers were transparent. When the new IDE version updated the color theme, it created an entry for line numbers where both the foreground and background colors were transparent. That strikes me as a, well, sub-optimal choice.

**Comment by muellmusik** [comment]
> Can you tell me more about this problem, the configuration? Can you check your theme? It could be linked to the transparency fix, now the transparency is really applied.

Check my theme for? So I should apply PR #1297?

> So, I will create a branch with reverted line numbering width and the focus rect.

okay thanks!

**Comment by vdonnefort** [comment]
> Check my theme for? So I should apply PR #1297?

Yes,  you need this patch https://github.com/vdonnefort/supercollider/commit/acec43583797fa39c0d88c127e30b1010b9fa205 which allows to deal correctly with transparency for foreground

**Pull request merged**
