### PR TITLE
Reimplement match lang ip

### PR DESCRIPTION
**Pull request by muellmusik**
This PR reimplements the prMatchLangIP primitive.

- The existing boost::asio implementation caused problems on some platforms
- It is preferable to avoid host resolution in implemeting this
- This default version should work on Linux, OSX, and most nix-y systems
- A windows specific implementation was added using GetAdaptersAddresses

Thanks to @bagong for help testing and debugging the Windows version!

### CODE REVIEW

**Comment by muellmusik** [comment]
Ping... I know this isn't at all old, but as it required painful cross-platform testing, it would be really nice to merge this sooner rather than later to avoid any conflicts.

**Comment by crucialfelix** [comment]
Can somebody else have a glance at this ? I'm super overworked today.

**Comment by miguel-negrao** [comment]
Not sure how exactly this should be tested, but here in debian testing, with this pull-request I get:

```
NetAddr.matchLangIP("127.0.0.1")

-> true

NetAddr.matchLangIP("192.168.1.79") //my local ethernet interface ip

-> true

NetAddr.matchLangIP("1.1.1.1")

-> false
```

**Comment by muellmusik** [comment]
> Not sure how exactly this should be tested, but here in debian testing, with this pull-request I get:

That looks correct Miguel, thanks.

**Pull request merged**
