### PR TITLE
Update PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by mtmccrea**
## Purpose and Motivation

In response to some [discussion on the PR process](https://scsynth.org/t/reviewing-prs/9372/13), I'm proposing some notes be added to the PR template:

- Add note about including a description even when linking to related issues
- Add note about option of draft PR
- Add optional merge notes

## To-do list

- [x] Code is tested
- [x] This PR is ready for review

### CODE REVIEW

**Comment by JordanHendersonMusic** [comment]
> Add note about option of draft PR

Might it be worth removing the label 'Work In Progress (WIP) do not merge yet'?

**Comment by mtmccrea** [comment]
> Might it be worth removing the label 'Work In Progress (WIP) do not merge yet'? We could migrate those prs with the label to drafts?

I agree in principle, though I don't have a working knowledge of draft PRs, or the process/effect of changing an active PR to a draft, so someone who does would have to weigh in...

**Comment by JordanHendersonMusic** [comment]
Perhaps you could also mention something about labels? All commits should at least have a `comp:` label.

**Comment by mtmccrea** [comment]
Good idea.

I understand you to mean using the recommended commit message format (as opposed to assigning a label to the PR), correct?

Updated with a note about commit message format (and updated the wiki with common `comp:` tags), lmk what you think...

**Comment by JordanHendersonMusic** [comment]
Hmm, I can't quite parse what you're saying...

All prs (and issues) must have a `comp:*` label -
https://github.com/supercollider/supercollider/wiki/Labels-and-milestones-for-PRs-and-Issues

Perhaps the comment about commit message format and mandatory labels should go right at the top, not at the bottom, as it's easy to miss and not really a note, but a (soft) requirement?

**Comment by mtmccrea** [comment]
>All commits should at least have a comp: label.

Perhaps you meant to say all PRs should have...

Commits are also recommended to have a message format beginning with a `comp:`, so I thought you were referring to that.

AFAIK only those with write access can assign tags, so essentially reviewers, who should hopefully know about this, but if you think it would be useful to mention I could add it.

> Perhaps the comment about commit message format and mandatory labels should go right at the top, not at the bottom, as it's easy to miss and not really a note, but a (soft) requirement?

I agree it's not optimal—trying to find a balance between front-loading the necessary stuff with tips/reminders at the end. I'll try it out...

**Comment by JordanHendersonMusic** [comment]
I could have sworn you could add labels to your own prs and issues... I think I've got another GitHub account somewhere so I'll give it a go and report back!

**Comment by JordanHendersonMusic** [comment]
Ah no your right! I wouldn't mention labels then.

**Comment by mtmccrea** [comment]
I tried moving the note about commit message to the top and it was just distracting. It's the kind of thing you really only need to see once or twice, essentially we just want new contributors to be informed given they likely haven't seen the wiki.

I'm thinking the end may be the least obtrusive? Open to other options or just bagging it if it's overkill.

>I could have sworn you could add labels to your own prs and issues...

I just had a hunch about it and confirmed with a [quick search](https://www.google.com/search?q=in+github+who+can+assign+labels&oq=in+github+who+can+assign+labels&gs_lcrp=EgZjaHJvbWUyBggAEEUYOTIHCAEQIRifBTIHCAIQIRifBdIBCDY1NjFqMGo3qAIAsAIA&sourceid=chrome&ie=UTF-8), but maybe that's not the best confirmation X-D

**Review by JordanHendersonMusic — APPROVED** [review]

**Comment by mtmccrea** [comment]
Merging Reviewer, please squash!

**Review by telephon — APPROVED** [review]

**Pull request merged**
