### PR TITLE
fixing scdoc.cpp indentation

### PR DESCRIPTION
**Pull request by tiagmoraismorgado**

### CODE REVIEW

**Comment by Sciss** [comment]
Is it possible to create _one_ pull requests for each and every change in indentation, instead of _ten_? My e-mail inbox is getting flooding with this stuff, and I'm about to unsubscribe from this.

**Comment by tiagmoraismorgado** [comment]
my apologies, @Sciss  i didn't master managing multiple pull requests from a single fork branch. maybe that's a sign i should pay some attention to it

**Comment by Sciss** [comment]
No problem. It's just there are 134 repository watchers, so that just created around 1500 e-mails that many people have to go through. Appreciate your efforts.

**Comment by tiagmoraismorgado** [comment]
maybe it's a better idea to space them in time. so making around two PRs every half an hour. instead of making them all at the same time

**Comment by brianlheim** [comment]
This is incorrect indentation.

**Pull request closed without merging**
