### PR TITLE
Update Pipe.schelp

### PR DESCRIPTION
**Pull request by dyfer**
## Purpose and Motivation

Remove references to macOS/OS X 10.3.

AFAIU, SC won't compile on such an old system anymore.

## Types of changes

- Documentation

## To-do list

- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
I cancelled the builds, since this is only a documentation change.

**Comment by brianlheim** [comment]
> I cancelled the builds, since this is only a documentation change.

please use `[skip ci]` in the commit message instead next time!

**Comment by dyfer** [comment]
> please use `[skip ci]` in the commit message instead next time!

I know about this but I usually remember it just  _after_ pushing the commit... I'll try to remember next time :)

**Comment by brianlheim** [comment]
no worries, i usually forget it too >_>

**Pull request merged**
