### PR TITLE
Make Help Browser open external links in desktop browser

### PR DESCRIPTION
**Pull request by brianlheim**
This is toward #2897.

We realized at the dev meeting today that it's impossible to have the help browser open an external link in the user's default desktop browser. This PR adds an option to our extension of QWebPage for doing so, and then turns it on when the webpage is inside the help browser.

To test, you'll need to go to a web page that has a link with `taget="_blank"`. The first link I found that does this is:

`HelpBrowser.goTo("https://www.github.com")`

and then click on the "terms of service" link.

This works flawlessly on macOS (10.13 beta).

The next step after this PR is adding links that say "Submit a change to this file"/"Submit documentation for this file" in relevant help files.

### CODE REVIEW

**Comment by brianlheim** [comment]
I could make this available in the SuperCollider WebView class too, if people want that.

**Comment by brianlheim** [comment]
Huh, actually, it looks like that's never even been supported in WebView, so maybe I should just make it that way by default?

**Comment by telephon** [comment]
yes! The webview isn't a very good browser after all.

**Comment by adcxyz** [comment]
Maybe add a second argument to HelpBrowser.goTo, so one can specify which ?
```
HelpBrowser.goTo("https://www.github.com", "Help")    // SC HelpBrowser
HelpBrowser.goTo("https://www.github.com", "default"); // OS default browser  
HelpBrowser.goTo("https://www.github.com", "Firefox"); // look for specific browser app, else default
```

**Comment by brianlheim** [comment]
> Maybe add a second argument to HelpBrowser.goTo, so one can specify which ?

@adcxyz not sure what you mean by this.

do you want to be able to open an arbitrary URL in an arbitrary browser? if so I think a call to UnixCmd is more appropriate.

do you want to be able to set the help browser to open external links in an arbitrary browser? if so you should understand that this is a property of the WebPage itself, not of a particular URL loaded in it. so it does not and should not need to be set at the same time as the URL.

is being able to choose the browser really that important? if so would you have any ideas on how to do that? AFAICT one easy way to do so would be IPC with sclang, although I think that is not sound design.

i realized reading the Qt docs though that this actually does a lot more than just use the browser; `QDesktopServices::openUrl` actually opens `file:///` URLs in the appropriate program if there is one (http://doc.qt.io/qt-4.8/qdesktopservices.html#openUrl). i personally think that is more valuable than forcing all URLs to go to an arbitrary application or spending time to implement similar functionality myself.

**Comment by adcxyz** [comment]
@brianlheim 
- it was meant as nice-to-haves if they require little work, none of it necessary :-)
My main point was that it would be nice to choose between SC help browser and 
default browser app, which can already be done, and is good enough:
```
"https://github.com".openOS; // default browser
HelpBrowser.goTo("https://github.com"); // SC Help
```
If choosing which browser to use were already there in Qt, then why not make it available;
it seems that it takes longer than 5 minutes to make, so please don't waste time on it!
- if anyone ever really needs it, using unixCmd is fine.

**Comment by telephon** [comment]
Why this was closed? The suggestion seemed very reasonable.

**Comment by brianlheim** [comment]
I don't want to have something open that I don't plan to work on. I will reopen it when I have time.

**Pull request closed without merging**
