### PR TITLE
Fixes/alsa midi fixes

### PR DESCRIPTION
**Pull request by timblechmann**

### CODE REVIEW

**Comment by miguel-negrao** [comment]
Out of curiosity, what was the symptoms that this fixes, just in case I was witnessing the problem.

**Comment by timblechmann** [comment]
deadlock when quickly recreating helper threads (hid/midi/serial)

**Comment by miguel-negrao** [comment]
And in practice, when does that happen ?

**Comment by timblechmann** [comment]
in my case it was related to initializing midi before initializing the modality midi device

**Comment by timblechmann** [comment]
btw, someone might want to change the linux build on travis to use an compiler, which is sufficiently compliant to c++11 ... 2015 is ending roughly in a week and all modern compilers have sufficient c++14 support these days.

**Comment by crucialfelix** [comment]
We can't merge this unless travis completes. Either by changing the implementation or changing the travis compiler.

**Comment by patrickdupuis** [comment]
@timblechmann : Would switching to Travis' Trusty build environment offer enough C++11 compliance? We would get gcc 4.8.4. (though it looks like we were already getting 4.8 from a PPA in the Precise build environment)
https://docs.travis-ci.com/user/trusty-ci-environment/
Maybe this is a stupid question but... should -std=c++11 be somewhere in our build recipe?
What minimum version of gcc do you need to be 100% c++11 compliant?

**Comment by timblechmann** [comment]
@patrickdupuis cool! don't ask me about the minimum version. no need to specify the c++ standard, though ... it should be done something in cmake (iirc it is hardcoded, one could make the code a bit more expressive by relying on cmake to pass the right flags, though: https://cmake.org/cmake/help/v3.4/prop_tgt/CXX_STANDARD.html)

**Comment by crucialfelix** [comment]
@patrickdupuis has a travis fix here: https://github.com/patrickdupuis/supercollider/blob/master/.travis.yml

Once he gets a chance to make a PR for that change and its merged then I think you can rebase this to make it complete. Or maybe we should just merge it on trust.

**Comment by timblechmann** [comment]
no need to contribute fixes upstream

**Pull request closed without merging**
