### PR TITLE
sclang: fixes hardlock on floating point increments to Integer::forBy

### PR DESCRIPTION
**Pull request by lnihlen**
Regarding #2690.

Previously floating point arguments to the special optimizations on the
```Integer::forBy``` function would be cast to ```Integer```, which meant that if they
were relying on fractional increments those could be lost in the cast,
resulting in a nonterminating loop. This commit adds support for floating
point arguments. If any of the arguments are floating point they are all
cast to floating point and the loop proceeds using floating point.

### CODE REVIEW

**Comment by lnihlen** [comment]
Ping, would appreciate some feedback when you get the chance, thanks!

**Comment by lnihlen** [comment]
Apologies for the mess.

**Comment by lnihlen** [comment]
Moved to #3804 after making a mess on this PR.

**Comment by jamshark70** [comment]
Alternate solution: `git reset` (or `git reset --hard`) back to the right commit and `git push --force` -- they suggest not doing a force push too often because it can cause problems if someone in the interim bases work on the commits that will be deleted, but a/ devs should be basing new branches on develop anyway and b/ unlikely to be an issue if it's done quickly, to correct an error.

**Pull request closed without merging**
