### PR TITLE
LineLayout related doc improvements

### PR DESCRIPTION
**Pull request by muellmusik**
This adds some links, comments, and examples to the LineLayout related help files. In particular this addresses the absence of a ScrollView related example.

## Types of changes

- Documentation

## To-do list

- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Review by mtmccrea — APPROVED** [review]
Thanks for these examples! 
- [x] Tested and working

**Comment by mtmccrea** [comment]
Sorry, didn't see there was an assigned reviewer!

**Comment by muellmusik** [comment]
> Sorry, didn't see there was an assigned reviewer!

No worries! I just added @scztt as we were chatting on the forum.

**Comment by muellmusik** [comment]
As this has been reviewed, I'd like to merge? The CI failure is not about doc, so seems unrelated.

**Pull request merged**
