### PR TITLE
Use single blank line as file ending in sc files

### PR DESCRIPTION
**Pull request by capital-G**
## Purpose and Motivation

Inspired by https://github.com/supercollider/supercollider/pull/6323#issuecomment-2165076689

*Controversial* proposition which enforces a single blank line as file ending (`\n` aka LF) on `.sc`, `.schelp` and `.scd`.
As this touches many files (and therefore git history), this is open for discussion - if we want to go this way, the code is here. But, other than clang-formatting, it does not taint `git blame`.

The formatting rules are checked via pre-commit, so if people have set it up, their files will be adjusted automatically.

Most interesting files are
* https://github.com/supercollider/supercollider/blob/d3d999270a8be8ec47c05ba8ed49ebc3282a8784/tools/remove_trailing_blank_lines.py
* https://github.com/supercollider/supercollider/blob/d3d999270a8be8ec47c05ba8ed49ebc3282a8784/.pre-commit-config.yaml

## Types of changes

- New feature
- Breaking change

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [ ] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by mtmccrea** [comment]
I'm actually surprised how _few_ files this touches. My immediate hesitation was about the classlib, but I see only _four_ are modified there.

The majority seem to be _.schelp_, examples, and some testsuite files, which are somewhat "low stakes" in terms of revision history, IMO. So it could be worth it if we have the benefit of acquiring this pre-commit rule going forward? It's indeed a cumbersome thing to check for and ask of PR authors.

(Aside: wishing I would have done this in the recent style reformat of the help docs so many of these touched files would have been grouped into that commit :-/)

**Comment by JordanHendersonMusic** [comment]
Perhaps this would be a good commit to test how blame might ignore certain commits?

**Comment by capital-G** [comment]
> Perhaps this would be a good commit to test how blame might ignore certain commits?

Thanks for bringing this up. Bundled this comment with the discussion https://github.com/supercollider/supercollider/issues/6340 this resulted in https://github.com/supercollider/supercollider/pull/6350 which I think is pretty neat :)

**Comment by mtmccrea** [comment]
Tested and working as expected using git CLI. Nice!

Though I use GitHub Desktop, and there's one snag: when committing a file that is subsequently modified by the hook to remove EOF whitespace, GH Desktop doesn't see that file as being "touched" so the diff view still shows the EOF whitespace. Switching to XCode, I see the whitespace removed, switching back to GH Desktop the updated diff shows properly. 
Seems like a GHD issue... (quick web search didn't provide any immediate answers) Or could it be that the files are modified in such a way that they aren't broadcasting as being "touched"? Could be related to the fact the changes are whitespace only?

**Comment by capital-G** [comment]
Rebased against develop to resolve merge confilcts.

Would like to get a definitive yay/nay on it.

**Comment by mtmccrea** [comment]
I'm in favor of this. If merged it would be good to add to `.git-blame-ignore-revs` and add a note in docs about this behavior (maybe in formatting instructions and/or docs about git/CI behavior)

**Comment by capital-G** [comment]
> I'm in favor of this. If merged it would be good to add to `.git-blame-ignore-revs` and add a note in docs about this behavior (maybe in formatting instructions and/or docs about git/hook behavior)

We could add this commit to `.git-blame-ignore-revs', but this would only be helpful during git blame, not while traversing the git tree - since no actual code is touched here, and git blame on a file ending is not too interesting, I decided not to include it in the file, but I can add it if you think it should be.

**Comment by mtmccrea** [comment]
>git blame on a file ending is not too interesting

Good point. So it is really just a judgement call, I could see adding it just for the sake of if thematically being a large whitespace modification, but I don't feel strongly about it either way :)

**Comment by capital-G** [comment]
Rebased and added the offending commit to `.git-blame-ignore-revs`

**Review by JordanHendersonMusic — APPROVED** [review]
Looks good, I don't think its controversial because it is just the end of the line. 

One note to merger, this should **not** be squashed as the middle commit has been added to .git-blame-ignore-revs.

**Comment by dyfer** [comment]
There seems to be a consensus that we want this - merging. Thanks!

**Pull request merged**
