### PR TITLE
Support for Boost 1.71

### PR DESCRIPTION
**Pull request by brianlheim**
## Purpose and Motivation

Fixes https://github.com/supercollider/supercollider/issues/4576, https://github.com/supercollider/supercollider/issues/4490

I looked for a nicer way to to this, but couldn't find anything -- there appears to have been a single boost release (1.70) where this class hierarchy was somewhat compatible in both directions.

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested - tested this on macOS 10.14 with boost 1.66 (packaged) and boost 1.71 (system), both build
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
TODO - test that built supernova actually runs
TODO - document using `-DBoost_NO_BOOST_CMAKE` (https://github.com/supercollider/supercollider/issues/4576#issuecomment-531499017)

**Comment by brianlheim** [comment]
Note that I also need #4611 to build develop branch on macOS + xcode 11. After merging that, 3.10 should be merged into dev ASAP.

**Comment by snappizz** [comment]
this should go to 3.10 branch not develop per today's discussion

**Comment by dvzrv** [comment]
@snappizz what is the rationale behind this though? `develop` also broke for me without this fix

**Comment by snappizz** [comment]
@dvzrv branches should be made against 3.10 if they are uncontroversial bug fixes with no risk. brian and i talked about this at the last dev call and we agreed this PR should be based on 3.10 and not develop, the above are just a reminder of our decision until he gets around to it

**Comment by brianlheim** [comment]
updated, sorry for the delay, forgot about this for a while!

**Pull request merged**
