### PR TITLE
freqscope: sr-dependent resolution

### PR DESCRIPTION
**Pull request by timblechmann**

### CODE REVIEW

**Comment by telephon** [comment]
looks good.

**Comment by bagong** [comment]
Linux fails in a test:

`````
    [1/1] UnitTestScript:sclang_crash_1.scd (0.0s)
           * Didn't crash.
    [!]   UnitTestScript:allViews.scd (0.0s)ERROR: Message '/' not understood.
    [1/1] UnitTestScript:sclang_crash_2.scd (0.0s)
           * Didn't crash.
`````

**Comment by crucialfelix** [comment]
was `server.sampleRate` nil on linux in this situation ? sounds doubtful. are there some situations where that can fail ?

**Comment by telephon** [comment]
Yes, when the server isn't running yet, the `sampleRate` isn't updated yet.

**Comment by timblechmann** [comment]
@telephon is the `sampleRate` ever updated? afaict there is no communication channel to inform the language of the samplerate of the server

**Comment by jamshark70** [comment]
@timblechmann http://doc.sccode.org/Reference/Server-Command-Reference.html#/status - /status.reply includes both the nominal and actual sample rates.

**Comment by timblechmann** [comment]
ah ... `sampleRate` vs `options.sampleRate` ... iirc there are some reference to the second in the class library code ...

**Comment by timblechmann** [comment]
no need to improvements upstream

**Pull request closed without merging**
