### PR TITLE
class library: refactor functionality: connectToServerAddr

### PR DESCRIPTION
**Pull request by telephon**
## Purpose and Motivation

While looking for a fix of #5568, a small refactoring was recommended.

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks so much! 
(especially that the linked issue was introduced by my commit...)
- Maybe it would be good to add the documentation for the new method in the help...?
- Do you think this should be cherry-picked for 3.12 or is it fine to stay on develop?

**Comment by telephon** [comment]
I'm still usure whether `connectToServerAddr` is the best name for the method – it seems misleading when taken out of context. Whe only connect if necessary (for tcp), otherwise we directly call the onComplete message.

In fact, I would have thought it good to pack the `startAliveThread` into it, but the method `boot` passes this only when the argument `startAliveThread = true` (sorry, this is all a bit complicated to explain).

**Comment by dyfer** [comment]
> In fact, I would have thought it good to pack the `startAliveThread` into it, but the method `boot` passes this only when the argument `startAliveThread = true` (sorry, this is all a bit complicated to explain).

Yeah... the whole `Server` class and boot behavior was mean to be rewritten, but it seems it never happened. Not sure how much we want to change before the (hopefully) rewrite later one, and how much we should resort to minimal patching.

**Comment by telephon** [comment]
@adcxyz did a rather large rewrite long ago, but as far as I know, it somehow was never taken up and merged.

**Comment by adcxyz** [comment]
> @adcxyz did a rather large rewrite long ago, but as far as I know, it somehow was never taken up and merged.

Yes, that was discussed here : https://github.com/supercollider/supercollider/issues/3310
and the related fork that sketched this out: https://github.com/adcxyz/supercollider/tree/server_ServerProcess

**Comment by telephon** [comment]
Ah good, thanks for pointing to this. As you wrote, the branches have diverged. What do you think: is the current PR doing harm (I can minimize impact at the cost of beauty :))

**Comment by telephon** [comment]
what do you think?

**Review by adcxyz — APPROVED** [review]
looks good to me, clearer than before.

**Pull request merged**
