### PR TITLE
plugins: DetectSilence: initialize output

### PR DESCRIPTION
**Pull request by snappizz**

### CODE REVIEW

**Comment by snappizz** [comment]
@telephon  Looks like the comment is simply outdated. The docs say

> This UGen outputs 1 if silence is detected, otherwise 0.

and the source code agrees.

**Comment by telephon** [comment]
The zero return of DetectSilence was hidden in a commit that was about something unrelated:

https://github.com/supercollider/supercollider/commit/3d9d7277c9c938012a89f78091f5349006763be8

@sensestage do you remember why you put it in?

**Comment by jamshark70** [comment]
> The zero return of DetectSilence was hidden in a commit that was about something unrelated... @sensestage do you remember why you put it in?

It appears the ^0.0 should have been commented out earlier, in https://github.com/supercollider/supercollider/commit/3f85c33b21b9e499f4c68654422905a7ff1e5172 -- here, the plugin code was changed but the class library was not updated accordingly.

The commit history is sloppy but the end result is correct.

If anything is to be done with the `// ^0.0...` line, it is to delete it and avoid future confusion.

**Comment by telephon** [comment]
@jamshark70 ah yes, I see, it outputs 0 or 1. Better remove the line.

This would be an example for the helpfile:

```
{ var sound = LFNoise2.ar(3000).max(0); [sound, DetectSilence.ar(sound, time:0.0001)] }.plot
```

**Comment by snappizz** [comment]
ping (sorry if these are getting annoying)

**Comment by telephon** [comment]
not at all. 
Could you be so kind and also just remove the line `//		^0.0		// DetectSilence has no output` from the class file?

**Comment by snappizz** [comment]
done

**Pull request merged**
