### PR TITLE
Array dimensions exclude strings

### LINKED ISSUE #2537: flop behaves differently in primitive as opposed to class library
```
["it is me"].flop; //  [ [ it is me ] ]
List["it is me"].flop // [ [ i ], [ t ], [   ], [ i ], [ s ], [   ], [ m ], [ e ] ]
```

### PR DESCRIPTION
**Pull request by telephon**
This fixes #2537, and implements a clear interface. Maybe the method names could be better, and also in general discussion is very encouraged.

Note that the first commit is not properly part of this, it is just needed as a precondition (it's in another PR).

### CODE REVIEW

**Comment by brianlheim** [comment]
Will write more later, but I think adding separate logic for the idea of "indexableDepth" needs more justification in this instance. What exactly does this term mean? Since (IMO) the only reason for not using multiChannelExpand on String is that it's more intuitively convenient not to treat Strings as char arrays, using the isKindOf(String) check keeps the code more readable. But that's just at a first glance.

**Comment by telephon** [comment]
@brianlheim thanks for your comments. 

Yes, it does need justification, but it should be covered by the justification for the `flop` behavior, shouldn't it? I think there should be a clear interface in sclang that determines how an object behaves with flop – string may not be the only one. Generally, it is not considered good style to use `isKindOf`, unless there is a good reason. `respondsTo` is ok, otherwise it is better to make an interface that can be also implemented by unrelated objects.

Terminology is perhaps not the best, it was my first attempt.

**Comment by telephon** [comment]
so the terminology is:

strings can't be nested, objects can't be unless specified

`canHaveDepth` (for any object)
`canHaveIndexableDepth` (for any object that has order, acan be indexed with `wrapAt`).

Maybe one could use 
`canHaveDepth` (for any object)
`isSequenceable` (for SequenceableCollections)

and then combine them 

`x.canHaveDepth and: x.isSequenceable`

?

**Comment by brianlheim** [comment]
Thanks for the response & explanations @telephon!

> I think there should be a clear interface in sclang that determines how an object behaves with flop – string may not be the only one.

Can you provide a second example? Otherwise, seems like a case of [YAGNI](http://wiki.c2.com/?YouArentGonnaNeedIt), and I'd prefer to create that interface only when it's apparent that it will refactor existing code. I can't think of another place to use `canHaveIndexableDepth`, but it might just be my own lack of imagination. :)

We also have the method `isString` to use instead of `isKindOf`.

I do think these changes you're suggesting are well-suited to the way this kind of problem has been approached so far in SC, but IMO the fact that there are so many methods like this defined on Object seems like a symptom of the need for a legitimate interface or type class system in SC. Maybe a feature for 4.0, hahaha.

**Comment by telephon** [comment]
>the fact that there are so many methods like this defined on Object seems like a symptom of the need for a legitimate interface or type class system in SC. 

In general, it is a "natural" result of the method dispatch system (single and double dispatch). The philosophy behind it is "you don't know what you will need", and also "type is behavior only".

In any case, your point is good, we need to check for every case if it is worth such an interface.

I am suggesting this here because it is an essential property of any composite object to be "nestable" or not, which I find adds clarity once we have it. In other words, it is better to make explicit *why* we are not expanding strings rather than only *that* we are doing this.

I'll think of an example.

**Comment by telephon** [comment]
`canHaveDepth` is actually wrong – this is not what is intended.

The point is that

`[[1, 2, "flip"], [100, "flop"], "flap"].flop`
should return 
`[ [ 1, 100, flap ], [ 2, flop, flap ], [ flip, 100, flap ] ]`
and not
`[ [ 1, 100, f ], [ 2, flop, l ], [ flip, 100, a ], [ 1, flop, p ] ]`.

This is the case with the array primitive, but not with the sclang implementation (e.g. for `List`).

The other case is `flat` and `flatten`.

Currently, we have:

`[[1, 2, "flip"], [100, "flop"], "flap"].flat`
returning
`[ 1, 2, f, l, i, p, 100, f, l, o, p, f, l, a, p ]`

We need to discuss if this actually should be

`[ 1, 2, flip, 100, flop, flap ]`

(I know that this is a potentially problematic API change)

So, after all this, I think the most explicit method would be `shouldMultiChannelExpand`.

**Comment by telephon** [comment]
There may be a better solution, it's in the works.

**Comment by brianlheim** [comment]
I took a bit of time to think about this, and I'm of the opinion now that the most reasonable solution is to treat a String as an array type, always--including during flopping. Meaning:
```
[ ["abc"], ["def"] ].flop -> [ ['a', 'd'], ['b', 'e'], ['c', 'f'] ]
```
Consider the difficulty of circumventing this issue for each option we could take. If Strings don't flop, the user has to create a new `Stringlike[char] : RawArray` themselves, which won't have the syntactical ease that string literals have in sclang. If they do flop, it's trivial to get around that by creating a `StringWrapper : Object` which still provides access to the underlying array.

Keeping a String together during flopping made sense to me at first, but Strings don't always hold linguistic content, and the class name is really just an alias for a "raw" char array, so my vote now is for it to always behave like an array would.

**Comment by telephon** [comment]
>Consider the difficulty of circumventing this issue for each option we could take.

I see your point, but the result would be unwieldy. Having to rely on a wrapper for strings in all the more common cases would be quite unidiomatic and inefficient. It is very common, e.g. for OSC messages, to use strings and symbols interchangeably (just like floats and ints).

1. Given the fact that right now we have an inconsistent interface, it might be reasonable to pass in a condition. 

2. Or, have two separate methods – actually, with a minor change, we could just use the existing `flopDeep` method.

3. Maybe the difference in behavior (that motivated the current issue) is OK - we just have to document it. It is much easier to change the outer collection to a List when you want to treat strings as arrays than wrapping all the contents in the more common other cases.

I tend towards (2) but am open to any …

**Comment by brianlheim** [comment]
> I see your point, but the result would be unwieldy. Having to rely on a wrapper for strings in all the more common cases would be quite unidiomatic and inefficient.

I think you may have misunderstood the wrapper suggestion--the idea is that you'd wrap before flopping/flatting and then unwrap after. In fact, you could do that very easily right now using `.asSymbol` and `.asString`.

> It is very common, e.g. for OSC messages, to use strings and symbols interchangeably (just like floats and ints).

The problem with this comparison is that String is an array type, while Symbol wraps an array within a unindexable object. Float and Int are more readily interchangeable because they're primitive data types. This is kind of like saying `Int 123` is interchangeable with `Array [1,2,3]`.
You can convert them back and forth using `.toDigits` and `.convertDigits`, but they have very different capabilities otherwise. In my experience, Strings in SC tend to be interchangeable/cast to Symbols when they're declared as literals, but there are plenty of cases where you want to manipulate and build strings using array functions.

> Given the fact that right now we have an inconsistent interface, it might be reasonable to pass in a condition.

This is [bad practice](http://softwareengineering.stackexchange.com/questions/147977/is-it-wrong-to-use-a-boolean-parameter-to-determine-behavior).

> Or, have two separate methods – actually, with a minor change, we could just use the existing flopDeep method.

Could you elaborate please? Not totally convinced that a new method is necessary since the `.asSymbol` / `.asString` conversions I mentioned above would be two additional lines of code max, but I agree that if users really need that convenience of this functionality it could be a good addition.

I think there needs to be input on this from other people. This has been a productive discussion so far, but it's turned into a larger conversation about the general behavior of String in SC, and I'd like to have a consensus on what exactly that is before we change flop/flat.

**Comment by telephon** [comment]
The class of an object in supercollider is not its type. This is a common misunderstanding.  SuperCollider (or Smalltalk) is very different here from Java or C++. 

The type of an object is only its behaviour with respect to a specific message.This is *really* important. 

So the fact that class string is a subclass of class array doesn't help so much to decide this point. The fact that the primitive handles strings separately already is a clue.

I've understood that you'd want to convert all contained strings to symbols in order to make flop behave as in the primitive. We are talking about arrays like:

`["freq", [420, 461], "amp", 0.2]`
vs.
`[\freq, [420, 461], \amp, 0.2]`

If you have to inspect every nested array to check for potentially existing strings, in order to convert them to symbols, this is a lot of bloat and wasted resources. Because users will always supply strings and symbols interchangeably for specifying argument names, there is no way to guarantee this unless you want to change the usage itself. As `flop` is quite important, it is already in use in all kinds of projects, you'd also have to force every developer to change their implementation in the meanwhile to make sure it doesn't break.

>Could you elaborate please? Not totally convinced that a new method is necessary

I mentioned an already existing method, `flopDeep`. It semantically matches better the case where strings are treated as collections.

>I think there needs to be input on this from other people. 

I understand that I am not enough here :) I'll let the case rest here - thanks for contributing!

**Comment by telephon** [comment]
P.S. Re. "bad practice": I wasn't suggesting a boolean, but a function that you can specify. This is common and good practice to make variants of behavior depend on a function that returns a boolean.

**Comment by brianlheim** [comment]
I'm sorry, I'm trying really hard to understand what you mean about type and behavior in SC, but I just don't see it reflected in the design of the language. Can you point to an article or something about this?

**Comment by brianlheim** [comment]
Also, I apologize for misunderstanding your suggestion re: conditions. Thank you for clarifying!

**Comment by telephon** [comment]
It isn't self evident at all, so it's a good question. Note that the special methods we were talking about are edge cases of a more general design strategy.

I find that Alan Kay's "The Early History of Smalltalk" (http://worrydream.com/EarlyHistoryOfSmalltalk/) gives a good perspective on the original motivations behind OOP. The discussion http://wiki.c2.com/?DuckTyping is not systematic, but you can read the idea between the lines. Kent Beck's "Smalltalk Best Practice Patterns" might have something here, too. In other languages, a lot of this kind of functionality is made explicit in terms of interfaces or similar structures. 

The clearest description I can find is by James McCartney, who wrote in an email conversation: *"… subclassing is implementation inheritance. The type of an object is not its class, the type of an object is what it responds to."*

This is best understood from the pure object-centric perspective that Alan Kay proposed. I'd be also curious to see a focused article about it!

**Comment by jamshark70** [comment]
Also note that symbols live in a table whose numeric index is the symbol's unique ID (which is how they are matched for identity). New symbols (whether \literals or generated by asSymbol) go into this table and AFAIK they are never removed. If we change strings to symbols only for the purpose of flopping, the symbol table may grow out of control, inadvertently.

It's sometimes assumed that asSymbol is basically transparent, but there is a cost, and the cost goes up the more distinct strings you have.

**Comment by brianlheim** [comment]
@telephon Thank you for the links!

@jamshark70 Absolutely, I was only suggesting that as a quick general fix in case using `.flopDeep(array.maxDepth-1)` wouldn't work—i.e., the array has strings at multiple depths that all need to remain unflopped. The number of cases where that wouldn't apply is pretty low IMO. Looking at it from the other side, it would be a similar waste of resources to have to convert Strings to basic Arrays and back in order to flop them.

**Comment by telephon** [comment]
>It's sometimes assumed that asSymbol is basically transparent, but there is a cost, and the cost goes up the more distinct strings you have.

[OT] This is also a problem with incoming OSC messages, in which all "strings" are symbols.

**Comment by brianlheim** [comment]
Point well taken. I'm gonna take a few more days to think about this, I don't (despite how it may seem) have strong feelings one way or another at this point.

**Comment by vivid-synth** [comment]
@jamshark70 I can't find information about the symbol table being GC-ed, but we should document this! Long-running processes could crash if they generate lots of these

**Comment by brianlheim** [comment]
Doesn't seem like it's being gc'd. I let this run for awhile:

```
(
fork {
	var i = 0;
	loop {
		String.fill(1000, {rrand(32, 126).asAscii}).asSymbol;
		if(i % 5000 == 0) {
		format("%: %", i, Object.totalFree).postln;
		};
		i = i + 1;
	}
}
)
```

It's been about 10 minutes; the process is currently taking up about 700 MB of memory and steadily growing.

**Comment by vivid-synth** [comment]
Erlang has the same problem; they just warn about it in the docs

**Comment by telephon** [comment]
to be reopened later when we have time.

**Pull request closed without merging**
