### PR TITLE
Increase the default number of audio buses from 128 to 1024

### PR DESCRIPTION
**Pull request by vivid-synth**
As is being discussed on the mailing list, this patch proposes to increase the default number of audio buses.

### CODE REVIEW

**Comment by vivid-synth** [comment]
(I'm very open to discussing whether 1024 is the right choice -- but this is what the change will look like if that's the number we settle on)

**Comment by telephon** [comment]
just for those who haven't followed the conversation on the list, can you specify how much this affects memory requirements and startup time of the server?

Also, it may be recommendable to also change the number of control busses.

**Comment by jamshark70** [comment]
1024 buses should in theory require a walloping 1024 x 64 x 4 bytes = 64 x 4 kb = 256 kb = 1/4 meg. Startup cost should be negligible.

I don't see a need to bump up control buses. Has anyone ever actually run out of the 4096 of them?

The only downside of this change is that users of very tiny embedded systems *might* need to set the number of audio buses explicitly lower. That's a far rarer case than usage on a desktop or laptop with sufficient memory.

**Comment by telephon** [comment]
good.

i've only once run out of control busses, in a virtual gamelan that allows you to control four parameters per partial.

Increasing it may encourage modularity, but it's not important

**Comment by vivid-synth** [comment]
@jamshark70 if someone has a block size significantly larger than 64 they may get into multi-megabyte territory (e.g. at 1024 you're up to 4 MB), but that's still tiny on most systems, and maybe we'd argue if a user is changing the block size they also are able to change their number of audio buses.

To @telephon 's point, if people even sometimes run out of control buses, it may be worth bumping their number up also: they're 64 times less expensive than audio buses. We could go up to 65,536 and still only use 1/4 MB

**Comment by vivid-synth** [comment]
(Sorry, these /n_order changes are on the wrong branch)

**Comment by telephon** [comment]
I think it makes sense to also bump the control busses. It then feels as if there were infinitely many, which is reasonable.

**Comment by crucialfelix** [comment]
Hanns Holger Rutz just pointed out that this changes what the server defaults are, not just what the sclang client library thinks they are.

> Please revert this change. This implies that have a perfect match
between client and server version. It's ok to change the default number
of buses on the client side if you enforce adding it to the terminal
command, but changing it in the server is extremely bad, because it will
break many systems who now have a mismatch between their knowledge and
the actual default behaviour of the server that depends on the server
version!!

**Comment by vivid-synth** [comment]
Let's discuss this on the sc-dev list, so we don't have the convo in 2 places

**Pull request merged**
