### PR TITLE
Add NO_X11 build option for headless plugins compilation

### PR DESCRIPTION
**Pull request by orbsmiv**
When compiling for a headless system I'm passing the flags `-DSC_IDE=OFF -DSC_QT=OFF` but the compiler automatically builds the UIUgens plugin, which requires libx11. I've therefore defined a further flag `NO_UIUGENS` (taking the form similar to `NO_AVAHI`) which skips all of the UIUgens-related code.
Perhaps a further option might be to define a higher-level `NO_UI` flag that wraps all of the UI-related flags into one?

### CODE REVIEW

**Comment by orbsmiv** [comment]
I have now! Builds and runs successfully both with and without supernova.

**Comment by muellmusik** [comment]
Great. I'll approve my review then but leave it for the moment in case anyone else wants to check.

**Comment by brianlheim** [comment]
> looks great, thanks. the UIUGen class files will still be installed in sclang and people will get "UGen not installed" errors if they try to use the classes, but it's part of a broader problem with sclang that selective class import is really annoying to do.

Couldn't we just not copy those files?

**Comment by snappizz** [comment]
i would prefer `NO_X11` over `NO_UIUGENS`, in case there are other future dependencies on X11 that don't involve UGens.

> Couldn't we rather not copy those files while building, in the same way GUI files are not copied?

hmmmm i'm not wild about reorganizing the directory structure in the help files and the class library just to separate out these dudes, but i guess that's what we gotta do in this wonky language.

so now we have to account for the possible absence of a UIUGen on any given SC installation. fortunately, there's only one use in the class lib: `MouseX` is used in `Filter.scopeResponse` in `SCClassLibrary/Common/GUI/PlusGUI/Control`. however if you have Qt you definitely have X, so not an issue. (also, I may add, `Filter:scopeResponse`, and the fact that it uses MouseX for some reason, is pretty exemplary of the bloat we have in the class lib)

**Comment by brianlheim** [comment]
> i would prefer NO_X11 over NO_UIUGENS, in case there are other future dependencies on X11 that don't involve UGens.

That's a good point.

> hmmmm i'm not wild about reorganizing the directory structure in the help files and the class library just to separate out these dudes, but i guess that's what we gotta do in this wonky language.

You could also build a regex by listing the names of the files you explicitly want to ignore, but grouping them by functionality would also be OK. Either solution is fine with me.

**Comment by brianlheim** [comment]
@orbsmiv do you mind rebasing this and fixing the merge conflict?

**Comment by orbsmiv** [comment]
Argh... SourceTree rebase fail – would you like me to open a fresh PR with the `NO_X11` option instead?!

**Comment by orbsmiv** [comment]
Rebase done.
Is the consensus that `NO_X11` is the preferred flag name? If so I'll go ahead any make these changes too.

**Comment by brianlheim** [comment]
Thanks @orbsmiv! I think that NO_X11 makes more sense as a flag name, thanks for the suggestion @snappizz.

**Comment by orbsmiv** [comment]
Okay, flag name and description updated.

**Comment by klingtnet** [comment]
I am trying to compile headless supercollider on a Raspberry PI 3b+ on the latest raspbian but the cmake call fails because X11 is not present even though I disabled it with `NO_X11=ON`:

```sh
$ git clone --recursive https://github.com/supercollider/supercollider && mkdir supercollider/build && cd supercollider/build
$ cmake -DSC_IDE=OFF -DSC_QT=OFF -NO_X11=ON ..
# ...
CMake Error at /usr/share/cmake-3.7/Modules/FindX11.cmake:429 (message):
  Could not find X11
# ...
```

**Comment by brianlheim** [comment]
@klingtnet You are missing the `D` in `-D NO_X11=ON`...

**Comment by klingtnet** [comment]
Thanks!

**Pull request merged**
