### PR TITLE
update qt to 5.15 for Windows x64 builds

### LINKED ISSUE #5033: Some IDE windows and all sclang windows are blank and transparent when a custom color profile is active
## Environment

* SuperCollider version: 3.11.0
* Operating system: macOS 10.15.5, Windows 10
* Other details (Qt version, audio driver, etc.): my own hardware is [MacBookPro12,1](https://support.apple.com/kb/SP715), with Intel Iris Graphics 6100

## Steps to reproduce

- Start SuperCollider 3.11.0 with a custom color profile active (see comments ↓).
- Select SuperCollider > About SuperCollider. The window that appears is a transparent box.
- Select SuperCollider > About Qt. Likewise, a transparent box.
- SuperCollider > "Preferences…". Same deal
- Run some sclang code that produces graphics. The window appears with the correct title but is a transparent box.

## Expected vs. actual behavior

Expected behavior is obvious.

Actual behavior:

Screen Shot 2020-06-20 at 1 37 38 PM
Screen Shot 2020-06-20 at 1 37 49 PM

### PR DESCRIPTION
**Pull request by dyfer**
## Purpose and Motivation

~~If seems that QT 5.15 fixes #5033. I'm guessing it will also on Windows and would like to try updating QT on our CI.~~
5.15 fix seems to apply to macOS, but hasn't been confirmed yet to fix this issue on Windows

## Types of changes

- Breaking change (possibly? you never know when updating QT)

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

### CODE REVIEW

**Review by brianlheim — APPROVED** [review]

**Comment by brianlheim** [comment]
@dyfer what is WIP in this PR?

**Comment by dyfer** [comment]
> @dyfer what is WIP in this PR?

I haven't tested/run the build from the CI. But maybe it's okay as long as it builds? it's in develop after all

**Comment by brianlheim** [comment]
just tested it out w the uploaded artifact and didn't notice any issues. started the IDE and created a Window in sclang. thanks!

**Comment by brianlheim** [comment]
btw, this is using 5.15.0, not 5.15.1. i believe the 5.15 symlink will go there automatically whenever they add it.

**Comment by brianlheim** [comment]
merged as this is an appveyor only fix and appveyor passed

**Pull request merged**
