### PR TITLE
Cherrypick #3897 onto 3.10 (Supernova: Add missing \n)

### PR DESCRIPTION
**Pull request by snappizz**

### CODE REVIEW

**Comment by brianlheim** [comment]
Wait, I'm confused - why/how was this against `develop`?

**Comment by snappizz** [comment]
it was a mistake. should have gone into 3.10. we just merged the same commit twice

**Comment by jamshark70** [comment]
@brianlheim - because I don't have time to pay that much attention to the current state of development.

Sorry, if it's that bad, I'll restrict myself to logging bugs and I won't do pull requests anymore. Getting a bit tired of negative feedback on literally everything.

**Comment by snappizz** [comment]
@jamshark70 you're fine -- brian was referring to the target branch set incorrectly in this cherrypick, not in your PR.

**Comment by jamshark70** [comment]
Oh ok - wasn't clear, thanks for explaining.

**Pull request merged**
