### PR TITLE
Pstutter vs Rest

### PR DESCRIPTION
**Pull request by jamshark70**
Two related commits (again, putting in for master because I'm not sure these days what is the right thing).

First -- should be a no-brainer -- currently, `Rest(1).isRest` is actually false. That seems... how to put it... counterintuitive at best.

Second -- there's a case with Pstutter and Rests that doesn't work cleanly.

```
p = Pbind(\degree, Pstutter(2, Pseq([0, Rest(1), 2], 1))).asStream.all(()).do(_.postln);

( 'degree': 0 )
( 'degree': 0 )
( 'isRest': true, 'degree': 1 )
( 'degree': 1 )   // this one is wrong
( 'degree': 2 )
( 'degree': 2 )
```

For the "wrong" event: Pstutter should duplicate the output values, and when the output value to be duplicated is a Rest, I'd expect the duplicates to be rests as well. But they aren't. That's because Rests are (currently) transmitted into the output event only by a side effect -- setting 'isRest' in the event. Pstutter (currently) considers only the child stream's value, but not the side effect.

This fix (checking the side effect) isn't especially pretty, but it gets the right result.

A proper fix would be to redesign the Rest mechanism altogether. The 'isRest' side effect was a clever way to avoid implementing math operations for Rests, but as others (particularly Julian) pointed out, it complicates the Pattern internal interface. This Pstutter issue is severe enough and the fix is ugly enough that I'm finally forced to concede that, indeed, the side effect was not the right way to go.

I had actually mentioned this some time ago on sc-dev, but nobody took up the discussion and I didn't have time to pursue it further. (For that matter, I don't have any ideas for a better design.) If the discussion is going to remain stalled, then at least we should get the right behavior by whatever means.

I bundled the commits because the Pstutter fix depends on isRest. If they should be separated, let's deal with that later.

### CODE REVIEW

**Comment by telephon** [comment]
Certainy `Rest(1).isRest` should be true. The other change, if it is added, should be marked as something to refactor later. I really don't think the current way `Rest` is implemented is the last word – it looks as if it was creating all kinds of complications in quite unrelated places. E.g. `Pstutter` shouldn't really have to do anything with events, it's just an object-repeater. 

Should I open an issue where we can link all these cases and find a better solution?

I am not against this band-aid, but I think that in the future the pattern-rest-system will need a conceptual fix.

**Comment by jamshark70** [comment]
@telephon yes, I think we should have a new issue for refactoring rests.

The main problem was that whatever object is returned by a stream when it finds a rest, it must respond to math ops. At the time, some of the proposed solutions seemed to be veering into madness -- I forget details, but I think there was even talk of two parallel rest classes, one that could do math and the other that wouldn't -- and I proposed the side-effect solution to sidestep those problems. The ugliness of that approach has now reached a level where I agree, it's worth revisiting the other issues.

**Comment by telephon** [comment]
Of course the question may be in the end whether one needs to limit any functionality for a sane solution. It is a performance issue, in the end. One could just do something like this:

```
Rest2 : Ref {

	dur_ { |dt| value = dt }
	dur { ^value }

	// this should be called in the event!
	// maybe we need a check.
	asControlInput {
		~isRest = true;
	}

}

```

And then check in the event, after the `asOSCArgs` call if `~isRest == true`.

**Comment by crucialfelix** [comment]
@telephon ready to merge ? It does fix the bug

**Comment by snappizz** [comment]
The first commit here duplicates #2495, doesn't it?

**Comment by jamshark70** [comment]
> The first commit here duplicates #2495, doesn't it?

I think git generally handles that case pretty well -- if it's merging a commit into a branch and the commit is already there, usually it just goes ahead with the next thing... or, am I wrong?

**Comment by snappizz** [comment]
The commit IDs are different. The merged commit is 40503a6, and this one is 19350f8.

**Comment by vivid-synth** [comment]
@snappizz the code is the same, though -- it should probably merge fine

**Comment by jamshark70** [comment]
I think vivid is right. Locally, I cherry-pick things all the time, which creates a new ID for the copy of the commit, and then when I do a merge later (into the branch that was also the target of the cherry-pick), I don't remember seeing duplicate commits in the history.

I guess we should test it but I'm pretty sure this is no problem.

**Comment by jamshark70** [comment]
So... I made a testing repository to try a cherry-pick and merge, and I actually did get a conflict that I had to resolve. So it wasn't as transparent as I expected.

But... here, github says there are no conflicts and it can be merged automatically, which could mean a couple of things. So I guess my local test case was different from the state of this PR.

FWIW I tried the command line instructions to merge the PR locally into the current master, and it fast-forwarded, reporting no conflicts, and "git log" did not show duplicate commits. 40503a6e30 below is the one that would have been duplicated. (qgit showed duplicates, but I think that's because it tries to visualize the commit tree. The commandline log is clean.)

```
$ git log SCClassLibrary/Common/Streams/Rest.sc
commit cce6208d9bc2292aac91a8521728a0d0ebbc63f7
Author: James Harkins <jamshark70@dewdrop-world.net>
Date:   Tue Nov 15 08:41:16 2016 +0800

    Classlib: Collection:processRest must return the processed value

commit 40503a6e30579d722e91ccc73b8a12a02f18394b
Author: James Harkins <jamshark70@dewdrop-world.net>
Date:   Tue May 3 13:55:05 2016 +0800

    Classlib: Add 'isRest' to Rest
    
    Without this, 'Rest(1).isRest' is false!

commit 047543a9be621a42a939cea5276f2e31b62e38d9
Author: James Harkins <jamshark70@dewdrop-world.net>
Date:   Wed Nov 5 14:37:17 2014 +0800

    Classlib: Rest: Add 'value' method to simplify mixing rests and numbers
```
... etc.

**Comment by jamshark70** [comment]
I was just looking up this issue in connection with a mailing list question, and I noticed -- it has the "has conflicts" label, but at the bottom, "This branch has no conflicts with the base branch." I understand why the label was added, but maybe we can remove it now?

Note my previous comment:

> FWIW I tried the command line instructions to merge the PR locally into the current master, and it fast-forwarded, reporting no conflicts, and "git log" did not show duplicate commits. 40503a6 below is the one that would have been duplicated. (qgit showed duplicates, but I think that's because it tries to visualize the commit tree. The commandline log is clean.)

**Comment by telephon** [comment]
yes, please remove it!

**Comment by jamshark70** [comment]
I'd like to suggest closing this. The rest reform will make this change unnecessary, and there's no need at this point to merge additional complexity that will be reverted in a couple of weeks' (months?) time.

**Comment by brianlheim** [comment]
I agree; I think #2802 is an overall better approach. Let's focus our discussion on that for now.

**Pull request closed without merging**
