### PR TITLE
Qt52 - is it ready?

### PR DESCRIPTION
**Pull request by telephon**
It would be nice to move forward – if we can – with QT5, possibly with QT 5.4 (http://qt-project.org/wiki/New-Features-in-Qt-5.4). 

I tried to use the homebrew install (````brew install qt5````), but cmake lacked the package config file: ````Qt5MacExtrasConfig.cmake````.

Are there may possible issues with this branch?

### CODE REVIEW

**Comment by timblechmann** [comment]
i'd go for: https://github.com/timblechmann/supercollider/tree/topic/qt5-win

despite its name, it is not windows-only and it contains various fixes that i have accumulated over the last months. fwiw, qt5 can easily be installed via the qt installers, no need for homebrew.

**Comment by telephon** [comment]
Ah ok, thank you. I'd prefer a homebrew installer if possible, because that would give a uniform workflow. But if that isn't in place it would be OK.

Have you tried this branch on windows and OS X, too?

**Comment by timblechmann** [comment]
i had compiled this branch on osx, windows and linux

**Comment by bagong** [comment]
We need @scztt 's opinion on that. Tim's Windows changes are required to compile the Windows-version, but only the first half of them have been merged into this branch, because the second half conflicted with changes Scott had made to the build system. Looks like switching to Tim's branch would undo some work Scott had done with a reform of the scide/sclang-application bundle in mind.

**Comment by bagong** [comment]
Requiring the qt-installers would also conflict with the travis stuff Scott worked for.

**Comment by timblechmann** [comment]
@bagong, there is no "requirement" for the official installer, just a recommendation from someone working with qt every day

**Comment by muellmusik** [comment]
FWIW, and without knowing what the travis issues are, I also recommend the official installers. They've always worked in a very straightforward way, and seem much less hassle than home brew.

**Comment by scztt** [comment]
Merging changes from tim's qt5-win and the mainline qt52 branch is still going to be required, as far as I can tell. @timblechmann's qt5-win branch doesn't build properly on mac - verify_app fails during the install step, and it looks like there might be duplicate executables. It sounds like tim has successfully built  and run on OSX at some point, so there may be an issue with the build instructions? It would be helpful to validate the qt5-win branch with travis, to ensure it's building in a clean environment.

**Comment by scztt** [comment]
Regarding qt5 installers - I don't think it's necessary to REQUIRE one form of installation over another. Homebrew is already required for installing other required components, so doing the qt5 installation this way involves the least handholding, extra manuals steps, and is the most well-tested via travis - I think it makes sense to have this be the way that's called out in the build instructions. However, it would be a major problem if manual installers were not also supported, so any problems there should be dealt with as bugs / documented appropriately also.

**Comment by timblechmann** [comment]
@scztt i've built it on osx just a few days ago

**Comment by scztt** [comment]
@timblechmann Will try again - after attempting to build the other day, I saw several similar issue so I suspect it was something about the state of my system.

**Comment by telephon** [comment]
… did it work?

**Comment by timblechmann** [comment]
fwiw, have just built it a few minutes ago on osx 10.10.

**Comment by telephon** [comment]
For me it says:

````
CMake Warning at QtCollider/CMakeLists.txt:24 (find_package):
  By not providing "FindQt5MacExtras.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5MacExtras", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5MacExtras" with
  any of the following names:

    Qt5MacExtrasConfig.cmake
    qt5macextras-config.cmake
````

(I have a homebrew qt5, but it would be nice if it worked with this, too.)

Should I add the path to the directory containing Qt to ````CMAKE_PREFIX_PATH````?

**Comment by timblechmann** [comment]
On 28/02/15 20:03, Julian Rohrhuber wrote:
> For me it says:
> 
> |CMake Warning at QtCollider/CMakeLists.txt:24 (find_package):
>   By not providing "FindQt5MacExtras.cmake" in CMAKE_MODULE_PATH this project
>   has asked CMake to find a package configuration file provided by
>   "Qt5MacExtras", but CMake did not find one.
> 
>   Could not find a package configuration file provided by "Qt5MacExtras" with
>   any of the following names:
> 
>     Qt5MacExtrasConfig.cmake
>     qt5macextras-config.cmake
> |
> 
> (I have a homebrew qt5, but it would be nice if it worked with this, too.)
> 
> Should I add the path to the directory containing Qt to |CMAKE_PREFIX_PATH|?


the recommended way to obtain qt is
http://www.qt.io/download-open-source/

**Comment by telephon** [comment]
> (I have a homebrew qt5, but it would be nice if it worked with this, too.) Should I add the path to the directory containing Qt to |CMAKE_PREFIX_PATH|?
>the recommended way to obtain qt is http://www.qt.io/download-open-source/ 

What a shame – it would have been nice to have a bit more uniformity. I hope the installs don't interfere.

**Comment by telephon** [comment]
OK, installed with the online installer at http://www.qt.io/download-open-source/ now. 

But it makes no difference, the cmake error remains:

on ````cmake -L ..````, it shows that it still hasn't found the paths.

````
Qt5Core_DIR:PATH=Qt5Core_DIR-NOTFOUND
Qt5MacExtras_DIR:PATH=Qt5MacExtras_DIR-NOTFOUND
Qt5Network_DIR:PATH=Qt5Network_DIR-NOTFOUND
Qt5OpenGL_DIR:PATH=Qt5OpenGL_DIR-NOTFOUND
Qt5Positioning_DIR:PATH=Qt5Positioning_DIR-NOTFOUND
Qt5PrintSupport_DIR:PATH=Qt5PrintSupport_DIR-NOTFOUND
Qt5Qml_DIR:PATH=Qt5Qml_DIR-NOTFOUND
Qt5Quick_DIR:PATH=Qt5Quick_DIR-NOTFOUND
Qt5Sensors_DIR:PATH=Qt5Sensors_DIR-NOTFOUND
Qt5Sql_DIR:PATH=Qt5Sql_DIR-NOTFOUND
Qt5WebKitWidgets_DIR:PATH=Qt5WebKitWidgets_DIR-NOTFOUND
Qt5WebKit_DIR:PATH=Qt5WebKit_DIR-NOTFOUND
Qt5Widgets_DIR:PATH=Qt5Widgets_DIR-NOTFOUND
````

**Comment by timblechmann** [comment]
cmake won't magically find Qt:

http://doc.qt.io/qt-5/cmake-manual.html
tells:
In order for find_package to be successful, Qt 5 must be found below the CMAKE_PREFIX_PATH, or the Qt5<Module>_DIR must be set in the CMake cache to the location of the Qt5WidgetsConfig.cmake file. The easiest way to use CMake is to set the CMAKE_PREFIX_PATH environment variable to the install prefix of Qt 5.

**Comment by telephon** [comment]
>cmake won't magically find Qt.

If we would uniformly rely on hombrew, it would be possible, no?

Thanks for the pointers. The instructions in the manual are not accurate, but I'll try to add instructions for it in the README.

You need:

````cmake -DCMAKE_PREFIX_PATH=/PATH/TO/QT5/5.4/clang_64/lib/cmake/ ..````

This will have to change each time when we update to a new version of QT.

**Comment by timblechmann** [comment]
feel free to use homebrew, though personally i recommend to use the official installer.

you have to remove your build folder anyway when upgrading to a new version of qt.

**Comment by telephon** [comment]
OK, using the above cmake command, this branch built fine on OS 10.10. I did a ````make clean```` before.

SCIDE crashes on start, however:

````
Process:               SuperCollider [19186]
Path:                  /Volumes/VOLUME/*/SuperCollider.app/Contents/MacOS/SuperCollider
Identifier:            net.sourceforge.supercollider
Version:               3.7 (alpha0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           SuperCollider [19186]
User ID:               501

Date/Time:             2015-03-01 14:48:21.999 +0100
OS Version:            Mac OS X 10.10.2 (14C109)
Report Version:        11
Anonymous UUID:        E1C69DE8-44DD-4D3F-A4EB-72FBB03271B2

Sleep/Wake UUID:       EFEE91F6-4EAA-43A3-961D-2AA64886ADC1

Time Awake Since Boot: 440000 seconds
Time Since Wake:       2000 seconds

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Application Specific Information:
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff91b56286 __pthread_kill + 10
1   libsystem_c.dylib             	0x00007fff8b8f8b53 abort + 129
2   QtCore                        	0x000000010d2f8d29 qt_message_fatal(QtMsgType, QMessageLogContext const&, QString const&) + 9
3   QtCore                        	0x000000010d2fa1e1 QMessageLogger::fatal(char const*, ...) const + 161
4   QtGui                         	0x00000001111da0b7 QGuiApplicationPrivate::createPlatformIntegration() + 6359
5   QtGui                         	0x00000001111da0db QGuiApplicationPrivate::createEventDispatcher() + 27
6   QtCore                        	0x000000010d5138e1 QCoreApplication::init() + 113
7   QtCore                        	0x000000010d513857 QCoreApplication::QCoreApplication(QCoreApplicationPrivate&) + 39
8   QtGui                         	0x00000001111d754e QGuiApplication::QGuiApplication(QGuiApplicationPrivate&) + 14
9   QtWidgets                     	0x000000011099aaae QApplication::QApplication(int&, char**, int) + 206
10  net.sourceforge.supercollider 	0x000000010d0883ef main + 47 (main.cpp:51)
11  libdyld.dylib                 	0x00007fff8a8085c9 start + 1

Thread 1:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x00007fff91b57232 kevent64 + 10
1   libdispatch.dylib             	0x00007fff85c8fa6a _dispatch_mgr_thread + 52

Thread 2:
0   libsystem_kernel.dylib        	0x00007fff91b5694a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff91a9a40d start_wqthread + 13

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff91b5694a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff91a9a40d start_wqthread + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff91b5694a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff91a9a40d start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff91b5694a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff91a9a40d start_wqthread + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff52b7e428  rdx: 0x0000000000000000
  rdi: 0x000000000000130f  rsi: 0x0000000000000006  rbp: 0x00007fff52b7e450  rsp: 0x00007fff52b7e428
   r8: 0x00007fff52b7e390   r9: 0x00007fff74ea3300  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x000000010d60ab88  r13: 0x00007fd378c003e0  r14: 0x00007fff74ea3300  r15: 0x00007fff52b7e9e4
  rip: 0x00007fff91b56286  rfl: 0x0000000000000206  cr2: 0x00007fff7435ffd8
  
Logical CPU:     0
Error Code:      0x02000148
Trap Number:     133
````

**Comment by telephon** [comment]
… trying again with deleted build folder now.

**Comment by telephon** [comment]
OK, this worked. Good!

**Comment by timblechmann** [comment]
you might want to start the binary from terminal. especially when seeing something like QMessageLogger or qt_message_fatal in the backtrace. sending the crash information to apple might not be too helpful, though

**Comment by telephon** [comment]
So I'll test the branch a little. The first impression is good.

Minor issue, but I don't know how to fix it:
- The SCIDE icon is a cube.

**Comment by telephon** [comment]
Another problem to fix: font display in ````Pen```` on a retina display is wrong:

````
// displays a ragged anti-aliased font
(
var w, font;

w = Window.new("gui", Rect(100, 300, 300, 200)).front;
w.view.background_(Color.new255(153, 255, 102).vary);

w.drawFunc = {
	var font = Font("Helvetica", 40).boldVariant;
	Pen.stringAtPoint("Smooth".asString, Point(40, 40), font, Color.black);
};

w.front;
)
````

This works well for ````TextView````.

**Comment by telephon** [comment]
Similarly for ````Pen.stroke````:

````
(
w = Window.new.front;
w.view.background_(Color.white);
w.drawFunc = {
    // set the Color
    Pen.strokeColor = Color.red;
    Pen.moveTo(200@100);

    Pen.lineTo(250@200);
    Pen.lineTo(300@200);
    Pen.lineTo(200@250);
    Pen.lineTo(100@200);
    Pen.lineTo(150@200);
    Pen.lineTo(200@100);

    Pen.stroke
};
w.refresh;
)
````

**Comment by telephon** [comment]
screen shot 2015-03-01 at 17 41 38

**Comment by muellmusik** [comment]
> feel free to use homebrew, though personally i recommend to use the official installer.

I would also suggest that we should support the official installer as default as well. If cmake can be made to find homebrew Qt as well though, that would be great.

**Comment by telephon** [comment]
A bit worse, maybe:

- The ````Cmd-period````-key binding doesn't work anymore, but the menu entry does
- The Server display doesn't update (stays as 0.00 %).

**Comment by telephon** [comment]
> If cmake can be made to find homebrew Qt as well though, that would be great.

Yes. The problem is that the installer asks you where to install it, and it thus may be anywhere. We could require one of a number of places, maybe?

**Comment by muellmusik** [comment]
> Yes. The problem is that the installer asks you where to install it, and it thus may be anywhere. We could require one of a number of places, maybe?

Yes maybe. Is there not a default location?

**Comment by telephon** [comment]
The default location the installer suggests is the user home directory. I don't know if this is where most people would like to have it, I wouldn't, seems too "high level" somehow. But probably one can check a few standard paths. A problem may be that the QT installer asks you to *create* a folder first, in which it then expands all the files. It suggests no name, so that could be anything.

**Comment by telephon** [comment]
In the current master, cmake finds Qt4 automatically here:

````-- Found Qt4: /usr/local/bin/qmake (found suitable version "4.8.6", minimum required is "4.7") ````

**Comment by muellmusik** [comment]
I'm no cmake expert, but shouldn't ```find_package``` be able to find Qt5 as well?

**Comment by telephon** [comment]
Looking at the ````CMAkeLists.txt```` file, it seems that currently it is using ````find_package````.
I've tried and changed the current one to:

````
set(required_qt_version 5.4)


find_package (Qt5 ${required_qt_version} COMPONENTS QtCore QtGui QtWebKit)

````

this finds the paths, but also goes wrong:

````
CMake Warning at /usr/local/lib/QT5/5.4/clang_64/lib/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5QtCore" with
  any of the following names:

    Qt5QtCoreConfig.cmake
    qt5qtcore-config.cmake

  Add the installation prefix of "Qt5QtCore" to CMAKE_PREFIX_PATH or set
  "Qt5QtCore_DIR" to a directory containing one of the above files.  If
  "Qt5QtCore" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  QtCollider/CMakeLists.txt:4 (find_package)
  lang/CMakeLists.txt:180 (include)


CMake Warning at /usr/local/lib/QT5/5.4/clang_64/lib/cmake/Qt5/Qt5Config.cmake:26 (find_package):
  Could not find a package configuration file provided by "Qt5QtGui" with any
  of the following names:

    Qt5QtGuiConfig.cmake
    qt5qtgui-config.cmake

  Add the installation prefix of "Qt5QtGui" to CMAKE_PREFIX_PATH or set
  "Qt5QtGui_DIR" to a directory containing one of the above files.  If
  "Qt5QtGui" provides a separate development package or SDK, be sure it has
  been installed.
Call Stack (most recent call first):
  QtCollider/CMakeLists.txt:4 (find_package)
  lang/CMakeLists.txt:180 (include)
````

**Comment by timblechmann** [comment]
>   * The |Cmd-period|-key binding doesn't work anymore, but the menu
>     entry does
>   * The Server display doesn't update (stays as 0.00 %).

fwiw, these issues (and a lot of others) are fixed in my topic/qt5-win
branch:
https://github.com/timblechmann/supercollider/tree/topic/qt5-win

despite the suffix -win, it also compiles on osx and linux ...

**Comment by scztt** [comment]
I'm closing this pull request. This branch got combined with a few of tims fixes that were missing, and merged into master.

**Pull request closed without merging**
