### PR TITLE
supernova: don't delete shared memory data

### PR DESCRIPTION
**Pull request by timblechmann**
fixes crash on exit

### CODE REVIEW

**Comment by telephon** [comment]
shouldn't this go into 3.7?

**Comment by miguel-negrao** [comment]
Any reason not to merge this ???

**Comment by danstowell** [comment]
@miguel-negrao your question marks suggest incredulity. No-one's actually confirmed that the fix works or makes sense, which is what PRs are supposed to be about (otherwise why not just commit to trunk)

**Comment by bagong** [comment]
Yes Dan, I am happy to test this soon, not quite just yet. This is the second attempt at an issue for which Victor proposed a solution in the past. Victor and Tim discussed a lot then. I should be a pretty well thought out fix. If it really solves "the" server crash issue, it is not "just another" bug fix and should be seriously considered for 3.7

**Comment by miguel-negrao** [comment]
> @miguel-negrao your question marks suggest incredulity. No-one's actually confirmed that the fix works or makes sense, which is what PRs are supposed to be about (otherwise why not just commit to trunk)

@danstowell Yes, sorry, my comment was not very constructive. I saw a one liner by the author of supernova, I reckoned it would be safe to merge. I wasn't questioning the importance of pull-requests.

With this commit doing a ctrl-c on supernova still causes a crash:

```
(gdb) signal 2
Continuing with signal SIGINT.
Cannot read socket fd = 10 err = Success
CheckRes error
JackSocketClientChannel read fail
Cannot open supernova client
JackShmReadWritePtr1::~JackShmReadWritePtr1 - Init not done for 4294967295, skipping unlock
[Thread 0x7fffe500a700 (LWP 24210) exited]
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
jack_set_thread_init_callback called with a NULL client
jack_set_process_callback called with a NULL client
jack_set_xrun_callback called with a NULL client
jack_on_info_shutdown called with a NULL client
[Thread 0x7fffe508b700 (LWP 24209) exited]
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_port_register called with a NULL client
jack_get_sample_rate called with a NULL client
jack_get_buffer_size called with a NULL client

Program received signal SIGFPE, Arithmetic exception.
0x000000000049b401 in nova::cpu_time_info::resize (this=0x7fffffff1978, sampleRate=0, blockSize=0, seconds=1)
    at /home/miguel/Development/SuperCollider/supercollider/server/supernova/./audio_backend/cpu_time_info.hpp:38
38	        const size_t blocks = sampleRate * seconds / blockSize;

(gdb) frame
#0  0x000000000049b401 in nova::cpu_time_info::resize (this=0x7fffffff1978, sampleRate=0, blockSize=0, seconds=1)
    at /home/miguel/Development/SuperCollider/supercollider/server/supernova/./audio_backend/cpu_time_info.hpp:38
38	        const size_t blocks = sampleRate * seconds / blockSize;
(gdb) bt
#0  0x000000000049b401 in nova::cpu_time_info::resize (this=0x7fffffff1978, sampleRate=0, blockSize=0, seconds=1)
    at /home/miguel/Development/SuperCollider/supercollider/server/supernova/./audio_backend/cpu_time_info.hpp:38
#1  0x000000000049e15d in nova::jack_backend<nova::realtime_engine_functor, float, false>::open_client (this=0x7fffffff18f0, server_name="", 
    name="supernova", input_port_count=8, output_port_count=8, blocksize=64)
    at /home/miguel/Development/SuperCollider/supercollider/server/supernova/./audio_backend/jack_backend.hpp:125
#2  0x000000000049774c in (anonymous namespace)::start_audio_backend (args=...)
    at /home/miguel/Development/SuperCollider/supercollider/server/supernova/server/main.cpp:136
#3  0x00000000004984ee in main (argc=3, argv=0x7fffffffdda8) at /home/miguel/Development/SuperCollider/supercollider/server/supernova/server/main.cpp:395
```

Not sure this is the same issue the commit was trying to fix ?

**Comment by miguel-negrao** [comment]
I can't seem to replicate that error again. Now I always get this one (I did a rm -r * and compiled again to be on the safe side. this is with Debug build.):

```
(gdb) signal 2
Continuing with signal SIGINT.
Jack: xrun detected - resyncing clock
Jack: xrun detected - resyncing clock
[Thread 0x7fffe4f89700 (LWP 31452) exited]
[Thread 0x7ffff7e7f740 (LWP 31455) exited]
[Thread 0x7ffff7f00740 (LWP 31454) exited]
[Thread 0x7ffff7f81740 (LWP 31453) exited]
[Thread 0x7ffff3d10700 (LWP 30563) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffe633f700 (LWP 30565)]
0x00007fffe6cda07a in ?? ()
(gdb) bt
#0  0x00007fffe6cda07a in ?? ()
#1  0x0000000000000000 in ?? ()
```

**Comment by gusano** [comment]
> No-one's actually confirmed that the fix works or makes sense, which is what PRs are supposed to be about (otherwise why not just commit to trunk)

@danstowell PRs are supposed to be reviewed, which is why committing to "trunk" (i.e. master) should be avoided

**Comment by miguel-negrao** [comment]
> @danstowell PRs are supposed to be reviewed, which is why committing to "trunk" (i.e. master) should be avoided

That is exactly what @danstowell said. :-)

**Comment by timblechmann** [comment]
two points:
* PRs can be automatically compiled and unit-tested before they are merged
* PRs can be manually reviewed (trying to read and understand the consequences, maybe learning something for the future)

**Pull request merged**
