### PR TITLE
class library: server is marked as unresponsive instead of dead when …

### LINKED ISSUE #774: Server loses SHM after computer sleep
When I leave the server running while computer is sleeping, the server seems to lose its SHM interface:

s = Server.local.boot;
s.hasShmInterface; // true
//Put the computer to sleep, and wake it up again, leaving the server running
s.hasShmInterface;  // false
s.reboot;
s.hasShmInterface; // true

I'm on a MacBook running OSX 10.6.8.

### LINKED ISSUE #889: After a server sleep, shm interface is lost
// this happens when the computer is asleep, but can be reproduced by allocating a larger buffer.
// you'll have to wait for a while (it simulates sleep by buffer allocation)

```
(
fork {
    s.quit;
    1.wait;
    s.waitForBoot {
        [\hasShmInterface, s.hasShmInterface].postln; // true
        Buffer.alloc(s, 48000 * 60 * 60 * 4);
        s.sync;
        [\hasShmInterface, s.hasShmInterface].postln; // false
    }
}
)
```

// as serverRunning_(val) actually tests whether the computer is sleeping to optimise this a little,
// we need to see ifthis actually works. If not, this can be the source of the problem, but things like the above (long periods of unreachability because of a cumbersome request would still kill the shm interface.

```
(
fork {
    var t = Main.elapsedTime;
    loop {
        [Main.elapsedTime - t, thisProcess.platform.isSleeping].postln;
        0.5.wait;
    }
}
)
```

### PR DESCRIPTION
**Pull request by telephon**
…asleep

This fixes #774 and fixes #889.
A better, fully refactored server version is in another pull request, but it is more likely to break existing code.

### CODE REVIEW

**Comment by scztt** [comment]
@telephon - Can you specify a quick test case to verify this is working?

**Comment by telephon** [comment]
From the issue:

````
(
fork {
    s.quit;
    1.wait;
    s.waitForBoot {
        [\hasShmInterface, s.hasShmInterface].postln; // true
        Buffer.alloc(s, 48000 * 60 * 60 * 4);
        s.sync;
        [\hasShmInterface, s.hasShmInterface].postln; //  this should be true as well.
    }
}
)
````

**Comment by telephon** [comment]
And this:
````
// put your computer to sleep for ten seconds while this is running
(
fork {
    var t = Main.elapsedTime;
    loop {
        [Main.elapsedTime - t, thisProcess.platform.isSleeping].postln;
        0.5.wait;
    }
}
)
````

**Comment by telephon** [comment]
Better even:
````
(
// put your computer to sleep for ten seconds while this is running
fork {
   loop {
        [\hasShmInterface, s.hasShmInterface, s.unresponsive].postln; // true, true is OK!
		1.wait;
    }
}
)
````

**Comment by telephon** [comment]
I'm not sure if this was tested enough. I have mainly used the fully refactored branch (https://github.com/supercollider/supercollider/tree/topic/refactor-server-clean) for the last months. I actually wonder if we should move this one into 3.7 instead of 3.8.

**Comment by telephon** [comment]
If we merge #1655 into `3.8`, then we don't need this one. This is only meaningful for `3.7`, if we say that the problem can wait, we can save the trouble and ignore this one.

**Comment by crucialfelix** [comment]
closing, see: https://github.com/supercollider/supercollider/pull/1935

**Pull request closed without merging**
