### PR TITLE
Fix compilation with boost-1.67

### PR DESCRIPTION
**Pull request by TristanCacqueray**
Purpose and Motivation
----------------------

This change is required to build supernova with a system boost version >1.66

Types of changes
----------------

- Bug fix (non-breaking change which fixes an issue)

Checklist
---------

- [ ] All tests are passing
- [ ] If necessary, new tests were created to address changes in PR, and tests are passing
- [ ] Updated documentation, if necessary
- [ ] This PR is ready for review

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
The fix is borrowed from https://github.com/balint256/gr-baz/issues/55.

**Comment by brianlheim** [comment]
Thanks! Could have sworn we had an open issue or even PR for this somewhere else but I guess not. I've made this fix locally before when checking if there were issues upgrading our bundled boost to 1.67, this is correct AFAIK.

**Comment by dvzrv** [comment]
Sorry for being late to the party, but yes, this already got fixed, but never cherry picked onto 3.10!
https://github.com/supercollider/supercollider/issues/3981
https://github.com/supercollider/supercollider/pull/4097

**Comment by snappizz** [comment]
ah hell. that should have been my responsibility. sorry about that!

**Comment by dvzrv** [comment]
@snappizz no worries. I would completely get lost with all of these branches and different merges in this repository on a daily basis ;-)
I guess we only have to take care, that this merge won't conflict, once 3.10 gets merged back to develop or something like that.

**Pull request merged**
