### PR TITLE
Fix PSinGrain

### PR DESCRIPTION
**Pull request by patrickdupuis**

### CODE REVIEW

**Comment by patrickdupuis** [comment]
First time trying @brianlheim's wonderful cherry-picking script. Did I get it right?

**Comment by brianlheim** [comment]
@patrickdupuis nice! You should try the new version of the script; it will reference the original (so the link will appear in the other PR's conversation) and also includes a link to the script itself.

https://gist.github.com/brianlheim/7809f7a062362f0ea3ff1490ae12694b

**Comment by patrickdupuis** [comment]
Sweet!
________________________________

**Comment by brianlheim** [comment]
This works, awesome!

**Pull request merged**
