### PR TITLE
ide: introducing themes management

### PR DESCRIPTION
**Pull request by vdonnefort**
This patch adds IDE themes management. It has the same behaviour as QtCreator.
There is some default theme provided and the user can copy them to create a new
one. Only user created theme can be edited. For now only default theme is
provided: "default".

### CODE REVIEW

**Comment by miczac** [comment]
Hi Vincent, I'm on OS X 10.8.5:
What 'current' theme would be converted: from _3.6_ or _3.7a prior to this PR_?
IAC as of 266456bc819be4ed82acbc02d5324f909ec2db1a (per now) the post window is black on black,
and the editor's theme colours are not converted entirely:
This is from 3.7a before this PR got merged: 
screen_shot_2015-01-21_at_16 23 22
(note the dark-grey background of the current line)
which became this (per today):
screen_shot_2015-01-21_at_16 25 43
Is there anything I could/should test etc?   thx, Michael.

**Comment by vdonnefort** [comment]
Hi Michael,

At the first theme manager usage, the previous configuration is stored into "My old theme".  The all elements remains the same.

I think you point the wrong commit id (266456b) :)

What I understand of your problem is: the "current line" is not correctly imported from the old theme. Is that correct?

If you set again the "current line" to black, is it working?

**Comment by miczac** [comment]
Sorry about the commit confusion! I meant to point at what version I compiled to test.
I didn't follow the recent developments and bisected to see what caused the miss-colouring.
Since I got many flavours of errors regarding the theme I decided to test the most recent version.
Yes, the import for the current line background is not correct: it's white, not dark grey as I set it.
And also yes, I can correct the colour in "My old theme" to dark grey, which is apparently
properly stored and recalled.
BTW, while testing I just found that I can't set the foreground colour of the current line. Thanks!

**Comment by vdonnefort** [comment]
- I can't even see any currentLine configuration applied w/ Ubuntu (w/ or /w theme management support). I'll give a try later w/ a OSX 10.9

- The second point you're talking about is related to this commit:
       2e604d7c102e08923c3995e53307d0cd3dadccc2  ide: themes: disable unused options display for currentLine
 This is a "normal" behaviour. The colour box is disabled.

**Comment by vdonnefort** [comment]
@miczac How do you trig the "current line" colors? :)

**Comment by miczac** [comment]
Not sure what you mean by "triggering", It's just there:
sc37a-current_line-2
also when there's a fresh profile:
sc37a-current_line-no_prev_profile
regarding "disable unused options display for currentLine" - is the interface meant to reflect this disabled state? IOW, how would a user realise that the fg-colour can't be set?

**Comment by vdonnefort** [comment]
* I mean that even if I set a red background for "Current Line", I never see any red on my editor with any SC version.

* The disabled mode in Qt is sadly not visible, we'd better to remove the color picker!

**Comment by miczac** [comment]
* AFAICS no problem here to set. Just had a terrible pink for a test. ;)
* BTW, what's the idea of this checkbox [x] to the right of the picker? Clicking it the picker becomes inaccessible ("disabled"). But clicking it again doesn't show it's active again, only if I selected a colour via the picker (by clicking on the shaded version of the picker box).

**Comment by vdonnefort** [comment]
The checkbox allows to "remove" the color, to set it to "transparent".

**Comment by vdonnefort** [comment]
@miczac, this patch https://github.com/vdonnefort/supercollider/commit/ee832c9bc0093d17f9404bc1a66ce09df4c7944a should fix your import problem: some keys (created after 3.6) weren't imported.

**Comment by miczac** [comment]
@vdonnefort importing from a 3.7a profile created before this PR works now. CurrentLine is there - thx!
And I can see now what you probably meant by "I can't even see any currentLine configuration".
I deleted the entire profile, created one by starting 3.6.6, switched to 3.7a/post PR and also don't even see a selection for "Current Line". It looks a bit weird ATM, have too look again this evening, need to see the pattern.

**Comment by vdonnefort** [comment]
Thanks @miczac for testing!

Do you have any other problems before I send a PR?

**Comment by miczac** [comment]
@vdonnefort - if you could wait until evening, something appears weird when switching versions of SC and "updating" then. I got rehearsals now - have to have a deeper look, maybe it's just me.

**Comment by miczac** [comment]
@vdonnefort - I can see a probably similar situation like you described before on your system:
I'm not able to make CurrentLine work if there's no profile at the first place. Curiously enough I also don't get it when using an older binary before this original themes-PR. IAC I can see the selection entry for CurrentLine but choosing a colour has no effect. Also when I create a fresh profile by starting 3.6.6 after deleting the profile and step be step "update" the profile by starting newer binaries. 
The background colour of CurrentLine only works to be set when using my existing profile.

**Comment by vdonnefort** [comment]
Thanks again @miczac. This is not related to my patch but I will give a look at it.

I updated my branch https://github.com/vdonnefort/supercollider/commits/scide/theme-mgmt-fix with your remarks about the clear foreground button.

**Comment by vdonnefort** [comment]
@miczac The current line needs the "highlight current line" option set to work (settings > editor > display). I think I can now send the new PR.

**Comment by miczac** [comment]
@vdonnefort  - ah forgot to check. :/ That's it of course.
And from this experience, it would be convenient if disabled GUI-elements reflected their state. (my 2c)
Thanks for the reminder! ;)

**Pull request merged**
