### PR TITLE
Make the required version Windows Vista

### PR DESCRIPTION
**Pull request by llloret**
Make Windows Vista the minimum required version.

### CODE REVIEW

**Comment by bagong** [comment]
@llloret , does anything immediate depend on this or would this be enough for master?

**Comment by llloret** [comment]
@bagong, that should be enough for master.

>

**Comment by bagong** [comment]
So the PR should be moved to the master branch, sorry to say. We are currently in this unfortunate situation that working and testing is a lot easier on this branch, but the actual commits should go into the respective vanilla branches. But let's only do this, once the PR's are considered done. Give me a day or so for this one, I can build master using MinGW... 

I wish we could find a solution to that IPC-problem that doesn't interfere with the other OSses. I'll try to inspect to which degree the Windows specific part of the general "Unicode" issue plays into this.

Would you mind me tagging the midi-PR as "work in progress, don't merge"? ;)

**Comment by llloret** [comment]
Sure, @bagong, you now what's the best way to organise this.

>

**Comment by bagong** [comment]
Just didn't want to appear impolite ;)

**Comment by bagong** [comment]
This is fine with master. So let's commit it to master. Will you redo the pull request yourself?

**Comment by llloret** [comment]
I'll do it later today.

>

**Comment by llloret** [comment]
@bagong, I have created PR #2017 to merge into master.

**Comment by bagong** [comment]
Cool!

**Pull request closed without merging**
