### PR TITLE
example on sending audio feature extraction in osc

### PR DESCRIPTION
**Pull request by tiagmoraismorgado**
example on sending audio feature extraction in osc. i came across with a doubt on how to do this. and eventually was able to practically fix this. however, i think it is important that this scenario is covered within the documentation of this class

### CODE REVIEW

**Comment by brianlheim** [comment]
@tiagmoraismorgado Thanks. I edited your submission for styling and clarity. Here are some suggestions for future submissions:

- try to keep your code to one statement (one semicolon) per line
- make sure your example does something, either visually or sonically, when it's run. I added "msg.postln" because seeing the data in the post window makes the behavior much clearer
- indent your code with tabs. Your original submission had each line indented by a single space. Notice how I changed each line inside the pairs of `{}` so that the code would appear like it does when indented by the IDE.

**Comment by brianlheim** [comment]
> Pitch outputs an array. at least use SendReply.kr(trig, '/amp', [amp, freq[0]]);

The components get flattened in the array; the second element of `Pitch`'s output is useful feature extraction info.

> and what is at port 5000? maybe add a comment about what it is good for.

How would you change the comment `// Sending audio feature extraction data over a network via OSC` or the variable name `~testNetAddr` to make this clearer?

**Comment by redFrik** [comment]
what do you mean?  on my machine (osx, sc3.8) this example is clearly broken.  here's what it the oscdef posts...
```
[ /amp, 1000, -1, 0.00025629863375798 ]
[ /amp, 1000, -1, 3403.2373046875, 0 ]
[ /amp, 1000, -1, 6.8446002842393e-05 ]
[ /amp, 1000, -1, 3403.2373046875, 0 ]
[ /amp, 1000, -1, 0.00050326448399574 ]
[ /amp, 1000, -1, 3403.2373046875, 0 ]
[ /amp, 1000, -1, 0.00021246251708362 ]
[ /amp, 1000, -1, 3403.2373046875, 0 ]
[ /amp, 1000, -1, 0.00024830986512825 ]
[ /amp, 1000, -1, 3403.2373046875, 0 ]
[ /amp, 1000, -1, 0.0003573932335712 ]
[ /amp, 1000, -1, 3403.2373046875, 0 ]
[ /amp, 1000, -1, 0.001629265374504 ]
```

so you're sending over amplitudes of 3403.  bad.

we could give some idea of what the receiver is.  is it a custom python script? some vj app or is it another laptop?  it's for sure very abstract as written. and to call amp and freq 'audio feature data' is a bit of an overstatement in my opinion.

**Comment by brianlheim** [comment]
@redFrik Good points, have a look at #2977.

**Pull request merged**
