### PR TITLE
Topic/fix aa methods of triggered rand

### LINKED ISSUE #1278: TRand, TExpRand, TIRand are broken for audio-rate inputs
This is SC 3.6.5, not tested with SC 3.7 yet:

```
// kr -- ok
x = play {
  var p = Impulse.kr(1);
  var lo = \lo.kr(0);
  var hi = \hi.kr(1);
  var t = TRand.kr(lo, hi, p);
  t.poll(p, "rand");
  0
}

// ar -- moves towards hi and sticks to hi value
x = play {
  var p = Impulse.ar(1);
  var lo = \lo.ar(0);
  var hi = \hi.ar(1);
  var t = TRand.ar(lo, hi, p);
  t.poll(p, "rand");
  0
}
```

### PR DESCRIPTION
**Pull request by telephon**
## Purpose and Motivation

Fixes #1278

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] This PR is ready for review

### CODE REVIEW

**Comment by telephon** [comment]
these tests succeed:

```supercollider
(
{
  var p = Impulse.ar(400);
  var lo = \lo.ar(0);
  var hi = \hi.ar(10);
  var t = TIRand.ar(lo, hi, p);
 t
}.plot(0.15)
)


(
{
  var p = Impulse.ar(400);
  var lo = \lo.ar(0);
  var hi = \hi.ar(10);
  var t = TRand.ar(lo, hi, p);
 t
}.plot(0.15)
)


(
{
  var p = Impulse.ar(400);
  var lo = \lo.ar(0.01);
  var hi = \hi.ar(10);
  var t = TExpRand.ar(lo, hi, p);
 t
}.plot(0.15)
)



````

**Comment by jamshark70** [comment]
One of the things we can learn from this bug, as a dev community, is the importance of a well-designed test.

We are testing whether the bounds of triggered-rand update correctly in the middle of a control cycle, at audio rate.

But the test uses constant bounds.

So the test is incapable of detecting failure! (Well, it may detect *some* failures, but there's a large category of failure that is invisible to this test structure.)

A better designed test would ensure that each successive sample has a range that doesn't overlap with the previous or next sample. If, at time point x, the random number is not within the range, then you know that the range is not being processed correctly.

```supercollider
(
s.waitForBoot {
	var cond = Condition.new;
	var didFail = false;
	
	l = List.new;
	
	OSCdef(\collect, { |msg| l.add(msg[3..]) }, '/trandTest', s.addr);
	
	a = {
		var lo = Sweep.ar(0, SampleRate.ir);
		var hi = lo + 0.25;
		var trig = Impulse.ar(SampleRate.ir * 0.01);   // 100 samples per trig
		var data = [
			lo, hi,
			TRand.ar(lo, hi, trig),
			TExpRand.ar(lo, hi, trig),
			TIRand.ar(lo * 100, hi * 100, trig)  // an integer range should not be smaller than 1.0
		];
		SendReply.ar(trig, '/trandTest', data);
		Line.kr(0, 1, 1, doneAction: 2);
		Silent.ar(1);
	}.play;
	
	a.onFree { cond.unhang };
	cond.hang;
	
	l.do { |row, j|
		var lo, hi, rand;
		#lo, hi ... rand = row;
		rand.do { |value, i|
			if(i == 2) { value = value * 0.01 };
			if(value.inclusivelyBetween(lo, hi).not) {
				row.debug("failed");
				didFail = true;
			};
		};
	};
	
	if(didFail) { "There were failures".postln };
};
)
```

Running this without the patch, basically every row fails. (So, if the test had been more carefully considered six years ago, the bug would have been detected immediately and an improper fix would never have been merged.)

And after applying the patch, *all* of the failures disappear.

So:

- Tested, works, so it can be reviewed for style and then merged.
- The above test code should be cleaned up and added to the test suite.
- Part of the dev process is to design a good test.

**Comment by telephon** [comment]
Thank you, James! Two things I have to say:

- the test is so complicated that I am not sure I could have written it correctly
- you'd have to be a prophet to write a test that already knows what will fail
- looking at the code directly, anyone could have seen my utterly silly mistake just by reading


The consequences, imho:
- your test is a great step towards an improvement of our unit test system. I think it should be generalised and integrated as a test method. Maybe there is even a general way of testing for similar issues in going from control rate to audio rate elsewhere?
- we might want to emphasise actually reading code for reviewing a little more in the future (and of course as an author as well!)

**Comment by telephon** [comment]
The linter fails, but I don't understand the problem from reading the error message. The line where it fails wasn't changed.

```
if (next > 0.f && prev <= 0.f) {
             int range = hival - loval + 1;
             RGen& rgen = *unit->mParent->mRGen;
             ZXP(out) = outval = (float)(rgen.irand(range) + loval);
Error: Process completed with exit code 1.
```

**Comment by dyfer** [comment]
It seems that the linter wants to have variable declarations in a [single line](https://github.com/supercollider/supercollider/pull/5336/checks?check_run_id=1841859944#step:4:23), and also complains about some whitespace.

We have instructions on the [wiki](https://github.com/supercollider/supercollider/wiki/Cpp-formatting-instructions) how to [format](https://github.com/supercollider/supercollider/wiki/Cpp-formatting-instructions#working-with-clang-format) your code locally. There are also plugins for various editors to edit the code automatically.

**Comment by telephon** [comment]
thank you! Indeed the indentation settings of xcode had been wrong again, so that was the whitespace part. I also improved some things that looked like horrible formatting to my eye. As for the rest, I have no idea.

The installation and use of a full linter toolchain seems way too complicated for me. I'll have to leave it at that.

**Comment by jamshark70** [comment]
One thing that I wasn't clear about in my last message is that I see this as a process (community) mistake much more than an individual mistake. 2014 is, IIRC, before current code review practices -- "anyone could have seen [the] mistake just by reading" but we didn't. We *all* missed it. It's valid to autopsy and consider ways to prevent it in the future.

For future testing, one conclusion is: If we're testing audio rate modulation, the test is incomplete if the modulator doesn't change mid-block. *All* ar-modulation tests should consider this.

"you'd have to be a prophet to write a test that already knows what will fail" -- that's true sometimes. In this specific case, my thought process was:

- The difference between modulating a parameter at control rate vs audio rate is that control rate modulation can change only at the beginning of a control block, while audio rate modulation can change in the middle of a block. That is: If the modulation is not changing mid-block, then there's no point in it being audio rate. 

- Therefore, an ar-parameter test without new values mid-block is not testing the feature that distinguishes ar parameters -- hence the conclusion above. (No prophecy involved here: `DC.ar(x)` looked suspicious because a constant input can't test mid-block value changes.)

- In this specific case, if a trigger occurs `n` samples into a block, and we're modulating the random range, then there's a range lo1 .. hi1 at sample n-1, and lo2 .. hi2 at sample n. So, for testing, the modulation for `lo` should guarantee lo1 != lo2. (If they are equal, then we don't know if the range updated.)

- If lo1 .. hi1 and lo2 .. hi2 overlap (if lo2 < hi1), then the random number could be between lo2 and hi1. In that case, you can't tell which range the RNG was using at trigger time. So we need to guarantee lo1 != lo2 *and* lo2 > hi1. So this test increments lo by 1 each sample (lo2 = lo1 + 1), and the range is smaller than 1.0 (hi1 = lo1 + 0.25, guaranteeing the condition).

- So then, if, at trigger time, lo <= random <= hi is *not* true, we can be certain that it's because the range was not updated mid-block correctly.

The test code could be simplified, maybe:

```
(
s.waitForBoot {
	var successResp, failureResp;
	var result;
	var cond = Condition.new;

	successResp = OSCFunc({ |msg|
		result = true;
		cond.unhang;
	}, '/randSuccess', s.addr);

	failureResp = OSCFunc({ |msg|
		result = false;
		"Failed: Expected range % - %, got a value %"
		.format(*msg[3..])
		.warn;
		cond.unhang;
	}, '/randFailure', s.addr);

	{
		var trig = Impulse.ar(SampleRate.ir / 100);
		var lo = Sweep.ar(0, SampleRate.ir) * 10;
		var hi = lo + 5;
		var rand = [TRand.ar(lo, hi, trig), TExpRand.ar(lo, hi, trig), TIRand.ar(lo, hi, trig)];
		var ok = (rand >= lo) * (rand <= hi);  // array of 3
		var stopCtl = Line.ar(0, 1, ControlDur.ir * 10, doneAction: 2);
		var done = Done.kr(stopCtl);
		var shouldStop = done;
		ok.do { |flag, i|
			var test = (flag <= 0) * trig;
			SendReply.ar(test, '/randFailure', [lo, hi, rand[i]]);
			shouldStop = shouldStop + T2K.kr(test);  // stop immediately on failure
		};
		SendReply.kr(done, '/randSuccess');
		FreeSelf.kr(shouldStop);
		Silent.ar(1)
	}.play;

	cond.hang;

	successResp.free;
	failureResp.free;

	"OK: %\n".postf(result);
};
)
```

Server tests always seem to involve some "glue" -- here, the principle of the test is fairly straightforward, but the mechanics of getting the result back from the server and managing the node are extremely delicate -- e.g., the failure trigger needs to be ar but `FreeSelf` supports only kr. (I lost a good half hour just now over a minor error in the failure OSCFunc above.) It would be helpful if we did some more work on the testing infrastructure, so that we don't have to improvise notification and node control for every UGen test. "the test is so complicated that I am not sure I could have written it correctly" -- this sort of burden should not be put onto every developer who touches UGen code!

**Comment by brianlheim** [comment]
> The installation and use of a full linter toolchain seems way too complicated for me. I'll have to leave it at that.

we've been working really hard to make it easier for people to install and use clang-format, maybe you could give it a try and let us know where you get stuck?

**Comment by telephon** [comment]
OK, thank you! I've added an issue here to keep the discussion separate: 5340

**Comment by telephon** [comment]
Made a fresh one here: #5344

**Pull request closed without merging**
