### PR TITLE
server: added binout to SpecPcile

### PR DESCRIPTION
**Pull request by woolgathering**
If enabled, outputs the bin number directly instead the calculated 
frequency. If interpolate is true, performs linear interpolation and 
outputs a fractional bin as a float.

## Purpose and Motivation

I needed the functionality of SpecPcile UGen but needed the bin number as opposed to the frequency. Works as expected.

## Types of changes

- Documentation
- New feature

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Hi Jacob! Could you please [fix](https://github.com/supercollider/supercollider/wiki/Cpp-formatting-instructions#example-workflow) the formatting?

**Comment by woolgathering** [comment]
Ah! Ok, still learning how to properly contribute. 

I used clang 8.0.0 and after running `./build/format.py` there are no changes to any of the files I modified. Is this expected behavior?

**Comment by woolgathering** [comment]
Amended the commit to include the correct formatting and keep the commits clean.

**Comment by brianlheim** [comment]
thanks for this @woolgathering and sorry for the delay in reviewing! i have two questions about this, specifically the difference between `interpolate` and `binout`.

`interpolate` is set at initial rate (`ir`), when the UGen is constructed, while `binout` is chosen at control rate (`kr`). is there a reason for that choice? if there is a reason, it should be documented. also, whatever the final choice, whether these two arguments are `ir` or `kr` should also be documented.

`interpolate` is enabled if the input is > 0.0f, but if i'm reading correctly `binout` is enabled if the input is != 0.0f. these should be consistent. also, the fact that these are positive/nonpositive switches should be documented; right now the documentation only says that they accept 0 and 1 but don't describe the behavior with any other input.

**Comment by woolgathering** [comment]
@brianlheim Also sorry for the delayed reply! 

1.) I guess I just got kind of lazy and didn't want to go modify the struct. Makes more sense as an `ir`. I'll change that.

2.) Ah, yes, that is a mistake. It also should be `> 0.0f`; it's that way in my ugly fork of SC and forgot to edit that in the PR. I'll also more clearly document the expected input and behavior.

**Review by joshpar — APPROVED** [review]

**Pull request merged**
