### PR TITLE
ClassLib: Make Pbind work with kwargs

### PR DESCRIPTION
**Pull request by JordanHendersonMusic**
## Purpose and Motivation

Simply append the kwargs (as keyword-value pairs) to the list of pairs.

Explain different in the help file, along with the nuance with unpacking multiple keys from PTuple.

Add test to check keywords are identical with key-value pairs.

```supercollider
Pbind(a: Pseq([1, 2, 3]), dur: 1).trace.play
```

## Types of changes

- New feature

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Review by telephon — APPROVED** [review]
Yes, this was one of the convincing points about kwargs.

**Review by telephon — CHANGES_REQUESTED** [review]
only merge when tested …

**Comment by JordanHendersonMusic** [comment]
One question is whether I should change all examples in the help docs?? Opinions? The down side (as mentioned) is that it can't do unpacking* but this doesn't occur often.



*Technically, it might be possible, to make the following a language feature...
```
f.(#[a, b]: [1, 2]) == f.(a: 1, b: 2)
```

I kinda like this as it's similar to 
```
#a, b = g.();
```

**Comment by telephon** [comment]
yes, I would first make the syntax complete before changing all examples. And I think the syntax should be implemented, because it avoids people have to think through special cases. If you have time, that would be excellent of course.

**Comment by JordanHendersonMusic** [comment]
This one might take a moment because it means dealing with the parsenodes (which are quite messy). I've messed with them before with trying to get variable declarations in any order, I got quite close, but didn't have time to investigate.

**Comment by JordanHendersonMusic** [comment]
So adding that additional syntax might actually be quite challenging so should be a separate PR. 

This PR just makes kwargs possible with `Pbind` and alters the documentation to mention this.

**Review by telephon — APPROVED** [review]

**Review by capital-G — APPROVED** [review]
Thanks Jordan, this is such a great addition! Looking forward to use it soon in performances :)

**Pull request merged**
