### PR TITLE
add ability to skip travis with commit message

### PR DESCRIPTION
**Pull request by brianlheim**
Purpose and Motivation
----------------------

Sometimes you want to be able to skip building on Travis, like in #4038.

Use the line from https://gist.github.com/alexislefebvre/597ad49e5f60e804ea2d45b73de9967d to allow [skip travis] in the commit message to skip travis builds.

Types of changes
----------------

- Documentation (non-code change which corrects or adds documentation for existing features)
- New feature (non-breaking change which adds functionality)

Checklist
---------

- [x] Updated documentation, if necessary
- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
Gah, for some reason that first commit gets skipped too.

**Comment by brianlheim** [comment]
@patrickdupuis this is not in a mergeable state yet

**Comment by gusano** [comment]
@brianlheim sorry if I miss the obvious but why not using `[skip ci]` which seems to do what you want?
https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build

**Comment by snappizz** [comment]
@gusano sometimes it's good to just skip one or the other. for example, if you're editing linux or macOS such as supernova, `[skip appveyor]` is highly recommended to speed things up since we can only have one appveyor build at a time.

**Comment by gusano** [comment]
@snappizz yes but I was talking about skipping travis, which is already natively supported by travis

**Comment by brianlheim** [comment]
@gusano

skip ci skips both travis and appveyor

skip appveyor only skips appveyor

there is currently no way to only skip travis, while letting appveyor run.

**Comment by brianlheim** [comment]
No time to work on this at the moment, will revisit later.

**Pull request closed without merging**
