### PR TITLE
Abstract message matcher copy fix

### PR DESCRIPTION
**Pull request by muellmusik**
Fix for Issue #1306

### CODE REVIEW

**Comment by telephon** [comment]
>>Wouldn't it be clearer to override removeFunc instead? The .copy seems unusual in any case.
>We need the copy to allow for altering active[key] while iterating. 

But we are iterating over ````keys````, not over ````active```` – the ````removeFunction```` interface isn't meant to require a copy.

>But the normal removeFunc tests for identity. 

Yes, I did that with a few doubts, but it is better than ````==```` in this case.

>The problem is if it's not a FunctionList, but just an AbstractMessageMatcher.

It should behave like a ````Function````, which would be the last object you get *returned* when you do ````removeFunc````, which in turn just behaves like Object.

**Comment by muellmusik** [comment]
> But we are iterating over keys, not over active – the removeFunction interface isn't meant to require a copy.

I think it does in some cases. I'll try to be clearer:

- The dispatcher calls value on active[someKey] when it receives a message for someKey.
- If that's a FunctionList it will iterate over the list.
- There we need copy, because any member of that list might modify the list.
- However, FunctionList returns a single member if we're down to size one.
- This is fine if it's a Function, since aFunction::copy === aFunction
- But if it's an AbstractMessageMatcher that doesn't work, and removeFunc fails.
- So the proposed solution is to make AbstractMessageMatcher::copy behave like Function::copy

But other solutions are possible. (Override removeFunc, use something besides a FunctionList, etc.)

> It should behave like a Function, which would be the last object you get returned when you do removeFunc, which in turn just behaves like Object.

That's sort of what I'm trying to do, but the problem is that the polymorphism of removeFunc, while very elegant, doesn't deal well with cases where evaluation calls removeFunc on the receiver.

Hope that makes more sense.

**Comment by telephon** [comment]
I wonder whether it was such a good idea to implement the symmetry between adding and removing:

addFunc:
````nil ------> func ------> FunctionList[func, func] ------> ...````

removeFunc
````… ------> FunctionList[func, func] -----> func ------> nil````

Essentially it is an automatic optimization, because in many cases, you won't need more than one functions. When removing, however, one could just keep the function list as long as possible (a bit like a hysteresis principle).

removeFunc
````… ------> FunctionList[func, func] -----> FunctionList[func] ------> nil````

Not as "clean", but if this would avoid such issues before one runs into them, it may be better.

**Comment by telephon** [comment]
… the alternative would be of course to explicitly state in the documentation that only objects can be safely added with ````addFunc```` that can't be copied, like ````Function```` and ````Thread```` (````Routine````).

**Comment by telephon** [comment]
Or, shouldn't maybe rather ````FunctionList```` copy its array on calling ````value````?

The following wouldn't cause any more strain to the garbage collector:
````
value { arg ... args;
		var res = array.copy;
		res.size.do { |i| res.put(i, array.at(i).valueArray(args)) };
		^if(flopped) { res.flop } { res }
	}
````

**Comment by muellmusik** [comment]
> I wonder whether it was such a good idea to implement the symmetry between adding and removing

I also wondered this, but it has a sort of beauty! ;-)

> value { arg ... args;
>         var res = array.copy;
>         res.size.do { |i| res.put(i, res.at(i).valueArray(args)) };
>         ^if(flopped) { res.flop } { res }
>     }

Ah that could be good. We should test and bench it. Travelling today, but I'll try to look into it ASAP.

S.

**Comment by telephon** [comment]
Here is a branch that implements it: https://github.com/supercollider/supercollider/tree/topic/function-list-copies-before-iteration

If the addition of the method ````collectInPlace```` is disputable, I can do it locally in FunctionList. I just thought that sometimes, it may actually be exactly what you want.

**Pull request closed without merging**
