### PR TITLE
Update Lexer to allow symbols like \1a

### PR DESCRIPTION
**Pull request by brianlheim**
Previously, symbols beginning with a backslash and combining digits and letters would throw a parse error if the first character was a digit, even though the same symbol could be notated without a problem in single quotes. This commit gets rid of some unnessary goto splits in the lexer that were causing the issue.

Also adding regression tests to TestParser.sc.

### CODE REVIEW

**Comment by snappizz** [comment]
This fixes #2673.

**Comment by brianlheim** [comment]
New tests added, these will only pass after merge. They run fine on my build, could someone else give them a go please?

Failures before:
```
There were failures:
a TestParser:test_symbolLiterals - '12ab_' should be a legal symbol literal when preceded by backslash 
Is:
	 nil 
Should be:
	 3 

a TestParser:test_symbolLiterals - '2ab_1' should be a legal symbol literal when preceded by backslash 
Is:
	 nil 
Should be:
	 3 
```

No failures after.

**Comment by brianlheim** [comment]
Should I add some regression tests to make sure something like `\1asString: 1234` is never legal again? (shudder)

**Comment by brianlheim** [comment]
@telephon That's something I've been asking myself. Two things I noticed are (1) how the goto sections for accidentals and floating point numbers with exponents are structured (which is to say, very awkwardly), and (2) the fact that the label 'symbol4' is used here, which gives a hint as to the order of implementation. 

My guess would be that this made sense for a particular use case when it was added, and then either (1) it was never tested fully or (2) the surrounding code changed and those changes were never regression tested. My guess would be that first there was symbol1 and symbol2, and then when symbol3 was added JMC went back and wrote symbol4 so that digits would work in \-symbols.

That's an "additive" interpretation, you might say. My "subtractive" interpretation is that symbol2 and symbol4 used to have some meaningful distinction. Maybe one pointed to processsymbol(), and the other pointed to something else; the labels could even have been different. Later on, perhaps that development path was nixed and the code changed to what it was in 2002.

**Comment by snappizz** [comment]
I'm not looking at all the data here so this is just a guess -- maybe it started with `\symbols` only supporting valid identifiers, and support for digits was added later.

**Comment by telephon** [comment]
Both interpretations sound similar, and plausible, also because the code that comes from around that time necessarily went out the door as it was and unpolished.

**Comment by brianlheim** [comment]
Does anyone have objections to merging this now? As I've said before, I have concerns about changing the lexer before regression tests are in place, but since the class library compiles correctly and the tests I added work it should be OK.

**Comment by snappizz** [comment]
No objections here, but I'd like to see an approval from another contributor first.

**Comment by brianlheim** [comment]
Closing until the lexer-parser-compiler regression tests are brought in.

**Pull request closed without merging**
