### PR TITLE
readme: rename OS X to macOS

### PR DESCRIPTION
**Pull request by snappizz**

### CODE REVIEW

**Comment by snappizz** [comment]
weird, GitHub told me that the first commit had a conflict, but merging via command line didn't ask me to resolve anything

**Comment by brianlheim** [comment]
Actually, hold on... A change needs to be made to the cmake file, the Xcode build is failing because it can't find the renamed readme.

**Comment by bagong** [comment]
It's in the top level CMakeLists.txt line 450

**Comment by brianlheim** [comment]
Got it! Through grep, also found a reference to the readme file in the package generator, which I updated.

**Comment by bagong** [comment]
Thanks, although MacOS still feels weird ;)

**Comment by snappizz** [comment]
Thanks Brian!

**Pull request merged**
