### PR TITLE
comment bad include to sndfile to let windows compile supernova

### PR DESCRIPTION
**Pull request by sonoro1234**
All is expained in issue #4017

### CODE REVIEW

**Comment by sonoro1234** [comment]
why travis is failing with removed include but not with commented include?

**Comment by brianlheim** [comment]
Sometimes CI builds fail for spurious reasons; I've restarted it. That is something to look into eventually but it's workable for now since most maintainers have permissions to restart the builds.

**Comment by sonoro1234** [comment]
When is it going to be merged?

**Comment by brianlheim** [comment]
I don't know. We usually wait for 1 person to review and 1 person to merge, so whenever else someone has a chance to look at it.

**Pull request merged**
