### PR TITLE
[schelp.scd] link to supercollider book tutorials

### PR DESCRIPTION
**Pull request by tiagmoraismorgado**
adding link to supercollider book tutorials. the motivation behind sharing this link, lies within the fact that it's universally accepted as one of the most comprehensive resources to learn supercollider

### CODE REVIEW

**Comment by bagong** [comment]
I think it would be nicer to edit the files, remove unnecessary/duplicate parts (rtf, quarks). I think the volume will boil to to about a 10th of the current. And then add it to the examples folder.

**Comment by brianlheim** [comment]
> I think it would be nicer to edit the files, remove unnecessary/duplicate parts (rtf, quarks). I think the volume will boil to to about a 10th of the current. And then add it to the examples folder.

1.7 MB of example code is still a lot, and duplicates the "Getting started" tutorials already in this repo. In fact, less so, because it is only figures and no explanations. My question is still, why? Seems like a lot of extra work and a lot of duplication for no real gain.

**Comment by bagong** [comment]
I am not particularly passionate about this. But it would be practical for people reading the book, it would give the community behind the book more personal visibility in SC, and it might even generate some sales ;)

**Comment by brianlheim** [comment]
All of that is accomplished by linking to the book and the code examples from the documentation... so let's do that

**Comment by tiagmoraismorgado** [comment]
i think it is ok to add 1.7 mb of code. and i think we can credit the authors, which can be a nice thing

**Comment by snappizz** [comment]
not on the main page, please. there should be a link to another page which aggregates 3rd-party tutorials.

**Pull request closed without merging**
