### PR TITLE
help: fix broken links in multiple helpfiles

### PR DESCRIPTION
**Pull request by redFrik**
Purpose and Motivation
----------------------

used a regexp script and found many helpfiles that had broken links - mainly for instance methods but also a few class methods and section links.
all changes tested manually and confirmed to work.

```
.findAllRegexp(" link::#[^-*]*::");
```

### CODE REVIEW

**Comment by patrickdupuis** [comment]
Would it be possible for you to rebase this PR on `3.10`? That way, it will be part of `3.10.1`.

**Comment by redFrik** [comment]
i give up.  even with the updated instructions i couldn't solve the situation.  made a fresh start here https://github.com/supercollider/supercollider/pull/4233

**Comment by brianlheim** [comment]
Note that there is a bug on GitHub where this PR appears as merged even though it technically wasn't. AFAICT that's because the last commit on this branch is a merge commit that also happens to be the tip of 3.10. By changing the base, GitHub erroneously considers this PR merged, not closed. I thought I was going loopy at first, but confirmed with a second test PR: https://github.com/supercollider/supercollider/pull/4234

cc @patrickdupuis

**Comment by redFrik** [comment]
now i get confused.  what i saw after pushing my first rebase attempt was like here above "htor and others added some commits on 18 Jul 2018" and then a lot of unrelated additions going back a few months. same thing can be seen in https://github.com/supercollider/supercollider/pull/4234 and in https://github.com/supercollider/supercollider/pull/4235
of course i assumed i had broken something.
can you explain to a git newbie like me what is going on here, where these unrelated additions come from and if i should've just ignored them in the first place?  thanks.

**Pull request closed without merging**
