### PR TITLE
Big Sur patches for 3.11

### PR DESCRIPTION
**Pull request by dyfer**
## Purpose and Motivation
The PR applies patches that creates SC functionally equivalent to version 3.11.2, that runs on macOS Big Sur. This build also seems compatible with macOS Catalina.

For context see:
https://github.com/supercollider/supercollider/issues/5168#issuecomment-778898320
https://github.com/supercollider/supercollider/issues/5168#issuecomment-779081643

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
per discussion on #5358 we will not be merging this to 3.11

**Comment by dyfer** [comment]
> per discussion on #5358 we will not be merging this to 3.11

I was planning to change the destination branch once it's created; it was marked as a "draft" to avoid accidental merge. I'm planning to reopen this once the destination branch is ready

**Comment by brianlheim** [comment]
ok! that works too

**Review by brianlheim — APPROVED** [review]
thanks!

**Pull request merged**
