### PR TITLE
PyrLexer: expand "~" in pathnames in passOne_processDir

### LINKED ISSUE #3547: Paths in library configuration files are not tilde-expanded
## Introduction

I believe I've spotted (and resolved: see related pull request, incoming shortly) a regression that occurred some time between SuperCollider 3.8.1 and the most current code.  In short, paths specified with leading tildes in library configuration files are no longer expanded.  Reproduction notes are shown below.

Testing platform: MacOS Sierra 10.12.6

## Setup

The following shows the contents of a simple library configuration file with one `includePaths` entry which contains a path with a leading `~`.  The directory referenced in `includePaths` is shown to exist.

```
$ cat ~/includes.conf.yaml
includePaths:
  [~/sc-includes]
$ file ~/sc-includes
/Users/USER/sc-includes: directory
```

## 3.8.1 MacOS Release--Expected Behavior: "~" Is Expanded

You can see below that `~` is properly expanded on SuperCollider's 3.8.1 MacOS release: `/Users/USER/sc-includes` is compiled without error.

```
$ sclang -version
sclang 3.8.1 (Built from branch 'HEAD' [05f3d5e])
$ sclang -l ~/includes.conf.yaml
init_OSC
compiling class library...
initPassOne started
	NumPrimitives = 711
initPassOne done
	compiling dir: '/Applications/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary'
	compiling dir: '/Library/Application Support/SuperCollider/Extensions'
	compiling dir: '/Users/USER/Library/Application Support/SuperCollider/Extensions'
	compiling dir: '/Users/USER/sc-includes'
	pass 1 done
	numentries = 810198 / 11056472 = 0.073
	5012 method selectors, 2206 classes
	method table size 12146520 bytes, big table size 88451776
	Number of Symbols 11434
	Byte Code Size 344559
	compiled 312 files in 1.42 seconds
compile done
Class tree inited in 0.02 seconds
Cleaning up temp synthdefs...


*** Welcome to SuperCollider 3.8.1. *** For help type cmd-d.
sc3>
Exiting sclang (ctrl-D)
sc3> main: waiting for input thread to join...
main: quitting...
cleaning up OSC
```

This is the expected behavior.

## "develop" Branch--Regression: "~" Is NOT Expanded

The most recent SuperCollider code no longer expands `includePaths` entries with leading leading tildes.  These paths are interpreted literally, leading to a missing directory error.

```
$ Install/SuperCollider/SuperCollider.app/Contents/MacOS/sclang -version
sclang 3.9.1 (Built from branch 'develop' [6f5476609])
$ Install/SuperCollider/SuperCollider.app/Contents/MacOS/sclang -l ~/includes.conf.yaml
compiling class library...
	Found 714 primitives.
	Compiling directory '/Users/USER/Developer/github/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/Resources/SCClassLibrary'
	Compiling directory '/Library/Application Support/SuperCollider/Extensions'
	Compiling directory '/Users/USER/Library/Application Support/SuperCollider/Extensions'
WARNING: Could not open directory: '~/sc-includes'
	To resolve this, either create the directory or remove it from your compilation paths.

	numentries = 809256 / 11415240 = 0.071
	5142 method selectors, 2220 classes
	method table size 12295432 bytes, big table size 91321920
	Number of Symbols 11655
	Byte Code Size 354589
	compiled 322 files in 0.56 seconds
compile done
localhost : setting clientID to 0.
internal : setting clientID to 0.
Class tree inited in 0.02 seconds


*** Welcome to SuperCollider 3.9.1. *** For help type cmd-d.
sc3>
Exiting sclang (ctrl-D)
sc3> main: waiting for input thread to join...
main: quitting...
cleaning up OSC
```

An incoming pull request provides a solution for this issue.

### PR DESCRIPTION
**Pull request by mneilsen**
This changeset fixes a regression that eliminated tilde-expansion on
paths specified in library configuration files.

This fixes #3547.

### CODE REVIEW

**Comment by brianlheim** [comment]
Awesome, thanks for this! I'll give it a try soon.

We should really have a description of the directory scanning process somewhere, it's a little thorny and I think users would probably benefit from knowing. Maybe in a Reference schelp doc. I'll also try to think of a way we could add unit tests for this, it's likely to be touched again for fixes or refactors and quite time consuming to check by hand.

**Comment by brianlheim** [comment]
@snappizz - opinions on putting this in 3.9.2?

**Comment by brianlheim** [comment]
Sure, can you open a PR for it?

**Comment by mneilsen** [comment]
Thanks!  Apologies if this is a silly question, but what branch should I base the PR on?  3.9?  master?

**Comment by brianlheim** [comment]
No worries! I forget that it's not immediately obvious, sorry. Please base it on 3.9.

**Comment by mneilsen** [comment]
Thanks Brian!  New PR against 3.9: #3643

**Pull request merged**
