### PR TITLE
WIP: ide/qtcollider: prototype port to qwebengine

### PR DESCRIPTION
**Pull request by timblechmann**
setting up the architecture for qtwebengine ... there are still some issues with the help browser, which might need some love, but the hard part is done.

someone might want to adopt and polish it
## 

todo:
- WebView::setFontFamily
- HelpBrowser::onLinkClicked is still broken

### CODE REVIEW

**Comment by bagong** [comment]
This is very cool!
It builds for me both on OSX with Qt5.5.1 (but crashes on startup) and on Ubuntu 14.04 with Qt5.5.1. (and "works"). The later is quite similar to the travis build system. I'll try to see what is wrong with the travis build image, maybe just a package missing.

On OSX I get a crash. The crash report is posted here:

https://gist.github.com/bagong/397c096a6fcaf4d24b1fa00ba3b39b09

**Comment by bagong** [comment]
OSX, using qt5.6, same thing. Builds but crashes at startup:

https://gist.github.com/bagong/40f92b620bb8043aa589f3b862677b94

**Comment by bagong** [comment]
For Windows: Webenginewidgets seem not to be available in the MinGW build of Qt5.6. As the VS build is broken atm, this cannot be tested on Windows.

**Comment by timblechmann** [comment]
diy

**Comment by telephon** [comment]
I've reopened this, because it makes it easier to solve #2204. I'm not competent to do it, but maybe this helps a little.

**Comment by bagong** [comment]
There is scott carvers (@scztt) branch:

https://github.com/supercollider/supercollider/tree/topic/webengine

I think it has come a bit further than this. I once built it on Windows, and it kind of worked (links broken, but that might work now, since Brian's fix), same on Mac. One thing is getting it to work nicely cross-platform, but there are more considerations:

- webengine is *really* big, like a build of Scott's branch is something like 300MB - seems a bit disproportionate for a help renderer ;)
- on Windows it is currently the easier to obtain alternative to webkit *in msvc builds*, but it it is *not* available in mingw builds. I'd still be cautious about saying good by to mingw builds: considerations are
     - sc mingw builds are still less buggy
     - supernova can't be built
     - while readline is broken, it is likely not difficult to fix it in mingw-builds. Atm there is no accepted alternative for msvc-builds
     - oth Brians utf16-pathnames PR works with msvc, but not with mingw (so far)

Note that qtwebkit is currently having a renaissance. It will likely return in Qt 5.10, and it is available as add-on module for all qts from 5.6 upwards. Unfortunately it needs to be built manually in homebrew, but it is already available through several distributions on Linux and in msys2/Windows.

This is a difficult discussion because it will be hard to make a decision ;) For 3.9 though it started to feel like we'd stick with webkit to see how it develops.

**Comment by telephon** [comment]
good arguments, @bagong!

**Pull request closed without merging**
