### PR TITLE
Reponse->Response spelling

### PR DESCRIPTION
**Pull request by anthonylauzon**
## Purpose and Motivation
Code nit.

## Types of changes
Just adding a few 's' characters.

## To-do list

- [X] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [X] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
Thanks @anthonylauzon ! Please rebase this against 3.10 -- see our [contributor's guide](https://github.com/supercollider/supercollider/blob/develop/CONTRIBUTING.md#notes-on-rebasing-and-merge-conflicts) for more information.

**Comment by brianlheim** [comment]
And, please submit changes on a feature/topic branch (i.e., not develop, master, or 3.10); this will make it easy to maintain your fork of the repo.

**Comment by anthonylauzon** [comment]
Would you like me to submit to any particular upstream topic branch?

**Comment by brianlheim** [comment]
> Would you like me to submit to any particular upstream topic branch?

I'm not sure I understand. We have very clear instructions in our [contributing guide](https://github.com/supercollider/supercollider/blob/develop/CONTRIBUTING.md#pull-requests); I would recommend following those. If anything is unclear please let me know!

**Pull request closed without merging**
