### PR TITLE
[docs] - supercollider/supercollider/README_JAILBROKEN_IPHONE.md - fixing minor issues with README file

### PR DESCRIPTION
**Pull request by tmm2018**
[docs] - supercollider/supercollider/README_JAILBROKEN_IPHONE.md - fixing minor issues with README file

### CODE REVIEW

**Comment by brianlheim** [comment]
Everything looks fine except the last paragraph should not be indented.

**Comment by tmm2018** [comment]
hey brian. thank you so much for your precious feedback. unfortunately, i am not being able to fix this one myself. if you have time help me out with this, please. my apologies. thank you so much

a lot of light and peave for all you guys.
cheers

**Comment by brianlheim** [comment]
The last paragraph should not be indented at all.

**Comment by tmm2018** [comment]
hey brian. I am not being able to fix this. if you can help me out, I would be quite thankful. thank you so much

**Comment by jamshark70** [comment]
The fix for the indented paragraph is to delete one leading tab character from one line. I don't think you have to ask Brian to do that for you.

**Comment by brianlheim** [comment]
Please reopen if you can provide a patch.

**Pull request closed without merging**
