### PR TITLE
master -> develop

### PR DESCRIPTION
**Pull request by brianlheim**
## Purpose and Motivation

merge master into develop per workflow docs: https://github.com/supercollider/supercollider/wiki/git-workflow-and-guidelines#releasing

### CODE REVIEW

**Comment by brianlheim** [comment]
@snappizz i think we should merge 3.10 into develop first to resolve the conflict?

**Comment by brianlheim** [comment]
ah, never mind, i see what the problem is.

**Comment by snappizz** [comment]
sometimes you gotta do what you gotta do.

**Comment by brianlheim** [comment]
see #4741

**Pull request closed without merging**
