### PR TITLE
Helpfile fixing

### PR DESCRIPTION
**Pull request by adcxyz**
4 little fixes that SCDoc.renderAll complains about.

### CODE REVIEW

**Comment by crucialfelix** [comment]
oh, was this work in progress ? sorry. I see you merged #2041 

I also already merged that. no problem though, it won't conflict.

but if you want to keep a PR open and push more fixes to it then assign the label "work in progress - don't merge me yet"

**Comment by miczac** [comment]
sorry, found a copy&paste error after committing & pushing.
did a new commit, squashed it and force-pushed. Was that wrong?

**Comment by crucialfelix** [comment]
nothing wrong I think.  I don't think you need to squash anymore because we can select to squash when we merge the PR. I did that for this one.

**Comment by miczac** [comment]
ok, thanks!  BTW, where can a user (me) set the label "work in progress..."? I can't see anything when issuing the PR, and then it's out of my hands.

**Comment by miczac** [comment]
just checked when issuing https://github.com/supercollider/supercollider/pull/2048

**Comment by crucialfelix** [comment]
alberto could have done it. 

maybe you guys should have a single branch and then make one PR. right now poor travis is grinding away for each pull request.  but don't let me stop you folks from your help file hack day. just keep going.

**Comment by miczac** [comment]
I realised that. I'm staying local as much as I can. ;)

**Pull request merged**
