### PR TITLE
Merge develop into 3.9

### PR DESCRIPTION
**Pull request by brianlheim**
Some recent PRs have been made against develop as opposed to 3.9. These should be merged into 3.9, and then 3.9 merged back into develop so the branches are consistent.

cc @snappizz @joshpar - Am I doing this right?

### CODE REVIEW

**Comment by brianlheim** [comment]
Not sure what will happen with that merge conflict if using the web editor. I think @jamshark70 tried that once and it had unintended consequences. Since we are working with permanent branches here probably best to try it via command line.

**Comment by brianlheim** [comment]
Also, w/r/t the merge conflict, use the version of qpm-prep.sh _without_ UnitTesting quark (i.e., the version on 3.9 is correct).

**Comment by joshpar** [comment]
I believe so - develop should be able to be ahead (and unstable). 3.9 should be stable and working toward “ship it”

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by snappizz** [comment]
normally it would be incorrect to merge develop into 3.9, because develop would have new features that won't be released until 3.10. but in this case, all commits to develop are bugfixes and are safe for release.

**Comment by brianlheim** [comment]
> but in this case, all commits to develop are bugfixes and are safe for release.

My thoughts exactly.

Would you be opposed to fixing the merge conflict via a single-commit PR to 3.9 that makes the same changes? That seems like the most risk-free way to do it.

**Comment by snappizz** [comment]
sounds fine to me!

**Comment by crucialfelix** [comment]
btw. the "organizational" tag was meant to be about the supercollider people organization.  It's an odd word though, isn't it.  https://github.com/supercollider/supercollider/issues?q=is%3Aopen+is%3Aissue+label%3Aorganizational

**Comment by brianlheim** [comment]
@crucialfelix Would you suggest a different tag?

**Comment by brianlheim** [comment]
I am performing this merge manually via the command line, on branch 3.9-test. Once that passes, I will update the 3.9 branch by pushing to it directly if that's ok. It is going to be a bit messy, but at least it's going through CI.

**Comment by brianlheim** [comment]
https://travis-ci.org/supercollider/supercollider/builds/287783539

**Comment by brianlheim** [comment]
Update - it passes. @snappizz are you ok with me pushing that directly to 3.9? I.e., 3.9-test was the test version of what 3.9 will look like.

**Comment by snappizz** [comment]
:white_check_mark:

**Pull request merged**
