### PR TITLE
fix scope on internal, solves #1527

### PR DESCRIPTION
**Pull request by adcxyz**

### CODE REVIEW

**Comment by bagong** [comment]
Works for me on OS X 10.10.3, Qt5.4.2. But in general the IDE supports the internal server very badly, actually it looks as if that was never intended.

**Comment by telephon** [comment]
This is true, but I think we should rather add a few steps to support it if possible. But if we want to hurry, it is OK to publish 3.7 without proper support of the internal server and do this for 3.8

**Comment by bagong** [comment]
If a Windows version of 3.7 is wanted - and I very much hope it is - I don't see that we will be ready very soon. The biggest Windows bug has been fixed, but that interferes seriously with the other platforms, and doesn't build on them right now. So from my point of view there is no need to feel in a hurry.
On that line: It would be really helpful if somebody looked into that... (sorry OT), Lucas, who has been working hard, is getting more and more frustrated...

**Comment by telephon** [comment]
[OT] I suppose it is all about making your changes compile on linux and mac? I'm not sure if I can assist with fixing issues there, because I don't know much about the os specific hurdles.

**Comment by bagong** [comment]
Yes, it would be great if somebody on OS X or Linux could make the winport branch build on either of those platforms, ideally in a way that works for all ;)

**Pull request merged**
