### PR TITLE
lang: make "Byte Code Size" and "Number of Symbols" posts only in debug mode

### PR DESCRIPTION
**Pull request by snappizz**
does anyone know what these mean? are they useful information at all? we
already have post messages for the size of the method table.

### CODE REVIEW

**Comment by brianlheim** [comment]
byte code size: total number of byte code elements compiled
# of symbols: the number of symbols registered in the symbol table after compilation

**Comment by brianlheim** [comment]
how would you feel about leaving these in the debug build?

**Comment by vivid-synth** [comment]
I don't care if they go, but I recall someone saying they use that info occasionally for debugging. Debug mode seems like a fine compromise

**Comment by snappizz** [comment]
@vivid-synth i remember @jamshark70 noting that the *method table size* was useful occasionally, but i'm not sure i remember anyone defending these two posts.

**Comment by brianlheim** [comment]
@snappizz ok, you can officially consider me as defending them for debug build only then.

**Comment by brianlheim** [comment]
i think this is the same argument i gave in slack - it would take a non-trivial amount of time to find the correct spot to add in these print statements, so i think you are doing future-us a disservice by eliminating that knowledge now, if it becomes useful. and given that we have no unit testing or documented architectural design for the language implementation, these posts are worth something as diagnostics and as structural signposts. my 2c

**Comment by telephon** [comment]
I defend detailed information on startup generally - where it isn't redundant or misleading. Since we do not distinguish between user and developer, it is good to show what is going on. Maybe there are disadvantages of this which I have failed to understand?

Fixing or removing redundant or misleading output, and improving the REPL output in general is really worthwhile.

**Comment by brianlheim** [comment]
> Since we do not distinguish between user and developer, it is good to show what is going on. Maybe there are disadvantages of this which I have failed to understand?

Mm, I agree with nathan that this is totally useless and cluttering information for a user. I only see this being relevant for a developer working on very specific tasks. It's the same reason we don't enable verbose output for Qt code or the scdoc system.

**Comment by telephon** [comment]
Fair enough! 

What about wrapping all this detailed information into a primitive? This would be more useful at least when all works well

**Comment by brianlheim** [comment]
yes, i'd absolutely support that level of interpreter introspection (although i think it is best left for a separate PR)

**Comment by telephon** [comment]
good! It would make sense to immediately feed that new PR with each information moved out from the startup. 

@snappizz do you think you could do this? That would be great!

**Comment by snappizz** [comment]
ping

**Comment by telephon** [comment]
@snappizz do you think you could do this? That would be great!

**Comment by snappizz** [comment]
i'd prefer that to be in a separate PR.

**Comment by telephon** [comment]
sure!

**Comment by snappizz** [comment]
going to put this one on the backlog, not too important

**Pull request closed without merging**
