### PR TITLE
Topic/level indicator

### PR DESCRIPTION
**Pull request by scztt**
See previous #1298

### CODE REVIEW

**Comment by scztt** [comment]
Can we merge?

**Comment by bagong** [comment]
Examples work fine for me on OS X

**Comment by telephon** [comment]
I get a warning:
````
Qt: WARNING: Do not know how to use an instance of class 'Meta_QLevelIndicatorStyle'
````

**Comment by bagong** [comment]
Doesn't apply cleanly anymore. Nobody will test ;)

**Pull request merged**
