### PR TITLE
Expand tilde to users home directory on Windows

### PR DESCRIPTION
**Pull request by miriamvoth**
## Purpose and Motivation

Fixes issue #5330

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [ ] All tests are passing - when I run ctest on the clean current develop branch, test 1&2 fail. Same happens on my branch.
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by miriamvoth** [comment]
I am trying to fix the problem with linting at the moment. It clang was / is not configured properly yet on my system (Windows 10). 
When I run `lint.py develop` I get an error saying "Could not find clang-format at C:\Program Files\LLVM\bin\clang-format". But thats exactly the correct path (including the filename).
Also running `clang-format --version` and `clang-format-diff.py -h` works and gives the expected output.

Suggestions are welcome!

**Comment by dyfer** [comment]
Sorry again for the delay on this.
As far as I remember, the point in the discussion was that tilde expansion is a unix shell convention, and therefore supporting it on Windows would be weird.
Thinking about this again, we already use `.unixCmd` to run commands on all systems, including Windows, and while Bash is not present on Windows by default, it can indeed be installed and used there. Having that in mind, I personally wouldn't mind supporting tilde expansion on that platform as well. What do you think, @jrsurge ?

**Comment by joshpar** [comment]
Hi all - we'd like to pull this in for 3.13.0 and are planning an RC for that after our meeting on Aug, 27, 2022. Anything else to add? Or can we close this?

**Comment by dyfer** [comment]
After discussion with @jrsurge we just want to make sure this doesn't interfere with the current operation of `"~".standardizePath` on Windows and if there are no side effects we'll pull this in. Thanks!

**Review by joshpar — APPROVED** [review]

**Pull request merged**
