### PR TITLE
IDE: greater control over adding editor tabs

### LINKED ISSUE #3941: [SC-IDE] order of tabs in Editor gets reversed with every launch of SC
* SuperCollider version:  master [ 0f779a492]
* Operating system and version:  macos 10.12.6 
* Qt 5.11.1 via homebrew

Order of tabs in in the current session  representing multiple open Documents (files) gets out of order after closing SC and starting again.
It appears the order gets _reversed_ every time SC-IDE is closed and re-launched.
On the contrary the order in the Documents-Docklet is reverse to the order of the Editor's tabs.
And all, but the first file/tab!

In my particular session I have currently 35 files open.

Steps to reproduce
-----------------------------
* move the current profile ```/Users/mz/Library/Application\ Support/SuperCollider``` away
* start SC-IDE
* open 10 arbitrary files
* observe Documents-Docklet and Editor's tabs
* close SC, launch again, check tabs and Doc-Decklet

After posting this observation on sc-users two other observations in that context were reported.
At least one was confirmed to happen on Linux Mint.

### PR DESCRIPTION
**Pull request by mossheim**
Purpose and Motivation
----------------------

Fixes #3941

Previously adding tabs from a session resulted in backwards ordering
because of changes made in #3053 -- restored tabs were now inserted next
to the current index instead of at the end. This commit changes `addTab`
to `insertTab` and allows tabs to be inserted at any index, including
the previous default behavior (when the requested index is negative)

Types of changes
----------------

- Bug fix (non-breaking change which fixes an issue)

Checklist
---------

- [x] All tests are passing

- [x] If necessary, new tests were created to address changes in PR (and tests are passing)

- [x] Updated documentation, if necessary

- [x] This PR is ready for review

### CODE REVIEW

**Comment by miczac** [comment]
thanks a lot, two things popped up here:
* if the current tab is the last one (right-most) than a new tab ("Untitled" after cmd-n) won't get the focus.
screen shot 2018-08-05 at 23 57 59
screen shot 2018-08-05 at 23 58 21
wavetable_...scd is the far right tab in my IDE here.
* noticed, that if the focus is at any tab somewhere (got quite a few open in this session), Documents-Docklet shows the new tab  as last tab:
screen shot 2018-08-06 at 00 09 19
screen shot 2018-08-06 at 00 09 45

**Comment by miczac** [comment]
ad second point:
it's the same when opening an existing file (R2M...txt) :
screen shot 2018-08-06 at 00 35 36
This time I created a new profile with just three files open.
Creating a new doc or loading one like above has the same effect.

**Comment by miczac** [comment]
just cross-checked w/ 3.9.3: 
the second point seems to be part of the original problem and apparently wasn't introduced with this PR. Should I open a dedicated issue for this?

**Comment by brianlheim** [comment]
Yes, please open a separate issue. I cannot reproduce this at all so we'll need more information and time to fix that.

**Comment by brianlheim** [comment]
(So to summarize, this PR fixes a known issue and does not seem to address an issue that was present previously. Should be OK to merge)

**Comment by miczac** [comment]
ok, done: https://github.com/supercollider/supercollider/issues/3945
(ned to establish a tighter testing regimen 😒 )

**Comment by miczac** [comment]
any objections to merge this? This appears to work and **really** helps!

**Pull request merged**
