### PR TITLE
sclang: ease primitive writing

### PR DESCRIPTION
**Pull request by brianlheim**
This PR attempts to alleviate some of the complexity of primitive-related code by reducing boilerplate with convenient macros.

The headliner change is that instead of writing:

```cpp
// takes 2 arguments, not varargs
int prFoo(VMGlobals* g, int numArgsPushed) { /* ... */ }

void initFooPrimitives() {
    /* ... */
    definePrimitive(base, nextPrimitiveIndex(), "_Foo", prFoo, 2, 0);
}
```

one can now simply write:

```cpp
SCLANG_DEFINE_PRIMITIVE( Foo, 2 ) { /* ... */ }
```

with the exact same effect.

---

The main additions are in `SC_PrimRegistry.hpp`, in particular the macros `SCLANG_DEFINE_PRIMITIVE`, `SCLANG_DEFINE_SYMBOL`, and `SCLANG_DEFINE_CUSTOM_INITIALIZER`. Each of these registers an action with a global registry, and the action is then called while the interpreter starts up. In particular:

- `SCLANG_DEFINE_PRIMITIVE`'s action is to call `definePrimitive()`
- `SCLANG_DEFINE_SYMBOL`'s action is to call `s_foo = getsym("foo")`
- `SCLANG_DEFINE_CUSTOM_INITIALIZER` just runs the given function

The remainder of the PR applies these macros to existing primitive code.

I've also rewritten some of the "Writing Primitives" help file to reflect these changes. That may be a good place to start to get an understanding of what's going on.

The way the macros work is (by necessity) a bit dense. I'm happy to explain them if anyone's interested. Personally, I'm not totally satisfied with `SCLANG_DEFINE_SYMBOL`/`SCLANG_DEFINE_SYMBOL_SIMPLE` (the names and the behaviors). I also really don't like that I'm writing these boilerplate structs per registry. There should be a way to simplify that, but I haven't thought it through yet (cc @scztt ?).

TODO:

- [ ] apply these macros to the remainder of primitives. I have a janky python script I've been using to do this, it's not perfect but gets things close enough.
- [ ] I was working with global objects instead of singleton instances for a bit, and I think that is the better way to go (singletons per templated class is kind of arcane), but this caused problems with order of initialization and I think to do it right I'd have to add a .cpp file. I'm not opposed to that, just haven't tried it yet.
- [ ] names are totally up for debate, I haven't pinned them down yet in my mind. `SC_PrimRegistryMacros.hpp` needs a new name; ideally something that indicates its detail status.
- [ ] add any other functionality that would be necessary to turn all bare primitive definitions into macro invocations. Templated primitives are tricky here.

### CODE REVIEW

**Comment by miguel-negrao** [comment]
Didn't test this, but it looks very usefull !

**Comment by miguel-negrao** [comment]
The only downside I can see to this is that now g becomes misterious as its definition is not visible. It's not such a big deal as g was already misterious even when it was clear it was a function parameter. Perhaps this could be improved by also creating macros for extracting the parameters of the sclang method ?

Maybe substituting 

```
SCLANG_DEFINE_PRIMITIVE( signalOverWrite, 3 ) {
    PyrSlot* a = g->sp - 2;
    PyrSlot* a = g->sp - 1;
    PyrSlot* b = g->sp - 0;
```

with something like

```
SCLANG_DEFINE_PRIMITIVE( signalOverWrite, 3 ) {

     SCLANG_GET_CALLER(a);
     SCLANG_GET_ARG(b, 0)
     SCLANG_GET_ARG(c, 1)
```
which would get replaced by something like
```
...
     constexpr int numArgs = 3;
 
      constexpr int a_n = numArgs-1
      PyrSlot* a = g->sp - a_n;
      constexpr int b_n = numArgs - 2 - 0 -> 
      PyrSlot* b = g->sp - b_n;
      constexpr int c_n = numArgs - 2 - 1 -> 
     PyrSlot* c = g->sp - c_n;
```
This totally is untested... I haven't even ever used contexpr :-) but it should calculate the values at compile time. Also, I think static_assert could  be used to do compile time checks that the index passed to GET_ARG doesn't overflow.

Also, wouldn't it be clearer if the second argument of SCLANG_DEFINE_PRIMITIVE was the number of arguments actually passed to the method (so excluding the object itself) ? In this example 2 instead of 3.

**Comment by miguel-negrao** [comment]
Actually, it would be even better to be able to just write

    SCLANG_DEFINE_PRIMITIVE( signalOverWrite, 3, a, b, c) {

Not sure if it is possible to achieve that with macros, but googling I see some pretty crazy stuff done with macros such as iterating over all arguments in a variadic macros or getting the number of parameters passed in. This would do the same as what I proposed above but all in one go (if it is possible, that is...).

**Comment by brianlheim** [comment]
@scztt is working on the arg unwrapping portion I believe. Yes it would be ideal, and Qt primitives already do this IIUC. the point of this PR is to standardize and cleanup this aspect of writing primitives - i.e., avoid adding an explicit extra line or two elsewhere per primitive.

**Comment by brianlheim** [comment]
> Also, wouldn't it be clearer if the second argument of SCLANG_DEFINE_PRIMITIVE was the number of arguments actually passed to the method (so excluding the object itself) ? In this example 2 instead of 3.

But that _is_ the number of arguments actually passed to the method... Either convention would require additional explanation, so I'd prefer to stick with the established one.

**Comment by brianlheim** [comment]
Btw, you will notice that the number of "primitives found" decreases with this PR; that's because the array primitives [were being initialized twice](https://github.com/supercollider/supercollider/blob/develop/lang/LangPrimSource/PyrPrimitive.cpp#L4236-L4245). Now the number of available primitives on macOS is 666. :)

**Comment by brianlheim** [comment]
I've been pruning dead code and variables as I find them, I'm not being very thorough but each deletion is uncontroversial - no references to a given symbol in the entire project; functions with little or no implementation hidden behind undefined macros.

The current design of the registrar system needs to be reconsidered. We need to add a deinitializer registry for components that do deinit: HID and MIDI, and I don't like that this requires adding a new struct. There's also a new case I didn't consider which is calls to `definePrimitiveWithKeys`. I'm not totally sure but I think I may be able to do this more easily with `std::bind`.

Anyway, I'm glad you like it @miguel-negrao and @telephon, I've been wanting to do this for awhile.

**Comment by miguel-negrao** [comment]
> Also, wouldn't it be clearer if the second argument of SCLANG_DEFINE_PRIMITIVE was the number of arguments actually passed to the method (so excluding the object itself) ? In this example 2 instead of 3.
> 
> But that is the number of arguments actually passed to the method... Either convention would require additional explanation, so I'd prefer to stick with the established one.


Is the normal understanding in object oriented languages that the object on which a method is being called is considered one of the arguments ? I thought that, like in C or other function/procedure based languages,  in C++ the arguments are what you declare explicitely in your method prototype that the function accepts. That is why I always found it confusing that  definePrimitive calls it numArgs. Basically one has to remember it is actual numArgs + 1.
 
> Also, there is at least one primitive which is defined as taking 0 arguments.

Do you mean definePrimitive's numArgs is 0 or 1 in that case ? See again, to me, this causes confusion...

**Comment by brianlheim** [comment]
I'm sorry, this conversation is really not related to this PR so perhaps we could have it in another venue if you feel strongly about it. All i have to add at the moment is that this is the implementation of an interpreter, I think you should not expect it to align exactly with the high level descriptions of the language.

And yes, that primitive's numArgs is 0, so if you want to shift everything by one it would become -1.

**Comment by miguel-negrao** [comment]
> I'm sorry, this conversation is really not related to this PR so perhaps we could have it in another venue if you feel strongly about it. All i have to add at the moment is that this is the implementation of an interpreter, I think you should not expect it to align exactly with the high level descriptions of the language.
> 
> And yes, that primitive's numArgs is 0, so if you want to shift everything by one it would become -1.

Oh, ok, I didn't know a primitive could have numArgs = 0, in that case ignore everything I said. In any case, my question/suggestion, even if invalid due to ignorance (i thought numArgs >= 1), was related to this PR, it was not a theoretical rambling.

**Comment by miguel-negrao** [comment]
I was playing a bit with the variadic macros for auto declaring and initializing the stack variables and I think I got it work. I suggest that SCLANG_DEFINE_PRIMITIVE could be changed to auto declare the stack variables. The syntax I propose is

```
SCLANG_DEFINE_PRIMITIVE( SFWrite, 2, a, b)

   //a and b available here as PyrSlot*
}
```
Note that there is no { after a,b) when calling the macro. Might seem a bit weird but didn't find a way around that.
I think something like the following could work:

```

#define SCLANG_PRIMITIVE_DEFINE_ARG_0(n, i, a)
#define SCLANG_PRIMITIVE_DEFINE_ARG_1(n, i, a) constexpr int m_ ##  a = i; PyrSlot *a = g->sp - m_ ##  a;
#define SCLANG_PRIMITIVE_DEFINE_ARG_2(n, i, a, ...) constexpr int m_ ##  a = i; PyrSlot *a = g->sp - m_ ##  a; SCLANG_PRIMITIVE_DEFINE_ARG_1(n, i-1, __VA_ARGS__)
#define SCLANG_PRIMITIVE_DEFINE_ARG_3(n, i, a, ...) constexpr int m_ ##  a = i; PyrSlot *a = g->sp - m_ ##  a; SCLANG_PRIMITIVE_DEFINE_ARG_2(n, i-1, __VA_ARGS__)
#define SCLANG_PRIMITIVE_DEFINE_ARG_4(n, i, a, ...) constexpr int m_ ##  a = i; PyrSlot *a = g->sp - m_ ##  a; SCLANG_PRIMITIVE_DEFINE_ARG_3(n, i-1, __VA_ARGS__)
#define SCLANG_PRIMITIVE_DEFINE_ARG_5(n, i, a, ...) constexpr int m_ ##  a = i; PyrSlot *a = g->sp - m_ ##  a; SCLANG_PRIMITIVE_DEFINE_ARG_4(n, i-1, __VA_ARGS__)
#define SCLANG_PRIMITIVE_DEFINE_ARG_6(n, i, a, ...) constexpr int m_ ##  a = i; PyrSlot *a = g->sp - m_ ##  a; SCLANG_PRIMITIVE_DEFINE_ARG_5(n, i-1, __VA_ARGS__)
#define SCLANG_PRIMITIVE_DEFINE_ARG_7(n, i, a, ...) constexpr int m_ ##  a = i; PyrSlot *a = g->sp - m_ ##  a; SCLANG_PRIMITIVE_DEFINE_ARG_6(n, i-1, __VA_ARGS__)
#define SCLANG_PRIMITIVE_DEFINE_ARG_8(n, i, a, ...) constexpr int m_ ##  a = i; PyrSlot *a = g->sp - m_ ##  a; SCLANG_PRIMITIVE_DEFINE_ARG_7(n, i-1, __VA_ARGS__)
#define SCLANG_PRIMITIVE_DEFINE_ARG_9(n, i, a, ...) constexpr int m_ ##  a = i; PyrSlot *a = g->sp - m_ ##  a; SCLANG_PRIMITIVE_DEFINE_ARG_8(n, i-1, __VA_ARGS__)
#define SCLANG_PRIMITIVE_DEFINE_ARG_10(n, i, a, ...) constexpr int m_ ##  a = i; PyrSlot *a = g->sp - m_ ##  a; SCLANG_PRIMITIVE_DEFINE_ARG_9(n, i-1,__VA_ARGS__)

// NUM_ARGS(...) evaluates to the literal number of the passed-in arguments.
#define _NUM_ARGS2(X,X64,X63,X62,X61,X60,X59,X58,X57,X56,X55,X54,X53,X52,X51,X50,X49,X48,X47,X46,X45,X44,X43,X42,X41,X40,X39,X38,X37,X36,X35,X34,X33,X32,X31,X30,X29,X28,X27,X26,X25,X24,X23,X22,X21,X20,X19,X18,X17,X16,X15,X14,X13,X12,X11,X10,X9,X8,X7,X6,X5,X4,X3,X2,X1,N,...) N
#define NUM_ARGS(...) _NUM_ARGS2(0 ,##__VA_ARGS__ ,64,63,62,61,60,59,58,57,56,55,54,53,52,51,50,49,48,47,46,45,44,43,42,41,40,39,38,37,36,35,34,33,32,31,30,29,28,27,26,25,24,23,22,21,20,19,18,17,16,15,14,13,12,11,10,9,8,7,6,5,4,3,2,1,0)

#define _SCLANG_PRIMITIVE_DEFINE_ARGS_3(N, ...) SCLANG_PRIMITIVE_DEFINE_ARG_ ## N(N,N-1, __VA_ARGS__)
#define _SCLANG_PRIMITIVE_DEFINE_ARGS_2(N, ...) _SCLANG_PRIMITIVE_DEFINE_ARGS_3(N, __VA_ARGS__)
#define SCLANG_PRIMITIVE_DEFINE_ARGS(...) _SCLANG_PRIMITIVE_DEFINE_ARGS_2(NUM_ARGS(__VA_ARGS__), __VA_ARGS__)

#define SCLANG_PRIMITIVE_SIGNATURE2( name, ...)                                                            \
    int SCLANG_PRIMITIVE_NAME( name ) ( struct VMGlobals *g, int numArgsPushed ) { \
    SCLANG_PRIMITIVE_DEFINE_ARGS(__VA_ARGS__)

#define SCLANG_DEFINE_PRIMITIVE_HELPER2( name, numArgs, varArgs, ...)                                      \
    SCLANG_PRIMITIVE_SIGNATURE( name );                                                               \
    SCLANG_REGISTRY_HELPER_DEFN( name, numArgs, varArgs );                                            \
    SCLANG_PRIMITIVE_SIGNATURE2( name, ##__VA_ARGS__)

#define SCLANG_DEFINE_PRIMITIVE2( name, numArgs, ...)                                                      \
    SCLANG_DEFINE_PRIMITIVE_HELPER2( name, numArgs, 0 , __VA_ARGS__)
```

This is based on code from https://stackoverflow.com/questions/824639/variadic-recursive-preprocessor-macros-is-it-possible
Only included code for up to 10 arguments, more could be added if needed.

When running the following

```
SCLANG_DEFINE_PRIMITIVE2( SFWrite, 2, a, b)

	SNDFILE *file = (SNDFILE*)slotRawPtr(&slotRawObject(a)->slots[0]);

	...

	return errNone;
}
```
 It compiles and using gcc -E to see after the preprocessor I get

```
int prSFWrite ( struct VMGlobals *g, int numArgsPushed ); static_assert( 2 >= 0, "sclang primitive must have a nonnegative number of arguments" ); static_assert( 0 == 0 || 0 == 1, "sclang primitive's varargs quality must be either 0 or 1" ); static detail::SC_PrimRegistryEntry<detail::SC_PrimDefinition> SFWrite_PrimDefinerEntry { { & prSFWrite, "_SFWrite", 2, 0 }, SC_PrimDefiner::instance() };; int prSFWrite ( struct VMGlobals *g, int numArgsPushed ) { constexpr int m_a = 2 -1; PyrSlot *a = g->sp - m_a; constexpr int m_b = 2 -1 -1; PyrSlot *b = g->sp - m_b;

 SNDFILE *file = (SNDFILE*)slotRawPtr(&slotRawObject(a)->slots[0]);
```

I think `##__VA_ARGS__` might not be available outside gcc though, that would have to be tested. It might be possible to have this work on gcc and msvs since the latter "will suppress a trailing comma if no arguments are passed to the ellipsis." https://docs.microsoft.com/pt-pt/cpp/preprocessor/variadic-macros. Or we could just make a different versions SCLANG_DEFINE_PRIMITIVE_WITH_ARGS and SCLANG_DEFINE_PRIMITIVE_WITHOUT_ARGS.

I didn't test the actual primitive, just checked that it compiled.

**Comment by brianlheim** [comment]
Cool! A couple of thoughts:

- I think Qtcollider is already doing something quite similar to this, you may want to look at how primitives are done there.
- A macro that hides an opening brace is a non-starter for me, as it will break auto-indent.
- You don't need to use constexpr like that; all compilers will optimize away constant ints
- tokens that begin with an underscore followed by a capital letter are reserved by the compiler - 
https://wiki.sei.cmu.edu/confluence/plugins/servlet/mobile?contentId=88046915#content/view/88046915
- You may want to talk to @scztt about his work on unpacking arguments and simultaneously type checking. It may be applicable to what you're doing.
- I really want to avoid scope creep on this PR. at the moment it already does quite a lot. I appreciate what you're suggesting, and I would be happy to continue discussing it, but it will not go into this PR. Plus, once this is through it will be much easier to programmatically refactor the primitives.

**Comment by miguel-negrao** [comment]
> I really want to avoid scope creep on this PR. at the moment it already does quite a lot. I appreciate what you're suggesting, and I would be happy to continue discussing it, but it will not go into this PR. Plus, once this is through it will be much easier to programmatically refactor the primitives.

Ok, we leave it for a later time. It will require changing all primitives again though, that was my main concern... Thanks for the feedback also, will check Qt primitives.

**Comment by brianlheim** [comment]
Closing until I have time to work on this again.

**Pull request closed without merging**
