### PR TITLE
build system: move fftlib header back into include/common

### LINKED ISSUE #1391: on linux, fftlib.h does not get installed
when compiling sc-plugins on my linux machine, I noticed that `fftlib.h` (in `common`) does not get installed when doing make install.
This header is needed at least for JoshPVUGens.

`make` in sc-plugins:

```
source/CMakeFiles/JoshPVUGens.dir/build.make:54: recipe for target 'source/CMakeFiles/JoshPVUGens.dir/JoshUGens/JoshPVUGens.cpp.o' failed
make[2]: *** [source/CMakeFiles/JoshPVUGens.dir/JoshUGens/JoshPVUGens.cpp.o] Error 1
CMakeFiles/Makefile2:1329: recipe for target 'source/CMakeFiles/JoshPVUGens.dir/all' failed
make[1]: *** [source/CMakeFiles/JoshPVUGens.dir/all] Error 2
```

### PR DESCRIPTION
**Pull request by gusano**
Fix #1391

### CODE REVIEW

**Comment by timblechmann** [comment]
this is not a public header, but a private one coming from green-fft. user code should utilise the fft interface provided by sc.

**Comment by danstowell** [comment]
I agree with @timblechmann. We don't really want sc3-plugins authors to depend on "gory internals", that's why we provided the fft interface.

The counter-argument would be if green lib provided functionality which ours doesn't AND if the sc3-plugins is using that extra functionality. Can anyone confirm? (Of course the best fix then would be to wrap that extra functionality up in our interface.)

**Comment by nuss** [comment]
Aren't the required headers part of the supercollider-dev package? (installable via apt-get on Ubuntu and the like). So, if one installs SC via package manager and then decides to compile the plugins from source she can install the required headers easily without downloading the whole SC sources, no?

**Comment by gusano** [comment]
Ok guys, thanks for the info, I'm gonna close this PR then.
We should ask to the non-building-plugins authors to update their code and meanwhile tell users to build sc3-plugins against a checkout of sc repo (or supercollider-dev package but I have no idea if @danstowell manually add files like *fftlib.h* when packaging..).

**Comment by danstowell** [comment]
@nuss @gusano thanks - see the list of files at for example https://packages.debian.org/jessie/i386/supercollider-dev/filelist

**Pull request closed without merging**
