### PR TITLE
fix closing TCP connections in sclang on recompile

### LINKED ISSUE #4482: TCP connection to the server is not properly closed when recompiling library
## Environment

* SuperCollider version: 3.10
* Operating system: macOS 10.13
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
// 1. check initial state
thisProcess.recompile;
"lsof -nP -iTCP:57110".unixCmd; //check who's listening on default scsynth's port 57110 on TCP
// should give no output message


// 2. boot scsynth on tcp
(
Server.scsynth;
s.options.protocol_(\tcp);
s.waitForBoot({
	"lsof -nP -iTCP:57110".unixCmd;
})
)
```
```
// output:
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
sclang  91167 marcin   88u  IPv4 0x25d72d5c1ddb305d      0t0  TCP 127.0.0.1:61168->127.0.0.1:57110 (ESTABLISHED)
scsynth 91200 marcin   12u  IPv4 0x25d72d5c1d4529bd      0t0  TCP *:57110 (LISTEN)
scsynth 91200 marcin   13u  IPv4 0x25d72d5c1e68005d      0t0  TCP 127.0.0.1:57110->127.0.0.1:61168 (ESTABLISHED)
```
```supercollider
// 3. recompile (without quitting server first)
thisProcess.recompile;
// then repeat step 2.
```
```
//output:
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
sclang  16145 marcin   71u  IPv4 0x25d72d5c1b0639bd      0t0  TCP 127.0.0.1:52912->127.0.0.1:57110 (CLOSE_WAIT)
sclang  16145 marcin   72u  IPv4 0x25d72d5c0b6c39bd      0t0  TCP 127.0.0.1:52977->127.0.0.1:57110 (ESTABLISHED)
scsynth 17366 marcin   13u  IPv4 0x25d72d5c310e49bd      0t0  TCP *:57110 (LISTEN)
scsynth 17366 marcin   20u  IPv4 0x25d72d5c3845831d      0t0  TCP 127.0.0.1:57110->127.0.0.1:52977 (ESTABLISHED)
scsynth 17366 marcin   71u  IPv4 0x25d72d5c1b0639bd      0t0  TCP 127.0.0.1:52912->127.0.0.1:57110 (CLOSE_WAIT)
```
```supercollider
// repeat 3. and 2.
```
```
COMMAND   PID   USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME
sclang  91167 marcin   88u  IPv4 0x25d72d5c1ddb305d      0t0  TCP 127.0.0.1:61168->127.0.0.1:57110 (CLOSE_WAIT)
sclang  91167 marcin   92u  IPv4 0x25d72d5c303bd5dd      0t0  TCP 127.0.0.1:61203->127.0.0.1:57110 (CLOSE_WAIT)
sclang  91167 marcin   93u  IPv4 0x25d72d5c1edbd31d      0t0  TCP 127.0.0.1:61243->127.0.0.1:57110 (ESTABLISHED)
scsynth 91278 marcin   12u  IPv4 0x25d72d5c1e6809bd      0t0  TCP *:57110 (LISTEN)
scsynth 91278 marcin   13u  IPv4 0x25d72d5c2194fc7d      0t0  TCP 127.0.0.1:57110->127.0.0.1:61243 (ESTABLISHED)
scsynth 91278 marcin   88u  IPv4 0x25d72d5c1ddb305d      0t0  TCP 127.0.0.1:61168->127.0.0.1:57110 (CLOSE_WAIT)
scsynth 91278 marcin   92u  IPv4 0x25d72d5c303bd5dd      0t0  TCP 127.0.0.1:61203->127.0.0.1:57110 (CLOSE_WAIT)
```
Moreover, supernova will not boot at all when there are dangling close_wait connections:
```supercollider
s.quit;
(
Server.supernova;
s.options.protocol_(\tcp);
s.waitForBoot({
	"lsof -nP -iTCP:57110".unixCmd;
})
)
```
However, the connection is properly closed when quitting the server without recompiling.
```supercollider
thisProcess.platform.killAll("sclang"); //clean previously opened connections
// afterwards manually boot interpreter

// 1. check who's listening
"lsof -nP -iTCP:57110".unixCmd;
// should give no output message


// 2. boot scsynth on tcp
(
Server.scsynth;
s.options.protocol_(\tcp);
s.waitForBoot({
	"lsof -nP -iTCP:57110".unixCmd;
})
)

// 3. quit the server
s.quit;

// 4. check open ports again
"lsof -nP -iTCP:57110".unixCmd;
// should give no output

```

## Expected vs. actual behavior

I think that TCP connections should be closed when recompiling the library. 
This was observed while reviewing #4435.

### PR DESCRIPTION
**Pull request by dyfer**
## Purpose and Motivation

Fixes #4482 
 
It turns out that we were [failing to store a list of TCP connections](https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Control/NetAddr.sc#L143) when the `disconnectHandler` was `nil`, which prevented the connection from being added to the `IdentityDictionary`.

My fix replaces `nil` for the `disconnectHandler` with an empty function `{}`. I'm not sure if there's a better object to use here and I'm open to suggestions.

In the process of debugging this, I temporarily exposed `NetAddr *connections`. ~~I think it would be beneficial to keep it available, so I added a getter to it (as well as an entry in the docs) in a separate commit. It this is not desirable here, I'm happy to take this out. On one hand, it would be useful to have this information, but on the other, the user should not make changes to this dictionary...~~ I kept this class method and added documentation, but modified it to return a copy of the original dictionary, so the original can't be modified.

## Types of changes

- Bug fix
- Documentation

## To-do list

- [x] Code is tested
~~- [ ] All tests are passing~~ there are no tests for this...
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
> On one hand, it would be useful to have this information, but on the other, the user should not make changes to this dictionary...

How about returning a copy instead then?

**Comment by dyfer** [comment]
> How about returning a copy instead then?

Great idea. I updated the PR and the class method now returns a copy of that dictionary.

**Comment by snappizz** [comment]
there's a new method in here but it's pretty minor. should this go into the 3.10 branch?

**Comment by dyfer** [comment]
I'd be happy to rebase.

**Comment by brianlheim** [comment]
i don't have a strong opinion on whether or not this goes into the next 3.10 release, but for now i am going to merge it into master. @snappizz @joshpar any thoughts?

**Pull request merged**
