### PR TITLE
improve SequenceableCollection flatten

### PR DESCRIPTION
**Pull request by telephon**
This improves performance of `flat` and `flatten` and provides a flatten from bottom for negative levels.

```
(
(-3..3).do { |i|
    i.postln;
    [[1], 2, [[3, 4], 5], [[[]]], [[[6]]], 7, 8, []].flatten(i).postln
}
)
```

returns

```
-3
[ [ 1 ], 2, [ [ 3, 4 ], 5 ], [ [ [  ] ] ], [ [ [ 6 ] ] ], 7, 8, [  ] ]
-2
[ 1, 2, [ 3, 4 ], 5, [ [  ] ], [ [ 6 ] ], 7, 8 ]
-1
[ 1, 2, 3, 4, 5, [  ], [ 6 ], 7, 8 ]
0
[ [ 1 ], 2, [ [ 3, 4 ], 5 ], [ [ [  ] ] ], [ [ [ 6 ] ] ], 7, 8, [  ] ]
1
[ 1, 2, [ 3, 4 ], 5, [ [  ] ], [ [ 6 ] ], 7, 8 ]
2
[ 1, 2, 3, 4, 5, [  ], [ 6 ], 7, 8 ]
3
[ 1, 2, 3, 4, 5, 6, 7, 8 ]
```

### CODE REVIEW

**Comment by adcxyz** [comment]
some questions regarding what flatten from below is intended to do, 
and some benchmarks:
```
a = [1, [2, 3, [4, 5, [6]]]];

a.flatten(0)
-> [ 1, [ 2, 3, [ 4, 5, [ 6 ] ] ] ]

a.flatten
-> [ 1, 2, 3, [ 4, 5, [ 6 ] ] ]

a.flatten(2)
-> [ 1, 2, 3, 4, 5, [ 6 ] ]

a.flatten(3)
-> [ 1, 2, 3, 4, 5, 6 ]

// how do negatives flatten from below?
// they produce the same as basic flattening: 
a.flatten(-1) // same as flatten(3)
a.flatten(-2) // same as flatten(2)
a.flatten(-3) // same as flatten(1)
a.flatten(-4) // unchanged like flatten(0)

// I would guess that "flattening from below" means something like
// flattening the deepest levels of nesting first. Like this:   
a.flatten(-1) 
would be -> [ 1, [ 2, 3, [ 4, 5, 6 ] ] ]
a.flatten(-2) 
would be -> [ 1, [ 2, 3, 4, 5, 6 ] ]
a.flatten(-3) // maxDepth reached, thus fully flat
would be -> [ 1, 2, 3, 4, 5, 6 ]


// Benchmarks: 
// flat has gotten a little faster
bench { 100000.do { a } };             // 0.0058 // just access
bench { 100000.do { a.flat } }; 	   // 0.97 was: 0.85

// new flatten is slower than previous: new ----  old
bench { 100000.do { a.flatten } };     // 0.24  was: 0.14
bench { 100000.do { a.flatten(2) } };  // 0.60  was: 0.30
bench { 100000.do { a.flatten(3) } };  // 0.88  was: 0.44


// negative flatten is slower again than positive:
bench { 100000.do { a.flatten(-1) } }; // 1.17    // 0.028 old, but that does nothing
bench { 100000.do { a.flatten(-2) } }; // 0.92
bench { 100000.do { a.flatten(-3) } }; // 0.60

**Comment by adcxyz** [comment]
@telephon 
here is a sketch for how I believe flatten from below should behave:
```
a = [1, [2, 3, [4, 5, [6]]]];

~flattenLowFirst = { |arr, level = -1|
	if (arr.isCollection) { 
		if (level < -1) { 
			arr.collect(~flattenLowFirst.(_, level + 1));
		} { 
			arr.prFlat;
		}
	} {
		arr
	}
};

~flattenLowFirst.(a, -1);
~flattenLowFirst.(a, -2);
~flattenLowFirst.(a, -3);
~flattenLowFirst.(a, -4);

// and benchmarks
bench { 100000.do { ~flattenLowFirst.(a, -1); } }; // 0.47
bench { 100000.do { ~flattenLowFirst.(a, -2); } }; // 0.63
bench { 100000.do { ~flattenLowFirst.(a, -3); } }; // 0.81
bench { 100000.do { ~flattenLowFirst.(a, -4); } }; // 0.99
```

**Comment by telephon** [comment]
good! do you have benchmarks for the positive values, too?

**Comment by telephon** [comment]
Closing this one, found an efficient working implementation of this idea, @adcxyz will open a new PR soon.

**Comment by telephon** [comment]
here: #2527

**Pull request closed without merging**
