### PR TITLE
sclang: use linenoise-ng instead of readline

### PR DESCRIPTION
**Pull request by llloret**
Linenoise-ng is a modern replacement for readline that works nicely on Windows (MSVC and mingw), Linux, Mac, etc. It is a close fork of linenoise (adding Windows support), which is in use in some big projects like Redis, MongoDB and Android.

The idea would be to stop using readline, and use linenoise-ng, so that we are able to use the same code base on all architectures and compilers.

This PR has been tested in Linux, Max, and Windows, both with MSVC 64 bits and mingw 32 bits. It adds 3 files, plus an external git submodule for the linenoise-ng lib, which gets compiled in-place.

Please see #2171, for a brief discussion about the topic.

While doing this I have tried to keep the architecture of SC_TerminalClient as close to the original as possible, but some changes were necessary, mostly because linenoise-ng does not have a key-by-key feed function, but works more like `readline()`.

The main advantages are:
- common codebase for all architectures (less #ifdefs, easier to maintain)
- Brings readline - like features to Windows
- more portable
- dependencies are in-tree (just 3 files), so easier to setup dev environments

Linenoise-ng has most of readline features, and then some more, like history, autocompletion, navigation keys, CTRL-R history search, etc.

Any comments / critique, etc are more than welcome. The PR is meant as a place to start the discussion about this.

### CODE REVIEW

**Comment by crucialfelix** [comment]
I support this.

**Comment by crucialfelix** [comment]
I'm still not sure if we should try to put this into 3.8 or 3.9

That is uh... 10 days away and we haven't even branched or gotten a beta ready.

On the one hand it fixes Windows and thus may reduce the overall work and worry.
On the other hand there might be issues we don't yet know about. A few of us (myself included) use sclang outside of the IDE. I should test this PR with supercolliderjs and see if it does affect anything.

**Comment by llloret** [comment]
It would be great if we can get some testing and feedback on this, that's
for sure.

**Comment by redFrik** [comment]
gave this a quick test-spin under raspbian (jessie-lite, rpi3) and it seems to work just fine.

**Comment by llloret** [comment]
thanks for giving it a try, redFrik!

It would be great if you could elaborate on what things did you do? I mean,
history, CTRL-R history search, ...? We would like to understand what
features people use, and which ones work (or not).
Luis

**Comment by redFrik** [comment]
some more info: i built sc with gcc 4.8, ctrl+r search works and history (up/down arrows i assume) works like before, the raspbian i tested is just debian linux so no surprises that everything is ok.

**Comment by crucialfelix** [comment]
Travis failure is this:

```
[ 43%] Building CXX object lang/CMakeFiles/libsclang.dir/__/external_libraries/linenoise-ng/src/linenoise.cpp.o
In file included from /usr/include/c++/4.9/bits/atomic_base.h:36:0,
                 from /usr/include/c++/4.9/atomic:41,
                 from /home/travis/build/supercollider/supercollider/external_libraries/linenoise-ng/src/linenoise.cpp:127:
/home/travis/build/supercollider/supercollider/external_libraries/linenoise-ng/src/linenoise.cpp:137:40: error: use of deleted function ‘std::atomic<bool>::atomic(const std::atomic<bool>&)’
 static std::atomic<bool> wantsToExit = false;
                                        ^
In file included from /home/travis/build/supercollider/supercollider/external_libraries/linenoise-ng/src/linenoise.cpp:127:0:
/usr/include/c++/4.9/atomic:491:7: note: declared here
       atomic(const atomic&) = delete;
       ^
make[2]: *** [lang/CMakeFiles/libsclang.dir/__/external_libraries/linenoise-ng/src/linenoise.cpp.o] Error 1
make[1]: *** [lang/CMakeFiles/libsclang.dir/all] Error 2
make: *** [all] Error 2
```

This PR is failing to build for me here:
```
The following build commands failed:
       	CompileC build/lang/SuperCollider.build/RelWithDebInfo/libsclang.build/Objects-normal/x86_64/linenoise.o external_libraries/linenoise-ng/src/linenoise.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

**Comment by vivid-synth** [comment]
Note there's also still discussion about this pull request happening at https://github.com/supercollider/supercollider/issues/2171

**Comment by llloret** [comment]
From what I see, this might still be too controversial to have in 3.8?

**Comment by crucialfelix** [comment]
It's definitely 3.9 and tagged with that Milestone

**Comment by llloret** [comment]
Ok, makes sense.

**Comment by bagong** [comment]
This PR is stale too, but should be easy to recover... Can we reach a consensus here? If this can get accepted, no need to look into readline for Windows-MinGW.

**Comment by vivid-synth** [comment]
I appreciate that this would be the simplest way to "just get the damn thing working" but the linenoise-ng situation is worse than when we discussed it 6 months ago: there hasn't been a single commit in their repo since then. (An outline of my concerns is here: https://github.com/supercollider/supercollider/issues/2171#issuecomment-239182225 )

I'd strongly prefer not to introduce such iffy code into our codebase.

As I mentioned in https://github.com/supercollider/supercollider/issues/2171 , there are other options for getting this working well on Windows that will probably much better long-term.

**Comment by bagong** [comment]
So rather than enforcing linenoise on everybody, this comes as an option now. It is used by default on Windows (in lack of a working alternative), and can be used on Mac and Linux by setting SC_LINENOISE=ON as build option. As long as this setting is not made, nothing changes on the other platforms, i.e. readline will be used if the libraries are found, no command-line functionality, if readline is not found. As is hard to avoid, the flexibility comes at the price of less transparent code...

This is tested on Windows (VS2015/MSYS2), Mac and Linux (Ubuntu-Studio 16.10)

I consider this done, but Luis and I will follow up on problems, of course. The most important thing needed is real world exposure now. I've been using this extensively when inspecting problems on Windows, and have never met a problem relatable to linenoise-ng and its sc-integration per se. Note also that this only does something if you are actually using the command line interface. I'll comment on the "quality"-question in the issue thread. I'll just say that Luis (@llloret) has made some of the best contributions to SC during the last months. Thanks a lot, Luis!

**Comment by llloret** [comment]
It would be great if people can give it a try and highlight issues.

Perhaps there have not been upstream changes to the git repository because they are not needed ;). The real measure of quality is real testing!

Thanks a lot, @bagong, for taking care of this.

**Comment by vivid-synth** [comment]
Fwiw, my concerns are with the linenoise-ng code. @llloret 's code here looks great.

**Comment by bagong** [comment]
Well, then make a case!! Otherwise the submitted code is to be considered part of @llloret contribution.

**Comment by vivid-synth** [comment]
Case is on https://github.com/supercollider/supercollider/issues/2171

**Comment by bagong** [comment]
A case would be a test that shows problems, or a code review that shows problems in the current code. I do not see that in your writeup!

**Comment by brianlheim** [comment]
I agree with @vivid-synth's assessment that linenoise-ng is iffy code, and that we should fully explore other libraries that are more reliable and portable. These options have already been stated, and it's a mystery to me as to why they have not been considered and also tested, because they seem like much more reliable alternatives.

I _strongly_ oppose any solution to this problem that adds build options, further fragments the codebase, and draws in redundant third party libraries. It only makes things more difficult to maintain in the future, and should not be considered a technique for reaching compromise.

**Comment by llloret** [comment]
Brian, it's not a big mystery... I'll explain: linenoise-ng was working
fine as far as I could see, and it would allow all platforms to share the
same code, which is something that I was pursuing when I stepped in (among
others) to try and save the Windows platform last year, which was falling
well behind the other platforms (I helped fix midi, hid, and some
problematic interfacing code for windows) And since it was working fine, I
didn't work more on it, since my time is quite limited lately.

I won't feel bad if the group decides to ditch it, but as of now, I won't
have time to work on a replacement.

Why do some people say its not good code. I don't remember all details, but
if I remember correctly, it seemed to me like it was linenoise with Windows
portability code. Perhaps someone can elaborate on that.

Hope this clarifies things, and let me know if you need more detail.
Luis

>

**Comment by brianlheim** [comment]
Thanks for the explanation @llloret! To summarize these [two](https://github.com/supercollider/supercollider/issues/2171#issuecomment-239182225) [comments](https://github.com/supercollider/supercollider/issues/2171#issuecomment-282462065) by @vivid-synth:
- development seems to have proceeded haphazardly
- it's not well-supported or widely used
- a lot of it has changed from the original linenoise
- because of that, we don't know if it's good or bad code

I understand a lot of work has already been done on this, but now that we have more people interested, I think it would be worth it to have another investigation into the other libraries that are out there. Here are some alternatives:

- https://github.com/yhirose/cpp-linenoise
- Fixing linenoise for MSVC
- http://mingweditline.sourceforge.net/

And I'll probably be giving them a try this week, because I of course want to see sclang's CLI working again on Windows ASAP. :)

**Comment by vivid-synth** [comment]
Another concern is that, because the file structure has been changed significantly, it's more difficult for it to get patches+fixes from upstream. So it can potentially end up as a sort of orphaned project.

**Comment by vivid-synth** [comment]
Thanks @brianlheim for offering to put some time in!! :muscle:

**Comment by snappizz** [comment]
are there any further plans to work on this PR?

**Comment by brianlheim** [comment]
This hasn't been updated since last year, so I'm closing it for now.

**Comment by dyfer** [comment]
#5712 brought Readline on Windows, so I'll remove the "postponed" label.

**Pull request closed without merging**
