### PR TITLE
example & help files: fix reference to default server 

### PR DESCRIPTION
**Pull request by miczac**
... and simplify server handling

### CODE REVIEW

**Comment by miczac** [comment]
I'm inclined to remove any s = Server.default and thelike statements from helpfiles, as long as it's not about the statement itself. The vast majority simply uses s.boot or s.waitForBoot to get a/the server running, if anyway.

**Comment by crucialfelix** [comment]
agreed, most everybody boots with the button or a key command anyway. they are in the IDE or they know what they are doing.

**Comment by crucialfelix** [comment]
thanks for doing these fixes !

**Comment by telephon** [comment]
yes, very much agreed. There are many files which still have ```s.boot``` in the code, however. Some of those may be justified according to the above, some not ...

```
/Classes/BAllPass.schelp /Classes/BBandPass.schelp /Classes/BBandStop.schelp /Classes/BHiPass.schelp /Classes/BHiPass4.schelp /Classes/BHiShelf.schelp /Classes/BLowPass.schelp /Classes/BLowPass4.schelp /Classes/BLowShelf.schelp /Classes/BPeakEQ.schelp /Classes/Recorder.schelp /Classes/Server.schelp /Classes/BusPlug.schelp /Tutorials/Getting-Started/03-Start-Your-Engines.schelp /Tutorials/Getting-Started/10-SynthDefs-and-Synths.schelp /Guides/Debugging-tips.schelp /Classes/Env.schelp /Classes/HID.schelp /Classes/LIDSlot.schelp /Classes/PV_BrickWall.schelp /Classes/PV_RandComb.schelp /Classes/ScopeView.schelp /Classes/Buffer.schelp /Classes/MIDIIn.schelp /Classes/OSCdef.schelp /Classes/OSCFunc.schelp /Classes/DiskOut.schelp /Classes/EventPatternProxy.schelp /Classes/Fdef.schelp /Guides/How-to-Use-the-Interpreter.schelp /Tutorials/JITLib/jitlib_basic_concepts_01.schelp /Tutorials/JITLib/jitlib_basic_concepts_02.schelp /Tutorials/JITLib/jitlib_basic_concepts_03.schelp /Tutorials/JITLib/jitlib_basic_concepts_04.schelp /Tutorials/JITLib/jitlib_efficiency.schelp /Tutorials/JITLib/jitlib_fading.schelp /Tutorials/JITLib/jitlib_networking.schelp /Other/JITLibChanges3.7.schelp /Classes/Monitor.schelp /Classes/MonitorGui.schelp /Classes/Ndef.schelp /Classes/NdefGui.schelp /Classes/NdefMixer.schelp /Classes/NodeMap.schelp /Classes/NodeProxy.schelp /Classes/NodeProxyEditor.schelp /Classes/Pattern.schelp /Classes/PatternProxy.schelp /Classes/Pbindef.schelp /Classes/PbindProxy.schelp /Classes/Pdef.schelp /Classes/Pdefn.schelp /Reference/plot.schelp /Classes/Pnsym.schelp /Classes/ProxyMixer.schelp /Classes/ProxyMonitorGui.schelp /Tutorials/JITLib/proxyspace_examples.schelp /Classes/ProxySpace.schelp /Classes/Psym.schelp /Classes/Stethoscope.schelp /Classes/SynthDesc.schelp /Classes/TaskProxy.schelp /Classes/Tdef.schelp /Guides/Working_with_HID.schelp /Tutorials/Mark_Polishook_tutorial/05_The_network.schelp /Tutorials/Getting-Started/13-Buffers.schelp /Classes/AbstractServerAction.schelp /Classes/Archive.schelp /Classes/Array.schelp /Reference/asTarget.schelp /Tutorials/JITLib/audio_rate_mapping.schelp /Guides/Bundled-Messages.schelp /Classes/Bus.schelp /Guides/ClientVsServer.schelp /Classes/Clip.schelp /Classes/DebugNodeWatcher.schelp /Reference/default_group.schelp /Classes/DiskIn.schelp /Classes/DynKlank.schelp /Classes/Environment.schelp /Classes/EZRanger.schelp /Classes/FFTTrigger.schelp /Classes/Fold.schelp /Classes/Free.schelp /Classes/FreeSelfWhenDone.schelp /Classes/FreeVerb.schelp /Classes/FreeVerb2.schelp /Classes/FreqScopeView.schelp /Classes/Gate.schelp /Classes/GrainBuf.schelp /Classes/GrainFM.schelp /Classes/GrainIn.schelp /Classes/GrainSin.schelp /Classes/Group.schelp /Classes/GVerb.schelp /Classes/Hilbert.schelp /Classes/HilbertFIR.schelp /Classes/History.schelp /Classes/In.schelp /Classes/InRange.schelp /Classes/KeyState.schelp /Classes/LFGauss.schelp /Classes/Mix.schelp /Classes/MoogFF.schelp /Classes/MulAdd.schelp /Guides/Multichannel-Expansion.schelp /Classes/MultiTap.schelp /Classes/Node.schelp /Classes/Onsets.schelp /Guides/Order-of-execution.schelp /Classes/OSCBundle.schelp /Classes/OSCpathResponder.schelp /Classes/OSCresponderNode.schelp /Classes/PanAz.schelp /Classes/Pause.schelp /Classes/PeakFollower.schelp /Tutorials/A-Practical-Guide/PG_02_Basic_Vocabulary.schelp /Classes/PlayBuf.schelp /Reference/playN.schelp /Classes/Pluck.schelp /Classes/Poll.schelp /Classes/ProxyMixerOld.schelp /Classes/PV_Add.schelp /Classes/PV_BinScramble.schelp /Classes/PV_BinShift.schelp /Classes/PV_BinWipe.schelp /Classes/PV_ChainUGen.schelp /Classes/PV_Conj.schelp /Classes/PV_CopyPhase.schelp /Classes/PV_LocalMax.schelp /Classes/PV_MagAbove.schelp /Classes/PV_MagBelow.schelp /Classes/PV_MagClip.schelp /Classes/PV_MagDiv.schelp /Classes/PV_MagFreeze.schelp /Classes/PV_MagMul.schelp /Classes/PV_MagNoise.schelp /Classes/PV_MagShift.schelp /Classes/PV_MagSmear.schelp /Classes/PV_MagSquared.schelp /Classes/PV_Max.schelp /Classes/PV_Min.schelp /Classes/PV_Mul.schelp /Classes/PV_PhaseShift.schelp /Classes/PV_PhaseShift90.schelp /Classes/PV_PhaseShift270.schelp /Classes/PV_RandWipe.schelp /Classes/PV_RectComb2.schelp /Classes/Pwalk.schelp /Classes/QuartzComposerView.schelp /Classes/Ramp.schelp /Classes/RecNodeProxy.schelp /Tutorials/JITLib/recursive_phrasing.schelp /Classes/Scale.schelp /Classes/SCEnvelopeEdit.schelp /Classes/Schmidt.schelp /Classes/Score.schelp /Classes/SendTrig.schelp /Guides/ServerTiming.schelp /Classes/Shaper.schelp /Classes/SharedIn.schelp /Classes/SharedOut.schelp /Guides/Spawning.schelp /Classes/SpecCentroid.schelp /Classes/Stepper.schelp /Classes/StreamClutch.schelp /Guides/Sync-Async.schelp /Classes/Synth.schelp /Classes/SynthDef.schelp /Guides/SynthDefsVsSynths.schelp /Classes/TabletView.schelp /Classes/TDuty.schelp /Classes/TGrains.schelp /Tutorials/JITLib/the_lazy_proxy.schelp /Guides/Tour_of_UGens.schelp /Tutorials/Tutorial.schelp /Classes/UGen.schelp /Guides/UGens-and-Synths.schelp /Classes/Unpack1FFT.schelp /Classes/UnpackFFT.schelp /Guides/UsingMIDI.schelp /Classes/Warp1.schelp /Classes/Wrap.schelp /Classes/ZeroCrossing.schelp
```

**Comment by miczac** [comment]
ok, this is getting twofold:
I did a simple grep over the source tree for boot and server.default.

I am currently removing constructs like 
 var s = Server.default;    (  I like this one, from an example � )
 s = Server.default; 
 s = Server.default.boot;
 s = Server.default; // just to be sure
 Server.default = Server.internal; s = Server.default;
etc.,
but leave simple s.boot or s.waitForBoot untouched.
Should I remove _any_ boot statement as long as it's not about the server or such?

On 20.Nov 2015, at 19:47 , Chris Sattinger <notifications@github.com> wrote:

> agreed, most everybody boots with the button or a key command anyway. they are in the IDE or they know what they are doing.

**Comment by telephon** [comment]
I'd say the former is the best (keep ```s.boot``` etc., because those may have practical reasons to be there).

**Comment by miczac** [comment]
not sure if I'd want to touch such contructs: 
Server.default.boot.doWhenBooted {
....
}
i.e. replacing with a profane s.boot or s.waitForBoot if you like.
Would that be overdoing it?

**Comment by telephon** [comment]
Well, it is more the question how much time you want to invest in it. Certainly, ```s.waitForBoot``` would be an improvement (unless the help file tries to demonstrate doWhenBooted).

simplifying helpfiles is definitely a good thing, because they should serve as templates for solving problems.

**Comment by jamshark70** [comment]
For the help examples involving Stethoscope, have you tested whether they work with `s` if you have assigned `s` to a different server, such as `s = Server.internal`?

I am not sure if the Stethoscope bugs related to server selection were ever fixed.

**Comment by miczac** [comment]
On 21.Nov 2015, at 1:01 , jamshark70 <notifications@github.com> wrote:

> I am not sure if the Stethoscope bugs related to server selection were ever fixed.

I'm using .scope and the like quite frequently and enjoy the use of the local/default server w/o needing the internal server.
So AFAICT it's ok.
What kind of bug are you referring to?

**Comment by miczac** [comment]
ah, ok - I think I can see your point:
If it's s which is re-assigned, Stethoscope claims localhost is not running.
But how's that connected to the help files? Because re-assigning s is exactly what they do.
So they work with Server.local, which won't be the case if s = Server.internal.
Or do I miss something?

> For the help examples involving Stethoscope, have you tested whether they work with s if you have assigned s to a different server, such as s = Server.internal?

**Comment by jamshark70** [comment]
Stethoscope used to fail if you tried to use it with a non-default server because there was logic hardcoded into it to ignore the receiver of `scope` -- e.g.:

```
// assuming 's' is the local server:

Server.internal.boot;
Server.internal.scope;

a = { SinOsc.ar(440, 0, 0.1) ! 2 }.play(target: Server.internal);
a.free;
```

In the past, `Server.internal.scope` would use the default server anyway.

This morning, however, the above works fine and I can't find a way to break it. So I have to assume it was fixed. No problem, then.

**Comment by miczac** [comment]
there you go: https://github.com/supercollider/supercollider/pull/1728

**Pull request merged**
