### PR TITLE
class library: make sure the event server is set when played

### LINKED ISSUE #3231: Pmono(Artic) broken on current 3.9
Pmono and PmonoArtic are broken in current 3.9. A recent PR seems to have broken things 6c56b0167312cc759c9ab62cd4b242bf7dbd2143 @adcxyz could you please have a look? 

### Error Message
```
ERROR: Message 'defaultGroup' not understood.
RECEIVER:
   nil
ARGS:

PROTECTED CALL STACK:
	Meta_MethodError:new	0x3dc0600
		arg this = DoesNotUnderstandError
		arg what = nil
		arg receiver = nil
	Meta_DoesNotUnderstandError:new	0x3dc25c0
		arg this = DoesNotUnderstandError
		arg receiver = nil
		arg selector = defaultGroup
		arg args = [  ]
	Object:doesNotUnderstand	0x1fe38c0
		arg this = nil
		arg selector = defaultGroup
		arg args = nil
	a FunctionDef	0x5146800
		sourceCode = "{ ~server.defaultGroup.nodeID }"
	a FunctionDef	0x5164100
		sourceCode = "#{ |server|
						var bndl, id, ids, addAction, f;
						addAction = Node.actionNumberFor(~addAction);
						~freq = ~detunedFreq.value;
						f = ~freq;
						~amp = ~amp.value;

						bndl = ( [9 /* \\s_new */, ~instrument, ids, addAction, ~group.asControlInput]
							++ ~msgFunc.valueEnvir).flop;
						bndl.do { | b |
							id = server.nextNodeID;
							ids = ids.add(id);
							b[2] = id;
						};
						~id = ids;

						if ((addAction == 0) || (addAction == 3)) {
							bndl = bndl.r...etc..."
		arg server = localhost
		var bndl = nil
		var id = nil
		var ids = nil
		var addAction = 0
		var f = 261.6255653006
	a FunctionDef	0x5152c40
		sourceCode = "#{
					var tempo, server, eventTypes, parentType;

					parentType = ~parentTypes[~type];
					parentType !? { currentEnvironment.parent = parentType };

					~finish.value(currentEnvironment);

					server = ~server ? Server.default;

					tempo = ~tempo;
					tempo !? { thisThread.clock.tempo = tempo };


					if(currentEnvironment.isRest.not) {
						eventTypes = ~eventTypes;
						(eventTypes[~type] ?? { eventTypes[\\note] }).value(server)
					};

					~callback.value(currentEnvironmen...etc..."
		var tempo = nil
		var server = localhost
		var eventTypes = ( 'fadeBus': a Function, 'freeAllocWrite': a Function, 'tree': a Function, 'on': a Function, 
  'load': a Function, 'freeBuffer': a Function, 'group': a Function, 'freeAllocRead': a Function, 'allocWrite': a Function, 
  'cue': a Function, 'grain': a Function, 'Synth': a Function, 'freeAllocWriteID': a Function, 'rest': a Function, 
  'alloc': a Function, 'sine2': a Function, 'sine1': a Function, 'midi': a Function, 'set': a Function, 
  'setProperties': a Function, 'parGroup': a Function, 'allocRead': a Fu...etc...
		var parentType = nil
	a FunctionDef	0x5105700
		sourceCode = "<an open Function>"
	Function:prTry	0x37bbe40
		arg this = a Function
		var result = nil
		var thread = a Routine
		var next = nil
		var wasInProtectedFunc = false
	
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Routine>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Function:protect
		arg this = <instance of Function>
		arg handler = <instance of Function>
		var result = <instance of DoesNotUnderstandError>
	Environment:use
		arg this = <instance of Event>
		arg function = <instance of Function>
		var result = nil
		var saveEnvir = <instance of Environment>
	Event:play
		arg this = <instance of Event>
	Event:playAndDelta
		arg this = <instance of Event>
		arg cleanup = <instance of EventStreamCleanup>
		arg mute = false
	EventStreamPlayer:prNext
		arg this = <instance of EventStreamPlayer>
		arg inTime = 8.846657349
		var nextTime = nil
		var outEvent = <instance of Event>
	< FunctionDef in Method EventStreamPlayer:init >
		arg inTime = 8.846657349
	Routine:prStart
		arg this = <instance of Routine>
		arg inval = 8.846657349
^^ The preceding error dump is for ERROR: Message 'defaultGroup' not understood.
RECEIVER: nil
```

### PR DESCRIPTION
**Pull request by telephon**
This should fix  #3231.

### CODE REVIEW

**Comment by patrickdupuis** [comment]
This PR was created against `master` and should be against `3.9`. I think this is a simple fix from within Github.

**Comment by telephon** [comment]
changed the base, that's where those other commits come from. Now points to 3.9

**Comment by patrickdupuis** [comment]
Hmmm... There must be a way to avoid having those commits added to this PR. Maybe you can rebase your branch on 3.9? (i'm not a git pro, sorry)

I don't mean to be annoying. I just want to test you PR to confirm that it fixes the Pmono issue which is a 3.9 branch issue.

**Comment by telephon** [comment]
see #3235

**Pull request closed without merging**
