### PR TITLE
Topic/source preview

### PR DESCRIPTION
**Pull request by scztt**
This PR adds a window at the bottom of the "Look Up Implementations" and "Look Up References" windows, that shows a preview of the source code for the currently selected item. The majority of the time, look-up functionality is used for reference purposes - this allows quick reference to the source of the method in question, without requiring actually opening the file in the IDE.

### CODE REVIEW

**Comment by timblechmann** [comment]
nice!

four points:
* i'd vote for hiding the preview view when there is no selection
* the tab sequence should toggle between input and result view. this is currently broken, as one cannot use tab to move out of the source preview
* related to the former: the source preview should not get the keyboard focus at all, as it is impossible to move the keyboard focus back to input or result view.
* it should go in master, not in qt52

**Comment by scztt** [comment]
- I will try hiding the preview w/ no selection, and see how it looks. My only concern is a large UI element appearing / disappearing is visually distracting and discontinuous - as far as I can tell, the only way to have no selection is when you have brought up the window but have not yet searched for anything? In that case, I think it should be okay.

- I'll fix not being able to tab out of the preview pane, should be easy. I disagree about not being able to focus at all - I've found switching focus to the preview very useful in practice, to enable selecting/copying code, and navigation via keyboard.

- The pull request is to qt52 because it has 6+ months of testing on that branch. If we can validate on the mainline, it's fine to PR there instead / also - the testing impact on master versus qt52 is pretty minimal.

**Comment by timblechmann** [comment]
>   * I will try hiding the preview w/ no selection, and see how it looks.
>     My only concern is a large UI element appearing / disappearing is
>     visually distracting and discontinuous - as far as I can tell, the
>     only way to have no selection is when you have brought up the window
>     but have not yet searched for anything? In that case, I think it
>     should be okay.

there is also the following use case:
* search for something -> found result
* search for something else -> no result

on the failed search, the source preview is currently not updated, but
keeps the old result. so we either want to hide it or clear it.

the visual distraction is a good point, but otoh an empty source preview
just takes screen space. but maybe one can use an animation when
showing/hiding the source preview. what do you think?

>   *
> 
>     I'll fix not being able to tab out of the preview pane, should be
>     easy. I disagree about not being able to focus at all - I've found
>     switching focus to the preview very useful in practice, to enable
>     selecting/copying code, and navigation via keyboard.

then we need to decide on two things:
* how to move the keyboard focus to the source preview? if 'enter' opens
it in a new editor, maybe 'shift+enter'?
* how to move the keyboard focus back to the input widget? maybe
'escape' could be used for this? this also works for moving the focus
from the post window to the editor windows.

>   *
> 
>     The pull request is to qt52 because it has 6+ months of testing on
>     that branch. If we can validate on the mainline, it's fine to PR
>     there instead / also - the testing impact on master versus qt52 is
>     pretty minimal.

afaict, there are not qt5 specifics in there, no?

**Comment by telephon** [comment]
(side remark: currently there seems to be no way to search for a combination of class and method. Typing ````Bus: play```` doesn't give results)

**Pull request closed without merging**
