### PR TITLE
help: add higher resolution raster logos

### PR DESCRIPTION
**Pull request by snappizz**
inkscape has trouble opening the SVG logo (GIMP and browsers handle it fine, so i don't know what's wrong), so it's probably worthwhile to save some people's time with nice high-res images.

### CODE REVIEW

**Comment by brianlheim** [comment]
aren't there parts of the repo that refer to specifically to icons in this folder? should those files be updated?

**Comment by brianlheim** [comment]
a quick grep for the 16x16 version shows usage in multiple places

**Comment by snappizz** [comment]
i wrote in the commit message:  "The SVG logo is sliiiightly different from the original (in particular the shadow is a bit lighter), but I don't think anyone cares."

**Comment by brianlheim** [comment]
ok, so these are just files lying around in case someone wants a 1024px version of the logo for something else?

**Comment by snappizz** [comment]
yeah. maybe that's a silly idea? idk

**Comment by brianlheim** [comment]
idk, it's not a big deal to me either way.

**Comment by brianlheim** [comment]
Is this still relevant with #3060 merged?

**Comment by snappizz** [comment]
i think it's fine

**Comment by brianlheim** [comment]
ok! i'm still 50/50 on whether to merge this, feel free to diy if you see there being a good use for it.

**Pull request merged**
