### PR TITLE
Merge 3.11 into develop

### PR DESCRIPTION
**Pull request by brianlheim**
## Purpose and Motivation

regular git-flow merge of 3.11 into develop

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
i'm not sure why the diff looks so big here. i merged it locally to test and the diff is only from #4883 and #5219, +160/-114. i guess github is not recognizing that these commits are also on develop

**Comment by dyfer** [comment]
I don't understand why the diff is shown like this here.
I tried to merge 3.11 into develop locally, uploaded to a new branch, and that one does show +160/-114 diff: https://github.com/supercollider/supercollider/pull/5228

**Comment by brianlheim** [comment]
@dyfer ok! mind approving this then?

**Review by dyfer — APPROVED** [review]
Let's see what happens! ;)
Thanks!

**Pull request merged**
