### PR TITLE
Update README_LINUX.md

### PR DESCRIPTION
**Pull request by novadeviator**
Changed the url to Debian Multimedia team.

## Types of changes

- Documentation
- Bug fix
- New feature
- Breaking change

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
Thanks! Please rebase this against 3.10 -- see our [contributor's guide](https://github.com/supercollider/supercollider/blob/develop/CONTRIBUTING.md#notes-on-rebasing-and-merge-conflicts) for more information.

**Comment by novadeviator** [comment]
Can I rebase this commit (i have already deleted my patch/branch from my profile) or must I pull the 3.10 branch and make the edit again? If I can rebase the commit itself, I'm not sure I know how. In other case, should I pull devel branch, make an edit, commit, rebase into 3.10 and then force push? Apologies for my cluelessness.

**Comment by novadeviator** [comment]
ok i was spending couple of hours trying to follow instruction on contributor's guide,making fork, cloneing to my local machine, creating branch and then failing at rebasing to 3.10. and now I see this was resolved by someone? what just happened? confused, but I don't want to take too much time from devs.

**Comment by snappizz** [comment]
sorry about the confusion! SC development is based on the [git-flow](https://nvie.com/posts/a-successful-git-branching-model/) model, where development takes place mainly on two branches: we merge changes into the `3.10` branch if it's a bug fix or something nonintrusive to be released in the next 3.10.x version, and we merge new features and breaking changes into `develop` to be released in 3.11.

if you make a new PR against develop when it's really a bug fix that should go against 3.10, we have two different strategies:

1. have the author rebase it against 3.10
2. let it be merged into develop, and then someone will cherry-pick it onto the 3.10 branch

there's been a little disagreement on whether we should go with 1 (which puts responsibility on the PR author to do a tricky git operation) or with 2 (which puts responsibility on maintainers, and we're currently grinding through a backlog of 50+ PRs). brian prefers requesting the PR author, while i'm pro-cherrypick, and i suggested to patrick to do the merge. sorry you got caught in the crossfire here.

**Comment by novadeviator** [comment]
that's alright. thanks for all the explanation.

I do actually want to learn more git (and perhaps contribute more) so i followed instructions:

* fork on github
* clone my fork `git clone --recursive https://github.com/novadeviator/supercollider.git`
* create topic branch with `git checkout -b topic/fix-linux_readme develop`
* make edits
* commit `git commit -a`
* trying to rebase with `git rebase -i --onto 3.10 develop topic/fix-linux_readme`

where I got stuck with error:
```
fatal: Needed a single revision
Does not point to a valid commit: 3.10
```

does that mean I don't have 3.10 branch? or I did something wrong elsewhere?

**Comment by snappizz** [comment]
yes, that'd be because you don't have the 3.10 branch. `git fetch origin 3.10` should do it.

**Pull request merged**
