### PR TITLE
fixing bug with helpir method (updating path)

### PR DESCRIPTION
**Pull request by tiagmoraismorgado**

### CODE REVIEW

**Comment by tiagmoraismorgado** [comment]
this fixes the issue many people may have when they try to load supercollider quartz composer view examples

**Comment by brianlheim** [comment]
this PR needs more information. @tiagmoraismorgado what problem are you trying to solve and how does this solve it?

**Comment by tiagmoraismorgado** [comment]
i am trying to solve the problem described here:

https://github.com/supercollider/supercollider/issues/3111

**thanks for the insights on the problem. i already figured out where the problem is.** 

**the problem is on the way as the Platform.helpDir method is set which returns** 

- _/Volumes/DATA/data/Nova pasta com elementos/SuperCollider/SuperCollider.app/Contents/Resources/Help/QC/Cells.qtz,_ 

**where what should be returned is** 

- _"/Volumes/DATA/data/Nova pasta com elementos/SuperCollider/SuperCollider.app/Contents/Resources/HelpSource/QC/Cells.qtz"_ 

**so i guess i know what is wrong with the whole thing. the help folder name has been updated from help to help source, and the same didn't happen with the Platform.helpDir which is still returning help.** 

**as a matter of fact, the way as all the examples are written returns something wrong. it should return  _HelpSource/QC/Cells.qtz_ and it is returning _Help/QC/Cells.qtz_ and as a matter of fact the quartz composer patches don't load**

**Comment by brianlheim** [comment]
@tiagmoraismorgado please stop bolding your entire comments. it is distracting and unnecessary. other contributors have asked this of you multiple times.

it sounds like the example code is what's broken. I would recommend fixing the example code rather than changing a line in `Platform`, which looks like it is used for much more than this example code. you don't know what behavior elsewhere in the codebase you might be breaking by changing this.

two alternatives to use in the example code might be:

```supercollider
// instead of: Platform.helpDir +/+ "QC/file.qtz"
SCDoc.helpTargetDir +/+ "QC/file.qtz"
Platform.userAppSupportDir +/+ "Help/QC/file.qtz"
```

feel free to make those changes in a new PR. i don't think we can accept this because whether it works in this case or not, it is too risky a change to modify a central class like `Platform` without knowing what you're doing.

**Comment by tiagmoraismorgado** [comment]
well i may remake the whole thing according to your specifications. but the method still needs to be updated

**Pull request closed without merging**
