### PR TITLE
Windows build system

### PR DESCRIPTION
**Pull request by bagong**
This basically does three things:

- switches to using embedded portaudio only (by adding the portaudio to the beginning of the compile all audio api's can be built now)
- allow to run/debug executable targets without installing
- reduce the risk of wrong library finds both in the beginning (find-modules) and at the end (fixup-bundle)

The readme-Windows is adjusted and contains quite a few enhancements and corrections of errors. Thanks to Joach and Kos for testing and discussing!

### CODE REVIEW

**Comment by crucialfelix** [comment]
Awesome. I'll leave this for a day to let somebody who knows cmake well to also have a glance. I checked it through a bit too.

portaudio is a submodule now, right ?

**Comment by bagong** [comment]
Yes, portaudio is a submodule. It already was since that previous build system related commit, but in this version it is obligatory for Windows. Keeping the options of both building portaudio as part of the SC build or providing libraries compiled outside of SC made subsequent code a lot more complicated and intransparent. Since the audio APIs provided now are the same than you would get from a portaudio build outside of SC I thought this was the preferable way.

To come back to the question of where that submodule/pa-fork should reside: I'd actually prefer to see it in the SC repo, not because of any burden it creates while it's in my repo, but because if people wanted to commit to the fork, they'd have to go through my repo. That would make me kind of a gate-keeper of portaudio on SC, something I'd prefer not to be...

**Comment by crucialfelix** [comment]
okay, let's fork from yours into the supercollider org.

**Comment by bagong** [comment]
Great! Should I do it, or will you? It's not urgent, of course...

**Pull request merged**
