### PR TITLE
speedup flatten, add flattenBelow, flattenLowestFirst, flatten2

### PR DESCRIPTION
**Pull request by telephon**

### CODE REVIEW

**Comment by snappizz** [comment]
Speeding up flatten is good, but I'm not convinced of the necessity of these new methods. Have people been requesting them?

**Comment by telephon** [comment]
I originally wanted this function because what it does is relatively hard, error prone, and you effectively don't do it unless you have a method for this. I first made a sketch simply extending `flatten` by negative arguments. But this is an API change, and I think adding these methods doesn't hurt, @adcxyz 's implementation makes more sense in a way.

Well implemented methods for complicated list transformations are a good thing. Most of the methods that are commonly found indispensable now were added because a developer saw that they make sense.

**Comment by adcxyz** [comment]
I liked Julians idea of a symmetry for flatten from above/below, and aimed to implement as clearly as possible. I can imagine cases where it is interesting to play with array transforms with them. 

The symmetric method is flatten2 for clarity (as in say clip2, fold2) andavoids the API change.
flattenBelow is a simple semi-symmetry to flatten the outer levels first, and where one need not know the array's maxDepth.
flattenLowestFirst does the exact lower half of the symmetry separately, so one can use it with a direct name too - that could do a better name if you can think of one. 

Building flatten2 from flatten and flattenLowestFirst avoids code duplication.

**Comment by adcxyz** [comment]
oh, and with the new maxDepth primitive, flattenLowestFirst and flatten2 should also be quite fast.

**Comment by snappizz** [comment]
Okay, that's a good enough reason for me. Now that I think of it, the class library has a lot of weird array methods like "sputter" and "curdle" and "pyramidg," so this doesn't seem too out of league. Still, it's important to justify any new additions.

**Comment by brianlheim** [comment]
This is an awesome idea, and something that I've wanted implemented before! Here's my two cents.

I think `flattenBelow` and `flattenLowestFirst` are too close to duplication. If a program needs to operate agnostically of the maximum depth, a call to `maxDepth` is not very expensive. However, if we were to add `flattenBelow`, I think it would be more conceptually accurate to implement it with ```if (numLevels <= 1) { ^this.flat };```, so that it extrapolates as it crosses 0 much like `flatten` appears to do.

Not sure about the clarity of the name `flatten2`. `clip2` and `fold2` (and `rand2`) work by taking a value and operating in the range [-value, value], so I would expect `flatten2` to flatten the same number of dimensions from both above and below. Also not convinced of its reasons for being included here: flattening from above and from below don't seem like operations that would naturally be conceptually paired, the method itself is just a simple sign-switching statement, and SequenceableCollection already has 300+ methods.

**Comment by telephon** [comment]
`flattenBelow { |numLevels = 1|`

“flattenBelow” implies “below a certain level”: so shouldn’t “numLevels” be really “level” ?
Then level = 0 would mean flat.

I see that it might be a useful thing to have zero as a special case, but the method is harder to understand this way.

`flattenLowestFirst`

An alternative name may be: `flattenUp` or `flattenUpward`

@brianlheim thank you for your comments! flattenBelow and flattenLowestFirst are inverses from each other almost. But indeed it is thinkable to have a single message for both.

Re: `flatten2`: I really like the symmetry:

```
a = [1, 2, [3, 4, [5, 6, [7, 8, [9, 0]]]]];
a.flatten2(4);  // [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 ]
a.flatten2(3);  // [ 1, 2, 3, 4, 5, 6, 7, 8, [ 9, 0 ] ]
a.flatten2(2);  // [ 1, 2, 3, 4, 5, 6, [ 7, 8, [ 9, 0 ] ] ]
a.flatten2(1);  // [ 1, 2, 3, 4, [ 5, 6, [ 7, 8, [ 9, 0 ] ] ] ]
a.flatten2(0);  // [ 1, 2, [ 3, 4, [ 5, 6, [ 7, 8, [ 9, 0 ] ] ] ] ]
a.flatten2(-1); // [ 1, 2, [ 3, 4, [ 5, 6, [ 7, 8, 9, 0 ] ] ] ]
a.flatten2(-2); // [ 1, 2, [ 3, 4, [ 5, 6, 7, 8, 9, 0 ] ] ]
a.flatten2(-3); // [ 1, 2, [ 3, 4, 5, 6, 7, 8, 9, 0 ] ]
a.flatten2(-4); // [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 0 ]
```

Its analogy is `keep` and `drop`. It it weren't for the API change (well not a really bad one, but it could produce problems) I'd just use `flatten`. The `2` in `clip2` 

>SequenceableCollection already has 300+ methods.

Yes, but that is entirely OK for such a central class, IMO. But I'd be happy if we can all pack it into a single method! 

Btw. all those messages could go into `Collection` because they do not presuppose order.

**Comment by brianlheim** [comment]
Thanks for the response @telephon!

> flattenBelow and flattenLowestFirst are inverses from each other almost.

Maybe I'm misunderstanding, but couldn't the call `a.flattenLowestFirst(n)` be expressed as `a.flattenBelow(a.maxDepth-n)`? They're not inverses, just differing implementations of the same idea.

> Re: flatten2: I really like the symmetry

But we could make plenty of methods symmetrical, right? I would like to see an argument as to why this particular symmetry is useful.

> Its analogy is keep and drop

Yeah, that makes more sense to me.

> Yes, but that is entirely OK for such a central class, IMO. But I'd be happy if we can all pack it into a single method!

Yeah, I would like to see this all become one `flatten` method in the future!

> Btw. all those messages could go into Collection because they do not presuppose order.

Agree, in fact `flatten` and `flat` could go there as well. Would it be an issue to make that change now?

**Comment by adcxyz** [comment]
dear @brianlheim and @telephon,
here is a synthesis of your suggestions:
We merge flattenBelow and flattenLowestFirst into flatBelow;
by default level is counting from the top, 
or if fromBottom is true, level is from bottom.

a = [1, [2, [3, [4, [5]]]]];
~flatBelow = { |arr, level = 1, fromBottom = false|
	if (fromBottom) { level = arr.maxDepth - level - 1 };
	if (arr.isCollection) { 
		if (level > 0) { 
			arr.collect { |el| ~flatBelow.(el, level - 1) } 
		} { 
			arr.flat
		} 
	} { arr };
};

~flatBelow.(a, 0); -> [ 1, 2, 3, 4, 5 ]
~flatBelow.(a, 1); -> [ 1, [ 2, 3, 4, 5 ] ]
~flatBelow.(a, 2); -> [ 1, [ 2, [ 3, 4, 5 ] ] ]
~flatBelow.(a, 3); -> [ 1, [ 2, [ 3, [ 4, 5 ] ] ] ]
~flatBelow.(a, 8); -> [ 1, [ 2, [ 3, [ 4, [ 5 ] ] ] ] ]

~flatBelow.(a, 0, true); [ 1, [ 2, [ 3, [ 4, [ 5 ] ] ] ] ]
~flatBelow.(a, 1, true); [ 1, [ 2, [ 3, [ 4, 5 ] ] ] ]
~flatBelow.(a, 2, true); [ 1, [ 2, [ 3, 4, 5 ] ] ]
~flatBelow.(a, 3, true); [ 1, [ 2, 3, 4, 5 ] ]
~flatBelow.(a, 8, true); [ 1, 2, 3, 4, 5 ]

and flatten2 (if that is the best name) switches between 
flatten for positives and flatBelow for negatives. 

yes?

**Comment by brianlheim** [comment]
@adcxyz Thanks for the suggestion! I would much prefer two separate methods over this. Using boolean flags to change behavior is only likely to lead to confusion and code maintenance problems in the future: http://softwareengineering.stackexchange.com/questions/147977/is-it-wrong-to-use-a-boolean-parameter-to-determine-behavior

Again, don't really see the need for a flag or a second method when using just one version and `.maxDepth-n` for the other case accomplishes the same thing.

**Comment by adcxyz** [comment]
ok, so flatBelow and flatten2 it is. 
will do asap.

**Comment by adcxyz** [comment]
done with f8cb24d.
```
a = [1, [2, [3, [4, [5]]]]];

a.flatBelow(0); // -> [ 1, 2, 3, 4, 5 ]
a.flatBelow( 1); // -> [ 1, [ 2, 3, 4, 5 ] ]
a.flatBelow( 2); // -> [ 1, [ 2, [ 3, 4, 5 ] ] ]
a.flatBelow( 3); // -> [ 1, [ 2, [ 3, [ 4, 5 ] ] ] ]
a.flatBelow( 8); // -> [ 1, [ 2, [ 3, [ 4, [ 5 ] ] ] ] ]

(-5..5).do { |level| ("l:" + level + a.flatten2(level)).postln }

l: -5 [ 1, 2, 3, 4, 5 ]
l: -4 [ 1, 2, 3, 4, 5 ]
l: -3 [ 1, [ 2, 3, 4, 5 ] ]
l: -2 [ 1, [ 2, [ 3, 4, 5 ] ] ]
l: -1 [ 1, [ 2, [ 3, [ 4, 5 ] ] ] ]
l: 0 [ 1, [ 2, [ 3, [ 4, [ 5 ] ] ] ] ]
l: 1 [ 1, 2, [ 3, [ 4, [ 5 ] ] ] ]
l: 2 [ 1, 2, 3, [ 4, [ 5 ] ] ]
l: 3 [ 1, 2, 3, 4, [ 5 ] ]
l: 4 [ 1, 2, 3, 4, 5 ]
l: 5 [ 1, 2, 3, 4, 5 ]
```

**Comment by telephon** [comment]
… the helpfiles

**Comment by brianlheim** [comment]
Ok, cool! Why the name change from flattenBelow to flatBelow? I thought this method was supposed to complement flatten?

**Comment by telephon** [comment]
my guess: @adcxyz chose it because it is analogous to `flat` in this respect: it doesn't take one more parameter to tell it when to stop flattening (well it could, I suppose?).

**Comment by telephon** [comment]
@adcxyz uups, I just saw there is still a call to `flattenLowestFirst` in `flatten2` left over.

**Comment by brianlheim** [comment]
@telephon I don't understand, sorry. `flat` removes all multidimensionality from the SeqColl and takes no arguments. `flatten` and `flatBelow` both take a `numLevels` parameter; am I missing something with parallelism here?

**Comment by telephon** [comment]
@brianlheim well, I read it as follows: `flatBelow` indeed removes all multidimensionality, but below a certain level.  

By contrast, `flatten` removes multidimensionality *down to* a certain level. For `flattenBelow`, I'd tend to expect a second parameter that lets us specify how many levels to "flatten" below the given level.

**Comment by brianlheim** [comment]
Oh!! I get it now, thanks for the explanation.

**Comment by telephon** [comment]
thanks for your comments – these things are a little hard to get clear indeed!

**Comment by adcxyz** [comment]
copypaste error fixed, added one more example, 
good to go for me.

**Comment by telephon** [comment]
sorry, that was accidental.

**Pull request merged**
