### PR TITLE
Do not allocate all channels reported by Pa_GetDeviceInfo / use memcpy instead of for-loop

### PR DESCRIPTION
**Pull request by hzulla**
On Linux, SuperCollider's PortAudio driver talks to ALSA (or to PulseAudio using PulseAudio's ALSA compatibility layer).

By default, the current audio driver will use the `default` audio device and [allocate *all* channels](https://github.com/supercollider/supercollider/blob/c017920b29d3fb76b230c14411c46be39b04e9f3/server/scsynth/SC_PortAudio.cpp#L418) reported back by `Pa_GetDeviceInfo()`.

On pure ALSA, the `default` device reports 128 in/out channels.
On PulseAudio, it reports 32 in/out channels.

It isn't necessary to allocate all channels, the application only needs to request the number of channels it actually uses. I didn't find a good explanation for why PortAudio reports these many virtual channels, but [this mailing list thread](http://music.columbia.edu/pipermail/portaudio/2014-February/015820.html) basically boils down to "don't worry, it's an artefact of the ALSA API and you're fine with simply allocating the number of channels you need and not more".

So that's what this patch does.

Also, both src and dst are float, so we can use memcpy/memset.

I tested this on XUbuntu 15.10 and there was no change in behaviour compared to the current git version. (Both the current git version and my patched version do not work with pure ALSA, but do work with PulseAudio. I will file a separate issue #1944 for debugging that.)

This will require testing. @sonoro1234 - could you please have a look?

### CODE REVIEW

**Comment by sonoro1234** [comment]
I have had a look and it seems good to me. In fact it is less confusing than original implementation.
I have not been able to test it.

**Comment by hzulla** [comment]
Thank you. Is it correct that you are using PortAudio on Windows? I'd be grateful if you could test my patch there.

**Comment by sonoro1234** [comment]
sorry for my ignorance: how can this be done?

**Comment by bagong** [comment]
The Windows build is in a bit unfortunate state on masters right now. It is waiting for changes in 3.7 to be merged. But once merged we will find that it currently breaks in two positions, depending on whether you are using VS or MinGW. I've documented the build breaks here:

VS:
https://gist.github.com/bagong/d94fecbef0170c9a3ad21aeb56fba3ba

MingW:
https://gist.github.com/bagong/0084f016cb80e61e0949c0f5b0f130a6

**Comment by sonoro1234** [comment]
but I only need scsynth to test that, and it can be built with 4.8.2 or 4.9.2.

my problem is with testing some patch?!

**Comment by sonoro1234** [comment]
@bagong  as for the 4.9.2 problem i posted that to gcc and they told it was related to mingw. then I sent email to mingw list where they ask me to try 4.9.3. I told them the problem is stil present in 4.9.3 but got NO ANSWER!!!!!!!!!!!!!!!!!!! :-(

**Comment by bagong** [comment]
I've tried 4.9.3 and 5.3, same error. Don't you think the "internal processor error" might be triggered by a preceding problem that has to do with how boost deals with system time? (just speculating, out of my expertise ;) )

As to git: You mean how to try out a PR? If yes, there are various methods. I personally prefer pulling PRs like remote branches and then merging them locally on a dedicated branch. You need to add a line to your .git/config for that, something like:

    	fetch = +refs/pull/*/head:refs/remotes/origin/pr/*

Resulting in:

`````
[remote "origin"]
	url = https://github.com/supercollider/supercollider.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	fetch = +refs/pull/*/head:refs/remotes/origin/pr/*
`````

My "origin" is set to the sc-github repo, not to my fork...

**Comment by bagong** [comment]
@sonoro1234 the changes in the "new" Windows build system are quite deep. Among others it will compile a bundled, latest PA as part of the SC build. Your old build system might still work on master right now, but once the changes from 3.7 get committed to master (still time to prevent it ;) ) you will have to change it. I hope you are fine with that. Maybe you want to have a look at 3.7? I can guide you via Gitter or so, if you are interested...

**Comment by sonoro1234** [comment]
well, I have just built master and I had to add -DPA_LIBRARY_TYPE="STATIC" to cmake but everything went fine.

**Comment by bagong** [comment]
Yes, but I assume you were still using your self built PA libraries. That option will not be accounted for in the newer version of the SCWin build system changes. It turned out to be pretty complicated to enable both embedded PA and keep the option of using self built PA libraries (out of the box), so I removed that option. Maybe you want to have a look if the PA-libs compiled with SC are fine for you? I've had three people check it out, but among the SC oldhands it looks like you are the only one to be affected by the change. Maybe check out on it?

**Comment by sonoro1234** [comment]
I have read in README_WINDOWS.md that embedded PA
```
Yet at the time of this writing the only sound-api supported by
this embedded build is WMME. If you need Asio support, or any of the other APIs
supported by Portaudio (DSound, WDM-KS, WASAPI), it needs to be built separately.
```
so please dont remove option of using self built PA libraries. If PORTAUDIO_LIBRARIES is defined just skip building embeded PA

**Comment by bagong** [comment]
Well, this needs a bit of negotiating/discussion. In the new build system the embedded build will allow to add ASIO and DSOUND if you add the SDKs. After I saw that could it could be done after all, I decided to avoid the considerable complications and intransparencies, if both build options were kept. This change also means that we'll all be talking of the same PA in SCWin if we have a problem with it. And we can patch a shared PA. The embedded PA repo is still in my Github repo, but that's going to change soon (provided everything goes as I anticipate).
The PA part is quite different in the Readme on the 3.7 branch, maybe have a look there ;) ?
Agreement possible? ;)

**Comment by hzulla** [comment]
You can check out this pull request on your machine and build it locally.

https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by sonoro1234** [comment]
@bagong if ASIO can be added that's ok for me

**Comment by bagong** [comment]
Great! Thanks!

**Comment by sonoro1234** [comment]
@hzulla I cant use that because cant follow that
```
At the bottom of the pull request, click command line. Follow the sequence of steps to bring down the proposed pull request. 
```
may be because I dont have write acces to repo?
What perhaps can be done is to create a patch, attach it to any message and then I can apply the patch?

**Comment by sonoro1234** [comment]
well, it seems that i can generate this patch as documented in https://coderwall.com/p/6aw72a/creating-patch-from-github-pull-request

**Comment by sonoro1234** [comment]
@hzulla OK I have applied this PR formated as a patch to master, compiled and run without any problem

**Comment by hzulla** [comment]
Thank you for your patience.

**Comment by crucialfelix** [comment]
Install the hub extension for git.
Then it's just

git checkout https://github.com/URL/of/pullrequest

Easiest way by far.

**Comment by bagong** [comment]
I also see no problem for Windows

**Comment by sonoro1234** [comment]
@crucialfelix I think it is not linux only but general portaudio. 
Also it is quite old!!

**Comment by bagong** [comment]
@crucialfelix , the "classical" Linux users are not interested in portaudio... I doubt you'll get more feedback. Maybe @hzulla could say a final word, I think his plans have changed a bit...

**Comment by hzulla** [comment]
I'm not sure by now if PortAudio on Linux is the solution to my problem on Linux, but still consider this patch here a minor bug fix and improvement to the code.

**Comment by bagong** [comment]
So with @sonoro1234 , let's have it at least for Windows. Thanks to the Sonic Pi Team!

**Pull request merged**
