### PR TITLE
Novacollider/freelist updates

### PR DESCRIPTION
**Pull request by timblechmann**
72e1532 is the second part of the fix for #1635

### CODE REVIEW

**Comment by miczac** [comment]
Hi, is there anything in these commits which requires XCode 6.1 minimum?

**Comment by timblechmann** [comment]
possibly. apple had fixed their atomic implementation about 2 years ago, so ancient appleclang versions may still have that bug.
there is always the possibility to use gcc ...

**Comment by telephon** [comment]
The question is now: normally we've supported 10.8, but I wonder if any of those who test the patches have still 10.8. I don't so this problem escaped me.

**Comment by timblechmann** [comment]
it is perfectly possible to compile with a new xcode for older osx versions.

http://www.cmake.org/cmake/help/v3.0/variable/CMAKE_OSX_DEPLOYMENT_TARGET.html

**Comment by telephon** [comment]
Ah good - thanks for this clue, I wasn't sure about this.

**Comment by miczac** [comment]
@timblechman, yup - but/and that implies having a more current system at hands for compiling. 
So for the time being my machine is out of the game of building and testing a current master frequently.  *)
(and DLing the binaries is not an option)
*) not a complaint!

**Comment by timblechmann** [comment]
@miczac `brew install gcc` ... gcc is still a better compiler than xcode's clang or msvc

**Comment by miczac** [comment]
Tim, thanks - you mentioned that above. I'll have to look at this ... 'd prefer gcc anyway.

**Comment by miczac** [comment]
well, I'm getting errors using gcc:

$ cmake -DCMAKE_PREFIX_PATH=`brew --prefix qt5` -DSUPERNOVA=OFF  .. && cmake --build . --target install --config RelWithDebInfo && cd ..
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/g++
-- Check for working CXX compiler: /usr/local/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SuperCollider Version: 3.7alpha1
-- Building from branch master, commit hash is 046af8e
-- Build type defaulting to "RelWithDebInfo"
-- Compiling with Qt GUI
-- Found Pthreads: /usr/lib/libpthread.dylib  
-- building boost libraries manually
-- using bundled libyaml-cpp
CMake Warning (dev) at external_libraries/hidapi/CMakeLists.txt:3 (project):
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.

The following variable(s) would be set to empty:

  PROJECT_VERSION
  PROJECT_VERSION_MAJOR
  PROJECT_VERSION_MINOR
  PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

hidapi cmakelists
===mac cmakelists===
===hidapi_parser cmakelists===
-- Audio API: coreaudio
-- Found a homebrew install of readline /usr/local/opt/readline
-- Found GNU Readline version 6.3: /usr/local/opt/readline/lib/libreadline.dylib
Qt: /usr/local/opt/qt5/lib/QtCore.framework/QtCore
-- Compiling with Readline support
-- Building the Qt IDE
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mz/dev/sc3.git/master/build
Scanning dependencies of target tlsf
[  0%] Building C object external_libraries/CMakeFiles/tlsf.dir/TLSF-2.4.6/src/tlsf.c.o
[  0%] Linking C static library libtlsf.a
[  0%] Built target tlsf
Scanning dependencies of target yaml


. . . skip


[ 25%] Building CXX object editors/sc-ide/CMakeFiles/SuperCollider.dir/__/__/common/SC_DirUtils.cpp.o
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:123:0,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.cpp:28:
/System/Library/Frameworks/Foundation.framework/Headers/NSTask.h:69:24: error: expected unqualified-id before '^' token
@property (copy) void (^terminationHandler)(NSTask *) NS_AVAILABLE(10_7, NA);
                      ^
/System/Library/Frameworks/Foundation.framework/Headers/NSTask.h:69:24: error: expected ')' before ^' token
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:159:0,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.cpp:28:
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:36:15: error: expected unqualified-id before '^' token
typedef void (^NSUserScriptTaskCompletionHandler)(NSError *error);
             ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:36:15: error: expected '' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:37:39: error: 'NSUserScriptTaskCompletionHandler' does not name a type
- (void)executeWithCompletionHandler:(NSUserScriptTaskCompletionHandler)handler;
                                     ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:53:15: error: expected unqualified-id before '^' token
typedef void (^NSUserUnixTaskCompletionHandler)(NSError *error);
             ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:53:15: error: expected '' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:54:70: error: 'NSUserUnixTaskCompletionHandler' does not name a type
- (void)executeWithArguments:(NSArray *)arguments completionHandler:(NSUserUnixTaskCompletionHandler)handler;
                                                                    ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:68:15: error: expected unqualified-id before '^' token
typedef void (^NSUserAppleScriptTaskCompletionHandler)(NSAppleEventDescriptor *result, NSError *error);
             ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:68:15: error: expected '' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:69:82: error: 'NSUserAppleScriptTaskCompletionHandler' does not name a type
- (void)executeWithAppleEvent:(NSAppleEventDescriptor *)event completionHandler:(NSUserAppleScriptTaskCompletionHandler)handler;
                                                                                ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:86:15: error: expected unqualified-id before '^' token
typedef void (^NSUserAutomatorTaskCompletionHandler)(id result, NSError *error);
             ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:86:15: error: expected '' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:87:72: error: 'NSUserAutomatorTaskCompletionHandler' does not name a type
- (void)executeWithInput:(id <NSSecureCoding>)input completionHandler:(NSUserAutomatorTaskCompletionHandler)handler;
                                                                      ^
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:160:0,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.cpp:28:
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:46:11: error: expected unqualified-id before '^' token
   void (^_interruptionHandler)();
         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:46:11: error: expected ')' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:46:11: error: expected ';' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:47:11: error: expected unqualified-id before '^' token
   void (^_invalidationHandler)();
         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:47:11: error: expected ')' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:47:11: error: expected ';' before '^' token
In file included from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/bind/mem_fn.hpp:25:0,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/mem_fn.hpp:22,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/function/detail/prologue.hpp:18,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/function.hpp:24,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string/detail/find_iterator.hpp:18,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string/find_iterator.hpp:24,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string/iter_find.hpp:27,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string/split.hpp:16,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string.hpp:23,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.h:37,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.cpp:45:
/Users/mz/dev/sc3.git/master/external_libraries/boost/boost/get_pointer.hpp:27:40: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
template<class T> T * get_pointer(std::auto_ptr<T> const& p)
                                      ^
In file included from /usr/local/Cellar/gcc/5.2.0/include/c++/5.2.0/bits/locale_conv.h:41:0,
               from /usr/local/Cellar/gcc/5.2.0/include/c++/5.2.0/locale:43,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string/classification.hpp:15,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string/trim.hpp:23,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string.hpp:19,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.h:37,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.cpp:45:
/usr/local/Cellar/gcc/5.2.0/include/c++/5.2.0/bits/unique_ptr.h:49:28: note: declared here
 template<typename> class auto_ptr;
                          ^
make[2]: *** [editors/sc-ide/CMakeFiles/SuperCollider.dir/__/__/common/SC_DirUtils.cpp.o] Error 1
make[1]: *** [editors/sc-ide/CMakeFiles/SuperCollider.dir/all] Error 2
make: *** [all] Error 2

**Comment by miczac** [comment]
something got mixed up: compiling with gcc (XCode is ok)  I'm getting an error:
`$ cmake -DCMAKE_PREFIX_PATH=`brew --prefix qt5` -DSUPERNOVA=OFF  .. && cmake --build . --target install --config RelWithDebInfo && cd ..
-- The C compiler identification is GNU 5.2.0
-- The CXX compiler identification is GNU 5.2.0
-- Checking whether C compiler has -isysroot
-- Checking whether C compiler has -isysroot - yes
-- Checking whether C compiler supports OSX deployment target flag
-- Checking whether C compiler supports OSX deployment target flag - yes
-- Check for working C compiler: /usr/local/bin/gcc
-- Check for working C compiler: /usr/local/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking whether CXX compiler has -isysroot
-- Checking whether CXX compiler has -isysroot - yes
-- Checking whether CXX compiler supports OSX deployment target flag
-- Checking whether CXX compiler supports OSX deployment target flag - yes
-- Check for working CXX compiler: /usr/local/bin/g++
-- Check for working CXX compiler: /usr/local/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SuperCollider Version: 3.7alpha1
-- Building from branch master, commit hash is 046af8e
-- Build type defaulting to "RelWithDebInfo"
-- Compiling with Qt GUI
-- Found Pthreads: /usr/lib/libpthread.dylib  
-- building boost libraries manually
-- using bundled libyaml-cpp
CMake Warning (dev) at external_libraries/hidapi/CMakeLists.txt:3 (project):
Policy CMP0048 is not set: project() command manages VERSION variables.
Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
command to set the policy and suppress this warning.

The following variable(s) would be set to empty:

  PROJECT_VERSION
  PROJECT_VERSION_MAJOR
  PROJECT_VERSION_MINOR
  PROJECT_VERSION_PATCH
This warning is for project developers.  Use -Wno-dev to suppress it.

hidapi cmakelists
===mac cmakelists===
===hidapi_parser cmakelists===
-- Audio API: coreaudio
-- Found a homebrew install of readline /usr/local/opt/readline
-- Found GNU Readline version 6.3: /usr/local/opt/readline/lib/libreadline.dylib
Qt: /usr/local/opt/qt5/lib/QtCore.framework/QtCore
-- Compiling with Readline support
-- Building the Qt IDE
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/mz/dev/sc3.git/master/build
Scanning dependencies of target tlsf
[  0%] Building C object external_libraries/CMakeFiles/tlsf.dir/TLSF-2.4.6/src/tlsf.c.o
[  0%] Linking C static library libtlsf.a
[  0%] Built target tlsf
Scanning dependencies of target yaml


. . . skip


[ 25%] Building CXX object editors/sc-ide/CMakeFiles/SuperCollider.dir/__/__/common/SC_DirUtils.cpp.o
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:123:0,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.cpp:28:
/System/Library/Frameworks/Foundation.framework/Headers/NSTask.h:69:24: error: expected unqualified-id before '^' token
@property (copy) void (^terminationHandler)(NSTask *) NS_AVAILABLE(10_7, NA);
                      ^
/System/Library/Frameworks/Foundation.framework/Headers/NSTask.h:69:24: error: expected ')' before ^' token
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:159:0,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.cpp:28:
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:36:15: error: expected unqualified-id before '^' token
typedef void (^NSUserScriptTaskCompletionHandler)(NSError *error);
             ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:36:15: error: expected '' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:37:39: error: 'NSUserScriptTaskCompletionHandler' does not name a type
- (void)executeWithCompletionHandler:(NSUserScriptTaskCompletionHandler)handler;
                                     ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:53:15: error: expected unqualified-id before '^' token
typedef void (^NSUserUnixTaskCompletionHandler)(NSError *error);
             ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:53:15: error: expected '' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:54:70: error: 'NSUserUnixTaskCompletionHandler' does not name a type
- (void)executeWithArguments:(NSArray *)arguments completionHandler:(NSUserUnixTaskCompletionHandler)handler;
                                                                    ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:68:15: error: expected unqualified-id before '^' token
typedef void (^NSUserAppleScriptTaskCompletionHandler)(NSAppleEventDescriptor *result, NSError *error);
             ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:68:15: error: expected '' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:69:82: error: 'NSUserAppleScriptTaskCompletionHandler' does not name a type
- (void)executeWithAppleEvent:(NSAppleEventDescriptor *)event completionHandler:(NSUserAppleScriptTaskCompletionHandler)handler;
                                                                                ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:86:15: error: expected unqualified-id before '^' token
typedef void (^NSUserAutomatorTaskCompletionHandler)(id result, NSError *error);
             ^
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:86:15: error: expected '' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSUserScriptTask.h:87:72: error: 'NSUserAutomatorTaskCompletionHandler' does not name a type
- (void)executeWithInput:(id <NSSecureCoding>)input completionHandler:(NSUserAutomatorTaskCompletionHandler)handler;
                                                                      ^
In file included from /System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:160:0,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.cpp:28:
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:46:11: error: expected unqualified-id before '^' token
   void (^_interruptionHandler)();
         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:46:11: error: expected ')' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:46:11: error: expected ';' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:47:11: error: expected unqualified-id before '^' token
   void (^_invalidationHandler)();
         ^
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:47:11: error: expected ')' before '^' token
/System/Library/Frameworks/Foundation.framework/Headers/NSXPCConnection.h:47:11: error: expected ';' before '^' token
In file included from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/bind/mem_fn.hpp:25:0,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/mem_fn.hpp:22,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/function/detail/prologue.hpp:18,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/function.hpp:24,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string/detail/find_iterator.hpp:18,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string/find_iterator.hpp:24,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string/iter_find.hpp:27,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string/split.hpp:16,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string.hpp:23,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.h:37,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.cpp:45:
/Users/mz/dev/sc3.git/master/external_libraries/boost/boost/get_pointer.hpp:27:40: warning: 'template<class> class std::auto_ptr' is deprecated [-Wdeprecated-declarations]
template<class T> T * get_pointer(std::auto_ptr<T> const& p)
                                      ^
In file included from /usr/local/Cellar/gcc/5.2.0/include/c++/5.2.0/bits/locale_conv.h:41:0,
               from /usr/local/Cellar/gcc/5.2.0/include/c++/5.2.0/locale:43,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string/classification.hpp:15,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string/trim.hpp:23,
               from /Users/mz/dev/sc3.git/master/external_libraries/boost/boost/algorithm/string.hpp:19,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.h:37,
               from /Users/mz/dev/sc3.git/master/common/SC_DirUtils.cpp:45:
/usr/local/Cellar/gcc/5.2.0/include/c++/5.2.0/bits/unique_ptr.h:49:28: note: declared here
 template<typename> class auto_ptr;
                          ^
make[2]: *** [editors/sc-ide/CMakeFiles/SuperCollider.dir/__/__/common/SC_DirUtils.cpp.o] Error 1
make[1]: *** [editors/sc-ide/CMakeFiles/SuperCollider.dir/all] Error 2
make: *** [all] Error 2
`

**Comment by timblechmann** [comment]
you might want to check, if the files are actually compiled as obj-c(++)

**Comment by miczac** [comment]
@martingasser kindly helped me out with this:
Libs like Foundation and NSTask use Apple's Blocks-Extension which is not supported by gcc.
So, apparently clang only on OS X.

**Comment by crucialfelix** [comment]
based on discussion on the list:

@miczac is accidentally compiling the IDE using gcc, which I don't think does obj-c in any reliable way.

you could maybe compile only the novacollider target using gcc, the rest using clang

**Comment by miczac** [comment]
@crucialfelix in hindsight I think that's what @timblechmann actually suggested above, I just didn't realise that back then. (sorry @martingasser ! )
Anyway, it's  beyond my current abilities to get that sorted cleanly.
However, it has some influence on the release of 3.7b since novacollider won't compile as described in the current version of README_OS_X.md according to https://github.com/supercollider/supercollider/pull/1791 .

**Pull request merged**
