### PR TITLE
[rebase] UnitTest: run add class info to post, remove debug posts

### PR DESCRIPTION
**Pull request by brianlheim**
@adcxyz is the original author of this PR

## Purpose and Motivation

Rebase of #3939, see discussion there for more details.

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
i took the liberty of rewriting this once since the previous PR changed a lot of formatting/spacing that wasn't necessary (@muellmusik maybe that's what you were seeing? those differences are in the original commits). someone should probably review it again.

**Comment by adcxyz** [comment]
Hi @brianlheim, 
thanks for the rebase - yes there were extraneous things in my UnitTest.sc file commits, 
and some still seem unnecessary, possibly even reverting later changes to Unit test - 
looking at them now, will write back ASAP. 

reading the code, I had an idea for making "reporting" more useful: 
ATM, ```report: true``` means post details, ```report: false``` means don't . 
It seems the best default for this would be: 
report full details only when test fails, e.g. for assertEquals, 
and when all is well, dont report, thus minimizing clutter. 
this could be done by defining ```report: nil``` to mean exactly that,
and making that the default in all assertX methods: 
```
//	assert { | boolean, message, report = true, onFailure, details |
	assert { | boolean, message, report, onFailure, details |
		report = report ? boolean.not;
		if(boolean.not) { 
			this.failed(currentMethod, message, report, details);
...
// 	assertEquals { |a, b, message = "", report = true, onFailure |
 	assertEquals { |a, b, message = "", report, onFailure |
etc 
```
makes sense?

**Comment by adcxyz** [comment]
argh, this PR still seems to revert stuff by accident - sorry! 
takes some more hunting down - hope I get to it later today

**Comment by adcxyz** [comment]
OK, checked, mostly this is obsolete, except:
1. getting rid of the unnecessary debug posts!
1a. some testsuite classes also post inline warnings due to var declarations;
I propose getting rid of those as well, in the same new PR 

2. new aspect: 
- making report more flexible with an option to report on fail only
I guess best to put this in a new PR?

best a

**Comment by telephon** [comment]
>I guess best to put this in a new PR?

I think so - thank you!

**Comment by brianlheim** [comment]
@adcxyz after your PRs, is this one still necessary?

**Comment by adcxyz** [comment]
> @adcxyz after your PRs, is this one still necessary?

no it isnt, so closing it now. 
thanks!

**Pull request closed without merging**
