### PR TITLE
Travis & gh pages feature

### PR DESCRIPTION
**Pull request by brianlheim**

### CODE REVIEW

**Comment by brianlheim** [comment]
Meant to do this on my own repo, sry.

**Comment by snappizz** [comment]
very nice idea!

**Comment by brianlheim** [comment]
yah i'm doing a lot of travis stuff for another project and realized it wouldn't be too hard to get this set up. generated docs should appear here for this dry run attempt: https://brianlheim.github.io/supercollider/

**Comment by crucialfelix** [comment]
That will be good. Bring more scrutiny and understanding to the cpp code

**Comment by brianlheim** [comment]
tada https://brianlheim.github.io/supercollider/

**Comment by crucialfelix** [comment]
Awesome !

That theme looks a bit old with that fake rounded plastic thing IMO.

Here's one that smells like Apple:

http://milik.cz/~jan/cppapp/docs/classcppapp_1_1_app_base.html
https://github.com/nnen/doxygen-theme

There are many out there of course.

I will also have to check out what is happening with the revisions to the
help files styling. That was in need of a freshner.

**Comment by brianlheim** [comment]
Thx, also been looking at Moxygen (https://sourcey.com/libsourcey/). The purpose of this exercise was just to see if I could get the pipeline up.

**Comment by brianlheim** [comment]
tried all this out tonight. Seems like Doxygen moved to js-based menus in 1.8.13 and that broke a lot of these tools. Moxygen doesn't work very well out of the box and that theme above didn't work well for me. The 'metro' version looks pretty weird IMO with the mix of fonts and font sizes. a bootstrap integration looked hopeful (https://github.com/Velron/doxygen-bootstrapped) but it's got issues, there's a fork (https://github.com/cellcortex/doxygen-bootstrapped) but this doesn't seem very reliable overall

**Pull request closed without merging**
