### PR TITLE
replace aiff with wav as the default value for recHeaderFormat

### LINKED ISSUE #5557: Switch away from using AIFF as default recHeaderFormat
## Motivation

When installing SuperCollider from fresh, it will by deffault recording the server output in the .aiff format unless changed ala `s.recHeaderFormat_("wav")` in a startup file. 

AIFF is a more MacOS centric format and it just doesn't work as well on Linux for example when converting files, importing/exporting from other programs etc. On Linux (and Windows?) users have to intervene to change this default to remedy the situation and I think it should be the other way around - if you want a more platform specific suffix/headerformat it should be something demanding intervention - just my 2 cents.

## Description of Proposed Feature

Change the default to "wav"

## Plan for Implementation

Change this line:
https://github.com/supercollider/supercollider/blob/e4743da23948f6ce1cfe7750273814d0f489cc20/SCClassLibrary/Common/Control/Server.sc#L98

### PR DESCRIPTION
**Pull request by RhnSharma**
## Purpose and Motivation

Fixes #5557

## Types of changes
Enhancement 

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

Hi @madskjeldgaard, how does this look?
Let me know if this needs any changes.
Thanks

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks @RhnSharma 
I personally don't oppose this change, but I think it would be good to get input from multiple devs whether this is desirable.
As for the PR itself, the documentation in `Server.schelp` (maybe elsewhere as well? haven't looked closely) should also be updated.

**Comment by telephon** [comment]
As far as I am concerned, it is ok. I am not sure about possible downsides of `wav` though. I think there used to be a difference in the way headers could be extended, but I don't know.

**Comment by dyfer** [comment]
I've just realized: what about files >4GB? Currently, AFAICT, `wav`'s data is being written above that level, but the header does not support that size (some programs will read the whole file, some will only read the size up to what's specified in the header). I'm not sure what's the state of supporting RF64/BWF to get around 4GB limit with `wav` files. I think the 4GB limit is something we should consider when making changes to the default format.

**Comment by jamshark70** [comment]
> FWIW the 4GB limit might also apply to AIFF

https://manual.audacityteam.org/man/export_formats_supported_by_audacity.html :

"Size limits for WAV and AIFF PCM-encoded files
"WAV and AIFF files are limited to a maximum size of 4GB (this is a general restriction and not an Audacity one)."

So we don't lose anything by switching to WAV.

I think this change is fine esp. for the benefit of Windows users. (FWIW, #5557 reports problems opening AIFF files in Linux, which I have never experienced, so I found that a puzzling remark.)

**Comment by madskjeldgaard** [comment]
> I think this change is fine esp. for the benefit of Windows users. (FWIW, #5557 reports problems opening AIFF files in Linux, which I have never experienced, so I found that a puzzling remark.)

This is generally true - sorry, I should have specified (was in a hurry when reporting - bad idea). The only program really that struggles with this is `lame`, it simply refuses to use aiff. Of the programs I use daily - `sox` and Reaper seem ok with AIFF for example. I don't use audacity and ardour so I don't know how they behave. Still, I think the argumentation holds - that having something more universal than an apple format as the default would be cool

**Comment by jamshark70** [comment]
> The only program really that struggles with this is lame, it simply refuses to use aiff.

FWIW I couldn't reproduce this: `lame -V5 SC_210703_134352.aiff SC_210703_134352.mp3` produced a valid mp3 file.

But again, I don't mind the change for the sake of Windows players.

It's more common to find audio apps that don't like 32-bit float samples, but we shouldn't change that -- floats prevent irreversible clipping.

**Comment by dyfer** [comment]
If we are to move ahead with this change, the documentation should be updated as well.

**Comment by dyfer** [comment]
To clarify: I'm now also OK with this change, but the PR needs to have the documentation updated, as indicated earlier.

**Comment by smrg-lm** [comment]
WAV is a simpler format and don't have extended 80 bit IEEE Standard 754 floating point number just for the sample rate... Which is a technological mystery for me.

**Review by joshpar — CHANGES_REQUESTED** [review]
Thanks! Can you please add changes for documentation?

**Comment by dyfer** [comment]
Hello @RhnSharma 
Would you be able to add documentation changes to this?

**Comment by dyfer** [comment]
Okay, I'm going to push documentation changes for this PR

**Review by joshpar — APPROVED** [review]

**Comment by dyfer** [comment]
Please note:
- I did make changes to the `Non-Realtime Synthesis` guide replacing `aiff` with `wav`
- `Buffer -write` still uses `aiff` as the default format; as this was not the objective of this PR, I did not change that
- `ProxySpace` recording uses `aiff` by default (present in the documentation in the main repo, but the classes are in the `JITLibExtensions` quark; again, I haven't touched these

**Comment by madskjeldgaard** [comment]
> Please note:
> - I did make changes to the `Non-Realtime Synthesis` guide replacing `aiff` with `wav`
> - `Buffer -write` still uses `aiff` as the default format; as this was not the objective of this PR, I did not change that
> - `ProxySpace` recording uses `aiff` by default (present in the documentation in the main repo, but the classes are in the `JITLibExtensions` quark; again, I haven't touched these

Thanks a bunch Marcin !

**Comment by dyfer** [comment]
All right, seems like there are no objections, I'll merge this. Thanks!

**Pull request merged**
