### PR TITLE
Classlib: Correct 'a+b.neg' ugen optimization, and fix descendants

### PR DESCRIPTION
**Pull request by jamshark70**
This PR addresses the issues raised in #972.

- `a + b.neg` should optimize to `a - b` *only* if `b.neg` has only one descendant. But the prior logic was to perform some sort of optimization, no matter how many descendants needed the `b.neg` result. This caused required UGens to be lost to dead code optimization.

- Scott C. correctly pointed out that the "optimize" methods use `descendants` to decide whether the optimization is legitimate, but they do not update the descendants sets belonging to inputs of the replaced or deleted units. This PR introduces a method to update the descendants of all relevant input UGens.

- It also adds some preliminary unit tests for SynthDef optimizations. Currently testing each binary-op optimization method for the correct types of remaining operators. The tests don't currently check inputs or descendant sets.

Test case from #972.

```
(
d = SynthDef(\spreaderBroke, {
	var a, b, c, d, e;
	a = DC.kr(0.3);
	b = a + 1.1;
	c = b.neg;
	Poll.kr(1, c);
	
	d = 1.2 - c;
	e = d.abs;
}).add;

d.children
)
```

Without the fix, Poll gets lost because its source (`b.neg`) got folded into `optimizeSub`, and then the optimized UGen got removed as dead code.

```
-> [ a DC, a Sum3, an Impulse ]
```

With the fix, d and e are correctly dropped (dead code elimination) but the use of `b.neg` in Poll prevents optimization (correctly), and Poll remains intact.

```
-> [ a DC, a BinaryOpUGen, an UnaryOpUGen, an Impulse, a Poll ]
```

Suggesting 3.9.1 as it is a bugfix (of a subtle issue that is hard to explain), not a new feature.

### CODE REVIEW

**Comment by scztt** [comment]
@jamshark70 I can look at this in the next few days. You are a superstar for addressing this :)

**Comment by scztt** [comment]
@mtmccrea Want to look at this also, since you originally found it? You should be able to drop in the .sc's to test.

**Comment by mtmccrea** [comment]
@scztt  I ran it on the original case (2013!) and it looks like we're getting the right answer now.
Thanks to you and @jamshark70 for taking this on, it's been a long time coming and I know this one was a deep dive. Much appreciated!

**Comment by patrickdupuis** [comment]
This builds, the reproducer is fixed, and the UnitTest passes. It's clear that @jamshark70 thought this through carefully.

@scztt have you had a chance to look at this?

**Comment by jamshark70** [comment]
FWIW, just now, I wanted to check myself on the descendants logic. After some false starts, I'm satisfied that it's working correctly.

Something to ponder for the future -- It's incredibly difficult to test UGen states in the middle of optimization, for a few reasons:

- No external access. We `initTopoSort` at the beginning of optimization (populating descendants), and re-init for the topological sort itself. You can't put debugging statements into the SynthDef function because optimization happens after the function returns, and you can't unit test the def after building because the antecedents and descendants variables have been cleared (and even if they weren't cleared, they would reflect the state after sorting, not the state after optimization). I had to resort to extensive and hard-to-read debugging posts.

- OutputProxies. Debugging was harder because MultiOutUGens pass OutputProxies as inputs to their descendants, and we don't set descendants the proxies. That's not wrong in itself -- we optimize and sort UGens, not output channels -- but it means, for instance, when I checked `a.tryPerform(\descendants).do(_.dump)`, if `a` was an OutputProxy, nothing would print.

I don't think we have to worry about it for this PR. I checked `optimizeAddNeg` and `optimizeToMulAdd` and, after `optimizeUpdateDescendants`, upstream units' descendants are right. Since I'm using a method for this update, I'm sure it's consistent across the other optimizations. But it's something to be aware of for future work on graph optimizing -- it's easy to check the result, but hard/impossible to unit test the logic to get there.

**Pull request merged**
