### PR TITLE
Linux README: update required CMake version

### PR DESCRIPTION
**Pull request by snappizz**

### CODE REVIEW

**Comment by crucialfelix** [comment]
We didn't finish deciding about this yet.  3.1 is required for supernova but not yet for supercollider/ide/sclang/scynth

https://github.com/supercollider/supercollider/issues/2143

**Comment by danstowell** [comment]
What do we actually GAIN by doing this? There's no point bumping up a dependency just because "modern modern" etc etc. Is there a specific cmake feature we want to use more widely? Or is the supernova aspect your motivation (since supernova's cmake uses some recent features)? I'd prefer to put supernova's stricter cmake requirement into the supernova-specific CMakeLists.txt, since the current almost-consensus seems to be to let supernova run ahead in its requirements.

**Comment by crucialfelix** [comment]
I think we should resolve the discussion in the other thread and then do one PR that updates all docs and cmake requirements.

The other thread is much more detailed on this.

3.0.2 may be the current minimum for sc (if I'm following it all correctly)

**Comment by timblechmann** [comment]
> There's no point bumping up a dependency just because "modern modern"

@danstowell "modern" features allow a more robust architecture, leading to less bugs, less maintenance overhead and less developer time spent on working around classes of bugs, which are simply not possible when using "modern" features.

it also might help supercollider to attract new developers and not to loose experienced ones :P

**Comment by crucialfelix** [comment]
We know, we discussed it quite well in the other thread. Now let's get the exact version decided (over there) so we can avoid boring repeat discussions.

**Comment by snappizz** [comment]
I'm not endorsing this upgrade, all I'm trying to do here is update the
docs to match the repository. You'll get an error if you try to build with
an older cmake.

Maybe I'm simply putting this in the wrong place -- does supernova have
separate build instructions?

**Comment by crucialfelix** [comment]
Were you building supernova ?  That does now require 3.1 and some docs somewhere need to be updated to mention that.  But AFAIK the main sclang/scsynth/scide do not require cmake 3.1 right now.

**Comment by snappizz** [comment]
If you follow the instructions in the Linux README, supernova is built by default and it produces an error for cmake < 3.1.

**Comment by danstowell** [comment]
Maybe #2170 instead?

**Pull request closed without merging**
