### PR TITLE
ide cleanup

### PR DESCRIPTION
**Pull request by timblechmann**

### CODE REVIEW

**Comment by telephon** [comment]
I'd like to make all those changes at once, together with the server-refactoring, so that there is only trouble once ...

**Comment by timblechmann** [comment]
fwiw, i'd suggest that `3.7.x` is for bugfixes only, not for architectural improvements ... and please don't wait for half a year before merging this: if you want to release 3.7, creating a release branch is the first step. i have pull requests open for several months because "3.7" is about to be released.

**Comment by crucialfelix** [comment]
Trust me Tim. I'm releasing this f**er soon.  All the other people who
should have released their work, didn't (for whatever reason).

I'm doing it.

I've already announced that the release is closed for new features.
This pr is obviously not going in.

I already announced that I am doing beta as soon as we resolve the ones
that are in the 3.7.0 milestone

**Comment by timblechmann** [comment]
i know, managing a release is time consuming and not thankful ... have been doing it a couple of times ... time consuming, no reward ... nevertheless: first thing i used to do when managing a release is to create a release branch (i used to do it like two months before the actual release)

**Comment by crucialfelix** [comment]
Yeah, and then everybody commits thing here or there and then argues about what should be cherry picked. Then tediously they cherry pick things and discuss each one, then some get missed and those get discussed.

We are done, we are ready.

I'll make the release branch, make a beat release, if it does not actually kill any of the users then we release it.

**Comment by telephon** [comment]
yes, please go ahead. You could instantly also make a 3.8.0 release that will get all the refactorings in 3.8.1, so whoever wants to just have bugfixes stays on 3.7.x, and whoever wants unstable goes 3.8.x

Is this a reasonable thing to do?

**Comment by crucialfelix** [comment]
personally I really like git-flow

it solves this problem very elegantly.

you do hotfixes and it automatically merges to master (releases) and
development branch

**Comment by timblechmann** [comment]
this arguing is usually referred to as 'review process'

**Comment by telephon** [comment]
@crucialfelix so in terms of the workflow: would we now merge this?

**Comment by timblechmann** [comment]
no conflict anymore.

**Pull request merged**
