### PR TITLE
Update "Getting Started" chapter 3

### PR DESCRIPTION
**Pull request by pearcemerritt**
## Purpose and Motivation

Revisiting SuperCollider after a long time away and making doc edit suggestions as I go. Previous chapter PR: #4854

## Types of changes

- Documentation

## To-do list

- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by pearcemerritt** [comment]
Is there some doc that explains how to render these schelp files? Or do I need to copy them into `SuperCollider.app/Contents/Resources/HelpSource/Tutorials/Getting-Started` in order to see that?

**Comment by brianlheim** [comment]
> Is there some doc that explains how to render these schelp files? Or do I need to copy them into SuperCollider.app/Contents/Resources/HelpSource/Tutorials/Getting-Started in order to see that?

when developing, i typically have sclang configured to use the class library in the source directory (excluding the default compile paths). i believe that causes the IDE to also use the help files in the source directory too, because I've always been able to just edit those and see the result immediately when i reload.

**Comment by pearcemerritt** [comment]
>  i typically have sclang configured to use the class library in the source directory (excluding the default compile paths)

Is there a doc that describes how to do this ^ ?

**Comment by brianlheim** [comment]
not to my knowledge! but i'm also not sure if that's what other people do. on macOS i think it's trickier. anyway where would you like that to live?

**Comment by telephon** [comment]
> not to my knowledge! but i'm also not sure if that's what other people do. on macOS i think it's trickier.

no, it's exactly the same. You just use the interpreter preferences and remove the default paths and include the path of the source folders (supercollider/SCClassLibrary and supercollider/HelpSource).

**Comment by brianlheim** [comment]
oh, i know now, i was thinking of how it's difficult to run the IDE except when everything is assembled in an app bundle

**Comment by telephon** [comment]
yes, this is true.

**Comment by pearcemerritt** [comment]
@brianlheim @telephon thanks! With some poking around I was able to figure out what y'all were talking about :D

> anyway where would you like that to live?

@brianlheim I looked at the wiki and I didn't really see any section that felt suitable to describing this level of local set-up. I think it would warrant a new page. Could be included on `Home.md` right after the unit testing guide you made. Here's some boilerplate markdown:

```
SuperCollider can be configured to read classes and help source from your local code repository:

macOs
-----
In the IDE:
1. Preferences > Interpreter
1. Check `Exclude default search paths`
1. For reading local classes
   1. Add an "include" for `/path/to/supercollider/SCClassLibrary`
1. For reading local help source
   1. Add an "include" for `/path/to/supercollider/HelpSource`

windows
-------
TODO

linux
-----
TODO
```

**Comment by pearcemerritt** [comment]
Oh, just found this!
https://doc.sccode.org/Guides/WritingHelp.html
Maybe it should go in here ^ ? But it should also probably be linked from the wiki somewhere

**Comment by dyfer** [comment]
Re: switching class library:
I have some code to aid with changing class library. Not 100% foolproof but I use it constantly.
- be sure to set paths to your source in multiple places in the file
- it will recompile the library when you run the appropriate sections

https://gist.github.com/dyfer/0a98f3e6bb194e2e29a8e7c9355046ec

**Comment by brianlheim** [comment]
thanks all! i just added this: https://github.com/supercollider/supercollider/wiki/Setting-up-your-development-environment, i think that pretty much covers this! feel free to edit with additional information or TODOs for other information you'd like to see.

**Pull request merged**
