### PR TITLE
Remove dead android-related code

### PR DESCRIPTION
**Pull request by brianlheim**
## Purpose and Motivation

remove android-related code for scsynth that hasn't been working since.. v3.4?

## Types of changes

- Cleanup

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
If someone decides to pick up on work to port SC to Android, would it be useful for them to be able to find this more easily than checking out an old SC branch?

**Comment by brianlheim** [comment]
> If someone decides to pick up on work to port SC to Android, would it be useful for them to be able to find this more easily than checking out an old SC branch? I guess my question is whether we'd want to leave this around for the time being.

hmm, why is this hypothetical person who hasn't appeared in 8+ years capable of finding the code here, but not capable of looking in the changelog or git history, or asking project maintainers?

**Comment by brianlheim** [comment]
sorry, maybe a bad joke. what i mean is, i think it's okay to remove this because there are lots of other ways a person interested in doing that work would be able to find it.

**Comment by brianlheim** [comment]
@dyfer what do you think? i'd really like to remove this.

**Comment by elgiano** [comment]
My 2c: this code is part of a project that has been inactive for more than 8 years. Everything changed in the meanwhile, and, following also some discussion on the forum, I think a modern implementation could be done with OpenSLES, and, in general the android code we have now is as good an example as SC_CoreAudio would be.
So, I would call this safe to remove, also because there's ongoing discussion about SC and Android on the forum [here](https://scsynth.org/t/my-attempt-to-build-supercollider-on-termux-android/1297/4), so that anyone interested in working on this can see there's some interest already there.

**Comment by dyfer** [comment]
thanks for your comments @brianlheim and @elgiano 

I wasn't sure about this just because I didn't feel I have enough perspective. But from the conversation I see that there's no reason to keep this around, as any possible "current" Android implementation would look very different anyway. 

Should I still merge this even though it's aimed at 3.11 and we're in the middle of the release?

**Comment by brianlheim** [comment]
> Should I still merge this even though it's aimed at 3.11 and we're in the middle of the release?

good point, let's wait. 👍

thanks for the quick responses @elgiano and @dyfer. :)

**Comment by dyfer** [comment]
Thanks! Just checking - as this went into 3.11: In case we don't release 3.11.2, would we need to remember to merge this (or 3.11 branch) into develop?

**Comment by brianlheim** [comment]
> In case we don't release 3.11.2, would we need to remember to merge this (or 3.11 branch) into develop?

yeah, we'd merge 3.11 into develop one last time before starting a 3.12 release

**Pull request merged**
