### PR TITLE
SynthDef.build gets a changed posthook

### LINKED ISSUE #5656: SynthDef.build posthook
## Motivation

[Some quarks](https://refined-github-html-preview.kidonng.workers.dev/supercollider-quarks/autogui/raw/master/Help/SynthDefAutogui.html) are rolling their own `SynthDef.build` posthook by overriding that method because their devs hate depending on SynthDescLib, perhaps because one forgets to `add` their synthdefs manually. In practice, this is a bit problematic because it can result in such quarks [installing outdated versions of SynthDef.build](https://github.com/supercollider-quarks/autogui/issues/4).

I can say I commiserate with that, as I have occasionally forgotten to `add` a new version of SynthDef only to wonder why nothing appears to have changed when I start a Synth on that name.

But for such purposes as standard notification mechanism exists in SC, and it is actually used by SynthDescLib, but alas not by SynthDef, so that doesn't help if you expect fully automatic `add`s or some other kind of post-hook in `SynthDef.build`.

## Description of Proposed Feature

Basically, this is a one-line addition to make `SynthDef.build` call `changed` on its class at the end of a successful build, passing the newly built SynthDef instance as parameter to the notification:

```
+ SynthDef {

	build { arg ugenGraphFunc, rates, prependArgs;
		protect {
			this.initBuild;
			this.buildUgenGraph(ugenGraphFunc, rates, prependArgs);
			this.finishBuild;
			func = ugenGraphFunc;
			this.class.changed(\synthDefBuilt, this); // post-HOOK added
		} {
			UGen.buildSynthDef = nil;
		} ;	
	}
}
```

Interested objects can register themselves the usual way to receive that, e.g.

```
ForgetfulMe {

	classvar <>autoAdd = false;

	*initClass {
	
		Class.initClassTree(SynthDef);
		SynthDef.addDependant(this);
		
		// you probably don't want update to run during sclang boot
		// as that would double-add every std. synth, wasting a bit of time
		StartUp.add {
			{ autoAdd = true; }.defer(2) // too early otherwise
		}
	}
	
	*update { arg obvious, iKnow, synthDefInstance;

		if(this.autoAdd) {
			synthDefInstance.add;
			postln("Auto-added new SynthDef" + synthDefInstance.name)
		}
	}
	
}
```

As rather trivial application, the above will auto-register synthedefs with synthdesclib. I'm not saying this latter class should be added to SC. I'm just giving it as an example that I have used to test that this idea works in practice.

## Plan for Implementation

Pretty trivial. I'll make a PR for that one-liner.

### PR DESCRIPTION
**Pull request by avdrd**
## Purpose and Motivation

Fixes #5656

## Types of changes

- New feature

## To-do list

If reviewers don't think this is another horrible idea of mine, I'll even write a test case and documentation for this, if deemed necessary. SynthDescLib does document its `changed` notification hooks in the help, although many other classes in SC do not.

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks!
In [#5656](https://github.com/supercollider/supercollider/issues/5656#issuecomment-1000581671) @jamshark70 suggested a slightly different symbol, let's agree on that in the discussion here.

**Comment by dyfer** [comment]
@jamshark70 do you have any more input for this PR?

**Comment by jamshark70** [comment]
I think I like Julian's `\synthDefReady`.

**Comment by dyfer** [comment]
@avdrd would you be willing to update the PR as suggested by @jamshark70 ?

**Comment by avdrd** [comment]
@dyfer Ok, I'll change the name to `\synthDefReady`.

**Review by telephon — APPROVED** [review]

**Pull request merged**
