### PR TITLE
Cherry-pick three build system PRs

### PR DESCRIPTION
**Pull request by brianlheim**
## Purpose and Motivation

this cherry-picks 3 PRs:
- #4906 "add CI jobs to implement platform support RFC"
- #5174 "travis: add legacy macos build and custom Qt version"
- #5014 "Fix linking errors with LIBSCSYNTH=ON"

mainly we want #5174 so we can deploy a legacy macOS build for 3.11.2, but in order to do that easily we also
cherry-pick #4906. #5014 is another fix that could have been cherry-picked earlier in order to fix libscsynth builds, but wasn't.

the only "breaking change" here is that the macOS job from which we deploy is bumped from the xcode9.4 image to
xcode10.x and xcode11.3 images. i'd prefer this to keeping the old one for a couple reasons:
- it's easier to maintain just one version of our CI matrix and not have to remember differences between 3.11 and develop CI scripts
- any issues we find with this during the 3.11.2 release candidate can be used to fix both 3.11 and develop, saving time
  overall
- travis and/or homebrew may drop support for this older osx image soon anyway

the other changes from #4906 are documentation updates and bugfixes

there were 4 merge conflicts:
1. in CMakeLists.txt, don't need a SYSTEM_ABLETON_LINK option because that's not a feature in 3.11
2. in .travis/before-script-osx.sh, previously we had 'install qt5' instead of 'upgrade qt5', but no matter because that
line is replaced anyway
3. in server/{scsynth,supernova}/CMakeLists.txt, we previously included one of the files we needed in the executable targets, but not both.

## Types of changes

- Documentation
- Bug fix
- New feature
- Breaking change
- all of the above

## To-do list

- [x] Code is tested
- [ ] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks @brianlheim !
I think I'd prefer to wait with this until we know how to address #5188

**Comment by brianlheim** [comment]
> I think I'd prefer to wait with this until we know how to address #5188

why? the same fix will have to be applied to both branches, and this way we can apply whatever fix is needed directly to 3.11 first and then merge into develop

**Comment by brianlheim** [comment]
i think the travis build failures here are due to a fix related to LIBSCSYNTH that was not cherry-picked to 3.11... will investigate

**Comment by brianlheim** [comment]
okay actually i agree we should wait now. there's a lot cherry-picked here and we should rightly focus on one problem at a time.

**Comment by dyfer** [comment]
> why? the same fix will have to be applied to both branches, and this way we can apply whatever fix is needed directly to 3.11 first and then merge into develop

I just wouldn't want an issue with XCode 11 additionally delay the 3.11.2 release. 
IMO for 3.11.2 we could consider releasing it using the current (3.11) build config, or even temporarily dropping QT version (i.e. not upgrading in CI) to maintain macOS 10.12 compatibility. That's of course just my personal view.

I agree that this also becomes a larger PR now and it would be better to focus on one thing at a time.

**Pull request closed without merging**
