### PR TITLE
class library: BufWr checks also inputArray for rates

### LINKED ISSUE #3748: BufWr doesn't throw an error for wrong input rate
When you play a control rate signal through an audio rate `BufWr` it doesn't complain, but records arbitrary spikes to the buffer.

```supercollider
b = Buffer.alloc(s, 1024);
{ BufWr.ar(0, b, Phasor.ar(0, 1, 0, BufFrames.kr(b))); 0.0 }.play;
b.plot
```

To fix this, we could either convert the input automatically or throw an error, like this:

```supercollider
checkInputs {
		if (rate == 'audio') {
			if(inputs.at(1).rate != 'audio') {
				^"phase input is not audio rate: % %".format(inputs.at(1), inputs.at(1).rate)
			} {
				if(inputs[3..].any { |x| x.rate != 'audio' }) {
					^"inputArray input is not audio rate: % %".format(inputs[3..], inputs[3..].collect(_.rate))
				}
			}
		};
		^this.checkValidInputs
	}
```

### PR DESCRIPTION
**Pull request by telephon**
This fixes #3748.

### CODE REVIEW

**Comment by telephon** [comment]
The permissible rate combinations are not documented. But they are never documented, so I assume that is ok.

There is actually a misleading statement about multichannel expansion in the documentation, but that is another issue.

**Comment by brianlheim** [comment]
> But they are never documented, so I assume that is ok.

I'm not sure that's a good enough reason. In the spirit of pushing for better dev practices overall I think you should add documentation for this. It will set a good precedent.

**Comment by brianlheim** [comment]
Related: #3723

**Comment by telephon** [comment]
I'd really prefer do this kind of documentation in one go, and collected in a separate place, maybe a database. It makes no sense to add this as little pieces everywhere. Also we have no agreed on format for this (there was a suggestion recently).

**Comment by brianlheim** [comment]
The format definitely needs to be discussed, yes. Let's try to figure out a solution to #3723 soon then, because this is really not hard to note and would seem to improve quality of life for many users.

**Comment by telephon** [comment]
ups, I had assigned you @Sciss and merged already. If you have the time, can you have another quick glance at it?

**Pull request merged**
