### PR TITLE
class library: sclang can derive current interpreter config path for IDE

### PR DESCRIPTION
**Pull request by telephon**
This would make it possible to add paths to the current LanguageConfig via the Quarks and save it there, too.

I'm not sure about where exactly the link between IDE and sclang is supposed to be, in particular when this path is used. Maybe Platform is a better place?

### CODE REVIEW

**Comment by telephon** [comment]
This is important for the Quarks system to function properly. If you are using a different editor, you can supply a different path in ````Platform````. But I do agree that the yaml format is very specific. I'd be happy to integrate a more general use case, but I have no setup to test it.

**Comment by crucialfelix** [comment]
now that I think about this, the only time the config file setting from the IDE's preferences is used is when you are using the IDE.  that yaml file is for the IDE, not for all clients.

supercolliderjs/atom, emacs, vim, command line etc. would not use that and I wouldn't expect them to use that.

so somebody may get caught if they use the IDE, switch to a custom config file, install quarks and then find that when they use the other editors they don't see those added.

but if we DON'T pay attention to this setting then they may use the IDE, switch to a custom config file, install quarks and even in the IDE find that the quark doesn't get added.

not sure what to do. maybe only if platform is IDE then consult the IDE's config file setting.

**Comment by telephon** [comment]
@crucialfelix You are right, this is the better way.

>ideal solution: add the paths to whatever is the currently active config file. not as determined by this yaml file, but check what file was used when sclang booted.

This path should be accessible via ````Platform````. I've looked around for half an hour or so, but couldn't find the place where to access this path. Should work like ````_Platform_userConfigDir```` somehow.

**Comment by telephon** [comment]
Ah, just found it, it is in ````gConfigFile.c_str()````. But I'm not sure where to read it from there into Platform.

**Comment by crucialfelix** [comment]
I think it would be a property of the interpreter, not the Platform.

its what config is currently active, regardless of how it got there or how
the platform or command line or whatever decided to specify that config.
supercollider.js does not specify a platform string as it doesn't want to
be tied to or dependent on any particular sclang class implementations.

either that or we store installed quarks in a separate file. but I think we
should shipping, not tinkering more.

**Comment by crucialfelix** [comment]
obviously the interpreter discards the config file path after reading it.
which is reasonable.

**Comment by telephon** [comment]
>obviously the interpreter discards the config file path after reading it. which is reasonable.

Wouldn't it be reasonable if it kept the path for later access?

**Comment by crucialfelix** [comment]
I just meant that the way it was written is reasonable for the job it was
designed to do: just parse the config file.

I'm still undecided what is best.

**Comment by jamshark70** [comment]
I hope this isn't excessively dense, but when you do `LanguageConfig.store`, it knows where to write the file. So I suppose there's a path hidden in there somewhere?

**Comment by telephon** [comment]
>I hope this isn't excessively dense, but when you do LanguageConfig.store, it knows where to write the file.

It doesn't know where to write it, it uses a default. This is why when you call ````.store```` in the Quark system, it stores it in the default. The IDE knows where to write it from the ide config file.

But indeed ````LanguageConfig```` would be the place to add the current path.

**Comment by telephon** [comment]
OK, I think I got it. Will need till tomorrow until I can submit a new pull request.

**Comment by telephon** [comment]
I opened a new one: #1327

**Pull request closed without merging**
