### PR TITLE
supernova: mutex for tcp send thread concurrency

### PR DESCRIPTION
**Pull request by sonoro1234**
This is a PR motivated by #4400

After this changes I dont get bad formated tcp /done responses from b_alloc or b_free.
There are other /done responses that should also be changed (/b_allocRead and more)

I think this could be related to #4062 because /notify also should modify the /done behaviour (or may be others used in the boot from sclang)

This is not ready for commit, the purpose is to provide information so that others can take a look.

### CODE REVIEW

**Comment by Spacechild1** [comment]
this doesn't look right. The /done message should definitely be sent in stage 4 (= the second system callback), see `void BufAllocCmd::Stage4()` in scsynth. 

I just had a quick look and I think the actual reason might be `tcp_connection::send` implicitly called in `send_done_message`. The method itself doesn't grab a mutex and I don't know if `socket_.send` is actually thread-safe (actually I don't think so...). On the other hand, `udp_endpoint::send` calls `sc_notify_observers::send_udp` which does lock a mutex.

you can try adding a mutex to the `tcp_connection` class and use a lockguard in the `send` method.

**Comment by jamshark70** [comment]
> The /done message should definitely be sent in stage 4 (= the second system callback), see `void BufAllocCmd::Stage4()` in scsynth. also, IO shouldn't be done in the realtime thread.

I don't have a lot to add, but I can confirm that both of these observations are correct. The done message shouldn't be moved outside the callback.

The mutex idea sounds right. It wouldn't surprise me that the UDP connection was used and debugged a lot while TCP was not.

**Comment by Spacechild1** [comment]
does the mutex solve your problem?

**Comment by sonoro1234** [comment]
@Spacechild1  and @jamshark70 
Thanks for taking a look!!!.
With the addition of tcp_mutex the issue in #4400 disapears.

@dyfer  I think this could solve #4062 also. Could you try?

I would open an issue for an enhancement: Could someone with the knowledge please document supernova? It is so difficult to make relations with scsynth code: SC_SequencedCommand shows two different threads RT and NRT but in sc_osc_handler at least three threads appear: system, rt and io.
Sharing this knowledge about supernova would make easier to have more eyes taking a look at the code.

**Comment by Spacechild1** [comment]
Skimming through the code I think that Supernova actually has two NRT threads:
1) `fire_io_callback` for client notification, e.g. `send_node_reply`.
2) `fire_system_callback` for asynchronous tasks, e.g. loading a soundfile.

this is actually a good thing. If you schedule a long async task in Scsynth, all following scheduled OSC messages have to wait for the task to finish, because they are on the same queue. In Supernova, however, those two things are decoupled (this is just my understanding from reading the code, I didn't actually test this, so please correct me if I'm wrong).

I think `handle_sync` in Supernova is a good example for this: 
https://github.com/supercollider/supercollider/blob/63783aeca007c1e1d2a7cf73b3f3da056913f077/server/supernova/sc/sc_osc_handler.cpp#L1114) 
compare it with `SyncCmd` in Scsynth 
https://github.com/supercollider/supercollider/blob/63783aeca007c1e1d2a7cf73b3f3da056913f077/server/scsynth/SC_SequencedCommand.cpp#L242

Note that for example `send_done_message` might be called from either the system thread (see the last stage of `handle_b_alloc`) or the io thread (see `send_trigger`). This explains why you get race conditions if the endpoint's send method is not thread safe.

> Could someone with the knowledge please document supernova

And probably also scsynth :-)

**Comment by sonoro1234** [comment]
@Spacechild1  Thanks for the spotlights!!
At least scsynth has Ross Bencina chapter 26 (Althought it is quite difficult to follow)

**Comment by sonoro1234** [comment]
I think this is a bug quite severe affecting all tcp communication in supernova with a solution only needing two lines.

If the git history seems complicated is because my clumsiness. 
If redoing all in one commit is best for anyone rewiewing I dont mind repeating PR

**Comment by brianlheim** [comment]
This PR has merge conflicts now, can you please rebase it according to the instructions [here](https://github.com/supercollider/supercollider/wiki/Cpp-formatting-instructions#i-made-a-pr-before-the-reformat-and-it-has-merge-conflicts-now-how-do-i-fix-it)? Let me know if you have any questions.

**Comment by sonoro1234** [comment]
For this PR it would be much easier: close it, make a branch from `develop` or `3.10` (whatever you prefer) add the two lines of code and open a PR.

May I do that?

**Comment by brianlheim** [comment]
you can do it however you'd like

**Pull request closed without merging**
