### PR TITLE
class library: cosmetics

### PR DESCRIPTION
**Pull request by telephon**
just because it is fresh now.

### CODE REVIEW

**Comment by brianlheim** [comment]
This should be an issue rather than a PR IMO.

**Comment by telephon** [comment]
I'm sorry, I don't understand.

**Comment by brianlheim** [comment]
#2913, #2914

**Comment by brianlheim** [comment]
I am closing this because until we have standards in place or have documented decisions, we can't make PRs enforcing style.

**Comment by brianlheim** [comment]
(I think that's clear from the discussion here: https://github.com/supercollider/supercollider/pull/2908)

**Comment by brianlheim** [comment]
and if it's not, feel free to reopen; I'm just trying to move this conversation to a format that will be more productive for everyone

**Comment by telephon** [comment]
While I am happy to help working together on a formatting guideline, closing this is a wrong signal. Brian, you shouldn't oblige yourself to be a gatekeeper. Why don't just trust for a moment? 

This commit was really just a minor change!

I had given comments to the PR which was merged anyway, so they were lost.

**Comment by brianlheim** [comment]
OK, I'm sorry. I will not touch your PRs again like this.

I think it would help if I explained my side of things here. Right now, from my perspective, there seems to be a prevailing double standard, which is that I am largely dismissed or ignored by you and others on this project when I begin discussions (not even PRs!) about style. And yet, you have been quietly and sometimes not-so-quietly changing things yourself in a couple of recent PRs. So even this commit, though small, feels unfair to me.

After seeing this pattern of behavior and the same conflicts repeat themselves over the last few months, I decided that it really needed to be brought to a more formal level of discussion for everyone's sake. I could have done that without aggressively closing this PR, and I apologize for doing so. To be totally honest, it came from a feeling of powerlessness; I'm not proud to admit that. I'm learning here, and I really, really appreciate your patience.

Can I request that we continue to discuss style-related changes as a community, before any changes are made? That already seems to have worked out well on the two new issue tickets, so I have hope that this will reduce friction everywhere.

**Comment by telephon** [comment]
> And yet, you have been quietly and sometimes not-so-quietly changing things yourself in a couple of recent PRs. So even this commit, though small, feels unfair to me.

I am really sorry if that came across as ignorance and aggression! Actually it is interesting for me to understand that it did, because it really surprises me. Thanks for your honest response, it helps a lot. In my perception, I was just cleaning up the dishes that have been standing there for ages …

But let me use this to just say that anything that I do here is *always* a suggestion.

There are a lot of tacit practices and intuitions that we have developed in the community over many years, and it can sometimes be painful to suddenly having to articulate them. I kind of enjoy this, maybe because I like reflection. I worry a little when trying to make a rule out of them, that some of the liberal attitude might get lost.

I'm happy about the precision here, however, because I've often applied similarly precise formatting as far as my own contributions are concerned, and it is maybe good to find a common one if possible.

**Comment by brianlheim** [comment]
> Thanks for your honest response, it helps a lot.

No problem. I should have been straightforward about this earlier, but I let it stew and that's on me. I will do my best to improve how I approach these situations!

> There are a lot of tacit practices and intuitions that we have developed in the community over many years, and it can sometimes be painful to suddenly having to articulate them. I kind of enjoy this, maybe because I like reflection.

This is very good to know! I am a curious person; if there are practices in place, I want to know what they are why, because it's an opportunity to expand my perspective. I will say that in the time I have been with this project I have learned so much from you—especially when you say something that I totally disagree with! Usually in a week's time I end up understanding your point and it helps me think more broadly about what I do as a developer and software engineer. That is invaluable. Thank you!

I think this passage from the Boost development guidelines are relevant:

"Beman Dawes comments: Failure to supply contemporaneous rationale for design decisions is a major defect in many software projects. Lack of accurate rationale causes issues to be revisited endlessly, causes maintenance bugs when a maintainer changes something without realizing it was done a certain way for some purpose, and shortens the useful lifetime of software.

Rationale is fairly easy to provide at the time decisions are made, but very hard to accurately recover even a short time later."

Without the part about maintenance bugs, this is essentially what I'm trying to articulate: if we have things written down somewhere, then it's much easier to recover, distribute, and build on existing practices. If it's not written down, someone like me (interpret that however you want :P) could come along and easily get confused or frustrated.

> I worry a little when trying to make a rule out of them, that some of the liberal attitude might get lost.

This is reasonable; I agree. What are some things we can do to avoid this?

> I'm happy about the precision here, however, because I've often applied similarly precise formatting as far as my own contributions are concerned, and it is maybe good to find a common one if possible.

I'm glad to hear that! I would love for everything to look uniform, and to me the great thing about these types of changes are that it's not too hard to apply it everywhere once we decide on it.

**Comment by bagong** [comment]
This was a well handled conflict that could have easily gone far worse. I welcome a clear style guide for whitespace and other little coding details. I think similar precision with discussion style, e.g. aspects of subjectivity and implicit judgmentalism are likely more important for fruitful development in this community.

**Comment by telephon** [comment]
I always sense and value your curiosity! So yes, let's just continue to think such things through. As long as we communicate sufficiently that this is not control obsession this is fine.

The comment by Beman Dawes you quote is well put, and I understand that this pull request here is a good starting point for a discussion.

>>I worry a little when trying to make a rule out of them, that some of the liberal attitude might get lost.
>This is reasonable; I agree. What are some things we can do to avoid this?

One possibility is to always apply principles in context. As a rule of thumb, the style of the surrounding code is the measure. And sometimes we can just clean up a whole file.

In general, it is reasonable to be strict for oneself and less so for others. Overly picky demands spoil the rhythm, while suggestions are part of it. If someone doesn't follow them, one can polish later.

These style guides can be embellished with really good sounding examples, so that reading them is an aesthetic pleasure?

**Comment by brianlheim** [comment]
> One possibility is to always apply principles in context. As a rule of thumb, the style of the surrounding code is the measure. And sometimes we can just clean up a whole file.
>
> In general, it is reasonable to be strict for oneself and less so for others. Overly picky demands spoil the rhythm, while suggestions are part of it. If someone doesn't follow them, one can polish later.
>
> These style guides can be embellished with really good sounding examples, so that reading them is an aesthetic pleasure?

These are great suggestions, thank you @telephon. I know the working guidelines I've got look pretty bare right now, but I hope to flesh them out with examples over the next few weeks. Feel free to add if you'd like; I'd especially like to see an example of what you mentioned here on #2914 :

> If there are several returns and the last one is not a fallback (but could just as much be amended by further ones), then and only then add a trailing semicolon.

Since consensus has been reached on #2914 and #2913, I'm removing the "waiting for consensus" tag from this PR and merging it. :) Thanks again for the compelling discussions here and on those two PRs.

**Comment by telephon** [comment]
thank you for bringing it up!

**Pull request merged**
