### PR TITLE
Move internal css to scdoc.css

### PR DESCRIPTION
**Pull request by rygen**
While trying to change the colors of the documentation to match a custom color scheme I found that some parameters couldn't be adjusted due to these html files having internal style sheets.

### CODE REVIEW

**Comment by miguel-negrao** [comment]
I think this could have been a single commit, it seems to me all commits refer to single "feature". Next time you could consider squashing the commits into a single commit, resulting in cleaner history, also easier to revert if needed. Thanks for contributing ! :)

**Comment by rygen** [comment]
Sorry, I realised how lame it was not to do it as a single commit some time after having submitted the pull request.

**Comment by miguel-negrao** [comment]
No worries. :-) 

Abraço ;-)

**Comment by rygen** [comment]
Ainda bem que o abraço saiu do CoC, senão estarias em apuros, haha ;)

[sorry to all non-portuguese speakers]

**Pull request merged**
