### PR TITLE
Topic/pdef clear fixes

### LINKED ISSUE #4767: Pdef quantization doesn't work when set as source to an Ndef
## Environment

* SuperCollider version: 3.10.3
* Operating system: Windows 10 Pro
* Other details (Qt version, audio driver, etc.):

## Steps to reproduce

```supercollider
// Get rid of old stuff
Ndef.clear; Pdef.removeAll; c = TempoClock(1.5);

// Create a "ping" metronome so we know where every 8th beat falls
Pdef(\ping, Pbind(\degree, Pseq([14, Pn(7,7)], inf), \dur, 1, \amp, 0.02)).play(c, quant: 8);

// Now create a quantized Ndef with a quantized Pdef as its source
p = Pbind(\degree, Pseq((0..3)), \dur, 0.125);
Ndef(\test).clock_(c).quant_(8).play;
Ndef(\test).source = Pdef(\pat, p).clock_(c).quant_(8);

// Play a minimal pattern that *should* start on a multiple-of-eight beat
Pdef(\pat).source = p.copy;
// (it doesn't, it seems to start right away, on the next beat...try it multiple times)

// In contrast, this works (not using Pdef but Pbind as Ndef source directly) -- the source changes at the quantization point:
Ndef(\test, p);
```

## Expected vs. actual behavior

If you're playing a `Pdef` directly, and when you set a Pdef as the source for an Ndef, the quant setting seems to be respected. However, if you set the Pdef source when it's not playing (but when it's set as source for a playing `Ndef`) the quant is **not** respected, and the new source pattern starts playing immediately on the next beat.

### PR DESCRIPTION
**Pull request by telephon**
## Purpose and Motivation

Where the old source pattern is shorter than the quant value, Pdef /
EventPatternProxy would start the new pattern too early. This is
because Pfindur only cuts and doesn’t extend. This change checks if the
stream has ended and adds a silent event that holds the time until the
new pattern comes in.

fixes #4767.

Also Pdef.clear didn't empty the dictionary as expected, this is fixed, too.

## Types of changes

Internal changes to embedInStream and constrainStream in EventPatternProxy

- Bug fix

Possible breakage:
If someone would use a Pdef to stream a pattern that sometimes returns `nil` and then values again, this would change behaviour now (it would stop). But all other patterns behave like this, so it is an edge case. Opinions welcome. 

## To-do list

- [ ] Code is tested
- [x] All tests are passing
- [ ] This PR is ready for review

### CODE REVIEW

**Comment by totalgee** [comment]
Tested this just now -- thanks, it's greatly improved, and mostly works as I'd expected. But I still found one odd thing about it:

```supercollider
// Pdef.clear works now, thanks!
Ndef.clear; Pdef.clear; c = TempoClock(1.5);

// Create a "ping" metronome so we know where every 8th beat falls
Pdef(\ping, Pbind(\degree, Pseq([14, Pn(7,7)], inf), \dur, 1, \amp, 0.02)).play(c, quant: 8);

p = Pbind(\degree, Pseq((0..3), 4), \dur, 0.125);
q = Pbind(\degree, Pseq((3..0)-7, 1), \dur, 0.5);
// Create a quantized Ndef with a quantized Pdef as its source
Ndef(\test).clock_(c).quant_(8).play;
Ndef(\test).source = Pdef(\pat, p).clock_(c).quant_(8);

// Play patterns that should start on a multiple-of-eight beat (they do, with fixed version)
Pdef(\pat).source = p.copy;
Pdef(\pat).source = q.copy;
```

If you play the two source-setting lines above, it now works exactly as I'd hoped...waiting for the next quant boundary. **Except** in one case: if you *set a new source before the other pattern has finished running* (while it's still playing notes), then it will be scheduled immediately when the current source ends. So quickly alternate executing the above two lines (or just repeat the same one several times in a row) and you'll see what I mean.

The other thing to ask about (not sure if it's a bug or desired behaviour) is that when you set a Pdef with the same source (object) several times, it doesn't re-schedule it. (this is why I am doing `source = p.copy` above instead of just `source = p`, because that won't schedule it to play again on the next quant boundary). Generally this isn't a huge problem (because normally in live coding I'm not sending the same object multiple times without modifying it), but I wanted to ask about it.

Thanks, this fixed version is already a huge improvement!

**Comment by telephon** [comment]
> The other thing to ask about (not sure if it's a bug or desired behaviour) is that when you set a Pdef with the same source (object) several times, it doesn't re-schedule it. (this is why I am doing `source = p.copy` above instead of just `source = p`, because that won't schedule it to play again). Generally this isn't a huge problem (because normally in live coding I'm not sending the same object multiple times without modifying it), but I wanted to ask about it.

Just to reply to this separate issue first: the only way for knowing that the source has changed is, well, by the fact that the source has changed. But you can reset the stream by the message `reset`:

```
Pdef(\x).reset;
Tdef(\x).reset;
```

**Comment by totalgee** [comment]
> Just to reply to this separate issue first: the only way for knowing that the source has changed is, well, by the fact that the source has changed. But you can reset the stream by the message `reset`

Thanks, that answers that part indeed... In the case I need to do it, I'll just send a `reset`.

As to the other part (when the old pattern is still running when you change the source, it doesn't wait for the quant boundary but schedules the change as soon as (and *if*) the existing source ends) isn't really a show-stopper for my use case (I'm pretty happy with your existing fixes on this PR ;-). However, if you do have an answer, I'll be curious. Maybe there's a good reason why it's behaving that way...(?)

**Comment by telephon** [comment]
Superseded by #4779. @totalgee could you check that one? Thanks for the detailed reports, very useful indeed!

**Comment by totalgee** [comment]
Thanks, yes, trying it now...

**Pull request closed without merging**
