### PR TITLE
help: GUI examples: update to 3.7

### LINKED ISSUE #560: Most examples in 'examples/GUI examples' do not work
Nearly none of the examples in 'examples/GUI examples' work out of the box. Some work with trivial modifications. Some invoke objects that are not implemented in GUI.qt

These should be removed, or fixed if they are going to be left in - they're the first thing a new user will try, they should work out of the box.

### PR DESCRIPTION
**Pull request by snappizz**
Fix #560. I got distracted from this and lost track of where I was. I think there are 1 or 2 examples remaining. See commit messages for full explanations of the changes to each file.

### CODE REVIEW

**Comment by snappizz** [comment]
There are some examples here that I have no idea how to fix:

- SCImage_animation -- contains unsupported features of Image
- ScopeExample.scd
- SCScope view x,y plot.scd
- strike.scd

I think in the case of the SCImage_animation, we have no option but to delete it. Having non-working examples is a really embarrassing state of affairs.

**Comment by crucialfelix** [comment]
We could add a note at the top of the file that it's broken.

**Comment by telephon** [comment]
I have that: `SCScope view x,y plot.scd` rewritten. I wonder how I can push to your branch now?

**Comment by snappizz** [comment]
You have push access to my topic branch so this should work:

```
git checkout -b topic/update-gui-examples master
git pull https://snappizz/supercollider.git topic/update-gui-examples
git add, git commit, etc
git push https://snappizz/supercollider.git topic/update-gui-examples
```

**Comment by telephon** [comment]
Hm, that (using `git pull https://github.com/snappizz/supercollider.git topic/update-gui-examples`) made a big mess, not sure why.

I'll just make another PR later.

**Comment by gusano** [comment]
> Hm, that (using git pull https://github.com/snappizz/supercollider.git topic/update-gui-examples) made a big mess, not sure why.

@telephon
- `git remote add snappizz git@github.com:snappizz/supercollider.git`
- `git fetch snappizz`
- `git checkout topic/update-gui-examples`
- `git commit ...`
- `git push snappizz topic/update-gui-examples`

**Comment by crucialfelix** [comment]
Really you should install the github extensions:

    git checkout https://github.com/supercollider/supercollider/pull/2329

That's all you have to do !

https://hub.github.com/

**Comment by telephon** [comment]
ok, I've installed hub. 

For `git checkout https://github.com/supercollider/supercollider/pull/2329`

I get:

`error: pathspec 'https://github.com/supercollider/supercollider/pull/2329' did not match any file(s) known to git.`

**Pull request closed without merging**
