### PR TITLE
Keep some windows to front

### PR DESCRIPTION
**Pull request by telephon**
When working with plots, scope, freqscope, meter, server window, node tree, it is often annoying that the window moves behind the text editor when the latter gets focus. 

This brings them to front by default. The behavior can be customized via `Platform.keepWindowsOnTop = false`.

### CODE REVIEW

**Comment by kisielk** [comment]
I think this would be better if it could be toggled per window via a right-click menu or some clickable widget.

Also `keepWindowsOnTop` is kind of a generic sounding config variable. Which windows does it refer to?

**Comment by jamshark70** [comment]
I am fine with this as an option, but, may I ask please to have the default be false? If I have to move windows out of the way only so that I can see what I'm typing, I will not like it one bit.

**Comment by telephon** [comment]
One can customize it by adding it to the startup file. But I'm certainly fine with either default!

The reason why I set it to true:

For those who are new to sc, the hiding is rather more irritating than having to move a window aside or minimizing it.

Again, whatever is preferred.

**Comment by telephon** [comment]
>Also `keepWindowsOnTop` is kind of a generic sounding config variable. Which windows does it refer to?

you are right: suggest a better name?

>I think this would be better if it could be toggled per window via a right-click menu or some clickable widget.

yes, probably. I have no time to look into that. But I'm not very invested in this PR, so …

**Comment by kisielk** [comment]
I think to do this incrementally it would be best to add an "alwaysOnTop" option to the `new` functions of the respective windows. Then you could do this programatically without having to add any options to `Platform`.

**Comment by telephon** [comment]
yes, why not. But mostly we don't open those windows programmatically.

**Comment by kisielk** [comment]
That's true, but it's a pathway to having it be configurable on a per-window basis instead of globally. Then a UI element could be added to the windows which toggles the flag just for that window instance. I just think having it as a global flag on `Platform` is the best way to enable this functionality. That's just my opinion though...

**Comment by brianlheim** [comment]
I agree with @kisielk that adding `alwaysOnTop` args to the respective constructors and having a UI element that can pin a window to the front are really helpful solutions to this problem.

But, I also see the need to configure this globally; it adds value to existing code and could potentially serve as a useful pedagogical shorthand.

There are two things that are problematic about this approach though:
1. the option only applies to certain kinds of windows. the fully descriptive name for the option seems to be `keepWindowsOfConvenienceAnalysisClassesAlwaysOnTop`. i'd really question why that is so much better and handier than keeping _all_ windows on top. in addition, that specificity makes it hard to extend this behavior to classes that are not in the core lib.
2. it's unclear why this should be a property of Platform; this makes it harder to find, and is also not very consistent with the kinds of things that are configurable through Platform.

Platform's documentation says:

> The Platform class (along with its subclasses) handles things which differ between operating systems (mac/linux/windows/...), to simplify cross-platform aspects of SuperCollider.

An option to configure window behavior doesn't seem to relate. It looks like other things like this have been hung there (`makeServerWindowAction`, for example), but they are undocumented and their purpose and justification for being there is unclear to me.

Here's an alternative approach:
- add a class variable to Window called `alwaysOnTop`.
- setting this variable causes all new windows created to be always on top, and may (optionally) cause all existing windows to become always-on-top as well.

Benefits:
- applies across all window types: there is no need to qualify "it only works for certain window types, and not for similar classes that are outside the core lib"
- is where you'd expect it to be: behavior related to windows is controlled by Window

Unclear value:
- doesn't apply to only the specific window types that Julian wants to control

Drawbacks:
- whichever behavior is chosen - changing the state of all windows, or not - someone will probably be unhappy.
- same deficiencies as pointed out by @kisielk above

**Comment by adcxyz** [comment]
Here is a much simpler alternative, as sketch first:
// these names identify introspection windows
~onTopNames = ["Node Tree", "scope", "levels"];
// test whether a new window is meant to be on top
~checkOnTop = { 
	Window.allWindows.do { |w| 
		if (~onTopNames.any { |str| w.name.contains(str) }) { 
			w.alwaysOnTop_(true.postln)
		}
	};
};

//  quick test (in class implementation ~checkOnTop.value happens by automagic)
s.scope; ~checkOnTop.value;
s.plotTree; ~checkOnTop.value;
s.meter; ~checkOnTop.value;


// sketch of an implementation, all in the Window class:
Window { 
	classvar <onTopNames;
	... 
	*initClass { 
		onTopNames = List["Node Tree", "scope", "levels"];
	}
	*addOnTop { |name| onTopNames.add(name); }
	*removeOnTop { |name| 
		var index = onTopNames.indexOfEqual(name);
		index !? { onTopNames.removeAt(index) };
	}
	initWindow { 
		...
		this.checkOnTop;
	}
	
	checkOnTop { 
		if (onTopNames.any { |str| this.name.contains(str) }) { 
			this.alwaysOnTop_(true.postln);
		}
	}
}

**Comment by adcxyz** [comment]
BTW, I fully agree with the premise that most of the introspection-related windows should really be on top by default, and that this should be easily user-configurable.

**Comment by jamshark70** [comment]
Re: Being on by default -- I'd suggest interested parties should live with it for a couple of weeks before deciding. I've certainly had instances where I thought, "Wouldn't it be nice if it...?" but then it was driving me nuts after some time.

I will go along with group consensus (and configure my local environment my way), but group consensus should be based on concrete experience, not speculation.

Other suggestion: make an effort to avoid placing the window over code or lower regions of the post window. That means the language needs to know where the post window is, which it currently doesn't, so maybe it's a non-starter, but... currently, if I pop up a freqscope and it's covering something I want to see, I can quickly switch windows. After this change, I would have to move it or close it to see what's under it. So if you're going to make that harder for users, then it's worth putting some intelligence into the initial position. Make it *really* user-friendly, not one of those half-thought-out things like we usually do.

**Comment by adcxyz** [comment]
yes we should test-live with them :-)
How would we go about finding a good recommended global default layout of screen space for documents, help, post window, and all common introspection windows reasonably out of the way of those? 
It would depend on screen size (which can vary wildly between users), 
and people will want to keep the placement and sizes they are used to, which is fine 
(e.g. having the post window below documents and both very wide) ... 

```
// maybe start with a list of which windows to consider - please add your faves:
s.scope; 
s.plotTree;
s.meter; 
s.makeWindow;
NdefMixer(s);
Pdef.gui;
Tdef.gui;
```

**Comment by kisielk** [comment]
If there is an option added to keep windows on top, it should definitely be available from the View menu in SC-IDE as well.

**Comment by telephon** [comment]
yes my solution is really a bit ad hoc. The key to a general option would be re-identifying windows after they have been closed. 

Then the question is whether this should be valid across recompiles. I tend to be a little wary about such state, but for usability it might be necessary.

**Comment by brianlheim** [comment]
sounds like this might be best hashed out in an issue thread with a solid proposal first

**Comment by telephon** [comment]
yes, sure!

**Pull request closed without merging**
