### PR TITLE
scsynth: set SC_ServerBootDelayWarning as source to scsynth

### PR DESCRIPTION
**Pull request by sonoro1234**
scsynth: set SC_ServerBootDelayWarning as source to scsynth not to libscsynth solves #4992

### CODE REVIEW

**Comment by sonoro1234** [comment]
> can you please make the equivalent change to supernova as well

It seems not necessary as supernova doesnt have internal server

**Comment by brianlheim** [comment]
it would still lead to some confusion if in the future libsupernova were built as a shared lib for another reason, and again it is also more consistent, so please change it while we have the problem and solution fresh in our minds. :)

**Comment by sonoro1234** [comment]
> so please change it while we have the problem and solution fresh in our minds

You are right. Done

**Comment by brianlheim** [comment]
oh, almost forgot -- the libscsynth option will still be broken on macOS due to this - https://github.com/supercollider/supercollider/issues/4992#issuecomment-637951787 . that one is a bit more complicated to handle because the eventloop stuff and disableAppNap are in the same header. i think i know a way to manage it, and i have a mac to test on. i will open a separate PR after this one.

after this PR i'll also add a job to #4906 for Linux+LIBSCSYNTH.

**Pull request merged**
