### PR TITLE
scide - theme: add dracula

### PR DESCRIPTION
**Pull request by gusano**
Some screenshots:

deepinscreenshot_select-area_20180112182859
deepinscreenshot_select-area_20180112182534
deepinscreenshot_select-area_20180112182514

### CODE REVIEW

**Comment by brianlheim** [comment]
wow, it looks very nice! @gusano are you sure using this theme doesn't require a license or attribution of some sort?

**Comment by patrickdupuis** [comment]
Trying this out. @gusano can you confirm what colour of the following text in the Post Window?

`*** Welcome to SuperCollider 3.9.0-rc2. *** For help press Ctrl-D.`

In your screenshots, it appears in white-ish. For me, I get black.

**Comment by patrickdupuis** [comment]
I ❤️ this highlight colour
dracula

**Comment by patrickdupuis** [comment]
For sure MIT is fine, but how do we properly credit the authors? Do we need to include a license file somewhere?

**Comment by gusano** [comment]
@patrickdupuis yes it is white here (no custom theme in `sc_ide_conf.yaml`, `dracula` theme).
About the license, I'd rather have [themes as `*.yaml` files](https://github.com/supercollider/supercollider/issues/3411) before including this (and *Solarized* ones) so our life is easier.

**Comment by Sciss** [comment]
Looks nice. I'm sceptic that copyright applies to the use of a range of RGB values. http://www.colourlovers.com/faq/18/How_can_you_copyright_a_color_palette is quite vague about it, claiming that you could protect "the arrangement of those colors into the rectangular shape" only.

**Comment by brianlheim** [comment]
OK, yet the repository has a license, and we're copying the name here. I think it would be best to contact them just as a gesture of good faith.

**Comment by brianlheim** [comment]
(they may also want to know purely for the sake of adding it to their list of projects using it)

**Comment by brianlheim** [comment]
> About the license, I'd rather have themes as *.yaml files before including this (and Solarized ones) so our life is easier.

@gusano - I'm not sure what you mean by this. Would you still want this to be reviewed/merged as-is or should it be closed and an issue opened for yaml-format themes?

**Comment by gusano** [comment]
@brianlheim I already opened an issue for supporting yaml themes and I think it might take some time to be done.. Reviewing/merging this one is up to you :)

**Comment by patrickdupuis** [comment]
As was discussed on slack, adding this and other themes via separate C++ files requires a little more work than expected. It was decided to simply add the license text above the function that contains the theme's colour palette.

**Pull request merged**
