### PR TITLE
Add WebAssembly (wasm) target for scsynth

### LINKED ISSUE #5224: [servers] porting audio servers for Emscripten/WebAssembly
## Motivation

Prior discussion on mailing list here: https://www.listarc.bham.ac.uk/lists/sc-dev/msg00227.html

> I know main devs were not particularly keen on spending time on an
> scsynth wasm target when I asked last time, but perhaps there are other
> people out there who would be interested in exploring that avenue?
> 
> My personal interest got renewed after coming back to Scala.js for my
> client, and seeing that the JS back-end compiler these days is rock
> solid. I think it would be fantastic to make sound installations or
> sketches work in the client-side browser. I even hacked up a WebAudio
> UGen for my FScape non-realtime DSP system to test the thing -- see
> https://www.sciss.de/temp/soundprocesses.js/ -- but of course this was
> never designed for this scenario, so first of all, that's all JavaScript
> not Assembly, and it has a rather complicated streaming framework behind
> (Akka Stream) instead of the relatively simple scsynth graph processing;
> so no wonder it is not very efficient in CPU terms.
> 
> I believe the sweet spot is to run the client through JS (that could be
> ScalaCollider/SoundProcesses, supercollider.js, or other languages that
> probably can run in the browser, like Python) and the server through
> wasm. Csound people tell me wasm support was quite a good addition.
> 
> Now, as I've stated repeatedly, my C skills are very small, same for
> LLVM and emscripten, and I don't know how entangled the build targets
> for scsynth vs sclang are. But if anyone sees this as an opportunity to
> experiment, I'm happy to try to learn the necessary stuff to start
> building a branch of scsynth against wasm (if it's doable at all -- but
> why not?).
> 
> Feel free to reply to the thread or ping me directly.

- @Sciss 

## Description of Proposed Feature

this thread is mostly for discussing requirements and resources for the implementation.

### PR DESCRIPTION
**Pull request by Sciss**
## Purpose and Motivation

fixes #5224

## Types of changes

- Documentation
- Bug fix
- New feature

## To-do list

- [X] Code is tested
- [X] All tests are passing
- [X] Updated documentation
- [X] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Thank you for this, @Sciss !
I don't have the expertise to do a full review, but I've noticed that submodule updates are part of this PR. Is this intentional? If not, then they should probably be reverted. Feel free to submit a separate PR for submodule updates, if desired.

**Comment by Sciss** [comment]
Not an expert with git submodules: I ran init and update a few times. How would I revert them? And to what commit?

**Comment by dyfer** [comment]
I'm not an expert either... 
I think that in order to check which commit they are at on the develop branch, you could switch to that branch, then go to each affected submodule directory, and use `git status` to check and take note of commit SHA. Then switch back to your PR branch, go to submodule directory again and checkout that commit...
Alternatively you can try deleting submodules and then run  `update --init --recursive` but that sometimes messes things up... see https://github.com/supercollider/supercollider/issues/5306#issuecomment-751402376 (and the rest of that issue, especially if you switched remotes on your submodules)

**Comment by dyfer** [comment]
Should this be closed in favor of #5571 ?

**Comment by dylans** [comment]
> Should this be closed in favor of #5571 ?

Probably, I retained the full commit history from @Sciss , but didn’t have an easy path to merge the updates back into this PR.

**Comment by dyfer** [comment]
Hello @Sciss 
Are you interested in continuing work on this PR?

**Comment by Sciss** [comment]
Definitely interested; I mean I'm using scsynth.wasm. I don't have time resources at the moment, though, so it'll have to wait a bit. I'm happy to comment on questions.

**Comment by dyfer** [comment]
Thanks, got it. Should we close this PR and move the discussion to #5571 (which has all your commits rebased and with resolved conflicts, AFAIU) or should we close that one and keep the discussion here? Just trying to tidy things up a bit.

**Comment by Sciss** [comment]
Yes, makes sense, thank you

**Comment by dyfer** [comment]
> Yes, makes sense, thank you

Which option would you like? Close _this_ PR and move discussion to the other one? Or close the other PR?

**Comment by dyfer** [comment]
(continue conversation in #5571)

**Pull request closed without merging**
