### PR TITLE
cmake: avoid confusing "FATAL" messages if not a git checkout

### PR DESCRIPTION
**Pull request by danstowell**
See https://github.com/supercollider/supercollider/issues/1807#issuecomment-173132001 - build without git is fine, indeed it has to be fine. However, SuperCollider's cmake scripts assume that it is safe to run "git" commands, which causes git to output confusing "FATAL" messages. This fixes that aspect.

I'm proposing merge into master here; @crucialfelix you might also like to comment on whether you'd like it merged into 3.7

### CODE REVIEW

**Comment by crucialfelix** [comment]
it should definitely merge into 3.7

I can merge it myself. thanks so much for the fast fix !

**Comment by crucialfelix** [comment]
oh what a huge mess to try to merge that into 3.7.  

either resubmit the PR by branching from 3.7 and merging it to 3.7 or I will just copy and paste the changes and make a new commit. that's probably easier.

**Comment by crucialfelix** [comment]
I've got it as a new PR thanks

**Comment by danstowell** [comment]
Why close this one? Should merge this into master no?

**Comment by crucialfelix** [comment]
We are merging 3.7 into master after the release.  All changes that happened in the 3.7 branch are valid changes for master.

**Comment by miczac** [comment]
the fatal msg is just postponed. 
git submodule init && git submodule update are not possible without a repo structure (.git) 
this is not part of the tarball/zipfile.
Or am I barking up the wrong tree? (sorry then!)

**Comment by danstowell** [comment]
@miczac thanks - you are half-right.

* Correct the `.git` metadata should not be in the tar/zip
* Correct that `git submodule` commands can therefore not be run in a gitless tree
* However, the cmake script does not attempt to run any `git submodule` commands.
* The cmake script outputs a message to the user if it fails to find the nova-simd library, and yes that message instructs the user to run a `git submodule` command. However that error message will not be output in normal conditions because a tar/zip should have bundled the libraries (the submodules) inside it already.

The fact that github's source downloads don't include the submodules is a bug in github, and even working around that bug is outside the scope of this PR. This PR is about fixing the really awkward problem that *any* non-git source bundle would blurt those horrid "fatal" messages.

**Comment by miczac** [comment]
ok, wrong tree - I realise that this PR is not intended to fix the submodule issue.
But the cmake script itself doesn't attempt but it _asks_ to do so, when issued.
At least here on my OS X:
```
cox:supercollider-Version-3.7.0-beta1 mz$ rm -rf build ; mkdir build; cd $_
cox:build mz$ cmake -G Xcode -DCMAKE_OSX_DEPLOYMENT_TARGET="10.7" -DCMAKE_PREFIX_PATH=`brew --prefix qt5` ..
CMake Warning at /usr/local/Cellar/cmake/3.4.1/share/cmake/Modules/Platform/Darwin-Initialize.cmake:97 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is '10.7' but the matching SDK does not exist
  at:

   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.7.sdk"

  Instead using SDK:

   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk".
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.4.1/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:18 (include)
  CMakeLists.txt:1 (project)


-- The C compiler identification is AppleClang 6.0.0.6000057
-- The CXX compiler identification is AppleClang 6.0.0.6000057
-- Check for working C compiler using: Xcode
-- Check for working C compiler using: Xcode -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler using: Xcode
-- Check for working CXX compiler using: Xcode -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SuperCollider Version: 3.7alpha1
-- Building from branch not_a_git_checkout, commit hash is na
-- Build type defaulting to "RelWithDebInfo"
-- Compiling with Qt GUI
-- Found Pthreads: /usr/lib/libpthread.dylib  
-- building boost libraries manually
CMake Error at external_libraries/CMakeLists.txt:2 (message):
  nova-simd submodule is missing: please run `git submodule init && git
  submodule update' from the toplevel of your git working tree


-- Configuring incomplete, errors occurred!
See also "/Users/mz/Downloads/supercollider-Version-3.7.0-beta1/build/CMakeFiles/CMakeOutput.log".
```

**Comment by miczac** [comment]
ok, wrong tree - I realise this PR is not intended for fixing the submodule issue.

**Pull request closed without merging**
