### PR TITLE
Scide/autocomplete help

### PR DESCRIPTION
**Pull request by vdonnefort**
Here's a new feature for scide. This PR adds help informations about selected class when showing autocomplete menu.

### CODE REVIEW

**Comment by muellmusik** [comment]
This is great @vdonnefort! A few thoughts:

- I notice a slight lag after selecting a class and then pressing '.' (debug build)
- Should this be optional?
- For readability, there is probably the need to respect a little more formatting (e.g. note::). Of course it doesn't have to render like the help files.
- A button to jump to the proper help file in the help browser would be nice.
- Can we have this for method completion too? :-)

I've been thinking about this sort of application ever since we first started discussing scdoc! Thanks!!

**Comment by vdonnefort** [comment]
Hi @muellmusik,

Thank you for your review.

* I noticed it too, but It doesn't seems related to my patch set. When I 
removed them, I still saw the problem. Can you check that?

* Tell me if you prefer to have an option to deactivate this feature.

* What do you mean about "a little more formatting", can you give me an 
example?

* I will have a look on how to update the help browser and your remark 
about method completion.

muellmusik a écrit:

**Comment by bagong** [comment]
This is cool, but it might bet in the way of people who want to write quickly, so I also think it should be optional.
I too notice a significant lag (Release mode) that I never noticed before.
Thanks!

**Comment by jleben** [comment]
If this introduces any lag, it could be solved by displaying the autocomplete window with the main info immediately, and load the help text *into* the window when it becomes available (waiting for it asynchronously, without blocking the main thread).

**Comment by vdonnefort** [comment]
I've just added:
  * a fix for the small lag we talked previously.
  * an option to show/hide this feature.

@muellmusik, can you tell me more about "formating"?

Does anyone has comments about my coding choices?

**Comment by bagong** [comment]
Nice!

**Comment by vdonnefort** [comment]
I've just added:
  * link to the help browser

Open points left:
  * the @muellmusik "formating" remarks for which I need more informations
  * code review?
  * same thing for method completion: It is a bit more complicated, I'd prefer do that into a separated PR later.

**Comment by muellmusik** [comment]
> the @muellmusik "formating" remarks for which I need more informations

Sorry for slow reply, I've been travelling. I mean a little more rendering of the structure, etc.

If you look for instance at OSCdef, the note::...:: is presented as the same paragraph as the description, with no space between. Indeed, paragraph breaks seem not to be respected at all. Server looks pretty bad because of this.

Similarly, subheadings in the description are not rendered, and just get squished in.

Links are presented with the scdoc syntax instead of the link text.

I think this makes it look a little unpolished and needs fixing before it should go in a release.

**Comment by vdonnefort** [comment]
Ok thanks, I saw the problem, I will bring a fix ASAP.

**Comment by vdonnefort** [comment]
@muellmusik This problem is fixed by the last commit.

**Comment by muellmusik** [comment]
> @muellmusik This problem is fixed by the last commit.

Thanks, but I just looked, and not entirely. Subsections are still squished without spacing or formating. Anchor links within the same doc show up with scdoc syntax. You can see this with Server help. code:: tags are also ignored.

This is a great feature though, and thanks for all the work!

**Comment by vdonnefort** [comment]
@muellmusik Fixed! 

Once again, thank you for testing!

**Comment by vdonnefort** [comment]
@muellmusik Fixed!

Once again, thank you for testing!

**Comment by muellmusik** [comment]
Okay, looks very good now!

Two minor things for the future:

- files which do not have an examples section perhaps should not show the 'Examples' heading.
- syntax colourising would be cool.

But I'm very happy to merge this as is.

**Comment by vdonnefort** [comment]
@muellmusik I fixed the Examples title.

I have however no clue for syntax colourising for now

**Comment by bagong** [comment]
Formatting and links are very nice! But now I get this issue: The links to help seem to open a help-page based on the assumption that the/a help-pane is already open (and visible). If that is not the case, indexing help is triggered but no page opens. Also if the help pane is in the background (detached and possibly covered by other windows) - the correct help-page will be loaded, but the pane does not come to the foreground.

**Comment by vdonnefort** [comment]
@bagong, it must be fixed. The last patch force the help dock to focus. Thanks for report

**Comment by bagong** [comment]
Sorry, this changes nothing for me. Does it work for you, did you try it out?

There are two issues:
- opening the help docklet if it is completely closed
- bringing it to the foreground if it is not closed but covered by other Windows

Maybe unrelated but worth a mention: it used to be possible to switch between main window and detached help window (and post Window) by pressing the `switch windows` key on Mac (on the German keyboard its cmd-`, I forgot what it is on the US keyboard) - this doesn't work atm

**Comment by vdonnefort** [comment]
Check if you applied correctly the patch on your side because on mine, 
it works with both case you described :)

Rainer Schütz a écrit:

**Comment by bagong** [comment]
Yea, the commit is in the log...

Are you on Qt4?

I just looked a bit into the new Quarks system and there the same phenomenon: you press a button to open a specific scdoc page and it works if the help pane is open but it does nothing, if it is closed. It also does not bring the help window to the foreground if it is covered by other windows. 
In case of Quarks it is pretty disruptive to the workflow: detach help and put it behind the editor-window. Open Quarks, select a Quark, click classes, click help. Now try to bring the helpfile to the foreground manually. It's not easy and cmd-d seems also not to work in this context. Among sclang-windows, btw, "switch-application-window" works.

**Comment by vdonnefort** [comment]
@bagong, I'm using Qt4.8. I tested it on OSX 10.9 and Ubuntu 14.10

**Comment by bagong** [comment]
Well, then it is likely a quite general Qt5 issue. Would be nice if somebody else on Qt5 compared. Should I file an issue?

Btw, why don't you switch to latest master? Would make sense as your stuff will be committed to a SC version that can only work with Qt5.

**Comment by vdonnefort** [comment]
@bagong I don't think so, it's working on my side using Qt5.

**Comment by bagong** [comment]
Hmmm, mysterious. I use Qt5.4.1 (homebrew) and latest master. And a few of the other pull requests. Would take a lot of time to isolate the problem. I am pretty sure my build is clean...
But the sum of it (same/similar thing happens with Quarks) probably allows to say that the focus/forground-problem is not related to your PR.

**Comment by bagong** [comment]
I am not sure why :), but now it works as expected for me here. Help window comes to front in all cases!

(not in Quarks though)

**Comment by muellmusik** [comment]
Shall we merge then?

**Comment by bagong** [comment]
Just saw that it conflicts with @scztt 's branch topic/ui-refresh in the autocompleter. Maybe wait for him to comment?

**Comment by scztt** [comment]
@bagong - don't worry about it. that branch is a ways from being mergable, and in any case merging the autocompleter changes from that is easy.

**Comment by scztt** [comment]
Actually - merge now, I'm going to mark 3.7-alpha0 in a bit, and it would be good to have this in for feedback :)

**Comment by bagong** [comment]
Just found another issue: help files from locations integrated via LangConfig are not found. This used to be the case for general scdoc too, but has been fixed here: https://github.com/supercollider/supercollider/commit/c48d5d603687a4ae317b5275de61809868b2d866

**Pull request merged**
