### PR TITLE
Cleanup PyrObject.cpp:initSymbols()

### PR DESCRIPTION
**Pull request by brianlheim**
Major changes: 

- Removes ~15~ 19 unused variables in PyrObject.cpp
- Rearrange and label sections of `initSymbols` method for clarity

~Also, if anyone knows why specifically Object, Boolean, Collection, etc. are counted as special symbols above other class names, it would be great to get an explanation on that. Otherwise I'll do some digging on my own.~ Never mind, it's pretty obvious why now.

### CODE REVIEW

**Comment by scztt** [comment]
👍 good change.

**Comment by snappizz** [comment]
> Never mind, it's pretty obvious why now.

As someone who has barely worked on sclang, it's not that obvious to me. Could you elaborate?

**Comment by brianlheim** [comment]
@snappizz Sure! These are all intrinsic classes, so they have special internal function within the language. This includes the basic utility and reflection classes like Object, Method, Interpreter, Routine; "primitive data types" (although SC technically has none) and their superclasses; and array and raw array types. Later on, most (maybe all) of these are used in a global variable `gSpecialClasses` in PyrParseNode to assist with opcode generation. That's my understanding, at least.

Actually, in figuring that out I found a few more unused symbols, so please don't merge yet.

**Comment by brianlheim** [comment]
Okay, ready to merge now if all looks good.

**Comment by snappizz** [comment]
Also looks good to me.

**Pull request merged**
