### PR TITLE
scsynth: port audio control fix to v1 synthdefs

### LINKED ISSUE #3266: Issue triggering old pre-compiled synthdefs in v3.9
I tried to throw  `v3.9-beta1` into Sonic Pi but ran into an issue triggering the pre-compiled synthdefs. This behaviour can be reproduced with vanilla SuperCollider:

```
s = Server.new
s.boot
// 
s.sendMsg( '/d_loadDir', "/Users/sam/Development/sonic-pi/etc/synthdefs/compiled/tmp/" ); 
s.sendMsg("/s_new", "sonic-pi-beep", x = s.nextNodeID, 1, 1);
```

Where the `tmp` directory contains a single synthdef:

https://github.com/samaaron/sonic-pi/blob/master/etc/synthdefs/compiled/sonic-pi-beep.scsyndef

EDIT (Brian): v1 file here: https://github.com/samaaron/sonic-pi/blob/36496b69e7e821562c6608a276b4536229d38250/etc/synthdefs/compiled/sonic-pi-beep.scsyndef

The behaviour I observe is that scsynth silently dies when attempting to trigger the synthdef.

This may be because support for the older synthdef byte code has been deprecated? Sonic Pi's synthdefs are compiled with Overtone, which hasn't yet been updated to support the latest byte code format. 

If support for older synthdefs has been deprecated, it would be nice for SuperCollider to not silently die and instead print a warning explaining that the older byte code format has been deprecated - it should also probably listed as a breaking change in the release notes :-)

### PR DESCRIPTION
**Pull request by brianlheim**
Fixes #3266
In #3063, GraphDef objects had their mAudioMapBusOffsetSize set, but
only when reading v2 files. This commit factors out code common to both
methods. Ideally, reading & initialization would be done in different
places, as this problem conceptually had nothing to do with the synthdef
format being v1.

I double-checked the code pulled from both sections with `diff` to make sure they were exactly the same except for the two added lines from #3036.

Thanks to @samaaron - without his testing this wouldn't have been discovered until release.

cc @snappizz - I've diplomatically tagged this as 3.9.x. I'll let you decide whether to merge this now or later, but as you know my preference is strongly for 3.9.0 given the severity of the flaw.

### CODE REVIEW

**Comment by jamshark70** [comment]
Ah, great! Since I have the reproducer on my machine, I'll test (but it will take a while to rebuild SC).

I think we should put this 3.9.0. If I'm reading it correctly, it's a regression from 3.8.x -- and a crashing regression, no less.

**Comment by snappizz** [comment]
yes, this should go into 3.9.0. this + #3376 will be the two fixes for 3.9.0-rc2.

**Comment by brianlheim** [comment]
@samaaron, would you be OK with us using your sonic-pi-beep file for a unit test?

**Comment by joshpar** [comment]
Nice! Great find everyone

/*
Josh Parmenter
www.realizedsound.net/josh
*/

**Comment by jamshark70** [comment]
Same here, fixed.

**Comment by brianlheim** [comment]
Fantastic, just working on a regression test now. @samaaron's code is MIT Licensed so there is no problem including it here, but I just wanted to ask to be nice :)

**Comment by brianlheim** [comment]
OK. Ready for review. Willing to consider organization of test/files, I kind of added it haphazardly.

**Comment by patrickdupuis** [comment]
You could make use of `setup {}` and `tearDown {}` in your test. It's fine as is though. We need to rewrite pretty much all of them anyway once we decide on how they should be written. 

Passes here as well.

**Comment by brianlheim** [comment]
Great! Unless anyone objects I will merge this later tomorrow.

**Comment by samaaron** [comment]
@brianlheim - Congrats on the fix! :-)

Also, it would be an honour for one my synthdefs to be included :-)

**Comment by brianlheim** [comment]
Yes. The sizeof operator is still being applied to the incorrect type.

**Pull request merged**
