### PR TITLE
import boost-1.58

### PR DESCRIPTION
**Pull request by timblechmann**
and use official boost.endian

### CODE REVIEW

**Comment by timblechmann** [comment]
ping

**Comment by scztt** [comment]
This should be for 3.8? We can pull once 3.7 is out, unless there are important 3.7 bugs that will be fixed by this.

**Comment by timblechmann** [comment]
if `master` is not open for updates, why not create a `3.7` release branch? that's how we dealt with the release process in the past.

**Comment by scztt** [comment]
We can create a 3.7 branch any time - we've held off thus far to concentrate attention on locking down 3.7 fixes, with the intention that we would branch when there were changes that needed to be shared in the main repo and were important enough to justify branching. This is probably a good candidate for that branch, especially if you have further development work to do on top of this.

**Comment by timblechmann** [comment]
4c8eb13 should be one part of the fix for #1635

**Comment by timblechmann** [comment]
fwiw, it would be nice if this could at one point be merged, as it block some further changes (read: bug fixes) of supernova

**Comment by telephon** [comment]
@scztt @timblechmann is it defendable to do this for 3.7.0 or 3.7.x? I don't know enough about the consequences to be able to decide this.

**Comment by danstowell** [comment]
make the 3.7 branch!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by crucialfelix** [comment]
3.7 is made and pushed

**Comment by crucialfelix** [comment]
Don't merge it to 3.7, there is no reason to introduce any risk, there is
nothing that the new boost fixes that is urgent.

**Comment by danstowell** [comment]
This compiles fine for me, and SC boots and makes the noises I expect it to make.

I suggest merging this into master.

(Note: the title of the PR is a bit wrong, since Tim later updated this branch to boost-1.59.)

**Pull request merged**
