### PR TITLE
scsynth: line option to bind to specific address

### PR DESCRIPTION
**Pull request by llloret**
Add a new command option (-B) to bind to an specific address. The idea
is to allow to bind to the loopback port so that it does not ask for
firewall permissions.

The default is 0.0.0.0, to not change the current behaviour.

This PR is for UDP only. TCP to follow.

This is to address #1266.

### CODE REVIEW

**Comment by samaaron** [comment]
Fabulous - this will be very useful for deploying Sonic Pi in schools with Windows :-)

**Comment by llloret** [comment]
Do not test yet, it is not working :(. I will do some basic testing and let you know when it is ready.

**Comment by llloret** [comment]
Ok, this seems to be working nicely now. Using `netstat -anb` on Windows this is what I get launching with `scsynth -u 63000`:
`UDP    0.0.0.0:63000`, which is the default behaviour, listening on all interfaces.

BUT, when I launch with `scsynth -u 63000 -B 127.0.0.1`, then I see:
`UDP    127.0.0.1:63000`, which I understand is the behaviour expected with the new parameter.

So, this is looking good on my side. If someone can have a look on their systems, that would be great.

**Comment by bagong** [comment]
Fab! I will test tonight. We also need to check non-Windows platforms...

**Comment by llloret** [comment]
Further testing on Windows and Linux looks good.

**Comment by bagong** [comment]
I've added milestone 3.7.2 although this is not a bugfix - as a topic of appreciation to our friends from Sonic Pi - who will then not have to distribute a custom build of scsynth. Could we agree on this?

I have for now verified on Windows that starting scsynth with:

    scsynth -u 57110 -B 127.0.0.1

does not prompt for a new firewall rule (which can only be confirmed with admin rights)

Starting it without `-B 127.0.0.1` continues to do so.

It appears to me that this is a pretty ideal solution (a lot nicer than the old sonic pi hardcoded solution) that also has uses for SuperCollider. Would be nice to have the same for sclang, wouldn't it?

(Testing this made me painfully aware that the server cannot be killed with ctrl-c on Windows atm)

**Comment by danstowell** [comment]
My tiny vote: don't backport this to 3.7.x, keep it for 3.8 - it's a fairly significant change that could backfire in various ways. Remember that felix aims to get 3.8 out rather soon :)

**Comment by muellmusik** [comment]
> On 15 May 2016, at 10:31, danstowell <notifications@github.com> wrote:
> 
> My tiny vote: don't backport this to 3.7.x, keep it for 3.8 - it's a fairly significant change that could backfire in various ways. Remember that felix aims to get 3.8 out rather soon :)
> 

+1

**Comment by bagong** [comment]
@samaaron , these are two big votes. It seems your developers build SC anyways, and the release uses bundled binaries? Maybe you could use this PR for your release and return to using SC vanilla once 3.8 is out?

**Comment by crucialfelix** [comment]
Yes, 3.7 is completely closed for new features or API changes. 

3.8 is imminent. It shouldn't be too hard to redo this as a PR for master, no ?

I think this would be great in 3.8, a welcome addition.

**Comment by crucialfelix** [comment]
Though I understand this is a big problem on windows with the firewall permission. So maybe we should squeeze it into 3.7.2 - it certainly doesn't break anything for anybody.

**Comment by llloret** [comment]
Exactly, the idea is that it defaults to the original behavior, so I don't
think it is particularly risky to have it on 3.7.2.

>

**Comment by telephon** [comment]
I think if needed very much now, this can be added to 3.7

As it is expected to be a security feature, someone with some background should give it a close look, please.

**Comment by jweather** [comment]
Sonic Pi does package a custom build of SC currently in order to apply this change, but we would prefer to make use of the release builds wherever possible.

Since it does not change the default behavior of SC, I do not see it as a risky change.  For those without local admin privileges (students) and security-conscious people who are using UDP/OSC on their local machine only, this will be a very useful function.

**Comment by Factoid** [comment]
I'd also like to vote in favour of inclusion into 3.7. For the SP team, it would be significantly easier if we can depend on upstream binaries/packages rather than having to ship custom versions to our users.

For those concerned about the potential for it backfiring, what kinds of scenarios are you envisioning? I might be able to better respond to those concerns if they were better defined.

The default behaviour of SC is unchanged by this patch, and it's been tested as to not disrupt the expectations of established users. 

If it's the lateness of the request in the release cycle, that's understandable. However, the scope of the change and the number of code paths that need to be tested is small, so I very much hope that folks will vote to slip this one in.

**Comment by danstowell** [comment]
The idea that "it does not change the default behavior of SC" is presuming it works exactly as designed on all platforms in all use cases. It doesn't matter what scenarios I am envisaging. I am envisaging the REALLY COMMON case where a patch seems obvious and simple yet breaks something for someone. Waiting for 3.8 is no problem for any of you, it's just a month or two.

Just my 2p, as always. I would defer to felix' decision.

**Comment by samaaron** [comment]
Personally I agree with @danstowell and see no massive need to attempt to fast track this. Let's all be happy and confident it works and take as long as it takes to do this together. 

My vote is for a potential inclusion in 3.8.

**Comment by llloret** [comment]
If Sam is OK waiting, then I guess it's the thing to do.

I will reissue the PR on master, and close the one on 3.7 branch, later
today.

**Comment by crucialfelix** [comment]
Good point dan. 3.8 it is.  Which is in 13 days anyway :)

**Comment by llloret** [comment]
Ok, I have created PR #2095, which is the same, but on master. If you are happy with that, you can pull it, and make it available for 3.8.

**Pull request closed without merging**
