### PR TITLE
scdoc: add a cute little logo to the upper left

### PR DESCRIPTION
**Pull request by snappizz**
untitled

towards #2943. the logo is clickable, lightens when you put your cursor on it, and scales to match the text size (up to 128x128px, which should be sufficient for normal text sizes).

### CODE REVIEW

**Comment by brianlheim** [comment]
This seems to have broken the checkboxes on the Browse and Search pages:

image
image

**Comment by snappizz** [comment]
that's a bug in the browser :/

**Comment by brianlheim** [comment]
you know i've never been able to see the checkboxes there anyway. but i can click them where they should be. tbh i really should have opened an issue for it a long time ago. maybe something you did just now made them visible there

**Comment by snappizz** [comment]
aha, it's #2286

**Comment by brianlheim** [comment]
oh thanks! i will try the fixes you suggested there

**Pull request merged**
