### PR TITLE
Extend UnitTest runAll with arguments for items and posting 

### PR DESCRIPTION
**Pull request by adcxyz**
While working on a specific area of SC, it is useful to test the most relevant subset of unit tests in one go, and the arguments added to runAll allow just that. E.g. for #3486, I kept running combinations of tests like this:
```
fork {
	Server.killAll;
	0.1.wait;
	TestServer_boot.new.test_notifyAndServerBootActions;
	0.1.wait;
	TestServer_clientID.new.run;
	0.1.wait;
	TestServer_clientID_booted.new.run;
};
```
which with this PR becomes 
```
Server.killAll;
UnitTest.runAll([
	"TestServer_boot:test_notifyAndServerBootActions",
	TestServer_clientID, 
	TestServer_clientID_booted
]);
```

### CODE REVIEW

**Comment by brianlheim** [comment]
I think UnitTest needs to be audited and redesigned a bit. We have several issues open for that. I think this approach is a bit haphazard -- it adds timing and posts in a style different from the rest of the class, and I don't think it's a great idea to stuff this into an existing method. Idk, I get that this has immediate benefit for you but IMO it adds to the technical debt of this class.

**Comment by adcxyz** [comment]
OK, fine to keep it only in my toolbox if not generally helpful at the moment, 
Maybe worth revisiting the idea when UnitTest redesign has happened.

**Comment by brianlheim** [comment]
Ok, I do think these are good ideas though (the timing and being able to select a subgroup of tests to run)

**Comment by adcxyz** [comment]
@brianlheim - feel free to reopen the PR and/or propose a better implementation yourself. 
I find it helpful to focus testing on the most-likely-affected areas first, 
and also when writing tests, for tweaking variants for full speed.

**Pull request closed without merging**
