### PR TITLE
[docs - supercollider] - updating readme.me

### PR DESCRIPTION
**Pull request by tmm88**
### [docs - supercollider] - updating readme.me

- This commit aims to fine-tune and adjust the SuperCollider source documentation.
- My goal is to improve the syntax and grammar of the documentation while maintaining the established code quality of the SC3 source.
- In doing so, I will strive to write better code while preserving the essence of SuperCollider.
- The intention is to support the existing code structure and architecture within SuperCollider.
- I am committed to assisting the SC3 community in enhancing SuperCollider as a product.
- My dedication is to gradually refine SuperCollider and contribute to its improvement.

---

- Dieser Commit zielt darauf ab, die SuperCollider-Quellendokumentation zu verfeinern und anzupassen.
- Mein Ziel ist es, die Syntax und Grammatik der Dokumentation zu verbessern, während ich die etablierte Codequalität des SC3-Quellcodes beibehalte.
- Dabei werde ich mich bemühen, besseren Code zu schreiben und gleichzeitig das Wesen von SuperCollider zu bewahren.
- Die Absicht ist es, die bestehende Code-Struktur und Architektur in SuperCollider zu unterstützen.
- Ich engagiere mich, der SC3-Community dabei zu helfen, SuperCollider als Produkt zu verbessern.
- Mein Engagement gilt der schrittweisen Verfeinerung von SuperCollider und seiner Verbesserung.

---

- Этот коммит направлен на уточнение и корректировку документации исходного кода SuperCollider.
- Моя цель — улучшить синтаксис и грамматику документации, сохраняя при этом установленное качество кода SC3.
- При этом я постараюсь писать более качественный код, сохраняя суть SuperCollider.
- Мое намерение — поддерживать существующую структуру кода и архитектуру в SuperCollider.
- Я обязуюсь помогать сообществу SC3 в улучшении SuperCollider как продукта.
- Мое стремление — постепенно улучшать SuperCollider и совершенствовать его.

***Vielen Dank, danke schön. Thank you very much. Большое спасибо.***

Just a small token of appreciation. Nur ein kleines Zeichen der Wertschätzung.
Mit Präzision und großem Interesse an Exzellenz.

[Watch this video on YouTube](https://www.youtube.com/watch?v=l1i0jgP0XB4&list=PL2RcrGlMi-suFYtqrLvilCZvR-FDY8IMa)

### CODE REVIEW

**Comment by capital-G** [comment]
Welcome @tmm88! Honestly, is this coming from an LLM? We welcome any contribution efforts here, but at the same time we would like to have transparency when tools like Co-Pilot, ChatGPT, etc. are used. Also note that putting SC source code into such services is not considered best practice, as the people who wrote said code did not agree to have it consumed or analyzed by such services.

Also, please specify the changes in the PR message, especially why you think this is an improvement over the current status quo. Including non-relevant responses from LLMs as a PR message just puts the effort of reading through the verbose LLM responses on the maintainers, instead of providing a concise statement.

**Comment by tmm88** [comment]
I have no problems assuming that i used an LLM. in fact, i see absolutely no problem using these kinds of things, once they allow us to do way much better work with less effort. if you want to delete my PR then do it. if you want to help me to correct my mistakes, please tell me what i have to improve and i will be glad to fix this

**Comment by capital-G** [comment]
> I have no problems assuming that i used an LLM. in fact, i see absolutely no problem using these kinds of things, once they allow us to do way much better work with less effort.

Well, SuperCollider is an FOSS project and the current models leech from such work while not contributing back which could be seen as a violation of our GPL - for more information on the problems regarding FOSS and proprietary LLMs see https://www.fsf.org/licensing/copilot/on-the-nature-of-ai-code-copilots
While I appreciate that these tools can enable people to code, there must also be respect for the past contributions that have been given/donated under this given license.
 
Although I must admit that there is not yet a consensus on how to handle contributions which originated in such tools.

> if you want to delete my PR then do it. if you want to help me to correct my mistakes, please tell me what i have to improve and i will be glad to fix this

I don't want to delete your contribution, but I told you that you need to give a motivation on how your contribution improves the current status quo - currently it is only a copy pasted reply from an LLM (see https://github.com/supercollider/supercollider/pull/6417#issue-2463954795).
Your commits suggest alternative formulations for the README - I am not a native speaker, but both formulations, the current one and the suggested one, seem valid to me - so why should we replace the current human-written formulation with one written by an LLM?

BTW - it is called `README.md`, not `readme.me`.

**Comment by tmm88** [comment]
done

**Comment by capital-G** [comment]
Thanks - for me the question remains how this LLM generated text improves the current text precisely. I am open for improvements, but I think we could have $n$ alterations of the text. As it is an important text (which current form has been proven over time), I'd personally favor the current human formulated text here.

At the same time, if you are interested in contributing you can take a look at https://github.com/supercollider/supercollider/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 - contributing to these would be considered less *controversial* as touching the introduction text to a project is always delicate.

I'd also appreciate transparency regarding what kind of tools were used here.

I think I said enough, I'd be interested what other think in regards to this PR :)

**Comment by tmm88** [comment]
I will try to play just with text and documentation in this repo as it is what i have done before in sc3 community before i was doing grammarly which proved to work fine, and i got some of my PRs accepted. If people don't want LLMs i can get it, and will focus, as long as possible not to use them, but above all i will write the revised versions of the text myself

vielen danke, danke schon, merci beaucoup. grazie mille

**Comment by tmm88** [comment]
Would it be relevant to translate the supercolllider docs to other languages as a Qauark? Would it be more valuable to create a Quark that includes my own SuperCollider tutorials and examples, showcasing the techniques I've developed over the years? Additionally, if translating the documentation is worthwhile, which languages would be most beneficial?

---

Wäre es relevant, die Supercolllider-Dokumente in andere Sprachen wie einen Qauark zu übersetzen? Wäre es wertvoller, ein Quark zu erstellen, das meine eigenen SuperCollider-Tutorials und Beispiele enthält und die Techniken zeigt, die ich im Laufe der Jahre entwickelt habe? Und wenn die Übersetzung von Dokumentation sinnvoll ist, welche Sprachen würden dann am meisten davon profitieren?

---

Будет ли уместно переводить документы суперколлайдера на другие языки, такие как Qauark? Было бы более ценным создать Quark, включающий мои собственные учебные пособия и примеры по SuperCollider, демонстрирующие методы, которые я разработал за эти годы? Кроме того, если перевод документации достоин действительности, какие языки выиграют больше всего?

**Comment by telephon** [comment]
I think we should keep the readme as it is. If there are specific changes that are motivated by content, this is ok, but this doesn't help much. We try to keep automatic changes to a minimum if we can.

**Pull request closed without merging**
