### PR TITLE
Add missing method 'recordingsDir'

### PR DESCRIPTION
**Pull request by patrickdupuis**
This PR adds the already documented but missing class method 'recordingsDir' to Platform.sc. I also added documentation for the method 'userHomeDir'.

### CODE REVIEW

**Comment by brianlheim** [comment]
Sorry, kind of a nuance with SC but the method you added is actually already defined [here](https://github.com/patrickdupuis/supercollider/blob/74056fc5aa85f01dd518a78a8d38ae76bd7e6ddb/SCClassLibrary/Platform/Platform.sc#L7) with `var <>recordingsDir` (`<>` meaning the getters and setters are automatically generated). The new method can keep the same code, but needs to be a class method `*recordingsDir` rather than instance `recordingsDir`. Also, that means the documentation is missing an entry for that new method.

**Comment by brianlheim** [comment]
Also, note this is a fix for #2713.

**Comment by patrickdupuis** [comment]
Thanks! I wasn't certain about the `*`

There is already some documentation for `recordingsDir` [here](https://github.com/supercollider/supercollider/blob/772bdd6946a7253390ba0b1b23eb3adc0acb97ea/HelpSource/Classes/Platform.schelp#L121).

**Comment by brianlheim** [comment]
NP, and thanks for taking care of it.

> There is already some documentation for recordingsDir here.

Yes, but if you'll notice, that's in the instancemethods:: section; there should be a corresponding entry above in classmethods::

**Comment by patrickdupuis** [comment]
great! do you want @jamshark70 to look at it since he is the one who suggested the improvement?

**Comment by brianlheim** [comment]
I think @jamshark70 mentioned in the issue that there are other methods in the Platform interface that may benefit from the same treatment. I didn't see any, but didn't look very hard. With methods as innocuous as this, I think we've agreed as a community that one test/review is fine.

**Comment by patrickdupuis** [comment]
ok. i didn't notice any other methods either.

**Pull request merged**
