### PR TITLE
Rest asEvent returns Event.silent fixing #5853

### PR DESCRIPTION
**Pull request by olafklingt**
## Types of changes

- Bug fix

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

### CODE REVIEW

**Review by telephon — APPROVED** [review]
It makes sense semantically. I'd be a bit more confindent if we had a few tests or some lines of examples.

**Comment by dyfer** [comment]
@telephon is it okay to merge this as is? (without tests)

**Comment by telephon** [comment]
could you post some informal tests (not UnitTests) to double check?

**Comment by dyfer** [comment]
> could you post some informal tests (not UnitTests) to double check?

me? I don't really use patterns so I'm not the best person to test this.

@olafklingt would you be able to post some examples to observe this change in action?

**Comment by dyfer** [comment]
@telephon is it okay to merge this?

**Comment by telephon** [comment]
OK, here is an example:
```supercollider
p = Pseq([(note: 7, dur: 0.01), Rest(0.01)], inf);
q = Pfindur(0.1, p);
Pevent(q).asStream.all;
```

**Review by telephon — APPROVED** [review]

**Pull request merged**
