### PR TITLE
Make ServerStatusWatcher return sampleRate as Integer

### LINKED ISSUE #4107: ServerStatusWatcher now returns sampleRate as Floats
Environment
-----------

* Your SuperCollider version: 3.10.0-beta2
* Your operating system and version: macOS 10.13.5 (17F77) 
SHA: 937a2615bf30208e09aaa93ecd3b1d13aa862950
branch: develop

Steps to reproduce (for bugs)
-----------------------------

```supercollider
//in 3.9.3 release
s.boot;
s.sampleRate; // --> 44100 (an Integer)

//in 3.10.0-beta2 @937a261
s.boot;
s.sampleRate; // --> 44100.0  (a Float)

```

Expected Behavior
-----------------

`s.sampleRate` should IMO return integer values. E.g. ATK switch statements for kernel selection depends on it.

Current Behavior
----------------
The latest version return sample rate as floats. I have tried to look into the ServerStatusWatcher but could not find any change there. Has anything changed in the status message that is sent from the scsynth?

### PR DESCRIPTION
**Pull request by blacksound**
Purpose and Motivation
----------------------
Fixes #4107 

Types of changes
----------------
This PR ensures that ServerStatusWatcher returns sampleRate as Integer. Please see issue #4107 for more information about this change.

Checklist
---------

Remaining Work
--------------
Should I make a test for this?

### CODE REVIEW

**Comment by blacksound** [comment]
I'm thinking that programming to the Server and ServerStatusWatcher interfaces is a good practice to keep consistency in general class lib. The interface for Server-sampleRate has been returning Integers. If it is necessary to be able to return the Float values we should rather make a separate sample rate Float value getter.

**Comment by telephon** [comment]
My guess is that nothing has changes between the server and sclang (that is, the server has always sent the sample rate as a float). The change has been that whole number floats now post the `.0` at the end to make sure that when you interpret them again, they become floats and not ints.

There have been some cases where some code relied on the printing representation of floats.

**Comment by blacksound** [comment]
Ah, I see you point @telephon ! 
The problem arises for all people that use `s.sampleRate.asInteger`. I encountered it working with the ATK Quark.
So the type interface for ServerStatusWatcher has not changed directly, but indirectly, as people may use the returned value for switch statements. In the ATK situation, this value is used to find the matching kernel file from a specific folder that can be named e.g. `kernels/44100/hello.wav'.

A similar issue is brought up by @patrickdupuis in #4110.

This is something that people should know, because although it may be a breaking change for some people using `s.sampleRate.asString`

**Comment by blacksound** [comment]
To be more precise this change actually is a breaking change for the Float-asString method, since it now will return a different result for values without decimals.

**Comment by blacksound** [comment]
Ah found that @jamshark70 already was aware of this. https://github.com/supercollider/supercollider/pull/3585#issuecomment-393727409

Closing this PR now, and will push PR to ATK instead.

**Comment by telephon** [comment]
Thank you, yes this is better. Sorry for the troubles, but the float as string method was simply not correct before.

**Comment by blacksound** [comment]
No troubles at all @telephon , thanks for the help.
Good to track down what changed and it's a good thing to smoke out thing like these.

**Pull request closed without merging**
