### PR TITLE
HiDPI fractional scaling: remove rounding to int

### LINKED ISSUE #4844: [HiDPI] QcCanvas doesn't handle fractional scaling
## Environment

* SuperCollider version: 3.11.0-beta1 (it was like this in 3.10 and 3.9 as well)
* Operating system: Arch Linux
* Other details (Qt version, audio driver, etc.): Qt 5.14

## Steps to reproduce
run: 
```
QT_AUTO_SCREEN_SCALE_FACTOR=1 QT_SCALE_FACTOR=0.75 sclang
```
And exec:
```supercollider
Env.perc.plot
```

## Expected vs. actual behavior
Expected: Window and Plot have the same size
Actual: Plot is smaller

Pics and fix idea [on this forum post](https://scsynth.org/t/problem-with-high-resolution-screen-display/823/12)

### PR DESCRIPTION
**Pull request by elgiano**
## Purpose and Motivation

Fixes #4844 

## Types of changes
- Bug fix

## To-do list

- [x] Code is tested (ctest + existing UnitTests)
- [x] All tests are passing (ctest + existing UnitTests)
Specific testing would require changing the user's HiDPI settings, which can't be done from sc
- [ ] Updated documentation (not needed IMO)
- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
@elgiano thanks for this! just want to note that appveyor CI failing is not your fault, it's an unrelated issue that i'm working to resolve.

**Comment by elgiano** [comment]
I'm adding Qt::AA_EnableHighDpiScaling in two places: one for sclang and one for scide.
This is equivalent on Linux to setting QT_AUTO_SCREEN_SCALE_FACTOR or the new QT_ENABLE_HIGHDPI_SCALING env vars (but it is overridable by them: i.e. you can cancel its effect by setting QT_AUTO_SCREEN_SCALE_FACTOR to 0)

The benefit (on Linux) is that scide and sclang figure out how to scale themselves automatically, without me needing to set any env var (which I can still do if I want things different).
I think it's a good feature, and hope it could maybe do something regarding #2442 on Windows, as it automatically scales widgets and HelpBrowser text (on my machine!).

@dyfer lets set up something on slack and test it out?
@brianlheim one question: do you think it is best to include these flags in this PR (maybe renaming it) or to create a new one?

**Comment by brianlheim** [comment]
@elgiano if you're going to do more work/testing on this it would be good to split it into 2 PRs at this point before it gets messy :)

**Comment by elgiano** [comment]
@brianlheim I agree. 
Even if for now it looks like a small addition, I will move those flags and further experimentation/testing to another PR

**Comment by elgiano** [comment]
> (and possibly Linux?)

Yes, Linux is actually the system I originally addressed in #4844 and this PR. And #4850 makes fractional scaling easier (more automatic, still customizable) on Linux too.

**Comment by brianlheim** [comment]
looks good, thanks!

**Pull request merged**
