### PR TITLE
scsynth: denormal handling in PortAudio and Jack

### PR DESCRIPTION
**Pull request by sonoro1234**

### CODE REVIEW

**Comment by telephon** [comment]
I would like to merge it, but it is not my expertise and I can't test it. Someone else, please?

**Comment by sonoro1234** [comment]
see SC_CoreAudio.cpp:1322 
sc_SetDenormalFlags is set in the audio_thread for macosx audio driver
the same should be done in the other audio drivers

**Comment by sonoro1234** [comment]
for testing #1656 Synth can be used

**Comment by sonoro1234** [comment]
@timblechmann , @jleben ,
or @scztt  are able to confirm that as they have done commits to the relevant files

**Comment by timblechmann** [comment]
it looks correct and important ... semantically, supernova is doing exactly this, though the implementation differs a bit

**Pull request merged**
