### PR TITLE
Topic fix server options num channels alternative

### PR DESCRIPTION
**Pull request by telephon**
This is an alternative to #2760.

Pros: shorter code, less maintenance.
Cons: less convenient

### CODE REVIEW

**Comment by telephon** [comment]
opinions on this? I find this version better.

**Comment by jamshark70** [comment]
I don't have a very strong opinion on exactly what the API ought to be, but I have a feeling this approach might be more reasonable. To be entirely honest, the current audio-bus-channels interface in ServerOptions mystifies me -- too many variables and too many potential interactions between them.

BTW I overlooked this one earlier, but I just saw a question on the mailing list where a user was confused that audio bus number 150 didn't work... then I saw that ServerOptions currently has a conflict: the default numAudioBusChannels is 1024, but numPrivateAudioBusChannels = 112, so, by default, the server boots with 112 private + 2 input + 2 output = 116 channels (and even here, 112 is legacy from the time when we defaulted to 8 in and 8 out channels: 112 = 128 - (2 * 8)).

Note `-a 116` here (!).

```
s.options.numAudioBusChannels
-> 1024

s.options.asOptionsString
->  -u 57110 -a 116 -i 2 -o 2 -b 1026 -m 131072 -R 0 -C 0 -l 1
```

So the current situation is misleading for users, and I would be in favor of merging this PR, if for no other reason than to clean up that mess.

**Comment by scztt** [comment]
1. I somewhat prefer the pattern used in the other PR, where errors are thrown as soon as the set happens, and inconsistent values CAN'T ever be set. This seems drastically better than allowing bad settings and then reporting much later during server boot.

2. Why not simply make each of the channel counts straight setters, and determine the -a option by adding them all together? The only thing this prevents is a one-shot way to fix the *total* channels on the server. This is an edge case, and it seems acceptable to say - if you care about having exactly 512 audio buses for resource reasons, do the math to allocate yourself. This would only ever increase the available channels, so shouldn't have an effect on existing code.

3. Another way to get radically unexpected results:
`s.options.maxLogins = 8;`
This seems harmless, but actually limits your available audio channels to `numAudioBusChannels / 8`. Eesh!

**Comment by telephon** [comment]
I'd suggest the following: 
1. merge this PR (which doesn't check). You can do the check at any time `s.options.checkConsistency` Perhaps this method should return a boolean.
2. over time, extend the `checkConsistency` method to cover more possible interactions.
3. call `checkConsistency` at the appropriate moments in the code.

This makes it easier to reason about the whole problem and locates it in one method. There is a bit of overhead in (3), because for every thing it checks all possible inconsistencies, but it saves a lot of human overhead.

**Comment by telephon** [comment]
@scztt what do you think about the above procedure?

**Comment by brianlheim** [comment]
I agree with @scztt, exceptions should be raised when trying to set values. That way we don't have to have a `checkConsistency` method at all, and `ServerOptions` doesn't depend on `Server` for raising exceptions about itself.

**Comment by telephon** [comment]
OK – I'm fine with testing on setting. 

But I'd really prefer to have all the checks in one method. This makes the whole thing easier to read.

**Comment by jamshark70** [comment]
Could someone describe the expected behavior with this PR?

I get nervous when we're starting to talk about throwing errors in multiple places, while at the same time I had said two months ago that I was confused about the changes and we *still* don't have a written summary of the cases that should not throw errors and the cases that should.

FWIW I don't think writing a spec has to be a waste of time. One way to do it is to update ServerOptions.schelp, which you would have to do anyway -- the PR is not ready to merge without documentation. It's a valid suggestion to write the help now, instead of at the last minute.

**Comment by brianlheim** [comment]
> Could someone describe the expected behavior with this PR?

It seems to be:

1. don't allow the client to set any of `numInputBusChannels`, `numOutputBusChannels`, `reservedNumAudioBusChannels` such that their sum is greater than `numAudioBusChannels`. In other words, `ServerOptions` should guarantee that `numAudioBusChannels`
2. Don't allow the client to set `reservedNumControlBusChannels` to be greater than `numControlBusChannels`
3. Don't allow the client to set `reservedNumBuffers` to be greater than `numBuffers`.
4. Calculate `numPrivateAudioBusChannels` on the fly instead of using a state variable.

But some points that are unclear to me are:

1. *What is the definition of `numPrivateAudioBusChannels`?* My guess: the number of audio channels that are not either input or output that are desired by the client. Since the defaults for `input`, `output`, and `total audio channels` are 8, 8, 128, this would explain the default setting of `numPrivateAudioBusChannels` as 112. It would also explain the behavior of the `firstPrivateBus` method, which just returns `numOutputBusChannels + numInputBusChannels`.
2. *What are the definitions of the three `reservedNumX` variables?* My guess: the client may want to request a certain number of busses/buffers to go unused by automatic allocation. These variables provide a means to do that, and are not communicated in any way to scsynth.

If that's right, then

- the relevant undocumented methods should be documented
- we need to discuss the default internal values for audio bus ranges, because the documentation, scsynth's documentation/behavior, and the default values provided by `ServerOptions` are not consistent.

The defaults are:
- `numAudioBusChannels`: 1024 in `ServerOptions` & doc, 128 in scsynth. This variable is not passed to scsynth anyway under the current implementation.
- `numInputBusChannels`: 2 in `ServerOptions`, also 8 in `ServerOptions` in `asOptionsString` and as the default value for `numInputBusChannels_`. 8 in `scsynth`.
- `numOutputBusChannels`: same as `numInputBusChannels`.
- `numPrivateAudioBusChannels`: 112 in `ServerOptions`; not documented.

I would also recommend removing the "default" checks in `asOptionsString`. They are unnecessary and more importantly only make it likely for silent bugs to be introduced in the future if `scsynth`'s defaults change.

> But I'd really prefer to have all the checks in one method. This makes the whole thing easier to read.

FWIW it's easier for me to read code that performs one-line checks on incoming data at the call site, and not in a separate six-line external method, because I can tell exactly which checks are necessary and relevant. If the requirements for state consistency were to grow (which they very well might, judging from this discussion), a `checkConsistency` method could quickly become a tangle of conditionals.

**Comment by telephon** [comment]
Hm, if there is an agreement about the last point, the #2760 is the right PR to document and merge.

**Comment by muellmusik** [comment]
> What are the definitions of the three reservedNumX variables? My guess: the client may want to request a certain number of busses/buffers to go unused by automatic allocation. These variables provide a means to do that, and are not communicated in any way to scsynth.

Sorry late to this party. I'd also be curious as to the use case for them. Is there a clear need (which couldn't be avoided by a slight modification of user code)? I'm generally suspicious of things that seem to mix the allocators and hard coded or reserved blocks, so just curious what the idea is.

**Comment by telephon** [comment]
I've poked around in emails from 15 years ago, but couldn't find an answer. (By the way: will we be able to read discussions like this one here on github in the year 2032?)

But I think I remember that we wanted to support at the same time the use of explicit bus numbers in osc messages (think of it as interpreter variables to say, e.g. `s.sendMsg(\s_new, \default, -1, 1, 1, \out, 5)`. Not everyone likes the object-style for this, and using one shouldn't break the other.

**Comment by muellmusik** [comment]
> In other words, when you work in this style, you should still be able to use parts of sclang that depend on objects internally.

Well, perhaps I'm in the minority here, but from the dev side I've always been concerned that mixing object and message style created a lot of unnecessary complexity, and that it was better to say we provide this high level interface, if you use that you work in this way, if you want the raw numbers, then stay away from this stuff. I'm not sure I've seen a clear case for why mixing is an advantage (though there could be one).

That said, I do think how to make your own stuff that works in object style is undocumented and only implicitly laid out. That's bad, as things could break. It would be nice to lay this out explicitly and commit to an API for this. Mostly that would be just explaining the allocators.

**Comment by telephon** [comment]
Yes, this alternative route should be documented. 

I would argue for keeping this option. Imagine you were someone who would want to use just plain numbers: you would have to stay away from almost every other bit of code, and you'd have to inspect the code in detail to see whether it interferes with you or not. 

Better make a "free" range explicit, which you can take care of yourself. If you run over it it's your fault and you can inspect your own code. It's just an offset after all.

**Comment by telephon** [comment]
Of course, there is also a workaround for the offsets.

```
(
ServerBoot.add({
	"reserving some busses --------------- ".postln;
	Bus.audio(Server.default, 24);
	Bus.control(Server.default, 42);
}, Server.default);
)

s.reboot
```

I would have thought: but no, it doesn't work:

`Bus.audio(Server.default, 1) // Bus(audio, 0, 1, localhost)`

This is because the allocators are reset after `ServerBoot` is called.

**Comment by muellmusik** [comment]
> This is because the allocators are reset after ServerBoot is called.

But isn't that why there's ServerTree?

**Comment by telephon** [comment]
tree is after freeAll, after cmd-period

**Comment by muellmusik** [comment]
> tree is after freeAll, after cmd-period

Yes, but runs after boot as well of course. You could check if it had already happened once, or maybe there should be a *once method. Is there an idea behind why ServerBoot happens before the allocators or?

**Comment by adcxyz** [comment]
Hi, 
for immediate fix of the inconsistency, can we please commit ASAP: 
var numPrivateAudioBusChannels = 1020; 
just so we have a reasonable state until this discussion and 2760 reach agreement :-)
thanks, adc

**Comment by adcxyz** [comment]
Some general design considerations on ServerOptions, 
hopefully useful towards the spec definition suggested by @jamshark70 : 

1. ServerOptions configures the server program when booting
this is useful as a separate object, and easy to understand and use:
configure, then boot; once running, don't touch settings, or you lose info.

2. Server object and/or its options know the current state of the running server
? Where and how to keep the current running server's config?
A. One could lock the options settings in s.options once s is booted
B. or copy them as immutable state into the server object.
C. the server may have made changes relative to the config string:  
samplerate, device, diverging defaults between server program and ServerOptions (anything else?)
-> Have the server program send its full active config on request. Would be accurate, and could be kept as lookup-only state in the server object. 
A and B are simple, C is more work, but best 

3. Convenience info in ServerOptions

**Comment by adcxyz** [comment]
3. Sanity of individual config settings: 
Currently most settings are wide open, one could set samplerate to -inf if desired. 
Which of them would need to be protected, all number values?
Should they be constrained to min/max values? 
Rather than throwing errors, this could just be warnings when out of legal range,
and fixing it by clipping into legal range.

4. Complexity and interaction between settings, esp. numAudioBusChannels
I would prefer simplifying these as much as possible:
calculate numPrivateAudioBusChannels, and remove its setter, 
then it is always consistent with minimal code. 
for symmetry, one could add a method 
numPublicAudioBusChannels which returns numIns + numOuts.

5. convenience methods that also live in ServerOptions:
	var <>initialNodeID = 1000;
	var <>remoteControlVolume = false;

	var <>reservedNumAudioBusChannels = 0;
	var <>reservedNumControlBusChannels = 0;
	var <>reservedNumBuffers = 0;
	var <>pingsBeforeConsideredDead = 5;

	var <>recHeaderFormat="aiff";
	var <>recSampleFormat="float";
	var <>recChannels = 2;
	var <>recBufSize = nil;

None of these concern the server program, only the server object:
initialNodeID is used for setting up the NodeIDAllocator, 
remoteControlVolume is a settable flag used in the server object only, 
the record settings could go into server.recorder, where they are used.

google finds only 2 uses each of reservedNumAudioBusChannels, 
reservedNumControlBusChannels, reservedNumBuffers:
github/Server.sc, and doc.sccode.org, nothing else - so no published uses of it. 

Maybe we can drop these, and tell users how to reserve bus and buffer ranges? 
// right after booting server, and/or in initTree? :
~resAudioBus = Bus.audio(s, numA2ToReserve);
~resControlBus = Bus.control(s, numC2Reserve);
~resBufs = numBufs.collect { |i| Buffer.new(s) };

**Comment by adcxyz** [comment]
5. Documentation - 
ServerOptions.schelp should have more general explanation,
and should group the  inst vars by:

server program options - set before booting:
* Resources with dynamic allocation:
Busses, Buffers, NodeIDs 
* hardware related settings
in/out/device, samplerate, hardwareBufferSize, 
input/outputStreamsEnabled
* synthesis resource settings 
blockSize, maxNodes, maxSynthDefs, memSize, etc

* Convenience settings for the server object
all the rest goes here ;-)

**Comment by muellmusik** [comment]
One thing to bear in mind is that a great advantage of separate ServerOptions is the ability to pass them around, either for multiple servers or clients. We need to retain that.

An ability to query a server for its config, and construct an accurate ServerOptions from the reply would be great, and would simplify the client case. It could be part of the /notify reply, or separate.

**Comment by telephon** [comment]
This thread is getting confusing, maybe we can find some kind of general agreement? I'd prefer to separate a fix from a larger refactoring.

So I suggest, as a first step, to merge #2760. It seems mostly consensual, reading the current thread.

Then we could go about putting together the above specs and an implementation.

**Comment by vivid-synth** [comment]
For the curious, private audio bus channels are defined here:
HelpSource/Tutorials/Getting-Started/11-Busses.schelp

I couldn't find a definition of private audio bus channels anywhere at all until I grepped through the source. I didn't see any mention in either searching the docs or in the SC Book.

I'd support either this proposal or #2760 . I agree that the ```-a 116``` behavior that @jamshark70 saw is very unexpected (and in fact I think I may have been the cause of that confusion, as I was the one to bump ```numAudioBusChannels```, having no idea I'd need to bump ```numPrivateAudioBusChannels``` for it to "take")

**Comment by telephon** [comment]
the discussion here is important, let's keep it in projects for now. But the outcome is in favour of #2760 or a variant, as far as I can see, so I close this.

**Pull request closed without merging**
