### PR TITLE
help: improve docs for Comb* and Delay*

### PR DESCRIPTION
**Pull request by snappizz**
Should be mostly uncontroversial. I also added notes that "delay" usually refers to what we call a comb filter, maybe unnecessary?

### CODE REVIEW

**Comment by brianlheim** [comment]
I don't know if it's documented anywhere, but do we have a rule/preference about 80-column formatting in help docs? I prefer that style, but I see it going both ways all the time.

**Comment by telephon** [comment]
It is a bit strange that github doesn't soft wrap. Fixed wrapping, everyone has to use the same width. Isn't it better to leave that to the editor app? (really just asking)

**Comment by brianlheim** [comment]
I don't really want to get too deep into the arguments for/against, I'll just say that it's really annoying for me when anything I have to open in a text editor (i.e. not in-browser) has 300-character long lines. The worst approach IMO is mixing styles in the same file, which I'm sure I'm guilty of as well. I just remember that someone on this project asked me not to remove newlines from a help doc paragraph. (might have been @jamshark70?)

**Comment by bagong** [comment]
Can't you set soft-wrapping on?

**Comment by telephon** [comment]
I don't know how. When I use split diff views, it is soft wrapped though.

**Comment by bagong** [comment]
Haha, I was asking Brian and thinking of an editor, never mind. On Github it's wrapped in raw view too ;)

**Comment by brianlheim** [comment]
I would just like to decide on one convention and stick with it. Over and beyond the arguments for and against, consistency is my greatest concern. If this is being too formal again, that's fine, but I just wanted to bring it up so I can know where we stand. I like not having to deal with the slightly different wrapping behavior that happens across the editors I use (char-based vs. word-based is slightly maddening), but again, I'm not looking to enforce that on anyone.

**Comment by bagong** [comment]
I also prefer linebreaks at 80. But I also think we shouldn't spend too much time with these recurring issues (spaces vs tabs the other one) because whatever we decide it's not going to work anyways. We're not there yet. Rejecting a PR because of wrong line breaks is inefficient. Let's try the magic long term method: positive reinforcement ;)

**Comment by bagong** [comment]
https://www.youtube.com/watch?v=heIGbOA6Ykw

**Comment by brianlheim** [comment]
> Rejecting a PR because of wrong line breaks is inefficient.

Where have I said anything about rejecting this PR? I just want to know what format we prefer, because I do care about this and will submit changes in that style, and I believe that other people will be open to similar recommendations if we make them available. Since most files in this repo are at 80-col, seems like I'll be doing mine in 80-col.

**Comment by jamshark70** [comment]
Better than positive reinforcement would be a hotkey in the editor that rearranges line breaks for the paragraph containing the cursor, much like M-q (alt-q) does in emacs.

If you want people to hew to a style convention, make it easy to do.

**Comment by brianlheim** [comment]
Definitely! This could easily automated at some point in the future to make the existing docs consistent.

**Comment by brianlheim** [comment]
Anyway! The actual PR looks good, thanks @snappizz!

**Comment by vivid-synth** [comment]
For the record, I'm also happiest when I see 80-col

**Pull request merged**
