### PR TITLE
More help documentation updates

### PR DESCRIPTION
**Pull request by llloret**

### CODE REVIEW

**Comment by bagong** [comment]
Okay to merge, no? Did someone cancel the builds manually? Not that these checks make much sense for changes to help, but it makes the outcome look dangerous ;)...

**Comment by gusano** [comment]
@bagong I restarted travis builds

**Comment by llloret** [comment]
I don't think this can break the build, it is just some spelling and typo cleaning on the help files.

**Comment by gusano** [comment]
@llloret This is just good practise. It doesn't cost to wait a couple of minutes before merging ;)

**Comment by llloret** [comment]
@gusano, of course, that's wise.

**Comment by bagong** [comment]
Great move!

**Pull request merged**
