### PR TITLE
sclang: clean up backtraces

### PR DESCRIPTION
**Pull request by kisielk**
For #2924 

I'm open to suggestions for better naming of things since it seems pretty verbose. On the other hand it's not settings people will need to tweak very often, if ever.

Still needs some documentation, which I will add once everything else is settled.

With this applied, a backtrace looks like this now:
```
sc3> nil.foo
ERROR: Message 'foo' not understood.
RECEIVER:
   nil
ARGS:
CALL STACK:
	Object:doesNotUnderstand
		arg this = nil
		arg selector = 'foo'
		arg args = [*0]
...
^^ The preceding error dump is for ERROR: Message 'foo' not understood.
RECEIVER: nil
```

### CODE REVIEW

**Comment by brianlheim** [comment]
FYI, in #2861 I reworked some of SC_LanguageConfig to avoid global variables and duplicate hard-coded strings, so I think there would be merge conflicts between this PR and that one. Idk about you but I considered moving gPostInlineWarnings to be a private member of SC_LanguageConfig a design improvement, and I hope we could do the same with any new language config elements.

**Comment by kisielk** [comment]
Definitely it's better as private member variables, I was just following the existing convention. Once that's merged then I'll move the config over from globals to that.

Can we add a WIP / do not merge label to this PR? I don't think I have the permissions to do that.

**Comment by telephon** [comment]
your example is a very basic one. How does the backtrace look like when there is a longer chain of calls between the command line and the exception ?

**Comment by kisielk** [comment]
@telephon there's some further discussion in the ticket (#2924), I don't want to split the discussion in two different places. If you have some examples of longer backtraces with more things in the chain, please post them there

**Comment by jamshark70** [comment]
Also don't forget "protected backtraces," most of which are printed from within the class library, not the c++ backend. (The backend prints the trace up to the point of using an error-handling method; the library prints the part of the trace that happened under the influence of the error handler.)

```
protect { 1.flarghle };
```

I don't remember if the language-side stack dump already omits error handling frames, though. But it's important to note the case anyway, since the discussion so far assumes that all stack trace printing happens in one place.

I guess it's a valid question whether those could be unified (way out of scope of this PR). I wouldn't know how, though; the stack frame data are bifurcated in memory.

**Comment by brianlheim** [comment]
@kisielk - this can move forward now that #2861 is merged!

**Comment by muellmusik** [comment]
@kisielk Just chasing this up, as it's been dormant for 11 months. Personally I'm a bit concerned about limiting the depth of backtraces.

**Comment by jamshark70** [comment]
> Personally I'm a bit concerned about limiting the depth of backtraces.

Seconding that. I reread the original thread and it talks about filtering out some specific method calls, but you can't assume everything will be within a given stack depth. (In my chucklib-livecode parser, the stacks can get cry deep.)

**Comment by brianlheim** [comment]
i think it's fair to say this has gone stale. @kisielk feel free to open it and respond to concerns if you have the time and desire

**Pull request closed without merging**
