### PR TITLE
fix typo in ProxyMixer help

### PR DESCRIPTION
**Pull request by dmorgan-github**
Purpose and Motivation
----------------------
A typo in a code example in the help file for ProxyMixer does not cause an error but does not result in the expected behavior.

Types of changes
----------------
- Documentation (non-code change which corrects or adds documentation for existing features)
Fix typo to change variable from "n" to "m"

Checklist
---------

- [ ] All previous tests are passing
- [ ] Tests were updated or created to address changes in this PR, and tests are passing
- [ ] Updated documentation, if necessary
- [ ] This PR is ready for review

Remaining Work
--------------

### CODE REVIEW

**Comment by brianlheim** [comment]
`git rebase --onto 3.10 develop topic/proxyspacemixer_typo_fix`
`git push --force topic/proxyspacemixer_typo_fix`

should do it.

`git help [rebase, push]` for more info

**Comment by dmorgan-github** [comment]
I tried those commands but I end up with conflicts. Not sure where they're coming from...

$ git fetch upstream 3.10
$ git rebase --onto upstream/3.10 develop topic/proxyspacemixer_typo_fix

First, rewinding head to replay your work on top of it...
Applying: Add cmake_gen tools
Using index info to reconstruct a base tree...
.git/rebase-apply/patch:188: trailing whitespace.
        install(TARGETS ${sn_name} LIBRARY DESTINATION ${name})
warning: 1 line adds whitespace errors.
Falling back to patching base and 3-way merge...
Auto-merging tools/cmake_gen/generate_server_plugin_cmake.py
CONFLICT (add/add): Merge conflict in tools/cmake_gen/generate_server_plugin_cmake.py
Auto-merging tools/cmake_gen/SuperColliderServerPlugin.cmake
CONFLICT (add/add): Merge conflict in tools/cmake_gen/SuperColliderServerPlugin.cmake
Auto-merging tools/cmake_gen/SuperColliderCompilerConfig.cmake
CONFLICT (add/add): Merge conflict in tools/cmake_gen/SuperColliderCompilerConfig.cmake
Auto-merging tools/cmake_gen/CMakeLists_header.template
CONFLICT (add/add): Merge conflict in tools/cmake_gen/CMakeLists_header.template
Auto-merging tools/cmake_gen/CMakeLists_footer.template
CONFLICT (add/add): Merge conflict in tools/cmake_gen/CMakeLists_footer.template
error: Failed to merge in the changes.
Patch failed at 0001 Add cmake_gen tools
Use 'git am --show-current-patch' to see the failed patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".

**Comment by brianlheim** [comment]
interesting, these commands work for me locally and i am using the current branches of your remote repo. i cannot debug what's happening on your local repo because git is very stateful. however, if you abort the rebase in progress (via `git rebase --abort`) and run `git log --oneline --all --graph` you should be able to see whether your branch is based on 3.10 or develop or something else. it might also be because you did not create a local tracking branch for 3.10 with `git checkout 3.10`. also check to make sure you have pulled from upstream (this repo) for 3.10 and develop.

if you don't want to spend time on this for this PR that's fine and totally understandable, however i would recommend that you become comfortable with rebase, as it's a very frequently used git command.

**Comment by patrickdupuis** [comment]
I'm going to merge this and cherry-pick into `3.10`

**Pull request merged**
