### PR TITLE
ide: udpate translation files

### PR DESCRIPTION
**Pull request by mossheim**
This can go into 3.9.2, right?

### CODE REVIEW

**Comment by brianlheim** [comment]
I am also adding info to Developing.md about how to do this.

**Comment by brianlheim** [comment]
Oh jeez, these haven't been updated since 2012.. 😆

**Comment by snappizz** [comment]
for changelog purposes, can someone explain what the user-facing changes are?

**Comment by brianlheim** [comment]
There are none. This just means that if someone wants to add translations for the IDE, they will be working off up-to-date files.

**Pull request merged**
