### PR TITLE
Move Qt primitives out of "common" to fix non-Qt builds

### PR DESCRIPTION
**Pull request by vivid-synth**
See the build error at https://github.com/supercollider/supercollider/pull/2197

### CODE REVIEW

**Comment by snappizz** [comment]
I can reproduce the Travis error with x86_64 and SC_QT on:

    [ 68%] Linking CXX executable sclang
    libsclang.a(sc_ipc_client.cpp.o): In function `SCIpcClient::readIDEData()':
    /home/nathan/git/supercollider/editors/sc-ide/primitives/sc_ipc_client.cpp:66: undefined reference to `ArrayToInt(QByteArray)'
    libsclang.a(sc_ipc_client.cpp.o): In function `void sendSelectorAndData<QString>(QLocalSocket*, QString const&, QString const&)':
    /home/nathan/git/supercollider/editors/sc-ide/primitives/localsocket_utils.hpp:23: undefined reference to `IntToArray(int)'
    collect2: error: ld returned 1 exit status
    lang/CMakeFiles/sclang.dir/build.make:125: recipe for target 'lang/sclang' failed
    make[2]: *** [lang/sclang] Error 1
    CMakeFiles/Makefile2:3627: recipe for target 'lang/CMakeFiles/sclang.dir/all' failed
    make[1]: *** [lang/CMakeFiles/sclang.dir/all] Error 2
    Makefile:160: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by vivid-synth** [comment]
Hmm, I'm going to need some help getting this building on Qt - I don't have it here so I'm just taking shots in the dark at this point.

**Comment by snappizz** [comment]
Same error as Travis here:

    CMake Error at lang/CMakeLists.txt:201 (add_library):
      Cannot find source file:

        /home/nathan/git/supercollider/common/localsocket_utils.cpp

      Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
      .hxx .in .txx

**Comment by snappizz** [comment]
Now it's back to the first error.

**Comment by vivid-synth** [comment]
Phew! Finally built

**Comment by crucialfelix** [comment]
tested: doesn't break OS X normal compile. We still can't compile without Qt on OSX but that's a separate issue.

Good to merge ?

**Comment by vivid-synth** [comment]
@crucialfelix what's the reason for that/how long has that been happening?

**Comment by crucialfelix** [comment]
It's a known issue. It's been like that for quite a while.  Certainly nothing to do with this PR.

We need to set up a separate build file structure layout for it and for scsynth. OS X builds into the SuperCollider.app/Contents and then we have to copy those file out to a separate folder, fixup_bundle etc.

I think we can merge this now. yes ?

**Comment by snappizz** [comment]
yes, it's working over here

**Pull request merged**
