### PR TITLE
help: improve examples in Pstutter

### PR DESCRIPTION
**Pull request by telephon**

### CODE REVIEW

**Comment by telephon** [comment]
(ping)

**Comment by brianlheim** [comment]
I'm going to look at this today!

**Comment by brianlheim** [comment]
Simplified some of the examples so that it's easier to hear the effect of using this class. I also switched a use of `EnvGen.kr` to `Env.kr` since we're already doing that in #2855.

**Comment by telephon** [comment]
they work fine - thanks!

**Comment by brianlheim** [comment]
np!

**Pull request merged**
