### PR TITLE
Remove potentially unused qt5 dependencies

### PR DESCRIPTION
**Pull request by simonvanderveldt**
PR to see if these Qt5 dependencies can be removed as discussed in #3471

### CODE REVIEW

**Comment by scztt** [comment]
One request: can we either leave in the Qt5OpenGL dependency, or leave the code but comment it out? Sensors and Positioning are neither here nor there, but there's a decently likelihood that we might start using OpenGL in the future. Cmake is already a hairy beast that very few of the core devs are comfortable modifying, so leaving a breadcrumb trail for this would be helpful.

**Comment by brianlheim** [comment]
I agree, at the very least leave it commented.

Also quick note that this might mean we can remove some dependencies from CI scripts and Readmes

**Comment by simonvanderveldt** [comment]
Can I conclude based on the passed CI runs that these dependencies are indeed unused?

> One request: can we either leave in the Qt5OpenGL dependency, or leave the code but comment it out?

I can comment that one out if that's preferred? I'd say it's in the git history so that wouldn't be needed but it's your codebase :)

> Also quick note that this might mean we can remove some dependencies from CI scripts and Readmes

I've found this https://github.com/supercollider/supercollider/blob/develop/.travis/before-install-linux.sh#L9
Qt5OpenGL isn't listed there btw, so I guess that makes it even more clear it wasn't being used.
Is there any other place I need to look at?

**Comment by brianlheim** [comment]
> Is there any other place I need to look at?

Nope, just there and then the corresponding place in README_LINUX. The other two OSs use monolithic installs of Qt. Thanks!

**Comment by patrickdupuis** [comment]
I can update the Linux build guides that are in the Wiki. I think the Rpi and BBB build guides on the website might need to be changed as well.

**Comment by brianlheim** [comment]
ahh, good point

**Comment by simonvanderveldt** [comment]
@brianlheim @scztt Would you prefer I comment out the Qt5OpenGL changes? Just checking to be sure.

**Comment by brianlheim** [comment]
yes, thanks for confirming. I get what you're saying about git history but unfortunately on a project this large it's easy for things like that to get lost

**Comment by simonvanderveldt** [comment]
@brianlheim OK, thanks for the confirmation. I'll update the PR this weekend.

**Comment by brianlheim** [comment]
@simonvanderveldt - can you take another look at this when you get a chance please?

**Comment by simonvanderveldt** [comment]
@brianlheim Sure, sorry for the radio silence. I'll put in in my agenda for this weekend, is that OK?

**Comment by brianlheim** [comment]
> Sure, sorry for the radio silence. I'll put in in my agenda for this weekend, is that OK?

No problem! Just wanted to make sure this doesn't go stale.

**Comment by simonvanderveldt** [comment]
All right, updated the Qt5OpenGL commit to just comment out (as best as I could) the changes.
Though t.b.h. whilst working through this my conclusion was that Qt5OpenGL is just more of the same, anyone looking at the `CMakeLists.txt` will understand what to add when adding Qt5OpenGL without the comments. And I have pretty much zero experience with CMake.
Not sure how much these comments make sense.

Also removed the `qt55sensors` install in the Travis setup.

**Comment by brianlheim** [comment]
Thanks!

> Though t.b.h. I'm not sure how much these comments make sense.

I understand where you're coming from, but from personal experience not everyone will be able to understand and modify these files as easily as you did. Not really a big deal either way, just trying to give some explanation.

**Comment by simonvanderveldt** [comment]
Just noticed I forgot to also update `LINUX_README`, so done that as well :)

**Pull request merged**
