### PR TITLE
docs: fix jsoftware link

### PR DESCRIPTION
**Pull request by alexhughk**
## Purpose and Motivation
typo in documentation causing broken external link

## Types of changes

- Documentation

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Thank you!
Sorry to split hairs here, are you sure we need a comma after "see"?

**Comment by alexhughk** [comment]
Hi,
No comma is probably fine. I think I copied that syntax from a similar usage in a different article.

**Comment by dyfer** [comment]
Sounds good. Would you make the change to remove it then?

**Review by dyfer — APPROVED** [review]
Thanks

**Pull request merged**
