### PR TITLE
Update TDelay.schelp

### PR DESCRIPTION
**Pull request by tiagmoraismorgado**

### CODE REVIEW

**Comment by redFrik** [comment]
sorry but this new example make no sense.  in my opinion there are multiple problems...
* `{[SinOsc.ar, FSinOsc.ar, SinOscFB.ar]}.plot` all give the same output.
* heavy use of `choose` is no good in helpfiles.  how are you suppose to know which ugen was chosen?
* the original example was short and to the point - this new is longwinded and only confuses the reader.

don't commit it.

**Comment by tiagmoraismorgado** [comment]
sure redfrik. by the way, you open openobggect supercollider extension was, for me pretty useful. really appreciated for the time you took to develop that

**Comment by tiagmoraismorgado** [comment]
by the way, despite the fact that i use this strategy a lot, this might not exactly be the way as many people use supercollider, i am aware that the recombination power of these classes and data structures, can lead to almost infinite possibilities if properly addressed. this goes pretty much along in the line of ramon lull ars combinatoria. and i find this extremely  powerful, myself. if you think it's not a good idea, i totally understand and respect that

**Comment by tiagmoraismorgado** [comment]
i have my own way of thinking about supercollider, and i go along with it. i don't want to change the way as the community thinks about supercollider. even though, i respect if people want to eventually think differently or doing things in other ways. i will follow my own, and try to give my best contribution towards the overall supercollider development

**Comment by jamshark70** [comment]
It's not that it's a bad idea in general, but rather that it's questionable *for help files*.

Somebody reading a help file needs a clear correlation between the code and the result. Adding randomness to a basic UGen example breaks the correlation.

Simplicity and clarity need to be the priorities.

**Comment by redFrik** [comment]
sorry@tiagmoraismorgado i don't mean to put don't your effort.  your contributions and insights are good, but perhaps you could add additional examples instead of rewriting the core ones that are already there (perhaps add a section 'further explorations' or we could even have a 'playground' section further down in the helpfile with wild and fun examples?).

"Simplicity and clarity need to be the priorities"
exactly.  thank you @jamshark70

**Comment by tiagmoraismorgado** [comment]
@redFrik, as i said it was a suggestion. i really have a great sense of respect towards your work and everything you do and did with supercollider, puredata, processing, open frameworks, raspberry pi. i got curious about computer music in 2000-2001. i only started to do midi compositions in 2003 or 2004. later on, i heard of maxmsp. it was around 2005 or 2006. in 2007 i had an opportunity to do an advanced level workshop on maxmsp with andre bartetzki, who is a great friend and collaborator of yours, despite the fact i didn't know anything about programming, and i felt completely lame noob and retarded there. even though in 2007 or 2008, i took an year doing hardcore research in computer music. by the time i got in touch with your work, but i didn't even know how to evaluate a line of code in supercollider, and i wasn't familiar with supercollider development at all. i then did a bachelors in computer music, and attended a masters in sonology. when i was about to finish my masters i started using supercollider. it's not my main tool. i don't really have a main tool. i like to put things together according to the specific necessities of every single thing i do. but at the time i came back to your examples, and i could follow them, and modify them, fool around with them, and make new stuff out of them. despite the fact that i am into music since 2000. and i hold a masters, and was accepted for a phd. i still feel i am scratching the surface and giving my first steps, in almost everything that i do, despite the fact sometime people tell me, hey what you are doing is really, really great. so i believe that if we ggoin efforts in this path, i can learn a lot from all of you guys, and make a meaningful contribution to the development of this whole thing. perhaps even if we would set a paypal for the supercollider community, i could release music of some of you guys once in a while, and contributing with the income to support the supercollider community, like the processing foundation did. so yeah. i think we can all come along and make stuff together. and i believe in the end we might learn all a little bit from each other. and complement ourselves in the community in a way that will be good to all of us

**Comment by redFrik** [comment]
@tiagmoraismorgado thank you.  yes, please don't take it personal.  see it rather as a motivation to write better examples.  and if you like you can think of me as an old fart that sometimes cause trouble and complain - like an obstacle you have to get pass with really great contributions!

ps. OpenObject is mainly Julian's work - i did the examples.

**Comment by tiagmoraismorgado** [comment]
@redFrik  i think you should make an example on how to bind super collider csoudn purata maxmsp and ableton using open object maxforlive, and overall osc. that would be terrific. a bit out of topic, but yeah

**Comment by snappizz** [comment]
I'm also a little worried about the use of "choose," because it no longer works as expected when you convert from { }.play to a SynthDef.

**Comment by tiagmoraismorgado** [comment]
@snappizz that's why i use buses (i don't know if i am using the right terminology so my apologies). but that can be fixed. if we get a method similar to TRand, as a choose equivalent, for synthdefs. and believe me, this approach as a tremendous power. the idea of suddenly getting a couple of classes that have infinite numbers of permutations, and can be stochastically chosen, is something really powerful, specially if you model this on an hierarchical and cross field related way, thinking of cartesianism of an instance. or thinking about ars combinatoria by ramon llull. or fractal geometry. or this quote by hermes trimegistus. as above so below. as within so without as the universe so the shoul. in fact if you have a series of synth definitions that are wrapped into a class, and then are modelled in a  multidimensional way and on an hierarchical way you can with very little code, create infinite possibilites for music creating. and that's why i am an avid defender of this approach, despite the fact that you are not in accordance with this on supercollider. but i see all the benefits in using this. please check this: https://github.com/tiagmoraismorgado/TMM_live_electronics-toolkit-wip-/blob/master/TMM_live_electronics%20toolkit%20(wip)/_sound_2_supercollider/Tiago%20Morais%20Morgado/TMM_Gran.sc even though that the code here is sort of retarded. i think we can scale this into an extreme degree of complexity and use it to model far much more complex behaviour

**Comment by tiagmoraismorgado** [comment]
if for an instance you create a single line saying for an instance {Tiago_Ambient.allSubClasses.choose.ar}.scope you can have an infinite index of permutation possibilities. that's it. kind regards. tiago

**Comment by tiagmoraismorgado** [comment]
and then if you combine this with other things. this can turn out to be really powerful

**Comment by jamshark70** [comment]
> if for an instance you create a single line saying for an instance {Tiago_Ambient.allSubClasses.choose.ar}.scope you can have an infinite index of permutation possibilities

Agreed that it's very powerful, but IMO this random-choosing technique would be better discussed in a post on sccode.org - UGen help files are not the best place to introduce this sort of technique. There are plenty of other places where this contribution would be highly valuable.

**Comment by telephon** [comment]
yes, snapizz,  post them on sccode.org, it is really a good place for such things. 

Or if you really would enjoy seeing them in the examples, you could make one file and submit a pull request for this to be added to the examples/demonstrations folder. But in either case you should really make sure that they work and that they sound "good in some way".

**Pull request closed without merging**
