### PR TITLE
Helpfile fixing

### PR DESCRIPTION
**Pull request by LFSaw**
updates/additions of several helpfiles

### CODE REVIEW

**Comment by LFSaw** [comment]
I'd like to then close this branch. Working on helpfiles should continue also off the effort made here: http://piratepad.net/Nx0YRDmchh

**Comment by crucialfelix** [comment]
You guys are merging pull requests into pull requests. That's crazy. 

I already merged #2069 into master.

**Comment by crucialfelix** [comment]
Nuts, I didn't notice your comment about closing this branch. Neither did miczac I guess.

This PR is merged in now. Duplicate commits shouldn't harm anything.

**Comment by LFSaw** [comment]
Appearantly There was some confusion about how to work with git... thanks for the merge!

**Comment by miczac** [comment]
allright .. so all new PRs should address master but the PP notes stay maintained?
I understood 'helpfile-fixing' as collection of improvements which is supposed to be merged every now and then and not every single PR being routed through it on a shorter-than-a- day basis.
There are many help files to be fixed and added.

**Pull request merged**
