### PR TITLE
Helpfile-fixing branch, final merge

### PR DESCRIPTION
**Pull request by LFSaw**
ok, I'm getting confused here, so I'll now merge the helpfile-fixing branch into master and then get rid of the branch.

### CODE REVIEW

**Comment by LFSaw** [comment]
succesful.

**Comment by miczac** [comment]
ok, that's the answer ... ;)

**Comment by LFSaw** [comment]
I created the branch "helpfile-fixing" for the one-off event at STEIM last weekend at which we were supposed to fix a lot of helpfiles so to not have too many people on master to be bothered with single-file commits. After that, I thought, I'll remove the branch again but somehow confusing things happened... so now, we're back in a state of confidence and can surely discuss if we want to have a more permanent helpfile-fixing branch established. :)

**Comment by miczac** [comment]
Also the commit messages got slightly messed up, I think. But I only briefly bothered to think about how to fix that.
I'm fine with the current (removed branch) state. No problem to collect my commits in a local branch, push them to my fork and issue a PR to upstream/master.

**Pull request merged**
