### PR TITLE
fix: Quarks.load quark set

### PR DESCRIPTION
**Pull request by crucialfelix**
previously it was failing to load a quark set file for any quarks that were not previously cloned. it would check them out (switch to the right tag) but it wouldn't clone it if needed.

also makes Quarks.load cancelable with command-.
does load with some pauses so it does not choke the main app
and updates the gui when its done

### CODE REVIEW

**Comment by telephon** [comment]
>this is a complicated app to build in supercollider. it needs async io and promises.

would it be hard to have promises in sc? Don't we have the infrastructure for that?

**Comment by crucialfelix** [comment]
Promises would be great. 

```supercollider
var result = {...do something async... }.await ;
```
would be really great. any thrown exception in the function would get rethrown in the top level call site.

It implies that there is always a top level Routine that code is evaluated in and that can be paused.

**Comment by telephon** [comment]
In what way is a top level Routine needed to permit ````await````?
You can hang and unhang a condition already.

**Comment by crucialfelix** [comment]
all the examples in Condition help file use a Routine or .fork

regardless of how it is implemented, if you write code like:

```supercollider
var result = {...do something async... }.await ;
```

then control flow stops until the condition is satisfied. if you are not in a Routine then you are on the main thread and you are blocking it. no ?

**Comment by telephon** [comment]
yes, of course you need to pass a function that is called when we are ready to continue, so the above direct assignment syntax is not currently possible with how the parser works.

But you could have an implementation that is called like this:

````
{ ... do something async ... }.await { | result | ... do something with the result }
````

But maybe this is not useful for what you want?

**Comment by telephon** [comment]
> if you are not in a Routine then you are on the main thread and you are blocking it. no ?

Yes, but with ````forkIfNeeded```` you can always wrap a routine around what you are doing.

**Comment by miguel-negrao** [comment]
On 28-09-2015 10:17, Julian Rohrhuber wrote:
> yes, of course you need to pass a function that is called when we are
> ready to continue, so the above direct assignment syntax is not
> currently possible with how the parser works.
> 
> But you could have an implementation that is called like this:
> 
> |{ ... do something async ... }.await { | result | ... do something with the result }
> |

Isn't the point of using coroutines to avoid callbacks ? Code without
callbacks is much easier to manage.

Best,
Miguel

**Comment by crucialfelix** [comment]
Yes, there is not really any point if we have to use callbacks to try to
make it resemble hipper programming languages.

To really make .await useful there would need to be many other common
operations in the language (network, server calls) that also implement it
so that you can chain things.

Also with promises - you want the server boot to be a promise so you can
server.boot().then({ { }.play })

> But maybe this is not useful for what you want?

I don't write any supercollider at all.  I just did the Quarks because you
guys needed it done.

**Comment by crucialfelix** [comment]
// this is how code should look for people that want await syntax
s.boot.await;
SynthDef(....).send.await;
g = Group.new.await;
Synth(defName).tail(g).await;

personally I don't plan on doing this kind of step by step imperative code
at all.
it makes awful music, its a pain in the ass and it causes all kinds of
state bugs.
computers should make these things happen, not composers.

**Comment by telephon** [comment]
>personally I don't plan on doing this kind of step by step imperative code at all.

Yes, me neither.

>To really make .await useful there would need to be many other common operations in the language (network, server calls) that also implement it so that you can chain things.

Yes, if we stayed within the current programming paradigm, they would all have to return a specific promise object.

**Comment by crucialfelix** [comment]
here's two articles showing javascript's new async compared to promises:

https://jakearchibald.com/2014/es7-async-functions/
https://nulogy.com/articles/from-promises-api-to-async-await

most of us these days use the babel transpiler to process javascript files
written with ES6 and some parts of ES7 (like await and async) to make the
code run on current browsers and older versions of node.js

so this syntax is available right now.

**Comment by telephon** [comment]
... moving this to sc-dev.

**Pull request merged**
