### PR TITLE
[docs] - supercollider/supercollider/helpsource/classes/alpassc.schelp - minor tweals (grammar, punctuation, formatting, et. al)

### PR DESCRIPTION
**Pull request by tmm2018**
[docs] - supercollider/supercollider/helpsource/classes/alpassc.schelp - minor tweals (grammar, punctuation, formatting, et. al)

### CODE REVIEW

**Comment by jamshark70** [comment]
You've taken more tabs and changed them into spaces... *after multiple requests from Brian not to do that.*

I strongly suggest using `git diff` at the command line before committing, to make sure you are committing only and exactly the changes you intend. Or use a graphical tool like qgit that allows you to review the diff as part of the commit process.

It's very easy for unexpected changes to creep in. This happens to me all the time! I'd estimate maybe 80% of the time, when I go to commit something, there's something I didn't want to change. So I learned that I have to check the diff *every time*... *never* trust that the diff is always exactly right. I think here, you didn't mean to change the spacing, but you didn't verify before committing.

Also, check your IDE spacing and indentation preferences.

**Comment by tmm2018** [comment]
hi @jamshark70 you are absolutely right. the thing is that the editor that i am using, converts tabs into spaces automatically. so, right now, i do know that I have to grab the stuff back to another editor, and double check for tabs before committing stuff. I know this can be extremmely annoying for you guys, but i had some difficulty figuring that out on my own, that was the reason why i screwed it up several times. I will bear this in mind, in order not to reapeat it anymore, and avoiding repeating mistakes. sorry for not fixing things immediately. once i was out yesterday through most of the afternoon and night. i will fix this immediately right now.

thank you for you understanding and thank you so much for your precious insight
cheers

**Comment by tmm2018** [comment]
correction - i was able to fix this. thank you so much for your help @jamshark70. sorry if sometimes i don't figure this as quickly as i should. and commit the same mistakes several times. it's not that i do it on purpose, but i should take more care with this. I would like to state - how can i fix this attitude for the community, besides trying not to commit the same mistake again?

**Comment by tmm2018** [comment]
thank you so much for accepting my contributions brian. more then a privilige, it's an honour to be part of the sc-dev team

**Pull request merged**
