### PR TITLE
get bela branch up to date

### PR DESCRIPTION
**Pull request by telephon**
This PR is just a test and a reminder that it would be good to keep the work of those who ported sc to the bela platform (http://bela.io/) up to date with the master branch.

### CODE REVIEW

**Comment by telephon** [comment]
P.S. it would be good to know what is the best way to handle such forks!

**Comment by brianlheim** [comment]
Sorry @telephon – I'm not sure exactly what's intended here. If the purpose is to update @giuliomoro's fork of SC, the PR should be made there, not here.

**Comment by gusano** [comment]
@brianlheim @telephon also it seems that [his fork](https://github.com/giuliomoro/supercollider) is based on Marije's fork and not sc main repo

**Comment by telephon** [comment]
Yes, exactly, it's based on Marije's fork, which in turn has diverged. As I said, I am not sure of how to avoid divergences that make it increasingly difficult to keep a branch up to date.

**Comment by snappizz** [comment]
Forking SC seems pretty painful. I see two basic strategies that serve as alternatives:

1. Make use of SC's existing extensibility capabilities.
2. Modify core SC to include, or at least accommodate, the extensions in a way that doesn't interfere with other users.

The first option is the most pleasant, but it's not always possible. It only applies to class library extensions (easy, that's what quarks are) and server plugins (not so easy since you need to set up a build system, but possible). If you're making changes to the build system, sclang, or scsynth/supernova core, you are stuck with the second option.

I've only skimmed the code, but many of the changes seem unobtrusive and could probably be safely merged in. If it's not too inconvenient for the developers of this branch, maybe the new UGens could be kept in a separate repository.

Since this is adding an entire new component to SC, we also need to discuss the organizational implications. If we can truthfully say "it runs on Bela" on our home page, that's pretty good PR for us. On the flip side, adding a new feature carries a risk -- if it falls out of maintenance, that's bad PR for us (the last thing we need is more code rot). I don't have a good answer for how these weigh against each other in this case.

Either way, I'd hold off merging into core until after 3.9.

**Comment by gusano** [comment]
@telephon @snappizz I agree with @brianlheim here, @giuliomoro fork should be rebased/merged with main repo master before anything else (if you intend to eventually merge his code into main repo).

**Comment by brianlheim** [comment]
The way to avoid divergence is to pull (or cherry-pick) regularly from master. I think we should focus on supporting Windows before we talk about Bela.

**Comment by brianlheim** [comment]
Sorry, just to be clear—it's not that we can't talk about this now, it's just that, as Nathan said, this is probably not something we can include in 3.9 unless someone takes it on as their own personal project. In that case, great!

**Comment by telephon** [comment]
>The way to avoid divergence is to pull (or cherry-pick) regularly from master. I think we should focus on supporting Windows before we talk about Bela.

If you think so, I'm fine with either, I currently can't test on either platforms anyway. 

But: We can't pull from master, because we are there, it's perhaps @sensestage. That was the content of the question. As there is no other way in this forum to note down such "issues" (which are not "issues"), I feel a bit at loss where to do this.

**Comment by gusano** [comment]
> As there is no other way in this forum to note down such "issues" (which are not "issues"), I feel a bit at loss where to do this

@telephon The "proper way" should be to open an issue on https://github.com/giuliomoro/supercollider about becoming more up-to-date with sc current master, *but*:

- that repo has not enabled issues
- that repo was forked from https://github.com/sensestage/supercollider which diverges from our repo quite a bit AFAICS so I don't see any easy solution

Maybe @giuliomoro should jump in the discussion?

In any case, this should be first solved on [giuliomoro/supercollider](https://github.com/giuliomoro/supercollider) side, and eventually we *could* merge his changes in.

**Comment by giuliomoro** [comment]
Hello, sorry for the late response, I struggled a lot to find the issue on github after I deleted the emails (it does not show up in my "notifications").

First off, thanks @telephon for the interest.

Second,
> @brianlheim supporting Windows before we talk about Bela.
I agree entirely.

I am part of the Bela team and jumped in to support Marjie and Dan in their porting effort. I am sort of a novice Supercollider person, let's say I probably wrote more lines in the `.cpp` sources than in the SC IDE, and I have not written that many anyhow.

Reason why https://github.com/giuliomoro/supercollider has no issue tracker is because issues are to be reported on https://github.com/sensestage/supercollider, which I consider to be the `origin` repo, in fact it is there where I submit my PRs, which mainly have to do with keeping the code and the build process up to date with the latest changes or added features on the Bela side.
Again, not knowing much about SC's code organization and not being a SC user myself (thus with limited capability in testing functionality of the software), I would not feel comfortable in merging in the ` 236 commits ahead, 741 commits behind supercollider:master`.

> @snappizz Modify core SC to include, or at least accommodate, the extensions in a way that doesn't interfere with other users.

We had to edit some of the core code to accommodate more command-line options and some changes to accommodate the use of Xenomai.

> @snappizz  If we can truthfully say "it runs on Bela" on our home page, that's pretty good PR for us. 

We do say "We have experimental support for SuperCollider", for what matters. In practice, it is working, but some of the latest Bela features have not yet been implemented. Surely, we could use more testing.

As a final note, of the commits I made I can think only of one which could be useful into the SC master branch, as most of them are entirely Bela-specific: this one would be useful to anyone with a Vector-floating-point unit (i.e.: Arm Cortex A8, A9 and similar) : https://github.com/sensestage/supercollider/pull/25

**Comment by bagong** [comment]
@giuliomoro , thanks for supporting SC! It would be great marketing for us too if we could say it runs well on Bela, and even better if it could be added in a way that remains compatible with mainline development. One sometimes thinks the most interesting work happens outside of SC "proper" these days, and running on an almost 0-latency affordable mini-system is certainly among the most exciting things that could happen to SC.
Interest in ARM is gradually rising within the SC community, but not much manpower and expertise to support the platform actively, we could really do with more contributors with your kind of expertise. Right now it's hard to do anything on mini-systems if you need tight timing... And here comes the Bela board... it's there, and we're about to miss another opportunity when the important work is being done. It was similar with the RPI, and now we have the unfortunate situation that the official RPI is stuck in 3.6 and cannot coexist with current SC on the same system. Also RPI profits little from mainline SC development...

**Comment by sensestage** [comment]
I will get back to Bela work in July, together with @giuliomoro and we'll get my fork uptodate with master again and fix some other outstanding issues.

I think the Bela UGens should be in main, as they heavily depend on the additions I had to make to scsynth to give access to the bela context. If the UGens would be in a separate repository, it would be hard to keep them in sync with the scsynth version. But they won't compile for other platforms, so they should not be in the way. The class files can be useful if controlling scsynth running on Bela from sclang running on a laptop or desktop; but I could make that into a built-in quark if necessary.

I think also the other changes I made to scsynth do not compile on other platforms (they are within Bela specific defines). I will doublecheck.

**Pull request closed without merging**
