### PR TITLE
Version 3.7.1

### PR DESCRIPTION
**Pull request by crucialfelix**

### CODE REVIEW

**Comment by crucialfelix** [comment]
doh

```
$ ifmac brew install cmake libsndfile qt55 || true
Error: cmake-3.0.2 already installed
To install this version, first `brew unlink cmake`
```

**Comment by bagong** [comment]
Haha, message was always there as a warning, but right for the release it turned angry ;)
I'll start Windows, might take two hours or so. Let me know how to proceed. Push a rebased version of Lucas' IPC stuff as a separate branch, tag it as something 3.7.1win (is that possible?) or so?

**Comment by crucialfelix** [comment]
I'll tag it now, then yes you can proceed ! 

maybe just 3.7-win not 3.7.1-win

I'm not keeping a separate 3.7.1 branch around, just adding to 3.7

**Comment by bagong** [comment]
The branch 3.7win, okay. So no extra tag? The build will not be from th 3.7.1 tag, it will be from 3.7.1 plus two commits...

**Comment by crucialfelix** [comment]
apparently pushing my branch to origin (supercollider) results in closing the PR automatically. I guess that's fine. I was just pushing the new tag.

**Comment by bagong** [comment]
Yea, it's apparently smart enough to see that the hashes are the same.

**Pull request merged**
