### PR TITLE
Improve doxygen style documentation in header files for plugin developers

### PR DESCRIPTION
**Pull request by madskjeldgaard**
## Purpose and Motivation

Fixes https://github.com/supercollider/supercollider/issues/5249

This PR adds doxygen style comments to important headerfiles that are facing plugin developers. With these, LSP based tools should be able to pick up the information from the source code and automatically give the developer hints when doing "code hover" or similar.

Where possible I have used the original comments and/or documentation from the schelp system. 

## Types of changes

- Documentation

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [x] Updated documentation
- [ ] This PR is ready for review

### CODE REVIEW

**Review by brianlheim — APPROVED** [review]
thanks!

**Comment by brianlheim** [comment]
can you please [format your code](https://github.com/supercollider/supercollider/wiki/Cpp-formatting-instructions) to pass the linting build job in travis? it looks like you just need to delete the trailing whitespace in some of your comments.

**Comment by madskjeldgaard** [comment]
I manually removed the trailing whitespace now after too many futile attemps to retroactively apply the including formatter to the code, hopefully it passes now (and hopefully I've integrated clangformat properly from now on for uncommited changes)

**Comment by madskjeldgaard** [comment]
Ci build still failing... okay, lll try the clangformatter again

**Comment by brianlheim** [comment]
hey @madskjeldgaard , thanks to the feedback from you and @muellmusik, i added a lot of new documentation to https://github.com/supercollider/supercollider/wiki/Cpp-formatting-instructions and tried to make everything clearer and more organized. i also added a section about how to make the right formatting while avoiding using clang-format, as a last resort. hope this helps! i also pinged you on Slack.

**Comment by madskjeldgaard** [comment]
Thanks @brianlheim !

**Review by brianlheim — APPROVED** [review]
thanks!

**Pull request merged**
