### PR TITLE
Skip verify on macOS universal CI

### PR DESCRIPTION
**Pull request by capital-G**
## Purpose and Motivation

A **temporary** fix for building the macOS universal binary, see #6352 
Supersedes https://github.com/supercollider/supercollider/pull/6357 which deactivated the build completely, here we just de-activate the verifying step during build macOS - I am surprised that the binary can be picked up by a different runner for testing though.

## Types of changes

- Bug fix
- 
## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

### CODE REVIEW

**Comment by silvanocerza** [comment]
Seems like the build was successful. 👀

**Comment by JordanHendersonMusic** [comment]
What does `verify-app` actually do?

**Comment by silvanocerza** [comment]
> What does `verify-app` actually do?

If it's `true` the `verify_app(<app>)` function is called. From the [docs](https://cmake.org/cmake/help/latest/module/BundleUtilities.html): 

> Verifies that an application `<app>` appears valid based on running analysis tools on it

**Comment by JordanHendersonMusic** [comment]
Ah! Thanks for the quick reply.

That might explain why the test still works because verify_app is trying to verify scide, whereas the test only needs sclang?

**Review by JordanHendersonMusic — APPROVED** [review]
A temporary fix for the CI. Thanks @capital-G!

**Pull request merged**
