### PR TITLE
Started work on Qt6 support

### PR DESCRIPTION
**Pull request by ohhmm**
## Types of changes

- Documentation
- Bug fix
- New feature
- Breaking change

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by capital-G** [comment]
Thanks for picking up this task!

Have in mind that @dyfer is already working on Qt6 support, see https://github.com/supercollider/supercollider/compare/develop...dyfer:supercollider:topic/qt6-11 - maybe it is best to get in contact with him and ask what steps are missing and pick up on these?

**Comment by mtmccrea** [comment]
>Have in mind that @dyfer is already working on Qt6 support, see https://github.com/supercollider/supercollider/compare/develop...dyfer:supercollider:topic/qt6-11 - maybe it is best to get in contact with him and ask what steps are missing and pick up on these?

Judging by the commits, looks like @jrsurge is also contributing, so may want to be involved.

**Comment by JordanHendersonMusic** [comment]
@ohhmm just a gentle bump to see if this PR is still being pursued separately from the other fork?

**Comment by ohhmm** [comment]
Hi @JordanHendersonMusic,
If you see any reason to not merge this compatibility patch, then feel free to act accordingly to your best judgment about this PR.

**Comment by jrsurge** [comment]
Hi, thanks for this PR, apologies it has taken me so long to get to it - I have some concerns about this approach. The process to migrate to Qt 6 is a little more involved than this PR would suggest (and I understand that this is an initial set of changes). I'm not sure this would build with Qt 6 as it stands, and even if it did, we should aim to be deprecating Qt 5 support, rather than prolonging it with compatibility shims. I've made a start, with some help from @dyfer, but a few things have delayed this work. I'm hoping to pick it up again shortly - if you'd like to help with that, please feel free to get in touch!

**Comment by dyfer** [comment]
Hello, this PR is not nearly enough for the Qt6 migration.
@jrsurge has made initial progress on Qt6 port, then I moved this along quite a bit, but there are still unresolved issues.
If you plan on updating to Qt6 (which would be very much appreciated!), please continue the work and ideally document your progress in https://github.com/supercollider/supercollider/issues/5169

**Pull request closed without merging**
