### PR TITLE
ide: menu option "Show Quarks"

### PR DESCRIPTION
**Pull request by miguel-negrao**
This adds a "Show Quarks" menu entry in the "language menu", after the first divider.

### CODE REVIEW

**Comment by miczac** [comment]
Thanks for that! ;)

**Comment by crucialfelix** [comment]
I'm not sure about "show".  

Right now without looking at the diff I can only guess. Is it ... the gui ? 

How about just "Quarks" ?  

because "show" is not always the intent of the user. It could be Install Quarks. Browse Quarks. "Install Packages" is a common.

**Comment by miguel-negrao** [comment]
captura de ecra de 2016-02-16 11-24-49

I was following the pattern in the rest of the menu entries. Whenever a menu entry opens a window it has "Show", as in "Show server meter", etc. But "Quarks" if fine with me too, don't have a strong opinion about it.

**Comment by gusano** [comment]
@miguel-negrao in any case I'd be in favour of having that quark menu entry more at the bottom, after server-related entries which are more "important"

**Comment by miguel-negrao** [comment]
> @miguel-negrao in any case I'd be in favour of having that quark menu entry more at the bottom, after server-related entries which are more "important"

I could move it to after the separator after "Mute".

**Comment by miguel-negrao** [comment]
> Right now without looking at the diff I can only guess. Is it ... the gui ?

Yes, it calls "Quarks.gui"

**Comment by gusano** [comment]
> I could move it to after the separator after "Mute"

:+1:

**Comment by miguel-negrao** [comment]
Moved it after mute and renamed to "Quarks".

**Comment by crucialfelix** [comment]
OK, looking at it on the menu and seeing the other ones I don't see any
problem now. Show Quarks is fine I think.

Its better up at the top because its by Recompile Class Library.  We still
have the problem that the menu item won't work if your quarks are fucked up.

On Tue, Feb 16, 2016 at 12:41 PM Yvan Volochine <notifications@github.com>
wrote:

> @miguel-negrao <https://github.com/miguel-negrao> in any case I'd be in
> favour of having that quark menu entry more at the bottom, after
> server-related entries which are more "important"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/pull/1867#issuecomment-184648098>
> .
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by crucialfelix** [comment]
I don't have a strong opinion about it either.

On Tue, Feb 16, 2016 at 1:33 PM Chris Sattinger <crucialfelix@gmail.com>
wrote:

> OK, looking at it on the menu and seeing the other ones I don't see any
> problem now. Show Quarks is fine I think.
>
> Its better up at the top because its by Recompile Class Library.  We still
> have the problem that the menu item won't work if your quarks are fucked up.
>
> On Tue, Feb 16, 2016 at 12:41 PM Yvan Volochine <notifications@github.com>
> wrote:
>
>> @miguel-negrao <https://github.com/miguel-negrao> in any case I'd be in
>> favour of having that quark menu entry more at the bottom, after
>> server-related entries which are more "important"
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/supercollider/supercollider/pull/1867#issuecomment-184648098>
>> .
>>
> --
> https://twitter.com/crucialfelix
> https://medium.com/@crucialfelix
> http://www.mattermind.com/
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by miguel-negrao** [comment]
> OK, looking at it on the menu and seeing the other ones I don't see any problem now. Show Quarks is fine I think. Its better up at the top because its by Recompile Class Library.

ok, I'll wait for more opinions then about up or down.

> We still have the problem that the menu item won't work if your quarks are fucked up.

What happens it the quarks are fucked up ? Quarks.gui throws an error ?

**Comment by crucialfelix** [comment]
If you got duplicate classes or missing a dependency then you cannot compile the library. So you cannot open Quarks.gui

**Comment by miguel-negrao** [comment]
> If you got duplicate classes or missing a dependency then you cannot compile the library. So you cannot open Quarks.gui

Oh, right. Well that is a consequence of Quarks.gui having been implemented in sclang instead of sc-ide. Given that design decision, not much that can be done in terms of using the quarks gui to fix quark problems. In any case if the problem is caused by quarks, the user can just use the ide interpreter settings to remove the offending quark (or manually edit the language config file), right ?

**Comment by miczac** [comment]
On 16.Feb 2016, at 13:33 , Chris Sattinger <notifications@github.com> wrote:

> OK, looking at it on the menu and seeing the other ones I don't see any
> problem now. Show Quarks is fine I think.

FWIW, if �action oriented� then it might be �Manage Quarks� since it does way more than just a display of � Quarks. 

> Its better up at the top because its by Recompile Class Library. We still
> have the problem that the menu item won't work if your quarks are fucked up.

good point, to consult the terminal would be inevitable then, which is not everyone�s cup of tee.

**Comment by crucialfelix** [comment]
yeah, you just have to edit the language config file manually.

at least in atom-supercollider it posts the link to the language config file to the console; you can just click it and open it in the editor.

today I think that just  "Quarks" is neutral and informative enough. it doesn't need a verb.

ready to merge I think.

**Comment by miguel-negrao** [comment]
> yeah, you just have to edit the language config file manually.
> 
> at least in atom-supercollider it posts the link to the language config file to the console; you can just click it and open it in the editor.

In the ide you can edit the language config file in the preferences pane, even with interpreter not running or class library not compiling.

> today I think that just "Quarks" is neutral and informative enough. it doesn't need a verb.
> 
> ready to merge I think.

Right now the Quarks are after mute, is the consensus to move it back up after "Recompile Class Library" ? If so I can edit the commit.

**Comment by crucialfelix** [comment]
yes, I think up by Recompile Class Library sounds good. Its a primary tool (installing or uninstalling packages) and its more obvious there.

**Comment by miguel-negrao** [comment]
> yes, I think up by Recompile Class Library sounds good. Its a primary tool (installing or uninstalling packages) and its more obvious there.

done

**Pull request merged**
