### PR TITLE
Classlib: GUI: asLayoutElement interface for non-Views that work in layouts

### PR DESCRIPTION
**Pull request by jamshark70**
Per discussion under #2188, this adds an interface for validity checking in layouts.

I'm traveling the next 2 days, feedback will be limited, just wanted to get this out there for discussion before leaving.

It passes this very basic test:

```
w = Window("test", Rect(800, 200, 500, 400)).front;

w.layout = VLayout(
	[StaticText().background_(Color.rand), stretch: 1],
	[StaticText().background_(Color.rand), stretch: 2]
);
```

### CODE REVIEW

**Comment by jamshark70** [comment]
Here's a more comprehensive test. It appears to behave correctly.

```
(
w = Window("test", Rect(800, 200, 500, 400)).front;
w.layout = VLayout(
	StaticText().string_("simple view")
	.background_(Color.rand(0.1, 0.4))
	.stringColor_(Color.white),
	
	nil,  // non-item: no error
	
	[nil, stretch: 3],  // stretch-factor spacer
	
	LayoutValueSlider(initValue: 0.5, spec: [0, 1]),  // SCViewHolder
	
	[
		StaticText().string_("view with stretch")
		.background_(Color.rand(0.1, 0.4))
		.stringColor_(Color.white),
		stretch: 2
	],
	
	100  // fixed-size spacer
);
)
```

However, I notice that the file name ext-asLayoutMember doesn't match the method name `asLayoutElement`. I'm going to try to change it and squash the commits down. This might break the PR. If so, I'll close this and put in a new one.

**Comment by jamshark70** [comment]
The file rename appears to have worked. For the record, I did `git push --force`, so if you already checked out the branch, a normal pull might complain. In that case, try `git pull --force ...`?

**Comment by crucialfelix** [comment]
In the future you can just add another commit that renames or does changes. When I merge I usually do a squash commit and I all commits appear as one with the ability to edit the messages.

**Comment by crucialfelix** [comment]
Anybody have any thoughts about this ? I haven't used sc gui for many years.

**Comment by crucialfelix** [comment]
@scztt @telephon  any feedback or approval ?

**Comment by scztt** [comment]
👍

**Pull request merged**
