### PR TITLE
test: add test for audio rate controls

### PR DESCRIPTION
**Pull request by telephon**
## Purpose and Motivation

This makes sure that node order doesn't matter for audio rate mapping, up to block delay.

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks @telephon and sorry for the delay
Could you please rebase your PR on the latest `develop`? Once you do, the added tests would automatically be run in our CI.

**Comment by telephon** [comment]
@dyfer good like this?

**Comment by dyfer** [comment]
The rebase is good, thanks!
One of the tests fails: [test_map_with_control_rate](https://github.com/supercollider/supercollider/pull/5304/checks?check_run_id=3245971788#step:8:15012)
Not sure if I understand correctly, but it seems that the number of channels is fine, but there is value discrepancy (possibly because of `.kr` -> `.ar` conversion  - trigger arriving before the end of the control period?). Since you designed these tests you probably have a better idea what's the best way to address this.

**Comment by telephon** [comment]
Just a precision error. Should be better now.

**Comment by dyfer** [comment]
Thanks! This still fails on macOS, [as you can see in the CI](https://github.com/supercollider/supercollider/pull/5304/checks?check_run_id=3261343857#step:9:15793). `.asInteger` truncates the floating point, one way to address this is to `.round` first I think?

**Comment by telephon** [comment]
OK, hope this works now.

**Review by dyfer — APPROVED** [review]
Thanks!

**Pull request merged**
