### PR TITLE
Fix python3 print statement

### PR DESCRIPTION
**Pull request by TristanCacqueray**
## Purpose and Motivation

Fix python code for python3 only environment.

## Types of changes

- Bug fix

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Last commit includes the future-import and it is rebased against 3.10.

**Comment by brianlheim** [comment]
@TristanCacqueray can you double-check your rebase? it doesn't look right

**Comment by brianlheim** [comment]
@TristanCacqueray Can you double check your rebase? this branch is still off develop.

**Comment by brianlheim** [comment]
you can also achieve the same thing with

```bash
git checkout 3.10
git pull
git checkout -b python3-compat2
git cherry-pick python3-compat
git checkout -B python3-compat
git branch -D python3-compat2
git push --force origin python3-compat
```

**Comment by TristanCacqueray** [comment]
Oh I see now, I thought 3.10 was the HEAD refs. It should now be rebased to the correct branch.

**Comment by brianlheim** [comment]
@TristanCacqueray thanks! CI was acting up, should be good to go now.

**Comment by snappizz** [comment]
thanks @TristanCacqueray :)

**Pull request merged**
