### PR TITLE
Improve checking for nil Buffers

### PR DESCRIPTION
**Pull request by patrickdupuis**
This PR is a redo of my previous work on checking for freed Buffers. The checks now happen inside the `Msg` methods. `OSCFunc`s have also been moved inside these `Msg` methods. The `Msg` methods are now consistently called in order to construct the Server messages. 

Thank you for testing and reviewing!

### CODE REVIEW

**Comment by telephon** [comment]
I just noticed that so far, the existing code is also not consistently caring for efficiency. So if you feel like improving it, that is good, but if you prefer to just leave this PR as it is, I can do this some other time.

**Comment by jamshark70** [comment]
I kind of hate to say this after all the work rejiggering the methods, but... I'm nervous about coupling the OSCFuncs with the message *creation*. When I started writing this, I was only a little nervous, but after finishing my remarks, actually I'm considerably nervous about it.

- **Pro** (OSCFunc in `getMsg`): `get`, `getn`, `query` etc. only make sense in a RT server, and if you're dealing with a RT server, it's nonsense to create a message and then never send it. Flipside: the normal use case for calling a `...Msg` method is to collect commands into a Score for NRT processing... but `get` is nonsense in NRT. So, sure, in theory there's the potential of creating orphan OSCFuncs, but in normal use, that won't happen.

- **Con** (OSCFunc in `get` instead): With the design currently in master, a user could respond to `/b_get`'s reply with a custom OSCFunc, by using `newMsg`, making her own responder, and sending the message manually. With the change, it becomes *mandatory* to install the standard responder, even if the user isn't interested in it. That is, the proposed change here assumes that the user will necessarily send the message and will necessarily use the standard responder -- but we don't know that. In general, programming languages should give tools to the user without ruling out what might appear to be creative abuse.

TBH I find the Con position more convincing. I can understand the reason for moving the OSCFuncs, but I disagree with it.

**Comment by patrickdupuis** [comment]
Thanks @telephon and @jamshark70 

### OSCFunc placement
I was only 50/50 on this one anyway. James seems to have a good point. I can move them back. I wonder: is there a `.listSendMsgWithReply` method we can use instead of having to create the `OSCFunc` explicitly?

### Performance and code duplication
I made these changes trying to avoid code duplication (both the bufnum.isNil check and Msg creation). It is not acceptable to decrease performance, however. I wonder if I need to go about this in the opposite way. All methods check for `nil` Buffers, and no methods call their corresponding `...Msg` methods. That way the code will be consistent and have better performance, but at the cost of duplication.

**Comment by telephon** [comment]
I didn't notice the OSCFuncs in the message creation code. I think it's not good to put it there, because it is supposed to just create the messages, nothing else.

**Comment by patrickdupuis** [comment]
This moves the `OSCFunc`s back to where they were initially.

Next up is the server messages.

**Comment by patrickdupuis** [comment]
These are the changed I now propose :

- Reverted the changes made to the `OSCFunc`s
- Methods no longer call their respective `...Msg` methods, which should improve performance a little over what was being done before (`write` and `writeMsg` for example)
- All methods check the `Buffer`'s validity without then checking it again when calling `...Msg`

Thank you for reviewing and testing 👍

**Comment by patrickdupuis** [comment]
Make sure you are looking at the latest changes. `fill` should have this check, as well as all the other methods.

**Comment by telephon** [comment]
ah good - sorry for the noise. Somehow the webpage showed me the wrong version.

**Comment by telephon** [comment]
@patrickdupuis is this ready to go?

**Comment by patrickdupuis** [comment]
Maybe @jamshark70 or @snappizz can give a look? The PR might need labelling and whatnot for the 3.9 change log.

**Comment by telephon** [comment]
looks good to me

**Comment by jamshark70** [comment]
Ok for me too.

**Pull request merged**
