### PR TITLE
[docs] - supercollider/supercollider/helpsource/classes/sinosc.schelp - adding a small example

### PR DESCRIPTION
**Pull request by tmm2018**
[docs] - supercollider/supercollider/helpsource/classes/sinosc.schelp - adding a small example

I've been most recently avoiding: 

- adding up examples of mine on supercollider documentation

the main reason fo that:

- supercollider documentation has been stabilized for already some time
- it's more worthy to improve it's overall quality, by adding in grammar checks, etc.

even though:

- I wrote this code example yesterday
- someone took the effort of reviewing it (lfnoise reddit user)
- i decided it could be a good pick to commit it

thank you so much

### CODE REVIEW

**Comment by tmm2018** [comment]
added in a couple of frequencies to the array. attenuated the amplitude range

**Comment by tmm2018** [comment]
hey telephone

- thank for having taken the time to review most of my input on this PR.
- i fixed everything you asked me to in the context of this specific PR. 
- let's way for the feedback of others, and see what we can do.

cheers, and thank you so much for giving me the honour to contribute to this amazing community

**Comment by brianlheim** [comment]
also please do not arbitrarily change whitespace

**Comment by snappizz** [comment]
sorry, but i think the list of examples in this helpfile is fine as is.

**Pull request closed without merging**
