### PR TITLE
Midi connect all

### PR DESCRIPTION
**Pull request by sensestage**
Fix for issue #1194.

### CODE REVIEW

**Comment by sensestage** [comment]
Please test on other platforms!

**Comment by sensestage** [comment]
Test:

```
MIDIIn.connectAll;
MIDIClient.sources; // should print currently available sources

// attach new midi device

MIDIIn.connectAll;
MIDIClient.sources; // should print currently available sources - so including the newly attached device
```

**Comment by LFSaw** [comment]
Tested successfully on OSX.
Test code:
```
// connect a midi interface
MIDIIn.connectAll
MIDIClient.sources
MIDIClient.destinations

// -> midi interface shows up in sources and destinations

// unplug device
MIDIIn.connectAll
MIDIClient.sources
MIDIClient.destinations

// -> midi interface removed from sources and destinations
```

**Comment by LFSaw** [comment]
@sensestage 's commits only affect Linux, so this still works on OSX.

**Comment by sensestage** [comment]
It not only still works on OSX, it works better - it connects to newly found ports now :)

**Comment by sensestage** [comment]
I also sneaked in a verbosity flag that sets whether or not to post the found MIDI ports.
This was a feature request from the Modality team.

**Comment by LFSaw** [comment]
well, that's what I meant: the patch does what it says, ergo it works :)

**Comment by bagong** [comment]
I can confirm OSX with LFSaw's code. On Windows it's a mixed bag, not sure what to expect ;)

After starting SC with three midi controllers (fca610, nanocontrol, sd-50) connected via usb I get:

    MIDI: cannot open device 1 3 PortMidi: `Host error'
    MIDI: Host error The specified device is already in use.  Wait until it is free, and then try again.
    MIDI Sources:
    	MIDIEndPoint("FCA610 MIDI 1", "FCA610 MIDI 1")
    	MIDIEndPoint("nanoKONTROL2", "nanoKONTROL2")
    MIDI Destinations:
    	MIDIEndPoint("Microsoft MIDI Mapper", "Microsoft MIDI Mapper")
    	MIDIEndPoint("Microsoft GS Wavetable Synth", "Microsoft GS Wavetable Synth")
    	MIDIEndPoint("FCA610 MIDI 1", "FCA610 MIDI 1")
    	MIDIEndPoint("nanoKONTROL2", "nanoKONTROL2")
    -> MIDIIn
    -> [ MIDIEndPoint("FCA610 MIDI 1", "FCA610 MIDI 1"), MIDIEndPoint("nanoKONTROL2", "nanoKONTROL2") ]
    -> [ MIDIEndPoint("Microsoft MIDI Mapper", "Microsoft MIDI Mapper"), MIDIEndPoint("Microsoft GS Wavetable Synth", "Microsoft GS Wavetable Synth"), MIDIEndPoint("FCA610 MIDI 1", "FCA610 MIDI 1"), MIDIEndPoint("nanoKONTROL2", "nanoKONTROL2") ]

The dramatical think happens after disconnect. After running MINIIn.connectAll, I get a long list of 
`errrr Portmidi: `Bad Pointer'

SC then get's into a state where these errors are produced at a very pace (one message every few seconds) and seems never to recover from this state.

**Comment by bagong** [comment]
Unfortunately I am not into MIDI, but I promise to have a look into it on Windows during the next week. Right now I have to go...

**Comment by sensestage** [comment]
ok - it might be that this lies in:

SC_PortMIDI.cpp lines 100-102:

```
	for( int i = 0 ; i < gNumMIDIInPorts; ++i ) {
		PmStream* midi_in = gMIDIInStreams[i];
		if( midi_in ) {
```

maybe it needs to be an explicit check for NULL?
```
if ( midi_in == NULL ) {
```

Also if you could run more separate tests:

```
MIDIIn.connectAll;

MIDIClient.list;

MIDIIn.disconnectAll;

MIDIClient.list;
```

And alternatively:

```
MIDIIn.connectAll;

MIDIClient.disposeClient;

// attach new device

MIDIClient.connectAll;
```

**Comment by bagong** [comment]
When rerunning MIDIIn.connectAll after disconnecting a device, I now get:
```
cannot close MIDI device: PortMidi: `Bad pointer'
cannot open MIDI iniput: PortMidi: Host error'
MIDI: Host error A device ID has been used that is out of range for your system.
-> MIDIIn
```

MIDIClient.list doesn't list anything, just
`-> MIDIClient`

MIDIClient.ini produces a list of devices. But it does not remove a device that has been unplugged, even after running MIDIClient.disposeClent and rerunning MIDIClient.init. That only happens if I reboot the interpreter.

Also adding a midi-device after MIDIClient as been started seems not possible by .disposeClient/.init or .disconnectAll/.connectAll

Unfortunately I am leaving to Hungary for two weeks tomorrow. I am doing this in a haste and won't be able to come back to it before mid July.

I uploaded a VS-build containing your midi and hid related pull-requests to:
https://drive.google.com/file/d/0B7igZrWv7UxdVGVSMmtQWFdFM1k/view?usp=sharing

Maybe somebody else can check with more detail.

**Comment by crucialfelix** [comment]
What's the status of this ? Better than it was, possibly not perfect on windows ?

Good enough for now ?

**Comment by sensestage** [comment]
I guess a good question is, does this make things worse on Windows than it was before?

**Comment by crucialfelix** [comment]
Its been waiting since June for testing on Windows. I will merge tomorrow unless some windows user comes forth and complains bitterly.

**Pull request merged**
