### PR TITLE
Quark hooks continued

### PR DESCRIPTION
**Pull request by telephon**
## Purpose and Motivation

This is a continuation of #5780.

See discussion there.

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks @telephon, this looks good and I'd like to include it in the next RC. Could you please rebase it on the `3.13` branch?

**Comment by dyfer** [comment]
Hello @telephon 
Sorry again for the mess with SCVersion.txt. I'm trying to fix it with upcoming merges between 3.13 and develop, but in the meantime could you possibly do interactive rebase on this branch and remove both commits that touch SCVersion.txt ([d34f26e](https://github.com/supercollider/supercollider/pull/5907/commits/d34f26ec7349391acb09e9a55fa50e37cbf1ec16) and [8d913cd](https://github.com/supercollider/supercollider/pull/5907/commits/8d913cdbf1637ea9384ac9115ef21c9f77ac29c3))?

**Comment by telephon** [comment]
I forgot how to do this. Do you have a hint?

**Comment by dyfer** [comment]
> I forgot how to do this. Do you have a hint?

Yes! :) 
https://github.com/supercollider/supercollider/wiki/Creating-pull-requests#rebasing-to-remove-commits

**Comment by dyfer** [comment]
@telephon would you be able to rebase this branch to remove the superfluous commits?

**Comment by telephon** [comment]
I hope this is how it should look like? I am not sure what the final state of this PR should be.

**Comment by dyfer** [comment]
@telephon thanks for making changes! It's close, but not quite there yet.
This PR should only include the changes regarding hooks, i.e. the last 7 commits (from https://github.com/supercollider/supercollider/pull/5907/commits/08b8628b41af9063f7fc443862768f971a48f849 to https://github.com/supercollider/supercollider/pull/5907/commits/88ddbd0fda2e14e188e02dcd38d3155f900a6e89). Specifically, https://github.com/supercollider/supercollider/pull/5907/commits/9729e255fe0414e050022390715980845d6cde7c and https://github.com/supercollider/supercollider/pull/5907/commits/ca2334719081501b9c221c3ac0e90fb8d6b3476d should still be removed. Sorry for the hassle! Please let me know if you need any help with this.

**Comment by telephon** [comment]
ah yes, so this should be better. Thanks!

**Review by dyfer — APPROVED** [review]
Looks good, thank you!

**Pull request merged**
