### PR TITLE
Supernova NRT fixes

### PR DESCRIPTION
**Pull request by Spacechild1**
## Purpose and Motivation

NRT synthesis is broken in Supernova.

Fixes https://github.com/supercollider/supercollider/issues/5270

Also contains a change that prevents duplicate creation of the default Group in the `Score.section` method.

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] This PR is ready for review

### CODE REVIEW

**Comment by sonoro1234** [comment]
Hi Chistof, I am a little busy now so it will take some days also.

**Review by sonoro1234 — APPROVED** [review]
Seems fine to me

**Comment by dyfer** [comment]
Thanks!

I've tried this PR, but the following code
```supercollider
(
var g;
Server.supernova;
Score.program = Server.program;
g = [
	[0, [\d_recv, SynthDef(\nrt, {Out.ar(0, SinOsc.ar(200.5, 0, -12.dbamp))}).asBytes]],
	[0.2, [\s_new, \nrt, 1001, 0, 0]],
	[10, [\c_set, 0, 0]] // finish
];
Score.recordNRT(g, nil, "~/Desktop/testNRTscsynth.wav".standardizePath); // synthesize
)
```
still produces an empty file.

Here's the output for the above example:
**supernova**
```
-> Score
Supernova booting
(...)
Performing non-rt synthesis:
late: 0.000000
  Next OSC bundle: 0.000000000
late: 0.000000
```
**scsynth**
```
-> Score
(...)
start time 0
nextOSCPacket 0
nextOSCPacket 0.2
nextOSCPacket 10
nextOSCPacket 10
```

(Also, possibly unrelatedly, if the destination folder does not exist, supernova reports `process completed`, while scsynth reports `Couldn't open non real time output file.`)

**Comment by Spacechild1** [comment]
@dyfer Are you sure you have actually rebuild Supernova?

With your example I get the following output:
```
Supernova booting
��0�Warning: cannot set thread affinity of audio helper thread

Performing non-rt synthesis:
  Next OSC bundle: 0.000000000
  Next OSC bundle: 0.000000000
  Next OSC bundle: 0.199999999
  Next OSC bundle: 10.000000000
  Next OSC bundle: 10.000000000

Non-rt synthesis finished in 0.009s
Peak summary:
  Channel 0: -12dB
  Channel 1: -infdB
```
The soundfile is 9.9999 seconds long and contains a sine tone.

**Comment by dyfer** [comment]
I just realized I did not, in fact, rebuilt supernova. Sorry, my bad! Running tests again

**Comment by Spacechild1** [comment]
> (Also, possibly unrelatedly, if the destination folder does not exist, supernova reports process completed, while scsynth reports Couldn't open non real time output file.)

I can have a look.

**Review by dyfer — APPROVED** [review]
Works as advertised, thank you!

NRT synthesis still continues if the destination path is unreachable. We can save this for another issue/PR, unless you feel like fixing it here.

**Comment by Spacechild1** [comment]
> unless you feel like fixing it here.

done :-)

**Review by dyfer — APPROVED** [review]
Thanks, works great!

**Comment by dyfer** [comment]
All looks good to me, ready to merge?

**Comment by Spacechild1** [comment]
For me yes! Thanks for the review!

**Pull request merged**
