### PR TITLE
[3.8] Update changelog and version number for 3.8.1

### PR DESCRIPTION
**Pull request by brianlheim**

### CODE REVIEW

**Comment by brianlheim** [comment]
@snappizz did I do this right?

**Comment by brianlheim** [comment]
@snappizz While I appreciate the review, the changes you pushed are worded somewhat strangely. gcc is a compiler, not a build system, and you build with it, not on it. "Include headers" is not a meaningful phrase; the only kind of header is one that you include. I've rephrased that sentence so that it is clearer than either of the previous versions.

"gcc" and "GCC" are both commonly used in this changelog and in general, so I don't see the reason for that capitalization, but I'll keep it.

**Comment by snappizz** [comment]
cool with me. one suggestion: reword to "There is no need to upgrade from 3.8.0 unless you are *unable to* build 3.8.0 yourself."

**Comment by patrickdupuis** [comment]
Maybe this? 

"There is no need to upgrade from 3.8.0 unless you are having issues building SuperCollider on your system using GCC 7."

**Comment by brianlheim** [comment]
Clarification: anyone who builds 3.8.0 with GCC 7 will get a build failure, and that is the only fix guaranteed by this patch release. Hoping this newest rewording is acceptable.

**Comment by patrickdupuis** [comment]
That's good!
________________________________

**Comment by dvzrv** [comment]
Something is broken with the ruby environment for the app bundler, if I understand correctly.
What can be done about it?

**Comment by brianlheim** [comment]
@dvzrv I've just been ignoring the CI feedback for this since we already know that 3.8.0 builds fine. Not worth maintaining IMO. Things are fine on the active branches.

**Comment by snappizz** [comment]
i think we agreed to put this one on hold until #3275 is merged.

**Comment by brianlheim** [comment]
> i think we agreed to put this one on hold until #3275 is merged.

I don't remember that discussion. Why?

**Comment by snappizz** [comment]
never mind, my memory must be going. let's merge this

**Comment by brianlheim** [comment]
@snappizz It still needs to be updated based on the recent merge :)

**Pull request merged**
