### PR TITLE
classlib: remove old workaround code in Recorder.makePath

### LINKED ISSUE #3307: Use standard recording path for Windows 10 in Recorder.makePath
On Windows 10 ```Date.localtime.stamp``` evaluates to YYMMDD_HHMMSS for both SuperCollider 3.8.0 and 3.9.0-beta.

Why is there still an override to use ```Main.elapsedTime.round(0.01)``` for Windows platforms?

https://github.com/supercollider/supercollider/blob/769f78c0367ab03c6412e37636f310a68f0d5a56/SCClassLibrary/Common/Control/Recorder.sc#L175

Is Date broken on earlier versions of Windows?

I would suggest to find a way to use ```Date.localtime.stamp``` at least for Windows 10 which appears to be working fine in this regard.

### PR DESCRIPTION
**Pull request by brianlheim**
Fixes #3307.

Please don't merge until 3.9.1. This code is probably fine, but for stability's sake I don't want to risk it.

### CODE REVIEW

**Comment by antonhornquist** [comment]
I suggest to merge this to 3.9.0. :) The [History change](https://github.com/supercollider/supercollider/issues/3044) is practically the same issue and its fix is included in 3.9.0-beta.

**Comment by brianlheim** [comment]
3.9.1 is scheduled to come out just a month or so after 3.9.0; not too long to wait.

**Comment by brianlheim** [comment]
I don't know what you mean. It already works afaict,

**Comment by adcxyz** [comment]
sorry for the noise, all is well! 
just early morning disorientation...

**Comment by antonhornquist** [comment]
3.9.1 is fine. Can we close this?

**Comment by brianlheim** [comment]
@antonhornquist No need to close; this is milestoned 3.9.1, so we'll just keep it open until it's time to merge. :)

**Comment by antonhornquist** [comment]
Fine. Is 3307 also to be kept open until 3.9.1 release?

**Comment by brianlheim** [comment]
@antonhornquist Yes.

**Pull request merged**
