### PR TITLE
Update Ringz.schelp

### PR DESCRIPTION
**Pull request by porres**
typo, it was missing the article

### CODE REVIEW

**Comment by telephon** [comment]
great! it would be good if you give it a standard commit message, like "help: fix typo in Ringz.schelp".

**Comment by porres** [comment]
ok, sorry, this is my first time helping out, i'm still kinda lost and confused actually - did it all just get approved by the way?

**Comment by bagong** [comment]
Yes ;)

**Comment by telephon** [comment]
Thanks!

**Pull request merged**
