### PR TITLE
Classname as Selector crashes

### PR DESCRIPTION
**Pull request by baconpaul**
This fixes https://github.com/supercollider/supercollider/issues/669

1 Object: 2

If you use a registered classname as a selector it would think it was a method, but resolve the object as the symbol and not check. Then if it actually looked it up you got segfaulted.

So this checks and puts you in the same error path that you get with

1 FooBazNotObject: 2

or

1 fooBazNotAMethod: 2

### CODE REVIEW

**Comment by baconpaul** [comment]
Oh also (and apologies for not have found this in the doc): I have small test cases I used to make sure this worked of course. Is there a way I can add those to standard regtest suite for SC? It wasn't clear to me from the developer doc. 

Hope you can tolerate the newbie question!

**Comment by crucialfelix** [comment]
Yes please post the test case. What a silly bug you've found !

You can add it to the test suite, but after the fix is in so that Travis
doesn't segfault all the time.

Thanks

**Comment by baconpaul** [comment]
Great. I'm really sorry, where do I commit it and how do I get it introduced into the suite? I can do that as another pull request when this one is merged. Happy to just read a doc but I can't find it, and the test suite directory in my fork looks tiny.

Oh and I didn't find the bug; I just fixed it. Someone else deserves credit for filing a bug report with a clear repo! I picked up a couple this weekend that looked tractable so I could learn the code some and set up my dev environment. 

Thanks

**Comment by telephon** [comment]
re the test suite: it is here https://github.com/supercollider-quarks/CommonTests
just poke around there, it's fairly easy to just modify some existing tests to fit the needs.

**Comment by baconpaul** [comment]
Got it. Once this is merged I'll send a pull request for the updated Methods test. Thanks very much!

**Comment by baconpaul** [comment]
Thanks for merging! Here's the test pull request to match. https://github.com/supercollider-quarks/CommonTests/pull/6

**Pull request merged**
