### PR TITLE
added selectIndex and rejectIndex to SequenceableCollection

### PR DESCRIPTION
**Pull request by LFSaw**
this adds methods 

```
selectIndex(function)
rejectIndex(function)

selectIndexAs(function, class)
rejectIndexAs(function, class)
```

to ```SequenceableCollection```. They are straight-forward implementations complementing ```select``` and ```reject``` with a way to return indices rather than values as does ```detectIndex``` for ```detect```.

### CODE REVIEW

**Comment by sensestage** [comment]
very useful!

**Comment by LFSaw** [comment]
> what would be a use case for ```selectIndexAs```?

```
List[1, 4, 6, 7, 9].selectIndexAs(_.odd, Array)
```

**Comment by adcxyz** [comment]
thanks, really useful, and fits exactly to the pattern one would expect.

**Comment by nuss** [comment]
Wouldn't it be adequate to implement `selectIndex`, selectIndexAt`, `rejectIndex`, `rejectIndexAt` for `Collection` like their counterparts `select`, `selectAs`, `reject`, `rejectAs`?

**Comment by telephon** [comment]
> On 28.06.2015, at 14:19, LFSaw <notifications@github.com> wrote:
> 
> what would be a use case for selectIndexAs?
> 
> List[1, 4, 6, 7, 9].selectIndexAs(_.odd, Array)

Assuming that by default it would return an array anyway, would you have one for that, too?

**Comment by LFSaw** [comment]
@nuss :
> Wouldn't it be adequate to implement `selectIndex`, `selectIndexAt`, `rejectIndex`, `rejectIndexAt` for `Collection` like their counterparts `select`, `selectAs`, `reject`, `rejectAs`?

yes but it'd break for non-sequenceable collections.

@telephon :
> Assuming that by default it would return an array anyway, would you have one for that, too?

this would work like that, yes, however, it would break the common pattern for those operations which is that they return an object of the receiver's type. Also, why should a `List` return an `Array`? I'd find that counter-intuitive.

**Comment by nuss** [comment]
> yes but it'd break for non-sequenceable collections.
Ah, yes, calling `selectIndex` on a `Set` wouldn't be overly useful...

**Comment by telephon** [comment]
>>Assuming that by default it would return an array anyway, would you have one for that, too?

>this would work like that, yes, however, it would break the common pattern for those operations which is that they return an object of the receiver's type. Also, why should a List return an Array? I'd find that counter-intuitive.

I'm not trying to be pedantic, just thinking it through.

The methods that return the same class (species) IIRC are those which return some sort of subset of the collection. An array of indices is something very different from a list of other things. An example, albeit a rather rare one, would be that of an ````Order````. If you call selectIndex on it, it would return an Order of indices, not really what you want. The default can bite you there.

This is why I somehow prefer a plain simple array in this case, even if I completely understand your argument.

**Comment by telephon** [comment]
>Ah, yes, calling selectIndex on a Set wouldn't be overly useful...

it is only defined for SequenceableCollections
One could add an equivalent for Dictionary

**Comment by LFSaw** [comment]
> Assuming that by default it would return an array anyway, would you have one for that, too?
> 
>     this would work like that, yes, however, it would break the common pattern for those operations which is that they return an object of the receiver's type. Also, why should a List return an Array? I'd find that counter-intuitive.
> 
> I'm not trying to be pedantic, just thinking it through.
> 
> The methods that return the same class (species) IIRC are those which return some sort of subset of the collection. An array of indices is something very different from a list of other things. An example, albeit a rather rare one, would be that of an Order. If you call selectIndex on it, it would return an Order of indices, not really what you want. The default can bite you there.
> 
> This is why I somehow prefer a plain simple array in this case, even if I completely understand your argument.

I understand what you say. However, my preference would be to model `selectIndex` and `rejectIndex` as close as possible to `select` and `reject`. This way it is easy to interchange them in code while developing. A practice, I actually do quite often in order to try out different ideas.

**Comment by telephon** [comment]
Well, ok, not completely convinced, but at least the result will be a SequenceableCollection.

**Comment by LFSaw** [comment]
@adcxyz , do you have an opinion?

**Comment by adcxyz** [comment]
was going to answer : 'yes.' ;-) 
but can also elaborate - according to the Principle of Least Surprise, 
collect, select, reject etc should return a collection of the same species;
most do, and that list does not is actually surprising. 

Best option for me:
* do a full comparison for consistency of collect, select, reject across all implementations,
* model selectIndex et al on those,
* return same class as default
* overwrite with Array where same class is confusing 

Dictionaries and Orders actually do not need selectKeys or similar:
the resulting dicts and orders already have the proper keys and indices ! 
2c 
adc

**Comment by telephon** [comment]
Ok, yes, I think it makes sense like this.

**Comment by LFSaw** [comment]
> do a full comparison for consistency of collect, select, reject across all implementations,

this is what I found: All of these cases create an instance of its type (apart from `WeighBag` which, I guess, is an implementation by @telephon :) ).

```
Collection{
	collect { | function |
		^this.collectAs(function, this.species);
	}
	select { | function |
		^this.selectAs(function, this.species);
	}
	reject { | function |
		^this.rejectAs(function, this.species);
	}
	collectAs { | function, class |
		var res = class.new(this.size);
		this.do {|elem, i| res.add(function.value(elem, i)) }
		^res;
	}
	selectAs { | function, class |
		var res = class.new(this.size);
		this.do {|elem, i| if (function.value(elem, i)) { res = res.add(elem) } }
		^res;
	}
	rejectAs { | function, class |
		var res = class.new(this.size);
		this.do {|elem, i|
			if (function.value(elem, i).not) {res.add(elem)}
		}
		^res;
	}
}

Dictionary {
	collect { arg function;
		var res = this.class.new(this.size);
		this.keysValuesDo { arg key, elem; res.put(key, function.value(elem, key)) }
		^res;
	}
	select { arg function;
		var res = this.class.new(this.size);
		this.keysValuesDo { arg key, elem; if(function.value(elem, key)) { res.put(key, elem) } }
		^res;
	}
	reject { arg function;
		var res = this.class.new(this.size);
		this.keysValuesDo { arg key, elem; if(function.value(elem, key).not)
			{ res.put(key, elem) } }
		^res;
	}
}

Order {
	collect { arg function;
		^this.copy.array_(array.collect(function));
	}

	select { arg function;
		var res = this.class.new;
		this.indicesDo { |item, i|
			if(function.value(item, i)) { res.put(i, item) }
		}
		^res
	}

	reject { arg function;
		var res = this.class.new;
		this.indicesDo { |item, i|
			if(function.value(item, i).not) { res.put(i, item) }
		}
		^res
	}
}

Pattern {
	collect { arg function;
		^Pcollect.new(function, this)
	}
	select { arg function;
		^Pselect.new(function, this)
	}
	reject { arg function;
		^Preject.new(function, this)
	}
}

WeighBag {
	collect { arg func; 
		items = items.collect({ arg item, i; func.value(item, i) }); 
	}
}

SparseArray {
	collect { arg function;
		^this.class.reduceArray(
			this.asArray.collect(function),
			default !? { function.value(default, 0) }
		)
	}

	select { arg function;
		^this.class.reduceArray(
			this.asArray.select(function),
			if(default.notNil and: { function.value(default, 0) }) { default }
		)
	}

	reject { arg function;
		^this.class.reduceArray(
			this.asArray.reject(function),
			if(default.notNil and: { function.value(default, 0).not }) { default }
		)
	}
}
```


> model selectIndices et al on those,
> return same class as default

this would be how it is proposed in this PR.

> overwrite with Array only where same class is confusing

debatable.

**Comment by telephon** [comment]
> All of these cases create an instance of its type (apart from WeighBag which, I guess, is an implementation by @telephon :) ).

I was young and naive back then :)

**Comment by telephon** [comment]
The classes 
- Order
- SparseArray
- Dictionary
- Set (maybe Collection by default?)
should return an Array, I suppose. 

The Pattern implementation is interesting - it isn't easy to come up with a case I would use it for (not a bad thing in itself).

P.S. WeighBag needs to be fixed, this is really bad, I hope nobody relies on it ...

**Comment by LFSaw** [comment]
> On 01. Jul 2015, at 23:24, Julian Rohrhuber <notifications@github.com> wrote:
> 
> The classes
> 
> 	• Order
> 	• SparseArray

why?

> 	• Dictionary

should return a Set of keys, I'd imagine... (no order...)

> 	• Set (maybe Collection by default?) should return an Array, I suppose.

Set should not implement `*Index` at all, no?


> The Pattern implementation is interesting - it isn't easy to come up with a case I would use it for (not a bad thing in itself).

E.g. WaveSet manipulation.


> 
> P.S. WeighBag needs to be fixed, this is really bad, I hope nobody relies on it ...

:+1:

**Comment by adcxyz** [comment]
> The classes
 	• Order
 	• SparseArray
 	• Dictionary
> should return a Set of keys, I'd imagine... (no order...)
actually, if they return the same species, they keep the indices or keys in the returned collection 
already! so no need for a separate method.
 	• Set (maybe Collection by default?) should return an Array, I suppose.
> Set should not implement `*Index` at all, no?
agreed, Set has no indices 

repeat from earlier post:
selectIndices, rejectIndices would be clearer that selectIndex, etc: 
they return the selected indices, not a single index.

best a

**Comment by LFSaw** [comment]
ok, I messed it up, apparently. did a rebase and somehow added all these other files... rargh!

**Comment by telephon** [comment]
well no problem, just reset the branch to the last reasonable commit (with sourcetree that is really easy) and make a new branch from it.

**Comment by LFSaw** [comment]
like so? 
https://github.com/supercollider/supercollider/pull/1591

**Comment by LFSaw** [comment]
closes and moved to #1591

**Pull request closed without merging**
