### PR TITLE
supernova: use c++14 move captures and proper move semantics

### PR DESCRIPTION
**Pull request by timblechmann**
have been using this for almost a year

### CODE REVIEW

**Comment by bagong** [comment]
Felix, this requires CMake 3.1 and is not tested on Windows...

**Comment by timblechmann** [comment]
@bagong to correct your statement, supernova requires cmake-3.1 and c++14.

**Comment by bagong** [comment]
The fact that I have verified here is cmake version: Debian Jessie and Ubuntu 15.04 ship with cmake 3.02. I have not tested for compiler versions, so if your c++ version causes further trouble on those platforms the more so it is something that cannot be introduced **tacitly**. @crucialfelix , either consider supernova Tims private hobby and state so explicitly, or wait until tests are done. This commit is clearly premature. We cannot return to the practice of committing stuff trust based where no trust is deserved. You are creating endless frustration among people who take the time to test. If Tim cannot stop his ruthless style of pushing through stuff that doesn't care about others, his PRs cannot be committed until it is verified that they do not do harm.

**Comment by timblechmann** [comment]
@bagong please read the title of the PR before using the word **tacitly**. as always, people who want to use new supercollider on old platforms can easily update their toolchains.

furthermore, if you don't trust my the code, you are more than welcome to review it. understanding is always a better way to ensure code quality than testing. and testing is better than spreading false claims and FUD.

fwiw, as developer and maintainer of supernova i still take the freedom to define it's minimum requirements.

**Comment by bagong** [comment]
@crucialfelix , I am not willing to continue this uncooperative discussion. In my view Tim has just expressed that SuperNova is not considered to be part of SuperCollider, where - as I understand it - minimum requirements and platform support are decided collectively.

**Comment by miguel-negrao** [comment]
The next stable debian version is only coming out in 2017, on the other hand debian testing from november last year (i.e. my machine) is on gcc 5.2.1 and cmake 3.3.2. Debian stable updates very slowly, I don't think the development branch of SC (i.e. master) should be expected to compile all the time on debian stable. Likewise the latest version of ubuntu (16.04) [has gcc 5.3.1](http://packages.ubuntu.com/xenial/gcc).  i think c++14 should work on [any gcc 5.x ](https://gcc.gnu.org/projects/cxx-status.html#cxx14)(not 100% sure). 

Wouldn't disabling compiling supernova still allow to compile the rest of SC when on gcc 4.x ? What about the cmake changes, would they break compiling with supernova disabled ?

> where - as I understand it - minimum requirements and platform support are decided collectively.

Yes and no. I think in the end you get to determine that in the proportion that you contribute to the project or a part of the project. Now supernova is almost 100% Tim's code, as far as I know there have been almost no extensive code contributions into that code base from anyone else, so Tim is in fact the only person maintaining and developing that code, and I can understand that he wants to use the best, most advanced technologies available. In fact, we should be applauding that someone is doing exactly that. Off course that shouldn't be allowed to break compilation for everyone else (talking hypothetically, don't think that would be the case), but no one is forcing us to merge the PR, it was just offered as a proposal. If you think it is too soon to merge it, make a case for that, and if people agree then it waits before being merged, isn't that reasonable for all concerned ?

**Comment by bagong** [comment]
Well, the minimum requirements are not well defined. On Mac and Windows this is no problem, you can install any version without problem. On Linux it is. So far for linux they were considered to be 2.9.

Two points are not clearly defined in this project, and that is the root of the problem:

- is the cmake minimum requirement for Linux defined collectively?
- is supernova part of supercollider

@sonoro, have you tried this on Windows?

**Comment by timblechmann** [comment]
* init-captures are available in gcc-4.9, clang-3.4 and msvc-2015
* this change has no implications for non-supernova builds of sc
* supernova always had higher requirements than the rest of supercollider, as it was using a modern coding style.
* the cmake requirements of supernova changed, not for the rest of supercollider
* cmake can easily be installed on linux either by compiling from sources or by downloading binaries from https://cmake.org/download/

**Comment by crucialfelix** [comment]
Shit, sorry.

**Comment by bagong** [comment]
@timblechmann , you points show that you are well aware of the consequences of your PRs, but they do not answer the two questions I have asked.

**Comment by timblechmann** [comment]
@bagong, it was not written as reply to your questions.

* usually the minimum requirements are defined by those people, who maintain the code. unfortunately in supercollider it is a bit different, as apparently robust architecture and long-term maintenance doesn't matter so much and those people win, who shout the loudest, not the ones who know or work with the code.

* you might want to consult the archives of the sc-dev list about details of the relationship between supernova and supercollider.

btw, how do you get the impression that the minimum cmake requirement was 2.9? this is something totally new to me and quite surprising as no cmake version 2.9 was ever released.

**Comment by bagong** [comment]
omg @timblechmann , the only thing you seem to want to do is demonstrate your superiority. No interest for SC as a community driven project.

**Comment by timblechmann** [comment]
@bagong lol ...

**Comment by telephon** [comment]
@miguel-negrao asked:

>Wouldn't disabling compiling supernova still allow to compile the rest of SC when on gcc 4.x ? What about the cmake changes, would they break compiling with supernova disabled ?

any clues?

The good thing about cmake is that we can (maybe) separate different parts of the system with different requirements.

@bagong it can be useful to be bold, here I suspect that it might have been a misunderstanding actually.

@timblechmann it would be useful if you could avoid to express sarcasm about technical issues that are trade-offs. We all know too well that is considered "modern" is often very different, in particular among the experts in a topic.

**Comment by telephon** [comment]
please, respect each others' work and knowledge.

**Comment by timblechmann** [comment]
@telephon the terms "modern c++" and "modern cmake" are actually quite well-defined (compare https://herbsutter.com/elements-of-modern-c-style and https://rix0r.nl/blog/2015/08/13/cmake-guide/ or any of the other google hits).

> > Wouldn't disabling compiling supernova still allow to compile the rest of SC when on gcc 4.x ? What about the cmake changes, would they break compiling with supernova disabled ?

> any clues?
> The good thing about cmake is that we can (maybe) separate different parts of the system with different requirements.

as mentioned: 
* "the cmake requirements of supernova changed, not for the rest of supercollider"
* "init-captures are available in gcc-4.9"

----

fwiw, i closed all my open PRs. i'm not planning to contribute back any improvements as long as the current situation persist. modernizing could make sc more robust and help the long-term maintenance, but apparently that's not the focus. nor do reviewers try to understand the code and the implications.

if supercollider wasn't GPL, i'd ask those people who claim that i'm not interested in the supercollider community not to use any code that i've written (there might be some pre-64bit, pre-ide, pre-simd-optimized versions of supercollider from the time before i managed the releases for which this applies).

**Comment by bagong** [comment]
@timblechmann , you are indirectly referring to me, so here my take on this: decisions need to be made consensually, and the consensus needs to be sought before facts are created. The outset of this controversy was that this merge created facts before a consensus was found. The rest are escalating emotions because a discussion was not lead in a cooperative manner. 

I have voiced the concern over creating facts before seeking consensus several times, and even suggested you ways how to make finding the consensus easier. You knew what this PR would break and you did not bother to mention it. To me this means you are not considering the needs of some members of this community.

**Comment by jamshark70** [comment]
The thing about temper tantrums is, you think you're doing the right thing at the time. Later, you'll look back on it and think, jeez, I was being a real sh!t. I still cringe a little to think of some of the things I said to crucialfelix back in the day.

This thread here is really embarrassing to read.

**Comment by bagong** [comment]
I've already asked Chris for apology in a private email, it is not his fault. I am pretty sure he didn't know what that merge implied.
To the rest I stand. The lines as to what is to be committed to master are not defined clear enough, and Tim's PRs - as brilliant as they may be from one perspective - continuously overstep the lines that I consider fruitful and inclusive for SC development. He has a right to his views, and I have a right to mine. What is needed is a better definition of that line and a community decision how this line is to be drawn. The travis builds alone are not precise enough. I have voiced that concern when the Linux build was defined for Travis, and nobody felt the need to speak up. So this PR happened to be the case when things escalated to a angry level. I hope this discussion will be lead now.

**Comment by jamshark70** [comment]
Perhaps a way forward is to draw up a timeline for dropping support for older compilers.

Tim is objectively correct that we must do it sometime, and his observation (that we can always find excuses to delay) is also correct. (FWIW I don't like being forced to upgrade my compiler either, but that doesn't change the correctness of Tim's assertions).

Rainer is correct that surprising users with new compatibility requirements is bad for community.

If we had a timeline, Tim would not be expected to wait indefinitely, *and* users would have advance warning, eg, "On August 1, you will be required to use gcc x.y.z."

Planning a timeline will involve argumentation of its own, but it's got to be better than the 40+ messages from github I got this morning.

**Comment by bagong** [comment]
Another consideration is locking out platforms. Requiring GCC 4.9 means locking out MinGW-Windows from master. So either this needs to be fixed, or the MinGW-Windows build needs to be dropped. Which as a consequence locks out supernova from Windows. These are hard decisions, but if they are not taken, tensions like the ones we experienced here, are bound to recur. 

My main point is that they must be taken by the community, and not as something that "accidentally" slipped in through a single contribution.

**Comment by snappizz** [comment]
I don't want to get involved here, but it's kind of pressing that the master branch broke. I humbly suggest that we revert this PR until we reach a consensus.

**Comment by jamshark70** [comment]
> These are hard decisions, but if they are not taken, tensions like the ones we experienced here, are bound to recur.

Yes, and without some sort of procedure -- a concrete plan with specific points that can be debated on specific grounds -- then we're stuck with endless passive-aggressive sarcasm from one side and resistance on the other. I think at least we could all agree that the current approach is not working...

**Comment by timblechmann** [comment]
> Requiring GCC 4.9 means locking out MinGW-Windows from master. [...] Which as a consequence locks out supernova from Windows.

http://mingw-w64.org/doku.php/download

> it's kind of pressing that the master branch broke

last time i checked, supernova was disabled by default on windows. fwiw, the buildserver builds pass. nothing is broken.

**Comment by snappizz** [comment]
Ah I see, didn't know about the supernova/windows situation.

Since this PR has bumped up some minimum dependencies, we need to update the installation docs.

**Comment by crucialfelix** [comment]
I think we've all gotten a lot better and our work and communication process here. When something like this happens (as in right now) let's just take the steps to improve and prevent.

Emotions and positional-arguments (my position against yours) are impediments to clear thinking. 

TBH I merged this quickly because Tim tried to claim the other day that I leave PRs for too long; something about a PR that was there for a year. Which wasn't me - I was the one who cleared the pipeline. So to prove that I went and jumped the gun and merged this one. Thus proving that arguing is bad for decision making.

Sorry again for jumping the gun in merging this.

**Comment by telephon** [comment]
Your analysis is very convincing. Thank you for keeping this clarity, steady already over a long time.

**Comment by miguel-negrao** [comment]
Was there an official  minimum requirement for cmake or not  ? Shouldn't the minimum requirements match what the build server has, then it becomes very easy to know (in osx and linux at least) if the minimum requirements were broken or not.  

Going forward, what about making the current oficial minimum gcc 5.1 (released April 22, 2015) and cmake 3.2.3 (released Jun 1 2015) ? Both are more or less a year old, shouldn't that be enough time for developers to update their toolchains ?

**Comment by muellmusik** [comment]
Yes, thanks Chris!

**Comment by sonoro1234** [comment]
Could build on mingw with
```
set PATH=%PATH%;C:\cmake-3.5.2-win32-x86\bin\;
SET PATH=C:\Qt\5.5\mingw492_32\bin;C:\Qt\Tools\mingw482_32\bin;%PATH%
SET CMAKE_PREFIX_PATH=C:\Qt\5.5\mingw492_32
cmake  -G"MinGW Makefiles"  -DSUPERNOVA=ON   -DSSE2=ON   ..
```

**Comment by sonoro1234** [comment]
this warning appeared alot
```
C:/SupercolliderRepos/scfork/supercollider/external_libraries/boost/boost/detail/winapi/GetLastError.hpp:20:17: note: #pragma
 message: This header is deprecated, use boost/detail/winapi/get_last_error.hpp instead.
 #pragma message "This header is deprecated, use boost/detail/winapi/get_last_error.hpp instead."
                 ^
```

**Comment by crucialfelix** [comment]
Let's discuss the requirements policy here:
https://github.com/supercollider/supercollider/issues/2143

and we can write it up so it is clear.  

I think we DO want to move forward and we do want the code base to be attractive for all of us to work on. We just have to organize that so we don't make it impossible for more casual users to compile it.

**Comment by crucialfelix** [comment]
I don't see a problem with allowing supernova to use any advanced toolchain; it's the high performance server and it should be able to move forward and test newer performance features. Those features will trickle down to sclang/scsynth. 

It should be avant-garde IMO. Tim shouldn't have to compromise on the build system for it.

If travis doesn't build it, then we would have to drop supernova from testing.

This PR doesn't actually break master. It does mean some documentation needs to be updated vis a vis build requirements for supernova.

**Comment by timblechmann** [comment]
@crucialfelix i didn't criticise you for not merging stuff fast enough. nor did i blame people personally for the bugs they introduced when fixing them, as i consider that as bad style. especially those people contributed code, not words.

actually you are one of the few people who actually merge stuff and take the time consuming and thankless job of managing releases. i know from my own experience that it's a shitload of work and not a thankful job as people simply take it for granted and at one point will accuse you not to care about the community.

**Comment by crucialfelix** [comment]
OK, maybe what you meant was that if a release branch is opened and then I delay merging that one then it would get out of sync. Which is true - that's why I am delaying opening the release branch until it really is ready to be an RC and go into the release process. We want to prevent such verschmelzenstau.

**Pull request merged**
