### PR TITLE
Refactor EnvirGui

### PR DESCRIPTION
**Pull request by adcxyz**
EnvirGui can show parameters flexibly: a number is shown on an EZSlider, a range is shown on an EZRanger, anything else is shown on an EZText. 
This was done in the EnvirGui class by creating widgets as needed, which led to occasional annoying display glitches - double labels, views being invisible by accident, which are hard to reproduce.
This refactor encapsulates the switchable display modes into a single class, ParamView, and does the switching by setting visibility only, which is much more reliable and clearer to read.
As it fixes glitches, it should go into the 3.7 release.

### CODE REVIEW

**Comment by crucialfelix** [comment]
Note that you shouldn't have merged master into your topic branch. Now all of those commits are included in this pull request.

It will merge fine and any duplicate hashes will be ignored, but its not good practice.

If you have a topic branch, don't worry if its not up to date. All of those changed files are different than the files your PR changes.

**Comment by adcxyz** [comment]
hi chris, 

> On 09/12/2015, at 19:31 , Chris Sattinger <notifications@github.com> wrote:
> 
> Note that you shouldn't have merged master into your topic branch. Now all of those commits are included in this pull request.
> 
> It will merge fine and any duplicate hashes will be ignored, but its not good practice. 
> 
> If you have a topic branch, don't worry if its not up to date. All of those changed files are different than the files your PR changes. 

ok, thanks for the clarification. I was not sure what the best practice is, 
and thought it safer to check with the current master. 

is it still possible to merge the PR in without the duplicate commits?

best a

**Comment by crucialfelix** [comment]
afaict but we should do the merge on our own machine first in case of an accident. not using the BIG DANGEROUS GREEN MERGE BUTTON.

github shows no conflicts, I'm sure it will be fine.

**Comment by timblechmann** [comment]
```
compiling class library...
initPassOne started
	NumPrimitives = 711
initPassOne done
	compiling dir: '/usr/local/share/SuperCollider/SCClassLibrary'
	compiling dir: '/usr/local/share/SuperCollider/Extensions'
	compiling dir: '/home/tim/.local/share/SuperCollider/Extensions'
	compiling dir: '/home/tim/.local/share/SuperCollider/downloaded-quarks/JITLibExtensions'
	compiling dir: '/home/tim/.local/share/SuperCollider/downloaded-quarks/Modality-toolkit'
	compiling dir: '/home/tim/.local/share/SuperCollider/downloaded-quarks/FPLib'
	compiling dir: '/home/tim/.local/share/SuperCollider/downloaded-quarks/ScalaTunings'
	pass 1 done
ERROR: Variable 'widgets' not defined.
  in file '/home/tim/.local/share/SuperCollider/downloaded-quarks/JITLibExtensions/SystemOverwrites/extMakeEnvirGui.sc'
  line 97 char 22:

  			var widge = widgets[i];
                        
  			if (widge.isKindOf(EZSlider) or: { widge.isKindOf(EZRanger) }) {
-----------------------------------
ERROR: Variable 'widgets' not defined.
  in file '/home/tim/.local/share/SuperCollider/downloaded-quarks/JITLibExtensions/SystemOverwrites/extMakeEnvirGui.sc'
  line 271 char 22:

  			var widge = widgets[i];
                        
  			if (newSpec != specs[key]) {
-----------------------------------

```

**Comment by adcxyz** [comment]
fixed already in jtilib extensions, just update to latest

**Pull request merged**
