### PR TITLE
class library: only one server meter by default

### LINKED ISSUE #5545: Many meters we have.
## Environment

* SuperCollider version: 3.12
* Operating system: Mac OS 10.13.6

## Steps to reproduce

Press Cmd+M more than once. 
Move a meter. 
See! 
More than one meter.

## Expected vs. actual behavior

I dare to dream of a world where SuperCollider does not open up more than one server meter. 
Instead SC would show me the one I already have open when I press Cmd+M.

### PR DESCRIPTION
**Pull request by telephon**
## Purpose and Motivation

This fixes #5545. ServerMeter now behaves like Scope. By result of the discussions in #5549, it may make sense to rethink the design of all server windows, and potentially an easy way to handle unique windows.

A refactoring of the server views is recommended, this is just the minimal step to fix the issue at hand.

Multiple ServerMeters can be created by directly instantiating the object (like Stethoscopse for multiple scopes).

Thanks to @capital-G and everyone else for discussion.

## Types of changes

- Bug fix
- Breaking change

## To-do list

- [x] Code is tested
- [x] This PR is ready for review

### CODE REVIEW

**Comment by telephon** [comment]
@dyfer it might be a candidate for the 3.13.0-rc2, just an annoying thing that is finally fixed.

It does change behaviour, this is why I have stated it is a `Breaking change`. But it fixes also something that wasn't good.

Suggestions welcome.

**Comment by muellmusik** [comment]
Strongly support this!

**Comment by dyfer** [comment]
Thanks @telephon 
Could you rebase this on the `3.13` branch? I'd like to get it in the next RC.

**Comment by dyfer** [comment]
It seems you did not rebase onto 3.13... (or something else was wrong, there shouldn't be a commit with the 3.14 version change after the rebase). However, with the reverting commit I think I can just squash merge to clean it up. Should I do that or would you try rebasing again?

**Comment by telephon** [comment]
Yes, it's been a mess, sorry – for convenience I tried to do it with GitHub Desktop, which seems to be broken in this respect.
With 
```
git rebase --onto 3.13 topic-fix-multiple-meters

```
it says `Everything up-to-date`. So I suppose the best is a squash.

**Review by dyfer — APPROVED** [review]
Thanks!

**Pull request merged**
