### PR TITLE
supernova: use -Z in portaudio 0 hight (negative) low others desired har...

### PR DESCRIPTION
**Pull request by sonoro1234**
use of -Z in supernova with portaudio:

0 means hight (longest) default latency
negatives means low default latency
positive means desired hardware buffer size

### CODE REVIEW

**Comment by timblechmann** [comment]
thanks a lot, looks good to me. just one issue: please use spaces for indentation in supernova ...

**Comment by sonoro1234** [comment]
second patch fixes it.

**Comment by sonoro1234** [comment]
This pull request can be automatically merged by project collaborators.
But when is it going to happen?

**Comment by timblechmann** [comment]
patch looks good to me, but i don't have write access to the repo anymore

**Pull request merged**
