### PR TITLE
sclang: Fix excessive calls to SC_TerminalClient::tick when SC_QT is off

### PR DESCRIPTION
**Pull request by snappizz**
this cherrypicks @giuliomoro's fix for #2144, the infamous "CPU hog when built without Qt" issue. this fix has been used for a long time in the bela fork of SC. see his comment here for explanation: https://github.com/supercollider/supercollider/issues/2144#issuecomment-320401926.

the fix seems quite logical to me, and i've tested and verified that it corrects the behavior. ~~what is mysterious is not the bug itself, but the fact that it *doesn't* happen when sclang is built *with* Qt.~~ **EDIT:** it's actually hilariously simple, there's an `#ifdef SC_QT` which redirects `SC_TerminalClient` to the completely separate `LanguageClient` code in QtCollider. so this is symptomatic of a larger problem: fragmentation of code depending on whether SC_QT is on or off, which is most likely a historical artifact of QtCollider's origins. this patch does seem fine to me though.

thanks so much to @giuliomoro, and sincere apologies to the alternate-client and embedded SC crowds for delaying on this for so long.

## Test case

build SC with `cmake -DSC_QT=OFF`. create a file called `foo.scd` with the following:

```
Server.default.waitForBoot {
   Routine {
      x = play { SinOsc.ar };
      "thing happening".postln;
      1.wait;
      x.free;
   }.play
}
```

run `sclang foo.scd` (makes sound). after this patch, sclang no longer uses a ludicrous amount of CPU.

### CODE REVIEW

**Comment by brianlheim** [comment]
This deserves at least:
- a comment on the addition
- a [doxygen] comment to document the function

**Comment by giuliomoro** [comment]
> @brianlheim a comment on the addition

my understanding is that this is the way it is meant to be: the current implementation is not checking for the error code there, while it should. So there is nothing SC or non-QT specific in that patch, it's just the way you are meant to do it, so you may not need a comment there?

**Comment by snappizz** [comment]
ok, documented!

@brianlheim can you check and ensure that my doxygen formatting is correct?

**Comment by snappizz** [comment]
done and done, thanks for the feedback!

**Comment by vivid-synth** [comment]
Thanks for getting this one across the finish line @snappizz !

**Pull request merged**
