### PR TITLE
FIx Guide 'Multichannel Expansion'

### PR DESCRIPTION
**Pull request by afischli**
Right parentheses were missing. This fix makes the examples work.

### CODE REVIEW

**Comment by gusano** [comment]
@afischli Thanks for the fix.
Just a note about git workflow, so we don't get the main repository polluted with *merge* commits like up here 462b23a : 

- start with an up-to-date `master` branch

    `git checkout master`
    `git pull origin master`

- create a branch **from up-to-date `master` branch**

    `git checkout -b NAME-OF-MY-BRANCH`

- write code and commit it
    `...`
    `git commit ...`

and then submit a PR.

Thanks!

**Comment by miguel-negrao** [comment]
Well, and for completeness, by the time you are ready to commit it's possible that more commits have landed in upstream/master, therefore you should

    git pull --rebase upstream master

before you push to your github fork, in order to avoid the merge commit. If you then have to correct the pull request, when you repeat the procedure you probably have to force-push, in order overwrite your remote (if any of this is unclear, I can clarify).

**Comment by afischli** [comment]
I am using ‘GitHub Desktop’ and not git CLT. BTW on purpose. 

My intention was to PR only the commit #163f1dd (Fixing syntax errors in examples https://github.com/afischli/supercollider/commit/163f1dd8632ea95dadc6a9a4466d9a04a6faed38) from branch "afischli:Guide-'Multichannel-Expansion'-fixes-". Thus @gusano, please note, I have branched, but true had not updated everything else before, again on purpose (I am writing a tutorial for the use of ‘GitHub Desktop’), since I believed the branches to be quite independent and did not think that any not yet updated branch would interfere with a new branch. Sorry.

Note, this extra commit 462b23a (https://github.com/afischli/supercollider/commit/462b23a0db9e90817b7abd24099c415a08a56561) is superfluous and was already merged to upstream (#1787). I do not know why this extra commit also appears now suddenly in the wrong branch, since I committed it in branch 'afischli:Tutorial-corrections' and nowhere else. Then I pushed. My conclusion would be to discard it. But how? Who?

Then I do not quite understand @miguel-negrao what a "merge commit" is. Do you mean the merge committing my pull requested changes to the upstream branch master? Then I see no reason to correct my pull request, since I filed it AFAIK ok. I also do not know what force-push is and see nothing comparable in ‘GitHub Desktop’. When I do 'git status' in my local repo 'supercollider' I get 

``On branch Tutorial-corrections``
``Your branch is up-to-date with 'origin/Tutorial-corrections'.``
`` ``
``nothing to commit, working directory clean``

The same is true for the other branch Guide-'Multichannel-Expansion'-fixes-'. I gives the same result. All just meaning my local repo is well synced with origin, I guess.

I do not exactly know what has now best to be done. One reason being that the official GitHub tutorial on ‘GitHub Desktop’ (https://help.github.com/desktop/guides/) is not very clear nor that helpful. Though, using ‘GitHub Desktop’ I can see now in branch 'Guide-'Multichannel-Expansion'-fixes-' also both commits, i.e. the superfluous one as well. But it seems there is not much I can do with it.

Can you help? What should I do now?

**Comment by gusano** [comment]
@afischli I never used *GitHubDesktop* and probably never will so I'm clueless about that point.



> Note, this extra commit 462b23a (afischli@462b23a) is superfluous and was already merged to upstream (#1787). I do not know why this extra commit also appears now suddenly in the wrong branch, since I committed it in branch 'afischli:Tutorial-corrections' and nowhere else.

I guess this is because you created your branch (this PR is based on) from *Tutorial-corrections* and therefore, at the time you submit the current PR, the extra commit was not yet in `master`.. 

(on a side note I am not a big fan of merging PRs with merge commits but that's just my humble opinion and I don't know how strict sc devs policy is on that matter)

> Can you help?

Sure, gonna submit a new PR with your fix, but I cannot tell you how to do this from within GitHub Desktop...

**Comment by afischli** [comment]
BTW, the situation is really a bit confusing, because the state is also here shown as inconsistent. E.g. listed are two commits, while only 1 file is listed as changed. This can't be correct, since the two commits pertain to two different files. Clicking on the changed files icon gives the correct file having a change.

Then I also checked in the meantime my records. They clearly show that when I made the pull request there was only 1 committed change in the branch. Not two. That's why I think I did on my side the right thing.

But I have no idea what the best way is to fix this.

**Comment by gusano** [comment]
@afischli if you want to propose a change to `master` branch, just create your topic branch from that branch and not from another one where you did other work before

**Comment by afischli** [comment]
@gusano  Thanks. Helps. Indeed I made a mistake as you pointed out by not branching from master. Stupid of me. That would explain why the 2nd commit was included in the pull request. There are several things I could do. I simply don't want to reverse the intended changes, i.e. to interfere with  #1787. I could perhaps do a pull. ‘GitHub Desktop’ offers such a command. If git pull --rebase upstream master would anyway be appropriate here, then ‘GitHub Desktop’ menu command Pull should be able to accomplish something similar. But I better do nothing until someone advises what would need to be done with CLT to fix this situation, i.e. to discard the unintended 2nd commit 462b23a. Note, I also don't want to reverse the intended changes (quite many) in my local repo by using the revert this commit in ‘GitHub Desktop’. Or does that not matter and when I pull from upstream those losses I would get my many edits back and the revert would be overwritten?

**Comment by gusano** [comment]
Cloging in favor of #1790

**Comment by gusano** [comment]
@afischli in the case of a simple change like here, I guess you'd better just create a new branch from `master` and re-apply your change and re-submit a PR.

**Comment by afischli** [comment]
@gusano  Why should I resubmit, since all those changes as I have them PRed earlier ( were already merged #1787 by @telephon? And then you seem just to have accepted my intended changes from commit 163f1dd. BTW thanks. So all looks as I wanted. Perhaps I simply delete this branch and the parent branch and all should be as it should. Right?

**Comment by gusano** [comment]
@afischli I meant re-submit the wanted new change (here commit 163f1dd), not the unwanted one, which is what I just did on the new PR.
And yes, you can delete those branches now.
Thanks for your fix BTW!
And don't be put out by git, it's a great tool, although it can be a bit frustrating in the beginning.. (and I would suggest that you have a try at cli git some time..)

**Comment by afischli** [comment]
cli git?  and thanks for all!

... and will delete these branches hoping that all will be fine thereafter.

**Comment by danstowell** [comment]
@afischli most of us use git only on the CLI. Who knows, git desktop may be able to do everything that's being suggested in this conversation, but we wouldn't know how to tell you what to do!

**Comment by afischli** [comment]
Yes, I know. I am on a steep learning curve here. ;-)  But I am collecting all and working towards what I hope will be a good tutorial to then eventually share with all.

**Comment by gusano** [comment]
> But then I could of course also fix this issue with CLT git

What I meant by **cli git** is `git` in your terminal, without any desktop app.. :)

**Comment by miguel-negrao** [comment]
sorry for being brief, busy at the moment:

> Then I do not quite understand @miguel-negrao what a "merge commit" is. 

read https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging :

>Instead of just moving the branch pointer forward, Git creates a new snapshot that results from this >three-way merge and automatically creates a new commit that points to it. This is referred to as a >merge commit, and is special in that it has more than one parent.

--


> I also do not know what force-push is and see nothing comparable in ‘GitHub Desktop’.

Force push will overwrite/delete/destroy the contents of that branch in the remote and substitute it by the contents that you are pushing when it detects that the contents are not compatible (which can happen when you rebase locally). When you are working on a branch locally sometimes you rebase, to clean up commits, delete commits, squash commits, etc, then you want to present this new work to the same pull-request in github, you can do that by force-pushing your new commits. It should be used only by experienced git users who know what they are doing, so for the time being, safe to ignore this workflow. That being said, a personal fork of supercollider in github is usually used by just one person, so you can do whatever you want to it. I'm not surprised github desktop doesn't have that option, since it is only for advanced users. In any case the canonical reference for git commands is git itself, so when you don't know about a command do 'git help command'. It's fine to use the gui, as long as you understand what is going on beneath it. Personally I do 99% of my git actions in a gui (smartgit), but if needed, I can go back to git cli for something more specific or tricky.

**Pull request closed without merging**
