### PR TITLE
Add commit to version info

### PR DESCRIPTION
**Pull request by vivid-synth**
The work for https://github.com/supercollider/supercollider/issues/2242

### CODE REVIEW

**Comment by snappizz** [comment]
lgtm

**Comment by vivid-synth** [comment]
Is there a way to re-run the travis test? It seems to have errored before it even started building.

**Comment by crucialfelix** [comment]
I restarted it

**Comment by snappizz** [comment]
This is still under discussion at #2242, correct?

**Comment by crucialfelix** [comment]
lgtm

**Pull request merged**
