### PR TITLE
Add S3 deployment to appveyor setup

### PR DESCRIPTION
**Pull request by brianlheim**
This PR adds S3 deployment to our Appveyor setup so that "bleeding-edge" builds can be downloaded and tested by interested users and developers. Most of this was copied/adapted from `.travis.yml`. Thanks to @scztt for helping with S3 access and general usage.

This should be accompanied by an appropriate PR to the website making these builds available.

With the current config, builds are uploaded both for 32-bit and 64-bit builds.

I haven't tackled the automatic release asset uploading part of the script. If it isn't too hard to add that in, we can merge both at once. Might take some testing with temp tags created on this branch, if you're ok with that @snappizz.

### CODE REVIEW

**Comment by muellmusik** [comment]
Thank you!

**Comment by brianlheim** [comment]
A tagged release is now building: https://ci.appveyor.com/project/brianlheim/supercollider-mu8dk/build/146

**Comment by brianlheim** [comment]
Test release tag: https://github.com/supercollider/supercollider/releases/tag/appveyor-test-2

**Comment by brianlheim** [comment]
This is ready for merge!

**Pull request merged**
