### PR TITLE
Topic/update pdocs

### PR DESCRIPTION
**Pull request by madskjeldgaard**
## Purpose and Motivation

This is a new pull request of https://github.com/supercollider/supercollider/pull/4689 with cleaner git and on a seperate branch.

### CODE REVIEW

**Comment by madskjeldgaard** [comment]
How's this, @brianlheim ?

**Comment by madskjeldgaard** [comment]
and @telephon

**Comment by brianlheim** [comment]
@madskjeldgaard looks good, thanks!

**Comment by brianlheim** [comment]
@madskjeldgaard do you happen to have the set of commands that solved this for you? it might be useful info for our development guide docs.

**Comment by madskjeldgaard** [comment]
Glad to hear it! 
I think I basically just had to do the rebasing from the develop branch instead of from my bew branch.

Something like this:

```
git checkout develop
git checkout -b topic/update-pdocs
git checkout develop
git rebase -i origin/topic/update-pdocs
```

**Comment by madskjeldgaard** [comment]
And to be honest, I don't know how but the merge commits just disappeared in the rebase ?_?

**Comment by telephon** [comment]
should be this:
```
git checkout develop
git checkout -b topic/update-pdocs
git rebase -i develop
```

**Pull request merged**
