### PR TITLE
Revert "syntax highlight and allow running code from schelp files"

### PR DESCRIPTION
**Pull request by miguel-negrao**
This reverts commit e1c7009ba8a61534b202ab7e436174bac7b28860.

### CODE REVIEW

**Comment by miguel-negrao** [comment]
Can we merge this ?

**Comment by telephon** [comment]
What does the revert fix?

**Comment by miguel-negrao** [comment]
> What does the revert fix?

Did you see the discussion at #1292 ?

syntax highlighting of schelp files is currently not well implemented, until a good implementation comes along probably more helpful to just disable.

**Comment by telephon** [comment]
Ok, I understand now - thank you for the reference. 

Does this remove the possibility of evaluating code in the help source?

To me, a fix that removes that possibility is really a regression. It is very complicated to first look into the rendered helpfile to track changes in the example code.

What's more, evaluating code in the helpfile is broken at the moment.

Generally, according to the principles of literate programming, the help source should be as close as possible to a code file.

**Comment by miguel-negrao** [comment]
> Does this remove the possibility of evaluating code in the help source?

Unfortunately yes. Evaluating code was my original reason for adding this patch.

**Comment by telephon** [comment]
I prefer wrong syntax highlighting to the inablility to run code. You can edit those files in another editor if it is too disturbing.

So I'm not for committing this.

**Comment by crucialfelix** [comment]
I agree: bad syntax highlighting is better than can't run code in help file.

**Comment by miguel-negrao** [comment]
ok, then lets keep and hope someone in the future implements proper syntax highlighting, or separates the running of code from the highlighting.

**Comment by timblechmann** [comment]
fwiw, the current syntax highlighting in schelp files violates the main design principle of the IDE: when something cannot be done correctly, don't do it.

the sc code editor component in the ide is designed for writing supercollider code, not to write schelp files. if you are doing this, it will be incorrect and it is better not to do something than to do something that is known to be wrong.

but i'm sure both @jleben and me would be happy to guide anyone through the code if someone would be willing to implement proper support for editing schelp files.

**Pull request closed without merging**
