### PR TITLE
GitHub Actions: add macOS legacy build

### PR DESCRIPTION
**Pull request by dyfer**
## Purpose and Motivation

#5294 was a roadblock in offering macOS legacy build in GitHub Actions. Now that that issue is resolved, it's possible to offer legacy build again. Legacy build uses "official" Qt distribution, since there's no easy way to add Qt 5.9 from homebrew to GH runners, which run macOS 10.15.

Deployment should work, though it was not explicitly tested for this addition.

I've also moved the position of the `aqtinstall` step to match the structure on Linux.

~~EDIT:
I guess it does not work, something is indeed wrong with the `rpath`. When trying to run the legacy build downloaded from Actions, I am getting~~

<details>

```sh
dyld: Library not loaded: @rpath/QtConcurrent.framework/Versions/5/QtConcurrent
  Referenced from: /path/to/SuperCollider.app/Contents/MacOS/SuperCollider
  Reason: image not found
```
</details>

~~Locally, I can build SC with official Qt and move it to another machine and it works...~~
## Types of changes

- New feature (?)

## To-do list

- [x] Code is tested (except for deployment)
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
> I guess it does not work, something is indeed wrong with the rpath.

sclang has the rpath entry, but not the ide binary:

```
[brianheim@BrianMBP SuperCollider]$ otool -l SuperCollider.app/Contents/MacOS/sclang | tail -4
Load command 47
          cmd LC_RPATH
      cmdsize 40
         path @loader_path/../Frameworks (offset 12)
```

i would guess you need to set the `INSTALL_RPATH_USE_LINK_PATH` property on `libscide` before calling `target_link_libraries( SuperCollider libscide)`. that's the only difference in usage that i see.

**Comment by dyfer** [comment]
thanks Brian! Changing that didn't seem to help. I'll get back to this in a few days.

**Comment by dyfer** [comment]
I've added the rpath entry for the `SuperCollider` target and that seems to work. Is this the way to go?

**Comment by brianlheim** [comment]
> I've added the rpath entry for the SuperCollider target and that seems to work. Is this the way to go?

ah great! i was wondering if that would work. `set_property` takes multiple targets, so you can combine those lines if you want or just merge it as-is.

**Review by brianlheim — APPROVED** [review]
thanks!

**Comment by dyfer** [comment]
oh great, I was wondering if I could set multiple targets. I'll do that and then merge

**Comment by dyfer** [comment]
Merging - the failure is CI was in tests, unrelated to this PR.

**Pull request merged**
