### PR TITLE
Add cmake options list to READMEs

### PR DESCRIPTION
**Pull request by vivid-synth**
It can be hard to find the list of possible CMake build options; now it's in the README.

### CODE REVIEW

**Comment by gusano** [comment]
@vivid-synth what about `cmake -L ..` ?

**Comment by vivid-synth** [comment]
@gusano the ones in CMakeLists.txt under "Options" are the ones the user "should" be setting, no?

When I ```cmake -L``` (or ```-LH```) I see tons more options, many of which the average user probably doesn't want to touch (```Qt5PrintSupport_DIR```, ```Qt5WebKitWidgets_DIR```, ```SN_MEMORY_DEBUGGING```, etc). The "Options" list gives just the ones you might want to toggle even as a newcomer (do you want to build the IDE, enable supernova, etc)

**Comment by danstowell** [comment]
I must admit I'm not a fan of telling people to go hunting in the CMakeLists.txt file. Much better to recommend `cmake -L ..`

The problem you mention @vivid-synth with the Qt5 options is that someone forgot to use cmake's [MARK_AS_ADVANCED()](https://cmake.org/cmake/help/v3.0/command/mark_as_advanced.html) to hide them from the normal view. Fixing that would be the fix IMHO

**Comment by vivid-synth** [comment]
@danstowell @gusano fair enough; I still think it's very helpful to show users who aren't proficient with CMake what their options are -- I've changed the instructions to explain ```cmake -LH```.

Could someone more familiar with the build process ```MARK_AS_ADVANCED``` the advanced flags (maybe as a separate ticket)?

**Comment by danstowell** [comment]
@vivid-synth thanks, done as PR #1968

**Comment by crucialfelix** [comment]
how is this conflicting ? it's so simple. hmpf.

**Comment by bagong** [comment]
Also: git's automatic merge doesn't always work the way we'd hope. When looking through this I saw that the Windows Readme from 3.7.1 wasn't merged the way I would have wanted it to be done.

**Comment by bagong** [comment]
The Windows Readme was committed to master from 3.7.1. This PR was created before that merge, git cannot identify the spot where to insert @vivid-synth's addition. For simplicity: may I suggest just to remove the Windows part in the PR. While not in the same place, `-L` `-LH` is mentioned twice in the Windows Readme...

**Comment by vivid-synth** [comment]
@bagong @crucialfelix : fixed conflict. I've removed the note from the windows readme.

**Pull request merged**
