### PR TITLE
Incorporate these tutorial corrections

### PR DESCRIPTION
**Pull request by afischli**
Improving on correctness of First Steps section in SC Tutorial:

As discussed under issue
https://github.com/supercollider/supercollider/issues/1781#issuecomment-
170959978 I have now made an attempt to improve on the correctness of
the section "02. First Steps" of Tutorial "Getting Started With
SuperCollider”. This should give new users of SC a much more pleasant
experience and avoid the bad impression of SC not working as it
should/described. However, some sections are related to a bug/bugs
(https://github.com/supercollider/supercollider/issues/1786).

### CODE REVIEW

**Comment by telephon** [comment]
this should go into 3.7 also

**Comment by crucialfelix** [comment]
If something should go into 3.7 (which very little should) then you should have merged it into 3.7

not into master

**Comment by crucialfelix** [comment]
3.7.0 is already feature and edit complete. its just being packaged (release notes) and getting ready for release.

nothing new goes in unless its a critical bug

**Comment by telephon** [comment]
ok, anyway, good news!

**Comment by LFSaw** [comment]
> If something should go into 3.7 (which very little should) then you should have merged it into 3.7

if something does not go into 3.7 (because it is ready), where does it go then? master?

**Comment by danstowell** [comment]
@LFSaw yes, new work goes to master, that's fine

**Comment by LFSaw** [comment]
thanks :)

**Comment by afischli** [comment]
Thanks for merging this. :-)

**Pull request merged**
