### PR TITLE
SinOscFB.schelp: added FM behavior description

### LINKED ISSUE #5641: Missing documentation on SinOscFB's special frequency modulation behavior
## Environment

* SuperCollider version: SuperCollider 3.12.1 (built from branch 'HEAD' [b678713])
* Operating system: macOS 10.14.6
* Other details (Qt version, audio driver, etc.): using built-in audio of MacBook Pro 15" (Intel Core i7 / 2,8 GHz / 16 GB)

## Steps to reproduce

```supercollider
{SinOsc.ar(440*SinOsc.ar(),0,0.1)}.play   // expected sound with SinOsc as carrier
{SinOscFB.ar(440*SinOsc.ar(),0,0.1)}.play // unexpected distorted sound with SinOscFB as carrier
{SinOsc.ar(440*SinOsc.kr(),0,0.1)}.play   // for comparison: same distorted sound with modulator running at .kr
```

## Expected vs. actual behavior
`SinOscFB` does not update incoming frequency modulation values as often as `SinOsc`, thus generating the unexpected distortion. It sounds as if `SinOscFB` updates incoming frequency modulation values only once every block of 64 samples, not for every sample as `SinOsc`, as the sonic result of
FM’ing `SinOscFB.ar` with `SinOsc.ar`
is practically idential to
FM’ing `SinOsc.ar` with `SinOsc.kr`.

The [documentation for `SinOscFB`](http://doc.sccode.org/Classes/SinOscFB.html) does not mention this behavioral deviation from `SinOsc`, which caused user confusion as can be seen in [this](https://scsynth.org/t/noob-how-to-do-classic-dx7-style-operator-feedback/4753/13?u=wolfgangschaltung) and the following post.

Perhaps adding the following sentence to the **Description** of `SinOscFB` would help:
"Please note: As SinOscFB does not update incoming frequency modulation values on every sample, but only once every block of 64 samples, you will notice distortion artefacts at higher frequency modulation frequencies."

### PR DESCRIPTION
**Pull request by wolfgangschaltung**
## Purpose and Motivation
Fixes #5641

This is my first pull request ever, and although I have read the contributing guidelines and watched Eli's video on "Contributing with Git and GitHub", I am not sure if it is enough of a description to reference to an existing issue. Please let me know if this is sufficient, or if more information should be provided in the pull request. Thanks!

## Types of changes

- Documentation

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Review by adcxyz — APPROVED** [review]
Thanks, this is useful to document here!

**Comment by dyfer** [comment]
Thanks for the PR and for merging!

I just noticed the part `once every block of 64 samples`. Since block size is configurable, maybe we could change it to `once every control period` or something like that? It's minor of course, I'm making the comment here more as a reminder for myself to suggest this change.

**Comment by wolfgangschaltung** [comment]
@dyfer: I am happy to do the change from `once every block of 64 samples` to `once every control period`, but as I am new to coding and GitHub, what's the best practice for doing it? Shall I create a new issue from your comment and an according PR, or is it OK to create just the PR and reference to your comment? Please let me know, thanks in advance!

**Comment by dyfer** [comment]
@wolfgangschaltung just a new PR would be great, thanks!

**Comment by adcxyz** [comment]
or maybe "once every control period (typically 64 samples)" ?

**Comment by wolfgangschaltung** [comment]
@dyfer: created PR #5688.

Sorry, this took longer than expected due to my stupidity. As it seems, I forgot to switch to the original branch `topic/SinOscFB_help_addition` on my initial attempt, so I worked on `develop` in my clone. But when pushing my changes, I pushed the unaltered branch `topic/SinOscFB_help_addition`, so there was nothing to commit. It took me a while to figure this out (including deleting my clone).

**Pull request merged**
