### PR TITLE
make_release.py: add some automation for opening webpages

### PR DESCRIPTION
**Pull request by brianlheim**
## Purpose and Motivation

working toward #4974. this is the result of working with @claremacrae  this morning, thanks Clare!

added the following:
- `YesNoStageWithUrl`: same as `YesNoStage`, but opens a URL in a web browser
- copied over some helpful utility files from ApprovalTests.cpp's automation scripting
- added a requirements file with 3 packages
- added command-line option for the new version number
- add some stages and reword some stages based on experience with last release
- we're git-ignoring 'venv' and '__pycache__' directories now since those were generated by pycharm while working on this

Clare, for handling versioning logic i found and used the semantic_version package. it seems to work well with the
kind of version strings we use, and it's less code we need to test, what do you think?

## Types of changes

- New feature

## To-do list

- [x] Code is tested - ran and tested locally
- [x] All tests are passing
- [x] Updated documentation - updated wiki documentation. once this code becomes more stable i would like to add a
  readme
- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
since this only affects code not packaged with the release, this is OK to go into the 3.11 branch.

**Comment by claremacrae** [comment]
> Clare, for handling versioning logic i found and used the semantic_version package. it seems to work well with the
kind of version strings we use, and it's less code we need to test, what do you think?

Awesome idea - I wish we had thought to look for something like that for ApprovalTests.cpp!

**Comment by claremacrae** [comment]
A thought for future work on this: upon re-reading the steps now, it seems that all the ones that say "have you run the script...." might eventually be converted to programatically checking whether said script has been run, and if not, then running it, which would be lovely...

**Review by jrsurge — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
