### PR TITLE
Set buffer sample rate to file's sample rate in supernova

### PR DESCRIPTION
**Pull request by nilninull**
It's similar to fef48b0c45245672cc716aafcd84041c7340caa3.

### CODE REVIEW

**Comment by bagong** [comment]
Vim users are a helpful lot! ;) Do you happen to know what would happen if a soundfile header didn't contain a sample rate? (hopefully not a stupid question ;) )

**Comment by nilninull** [comment]
I think no problem.
libsndfile validates information by validate_sfinfo function (in sndfile.c).

And I tested with a raw file format and a irregular wav file which changed the header sample rate value to zero.

Results are below.

```
-> Buffer(12, nil, nil, nil, /home/nilninull/test.raw)
File contains data in an unknown format.
```
```
-> Buffer(4, nil, nil, nil, /home/nilninull/test.wav)
Internal error : SF_INFO struct incomplete.
```

**Comment by bagong** [comment]
Yes, this is what I kind of hoped. So you say no problem in the sense that it doesn't create a crash, right?

I was asking because just the other day we had error-reports about SC sometimes not being able to open soundfiles, producing a return-message that didn't help much. One idea was that this might happen with sound files with incomplete header information (audio applications that still open the file could be more permissive than libsndfile). Unfortunately the error-reports were not very precise. All examples we got were with an aiff-file, the error message was: 

    Bad format field in SF_INFO struct when opening a RAW file for read

The one you get for .wav is a bit different, but still similar enough to think it could be the same underlying process? Or even if not - as this is a very specific failure condition, would it be complicated/expensive to have scsynth and supernova return a more informative error-message in the case of missing sample rate information, something like: sample-rate information missing in soundfile header?

**Comment by telephon** [comment]
The error message is defined here: https://github.com/erikd/libsndfile/blob/master/src/sndfile.c#L174

But I couldn't find ay code that calls `SFE_RAW_BAD_FORMAT`.

**Comment by bagong** [comment]
Yea, the one produced in the examples above are also not called by SuperCollider, it seems. They are SFE_UNKNOWN_FORMAT (File contains data in an unknown format) and SFE_BAD_SF_INFO (Internal error : SF_INFO struct incomplete). So it has to be libsndfile, that comes to those imprecise/generic conclusions. And then we don't know what else is broken in the headers above.

My point is - turning smiling to @nilninull  (no demands, just an enquiry) - as at the very point you are modifying, the servers tries to pick the sample-rate from the soundfile, we have a condition where the servers could produce informative error-output (complementing libsndfile's output). Even if that didn't solve the problems we got reports for, it would help to exclude or indicate a specific problem.

And maybe even one could go as far as disable the feature for raw files? I guess the file extension is not a secure indicator of the sound-file format, but it would probably catch many cases that would otherwise fail. I wonder if the server "knows" the filename at that spot? I see the variable `filename` a few lines upwards?

**Comment by bagong** [comment]
But yes @telephon , it seems we can safely say that the "Bad format field in SF_INFO struct when opening a RAW file for read" reports we got are a problem between the reporters soundfile and libsndfile, so not a case for the SC fire department, right?

**Comment by nilninull** [comment]
When I sent a patch, I did not think about it, but I tried using libsndfile for a while.

I think cost is high when trying to output useful error information at SC.

The reason is that libsndfile will not return it even if data can be taken halfway during an error.
Also, libsndfile ignores the suffix and determines the file type.

So, I think it is difficult to identify the file type and analyze the header in the SC just to return an error.

And I also thought about opening a raw file a bit.

To open raw files, at a minimum, you need to explicitly tell libsndfile that the file type is raw. In addition, it is necessary to specify sampling frequency, number of channels, subtype (16 bit, float ...).

So, if you want to read the raw file at SC,

- In / b_read command, change so that sampling frequency, number of channels, subtype can be specified.
- Create other commands such as / b_read_raw.
- Open the file with sclang's SoundFile and send it to the server side.

I think that processing is necessary. 

Currently, it seems that the operation of the raw file in the SC is prepared for writing out.


-----
I think that how to use words is a little strange, but I will write with this. Because I am not so good at English, do not worry if there is rude.

**Comment by bagong** [comment]
@nilninull , thanks a lot for your considerations. I was worried I scared you off with my far fetched thoughts burdening a PR that basically wants to adjust SuperNova to the Scsynth, which I think is a fair and good intent. I learnt a lot along the way. It would be nice to have somebody with your insight to look at the sndfile integration in SC, which I think works okay, but is a bit of a mess because of multiple hasty adjustments in the past.

As to your pull request: I think it is fair, but I don't feel competent to really make a judgement. Unfortunately the support status of SuperNova is a bit unclear. Can we just leave it open for a while in the hope somebody else might join the discussion?

Thank you again!

**Comment by vivid-synth** [comment]
I'll volunteer to try and be that person.

**Comment by telephon** [comment]
@vividsynth what do you think about this?

**Comment by vivid-synth** [comment]
I'm sorry, I've been too buried with work to give this a good look. I'm removing my self-assignment now in the hopes someone else can take a crack at it, otherwise I'll try and be back soon to look at it again.

**Pull request closed without merging**
