### PR TITLE
Osc.sc: fix audio rate TChoose

### PR DESCRIPTION
**Pull request by miczac**
thanks go to Daniel Mayer
http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/choosing-random-value-in-synth-tp7624784p7624799.html

Signed-off-by: Michael Zacherl <github-mz01@blauwurf.info>

### CODE REVIEW

**Comment by danstowell** [comment]
Phew! Thanks

**Comment by miczac** [comment]
oh boy ... what an effort for correcting a single byte! ;) :D

**Comment by bagong** [comment]
Haha, but after all that sweat it deserved to be committed even before the testbuild completed ;) !!

**Comment by miczac** [comment]
Dan seemed to be on the qui vive ;)  thanks & sorry again!

**Comment by bagong** [comment]
No harm done!

**Comment by telephon** [comment]
Thanks and sorry (it was me who caused it, and had I read emails, I would probably have searched for it ...)

**Pull request merged**
