### PR TITLE
Bug 1355 demand env overshoot

### PR DESCRIPTION
**Pull request by baconpaul**
I apologize for the bad merge before. This merge addresses Bug 1355 and also compiles.

Sorry again for pull requesting code which didn't build. Sloppy.

### CODE REVIEW

**Comment by telephon** [comment]
`ciel` – sky would be nicer than ceiling! 
looks good to me.

what is the inconsistency you mention?

**Comment by baconpaul** [comment]
Yeah another few decades and maybe I'll be able to remember how to spell the opposite of floor!

The inconsistency is by using the ciel we are actually microscopically adjusting the frequency. The "zero crossing" should really be 53.2 samples away but we make it 54 samples away. The other fix I was thinking about was in the second switch statement doing a "if phase < 0 level = a2" type thing but I decided to microscopically adjust the overall wavelength instead to avoid a one-sample glitch.

So the inconsistency is I've adjusted the wavelength by perhaps as much as .99ths of a sample (which really isn't that much but is an inconsistency and it is a consistency which is consistent through the envelope as opposed to a one sample change in wavelength).

Sorry for not expanding that in the comment.

**Comment by telephon** [comment]
that's fine, just curious.

**Comment by baconpaul** [comment]
Just took a look at EnvGen.

It has the similar code at line 2921

`	unit->m_grow = exp(curve / counter);
`
but rather than having the "count = phase" initialization that DemandUGens has on line 1017, it instead sets counter to the duration * samplerate cast to an int32 which ends up (basically) being the same as putting the ceil in the place I did. Also the original ticket showed the particular problem doesn't occur with EnvGen, so I think its fine.

Thanks, and thanks for looking at the pull request so quickly!

**Comment by telephon** [comment]
let's wait a little if someone sees a potential issue, but it looks very good to me.

**Comment by miguel-negrao** [comment]
just an issue of style, but if you squash your two commits into one then the initial error will not be recorded in the history and it will be cleaner. You can use '[git rebase -i](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)' for that, or do it from a GUI for instance [using](https://www.syntevo.com/doc/display/SG070/Outgoing+View) [smartgit](http://www.syntevo.com/smartgit/).

**Comment by crucialfelix** [comment]
We can squash commits when we merge it. It is a new github option.  And supercollider contributors don't seem to pay much attention to commit style anyway :)  

Thanks very much for the PR @baconpaul

**Comment by baconpaul** [comment]
Cool thanks! I will not rebase then. A couple of decades of using cvs makes me forget about these squash options - appreciate you doing it. And thanks for reviewing the pr everyone!

**Comment by miguel-negrao** [comment]
> We can squash commits when we merge it. It is a new github option. And supercollider contributors don't seem to pay much attention to commit style anyway :)

That is nice, but when you squash you also need to write a single commit message, and I don't think it's the maintainer's job to do that, the commiter is in a better position to do that, having actually written the code. Also, it's less work for maintainers if PRs come in nice and clean, so it would be nice if contributors do pay attention to PR style, although it's understood that this is a learning process, so we don't need to be super strict about it. If people use a GUI git program like smartgit, it's also really easy to do and requires no knowledge of git zen tricks.

**Comment by baconpaul** [comment]
Ok well I'm happy to rebase then :)

But I won't be able to get to it today so if you do want to squash and merge the commit comment on the first commit is the one I would copy and paste into the final; the second commit just fixes a dumb typo I embarrassingly pushed. 

Let me know either way!

Thanks

**Comment by miguel-negrao** [comment]
@baconpaul Btw, wasn't so much talking about this specific PR, more a general comment. Just something to consider for next PR. And off course, thanks for contributing ! :-)

**Comment by baconpaul** [comment]
Ok cool thanks! Ideally of course I wouldn't have pushed broken code in the first place! Doh!

Thanks to all for making it easy to contribute.

**Comment by crucialfelix** [comment]
>  but when you squash you also need to write a single commit message,

It concatenates all the commit messages into a long paragraph. The merger person can edit it to taste and squash to a single commit. It's splendid.

**Comment by crucialfelix** [comment]
btw. I often revise the commit messages when I do merges. Sometimes people don't clearly state what is fixed, why, what is changed etc. I try to make it so that the release notes give a clear read about what is new, what to watch out for.

**Comment by telephon** [comment]
ok, I'll remember to do this.

**Pull request merged**
