### PR TITLE
[classlib] FFT: fix for using regular Buffer

### LINKED ISSUE #3399: SCClassLibrary: synthdef build bug for FFT LocalBuf vs Buf
starting with sc3.7 there's a problem with building synthdefs.

this...
```supercollider
(
s.waitForBoot{
	l= 8;
	b.free; b= Buffer.alloc(s, l, 1);
	s.sync;
	SynthDef(\avTrk, {|in= 0, t_trig= 0|
		var z= In.ar(in, 1);
		var chain= FFT(b, z);
		Array.fill(l.div(2), {|i|
			var a= Unpack1FFT(chain, l, i, 0);
			var b= Demand.kr(chain>=0, 0, a);
			SendTrig.kr(t_trig, i, b);
		});
	}).dumpUGens;
};
)
```

should post...
```supercollider
avTrk
[ 0_TrigControl, control, nil ]
[ 1_Control, control, nil ]
[ 2_In, audio, [ 1_Control[0] ] ]
[ 3_FFT, control, [ 0, 2_In[0], 0.5, 0, 1, 0 ] ]
[ 4_Unpack1FFT, demand, [ 3_FFT, 8, 0, 0 ] ]
[ 5_>=, control, [ 3_FFT, 0 ] ]
[ 6_Demand, control, [ 5_>=, 0, 4_Unpack1FFT ] ]
[ 7_SendTrig, control, [ 0_TrigControl[0], 0, 6_Demand[0] ] ]
[ 8_Unpack1FFT, demand, [ 3_FFT, 8, 1, 0 ] ]
[ 9_>=, control, [ 3_FFT, 0 ] ]
[ 10_Demand, control, [ 9_>=, 0, 8_Unpack1FFT ] ]
[ 11_SendTrig, control, [ 0_TrigControl[0], 1, 10_Demand[0] ] ]
[ 12_Unpack1FFT, demand, [ 3_FFT, 8, 2, 0 ] ]
[ 13_>=, control, [ 3_FFT, 0 ] ]
[ 14_Demand, control, [ 13_>=, 0, 12_Unpack1FFT ] ]
[ 15_SendTrig, control, [ 0_TrigControl[0], 2, 14_Demand[0] ] ]
[ 16_Unpack1FFT, demand, [ 3_FFT, 8, 3, 0 ] ]
[ 17_>=, control, [ 3_FFT, 0 ] ]
[ 18_Demand, control, [ 17_>=, 0, 16_Unpack1FFT ] ]
[ 19_SendTrig, control, [ 0_TrigControl[0], 3, 18_Demand[0] ] ]
Receiving notification messages from server 'localhost'
```

the problem occurs when using a Buffer object instead of a LocalBuf.
see discussion on sc-dev...
https://www.listarc.bham.ac.uk/lists/sc-dev/msg57903.html

and the proposed fix by @jamshark70 is...
```supercollider
SCClassLibrary/Common/Audio/FFTUnpacking.sc
@@ -83,9 +83,11 @@ PV_ChainUGen : WidthFirstUGen {
                // find UGens that have me as an input
                directDescendants = buildSynthDef.children.select ({ |child|
                        var inputs;
-                       child.isKindOf(PV_Copy).not and: { child.isKindOf(Unpack1FFT).not } and: {
-                               inputs = child.inputs;
-                               inputs.notNil and: { inputs.includes(this) }
+                       child.isKindOf(WidthFirstUGen) and: {
+                               child.isKindOf(PV_Copy).not and: { child.isKindOf(Unpack1FFT).not }
+                                       inputs = child.inputs;
+                                       inputs.notNil and: { inputs.includes(this) }
+                               }
                        }
                });
```

### PR DESCRIPTION
**Pull request by dyfer**
Purpose and Motivation
----------------------

This is a fix for using regular Buffer with FFT UGens. I take no credit for this - @jamshark70 provided the solution in the linked issue; I wanted to get the ball rolling though, as his solution has solved the problem I had. I hope I'm not breaking etiquette by doing this...

Fixes #3399.

Types of changes
----------------

- Bug fix (non-breaking change which fixes an issue)

Checklist
---------

- [ ] All previous tests are passing
- [ ] Tests were updated or created to address changes in this PR, and tests are passing
- [ ] Updated documentation, if necessary
- [ ] This PR is ready for review

Remaining Work
--------------

I have no thorough understanding on the details of FFT processing in SC, so I can't comment on the validity of the solution, other than that it did fix an issue I had. It would be good to test this more to see if it breaks anything else with FFT.

See the reproducer below. Without this fix, if you swap ```LocalBuf``` for ```Buffer```, the synth will not post values, nor create the "trigger" signal from the FFT chain:

```SuperCollider
(
x.free;
b.free;
fork{
	b = Buffer.alloc(s, 32768);
	s.sync;
	x = {
		var in, chain;
		var trig, ff;
		in = WhiteNoise.ar(0.1);
		chain = FFT(LocalBuf(32768), in); //polling works
		// chain = FFT(b, in); //polling doesn't work
		chain.poll;
		trig = ( chain >=0 );
		trig.poll;
		IFFT(chain); // inverse FFT
	}.play;
};
)
```
Again, thanks to @jamshark70 for the solution!

### CODE REVIEW

**Comment by jamshark70** [comment]
The difficulty with testing is anticipating unknown use cases. SynthDefs have a *lot* of unknown use cases (this PR fixes one such case, which wasn't considered in the original logic).

I do see the point about testing, but I'm afraid that, for SynthDef-building logic, nobody has a big picture and requiring robust testing will lead to paralysis, where gradual improvement might be preferable.

I reviewed the e-mail thread, and the logic behind this PR is at the very least more sound than the logic it's replacing.

- The original intent was: If PV unit A has descendents B and C, which both modify the FFT data, then one of them needs to operate on a copy.

- The mistake in the original is assuming that *all* descendents require a copy, with two exceptions:
  - If a descendent is a `PV_Copy`, then we assume that the user is handling the copy explicitly and we don't need to do it again.
  - If it's `Unpack1FFT` then it's outputting a single bin and not modifying anything. (I think -- I'm not totally sure why this exception.)

- The case that found the bug is where a descendent is a BinaryOpUGen operating on the FFT trigger. That is, the original logic forgot that descendents do not have to be PV units. So, in the bug case, it was making a spurious PV_Copy for a comparison operator that isn't touching the buffer's contents.

- The fix is to consider only WidthFirstUGens (including all PV_ChainUGens and IFFT) for copying.

I would reorder it to do the general test before the more specific:

```
child.isKindOf(WidthFirstUGen) and: { child.isKindOf(PV_Copy).not }
```

(I think I saw in one of my e-mails that I suggested this expression, but it ended up backward in the PR.)

You might possibly raise a question about the other subclasses of WidthFirstUGen that are not PV units: `ClearBuf`, `SetBuf`, `RandID`, `RandSeed`, `LocalBuf`. I don't see how it makes sense for any of these to take a PV unit as an input. But we might want to handle that, just to be on the safe side.

Out of time for this morning. I swore I was going to be done with SC stuff by 10 am. Here it is, 10 am again...

**Comment by brianlheim** [comment]
> I do see the point about testing, but I'm afraid that, for SynthDef-building logic, nobody has a big picture and requiring robust testing will lead to paralysis, where gradual improvement might be preferable.

I'm not asking for much, just more than "I have tested it in the one case that was a problem." So we can catch any embarrassingly easy bugs.

**Comment by cianoc** [comment]
If I've understood this correctly the test cases could be:
1) The example posted in the original PR
2) An example of something that works today.

Would that satisfy you Brian?

**Comment by brianlheim** [comment]
@cianoc Sure! I don't have a strong opinion on it, I just don't want to miss an opportunity to test easy cases while this is under discussion.

**Comment by brianlheim** [comment]
> I feel like this change is fine. If anything, if we see issues with buffer numbers from FFT's output causing issues, we should add to this (if anything). I don't think there will be any other problems, but this DOES fix a problem and should be merged.

Good enough for me, but let's either keep this on the develop branch or do a release candidate before 3.10.2 if it's merged to 3.10.

**Comment by dyfer** [comment]
Who should (make the decision to) merge this to 3.10? That part of the development process is not clear to me, decision/responsibility-wise.

**Comment by brianlheim** [comment]
@dyfer It is usually an informal discussion between active developers, at developer meetings, on Slack, or on Github.

**Pull request merged**
