### PR TITLE
ServerStatus - watcher notifies the server

### LINKED ISSUE #2202: s.makeGui server window broken in master
broken-server-window

Server is running. IDE server panel is updating. Server window is not updating.

I guess the new server status watcher is not finished yet?

### PR DESCRIPTION
**Pull request by gusano**
Fix #2202 

Credits go to @jamshark70 =)

### CODE REVIEW

**Comment by crucialfelix** [comment]
Lol

**Comment by jamshark70** [comment]
The thing is, I'm not convinced that's the right answer.

The point of the server status watcher is that you ask the status watcher about the status... not, you ask the status watcher about some status-y things, and the server about other status-y things.

I don't know the best solution, in fact, as I haven't looked closely at the status watcher code. I'd rather not take credit for this.

**Comment by crucialfelix** [comment]
This is probably an artifact of the original PR being so large and consisting of many commits that were work in progress changes over various parts of the classes.

If this fix right here fixes the posted issue then we should commit it.

The further work on refactoring would continue from there anyway.

**Comment by jamshark70** [comment]
> If this fix right here fixes the posted issue then we should commit it.

On second thought, sure, that's fair. Any existing code watching server notifications will be attaching to the Server object, so it's reasonable to continue sending notifications from the Server until the rest is sorted.

**Comment by gusano** [comment]
@crucialfelix @jamshark70 I'm not familiar with this part of the code either but James proposal seems to fix it nicely (and it makes sense).
I'd say merge it.
James I could edit the commit message and not mention you but that would be unfair : )

**Comment by crucialfelix** [comment]
It's a fix for a broken master so it should be simple and just solve it. The next step is the next step.

**Comment by crucialfelix** [comment]
I haven't had a chance to test it, but I assume that you guys did and that the gui now functions. 

ok to merge ?

**Comment by telephon** [comment]
I think it's correct, nobody should need to watch for changes in the watcher. The watcher is an implementation detail of the server.

**Comment by gusano** [comment]
> I assume that you guys did and that the gui now functions

@crucialfelix yep

**Pull request merged**
