### PR TITLE
Win: add definition for VS2015 build

### PR DESCRIPTION
**Pull request by bagong**
Required from VS2015 update 2 upwards. A discussion of the issue is linked in the comment.

### CODE REVIEW

**Comment by brianlheim** [comment]
Awesome! Have you built this?

**Comment by bagong** [comment]
Yes, I'll make a review in about an hour... :)

**Comment by bagong** [comment]
Any reason to keep this open? Committing it would reduce the necessity for me to juggle with branches. This is ignored by anything that a VS2015 build.

**Comment by brianlheim** [comment]
@bagong I was waiting for you to make a review! Actually, that's the only reason I haven't merged this.

**Comment by bagong** [comment]
Haha, we were discussing this in context of the boost163 stuff. Confirming this was implied there. This just allows VS2015 to build and prevents it if it's not there. Nothing really to review.

**Comment by brianlheim** [comment]
Gotcha. Thanks for the explanation!

**Pull request merged**
