### PR TITLE
SynthDef File Format: note (un)signed ints

### PR DESCRIPTION
**Pull request by vivid-synth**
Please correct me if this is factually inaccurate/incomplete! It appears most ints are signed, but I'm not sure of that. Nearly all of the ints don't actually have a need to express negative numbers (e.g. the number of UGens is never negative), but they appear to anyway.

The only exception I see is ```input-spec```, which uses ```-1``` as a special case.

### CODE REVIEW

**Comment by jamshark70** [comment]
https://github.com/supercollider/supercollider/blob/master/server/scsynth/SC_GraphDef.h in the server is full of `uint32`, but I'm not sure it matters for parsing (practically speaking) because the language has no UInteger class. Also, any SynthDef that wraps around into negative numbers would be so large that it wouldn't execute in real time. (I've gotten up to 15,000 UGens in real time -- and that's... how many? 5 or 6 orders of magnitude below the maximum value of a signed integer.)

I guess it's worth noting but it seems like splitting hairs to me. A SynthDef will never be that big.

It's valid to be explicit that the size of a Pascal string is unsigned.

**Comment by vivid-synth** [comment]
Oh, so I'm exactly wrong on the first point! Thanks for the link.

> I'm not sure it matters for parsing (practically speaking) because the language has no UInteger class

I'm working on my non-sclang (Haskell) parser and I'd definitely rather be precise. For example, I can't imagine the use someone would have for 65,000 variants, but if it's an unsigned int16 I should represent it as such.

The implementations are also a bit of a mishmash: e.g. if you look at ```server/supernova/sc/sc_synthdef.hpp```, many values which are ```uint``` in scsynth are ```int``` in supernova. For the purposes of the docs, I think it makes sense to write what the standard should be (e.g. a count or index should be unsigned), and then consider it a very low-priority bug that the implementation sometimes doesn't match the spec.

(If we follow the above mindset, maybe e.g. calculation rate and special index should not be marked as "signed")

**Comment by vivid-synth** [comment]
To be clear: I'd actually like to remove a couple of the "signed" annotations (like on calculation rate and "index of constant")

**Comment by brianlheim** [comment]
fwiw I would prefer whatever supernova does there, and in general prefer signed to unsigned in cases where a negative = special precedent already exists. couldn't it prematurely lock out potential future extensions if we declare some ambiguous variables to be unambiguously unsigned?

**Comment by vivid-synth** [comment]
I'm fine with either case here (either defaulting to ```uint``` or ```int```), but I do think it's important we have a clear file format defined. I do not feel good about having a synth definition file format which essentially says "these ints are either ```int``` or ```uint```, we've actually realized we're not really sure."

Since SC has been around so long, I'd be in favor of just standardizing what's been the _de facto_ standard, except for the fact that apparently we've been living with this contradiction for years (```scsynth``` does one thing some of the time, something else other times, and ```supernova``` doesn't follow what ```scsynth``` does).

**Comment by vivid-synth** [comment]
@brianlheim to your point about the precedent of negative having a special meaning, I think that's true, but:
  - We're probably unlikely to make big changes to file format 2 (more likely we'll have a format 3, probably including fixes like discussed in https://github.com/supercollider/supercollider/issues/2803)
  - Some things clearly always will be unsigned (e.g. most of the ints in the spec are "how many ___s follow this int?" - which is, for example, what the unsigned pascal string byte is)

Like I said earlier, I'm happy to go with either, but I think we should have a clear definition.

**Comment by brianlheim** [comment]
> We're probably unlikely to make big changes to file format 2 (more likely we'll have a format 3, probably including fixes like discussed in #2803)

fair, didn't think of that.

> Some things clearly always will be unsigned

i realized looking over this again that there is a dependency issue to consider as well. line 126:
```
## signed int32 - index of unit generator or -1 for a constant
```
this means that both the number of constants (`K`) and the number of unit generators (`U`) have to be expressed as signed ints, otherwise you have a logic error—it would be impossible to have `U == (unsigned int)(-1)` and then refer to its index in an `input-spec` that interprets `-1` as a constant. so, `K` and `U` must be signed. it looks to me like the 5 major counts in synth definition are  `K, U, P, N, V` for constants, ugens, initial arguments, parameter names, and variants. if 2 have to be signed, i think they should all be signed; IMO there is no need to add extra complexity there when these limits are so unlikely in common usage. that only leaves the input/output counts `I, O` in the ugen specs; you can guess what i'd prefer there, haha.

have i interpreted that right?

**Comment by telephon** [comment]
if we make a new format, it might be a good idea to support arrays of numbers.

**Comment by vivid-synth** [comment]
@brianlheim I don't think that's right: U, K, etc. are all counts and are all 0 or greater. In the case of an Input Spec (the only thing which can have a -1), it's 64 bits: a 32 bit signed int, and if that's -1, then the next 32 bits is a non-negative index of a constant. Otherwise the next 32 bits is an index of UGen output (also non-negative). The count of Input Specs (I) is always non-negative.

**Comment by brianlheim** [comment]
@vivid-synth then what is the first signed 32 bits of the input spec an index into? if it's not U then i must be misunderstanding the documentation altogether

**Comment by brianlheim** [comment]
ah okay, never mind. reading it a second time and considering the constraints of the problem i realize i was mistaken in saying that `K` was forced to be unsigned. still unclear on what `index of unit generator` means though; in particular, relative to what this index is calculated. i didn't mean to say that any of these counts could be non-negative in practice, just that if they were unsigned, it looks like there are places in the spec where you couldn't properly index into some of those unsigned values. sorry for the confusion.

well, my vote is still for all signed. the only reference i could find one way or another in the books i have is:

> Guideline: Avoid using `unsigned` in the interface; use `int` instead. 

from Large-scale C++ Software Design by Lakos, §9.2.2. The rationalization being that issues related to implicit signed -> unsigned conversions are hard to find and debug, and "the extra bit is rarely useful." This is written in '96 but i think is still relevant with current compiler diagnostics. for instance clang and gcc don't complain about assigning a negative literal to an unsigned int or comparing unsigned and signed ints with `==` unless you compile with `-Wextra`, which this project doesn't (but should).

**Comment by vivid-synth** [comment]
By "index of the unit generator" they mean like a list index. E.g. if there are 3 UGens in the SynthDef, if you want to reference them you can use values ```0```, ```1```, or ```2```.

**Comment by brianlheim** [comment]
@vivid-synth ah ok, that makes sense. and actually i realize i was completely wrong to begin with about that.

anyway, you have my opinion, and in addition while I was reading I found Bjarne's from The C++ Programming Language 4th ed.:

> The `unsigned` integer types are ideal for uses that treat storage as a bit array. Using an `unsigned` instead of an `int` to gain one more bit to represent positive integers is almost never a good idea. Attempt to ensure that some values are positive by declaring variables `unsigned` will typically be defeated by the implicit conversion rules.

it doesn't seem like anyone else is chiming in about this. maybe take it to the dev list if you want more opinions, or just change it yourself. otherwise i think this PR is going to get stale.

**Comment by vivid-synth** [comment]
It seems that treating these items as signed will involve the least amount of upheaval, so I'll stick to the needed correction. In that case we still do want to, for the sake of adherence to spec, possibly fix the ```uint```s here:

https://github.com/supercollider/supercollider/blob/master/server/scsynth/SC_GraphDef.h

**Comment by brianlheim** [comment]
i'm happy with this proposal.

@jamshark70 what do you think about this?

**Comment by jamshark70** [comment]
> @jamshark70 what do you think about this?

I don't very much care either way, but if I had to choose, I'd say: sclang doesn't have unsigned integers, and I don't see a good reason for scsynth's structs to disagree with that.

**Pull request merged**
