### PR TITLE
Fix behavior of nested multiline comments

### PR DESCRIPTION
**Pull request by brianlheim**
Fix for #2624.

Code in PyrLexer.cpp used to be:
```
		do {
			c = input0();
			if (c == '/' && prevc == '*') {
				if (--clevel <= 0) break;
			} else if (c == '*' && prevc == '/') clevel++;
			prevc = c;
		} while (c != 0);
```

When the lexer encountered a string like `/* /* */*/`, it would count the `*/*/` as `--clevel` for `*/`, then `++clevel` for `/*`, then `--clevel` for `*/`. I added a few lines so that it immediately eats up any `*/` or `/*` encountered.

Also changed the interpreter messages for open-ended strings/symbols/comments to remove the spurious `...`.

This works for me now:
`/*/* */*/` -> `nil`
`/* /* */ */` -> `nil`
`/*/* */*` -> `Open ended`
`3/*/**/*/*3` -> `9`

### CODE REVIEW

**Comment by vivid-synth** [comment]
Maybe worth adding a couple unit tests to make sure we don't regress?

**Comment by brianlheim** [comment]
@vivid-synth Good idea, although I've never done that before. Where would those go?

**Comment by vivid-synth** [comment]
There are some tests in the 'testsuite' dir -  @snappizz 's testsuite/classlibrary/TestSanitize.sc tests might be a good model.

You could try just running e.g. :

```
"/* /* */ */".interpret
"3 /* */".interpret
"3/*/**/*/*3".interpret
```

and making sure they all return sensible results (catching the error cases of course)

**Comment by snappizz** [comment]
I'd introduce `TestParser.sc` to hold general regression tests of this kind.

**Comment by brianlheim** [comment]
Working on it now. Problem is that the "open ended comment" message just shows up in the post window, it's not thrown as an error. How could I/Could I test for that?

**Comment by brianlheim** [comment]
Never mind, just realized I can add some numbers/methods after the text to see if the comments were closed or not.

**Comment by brianlheim** [comment]
Here are my unit tests, maybe a little excessive but for parsing errors I think it's hard to be too paranoid.

**Comment by snappizz** [comment]
Great! I suggest adding a comment noting that these are regression tests for a specific bug in multiline comment parsing.

**Comment by brianlheim** [comment]
@snappizz Done.

**Comment by vivid-synth** [comment]
Tests!! :raised_hands:

**Pull request merged**
