### PR TITLE
IDE extension to open multiple windows in support to the MainWindow

### PR DESCRIPTION
**Pull request by LucaDanieli**
This pull request creates a new class SubWindow, presenting similar characteristics to the MainWindow.

Every SubWindow can be opened arbitrarily, and each SubWindow has an optional documentsDocklet. All documentsDocklet are in sync with the one on the mainWindow.
Particularly, when the main documentsDocklet is detached, one unique documentsDocklet is shared among Editors.
Generally, all documents are shared among Editors.

The shortcuts introduced are:
Ctrl/Cmd + Alt + N = open a new SubWindow;
Ctrl/Cmd + Alt + W = close current SubWindow;
Ctrl/Cmd + Alt + E = open menu to switch Window;

Particularly, Scott and I have considered SubWindows as an alternative to splits, and for this reason we thought that there would not really the need to open different documents on different windows. For this reason, we thought better to sync all documents.

We also considered the alternative to make every SubWindow completely independent, but we thought that users would probably not need to open/create different projects at once. For now this pull request is thought to improve the organisation of windows/splits so to view and edit codes. The creation of independent windows might be an option for the future.

### CODE REVIEW

**Comment by LucaDanieli** [comment]
Please, try to run this pull request.
Particularly, I am looking for feedback about the stability of the application (specifically when changing session).

**Comment by brianlheim** [comment]
_Why are you adding 200 lines of definitions to a header file?_

**Comment by LucaDanieli** [comment]
Actually, In Ubuntu I noticed that if I added a new file, the build had to start from scratch (new cmake). I just thought that it was more handy to build it this way during the first round of reviews, and then transfer the new class to a new file *.h, as in the case of multi_splitter.h
If you say that it is better to create the new file now, I will do it straight away.

**Comment by brianlheim** [comment]
Yes, it's better to have something fully reviewable now. Tha extra build step takes about 20 seconds for me the first time, so it's really not that inconvenient.

**Comment by telephon** [comment]
@LucaDanieli @muellmusik what do you think? Do you want to add something (and/or fix @brianlheim request)?

**Comment by LucaDanieli** [comment]
Hi @telephon. Hope you are well!

Actually I have solved some issues on macintosh, but generally the problem is that I cannot work on the code right now because I have no MAC available (I will start working on it as soon as I will be back in Birmingham).

I did not push the last improvements as I have found a SUPER-bug that I could not understand: it seems that I have broken the CMD-"+/-" on the post_window in MAC but not the CTRL-"+/-" on Linux. Which was weird but I could not properly investigate on it at that moment.
Right now the branch is not ready for testing at all, unfortunately. I will try to work on it in 1 month hopefully.

**Comment by brianlheim** [comment]
thanks @LucaDanieli :) this is going to be a good extension once we have the kinks worked out

**Comment by brianlheim** [comment]
This hasn't been updated since last year and discussion has stagnated, so I'm closing for now.

**Pull request closed without merging**
