### PR TITLE
Unittest:run add class info to post, remove debug posts

### PR DESCRIPTION
**Pull request by adcxyz**
UnitTest logs currently contain some stray debug postings, and do not show a clear structure where which Test class run begins. 

---------

This PR removes the few leftover debug post commands in the UnitTest subclasses.
New feature: 
It adds separate line that posts when a new UnitTest subclass begins to run.
This is intended to make UnitTest logs easier and quicker to read.
This header line can be suppressed with a flag if desired. 

---------
- [x] All tests are passing - except unrelated hang reported in #3938
- [x] Updated documentation
- [x] This PR is ready for review

OLD post example: 
```
...
PASS: a TestScore: test_pattern_asScore_timingValues_multichannel - onsets should be correctly derived from lag and timingOffset in multichannel expanding
Is:
	 [ 0.8, 1.7, 3.0 ] 
Should be:
	 [ 0.8, 1.7, 3 ]
'/quit' message sent to server 'localhost'.   //// <-- (... here next class test starts, hard to see ...)
PASS: a TestNodeProxy: test_load_init - when server isn't running, the SynthDef should be built
...
```
NEW post example: 
```
PASS: a TestScore: test_pattern_asScore_timingValues_multichannel - onsets should be correctly derived from lag and timingOffset in multichannel expanding
Is:
	 [ 0.8, 1.7, 3.0 ] 
Should be:
	 [ 0.8, 1.7, 3 ]

*** RUNNING UNIT TESTS of: TestNodeProxy   // <--- added newline and header line
'/quit' message sent to server 'localhost'.
PASS: a TestNodeProxy: test_load_init - when server isn't running, the SynthDef should be built
```

### CODE REVIEW

**Comment by brianlheim** [comment]
This looks good to me! I've definitely missed that header post.

You checked "updated documentation" without actually updating the documentation. :)

**Comment by adcxyz** [comment]
> You checked "updated documentation" without actually updating the documentation. :)

yes, had written it, but not committed - done now 

> 
> Also, in markdown, text above a ----- creates a header. The hyphens need an empty line above and below to create a divider.
> 
> And, [ ] creates an empty checkbox, and [x] (no spaces) checks it.

thanks, fixed those as well. copy-pasting always gets sloppified ;-)

**Comment by adcxyz** [comment]
Hi @brianlheim, 

The differences in UnitTest:run info post between current 3.10 and the PR have become smaller:

- in current 3.10, when report is true, UnitTest:run post now begins with a short header, e.g. 
```
RUNNING UNIT TEST a TestServer
... etc
```
- postHeader PR: there is a separate flag for postHeader, true by default, and the post is more conspicuous - bold with ***, preceded by a blank line and grammatically better ;-)
```
*** RUNNING UNIT TESTs of: TestServer
... etc
```
I like the blank line, bold text and grammar better; 
I don't really have a preference whether to keep or drop the separate flag.
Do you have a preference about this?
Then I would update the PR one way or the other.

**Comment by telephon** [comment]
@adcxyz  I've resolved the conflicts, could you check if it is what you intended?

**Comment by brianlheim** [comment]
@telephon @adcxyz sorry for the long response time, i forgot this one was waiting on my input.

> Do you have a preference about this?

i like the second more grammatically correct posting :)

can this PR please be put into a state that doesn't have a merge commit? we generally try to avoid that because it makes some operations with git trickier.

**Comment by telephon** [comment]
> can this PR please be put into a state that doesn't have a merge commit? we generally try to avoid that because it makes some operations with git trickier.

What is missing? The commits looks clean as such.

**Comment by brianlheim** [comment]
look again, the last commit is a merge commit....

**Comment by muellmusik** [comment]
> look again, the last commit is a merge commit....

I'm happy to try to resolve this. Is the correct approach roll back the branch to before the merge commit, then rebase on develop?

**Comment by brianlheim** [comment]
> I'm happy to try to resolve this. Is the correct approach roll back the branch to before the merge commit, then rebase on develop?

yes! thanks

**Comment by muellmusik** [comment]
Okay, done! Actually just realised that I force pushed to @adcxyz's fork. 😳 Looks like that caused no problems though.

**Comment by adcxyz** [comment]
thanks for helping, scott!
and sorry for being so stupid at git, 
best a

**Comment by muellmusik** [comment]
Actually @adcxyz can you just confirm that the version of run is still correct? Think I might have done the wrong thing on conflict resolution.

**Comment by muellmusik** [comment]
> thanks for helping, scott!
> and sorry for being so stupid at git,

No worries! Hope I haven't just been stupid!

**Comment by adcxyz** [comment]
hm strange, I don't see a new commit in my branch?

**Comment by muellmusik** [comment]
No you wouldn’t but there was a conflict on rebase. I think I did it correctly but just wanted to be sure. Rebase conflicts seem to be a place where I get confused! It was just the run method. Everything else should be untouched. I may just be being paranoid!

**Comment by brianlheim** [comment]
this has conflicts again after #3623  was merged

**Comment by muellmusik** [comment]
Yay! Those look pretty straightforward actually. I can fix them.

**Comment by muellmusik** [comment]
> Yay! Those look pretty straightforward actually. I can fix them.

Okay, actually I tried to do that by rebasing locally, but that leads to what looks like a couple of trivial conflicts on GH resulting when fixed in a mountain of formatting changes? Ack! Any advice? 

I'm tempted to resolve them here, then reorder and squash?

**Comment by brianlheim** [comment]
> Okay, actually I tried to do that by rebasing locally, but that leads to what looks like a couple of trivial conflicts on GH resulting when fixed in a mountain of formatting changes? Ack! Any advice?

I don't understand what you mean by "when fixed in a mountain of formatting changes"

**Comment by brianlheim** [comment]
i tried it locally and had no issue.. not sure what you're seeing. here is what i did

```bash
git checkout develop
git pull
hub pr checkout 3939 # or however you want to check out this branch
git rebase -i develop
# fix merge conflicts
git rebase --continue
```

**Comment by muellmusik** [comment]
I mean I resolved the conflicts and then there seem to be a variety of additional changes (mostly formatting) that have been added to Alberto’s commits. I’m baffled.

**Comment by brianlheim** [comment]
like i said, works for me. i can't help you if you don't tell me details :)

**Comment by muellmusik** [comment]
Your description is what I did. Away from my computer now so can’t check any details. But if it worked for you please push it. We don’t need to hold this up while I sort my confusion out. :-)

**Comment by brianlheim** [comment]
i will open a separate PR then, because i am very uncomfortable force pushing to other people's repositories.

**Comment by muellmusik** [comment]
Okay, thanks Brian.

**Pull request closed without merging**
