### PR TITLE
test: Clock-nextTimeOnGrid

### PR DESCRIPTION
**Pull request by telephon**
This is to match PR #2101.

### CODE REVIEW

**Comment by brianlheim** [comment]
If this goes with #2101, could you please just add it there? Helps keep clutter down.

**Comment by telephon** [comment]
At the time when this current PR was started, there was no directory for tests. This is why I made a separate one.

**Comment by brianlheim** [comment]
Oh wow! I didn't realize the tests were that recent :)

**Comment by telephon** [comment]
The other PR is a year old now … :)

**Comment by telephon** [comment]
This is a test for #2101. Will reopen once we work on it again.

**Pull request closed without merging**
