### PR TITLE
use c++17-style executors to compile class library

### PR DESCRIPTION
**Pull request by timblechmann**
boost.threadpool was never official and is unmaintained. executor-based implementations are more robust and expressive.

### CODE REVIEW

**Comment by telephon** [comment]
You prefer this to go into the current bugfix version or better into 3.8 ?

**Comment by timblechmann** [comment]
i'm not managing releases anymore, so i don't have a strong opinion ...

**Comment by telephon** [comment]
In any case you are the best to judge the nature of the changes you have done.

**Comment by danstowell** [comment]
(fwiw, IMHO Julian I'd suggest landing this post-bugfix)

**Comment by telephon** [comment]
OK, good!

**Comment by scztt** [comment]
Not building - looks like this may require some additional cmake work?

**Comment by timblechmann** [comment]
fwiw, the 'not building' part is due to #1528 not being merged for ages

**Comment by danstowell** [comment]
Do I understand right, that the C++17 functionality is provided by boost, and this patch doesn't actually restrict choice of compiler in any dramatic way? I believe so, and I can compile the branch (on ubuntu 14.04 and gcc 4.8.4). If I understand right, this PR looks like good futureproofing to me

**Comment by timblechmann** [comment]
the *semantics* is c++17, the implementation is in boost.thread. it requires #1528, though.

**Comment by danstowell** [comment]
I'd like to merge this into master. (I've merged #1528 as Tim suggested.) However it'd be nice to have a green tick from the Travis CI first. Anyone know a way to make that happen? I guess one way would be for Tim to rebase this onto master (or merge master in) so the branch is updated.

**Comment by miczac** [comment]
"green tick" in terms of getting it checked (what apparently happened) or getting corrected?
https://travis-ci.org/supercollider/supercollider/builds/95395258

**Comment by danstowell** [comment]
@miczac well, getting it checked, but I think it can't quite happen without it getting corrected (which must mean this branch needs updating to include the changes made by #1528)

**Comment by timblechmann** [comment]
this branch does not build, because #1528 is not merged ... that should be merged, then i'll rebase this.

**Comment by danstowell** [comment]
@timblechmann thanks - I merged that about an hour ago, so you're clear to proceed

**Comment by timblechmann** [comment]
@danstowell ah great ... thanks a lot!

**Pull request merged**
