### PR TITLE
Update pointer to scvim submodule

### PR DESCRIPTION
**Pull request by bagong**

### CODE REVIEW

**Comment by bagong** [comment]
This does what is expected on OSX and Linux. But: in the current state of the repo, sclang then starts with a scvim-module related "primitive _FileWrite" error. It does nothing, you can just go on, but if you don't know what's wrong, you might get worried. I guess it goes away either by installing the plugin properly, or disabling it (which both isn't necessarily to be considered trivial). With all sympathies to scvim, I think we should disable building scvim by default, okay? Should I set the option to off and add this to this PR?

**Comment by bagong** [comment]
Done ;)

**Comment by gusano** [comment]
> I guess it goes away either by installing the plugin properly

@bagong What do you mean? How did you install it? Right now `scvim` *is* a vim plugin so if you don't install it properly it does not work.

**Comment by bagong** [comment]
@gusano, I just built SC with default settings on Linux. Result: dangerous looking error-message at class-compilation. If you install SC in a blank system, you will see it. 

If a user carefully reads the errors, she will understand that it has to do with scvim, but will likely not know how to fix it. So somebody who has never heard of vim will be confronted with an error that is only simple to fix if you are in the know. The same is not true for scel and sced.

I am not happy with setting scvim off by default, I like maintaining the notion that SC can be used with many editors, and I was happy when people were working on the plugin. But the state in which the repo has been left after the big overhaul, and the response time to trivial PRs has left me with doubts as to its maintainability.

**Comment by bagong** [comment]
We have another commit in scvim which fixes scvim on OSX. I'll update the pointer, let's not merge this right now.
@gusano , please don't misread my suggestion as a display of power. I would rather see you fix the current behaviour. I cross checked with a clean build. Currently if you build SC with default settings in a system where the actual plugin is not installed (just SCVim.sc into /usr/local/share/SuperCollider/Extensions/scvim) you get this error on startup:

````
ERROR: 
SCVim could not be initialized.
Consult the README to see how to install scvim.

ERROR: Primitive '_FileWrite' failed.
Failed.
RECEIVER:
Instance of File {    (0x55f2cb197b58, gc=A4, fmt=00, flg=00, set=02)
  instance variables [1]
    fileptr : nil
}
CALL STACK:
	MethodError:reportError   0x55f2c9835088
		arg this = <instance of PrimitiveFailedError>
	Nil:handleError   0x55f2cafd5b98
		arg this = nil
		arg error = <instance of PrimitiveFailedError>
	Thread:handleError   0x55f2c98b3ce8
		arg this = <instance of Thread>
		arg error = <instance of PrimitiveFailedError>
	Object:throw   0x55f2c947abe8
		arg this = <instance of PrimitiveFailedError>
	Object:primitiveFailed   0x55f2caffd9d8
		arg this = <instance of File>
	< closed FunctionDef >   0x55f2cb081ce8
		var classList = [*2227]
		var file = <instance of File>
		var hugeString = "syn keyword scObject TDuty_o..."
		var basePath = nil
	Function:doOnStartUp   0x55f2c9806138
		arg this = <instance of Function>
	ArrayedCollection:do   0x55f2c9749df8
		arg this = [*7]
		arg function = <instance of Function>
		var i = 4
	List:do   0x55f2c9749f58
		arg this = <instance of List>
		arg function = <instance of Function>
	Meta_StartUp:run   0x55f2c974a218
		arg this = <instance of Meta_StartUp>
	Main:startup   0x55f2c98f2608
		arg this = <instance of Main>
		var didWarnOverwrite = false
^^ The preceding error dump is for ERROR: Primitive '_FileWrite' failed.
Failed.
RECEIVER: a File
`````

This is far worse than what ATK caused before the 3.8 release, and that stirred up half of the SC community.

I am not sure that this is a solution for this problem, but in general you might also want to consider installing to scide_scvim rather than to scvim. As we just saw on OSX that has some beautiful effects. The code that explains this is in common/SC_DirUtils.cpp:

````
extern const char * gIdeName; // string used for conditional compilation according to which IDE is in use this session.
// for example, if the value is "scapp" then folders "scide_scapp" will be included, all other "scide_*" excluded.
````

**Comment by bagong** [comment]
Ah, @nillninull 's  PR took care of Linux as well. Verified to work properly on Linux now. I force pushed the pointer to the current head and undid setting scvim off by default. Thanks nillnull for quick action! This will likely generate some duplicate-class errors for a while now, but I don't think that can be avoided.

PS: I didn't get ctags to work on Linux, but that's maybe my fault. Other than that it's lovely. You can use it via ssh and get both the sclang terminal and help-browser, in separate Windows via ssh-x. Probably any gui works. The server boots even in user mode! Thanks to everybody for a cool plugin and sorry for the alarmism.

**Comment by bagong** [comment]
As this has been approved already, I'll take the liberty to shorten the PR Queue myself ;) Thanks all.

PS: I do think @sbl and @carlocapocasa should be firmly invited to become collaborators in the scvim repo in the supercollider org and feel welcome here. It is a sign of respect for their work and could be very useful for us. I hesitate to do it myself as I feel this subcommunity has it's own internal dynamics...

**Comment by snappizz** [comment]
After `git pull upstream master && git submodule update && git submodule sync`, I am still getting the error

    SCVim could not be initialized.
    Consult the README to see how to install scvim.
    ERROR: Primitive '_FileWrite' failed.

Not only that, but the error breaks all functionality that relies on `StartUp.add`. If an error happens in one startup function, no other startup functions run. For example, `[1, 2, 3].plot` also returns an error because `GUI.skin[\plot]` was not initialized.

Any way to fix this?

**Comment by bagong** [comment]
A bit more context? The error is triggered from SCVim.sc. Where is yours, do you have multiple?

**Comment by carlocapocasa** [comment]
Looking at the SCvim.sc source, it insists that there is a folder within ~/.vim that contains a folder called scvim to populate its base path.

This has been satisfied in the past by cloning scvim into ~/.vim/bundle, so you can do a workaround:

mkdir -p ~/.vim/bundle
cd ~/.vim/bundle
ln -s ../../.local/src/supercollider/editors/scvim # replace with your path

I'll have a look at how to best fix it

**Comment by bagong** [comment]
@carlocapocasa , this should have already been fixed in the updated version by "installing" (copying) SCVim.sc to Extensions/scide_scvim rather than Extensions/scvim during the install stage of the build. In that case SCVim.sc is only read by sclang if sclang is started form scvim.
The question is why @snappizz is now still getting the error. As an aside (it shouldn't be relevant here): you want to run `submodule sync` before `submodule update`, and not the other way round ;)

**Comment by snappizz** [comment]
Solved by trashing `~/usr/local/share/SuperCollider/Extensions/` and running `make install` again. Looks like `SCVim.sc` was installed to `Extensions/scide_scvim`, but `make install` didn't clear out the old location at `Extensions/scvim`.

**Comment by bagong** [comment]
Yea, cleaning out stuff is not *install*'s job, it is *uninstalls* job. `sudo make uninstall` actually does do a pretty clean job on Linux. If you have a look in SCVim's CMakeLists.txt, they do provide for uninstall.
@snappizz, oho, running SC in your user folder. That's pretty interesting. I am surprised that's possible ;)

**Comment by gusano** [comment]
> I do think @sbl and @carlocapocasa should be firmly invited to become collaborators in the scvim repo in the supercollider org and feel welcome here

@bagong done = )

**Comment by bagong** [comment]
Very cool, thank you!

**Comment by carlocapocasa** [comment]
> I do think @sbl and @carlocapocasa should be firmly invited to become collaborators in the scvim repo in the supercollider org and feel welcome here

Thank you!

**Comment by bagong** [comment]
You're welcome! Thanks for joining!

**Pull request merged**
