### PR TITLE
Scide/line number fix

### PR DESCRIPTION
**Pull request by vdonnefort**
Here's the reverted patchs requested. See #1302

### CODE REVIEW

**Comment by bagong** [comment]
The line indicator width is nice now for me. The focus rectangle is removed to the left a few pixels now, probably not your fault, but it is. Personally I don't like the focus rectangle that much. Setting the default for "Inactive Window Fade" higher (96 is good for me) is stronger and leaves the overall appearance cleaner. But that's a question of taste, of course.

**Comment by telephon** [comment]
When you have no setting (in the preferences) for line numbers (I don't know if that is the default, but it was the case here), the numbers are invisible. Is that supposed to be correct?

**Comment by vdonnefort** [comment]
@telephon, what do you mean by "no setting"? Transparent?

**Comment by telephon** [comment]
Yes, I suppose (it is the default setting):

**Comment by bagong** [comment]
@telephon: what I currently see is different, not clean but safe: background cannot be changed, and changes to number/foreground color are simply not stored. So the numbers won't disappear, but you can't get red numbers on yellow background, not even green numbers on fixed grey background ;)

But is this related to this pull request? I only see handling of the column width, which is a change to the better and doesn't seem to cause problems.

Unfortunately the PR is combined with reverting removing the focus-frame. I personally don't like it, and 
in the past I saw that currently reverting the old state causes the frame to appear in an slightly offset position... We need a word, and possibly a fix here...

**Comment by sensestage** [comment]
is there a solution for this issue already?

**Comment by bagong** [comment]
The issue is not clear any more ;) But the width of the line-number column is adequate now by commit 45f8854. I don't think anybody has looked at the focus frame.

**Comment by sensestage** [comment]
My issue is mostly that starting up, I was missing the linenumbers, even though it was selected as being on in the preferences.

**Comment by bagong** [comment]
I think that's a different issue...

**Comment by bagong** [comment]
Could removing the frame and making the line numbers-column more narrow be separated? As for me, I don't miss the frame, but the line-number column is broader than required.

**Comment by crucialfelix** [comment]
can I get an amen ?

**Comment by vdonnefort** [comment]
Amen!

**Pull request merged**
