### PR TITLE
Update pointer to scvim submodule to latest and greatest

### PR DESCRIPTION
**Pull request by bagong**
I think this is still required? Or shouldn't the changes go to SC master yet? (@gusano , @blacksound )
Note: while the diff indicate a lot of change to scmaster, what really changes is only the hash pointing into the scvim submodule.

### CODE REVIEW

**Comment by brianlheim** [comment]
Thanks for catching this!

**Comment by brianlheim** [comment]
(I think this sync is trivial; if a submodule updates, we should update as well—we marked off the issue in our repo, after all!)

**Comment by bagong** [comment]
Sure... If the contributors still wanted a testing period, they would have likely said so. 

On another line: I was wondering if we shouldn't invite the original contributors to this version of the scvim module to become collaborators in the scvim repo within the sc-organizations. That would allow to maintain some sense of ownership and could foster participation in module maintenance within SC.

**Comment by brianlheim** [comment]
Yes, I think that's a great idea!

**Pull request merged**
