### PR TITLE
Fix printing filepath at end of recording

### PR DESCRIPTION
**Pull request by bagong**
issue #2432

### CODE REVIEW

**Comment by telephon** [comment]
Looks good. But maybe instead we could finally dare to merge https://github.com/supercollider/supercollider/pull/2422 ? Need to check why there was a travis failure though.

Maybe you can have a brief review of the code.

**Comment by crucialfelix** [comment]
We can't merge #2422 in 3.8, we are already in beta. It's probably about ready for master though.

**Comment by bagong** [comment]
I think this guy can't do any harm? It's just what get's printed at the end of a recording? Not that it's important, but it's not in conflict with #2422. Maybe the milestone was changed by accident?

**Comment by crucialfelix** [comment]
I just missed that it was on 3.8 branch. thanks for spotting it !

**Pull request merged**
