### PR TITLE
Topic/upgrade boost 1.80.0

### LINKED ISSUE #5865: ERROR: Primitive '_FileCopy' failed. when starting scide - boost needs upgrade to higher version to fix
My /home is mounted on a different physical disk than /usr. 

When starting scide, I get the following error:
```
*** Welcome to SuperCollider 3.13.0-dev. *** For help press Ctrl-D.
Couldn't set realtime scheduling priority 1: Operation not permitted
SCDoc: Indexing help-files...
ERROR: Primitive '_FileCopy' failed.
caught exception 'Invalid cross-device link: copy from "/usr/local/share/SuperCollider/HelpSource/browse.css" to "/home/shimpe/.local/share/SuperCollider/Help/browse.css"' in primitive in method Meta_File:copy
RECEIVER:
class File (0x563d1fd95400) {
  instance variables [19]
    name : Symbol 'File'
    nextclass : instance of Meta_FileDialog (0x563d1f9419c0, size=19, set=5)
    superclass : Symbol 'UnixFILE'
    subclasses : nil
    methods : instance of Array (0x563d1fd95580, size=12, set=4)
    instVarNames : instance of SymbolArray (0x563d1fd95700, size=1, set=2)
    classVarNames : instance of SymbolArray (0x563d1fd95880, size=1, set=2)
    iprototype : instance of Array (0x563d1fd957c0, size=1, set=2)
    cprototype : instance of Array (0x563d1fd95940, size=1, set=2)
    constNames : nil
    constValues : nil
    instanceFormat : Integer 0
    instanceFlags : Integer 0
    classIndex : Integer 1077
    classFlags : Integer 0
    maxSubclassIndex : Integer 1077
    filenameSymbol : Symbol '/usr/local/share/SuperCollider/SCClassLibrary/Common/Files/File.sc'
    charPos : Integer 0
    classVarIndex : Integer 212
}

PROTECTED CALL STACK:
	Meta_MethodError:new	0x563d1f733700
		arg this = PrimitiveFailedError
		arg what = caught exception 'Invalid cross-device link: copy from "/usr/local/share/SuperCollider/HelpSource/browse.css" to "/home/shimpe/.local/share/SuperCollider/Help/browse.css"' in primitive in method Meta_File:copy
		arg receiver = File
	Meta_PrimitiveFailedError:new	0x563d1f73b540
		arg this = PrimitiveFailedError
		arg receiver = File
	Object:primitiveFailed	0x563d1f158d00
		arg this = File
	ArrayedCollection:do	0x563d20200ac0
		arg this = [ [ /usr/local/share/SuperCollider/HelpSource/BrokenLink.html, BrokenLink.html ], [ /usr/local/share/SuperCollider/HelpSource/browse.css, browse.css ], [ /usr/local/share/SuperCollider/HelpSource/Browse.html, Browse.html ], [ /usr/local/share/SuperCollider/HelpSource/browse.js, browse.js ], [ /usr/local/share/SuperCollider/HelpSource/codemirror.css, codemirror.css ], [ /usr/local/share/SuperCollider/HelpSource/editor.css, editor.css ], [ /usr/local/share/SuperCollider/HelpSource/editor.js, editor.js ], [ /u...etc...
		arg function = a Function
		var i = 1
	Meta_SCDoc:indexAllDocuments	0x563d1f65afc0
		arg this = SCDoc
		arg clearCache = false
		var now = 0.549377424
		var key = Classes/String
		var doc = SCDocEntry("Classes/QKeyModifiers", "QKeyModifiers", "(Undocumented class)")
		var nonHelpFiles = [ [ /usr/local/share/SuperCollider/HelpSource/BrokenLink.html, BrokenLink.html ], [ /usr/local/share/SuperCollider/HelpSource/browse.css, browse.css ], [ /usr/local/share/SuperCollider/HelpSource/Browse.html, Browse.html ], [ /usr/local/share/SuperCollider/HelpSource/browse.js, browse.js ], [ /usr/local/share/SuperCollider/HelpSource/codemirror.css, codemirror.css ], [ /usr/local/share/SuperCollider/HelpSource/editor.css, editor.css ], [ /usr/local/share/SuperCollider/HelpSource/editor.js, editor.js ], [ /u...etc...
		var undocClasses = IdentitySet[ BelaServerOptions, Range, PureMultiOutUGen, QDragSink, BinaryOpXStream, NodeID, DrawGridX, AbstractGroup, MIDIEvent, MethodQuote, QCurve, OutOfContextReturnError, QTextViewBase, QDialog, ScopeBuffer, FuncStreamAsRoutine, Penv, PatternControl, HIDFuncDeviceProtoMatcher, QCallback, QFont, QRenderProcessTerminationStatus, PlusFreqScopeWindow, HIDElementProtoDispatcher, MIDISMPTEAssembler, QScope, QScope2, CurveWarp, QColorGroup, BlankGridLines, QNumberBox, CleanupStream, TextArchiveMDPlugin, HIDRa...etc...
		var additions = Dictionary[ (Classes/String -> [ /usr/local/share/SuperCollider/HelpSource/Classes/String.ext.schelp ]) ]
	Meta_SCDoc:documents	0x563d1f65e980
		arg this = SCDoc
	Meta_SCDoc:prepareHelpForURL	0x563d1f662c00
		arg this = SCDoc
		arg url = file:///home/shimpe/.local/share/SuperCollider/Help/Help.html
		var path = /home/shimpe/.local/share/SuperCollider/Help/Help.html
		var targetBasePath = /home/shimpe/.local/share/SuperCollider/Help
		var pathIsCaseInsensitive = false
		var subtarget = Help
		var src = nil
		var c = nil
		var cmd = nil
		var doc = nil
		var destExist = false
		var destMtime = nil
		var verpath = /home/shimpe/.local/share/SuperCollider/Help/version
	a FunctionDef	0x563d1efa4400
		sourceCode = "<an open Function>"
	Function:prTry	0x563d1f9c1100
		arg this = a Function
		var result = nil
		var thread = a Routine
		var next = nil
		var wasInProtectedFunc = true
	
CALL STACK:
	MethodError:reportError
		arg this = <instance of PrimitiveFailedError>
	< closed FunctionDef >
		arg error = <instance of PrimitiveFailedError>
	Integer:forBy
		arg this = 0
		arg endval = 0
		arg stepval = 2
		arg function = <instance of Function>
		var i = 0
		var j = 0
	SequenceableCollection:pairsDo
		arg this = [*2]
		arg function = <instance of Function>
	Scheduler:seconds_
		arg this = <instance of Scheduler>
		arg newSeconds = 0.742669093
	Meta_AppClock:tick
		arg this = <instance of Meta_AppClock>
		var saveClock = <instance of Meta_SystemClock>
	Process:tick
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Primitive '_FileCopy' failed.
caught exception 'Invalid cross-device link: copy from "/usr/local/share/SuperCollider/HelpSource/browse.css" to "/home/shimpe/.local/share/SuperCollider/Help/browse.css"' in primitive in method Meta_File:copy
RECEIVER: File
```

### PR DESCRIPTION
**Pull request by shimpe**
## Purpose and Motivation
Fixes #5865

## Types of changes
- Bug fix
- Upgrade of boost version to 1.80.0

## To-do list

- [X ] Code is tested (on a few of my own projects)
- [X ] All tests are passing
- [ ] Updated documentation
- [ X] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Thank you @shimpe 
I think this is great. And thanks for making sure the macOS legacy build still works.
Just FYI - I won't have time to review/test this properly until we finalize the 3.13 release.
I have one suggestion: it was [previously suggested](https://github.com/supercollider/supercollider/pull/5153#:~:text=applies%20sc%2Dorg%20boost%20patches%20(i%20don%27t%20feel%20these%20are%20necessary%20anymore%20but%20kept%20them%20in%20this%20PR)) that we might not need the SC-specific patches to boost anymore. Would you be willing to test (maybe push a separate branch) without the patches to see if that still works? If it does, I'd like to consider unpatched boost.

**Comment by shimpe** [comment]
Thanks for commenting. Unpatched boost would be great indeed. I'll try.

**Comment by dyfer** [comment]
IMO we can close this in favor of https://github.com/supercollider/supercollider/pull/5924. Do you agree @shimpe ?

**Comment by shimpe** [comment]
Yes this can be closed!

**Pull request closed without merging**
