### PR TITLE
cmake: use bundled yaml-cpp by default

### PR DESCRIPTION
**Pull request by timblechmann**

### CODE REVIEW

**Comment by danstowell** [comment]
no objections from me - it means less pain for people.

(debian people insist on using system yaml, but no reason it should be default for everyone)

**Comment by timblechmann** [comment]
debian people are more than welcome to port the current implementation to compile with yamlcpp-0.5.

of course this won't happen, as well as nobody else will have a look into it, as it is a boring engineering task, that does not introduce any new/exciting features.

**Comment by danstowell** [comment]
Please drop the sarcasm! No need! debian ships libyaml-cpp0.3

**Comment by timblechmann** [comment]
sc ships it, too. fwiw, "we" also provide bug fixes to our 3rdparty libraries to work around upstream bugs (not for yamlcpp, but for boost-1.57)

**Comment by bagong** [comment]
After Dans comment this is non-controversial

**Comment by danstowell** [comment]
@bagong possibly some confusion - I don't think my (latest) comment makes a difference. Since SC requires version 0.3 of libyaml-cpp, and no-one here is proposing to change that situation, we either require it as a dependency, or use the bundled version. We already allow both possibilities. The question is which of those possibilities should be default.

To be completely clear: I **support** this PR, as suggested in my first comment :) It's not controversial IMHO

**Comment by bagong** [comment]
Nono, I was referring to your first comment, sorry for the confusion. All is fine :)

**Pull request merged**
