### PR TITLE
Update linux travis recipe

### PR DESCRIPTION
**Pull request by patrickdupuis**
Let's see if this executes ok in Travis.

### CODE REVIEW

**Comment by patrickdupuis** [comment]
`apt-get install` can't find package `qt55-meta`

**Comment by bagong** [comment]
If I add that qt55 ppa on a vanilla ubuntu (not a travis image) the options for qt55 I get are:

- qt55-meta-full - The full stack of Qt 5.5 release
- qt55-meta-minimal - Minimal core of Qt 5.5 release
- qt55-meta-dbg-full - The full dbg stack of Qt 5.5 release

Maybe try one of those?

**Comment by patrickdupuis** [comment]
I based my last commit on this:
https://github.com/mariokonrad/vhf-sim/blob/master/.travis.yml

**Comment by bagong** [comment]
Ah, okay, then we're diverging from now on ;)

**Comment by patrickdupuis** [comment]
trying qt55-meta-full

**Comment by bagong** [comment]
wanna Gitter?

**Comment by patrickdupuis** [comment]
I had to look up Gitter! :) sorry, have to stop doing this soon.

It seems to be working, right?

**Comment by bagong** [comment]
Lets see. Looks good atm ;)

**Comment by patrickdupuis** [comment]
Since you have a Ubuntu machine to test on, do you think you can determine exactly what Qt packages are needed from thsi PPA? That's the next thing I want to try (maybe in a different PR though)

**Comment by bagong** [comment]
How would you go about that?
I tried installing the meta-minimum and got a cmake error:
```
CMake Error at /opt/qt55/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:9 (message):
  Failed to find "GL/gl.h" in "/usr/include/libdrm".
Call Stack (most recent call first):
  /opt/qt55/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:146 (include)
  /opt/qt55/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:87 (find_package)
  QtCollider/CMakeLists.txt:6 (find_package)
  lang/CMakeLists.txt:173 (include)


   Called from: [5]	/opt/qt55/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake
                [4]	/opt/qt55/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake
                [3]	/opt/qt55/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake
                [2]	/home/parallels/supercollider/QtCollider/CMakeLists.txt
                [1]	/home/parallels/supercollider/lang/CMakeLists.txt
   Returning to         /home/parallels/supercollider
   Called from: [1]	/home/parallels/supercollider/CMakeLists.txt
-- Configuring incomplete, errors occurred!
```

**Comment by bagong** [comment]
ah, needed sudo apt-get install libglu1-mesa-dev
Now I am at qt. still errors

**Comment by bagong** [comment]
It's asking for these:
Qt5LinguistTools
Qt5Positioning
Qt5Sensors
Qt5WebKitWidgets

**Comment by bagong** [comment]
I think it's these:

- qt55location
- qt55sensors
- qt55tools
- qt55webchannel
- qt55webkit
- qt55xmlpatterns
- qt55declarative
- qt55base

**Comment by bagong** [comment]
Works with those packages for master and 3.7.
Not sure though, if I'd leave away that -trusty suffix.

**Comment by patrickdupuis** [comment]
Thanks @bagong! I added webengine to your list. We'll need it for future development (replaces webkit).

The "-trusty" suffix is back.

**Comment by bagong** [comment]
Maybe a more general thought is in place too? Seems to me this creates kind of a "safe" build environment for Linux. With the relative modern compiler (compared to the default on linux distributions) and frozen Qt, things are likely to compile. So do I understand correctly that this build isn't primarily intended to ring alarm builds any more, if a build with default distro-typical setting breaks due to changes in either the SC code base or in a/the distro?

**Comment by crucialfelix** [comment]
Its ready to merge now, right ?

**Comment by bagong** [comment]
It's great in that it fixes the current build problems in master, but in my view it also changes the function of the travis build to be less that of a warner that we have to expect problems for people that build with default settings in their own distribution. It reinforces a change of policy from "support as many distributions as possible" to "support a single build environment, even if it requires adjustments to your distributions defaults that could be quite difficult to install". The beauty of the Linux build was that you just needed to install a few packages the usual way, type `cmake ..` and then build. That's not easy to support, but it used to be a goal. Maybe wait a few days to see if somebody chimes in and commit then? I think people like @scztt are not listening at the moment because they are busy with more exciting stuff on a SC event? ;)

**Comment by patrickdupuis** [comment]
Yes - it is ready. 
I would like to hear what the other linux devs have to say about the point @bagong makes. As it stands, Ubuntu 14.04LTS doesn't meet SC's Qt requirements (it has Qt 5.2). Debian stable has Qt 5.3, which is good. Both Ubuntu and Debian have gcc 4.8 (4.9 is available but not the default). In a month, the next Ubuntu LTS will be released and bring with it updated packages. Sadly, there always comes a time when Debian stable no longer meets SC's build requirements.
I think the choice of gcc 4.9 in Travis is sound. Should we be using Qt 5.3, which is the minimum required according to the readme, or should the linux build use Qt 5.5 like the OSX build?

**Comment by bagong** [comment]
It seems everybody is happy... Should I commit? I am eager to see the effect of some PRs and the 3.7.1 stuff on master ;)

**Comment by crucialfelix** [comment]
merged. some of those PR would have to be rebased before they would pass.

On Wed, Mar 30, 2016 at 11:36 AM Rainer Schütz <notifications@github.com>
wrote:

> It seems everybody is happy... Should I commit? I am eager to see the
> effect of some PRs and the 3.7.1 stuff on master ;)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/pull/1932#issuecomment-203346374>
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Pull request merged**
