### PR TITLE
typo correction: change Ugen/Ugens in help documents to UGen/UGens

### PR DESCRIPTION
**Pull request by prko**
## Purpose and Motivation
I recently saw a PR where Ugen was considered a typo. I found all these things in the built-in schelp and changed it accordingly.

## Types of changes

- Documentation

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by JordanHendersonMusic** [comment]
Looks good, thanks!

Could you maybe just describe what the non-latin change is? The diff is bigger than the rest.

**Review by JordanHendersonMusic — APPROVED** [review]
All good, this does what it claims. Thanks @prko

**Comment by prko** [comment]
@JordanHendersonMusic My pleasure! Thanks!

**Comment by prko** [comment]
@JordanHendersonMusic Oh, I missed a post of yours that was deleted. Um... I don't understand Japanese... haha... It seems to have been resolved anyway!

**Comment by mtmccrea** [comment]
@prko 
To keep the git history clean, please prefer [rebasing your branch onto develop](https://github.com/supercollider/supercollider/wiki/Rebasing-a-PR) rather than merging develop into your branch.

**Comment by prko** [comment]
@mtmccrea Thanks for letting me know!

**Pull request merged**
