### PR TITLE
quarks: sort list by name

### LINKED ISSUE #2212: Quarks list is in random order by default
screenshot_2016-06-29_11-38-36

### PR DESCRIPTION
**Pull request by gusano**
Fixes #2212

### CODE REVIEW

**Comment by snappizz** [comment]
lgtm

**Comment by crucialfelix** [comment]
See my comments on #2212  I think that's a better solution.

**Comment by crucialfelix** [comment]
I see what you did here - that does work to make the names in order. It was the dictionary that randomized it.

What I mentioned in the other comment about squirming when you un/install is still an issue, but we could merge this PR here and it would solve the main problem now.

**Comment by gusano** [comment]
:+1:

**Comment by crucialfelix** [comment]
interesting: it now orders them by installed, those you've checked out, those you've never checked out.  

and each section is alphabetical

screen shot 2016-06-30 at 12 42 42

**Pull request merged**
