### PR TITLE
Topic event type improvements

### PR DESCRIPTION
**Pull request by telephon**
(moved to this PR because of typo in the branch name)

This is a new feature: configure not only event type functions, but also their immediate default parent event. For those who use event types a lot, the missing possibility may ring a bell.

This is just a first suggestion, please feel free to comment.

### CODE REVIEW

**Comment by telephon** [comment]
Opinions?

**Comment by brianlheim** [comment]
This conflicts with master now.

@telephon I would be able to more easily give feedback on additions like this if you spent some time documenting what you've changed, why it was necessary, gave some reasons for why you chose to fix it this way, and what points in particular would be good to discuss. It really puts a heavy burden on me as a collaborator to have to piece together what you're trying to do from a brief description and a few dozen lines of (mostly commentless) code.

This is not really a criticism or a demand, but I would just like to make it clear that I really want to discuss (and hopefully merge) your contributions, and right now I find myself unable to do so because they are confusing to me.

**Comment by telephon** [comment]
yes, sorry, this assumes that the reader is already acquainted with the existing implementation. I don't think I should add conments to the code. But yes of course I can explain, and once we agree that it is the best solution I' ll update the help. 

I'll come back with some examples.

**Comment by jamshark70** [comment]
Writing as someone who is intimately familiar with the event system, I can say Julian's approach here is fine. If there's any quibble, it's that it maintains two collections with the same event type keys (where the `parent` one is optional) rather than a single collection of some data type that associates the event type function with its parent event. That's an extremely minor comment, as the collections are dictionaries (unordered, hence easier to keep in sync than parallel arrays), and it's largely a matter of personal coding style, but there's nothing particularly wrong here that I can see at a glance.

In fact my ddwChucklib quark has a `ProtoEvent` class to deal with the lack that Julian is addressing here.

**Comment by jamshark70** [comment]
I just took the liberty of resolving that conflict btw...

**Comment by telephon** [comment]
Thank you, James. Have you pushed the resolved conflict? I don't see it here.

On the long run, we should take a look at various quarks and see what we should integrate into core.

**Comment by jamshark70** [comment]
Well, I have to say, I'm somewhat perplexed at github's behavior here.

When I looked at this, I was not on my main development machine. I suspected the conflict was minor, and I noticed a button in the github Web interface to resolve the conflict. So I clicked it, and github showed me the conflict in Event.sc, which I cleaned up and then clicked the button to commit the fix. As a result, there is now a commit, "Merge branch 'master' into topic-event-type-improvements":

https://github.com/supercollider/supercollider/pull/2227/commits/ab41e16965b21bd7901be165d0890636812aa355?diff=unified

But... whaaaa? There was no indication in github's interface that "resolving a conflict in one file" would be the same as "merging from master." Further confusing is that github's desktop-style site doesn't display the diff for this commit at all -- but if I go on my phone and look at it in the mobile interface, it shows thousands of lines of changes in multiple files. Again, there was no warning that it would be this invasive.

I guess it's not a big deal because most of the changes that I just merged already exist in master and they won't be repeated... but it does make it next to impossible for you to review the conflict resolution. So I'm really quite irritated with the outcome of using the github website for editing (and @bagong, while I see your point about keeping these website conveniences available -- it seems to me this particular convenience from github is poorly implemented and caused a problem... that is, I just had to take 10 minutes to explain what happened, instead of spending the 10 minutes solving a real problem).

**Comment by bagong** [comment]
Hehe, @jamshark70 with the sharp teeth, still fighting :smile: Maybe just don't use those scary buttons? Or use the cancel button, if you aren't sure it's okay what you're doing? :smile:

Conflict resolution only becomes necessary if two defined branches are merged. When you do your PR you define those two branches (when we're close to a SC release and are expected to commit bugfixes to the release branch, we sometimes see that people often think they make the PR to the repo rather than a branch ;) ). So the procedure that determines which conflicts have to be resolved is a given. In order to get prompted for the resolution, you do the merge. And then you get that commit-message. If you diff the PR against master you should see what changed.

**Comment by jamshark70** [comment]
> Hehe, @jamshark70 with the sharp teeth, still fighting 😄 Maybe just don't use those scary buttons? Or use the cancel button, if you aren't sure it's okay what you're doing?

:D not fighting exactly, just pointing out a concrete case.

I would have used the cancel button if github had not presented a misleading view of the action in question. I'm aware it's probably fine for the merge but... git is confusing enough without github actively hiding information from the user :D

**Comment by telephon** [comment]
@jamshark if i had done it from scratch, i would have implemented it as only a single dictionary of events, each of which had a play function from the types. In other words, `\type` would look up an event. But I wanted to keep the change small.

We are so conservative ! Supercollider should be permitted to change more radically. But if course that is difficult if we have to keep ironing out old issues.

**Comment by telephon** [comment]
@jamshark70 is it correctly summarized as follows?
>Writing as someone who is intimately familiar with the event system, I can say Julian's approach here is fine. 

Or did you have too much of a quibble with it?

**Comment by jamshark70** [comment]
No, not too much. I think it's fine.

**Comment by jamshark70** [comment]
Pending documentation of course.

It might be worth trying the merge locally before merging here, because of that pesky "merge from master" that github tricked me into awhile back.

**Comment by telephon** [comment]
I tested, merges well locally. I'll write up some documentation.

**Comment by telephon** [comment]
For those who don't want to look into it in detail, here is an example what you can do with it:

```

Event.addEventType(\test, { ("x was" + ~x).postln }, (x: 450));

(type: \test).play;
(type: \test, \x: 7).play;

Event.addEventType(\test, { ("x was" + ~x.value).postln }, (x: { ~y + 1 }, y: 0));

(type: \test).play;
(type: \test, \y: 7).play;
(type: \test, \x: 10).play;
```

**Comment by telephon** [comment]
I've made an adjustment: now the `proto` instance variable is used, so that the original `parent` is kept intact and we don't need to add the default event as a parent to each prototype separately.

**Comment by jamshark70** [comment]
Hm. The last change will conflict, for instance, with the usage `aMixerChannel.play(pattern)`, which uses the proto variable to set the event's group and out bus to match the mixer. So, if the event type depends on logic in the proto, and the mixer has specified a proto, the event type proto will not be imported, meaning that the event type logic will be missing and the event won't play properly.

IMO the definition up to now has been:

- Event play logic goes into the parent event.
- The user may optionally use the proto for values that will not change across multiple events, but AFAIK the proto has always been for user values.

I think it's risky to change that, so I have doubts about this move. Just because most people don't use `proto` doesn't mean it's "free" to use for anything.

**Comment by telephon** [comment]
@jamshark70 ok, this is a reasonable point, I'll think about it.

We could also use `insertParent` to insert the event into the parent chain. This is not as efficient however.

**Comment by telephon** [comment]
we could do something like:

`protoEventType !? { currentEnvironment.insertParent(protoEventType.copy) };`

but then the protoEventType can't have a parent itself (unless we want to use a `deepCopy`).

**Comment by jamshark70** [comment]
I guess the trade-off here is:

- Use only `parent` for event types: Smaller API change (`proto` retains its original meaning), but a user creating a new event type needs to include the parent event explicitly to inherit from it (or include partialEvents explicitly) -- so it's a bit fussier at the time of creating the event type.

- Insert into `proto`: Parent event remains intact, but we have to be very careful about how (in what order) information goes into the `proto`. And, as you noted, it isn't the most efficient.

Unless there's a really solid reason for the second one, I think I'm in favor of the first.

1. If you're creating an event type, you already know what you're doing. Beginning users are generally not going to do this. It's totally fair to put the burden onto advanced users.

2. Smaller change = less risk. I already mentioned the risk of interaction with existing extensions or user code that already use `proto`. There might be other risks I haven't thought of.

3. Simpler to document and maintain: the `parent` and `proto` both have clear-cut roles, instead of splitting "parent" functionality over both variables (raising the question: why should a user put some of the logic in one and not the other?).

Final point: I don't think we should force all users to use the default parent event in every alternate event type. The default parent should be available, but not mandatory (though I guess it is mandatory now... hm... which is why I have `ProtoEvent` in ddwChucklib).

**Comment by telephon** [comment]
what about checking that, if there is a proto already, add it as a proto of the proto? Or add it to the proto of the parent ...

**Comment by telephon** [comment]
@jamshark70  fair points.
My main reason for using `proto` were: 
- more efficient than inserting a parent into the chain
- you do not block the possibility of passing parents into the event chain.

Let me explain the second point a bit better.

Usually, an EventStreamPlayer passes up an `Event.default` as an inval into the pattern chain. This default event usually has a parent event with basic settings (`Event.new(8, nil, defaultParentEvent, true);` Now if we assume that passing such events should somehow be transparent also when you define an event type with some parameters attached to it (now in proto), then we shouldn't really replace it with another event, but only amend it with the extra parameters.

So simply setting it as a parent is less than optimal. I think the case with proto is much rarer at least (but I see your point of course).

**Comment by jamshark70** [comment]
Rereading... actually, it's kind of meaningless to talk about replacing the parent completely, because it's the default parent event that implements event types in the first place. If you replace the parent, probably you don't have event types anymore. So that was a useless suggestion from me.

Putting the parent-modifier into the final event's proto means either:

- Efficient way: Replace the final event's `proto`. User cannot use `proto` for anything else. That's bad.
- Inefficient way: Merge the user's `proto` into the parent-modifier. That *may* be less inefficient than `Pchain(pattern, (default: value))`, but it's difficult to see by how much.

So you have either a loss of functionality, or additional complexity without a corresponding significant gain in efficiency (unless you want to benchmark and prove me wrong about the speed). *But* the gain, even in the "inefficient way," is that the user can invoke defaults using only an event type ID, instead of being responsible for Pchaining everything. So that would still be worthwhile (just saying, let's identify the correct gain: the point is user convenience, not necessarily efficiency -- and if efficiency leads to a risky situation, as I'm about to suggest, then efficiency should be scrapped).

Alternately -- intending this as a cautionary! -- we could stipulate:

- Parent events should leave their own `proto` variables empty. (There is not really a reason to split up a parent event's functionality between `parent` and `proto` -- especially since `proto` is, AFAIK, supposed to be reserved for user customization.)

- If `addEventType` specified a parent-modifier, then -- at play time, the parent's `proto` would be set to the modifier: `theEvent.parent.proto = protoEventTypes[theEvent[\type]]`. I think it might also be necessary to clear it -- `theEvent.parent.proto = nil` when all of the `play` activities have finished.

*But* it's a bit risky to change the parent event object itself, and I'm not sure the damage can be completely contained. I can't think it fully through right now, but this alternate idea smells funny to me. It's worth talking about all the options, if only to reject bad ones for the right reasons.

**Comment by telephon** [comment]
Thank you for this careful discussion, yes it is a little intricate. I think the original intention of having both `parent` and `proto` in dictionaries was that you can build systems with multiple inheritance. 

event-play-parent-order

The Numbers are the order in which events will override their values (highest is last, that is any given value in it will override any previous ones).

**Comment by telephon** [comment]
Now here I made a couple of diagrams with different versions of what could happen at the moment of play.

My original thought was to provide the default event as a parent to the parent-modifier:

event-play-parent-a

But then I worried that this will lose any passed in parent, such as that which you provide when you write:

`Pevent(pattern, (x: 9))`

So then I had the idea to override the proto instead:

event-play-parent-d

As you pointed out, James, we lose the benefit of keeping the proto free for  extra data passed in.

So you proposed something like this: if a proto already exists, keep its values. This can be done either by putting them all into the (copied) parent-modifier, or by overriding the proto's proto:

event-play-parent-e

(if no proto exists, just set it to the parent-modifier)

If we want to keep the proto-rail untouched, there are two more ways to deal with it on the level of the parent:

Insert the parent-modifier into the existing parent chain:
event-play-parent-b

Or temporarily use the parent's proto:
event-play-parent-c

**Comment by telephon** [comment]
A method like this might be helpful:

```
setProtoProto { |event|
    if(proto.isNil) {
        proto = event
    } {
        proto.setProtoProto(event)
    }
}
```

**Comment by telephon** [comment]
## Generally

The reason why I proposed this was that play function and values belong together. Instead of only setting a play function via `type`, associated values  should exist on the same level.

_[if we wanted to make a larger refactoring, we could associate every play function type with its own event. But I didn't want to go as far.]_

So the values should come in the order just before the finally overriding values of the event itself. This may mean either after the original `parent`, or even after the original `proto`.

Partly in mutual trade-off:
- easy to explain is good
- not blocking possibilities is good
- not copying events is efficient
- not modifying much state is good

**Comment by telephon** [comment]
currently I favor `3.`, because  it has 

- the smallest impact surface (proto can still be used, but if not, the modifications are minimal)
- relatively simple implementation (only one clear method above)

**Comment by telephon** [comment]
@jamshark70 what do you think about this? 

as far as I am concerned, I have one open question: if there is a proto event that is passed in, and that proto's proto is set in the `play` function, do we need to take care to remove it again afterwards? Or should we copy the proto event before modifying its proto?

It is common that the play function changes the event it plays. But I suppose it shouldn't affect anything on a higher level.

**Comment by jamshark70** [comment]
I think #3 is fine.

> as far as I am concerned, I have one open question: if there is a proto event that is passed in, and that proto's proto is set in the play function, do we need to take care to remove it again afterwards? Or should we copy the proto event before modifying its proto?

I think we can handle that in documentation: The event passed into Pattern:play should have the expectation that its proto's direct values will be untouched, but no guarantee about the inevent's proto's proto.

And we really need some new words for this. It's turning into Gertrude Stein here.

**Comment by telephon** [comment]
>And we really need some new words for this. It's turning into Gertrude Stein here.

This is why in mathematics we use things like `∀` and `א`! You are right.

given that we stick to `proto` and `parent`, we could call the above method `insertProto`?

**Comment by telephon** [comment]
@jamshark70 

>I think we can handle that in documentation: The event passed into Pattern:play should have the expectation that its proto's direct values will be untouched, but no guarantee about the inevent's proto's proto.

But that would mean that the proto event's parent becomes unreliable: the proto's proto is changed, and suddenly has old values that override the proto's parent.

Shouldn't we better copy the proto before setting its proto?

**Comment by jamshark70** [comment]
My gut feeling is: It will tie us in knots to try to cover every possible permutation. IMO if you're using values in:

- the event's main collection;
- the event proto's main collection;
- the event proto's proto's main collection;
- the event proto's parent's main collection;
- the event parent, and so on...

... then your data flow is too complicated to begin with and you're just asking for trouble.

That's just a gut feeling. I could be persuaded otherwise.

**Comment by telephon** [comment]
Believe me, I'd really like to agree, but look for yourself:

```
(
Event.addEventType(\test,
	{ "this is the current note: %".format(~note).postln }, 
	(note: 12)
)
)

p = (some: 8, special: 7, values: 9); // the proto
z = ().proto_(p); // use the proto event as the user defined extra data passed into the stream

// first, use without type
a = Pbind(\degree, 0).asStream;
e = a.next(z);
e.play;
e.use { ~note.value } // 0, correct

// then with event type "test"
a = Pbind(\type, \test, \x, 0).asStream;
e = a.next(z);
e.play;
e.use { ~note.value } // 12, correct



// now come back to the first example

a = Pbind(\degree, 0).asStream;
e = a.next(z);
e.play;
e[\note] // now it is 12, but I've set degree to 0!

// why?
e.proto.proto // ( 'note': 12 )
```

**Comment by telephon** [comment]
This can be avoided if we do this (method name could be changed):

```supercollider
setProtoProto { arg dict;
		if(proto.isNil) {
			proto = dict
		} {
			proto = proto.copy;
			proto.proto = dict;
		}
	}
```

**Comment by jamshark70** [comment]
`EventStreamPlayer` copies the inevent before passing it down, so the problem example is incorrect usage. If you're passing an event into `next`, it's the user's responsibility to do `next(z.copy)`. Unreliable behavior otherwise. We aren't responsible to make incorrect usage behave correctly.

**Comment by telephon** [comment]
Fair enough! But my example also "works" when you copy your event.

For convenience:

```
(
Event.addEventType(\test,
	{ "this is the current note: %".format(~note).postln }, 
	(note: 12)
)
)

p = (some: 8, special: 7, values: 9); // the proto
z = ().proto_(p); // use the proto event as the user defined extra data passed into the stream

// first, use without type
a = Pbind(\degree, 0).asStream;
e = a.next(z.copy);
e.play;
e.use { ~note.value } // 0, correct

// then with event type "test"
a = Pbind(\type, \test, \x, 0).asStream;
e = a.next(z.copy);
e.play;
e.use { ~note.value } // 12, correct



// now come back to the first example

a = Pbind(\degree, 0).asStream;
e = a.next(z.copy);
e.play;
e.use { ~note.value }  // now it is 12, but I've set degree to 0!

// why?
e.proto.proto // ( 'note': 12 )
```

The reason is that 

```
p = (some: 8, special: 7, values: 9); // the proto
z = ().proto_(p); 
z.copy.proto == p; // true
```

**Comment by telephon** [comment]
Btw. `Pevent` doesn't copy the event.

**Comment by jamshark70** [comment]
> // why?
> e.proto.proto // ( 'note': 12 )

Because, here:

```
// then with event type "test"
a = Pbind(\type, \test, \x, 0).asStream;
e = a.next(z);
e.play;
e.use { ~note.value } // 12, correct
```

`z` (the original, not a copy) has been modified during `play`, setting its `note` to 12 *at the top level*. Then, you are passing this modified event into the last type-less example... but the input event already overrides `note` at the top level, so `degree` in the Pbind becomes irrelevant.

If a user has advanced to the level of obtaining events directly from a Pbind stream, she should have seen this in doc examples that illustrate copying the event for `next`. Perhaps this should go into the doc as a counterexample, of why you must copy the event if you're doing this by hand.

**Comment by telephon** [comment]
I'm sorry, James, to be so utterly stubborn. Maybe I overlook something. 

Btw. my question `// why ?` was rhethorical: in the sense, this is what a user will ask. My example is carefully contrived to model this surprise case.

But: (unfortunately!) it doesn't matter whether you copy or not! You'd need to `deepCopy`.
This is why I want to copy the proto if it is modified. 

To repeat my above example:

```
// then with event type "test"
a = Pbind(\type, \test, \x, 0).asStream;
e = a.next(z.copy); // <---------------------------- copy!
e.play;
e.use { ~note.value } // 12, correct
```

and later:

```
a = Pbind(\degree, 0).asStream;
e = a.next(z.copy);
e.play;
e.use { ~note.value }  // still wrong.
```

**Comment by jamshark70** [comment]
Oh, ok, I see it now. Crossing messages.

Well, I don't know. Maybe this is all a bad idea. It would be a nice convenience, but often, when a data flow becomes too complex, it also becomes uncontrollable.

I have to get ready for day 2 of juries now so I can't propose a solution. But, if there are problems (of data correctness or of efficiency) with literally every possible place to put the new proto data, then it would suggest a redesign. Again, it's just a gut feeling, but I can't visualize the data structure in my head... so non-dev users won't be able to, either. I think it's too complex.

**Comment by telephon** [comment]
What's wrong with copying the proto in 

```
setProtoProto { arg dict;
		if(proto.isNil) {
			proto = dict
		} {
			proto = proto.copy;
			proto.proto = dict;
		}
	}
```
?
That would be safe, at least..

**Comment by jamshark70** [comment]
Part of my perspective here is that I've had `ProtoEvent` in my chucklib quark for 12 years now, for exactly this case. It stores the prototype event itself. Based on that, right now, with no change to the class library, I could do

```
Library.put(\eventTypes, \test, (parent: Event.default.putAll(( ... some data and funcs ...))));

p = Pbind(... something ...).play(protoEvent: Library.at(\eventTypes, \test));
```

... and the only thing I lose is the ability to choose the event type based on an event key (but that wouldn't be hard to solve).

This way, the definition is simple and unambiguous:

- An event's parent is reserved for the event definition, and all of the event definition belongs to the parent.

- An event's proto is reserved for user overrides that are shared across multiple events, and desired not to be copied (for efficiency).

It's easier to understand, easier to explain and harder to break.

I can understand the appeal of storing the minimum data structure and composing the final event at runtime, but if it isn't working cleanly without making copies that the user didn't ask for, it may simply be an attractive but flawed approach. Here, I lean toward the computer science maxim, to use the simplest solution that achieves the goal. Jiggering around with the user's proto may very well not be that simplest solution.

**Comment by jamshark70** [comment]
And I apologize, myself, for a degree of stubbornness. I'm open to being persuaded that it really is better to store a few defaults for event types, but from where I sit now, it looks like the implementation problems are pointing to a design problem. Maybe once exams are over, I could come up with an alternative.

Like, what if we put all the default values and functions that are currently shared between event types into one parent event, and then eventTypes looks like:

```
(
    note: (
        play: { ... },
        parent: theMasterParentDefaults,
    ),
    set: (... similar ...),
    ...
)
```

User event types with extra values would add them at the same level as `play` here.

The data structure is heavier but *all* of the problems of where to merge the extra values disappear, and each event level has a clear-cut role without blurring them.

**Comment by jamshark70** [comment]
Or, event types without extra data could just store a function in Event.default[\eventTypes] (current mechanism), and event types with extra data store a complete parent event in the other collection (which, as in my previous post, may refer to a collection of the shared defaults instead of replicating all of them -- so the memory impact would be minimal).

It's legit to replace the entire parent of the event-in-process with a complete, self-contained parent. It isn't legit to modify the parent, and I'm a bit nervous about swapping out the user's proto for a copy without any warning.

Offered in the interest of covering all bases.

**Comment by telephon** [comment]
>e the implementation problems are pointing to a design problem

yes, it is a design problem of the event system that I am trying to solve.

take your time, no hurry, happy exams! The whole thing is a specification problem more than anything else, I can implement the solutions myself - so I mainly need discussion.

>The data structure is heavier but all of the problems of where to merge the extra values disappear, and each event level has a clear-cut role without blurring them.

1. My original intuition also had been that we perhaps should always store with each event type the parameters that belong to it. I just hesitated, because it is a larger refactoring, and may break (advanced) code. But maybe this is the way to go. However, you still you lose the ability to pass parents into the chain via Pevent or EventStreamPlayer. But maybe this was just my assumption and should be discouraged? Should we always pass these in via proto?

>Or, event types without extra data could just store a function in Event.default[\eventTypes] (current mechanism), and event types with extra data store a complete parent event in the other collection

2. Yes, this is what this PR suggested in the beginning (diagram 1 above). My worry was that it makes it impossible to pass in your own parent.

3. `ProtoEvent` is great, and we probably should move it to common some time. It is completely orthogonal to the problem I am trying to solve, because I want to associate default values with functions directly. The lack of this possibility has made the event types tedious to design in many cases.

For completeness:

4. Maybe we could have an event that behaves like a function. Then all the functionality would be encapsulated there, and we don't have to touch the event as such.

5. A less efficient alternative would be to insert all non-existing values from the type-proto into the event directly when play is called.

**Comment by jamshark70** [comment]
> However, you still you lose the ability to pass parents into the chain via Pevent or EventStreamPlayer. But maybe this was just my assumption and should be discouraged? Should we always pass these in via proto?

And

> > Or, event types without extra data could just store a function in Event.default[\eventTypes] (current mechanism), and event types with extra data store a complete parent event in the other collection
> Yes, this is what this PR suggested in the beginning (diagram 1 above). My worry was that it makes it impossible to pass in your own parent.

Perhaps I'm a bit confused. If one defines an event type, with special defaults, within the default event prototype... why would one pass in a parent? What does it mean to write `Pbind(\type, \set, ...).play(protoEvent: (parent: someOtherEvent))`?

It's either:

- The defaults defined by addEventType should apply to any parent the user chooses at play time or on a per-event basis, even if the behavior in those alternate parents is incompatible.

- Or, the default event prototype + event type function + event type data constitute a predefined behavior that should act as an indivisible unit.

There's certainly a difference of opinion here, in which I favor a more strict view. In many cases, I argue for flexibility, but here, the number of places in which to stick data is high enough that I tend to feel it's chaotic to allow everything, and preferable to have a clear definition of what an event type is, and if users sneak around behind its back... you're on your own, at your own risk.

I do see that there could be value in supporting the user to design her own concept of event types.

**Comment by telephon** [comment]
I am also on the strict side here, but I want to combine the effect of the `type` and the event passed in. Thereby I want to avoid breaking standard behavior, obviously.

>Perhaps I'm a bit confused. If one defines an event type, with special defaults, within the default event prototype... why would one pass in a parent? What does it mean to write `Pbind(\type, \set, ...).play(protoEvent: (parent: someOtherEvent))`?

Simply do this:

`Pbind(\type, \set, ...).play(protoEvent: Event.default)`

or

`Pbind(\type, \set, ...).asStream.next(Event.default)`

and  you will have the situation I am worried about (and I discovered it only writing the code).

This is because:

```
Event {
*default {
		^Event.new(8, nil, defaultParentEvent, true);
	}
}
```

**Comment by jamshark70** [comment]
I guess what I was not understanding is:

- If you pass in an event with the default parent, and you replace that with a default_parent+extra_defaults, then... nothing bad has happened. (Note "replace," not "modify.")

- If you pass in an event with a non-default parent, then... the default event prototype handles the selection of the event type, so there are two cases:
  - Your custom event prototype bypasses the event type mechanism, in which case all of this is moot.
  - Or, your custom event prototype replicates the event type mechanism, in which case, replacing the parent would remove the custom logic... But if you're replicating the event type mechanism, it would be simpler to add an event type and use the default parent. So it's a mildly dubious use case anyway.

I have a feeling that the basic point has been lost in a thicket here, and we may be trying to cover "what-ifs" which, on closer inspection, don't make sense.

So what is the specific case you have in mind where a user passes in a parent, and *replacing* the parent causes user data to be lost? The example in your last message is not such a case.

**Comment by telephon** [comment]
I suppose I had always assumed that if you wanted to modify standard behavior, you'd copy the default parent event and modify it, passing it in as a parent to the stream input. I never even thought of touching the proto field. I see that I have in mind is indeed a bit of a wrong behavior.

I ran into the ramifications when I implemented the system first, replacing the parent, and it wouldn't work, because the new parent didn't have the default parent event as parent. So then I checked if the parent of the type-event is nil and if yes, set the default parent event for each separately.

So yes, as it seems, variant (1) is the one we are converging to.

**Comment by telephon** [comment]
This is how it looks:

https://github.com/supercollider/supercollider/pull/2227/commits/fb5f191636331c905eb470cfc73585e5f2142eda

**Comment by jamshark70** [comment]
https://github.com/supercollider/supercollider/commit/fb5f191636331c905eb470cfc73585e5f2142eda seems to work as I would expect:

```
(
Event.addEventType(\test, {
	~midinote.value.debug("note");
});

Event.addEventType(\test2, {
	~midinote.value.debug("note");
}, (octave: 6));
)

e = Event.default;
f = Pbind(\type, Pseq([\test, \test2], 1)).asStream.nextN(2, e);
f.do(_.play);
note: 60
note: 72

e.parent[\octave]  // still 5

// modifying defaults by putting them into the prototype event's top level
// works as expected: top level overrides parent
e = Event.default.put(\octave, 7);  // neither parent nor proto
f = Pbind(\type, Pseq([\test, \test2], 1)).asStream.nextN(2, e);
f.do(_.play);
note: 84
note: 84

// modifying defaults by putting them into 'proto'
// works as expected: proto overrides parent
e = Event.default.proto_((octave: 7));
f = Pbind(\type, Pseq([\test, \test2], 1)).asStream.nextN(2, e);
f.do(_.play);
note: 84
note: 84

// modifying defaults by passing in a modified parent
// is uglier than it seems at first
e = Event.default;
e.parent = e.parent.copy.put(\octave, 7);
f = Pbind(\type, Pseq([\test, \test2], 1)).asStream.nextN(2, e);
f.do(_.play);
note: 84
note: 72
```

In the last case, indeed, the `protoEventTypes` entry for `\test2` wipes out the event prototype's parent. But, as you had found, it's harder to override defaults by "passing in a parent" than it seems at first. You *have* to do it as above. If you take a shortcut -- `e = Event(parent: (octave: 7));` -- then the parent added here prevents the entire `defaultParentEvent` from being used, and then `f.do(_.play);` prints nothing (which I think we should not try to work around). So the problem scenario (values from `protoEventTypes` override something passed in) is a bit difficult to run into -- unlikely for users to do by mistake. Probably we should keep it unlikely, instead of facilitating it.

But `e = Event(proto: (octave: 7));` does exactly what you would expect.

So, for documentation, then we have:

- Overrides of default values that are specified in `addEventType` belong to the event's parent, because these are part of the definition of the event type.

- Ad-hoc overrides (in the event given to Pattern:play, or chained into a pattern) should go into `proto`.

Again, I apologize if I seemed stubborn myself, or if I wasn't expressing my concern clearly. I had a feeling that something didn't quite make sense... took a while to put my/our fingers on it.

**Comment by jamshark70** [comment]
Huh... somehow I wasn't on fb5f191 when I did those tests... but I retested on that commit and the behavior is the same. But the implementation is simpler (which is good in itself).

**Comment by telephon** [comment]
Please see #3021 for a revised PR.

**Pull request closed without merging**
