### PR TITLE
scdoc/sclang lexers: use intptr_t tof compatibility with LLP64 archtectures

### PR DESCRIPTION
**Pull request by timblechmann**
this is the good part of the windows patch. extracting took about 15 minutes

--->8---

based on a patch by Lucas Cornelisse

Signed-off-by: Tim Blechmann <tim@klingt.org>

### CODE REVIEW

**Comment by timblechmann** [comment]
btw, i'd strongly suggest to merge this (win32 compatibility)

**Comment by timblechmann** [comment]
could someone merge this? 64bit windows compatibility

**Comment by muellmusik** [comment]
This looks reasonable AFAICS, so I will merge if nobody objects, but I haven't been able to test it as I have no Windows machine.

**Comment by crucialfelix** [comment]
I eyeballed it. Looks good. Thanks a lot for separating that out Tim

**Comment by timblechmann** [comment]
could someone merge this, please?

**Pull request merged**
