### PR TITLE
use getpwduid on unix to find user home directory

### PR DESCRIPTION
**Pull request by bgola**
Purpose and Motivation
----------------------

Currently on unix systems SC uses the HOME environment variable to find the user home directory. On systems using `systemd` for example if the user specifies a service to run `sclang` without declaring the User= configuration explicitly, the HOME variable is not set, thus failing to run sclang (see #4132).

The patch also adds a path validation before trying to create the directories to avoid sclang from crashing.

Types of changes
----------------

- Bug fix (non-breaking change which fixes an issue)

Checklist
---------

- [X] All previous tests are passing
- [X] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
I am not sure I understand this change. It sounds like user error not to specify that like in the configuration file. Also, the man page for getpwduid says this:

> An application that wants to determine its user's home directory should inspect the value of HOME (rather than the value getpwuid(getuid())->pw_dir) since this allows the user to modify their notion of "the home directory" during a login session.

**Comment by brianlheim** [comment]
@bgola

> but should sclang break if there is no HOME environment variable set?

According to this, it is a POSIX requirement for it to be set: https://unix.stackexchange.com/a/123859

So if it isn't set, my opinion (and POSIX standard's opinion) is that it's not our problem.

However I still don't understand what was going wrong in the first place. Is this a bug in systemd? Is failing to provide an appropriate config setting an error according to their documentation/usage guide? If so, I don't see a need for this PR. However, if it's a common problem or isn't otherwise protected against, we could use getpwduid as a fallback.

**Comment by bgola** [comment]
According to systemd docs:
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Environment%20variables%20in%20spawned%20processes

> $USER, $LOGNAME, $HOME, $SHELL
> User name (twice), home directory, and the login shell. The variables are set for the units that have User= set, which includes user systemd instances. See passwd(5).

It is the expected behavior of systemd when you don't set the User= configuration.

I think using getpwuid as a fallback is a good idea in that case.

**Comment by brianlheim** [comment]
I agree, based on conversation here and at the dev meeting I am closing this and #4132 as user error

**Pull request closed without merging**
