### PR TITLE
Topic/ogl filled scope

### PR DESCRIPTION
**Pull request by scztt**
This changes the QcScopeShm class to be backed by an OpenGL widget, which improves drawing frame rates somewhat. It adds an additional property (fill) to fill the area below the graph. I've defaulted fill to true because I think it looks much better.

### CODE REVIEW

**Comment by jleben** [comment]
This should be tested on all operating systems to confirm that it doesn't degrade performance or quality of drawing for anyone.

**Comment by muellmusik** [comment]
@jleben, would you mind testing this on Linux? Last time I asked for some cross-platform testers, there was a deafening silence. :-)

**Comment by timblechmann** [comment]
this should especially be tested on windows with intel hd graphics 2000/3000 chips, which have pretty buggy opengl drivers

**Comment by miczac** [comment]
scztt: this is how the active fill property looks on 10.8.5:
funnyscope
While having the fill option is nice, in general, I'm not sure about defaulting to fill=true since this changes the look of existing code, like Freqscope. (see PR #1419 )

**Pull request closed without merging**
