### PR TITLE
example & help files: cleanup and streamlining of server handling

### PR DESCRIPTION
**Pull request by miczac**
now consistant to s.boot and s.waitForBoot, adapted help text if applicable.
removed .internal for Stethosope, it's not dependent on the internal server anymore.
checked against dowhenbooted, waitforboot, server.internal, server.default and boot.
omitted help files of Debugging-tips, ClientVsServer, asTarget, standalones, Server.

### CODE REVIEW

**Comment by crucialfelix** [comment]
ah, actually I think its better to leave these as explicit. I thought we were talking about entirely removing `s.boot` or `Server.default.boot` from help files.  why repeat this over and over again ? There is a button to boot the server.

but to rely on knowing that s is usually / by default set to Server.default is more mysterious.  

principal of least surprise:  "oh duh, I forgot to turn it on"  vs "what the hell is this s thing ? why do these people hide things from me ?"

**Comment by telephon** [comment]
if we have ```s``` to have a special meaning in interpreter code (and I take that as given), we should also use it in the examples.

"oh dude, look my nice patch: s = Synth(\default, [\freq, 8000]);"

That would be unfortunate ...

**Comment by miczac** [comment]
ok, you lost me here: leave what as explizit? There's a variety of changes in this 49 files.
should we remove s.boot at all? Or what would I change back?

**Comment by miczac** [comment]
@telephon , I took the special meaning as given, also as in "s is set  once and for good" (in Main.sc).
As @crucialfelix pointed out in the other thread, either users know what they are doing or use the button.
For a starter I'd recommend to leave s untouched for the time being, if she/he is more advanced side-effects of changing s etc should be clear.
The handling of Server.default etc changes throughout the help pages and I don't experience it as consistent - which IMHO should be the case in a help system.

**Comment by telephon** [comment]
I completely agree.

>ok, you lost me here: leave what as explizit? 
>There's a variety of changes in this 49 files.

yes, please change them as you proposed! It was just ```s.boot``` that you could leave in.

>should we remove s.boot at all? 

maybe not (at least this is what I tend toward)

>Or what would I change back? 

Nothing, I think.

**Comment by telephon** [comment]
>For a starter I'd recommend to leave s untouched for the time being, if she/he is more advanced side-effects of changing s etc should be clear.

yes!

**Comment by miczac** [comment]
revised HelpSource/Tutorials/Tutorial.schelp

**Comment by crucialfelix** [comment]
ok, consistency is best. `s` is well established I think. 

the changes here are fine with me.  I just made one note about not using a  ~var

**Comment by miczac** [comment]
great, thanks! I'll change that and push again.

**Comment by miczac** [comment]
ok, basically done, but I discovered I stated wrongly when saying at
s = Server.local;	// this is done by default at startup of SuperCollider  <----
I just cross-checked and in truth in Main.sc its 
// set the 's' interpreter variable to the default server.
                interpreter.s = Server.default;
So the above comment is not true ...

**Comment by miczac** [comment]
OT side-note: git-gui (homebrew) crashes when entering a ~ in the commit message field. "Copypasta" works though ;)

**Comment by miczac** [comment]
changed comment on s at startup and pushed again.

**Comment by miczac** [comment]
ok, pushed again ... ;)

**Comment by telephon** [comment]
thanks again, very welcome.

**Comment by miczac** [comment]
np!

**Pull request merged**
