### PR TITLE
sclang: remove dead code

### PR DESCRIPTION
**Pull request by brianlheim**
## Purpose and Motivation

remove a lot of unnecessary function declarations in primitives, perhaps due to requirements of early C++ compilers

also add blank lines to make file header comments stand out a bit

also remove dead code turned on with _SC_PLUGINS_ macro (unused).

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by patrickdupuis** [comment]
Out of curiosity, is there a reason this it aimed at `3.11`?

**Comment by brianlheim** [comment]
> Out of curiosity, is there a reason this it aimed at 3.11?

mainly because it's harmless, and also because i find it easier when 3.11 and develop diverge less.

**Comment by dyfer** [comment]
This looks fine to me, i.e. SC still compiles and works :)

I'm wondering whether putting this into develop won't make it less likely to have marge conflicts when we merge 3.11 into develop later. Or maybe it's just safest to wait with this PR until 3.11.1 is released and we merge 3.11 into develop - then we'll know we are not tempting any conflicts...

**Comment by brianlheim** [comment]
there will be fewer conflicts in the future if this change is in both branches. as for existing conflicts merging this into 3.11 and then into develop, you can test that yourself locally. there is one conflict in array primitives because of the levenstein distance primitive. it's easy to manage, and i'm happy to do it as soon as this is merged.

also, i'm not sure but it sounds like there is an assumption in your comment that we only merge 3.11 to develop after or during a release. that's not the case; those merges can happen at any time.

**Comment by brianlheim** [comment]
btw, the way i tested locally:

```
git checkout 3.11
git pull
git checkout develop
git pull
git checkout 3.11
git merge topic/dead-code
git checkout develop
git merge 3.11
git mergetool # examine merge conflicts

# undoing:
git merge --abort
git checkout 3.11
git reset --hard upstream/3.11
```

**Comment by dyfer** [comment]
> (...) it's easy to manage, and i'm happy to do it as soon as this is merged.

thanks!

> also, i'm not sure but it sounds like there is an assumption in your comment that we only merge 3.11 to develop after or during a release. that's not the case; those merges can happen at any time.

Good point. I know we can merge anytime, but sometimes we don't for a while :) 

@brianlheim after your last comment I agree that getting this in both branches soon would be best.

**Comment by brianlheim** [comment]
thanks!

**Pull request merged**
