### PR TITLE
Classlib: Fix UGen optimization of (a+b) + (a+b)

### LINKED ISSUE #5047: UGen math structure (a+b) + (a+b) is inappropriately deleted by the optimizer
## Environment

* SuperCollider version: 3.11
* Operating system: Irrelevant
* Other details (Qt version, audio driver, etc.): Irrelevant

## Steps to reproduce

```supercollider
SynthDef(\test1, {
    var sig = SinOsc.kr(0.1) + Rand(-0.02, 0.02);
    Out.kr(0, sig);
}).dumpUGens;

test1
[ 0_SinOsc, control, [ 0.1, 0.0 ] ]
[ 1_Rand, scalar, [ -0.02, 0.02 ] ]
[ 2_+, control, [ 0_SinOsc, 1_Rand ] ]
[ 3_Out, control, [ 0, 2_+ ] ]

SynthDef(\test2, {
    var sig = SinOsc.kr(0.1) + Rand(-0.02, 0.02);
    Out.kr(0, sig + sig);
}).dumpUGens;

test2
[ 0_SinOsc, control, [ 0.1, 0.0 ] ]
[ 1_Rand, scalar, [ -0.02, 0.02 ] ]
```

(Note: The UGen rates don't matter here -- Rand is `ir` but I tested `kr` as well, same problem.)

## Expected vs. actual behavior

The structure of `\test2` should be:

1. SinOsc
2. Rand
3. '+' (ugen1, ugen2)
4. '+' (ugen3, ugen3)
5. Out (ugen4)

But the binary math operator optimization is getting confused and deleting both operations and their descendent(s).

I haven't done any analysis beyond this.

Once the reason is found, the solution should be apparent -- but this is a complex part of the code, so the analysis is likely to take a while.

### PR DESCRIPTION
**Pull request by jamshark70**
## Purpose and Motivation

Fixes #5047.

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- ~~[ ] Updated documentation~~
- [x] This PR is ready for review

### CODE REVIEW

**Comment by jamshark70** [comment]
I just spotted a potential mistake: I think I should set `descendants_` on the Sum4 (like the Sum3)... so please don't merge yet. I'll fix it next time I'm on the computer.

**Comment by jamshark70** [comment]
OK, done.

**Comment by jamshark70** [comment]
While at it, I thought, why not test all the optimize methods?

That revealed one case to fix later: `a + b + (c + d)` could be a Sum4 but the algorithm isn't smart enough to find that yet. I'll say, out of scope for this PR, but worth noting for a future fix. The test is there, just commented out for now.

**Comment by joshpar** [comment]
Thanks @jamshark70. What kind of breaking changes should users be aware of for when this is applied?

**Comment by jamshark70** [comment]
>What kind of breaking changes should users be aware of for when this is applied?

None.

There's no change to any case that is currently functioning correctly.

In the case that it fixes, whole chains of UGens were being deleted. Nobody will be relying on that behavior :laughing:

**Comment by totalgee** [comment]
Just for those who don't know -- this fixes a bug with the `PulseDPW` UGen, currently in the system, which (in certain cases, e.g. when its `width` argument was calculated with an addition) would output...nothing. Not "no sound", but "no UGens"!

**Comment by jamshark70** [comment]
> this fixes a bug with the PulseDPW UGen

Right -- this pseudo-UGen does a clever optimization by writing `width + width` instead of `width * 2` (on the assumption that addition is faster than multiplication). If width is itself an addition operation, then you have:

```
+(id A)     +(id A)    (identical)
    \   /
      +(id B)
```

For the B `+`, `optimizeToSum3` wants to replace the pattern `(a + b) + c` with a Sum3, but this is valid only if the `(a + b)` isn't used anywhere else... but it *is* used as the other operand of the B `+`. But we fail to recognize this case because of a quirk in the way descendants are registered.

By definition, this fix can *only* affect the case of a `+` with the same `+` BinaryOpUGen in both arguments. It's a rare case but messing it up is catastrophic. (If you have two separate `a + b` UGens, there's no bug, and this fix doesn't affect that case.)

So it's a narrowly drawn fix that will not hurt cases outside the scope of this issue.

**Comment by brianlheim** [comment]
thanks!

**Pull request merged**
