### PR TITLE
docs: fix slider example indentation [skip ci]

### PR DESCRIPTION
**Pull request by elgiano**
## Purpose and Motivation

One example had excessive indentation, which prevented code-block execution from the Help Browser

## Types of changes

- Documentation

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by telephon** [comment]
what has changed?

**Comment by elgiano** [comment]
Just indentation, because with wrong indentation the code doesn't execute when pressing Ctrl+Enter on the Help Browser

**Review by telephon — APPROVED** [review]

**Comment by telephon** [comment]
> with wrong indentation the code doesn't execute when pressing Ctrl+Enter on the Help Browser

This seems to be a bug in the help browser which would be nice to get rid of.

**Comment by elgiano** [comment]
> This seems to be a bug in the help browser which would be nice to get rid of.
In principle I agree with you, but the current behavior is actually consistent with how the Document editor works. In this case the problem was that a code block is not recognized as a block because there is whitespace before the opening `(`. And this works the same in scide's Documents, opening parens for blocks need to be the first character on a line, otherwise the block is not recognized.

**Pull request merged**
