### PR TITLE
cmake: fix c++ sse flag 

### PR DESCRIPTION
**Pull request by smoge**

### CODE REVIEW

**Comment by vivid-synth** [comment]
Good eye, that seems to have been a bug in a0588e7265984701bcb6090f2e4a5d9fee2240f2 -- @timblechmann can you confirm?

**Comment by snappizz** [comment]
I wonder, could this explain a recently reported [denormal number issue on amd64](http://new-supercollider-mailing-lists-forums-use-these.2681727.n2.nabble.com/Clicks-with-pow-td7629111.html)?

[sc3-plugins seems to be safe](https://github.com/supercollider/sc3-plugins/blob/master/CMakeLists.txt#L59).

**Comment by smoge** [comment]
Maybe it's not the case anymore? I've built with `-O3 -ffast-math -msse2 -mfpmath=sse` without problems on macOS 10.12, including supernova

**Comment by brianlheim** [comment]
I'm merging this, it's gotta be a typo especially comparing to the sc3-plugins makelists

**Pull request merged**
