### PR TITLE
class library: scdoc catches missing argument in method specification

### LINKED ISSUE #3040: `indexAllDocuments` throws an error sometimes.
(updated)
`indexAllDocuments` throws an error on a syntax error of a help document.

Reproducer:
Put this into some schelp document:
```
copymethod::new
```

Then:

```supercollider
SCDoc.renderAll(true);
SCDoc.indexAllDocuments(true);
```

Error:

```
SCDoc: Indexing help-files...
ERROR: Message 'drop' not understood.
RECEIVER:
   nil
ARGS:
   Integer 1
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = nil
		arg selector = 'drop'
		arg args = [*1]
	SCDocEntry:prAddCopyMethod
		arg this = <instance of SCDocEntry>
		arg node = <instance of SCDocNode>
		arg list = <instance of IdentitySet>
	SCDocEntry:prScanMethodsKeywords
		arg this = <instance of SCDocEntry>
		arg node = <instance of SCDocNode>
	ArrayedCollection:do
		arg this = [*1]
		arg function = <instance of Function>
		var i = 0
	SCDocEntry:prScanMethodsKeywords
		arg this = <instance of SCDocEntry>
		arg node = <instance of SCDocNode>
	ArrayedCollection:do
		arg this = [*2]
		arg function = <instance of Function>
		var i = 1
	SCDocEntry:prScanMethodsKeywords
		arg this = <instance of SCDocEntry>
		arg node = <instance of SCDocNode>
	SCDocEntry:init
		arg this = <instance of SCDocEntry>
		arg node = <instance of SCDocNode>
		arg aPath = "Classes/PbindefCut"
		var hdr = <instance of SCDocNode>
		var bdy = <instance of SCDocNode>
	Meta_SCDoc:parseFileMetaData
		arg this = <instance of Meta_SCDoc>
		arg dir = "/Volumes/data/sc/supercollid..."
		arg path = "Classes/PbindefCut.schelp"
		var fullPath = "/Volumes/data/sc/supercollid..."
		var subpath = "Classes/PbindefCut"
		var entry = nil
		var x = <instance of SCDocNode>
	< FunctionDef in Method Meta_SCDoc:indexAllDocuments >
		arg f = <instance of PathName>
	ArrayedCollection:do
		arg this = [*879]
		arg function = <instance of Function>
		var i = 538
	PathName:filesDo
		arg this = <instance of PathName>
		arg func = <instance of Function>
...
^^ The preceding error dump is for ERROR: Message 'drop' not understood.
RECEIVER: nil


```

thereafter, also finding help with `cmd-D` fails, with the following error:

```
ERROR: Message 'isUndocumentedClass' not understood.
RECEIVER:
   nil
ARGS:
CALL STACK:
	DoesNotUnderstandError:reportError
		arg this = <instance of DoesNotUnderstandError>
	Nil:handleError
		arg this = nil
		arg error = <instance of DoesNotUnderstandError>
	Thread:handleError
		arg this = <instance of Thread>
		arg error = <instance of DoesNotUnderstandError>
	Object:throw
		arg this = <instance of DoesNotUnderstandError>
	Object:doesNotUnderstand
		arg this = nil
		arg selector = 'isUndocumentedClass'
		arg args = [*0]
	Meta_SCDoc:findHelpFile
		arg this = <instance of Meta_SCDoc>
		arg str = "SCDoc"
		var old = nil
		var sym = 'SCDoc'
		var pfx = "file:///Users/wanninger/Libr..."
	Meta_HelpBrowser:openHelpFor
		arg this = <instance of Meta_HelpBrowser>
		arg text = "SCDoc"
	Process:interpretCmdLine
		arg this = <instance of Main>
^^ The preceding error dump is for ERROR: Message 'isUndocumentedClass' not understood.
RECEIVER: nil

```

The method is:

```
prAddCopyMethod {|node, list|
		^list.add(node.text.split($ )[1].drop(1))
	}
```

So sometimes the list resulting from `node.text.split($ )` has no second element.

Instead of entries like `"Group *replace"` or `"Group *after"`, it has an entry: `"new"`

It is easy to fix, but it would be interesting if another error hides behind it.

### PR DESCRIPTION
**Pull request by telephon**
Fixes #3040.

### CODE REVIEW

**Comment by telephon** [comment]
Probably the scdoc parser should have discovered the problem in the first place.

It could be here (guessing): https://github.com/supercollider/supercollider/blob/master/SCDoc/SCDoc.tab.cpp#L2155

But I don't know anything about that part of the system.

**Comment by brianlheim** [comment]
I made a quick fix to the parser files that solves the problem:

```cpp
diff --git a/SCDoc/SCDoc.y b/SCDoc/SCDoc.y
index f06c17142..248376ef8 100644
--- a/SCDoc/SCDoc.y
+++ b/SCDoc/SCDoc.y
@@ -192,7 +192,13 @@ subsubsection: METHOD methnames optMETHODARGS eol methodbody
         doc_node_add_child($$, $5);
 //        doc_node_add_child($2, $3);
     }
-             | COPYMETHOD words eol { $$ = doc_node_make(
+             | COPYMETHOD words eol {
+                if ( !(strchr($2, ' ')) ) {
+                  yyerror("COPYMETHOD requires 2 arguments (class name and method name)");
+                  YYERROR;
+                }
+
+                $$ = doc_node_make(
                 stringEqual(method_type, "CMETHOD") ? "CCOPYMETHOD"
                                                     : (stringEqual(method_type, "IMETHOD") ? "ICOPYMETHOD"
                                                                                            : "COPYMETHOD"),
```

which gives errors like:
```
SCDoc: Indexing help-files...
ERROR: In /Users/brianheim/git/supercollider/build/Install/SuperCollider/SuperCollider.app/Contents/Resources/HelpSource/Classes/Array.schelp:
  At line 79: COPYMETHOD requires 2 arguments (class name and method name)

SCDoc: Indexed 1332 documents in 1.79 seconds
```

Note that this also requires running `./build_parser.sh` in the same directory. I can't find a quick and non-messy way to also print the culpable string. What do you think @telephon ?

**Comment by telephon** [comment]
Will the requirement of running `build_parser.sh` in the same directory pose a problem in some circumstances?

With regards to the lack of posting the string: the error handling in scdoc is generally a little stern - I often find it hard to know what the error is. But this is mostly some out-of-order delimiters, which are then really difficult to find. That would be a great opportunity for improvement.

But in this case the line number is just fine, because there is just one line.

**Comment by telephon** [comment]
Btw. we have a very similar coloring issue with posts. E.g. this is half green half black:

```
-> ( 'instrument': wvst0, 'num': 1, 'dur': 0.0017663990269195, 'start': 67, 
  'rate': 1, 'sustain': 0.0017663990269195, 'startFrame': 6166.9098837209, 'endFrame': 6244.8080808081, 'buf': 0, 
  'numFrames': 77.89819708715, 'sampleRate': 44100, 'rate2': 1 )
```

**Comment by telephon** [comment]
pretty printing would be *so* nice to have!

**Comment by brianlheim** [comment]
> Will the requirement of running build_parser.sh in the same directory pose a problem in some circumstances?

I don't understand. This is just to generate updated source files; the script needs to be run once and then built with the changes. I just made a note of that extra build step in case you or someone else wanted to try my patch.

**Comment by brianlheim** [comment]
Sorry, had to attend to something else before I could finish my post.

To recap, this is just a static fix. The patch I posted above adds a new error condition like the ones the sclang parser spits out (they are both written using Bison). I think it is a little better to catch this at parse time than at render time, although either is better than none at all. What do you think?

**Comment by telephon** [comment]
I think your parser fix is better than this one, also because it is, after all, something like a syntax error.

**Pull request closed without merging**
