### PR TITLE
classlib: kill both scsynth and supernova with Server -killAll

### LINKED ISSUE #3999: Server.killAll behavior when switching between scsynth and supernova
Environment
-----------

* Your SuperCollider version: 3.10-beta1
* Your operating system and version: macOS 10.13.06

Steps to reproduce (for bugs)
-----------------------------

```supercollider
//caution - this will force close the interpreter!
(
Server.scsynth;
s.addr.port = 57130; //set non-default port
s.waitForBoot({
	"killall sclang".unixCmd; //kill sclang (no cleanup - server will keep running)
})
)
//-----
//boot the interpreter manually, then:
//-----
//check if the old server is still running - it probably is
"ps ax | grep -E '[s]csynth|[s]upernova'".systemCmd; 

(
Server.supernova; //switch servers;
Server.killAll; //tries to kill supernova; scsynth keeps running;
s.boot; //boots fine, since the old server was using a non-default port
)

//check for scsynth and supernova - both are running
"ps ax | grep -E '[s]csynth|[s]upernova'".systemCmd; 

//you can manually kill scsynth... but should Server.killAll have done it?
"killall scsynth".systemCmd;
```

Error message (for bugs)
------------------------

(No error message)

Expected Behavior
-----------------
This is maybe a very edge case...
If one ends up with a dangling server, and then switches from ```scsynth``` to ```supernova``` (or vice versa), then ```Server.killAll``` option will not necessarily kill the old process. This happens only if the dangling process was booted with a non-default port number or if it's not responding to OSC messages anymore.

Current Behavior
----------------

```Server.killAll``` attempts to kill only the currently chosen server - either ```scsynth``` or ```supernova```. However it also sends ```\quit``` OSC message, so any dangling but responsive server _should_ still quit.

I'm considering whether ```Server.killAll``` should kill both ```supernova``` and ```scsynth``` instances. What do you think?

### PR DESCRIPTION
**Pull request by dyfer**
## Purpose and Motivation

This PR makes `Server -killAll` command kill both `scsynth` and `supernova`.
Fixes #3999

## Types of changes

- Bug fix

## Notes

I think that handling `scsynth` vs `supernova` throughout the `Server.sc` should be revisited, possibly defining executable strings in one place only. I had some [initial thoughts](https://github.com/supercollider/supercollider/issues/3999#issuecomment-414836118) on this, but it would be for a separate PR anyway.

## To-do list

- [x] Code is tested
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by jrsurge** [comment]
This might be slightly dangerous - I think there are several other programs called `supernova` out there based on a quick search

I think we should really be keeping track of PIDs in a lock file and killing them directly, but that's a slightly different PR?

**Comment by dyfer** [comment]
Yeah, that's a tricky problem.
I'd say there are two scenarios where one might need to kill the server: 
- when the server hangs, but sclang runs _and was not restarted/recompiled_ - in that case keeping track of PIDs would work
- when the server hangs and sclang either crashes or user recompiles, or if the server was hanging before SC was started - then we have no idea about the PIDs

I'd lean towards keeping this as `killAll` but maybe documenting that this is to be done as a last resort. I've certainly seen people using `Server.killAll` as a casual command before starting the server or recompiling library...

Maybe we could keep track of PIDs and kill those first? And if we have no PIDs then instigate actual `killAll`?

**Comment by jamshark70** [comment]
> when the server hangs and sclang either crashes or user recompiles, or if the server was hanging before SC was started - then we have no idea about the PIDs

It's possible, in principle, to have the server, early in its startup process, add its pid to a specific file on disk, and remove it at the end of shutdown. A crashed/hung server would leave the pid behind.

It's unlikely, but it may be possible for a server to crash, and if you don't killAll right away, maybe the OS would reuse the pid for a totally unrelated process, over which we have no control. That is, it isn't hard to imagine a pid list getting out of sync with reality. (Also, user processes don't survive a logout/login or reboot cycle -- so the file should be cleared in that case -- at which point it's looking like over-engineering.)

All of which is a long way around to say, maybe the solution is to give SC's supernova a distinct name, eg `scsupernova`.

**Comment by dyfer** [comment]
@jamshark70 I wonder if we should then make an Issue (or an RFC) proposing an executable name change for supernova? I understand the reasoning completely, but also this seem to me like a bit of a drastic change...

**Comment by brianlheim** [comment]
@jrsurge -- with a quick search i couldn't find any programs named supernova, do you happen to have a few examples?

my opinion is that this method is meant as a nuclear option, and the burden falls on users to use it prudently. perhaps adding a flag parameter that keeps the old behavior and defaulting it to false would be a good compromise, that way if it breaks anyone's workflow it is (hopefully) a one-time inconvenience. in any case i think we should try to keep the solution simple.

**Comment by jrsurge** [comment]
Apologies for not getting back to this faster.

I found three programs:
1) SuperNova (Dolphin Computer Access)
    * Screen reader & magnification, accessibility tool
2) SuperNova (EVGA)
    * PSU configuration tool
3) SuperNova (BANDAI NAMCO)
    * Game

Only 2 and 3 have the exact executable name from what I can tell.
I was mostly worried about 1, as it seems to be recommended by the RNIB in the UK, but after digging in the Dolphin support forums it looks like it uses a different executable name.

So, it looks like everything's fine for this PR, but I think it will need to be looked at again at some point

**Comment by dyfer** [comment]
I updated the documentation. How's the wording?

**Pull request merged**
