### PR TITLE
scdoc: make TOC popout-only

### LINKED ISSUE #3176: [Help] TOC dropdown awkward without fixed top bar
There are two issues related to the Help Browser's Table of Contents functionnality :

1. **with TOC open from the top bar**
Try opening the TOC of `ServerOptions` from the top bar. The bottom part of the TOC is obscured. There should be a way to scroll within the TOC. 

2.  **with TOC popped out**
It is possible to scroll within the TOC when popped out. However, the last line is always partially obscured.

### PR DESCRIPTION
**Pull request by snappizz**
fixes #3176. instead of going through the awkward and cramped dropdown, this PR makes the TOC always pop out to the left. also makes improvements to appearance, and some code cleanliness (although this part of SC is an absolute mess and there's only so much i can do).

### CODE REVIEW

**Comment by patrickdupuis** [comment]
Thanks for this @snappizz! I can now see the very last entry into the TOC when popped out 👍 

However, there are some issues still. The TOC isn't popping out as it should. It disappears when scrolling down the help file. It should always be visible to the left, otherwise it is not that useful.

sc_toc

**Comment by snappizz** [comment]
@patrickdupuis may have to do with my Monokai skin, could you try without?

**Comment by patrickdupuis** [comment]
@snapizz Oh! I totally forgot I themed my IDE :) Will try later.

**Comment by patrickdupuis** [comment]
@snappizz You were totally right about the theme. It was the cause of most of my TOC issues... should have though of that. This PR is looking much better now :D

The only thing that I can see that might be worth fixing is the TOC scrolling. Over here, after scrolling the TOC all the way down using the mouse wheel, the help file starts to scroll down as well. It would be nice if we could scroll the TOC to the bottom without affecting the rest of the page. Not a big issue, but it would make our lives a bit easier.

**Comment by snappizz** [comment]
ah you're right, i'm also getting double scrollbars (both horizontal and vertical) on the Server page.

**Comment by snappizz** [comment]
OK, TOC and contents should now scroll 100% indepenently.

**Comment by patrickdupuis** [comment]
Yes - that's fixed it. 

One more thing: Currently, the TOC opens when clicking on the word "TOC" in the top bar. I feel it would be better if the [ _classname_ - TOC ] area were to act as a button and open the TOC. What do you think?

**Pull request merged**
