### PR TITLE
class library: Volume free

### LINKED ISSUE #2551: class library: server quit calls volume.free but is not implemented.
No such method exists for `Volume`. But `isPlaying` is false anyway, because it isn't implemented either.

### PR DESCRIPTION
**Pull request by telephon**
This fixes #2551.

### CODE REVIEW

**Comment by brianlheim** [comment]
Should we also implement Volume.isPlaying to return the state of the `ampSynth`?

**Comment by patrickdupuis** [comment]
Built this and it works here. I remember 

`Node.isPlaying` can only return True if the node was registered with a `NodeWatcher`. Currently, the Server doesn't use `NodeWatcher.register` for anything. Would there be a benefit to registering the `ampSynth` when it is created? Do we really need to check that it is playing? Would `volume.notNil` be enough? 

Also, I noticed that the server creates a `Recorder` when it is initialized. It isn't freed explicitly, only with `RootNode(this).freeAll`. We should free it properly as well.

**Comment by telephon** [comment]
Yes, better to do this properly. Well, as far as it is now, you are not supposed to free your volume yourself, in a sense it is really just a function inside the server class. But the best thing would be to make it more general, like Recorder.

@patrickdupuis I don't see the problem with ´Recorder` - can you give me a hint? It is registered here:
https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Control/Recorder.sc#L136
and we rely on the synth also here:
https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Control/Recorder.sc#L56

**Comment by patrickdupuis** [comment]
Sorry, I wasn't being clear. I meant to say that in 
https://github.com/supercollider/supercollider/blob/master/SCClassLibrary/Common/Control/Server.sc#L871
there isn't a check to see if `recorder.isRecording` and then stopping and freeing it properly. Maybe there is something to be done here? It's a separate issue that  should not have mentioned here.

**Comment by telephon** [comment]
ah yes, I see. It doesn't make a difference for `Recorder`, because its synth is registered.

Try this:
```
{ Silent.ar }.play.register.onFree { "I was notified!".postln };
// and then:
s.quit;
```

if we register the Volume synth, then that would be the same, and we could just leave away 
```if(volume.isPlaying) { volume.free };```

**Comment by telephon** [comment]
… so it's either way!

**Comment by patrickdupuis** [comment]
Making `Volume` more general like `Recorder` could be a good thing, and that would be the time to implement `Volume.isPlaying`. For now, maybe it's enough just to make sure that the volume synth is freed on `Server.quit` ?

**Comment by telephon** [comment]
good to keep it simple. What I don't completely understand yet is: why do we have to free the synth explicitly when it is freed anyway by server.quit?

**Comment by patrickdupuis** [comment]
Sometimes, when I reboot the Server, I get this error:

*** ERROR: SynthDef volumeAmpControl2 not found

So, I think that the issue is not that the Synth isn't getting freed. It's that the newly booted Server is looking for a SynthDef that belonged to a past server.

**Comment by telephon** [comment]
interesting, I have never seen this. Yes, this is a bug.

**Comment by patrickdupuis** [comment]
The problem only appears when I set the Server's volume inside my Startup file.

`Server.default.volume = 0.125.ampdb;`

**Comment by telephon** [comment]
ah - good hint!

**Comment by telephon** [comment]
I'd like to fix this issue in a better redesign of Volume later.

**Pull request closed without merging**
