### PR TITLE
gc improvements

### PR DESCRIPTION
**Pull request by timblechmann**
* branch hints
* explicitly free frames (done for blocks, but not for methods)

### CODE REVIEW

**Comment by crucialfelix** [comment]
I wonder if we should merge some of these after 3.8

Just to be sure that dev people have lived with them for a few months.

**Comment by crucialfelix** [comment]
Ah but it's novacollider, so it is your call.

**Comment by timblechmann** [comment]
you're the release manager these days ... fwiw, having PRs open and unmerged for quite some time increases the chances for conflicts between different PRs. we had this before when one of my PRs for the IDE wasn't merged for half a year and eventually it ended up having a conflict, which i had to resolve manually ... 

if a 3.8 release is planned in the near future, maybe create a branch and merge post-3.8 changes to develop.

**Comment by bagong** [comment]
@timblechmann , if you want to speed up merges, help testing, tell people in human readable language what this is, and what to look out for, provide test examples, add a statement whether you yourself consider something risky for other than your favorite platform.
Merging to a "developer-branch" will not prevent stuff from staling, keeping it in a pull request will keep the responsibility where it belongs...

**Comment by crucialfelix** [comment]
Tim, I've been merging your requests quite quickly. In some cases on the very day you post them.

The ones that are not merged have conflicts and need to be fixed or are waiting for consensus. Everything is labelled and queued.

**Comment by crucialfelix** [comment]
> maybe create a branch and merge post-3.8 changes to develop.

We are releasing 3.7.2 and merging that to master. Then creating 3.8  

There is no develop branch. I have proposed it many times over the years. Master is develop.

**Comment by timblechmann** [comment]
@crucialfelix this is no 'supernova', but 'sclang'. 'novacollider' is my version of vanilla supercollider + about 70 patches. some of my patch series are specific to my setup, some are performance improvements, which i'm not planning to submit as they are quite intrusive, some are patches, which are waiting to be merged.

fwiw, #1715 wasn't pulled for half a year not because of a conflict with master, but because of a conflict with another PR which was considered not ready and was deferred for months. #1904 is open for over 2 months and not merged. #1760 is open, but travis is using an ancient compiler.

**Comment by timblechmann** [comment]
no need to contribute improvements upstream

**Comment by telephon** [comment]
I'd like to continue to reopen them, but I find it also not appropriate somehow. Could you please rethink a little what you are doing? Your contributions are highly valued.

**Pull request closed without merging**
