### PR TITLE
Update example in SendReply.schelp

### PR DESCRIPTION
**Pull request by brianlheim**
Add explanatory comments & fix logic. Addresses deficiencies in #2974.

@redFrik how does this look?

### CODE REVIEW

**Comment by redFrik** [comment]
better but still a pretty pointless and unneeded example i think.

```
SynthDef(\amplitudeAnalysis
```
it's now doing more than amplitude so can we call it `\audioAnalysis` instead?

and how about adding a comment about what's sent?
```
SendReply.kr(trig, '/analysis', [amp, freq[0], freq[1]]);  //amp, freq, hasFreq
```

and "SendReply can only respond to the host" is a strange sounding statement to me. probably i'm misreading but could users think SendReply can only send to sclang?

here's a good example demonstrating scsynth->processing without any added sclang oscdef detour like above.

**Comment by redFrik** [comment]
and one more thing: "insert your target host & port" -> "insert your target ip & port"?

**Comment by brianlheim** [comment]
> probably i'm misreading but could users think SendReply can only send to sclang?

That's what I thought tbh. Could you rework the example from the mailing list you posted into a PR? That would be better than what we're currently discussing.

**Comment by brianlheim** [comment]
fwiw, statements like

>better but still a pretty pointless and unneeded example i think.

could definitely be phrased into more constructive criticism, or at least put in a way that doesn't induce anxiety. today's been a rough day so please take that into consideration.

**Comment by redFrik** [comment]
ok, thanks for the note and sorry for that - i'll try to phrase my criticism better in the future. but i _do think this example is of very little use and i'd rather not see it being added.
the mailinglist example could be reworked but i don't like the idea of cluttering the SendReply helpfile with processing code. a mini scdoc tutorial or a file in the examples folder would be better.

**Comment by telephon** [comment]
I think it's not that pointless: it is a typical use case of `SendReply`, and you can use it as a template for things you typically do with it, can't you?

**Comment by jamshark70** [comment]
@telephon I think Fredrik is right about this:

> i don't like the idea of cluttering the SendReply helpfile with processing code. a mini scdoc tutorial or a file in the examples folder would be better.

We have a habit of thinking that documentation == Classes/ help files. That's a bad habit -- I've been saying so for years, but here again, "It's a common use case so let's stick it in the SendReply class doc." This old habit seems to have an almost subconscious influence.

It would be great, OTOH, to have a Tutorial or Guide with examples for Processing, Max, pd, ChucK and perhaps others (TouchOSC?). I've found, for instance, that syncing SC's state *bidirectionally* with external processes (TouchOSC in my specific case but the same would apply to others) is not obvious. That's a valid topic but not for class help.

**Pull request merged**
