### PR TITLE
Fix for Issue #2934

### PR DESCRIPTION
**Pull request by muellmusik**
This is an attempt to fix issue #2934. It may also solve issues #2933, #2797, #2823. Could the submitters of those four issues please test this?

### CODE REVIEW

**Comment by brianlheim** [comment]
I can confirm this gets rid of the assert failure, but I'm actually experiencing #2797 (new file doesn't focus) on both old 3.9 and this branch.

**Comment by muellmusik** [comment]
@brianlheim But you only guessed that #2797 was related, or? I cannot replicate #2797 btw.

**Comment by muellmusik** [comment]
@brianlheim and does it solve the other two issues for you?

**Comment by brianlheim** [comment]
@muellmusik it was a total guess :) I've closed #2933 since it seems to be a dupe of #2797. I've never been able to reproduce #2823. @ycollet, would you be able to take a look at this?

**Comment by muellmusik** [comment]
> it was a total guess :)

:-) Okay, I'm reasonably confident this branch is the correct fix for the issue you raised in any case, so unless anyone comes up with an objection we can probably merge.

**Comment by brianlheim** [comment]
OK! I'm convinced. Thanks again

**Pull request merged**
