### PR TITLE
remove redundant curly bracket

### PR DESCRIPTION
**Pull request by nuss**
small typo preventing the class lib from compiling

### CODE REVIEW

**Comment by vivid-synth** [comment]
How did this typo make it in without a PR?

**Comment by snappizz** [comment]
@vivid-synth [this commit](https://github.com/supercollider/supercollider/commit/cd3a2bf38413dd4addebb2dab8e750d974d7ff66) was pushed without a PR

**Comment by telephon** [comment]
This used to be common practice until some time ago, so nothing to worry too much about. Alberto just followed this practice, maybe because it is a little annoying to make a branch for every commit.

**Comment by jamshark70** [comment]
Right, but in general, I don't think it's too much to ask that devs at least compile the class library in between changing a class file and committing it.

That includes myself... I've got commits in my quarks that correct last minute typos, where I thought, "I'll just do blahbittyblah before checking in, should be fine" -- my point here is not to blame any individual, but just to remind that it happens to all of us -- the second we get complacent and think we don't have to test our changes (no matter how trivial) is the moment we get caught with our skirts (kilts?) around our knees. It's definitely happened to me more than once.

**Comment by gusano** [comment]
> it is a little annoying to make a branch for every commit

Yes but it's good practice in a community code base when we have access to tools like travis-ci which avoids accidental releases with typos and/or broken libraries :bug: https://github.com/supercollider/supercollider/issues/2388

**Comment by snappizz** [comment]
I suggest this setting to prevent intentional or accidental pushes to upstream:

    $ git remote -v
    origin  git@github.com:snappizz/supercollider.git (fetch)
    origin  git@github.com:snappizz/supercollider.git (push)
    upstream    https://github.com/supercollider/supercollider.git (fetch)
    upstream    nonexistent (push)

**Pull request merged**
