### PR TITLE
Add CommonTests and CommonTestsGUI to travis

### PR DESCRIPTION
**Pull request by scztt**

### CODE REVIEW

**Comment by crucialfelix** [comment]
qpm !   So what does the proto do ? Would we have to define what tests are included ?

**Comment by scztt** [comment]
@crucialfelix - You can run tests and test suites via e.g. ```qpm test.run "*:*"```,  ```qpm test.run "MyClass:*"```, ```qpm test.run "Server:boot_test"``` also. A json test plan gives us something in the repo to change and track, and a place to notate tests disabled due to bugs (plus a nice workflow: when you check in a fix, you remove the exception from the json file). In an ideal world, the json could eventually be boiled down to this (basically: run everything):
```
{ tests: [{ "suite": "*", "test":"*" }] }
```

**Comment by scztt** [comment]
(I don't know why this was set to "in progress", its ready to go if ppl feel like they want it in)

**Comment by crucialfelix** [comment]
that "in progress" is some of your travis magic, no ?

I want to take the time to understand everything you did, then I'll be
happy to merge it.
do the gui tests really run ? (sorry for naïve questions, very busy coding
today and haven't had a chance to look at it)

On Thu, Apr 14, 2016 at 6:50 PM scztt <notifications@github.com> wrote:

> (I don't know why this was set to "in progress", its ready to go if ppl
> feel like they want it in)
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/supercollider/supercollider/pull/1967#issuecomment-210045466>
>
-- 
https://twitter.com/crucialfelix
https://medium.com/@crucialfelix
http://www.mattermind.com/

**Comment by scztt** [comment]
np, please take your time. Yes, GUI tests run and work. On mac, the travis instance has a proper window server. On linux, we use: https://github.com/scztt/qpm/blob/qpm-unit/qpm/sclang_process.py#L139 (I believe travis has been using that for a while to do the existing launch/smoke test).

**Comment by crucialfelix** [comment]
We can document how to add tests on the wiki. 

Eventually we can figure out how to have it automatically detect them.

so `qpm test.run "*:*"` is one way to run tests. and the old way works still.

document how to install `qpm` too please.

**Comment by crucialfelix** [comment]
yay ! https://travis-ci.org/supercollider/supercollider/jobs/128653007#L6097 @scztt

**Pull request merged**
