### PR TITLE
build: fix an integer type mismatch that caused build fail for some

### LINKED ISSUE #1797: sclang compilation error in Linux
As before, I'm running Ubuntu Studio 14.04.3 LTS with gcc 4.8.4-2ubuntu1~14.04 and boost 1.55. Latest master fails with the following error:

    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp: In function ‘size_t fillClassRow(const PyrClass*, PyrMethod**, boost::executors::basic_thread_pool&)’:
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1388:62: error: no matching function for call to ‘irange(long unsigned int, size_t&)’
         for( int subClassIndex : boost::irange(0UL, numSubclasses) )
                                                                  ^
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1388:62: note: candidates are:
    In file included from /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:43:0:
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:208:5: note: template<class Integer> boost::integer_range<Integer> boost::irange(Integer, Integer)
         irange(Integer first, Integer last)
         ^
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:208:5: note:   template argument deduction/substitution failed:
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1388:62: note:   deduced conflicting types for parameter ‘Integer’ (‘long unsigned int’ and ‘unsigned int’)
         for( int subClassIndex : boost::irange(0UL, numSubclasses) )
                                                                  ^
    In file included from /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:43:0:
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:216:9: note: template<class Integer, class StepSize> boost::strided_integer_range<Integer> boost::irange(Integer, Integer, StepSize)
             irange(Integer first, Integer last, StepSize step_size)
             ^
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:216:9: note:   template argument deduction/substitution failed:
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1388:62: note:   deduced conflicting types for parameter ‘Integer’ (‘long unsigned int’ and ‘unsigned int’)
         for( int subClassIndex : boost::irange(0UL, numSubclasses) )
                                                                  ^
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1394:62: error: no matching function for call to ‘irange(long unsigned int, size_t&)’
         for( int subClassIndex : boost::irange(1UL, numSubclasses) ) {
                                                                  ^
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1394:62: note: candidates are:
    In file included from /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:43:0:
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:208:5: note: template<class Integer> boost::integer_range<Integer> boost::irange(Integer, Integer)
         irange(Integer first, Integer last)
         ^
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:208:5: note:   template argument deduction/substitution failed:
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1394:62: note:   deduced conflicting types for parameter ‘Integer’ (‘long unsigned int’ and ‘unsigned int’)
         for( int subClassIndex : boost::irange(1UL, numSubclasses) ) {
                                                                  ^
    In file included from /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:43:0:
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:216:9: note: template<class Integer, class StepSize> boost::strided_integer_range<Integer> boost::irange(Integer, Integer, StepSize)
             irange(Integer first, Integer last, StepSize step_size)
             ^
    /home/nathan/src/supercollider/external_libraries/boost/boost/range/irange.hpp:216:9: note:   template argument deduction/substitution failed:
    /home/nathan/src/supercollider/lang/LangSource/PyrObject.cpp:1394:62: note:   deduced conflicting types for parameter ‘Integer’ (‘long unsigned int’ and ‘unsigned int’)
         for( int subClassIndex : boost::irange(1UL, numSubclasses) ) {
                                                                  ^
    make[2]: *** [lang/CMakeFiles/libsclang.dir/LangSource/PyrObject.cpp.o] Error 1
    make[1]: *** [lang/CMakeFiles/libsclang.dir/all] Error 2
    make: *** [all] Error 2

Is my Boost version too old, maybe?

### PR DESCRIPTION
**Pull request by danstowell**
Fixes #1797 

Note: this NEEDS TESTING because the build fail doesn't happen on my system. Someone who has problem #1797 needs to confirm that this fixes it.

### CODE REVIEW

**Comment by redFrik** [comment]
thanks.  i can confirm that this fixes #1797 and sc is now compiling on a raspberry pi 2 under raspbian jessie (was broken before).  and the resulting app seems fine (although didn't test it much).

**Comment by crucialfelix** [comment]
If this is a build failure then it should go into 3.7.0

it would be merged into master after the release is out.

maybe the commit (not the PR) can be merged into both. cherry pick it into 3.7.0

**Comment by danstowell** [comment]
@crucialfelix it's a build failure in some code that Tim put in master only, so the fix goes in master only.

**Comment by crucialfelix** [comment]
oh right. sorry. good morning !! I'll make the coffee now

**Comment by danstowell** [comment]
No problem, thanks for the vigilance!

**Pull request merged**
