### PR TITLE
uiugens: correctly terminate input threads

### PR DESCRIPTION
**Pull request by timblechmann**
fixes potential crash on exit

### CODE REVIEW

**Comment by bagong** [comment]
This is for Windows, right? Any chance to rebase it on 3.7?

**Comment by timblechmann** [comment]
it potentially crashes on all platforms.

**Comment by bagong** [comment]
I cherry-picked it to 3.7, went fine, there seems to be no dependency on master. Why should this not go in 3.7?

**Comment by danstowell** [comment]
3.7 is supposed to be freezing for release - it's the kind of change that could well set the release calendar back. IMHO much better is to put it in master, release 3.7.0, and consider at leisure whether it should go in 3.7.1. There will always be bugfixes, and they will often look important

**Pull request merged**
