### PR TITLE
Fix Server volume and mute after reboot

### LINKED ISSUE #3105: Server's volume SynthDef 'volumeAmpControl2' not found after reboot
The server's volume control breaks after reboot if the volume was previously changed. There was some discussion in #2918 . A similar issue was apparently fixed (see #393).

### Reproducer
```supercollider
s.boot;

// set volume to -20 db
s.volume = 0.1.ampdb;

// make sound 
{SinOsc.ar}.play;

// quit and reboot server
s.quit;
s.boot;

// notice the error message: 
// *** ERROR: SynthDef volumeAmpControl2 not found
// FAILURE IN SERVER /s_new SynthDef not found
// the indicator on the bottom right says -20db

// setting volume gives error
s.volume = 0.1.ampdb;

// make sound (not-20db but 0db) 
{SinOsc.ar}.play;

// Cmd-Period

// make sound again (now -20db) 
{SinOsc.ar}.play;
```

### PR DESCRIPTION
**Pull request by patrickdupuis**
This PR is an attempt to fix #3105  & #3110. 

### Description
The problem is that, on reboot, `ServerTree` calls its `updateFunc` (it was added the first time the server booted) before `ServerBoot`'s `initFunc` is done sending the SynthDef. This causes the "SynthDef not found" error.

### Changes proposed
The fix remove the `updateFunc` from `ServerTree` when the server quits. That way, on reboot, `ServerTree` has nothing to call. When `initFunc` is finished sending the SynthDef, `updateFunc` gets added to `ServerTree`. 

Also, `this.updateSynth` needs to be called at the end of `sendSynthDef` so that the volume synth gets created, if necessary.

This change also makes `Server.quit` call `Volume.free`.

### CODE REVIEW

**Comment by patrickdupuis** [comment]
### Test
```supercollider
s.volume.volume = -36;
s.boot;
s.queryAllNodes;
/* should see this (if you have 2 outputs)
NODE TREE Group 0
   1 group
   1000 volumeAmpControl2
*/

s.quit;
s.boot;
s.queryAllNodes;
/* should see this (if you have 2 outputs)
NODE TREE Group 0
   1 group
   1000 volumeAmpControl2
*/
a = {SinOsc.ar}.play; // should play at -36db 
a.free;

s.mute;
s.quit;
s.boot;
a = {SinOsc.ar}.play; // no sound, server muted 
s.unmute; // should play at -36db
a.free;

s.quit;
s.options.numOutputBusChannels = 4;
s.boot;
s.queryAllNodes;
/* should see:
NODE TREE Group 0
   1 group
   1000 volumeAmpControl4
*/
```

**Comment by LFSaw** [comment]
are you still doing something here, @patrickdupuis, or is this ready for review?

**Comment by patrickdupuis** [comment]
Yes - it's ready for review 👍

**Comment by patrickdupuis** [comment]
I just messed up this entire PR

**Comment by patrickdupuis** [comment]
see #3125

**Pull request closed without merging**
