### PR TITLE
help: Remove some outdated GUI info

### PR DESCRIPTION
**Pull request by snappizz**
With an emphasis on debunking the suggestion to subclass UserView.

I removed a large section of the GUI intro file. It should be reinstated to demonstrate how to correctly compose a UserView, but I would rather have missing docs than misleading docs.

### CODE REVIEW

**Comment by crucialfelix** [comment]
SCViewHolder is not deprecated at all. It's the parent class for ObjectGui and for every Gui class in crucial-library.  There are other libraries also using it as a parent class.

It is used for simple composition. In those cases the view is usually a composite view or a flow view that the views are laid onto. It is precisely designed for making user views.

There is no reason to deprecate it.  

It is misnamed and should now just be ViewHolder. But that's a separate and minor issue.

**Comment by jamshark70** [comment]
> It is misnamed and should now just be ViewHolder. But that's a separate and minor issue.

The major issue about that is: renaming it would break code :(

Otherwise, yes... it doesn't make sense to suggest that SCViewHolder is deprecated in a PR that is about avoiding UserView subclassing... because SCViewHolder is the best way to accomplish the goal of avoiding UserView subclassing.

**Comment by crucialfelix** [comment]
it can be renamed and then an empty subclass of it called SCViewHolder can be added, to be deprec in 3.10

**Comment by snappizz** [comment]
Ok, the changes to SCViewHolder have been reverted.

**Comment by crucialfelix** [comment]
Thanks

**Pull request merged**
