### PR TITLE
(bad) boost: import boost-1.63, update boost.sync

### PR DESCRIPTION
**Pull request by brianlheim**
## Summary

Ran external_libraries/extract_boost.sh on the most recent release, 1.63.0.

Updated boost.sync with the latest changes from their develop branch.

Added README_BOOST.md which explains how to use extract_boost and how to maintain the boost packaging in SC.

## Testing

This builds fine on macOS (AppleClang 8.0); now we need to do the slog work of figuring out whether patches are needed for other compilers.

## Other info

Some patches that have worked for previous versions of boost are noted in #2301.

As a side note, I noticed that some boost files (those in boost.interprocess and boost.iostreams) changed permissions modes:
- boost.interprocess headers went from being non-executable to executable
- boost.iostreams headers went from non-exec to exec

This isn't an issue, is it?

## TODO

- [x] Target easy fixes for deprecation warnings (these can be made in a separate PR)
- [x] Apply past fixes to header files where appropriate (ID'd [here](https://github.com/supercollider/supercollider/pull/2772#issuecomment-284250134))
- [x] Leave a note for future developers that explains what custom changes we've made to the boost headers

### CODE REVIEW

**Comment by brianlheim** [comment]
FYI @bagong, I'm currently running an MSYS/gcc 6.3 build. Since you have the VS2015 setup already, I'd really appreciate if you could give that a whirl!

**Comment by bagong** [comment]
Sure, I am on my way...
If you rebuild, btw, you might get an error related to the symlinking of class-files etc. I've got a fix for that locally, I'll push it soon...
Best
.r.

**Comment by vivid-synth** [comment]
Note the patches in https://github.com/supercollider/supercollider/issues/2301 are just a few I've come across: my guess is there are lots that aren't listed there (and will cause subtle regressions if we don't patch them)

**Comment by brianlheim** [comment]
`git log external_libraries/boost`

I've already run into the issue fixed by #2473. Currently testing on a new branch to make sure it will work. BTW, I'm getting tons of deprecation warnings; I think this PR should try to solve as many of those as possible.

**Comment by bagong** [comment]
#2473 seems to be a gcc but to be fixed in version 7!
VS 2013 is okay, others still pending...
I'll check that other patch. The conditions under which it is needed are not easy to reproduce.
I'll check the other build systems later tonight.

**Comment by brianlheim** [comment]
Commits that are not simple imports:

654dba4 "fix some clang++ compilation warnings"
28bb1c77 "sclang: class library compilation - parallelize method table compression"
a0c3799f (possibly)
a8265362 "lang: use platform-independent boost::thread"
19dab0ca "external libraries: boost.chrono fix"
124d7019 "external libraries: boost.lockfree - msvc compile fix"
88c5c008 "boost.lockfree - add read_available/write_available methods again"
7493ea56 "boost: fix build error with recent versions of glibc"
44474ae5 "boost: spsc_queue - merge fixes from boost trunk"
c8487f2c "minor tweaks to build scsynth" (-_-)
da3d7c89 & fea978c4 "compilation fixes for 128-bit values not supported"
0948b57d "update win32_api.hpp"
ed566e6c "boost: backport intrusive compile fix"
2103dd16 "boost: lockfree - use std::atomic backport fix from develop"
55974d73 "backport bug fix for boost.intrusive"
66543052 "Fix mingw gcc-6.2 ICE"
868febe3 "Fix problem with boost interprocess module on Win (#2457)"
920725349 "Merge #2473 - fix mingw gcc-6.2 ICE"

**Comment by brianlheim** [comment]
> #2473 seems to be a gcc but to be fixed in version 7!

Woah, that's news to me! Is there a discussion about this somewhere that I missed?

**Comment by bagong** [comment]
Google is your friend!

**Comment by brianlheim** [comment]
@bagong I already tried googling it, not sure what combination of magic words to use. Just post a link if you have it please.

Using the change from #2473, I am able to build with MSYS. I'm going through the commits I listed above to see if there's anything else we should be porting.

**Comment by bagong** [comment]
Ah good you say it... I was thinking of doing it. It'll be nice to have all changes in one commit!
As to the link, I don't have it any more, if I bump into it, I'll send it.

**Comment by brianlheim** [comment]
@vivid-synth I've updated [this comment](https://github.com/supercollider/supercollider/pull/2772#issuecomment-284250134) after reviewing all the changes that were made to boost and whether or not they are still relevant. Thanks for the suggestion! It looks like we have very little extra work to do. I think after we make the additional changes, I will add a note in the external_libraries folder to note what changes we had to retain.

**Comment by bagong** [comment]
Okay @brianlheim , looks very good! Don't apply patch from #2457! The behaviour is slightly better without the patch in 1.63.

All builds work: MinGW 4.8.2, MSYS2 (with gcc patch), VS 2013-32, VS 2015-64.

But I guess we'll have to repeat the procedure after you've prepared the ported patches...

**Comment by brianlheim** [comment]
Per @bagong's request, I will not be applying the patch from #2457 (see https://github.com/supercollider/supercollider/issues/2409#issuecomment-284258836).

**Comment by brianlheim** [comment]
All right, I've applied the changes and I think this is ready to test again. Does anyone disagree with my assessment of the old boost patches I noted above? Or have recommendations/opinions on the little readme I left?

**Comment by brianlheim** [comment]
This builds and runs on macOS 10.12 (AppleClang 8.0) and Windows 10 (GCC 6.3).

**Comment by brianlheim** [comment]
Here is the build error stream output generated now by building on Windows with MSYS/gcc-6.3:

https://gist.github.com/brianlheim/aa6c63f7117f5dfbc05bdd0f73b859c3

A couple notes:
- there are a lot of inter-boost warnings about conflicting definitions. I think there may be a missing/bad macro definition happening somewhere; I doubt that this is standard behavior.
- there are lots of deprecation warnings generated because boost.sync is not updated (#2459). this will be updated soon, there's nothing we can do about it in this PR
- there are lots of deprecation warnings now being generated by yaml-cpp. I think attempts have been made in the past to bring this library up to date (there was a big API change between the version we have, 0.3, and the current version, 0.5.3): https://github.com/supercollider/supercollider/pull/2142. I think we should do this; we may even be able to add it as a submodule.

**Comment by bagong** [comment]
Haha, so I've built in almost every imaginable way on Windows now, including the MinGW4.8.2-native, MSYS2-32, VS2015 release and debug. I also did a few sc3-plugins builds. All looks great. This is the smoothest boost update ever!

PS: I also did try updated boost.sync on VS2015, and it's fine. Deprecation warnings gone and no problems detected. I can do a PR for it, or are you about to do it, @brianlheim?

As to yaml: yes, Lucas mentioned that as a potential problem causer for the lexer when he was trying to get Win64 working. So this sounds like something you really want for your stuff. Tim's PR is closed, but he offered somewhere to use it, if I am not mistaken.

**Comment by brianlheim** [comment]
@bagong Awesome, thank you so much!

Re: boost.sync, I have a branch for it already :) . I was waiting for this to merge before making a PR as there's no point in testing against the pre-1.63 headers.

This is a kind of big update; should I notify the dev list and/or wait awhile before merging?

**Comment by bagong** [comment]
Hahaha, there used to be very little discussion about boot updates, except me complaining about Windows problems. But yea, asking and then acting after about two days if you get no reaction seems nice.
How about adding the boost.sync PR to this PR. Then we have only one discussion...

**Comment by brianlheim** [comment]
> boot updates

http://www.bitrebels.com/wp-content/uploads/2013/06/high-tech-rain-boots-1.jpg

> How about adding the boost.sync PR to this PR

Sure, I consider it a separate lib, but keeping the discussion in one place is a big plus :)

**Comment by bagong** [comment]
If you add it, I can test them and the space-in-path stuff together...

**Comment by brianlheim** [comment]
Ok, I'll put it up soon! Sorry for the delay.

**Comment by bagong** [comment]
No worries! ;)

**Comment by brianlheim** [comment]
Ok, ready now @bagong.

**Comment by bagong** [comment]
Fab! Thank you!

**Comment by vivid-synth** [comment]
Has the directory structure changed here? I'm trying to see a diff but it's 700,000 additions and deletions...

**Comment by brianlheim** [comment]
@vivid-synth Nope, almost all of it is file modifications.

There were a lot of files changed:

```sh
$ git show --name-status topic/boost-1.63@{5} | wc -l
3718
```

**Comment by brianlheim** [comment]
D'oh, just realized GH already tells you how many files are changed in a PR. Apologies, I'm very tired tonight.

**Comment by brianlheim** [comment]
OK _wow_ I was using the CRLF line-terminated version of Boost. That's why there were so many changes. (Hopefully) never making that mistake again.

**Comment by bagong** [comment]
Rather than reassembling, it might be possible to have git convert them. Git has three modes of dealing with this linebreak-difference between Windows and the rest, one of them is check out as is, commit unixy...

http://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings

https://help.github.com/articles/dealing-with-line-endings/

**Comment by brianlheim** [comment]
Closing (#2787)

**Pull request closed without merging**
