### PR TITLE
Cmake change for WinHelp and LICENSE.txt

### PR DESCRIPTION
**Pull request by bagong**
Two little changes:
- makes Help work on Windows (tested on Windows and crosschecked on Mac) - looks strange but the previous one didn't work
- should rename COPYING to LICENSE.txt on all platforms (tested on Mac and Windows)

### CODE REVIEW

**Comment by danstowell** [comment]
@bagong the name COPYING is standard practice (recommended in [GNU Coding Standards](https://www.gnu.org/prep/standards/standards.html#Releases)). I would say this definitely shouldn't change on linux. On other platforms, what's your motivation?

**Comment by bagong** [comment]
Oh, I didn't know that. Chris mentioned on the mailing list it should probably be renamed (implying OSX), and on Windows there was a statement in platform/windows that actually renamed it. So I thought it would be simpler to do it in one place. I personally wouldn't ever expect a license text to be called copying, but I am happy to change it in any way preferred. My main intention here is get Windows help working.

**Comment by danstowell** [comment]
No problem. I'd suggest leave the linux version so it doesn't rename, and do your copy-with-rename for win+mac if that's what people want.

**Comment by crucialfelix** [comment]
ok sure enough, Richard Stallman declares:

   - a reference to the file which contains the copying conditions. The GNU
   GPL, if used, should be in a file called COPYING. If the GNU LGPL is
   used, it should be in a file called COPYING.LESSER.

I guess it should stay as that.

**Comment by bagong** [comment]
so COPYING for all three platforms?

**Comment by bagong** [comment]
So I reverted to COPYING for Linux and OS X. I kept LICENSE.txt on Windows, because Win is probably the platform where users have the biggest difficulties opening an extensionless file. But I can change it there too, if wished.

**Comment by bagong** [comment]
Superseded by https://github.com/supercollider/supercollider/pull/1387

**Pull request closed without merging**
