### PR TITLE
Fix a maths bug in expexp() in MiscInlineMath.h

### PR DESCRIPTION
**Pull request by markwheeler**
This is to fix the issue described in #3784

### CODE REVIEW

**Comment by telephon** [comment]
... or rather `) / (`   !

**Comment by snappizz** [comment]
motion to make `)/(` the new SC mascot. it's an emoticon symbolizing a 17-year cicada, the bug that emerges after years of lurking underground

**Comment by telephon** [comment]
and what about the unit test!?! )/(

**Comment by telephon** [comment]
It seems to me though as if this primitve has never been in use anywhere. The code in use constructs the formula correctly in sclang:

```supercollider
(
var old, new, used;
old = { |x, a, b, c, d|
	block { |return|
		if (x <= a) { return.(c) };
		if (x <= a) { return.(c) };
		if (x >= b) { return.(d) };
		if (x >= b) { return.(d) };
		return.(pow(d/c, log(x/a)) / (log(b/a)) * c)
	}
};

new = { |x, a, b, c, d|
	block { |return|
		if (x <= a) { return.(c) };
		if (x <= a) { return.(c) };
		if (x >= b) { return.(d) };
		if (x >= b) { return.(d) };
		return.(pow(d/c, log(x/a) / log(b/a)) * c)
	}
};

used = { |x, a, b, c, d|
	x.expexp(a, b, c, d)
};

k = { |x|
	[old, new, used].collect { |each| each.(x, 1, 100, 5, 20)  }
}
)


(1..100).collect(k).flop.plot
```

**Comment by brianlheim** [comment]
> It seems to me though as if this primitve has never been in use anywhere. The code in use constructs the formula correctly in sclang:

This is correct; a quick series of greps confirms it. If we had asked for unit tests in this PR (which should have happened AFAIC) it would have become immediately apparent, since there is no way to actually test this code. In fact I think this file can be removed entirely, since (1) none of the inline functions are used in the project and (2) the declarations can be moved to more appropriate headers if necessary.

**Comment by telephon** [comment]
the question is why we shouldn't just use them? 

Probably the answer is that the sclang support for nary operators that automatically choose the correct versions doesn't exist yet (see the discussion on the new boost math operators). NOt sure if we shouldn't just leave it in for that end.

**Pull request merged**
