### PR TITLE
Topic/mention default clock for s.waitForBoot and s.doWhenBooted

### PR DESCRIPTION
**Pull request by prko**
## Purpose and Motivation

https://scsynth.org/t/the-clock-of-s-waitforboot-and-s-dowhenbooted/8793?u=prko

## Types of changes

- Documentation

## To-do list

- [x] Updated documentation
- [x] This PR is ready for review

I am not sure about the clock for "onFailure" because I have not encountered it. I often experience `Server 'localhost' exited with exit code 0.`, but cannot remember the "onFailure" function being evaluated.

### CODE REVIEW

**Comment by cdbzb** [comment]
...but `waitForBoot` calls `doWhenBooted` which then calls `ServerStatus:doWhenBooted`  which returns a `Routine` which plays in the `AppClock` 

https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Control/ServerStatus.sc#L51-L85

**Comment by prko** [comment]
> ...but `waitForBoot` calls `doWhenBooted` which then calls `ServerStatus:doWhenBooted` which returns a `Routine` which plays in the `AppClock` !
> 
> https://github.com/supercollider/supercollider/blob/develop/SCClassLibrary/Common/Control/ServerStatus.sc#L51-L85

Yes! 
Sorry about that. It is a typo. In my thread on the forum,
> ## Purpose and Motivation
> https://scsynth.org/t/the-clock-of-s-waitforboot-and-s-dowhenbooted/8793?u=prko

I wrote as follows:
> However, there seems to be no mention of the default clocks for s.waitForBoot and s.doWhenBooted in the help document. I think AppClock is the clock for both. 

I have corrected this.

I did not know about `ServerStatusWatcher.doWhenBooted`. I added it, but I am not sure if adding this section is appropriate.

and..., please let me know the wrong English expression. I am not happy with using the plural form of AppClock...

**Comment by cdbzb** [comment]
there's only one `AppClock` !

**Comment by prko** [comment]
> there's only one `AppClock` !

Thanks! Done!

**Comment by prko** [comment]
Suddenly the following idea came to mind:
How about adding the fourth argument to `Server:waitForBoot`, `Server:doWhenBooted`, and `ServerStatusWatcher:doWhenBooted`? 
Here is the sketch with the successful test code:
https://scsynth.org/t/the-clock-of-s-waitforboot-and-s-dowhenbooted/8793/28?u=prko

**Comment by prko** [comment]
I think it is better to close this PR and make the following PR:
https://github.com/supercollider/supercollider/pull/6198

**Pull request closed without merging**
