### PR TITLE
Topic/update lang terminology

### PR DESCRIPTION
**Pull request by muellmusik**
Here's a start on addressing point 3 in #5251 (RFC 10). A couple of notes:

Re: Master there are a few remaining instances:
- In Quarks references to the master branch. This change should be made in conjunction with changes to the project. Left for the moment in the hopes that someone more git-capable than me will take that on as part of this. Can add a comment for now if that seems likely to take a while.
- One use of the word mastering. AFAICS that usage wasn't specifically singled out as problematic in the RFC. Don't mind either way myself, so make a suggestion if you'd like it changed.
- One reference to a Thrustmaster gamepad. I replaced another reference to this, but as this was an example, I was afraid of breaking something. I don't use HID a lot, so erred on the side of caution, but if we do want to change this, perhaps somebody can post some alternative code with a different device.
- A reference to drunken master. As this seems clearly to be a reference to kung fu films, I wasn't sure how to change it.

Re: Gendered pronouns
- I left a few hes in that referred to specific people, as I didn't think it was appropriate making decisions about people's pronouns without knowing their preferences. I was not able to find specific information on two of them, but other evidence (their bios, etc.) seemed to indicate the preference of he. We can write and ask if someone feels strongly about this. One reference to Bela Bartok I have left as he.

## Types of changes

- Documentation
- Terminology

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

### CODE REVIEW

**Comment by muellmusik** [comment]
The failure here on one of the Linux builds seems to be with an unavailable dependency, so not related to the PR.

**Comment by brianlheim** [comment]
thanks!

> In Quarks references to the master branch. This change should be made in conjunction with changes to the project. Left for the moment in the hopes that someone more git-capable than me will take that on as part of this. Can add a comment for now if that seems likely to take a while.

we have a ticket for it that needs discussion still (#5096), so good to leave it out of this i think.

> One use of the word mastering. AFAICS that usage wasn't specifically singled out as problematic in the RFC. Don't mind either way myself, so make a suggestion if you'd like it changed.

i think it would be in the spirit of the RFC to change "crucial to mastering SC" to something like "crucial to effectively using [or working in] SC". colonizing/conquering metaphors in music abound, having one less probably won't hurt. :)

> A reference to drunken master. As this seems clearly to be a reference to kung fu films, I wasn't sure how to change it.

i never heard of the film and didn't get the reference. :) i don't have a problem with the word being used there, but maybe the comment could do a better job of explaining how the code snippet and the film are connected.

> I left a few hes in that referred to specific people, as I didn't think it was appropriate making decisions about people's pronouns without knowing their preferences. I was not able to find specific information on two of them, but other evidence (their bios, etc.) seemed to indicate the preference of he. We can write and ask if someone feels strongly about this. One reference to Bela Bartok I have left as he.

checking bios is due diligence IMO, thank you for the transparency.

there are two other gendered terms that i would love to see removed from this codebase, which are "poor man's X" and "Herstory". "loose approximation of X" or even "poor substitute for X" would be suitable replacements for the former. code examples using the latter can simply be rewritten to use a different term.

**Comment by muellmusik** [comment]
> "Herstory".

The one place I see this is in the History class, where it would seem to be an attempt to be inclusive. I know that ἱστορία is not really gendered (actually fem grammatically), but I've always found the History/Herstory thing kind of fun, and a useful reminder even if the issue isn't etymological. So I suggest either 'Theirstory/they' in a similarly playful vain, or a mix there? (I think that would work in that example.) What do you think?

**Comment by muellmusik** [comment]
Sorry, btw for some reason I thought you'd asked for only lang and help. (Though I wasn't sure why! ;-) I'll look at C++ now where I know there are more.

**Comment by muellmusik** [comment]
Okay, I think remaining instances beyond those in discussion above are all boost or portaudio. If there's anything else let me know and I can chase it up.

**Comment by brianlheim** [comment]
> The one place I see this is in the History class, where it would seem to be an attempt to be inclusive. I know that ἱστορία is not really gendered (actually fem grammatically), but I've always found the History/Herstory thing kind of fun, and a useful reminder even if the issue isn't etymological.

much like the constructions "he or she" and "ladies and gentlemen", the idea of "herstory" as the dual of "history" is exclusionary of many queer people.

> So I suggest either 'Theirstory/they' in a similarly playful vain, or a mix there? (I think that would work in that example.) What do you think?

i would recommend to choose a gender neutral term which is already in common use. the purpose of technical documentation should be to illustrate the use of SC's features clearly and concisely. moreover, since public discourse and understanding of gender is always evolving, any term chosen for its gender-political implications runs the risk of becoming outmoded or even offensive to some later on. for instance the re-spelling of "women" as "womyn" was generally seen as progressive during second-wave feminism, but is now increasingly associated with trans-exclusive feminist groups (https://www.dailydot.com/irl/womyn/).

**Comment by dyfer** [comment]
Thank you for working on this.

I just wanted to add my 2c re "mastering": one of the definitions of the word "master" is "A skilled practitioner of a particular art or activity" [[1](https://www.lexico.com/en/definition/master)] I thought the word "mastering" (as used in "mastering SC") comes solely from that meaning. 
I know that it is an ongoing discussion on which terms are considered offensive, but I was wondering if there are any external resources that would help to put this in context and provide a reference for making specific decisions about these (important!) changes.

**Comment by brianlheim** [comment]
> I was wondering if there are any external resources that would help to put this in context and provide a reference for making specific decisions about these (important!) changes.

i don't think such a thing is likely to exist. but if there is an issue you have with this particular change, we can discuss it.

**Comment by muellmusik** [comment]
> i would recommend to choose a gender neutral term which is already in common use. the purpose of technical documentation should be to illustrate the use of SC's features clearly and concisely. moreover, since public discourse and understanding of gender is always evolving, any term chosen for its gender-political implications runs the risk of becoming outmoded or even offensive to some later on. for instance the re-spelling of "women" as "womyn" was generally seen as progressive during second-wave feminism, but is now increasingly associated with trans-exclusive feminist groups (https://www.dailydot.com/irl/womyn/).

Fair enough, though the same may become true of 'they' as singular pronoun at some point. Hence my suggestion of Theirstory.

How about Ourstory? :-) Genderless and inclusive. Or maybe you'd like to suggest something specific for the example in question?

**Comment by dyfer** [comment]
> i don't think such a thing is likely to exist. but if there is an issue you have with this particular change, we can discuss it.

I wouldn't call it as strong as an "issue". I have expressed my understanding of the term and thus I don't think that term is offensive. But if others think it is, I'm not going to oppose this change. My view is also influenced by the fact that In my native language the term for "master" <of slaves> and "master" <in skill> are two completely different words with no relation to each other.

**Comment by brianlheim** [comment]
> Fair enough, though the same may become true of 'they' as singular pronoun at some point. Hence my suggestion of Theirstory.

i kinda doubt that the pronouns i use will "go out of style" anytime soon, although it's wholly possible that the anglosphere will eventually find some better compromise for an inclusive gender-neutral pronoun, in which case i would be in favor of switching over to that. i obviously can't speak for everyone, but i personally hope that the employment of "they" for playful and subversive effect (e.g. "theydies and gentlethems") will disappear as soon as possible, because i generally find it infantilizing and not respectful at all.

> How about Ourstory? :-) Genderless and inclusive. Or maybe you'd like to suggest something specific for the example in question?

i would suggest "archives", because it is a word that is accessible to a nonnative speaker and does not present a challenge to screen readers.

> I have expressed my understanding of the term and thus I don't think that term is offensive. But if others think it is, I'm not going to oppose this change.

to clarify, my reasoning is *not* "all forms of the word master are offensive". it is that "mastering" a skill or tool suggests an act of conquering and dominance and i just personally think the world, and the music world in particular, already has enough of that kind of language. it's a view that's specific to me and one that i understand i can't force other people to share. this is more related to this point from the RFC than anything else: "Authors should [...] reflect on their use of metaphors generally."

**Comment by dyfer** [comment]
> to clarify, my reasoning is _not_ "all forms of the word master are offensive". it is that "mastering" a skill or tool suggests an act of conquering and dominance 

Because of my dissociation between the two meanings of "master", for me the word "mastering" has no association with conquering and dominance, but purely with achieving high level of skillfulness... (i.e. "mastery"?). BUT I do see your point that this meaning might not be clear. In this case I'm not opposing this change.

**Comment by muellmusik** [comment]
@brianlheim:

> i kinda doubt that the pronouns i use will "go out of style" anytime soon, although it's wholly possible that the anglosphere will eventually find some better compromise for an inclusive gender-neutral pronoun, in which case i would be in favor of switching over to that

Well, that's what I meant. Usage changes. 'Herstory' for example was clearly meant well, and I don't think the authors could have easily predicted the evolution of that, though perhaps I'm wrong.

@dyfer:

> Because of my dissociation between the two meanings of "master", for me the word "mastering" has no association with conquering and dominance, but purely with achieving high level of skillfulness... (i.e. "mastery"?). BUT I do see your point that this meaning might not be clear. In this case I'm not opposing this change.

Your view is completely understandable, and I'm sympathetic to it. Mastering in my personal sensibility has a very different sense than master. But but but...

I think it's really important that we keep in mind that the point of this is not what any one of us as individuals finds okay or not, nor is it really about what the majority find okay. If it will bother anyone, it's at least worth discussing, and trying to accommodate that concern. Being inclusive costs us very little, and gains us a lot! :-)

**Comment by muellmusik** [comment]
> i would suggest "archives"

I went with 'they' and 'the story' as that seemed more in the spirit of the original. Archives seemed a little out of place. If you feel strongly, feel free to replace it.

**Comment by muellmusik** [comment]
Okay, that's everything I could think of to check. Let me know if anything else occurs and I can look at that too.

**Review by brianlheim — APPROVED** [review]
as people brought up before, one of the risks of this change is that by replacing one technical term with another, the meaning becomes less clear. i think the replacements you picked are appropriate and unambiguous. :) thanks!

**Comment by dyfer** [comment]
Thanks!

**Comment by telephon** [comment]
The change is fine. 

Just for completeness:
The (now) gendered "he"/"his" is of Germanic origin, while the word "history" is from Greek/Sankskrit. The two occurrences "his" just happen to be written with the same letters.

https://www.etymonline.com/word/history

>from historein "be witness or expert; give testimony, recount; find out, search, inquire," and histōr "knowing, expert; witness," both ultimately from PIE *wid-tor-, from root *weid- "to see," hence "to know."

**Comment by muellmusik** [comment]
Thanks @telephon. This is sort of the point I was trying to make about ἱστορία above.

**Comment by telephon** [comment]
Ah I completely overlooked it, sorry. Yes the wordplays. As long as everyone takes them as humor! I found it interesting to read that "his" and "he" were originally ungendered and used for things.

**Pull request merged**
