### PR TITLE
String/fix pr flat

### PR DESCRIPTION
**Pull request by iani**
## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation (no need to update - there is no change, just a fix
- [x] This PR is ready for review

### CODE REVIEW

**Comment by dyfer** [comment]
Hello @iani 
It seems that you've create this PR from a quite old develop branch. Would you mind updating your develop branch and rebasing?

**Comment by brianlheim** [comment]
see prior discussion at #2538

**Comment by iani** [comment]
Hello Marcin,

I had performed a fresh pull pff the develop branch and then made my own
branch off of that.
It is surprising to hear that this ended up on an older branch, but I will
check.
Thanks.

Iannis

**Comment by brianlheim** [comment]
this commit is not right: https://github.com/iani/supercollider/commit/fbe245b171dfd6755de5ab0310c0203df1ff1339

a rebase won't fix that. you need to update your develop branch so it's up to date with this repo and then create your new branch with the changes you want off that.

**Comment by iani** [comment]
Thank you, I will do that.

Iannis

**Comment by iani** [comment]
Hello,
I cloned a fresh copy of the repository and created a new pull request from
a branch on develop.
I hope that I created the branch on the right develop commit this time.
(Should I be updating my own fork on my github account before that?)

Regarding the discussion at #2538, it seemed to me to be more theoretical -
I could
not gather any practical consequences or implications from the discussion.
I cannot imagine a case where a String would be multichannel-expanded, so
I do not understand the discussion about not multichannel-expanding Strings.
In my case, I often send "flat" to arrays that contain strings and the
resulting character arrays
break the solution that I am trying to implement.

Thanks,
Iannis

**Pull request closed without merging**
