### PR TITLE
Remove boost_sync

### LINKED ISSUE #4914: boost/sync doesn't compile with latest boost (1.73.0)
Logging this before @dvzrv gets a chance :)

## Environment

* SuperCollider version: develop
* Operating system: arch linux

## Steps to reproduce

Tried compiling supercollider with the latest source release of boost (downloaded from the boost website, as it's not yet in arch's pacman repos).

## Expected vs. actual behavior

Use of BOOST_THROW_EXCEPTION_CURRENT_FUNCTION in boost/sync causes compilation to fail. I don't have a full error log, but the errors all centered around that macro, which appears to have been removed from boost recently.

## Possible & proposed solutions

after some analysis, i think the best way forward would be to remove boost::sync as a dependency and replace its usage with official boost objects. this is how i see it:
- patching boost.sync ourselves is a last resort
- using existing boost.sync with 1.73 is impossible
- using newer boost.sync with our current 1.66 doesn't work (i tried)
- finding a version of boost.sync that builds with 1.66 and 1.73 is just delaying the inevitable and also time consuming
- we don't want to bump boost in 3.11 branch from 1.66 to 1.73, because that could cause bugs and/or change behavior and we don't want to introduce instability to 3.11.x releases
- ~boost.sync is only used for its `semaphore`, which boost.interprocess contains since 1.66 in [interprocess_semaphore](https://www.boost.org/doc/libs/1_73_0/doc/html/boost/interprocess/interprocess_semaphore.html). i would wager they might even be the same implementation, since the interprocess header is under a directory called "sync".~
- ~so, porting over the boost sync code should be very easy and safe, even in 3.11. then both 3.11 and develop can build with a system boost at 1.73.0 if desired; and at the same time we manage to lose a dependency!~

### PR DESCRIPTION
**Pull request by brianlheim**
## Purpose and Motivation

Fixes #4914 (confirmed locally using the boost from the source release)

I know this looks like a big change, but see #4914 for my reasoning. This is actually quite safe in terms of the amount of code that had to be ported.

There was only one place where i had to make a substantial change, in PyrSched.cpp, and i confirmed locally with a test program that this works as expected.

## Types of changes

- Bug fix

## To-do list

- [x] Code is tested
- [x] All tests are passing
- [x] Updated documentation
- [x] This PR is ready for review

### CODE REVIEW

**Comment by brianlheim** [comment]
whoops, please wait to review, this has legitimate linting issues :) sorry

**Comment by timblechmann** [comment]
@brianlheim don't! semaphores in boost.interprocess and semaphores in boost.sync are two different beasts: interprocess semaphores are, well, interprocess and much slower that what is in boost.sync. if boost.sync doesn't build with 1.73, that has to be fixed (please file a bug report for boost.sync)

especially for supernova the semaphore performance is critical

**Comment by brianlheim** [comment]
oh, i see! would the [std::binary_semaphore](https://en.cppreference.com/w/cpp/thread/counting_semaphore) from c++20 be a suitable replacement in your opinion @timblechmann ? thanks for the warning, and sorry for my negligence here. apologies are also due to @dyfer then for my arrogance in assuming this was so cut-and-dry when we talked about it earlier.

i do think boost.sync -- at least, the latest version -- will build with 1.73; but, i'm not sure it will build with 1.66 that we package in 3.11, and i didn't bother to find out since it seemed easier to do this port. i'll do some more research.

**Comment by dyfer** [comment]
thanks @brianlheim and no worries! I'm glad someone with more expertise than me chimed in on the issue.

**Comment by timblechmann** [comment]
i hope that the c++20 semaphores (binary or counting) will have a good implementation, so they will probably be the way to go once they are widely available (macos for example has 3 different semaphore implementations, i hope the libc++ implementation will use dispatch semaphores rather than system v). in general i'd rather recommend updating boost and boost.sync to solve those build issues.

**Comment by brianlheim** [comment]
thanks! yes definitely, now that i know the boost.sync semaphores aren't available anywhere else i'll keep them around. i was happy to find that boost.sync is still being actively maintained

**Pull request closed without merging**
