### PR TITLE
Update scdoc.css (reupload of #3865)

### PR DESCRIPTION
**Pull request by prko**
respacing lines
resizing font size

I closed #3865 and deleted the branch. It has some problems.

This new PR seems to be ok!

### CODE REVIEW

**Comment by prko** [comment]
I found an ugly display case:
The .play method of Function class has too narrow argument name frame.
I could not fix it. Except for this one, I think my proposal is ok.

**Comment by prko** [comment]
it is not easy to choose one from the 'text-indent' and the combination of the 'margin-top' and the 'margin-bottom'.
The most help documents are not optimised to the 'text-indent' while the layout seems to be a bit confusing and nor clear when more than one lists are combined... 

The best solution for me would be inputting a special combination of characters and SCDoc interprets it as an indent. I do not know if it is possible.

Perhaps it is not needed for most sc-users.

**Comment by telephon** [comment]
The minimal font size is still rather large (sorry, I wanted to post a screenshot, but it seems github has a problem there).

**Comment by prko** [comment]
something went wrong: there was line conflict in the commit of yesterday.

I must re-upload again. sorry

**Comment by prko** [comment]
@telephon 
Are the sizes of fonts acceptable now?
Should I change other things?

**Comment by telephon** [comment]
This is how it looks:

screen shot 2018-07-22 at 20 57 48

I certainly don't want to be difficult, but to my eye, the fonts are out of proportion with each other (in particular because we can only zoom in, not out).

**Comment by prko** [comment]
In my computer, the last version looks as follows:
screenshot 2018-07-23 06 33 08

The font of the code editor and post window is monaco and its size is 16pt.

The following is the original scdoc.css:
screenshot 2018-07-23 06 27 06

**Comment by telephon** [comment]
Hm, strange. I tried a fresh recompile, but still. I also wonder why my build says "SuperCollider 3.9.3"

**Comment by prko** [comment]
I compiled [c6bb5ae6e] from the branch 'develop'
I followed the instruction as follows
https://github.com/supercollider/supercollider/blob/develop/README_MACOS.md

And then I pasted the scdoc.css in this pull request into
/SuperCollider.app/Contents/Resources/HelpSource/

**Comment by prko** [comment]
Hm, the scdoc.css in my branch is not the last version which I revised. 
How can I do it? Should I close this PR and create a new one?

**Comment by prko** [comment]
could you retry?
I copied the scdoc.css in this PR to my local branch on my laptop and published.
(I am not sure if I correctly did it)

**Comment by telephon** [comment]
OK, now it works. Sorry for the noise, probably I forgot to fetch.

**Comment by prko** [comment]
Thank you.
This was my first submission of a PR. I am sorry for my clumsiness in doing this.

**Comment by telephon** [comment]
It was entirely my fault. Thank you for this!

**Comment by prko** [comment]
thank you for merging this!

**Comment by telephon** [comment]
you are welcome :) !

**Pull request merged**
