### PR TITLE
scdoc: typo in Working_with_HID.schelp

### PR DESCRIPTION
**Pull request by redFrik**
changed External control -> External Control so that it ends up in the right scdoc category

### CODE REVIEW

**Comment by crucialfelix** [comment]
should've merged to 3.7

just remember that all these commits will not go in the release. they go out in the next patch release

**Comment by telephon** [comment]
Hm, ok so what is the workflow? We will need this in both 3.7 and master.

**Comment by danstowell** [comment]
I was wondering this too. Many of the 3.7 commits will want to go to master, if they're bugfixes (which presumably is the main thing the branch is taking at the moment). It seems felix has a plan. One approach could be to focus on polishing up the 3.7 release in the 3.7 branch, then once that's done have a big leisurely cherry-picking session to bring things from 3.7 to master (i.e. cherry-picking in the opposite direction from what was done in the past)...?

**Comment by crucialfelix** [comment]
How about this:

The only things that should go into 3.7.0 right now are the updates to the readme, install instructions, changelog.

Then its a beta; final check through spit and polish. Then its released.

Development work on 3.7.0 is finished.

After it is released it is merged back into master, bringing any of these minor commits with it.  

To do a 3.7.x release we checkout 3.7.(x-1) and branch from there. Make any bug fixes or cherry pick any recent commits into it. Merge to master, tag it, its released.

Really git flow is the best for this: https://www.atlassian.com/git/tutorials/comparing-workflows/feature-branch-workflow

I do all my projects using this system.

**Pull request merged**
