### PR TITLE
Cmake: search for UDEV_INCLUDE_DIR and UDEV_LIBRARIES

### PR DESCRIPTION
**Pull request by Dsm0**
## Purpose and Motivation

I couldn't build supercollider from source because of cmake errors finding `UDEV_INCLUDE_DIR` and `UDEV_LIBRARIES`.
After some digging, I discovered [this cmake file](https://github.com/FreeRDP/FreeRDP/blob/master/cmake/FindUDev.cmake) that found the paths that I needed.
I added a few lines to CMakeLists.txt, and everything worked.

## Types of changes

- New feature

## To-do list

- [ ] Code is tested
- [ ] All tests are passing
- [ ] Updated documentation
- [ ] This PR is ready for review

How rigorously should I test a change to the cmake directory search?
I'm unsure if this sort of change warrants substantial testing.

### CODE REVIEW

**Comment by dyfer** [comment]
Thanks @Dsm0 
I don't primarily work in Linux so I can't help reviewing the actual functionality - I'll let others more familiar with the matter look into this.

However, I think it would be good to remove commented out lines from this PR, as well as add guards so this check only happens on linux. Currently CI fails on macOS and Windows because of that.

**Comment by brianlheim** [comment]
hi @Dsm0 , can you share some details about what was going wrong before this change? were you by chance trying to build without hidapi support? what was the output from your build? i ask because the hidapi subproject already finds and links with libudev, so there may be a cleaner way to handle this dependency. it seems odd that only including the libudev header, but not linking, was enough to fix your build. maybe this is a problem with hidapi's cmake files.

**Comment by brianlheim** [comment]
i'm really sorry, but i don't think this is the correct approach and without more information and being unable to reproduce this on my own machine, i can't help. please feel free to share more information if you have it, but i am going to close this for now.

**Comment by samm81** [comment]
old, but if anyone else finds this issue, I was getting the following error:

```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
UDEV_INCLUDE_DIR
   used as include directory in directory /home/maynard/src/supercollider/external_libraries/hidapi/linux
   used as include directory in directory /home/maynard/src/supercollider/external_libraries/hidapi/linux
   used as include directory in directory /home/maynard/src/supercollider/external_libraries/hidapi/linux
   used as include directory in directory /home/maynard/src/supercollider/external_libraries/hidapi/linux
   used as include directory in directory /home/maynard/src/supercollider/external_libraries/hidapi/linux
   used as include directory in directory /home/maynard/src/supercollider/external_libraries/hidapi/linux
   used as include directory in directory /home/maynard/src/supercollider/external_libraries/hidapi/linux
   used as include directory in directory /home/maynard/src/supercollider/external_libraries/hidapi/linux
   used as include directory in directory /home/maynard/src/supercollider/external_libraries/hidapi/linux
   used as include directory in directory /home/maynard/src/supercollider/external_libraries/hidapi/linux
UDEV_LIBRARIES
    linked by target "hidapi" in directory /home/maynard/src/supercollider/external_libraries/hidapi/linux
```

this was because I hadn't installed the appropriate develop package for udev. I fixed this by installing `eudev-libudev-devel` on my system (void linux musl).

**Pull request closed without merging**
